### ISSUE TITLE
Update master list of dapps for Discover Dapps

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#1001]
We also need a list of dapps, categorised, with these fields:

Name, Description, URL, Category.

e.g name: "AirSwap", description: "Peer-to-Peer trading on Ethereum", url: "https://airswap.io", category: "Games"

**Comment by zhangzhongnan928** [comment]
https://hyperdragons.alfakingdom.com/
https://tenzorum.org/tenz_id/
https://gravity.cool/
https://mokens.io/
https://gitcoin.co/
https://axieinfinity.com/
https://mlbcryptobaseball.com
https://chickenhunt.io/
https://cryptocare.tech/adopt/cryptocare
https://kickback.events/
https://namebazaar.io/
https://uniswap.exchange/swap
https://superrare.co/
https://opensea.io
https://beta.cent.co/
https://dice2.win/
https://amberdata.io/
https://game.lordless.io/home
https://www.bancor.network
https://app.totle.com/
https://cryptocup.io/
https://dapp.dragonereum.io/
https://app.compound.finance/
https://www.stateofthedapps.com/
http://lasttrip.matrixdapp.com/
http://0x-instant-staging.s3-website-us-east-1.amazonaws.com/
https://secure.monitorchain.com/
https://www.expotrading.com/trade
https://radi.cards/cardshop
https://alphawallet.github.io/dude-where-is-my-dapp/
https://localethereum.com/
https://cdp.makerdao.com/
https://dai-bridge.poa.network/
https://www.augur.net/ipfs-redirect.html
https://app.veil.co/
https://www.smartdrops.io/
https://kyber.network/swap/eth_knc
https://indorse.io/
https://peepeth.com/welcome
https://tf.alphawallet.com/

I save first, will organise later.

**Comment by zhangzhongnan928** [comment]
Can we use their API to get the information quickly? @hboon 
StateofDapps API
>  main api endpoints:
> 
> https://api.stateofthedapps.com/dapps
> Optional query args:
> limit=50
> offset=0
> page=1
> platform=ethereum|eos|poa
> sort=new|most-viewed|hot|rank|rating|name|dau|mau|vol_7d|dev_30d|usd_value_7d
> order=asc|desc
> status=any
> category=games
> tags=a,b,c / tags[]=a&tags[]=b
> text=abc
> 
> https://api.stateofthedapps.com/dapps/<slug>
> 
> https://api.stateofthedapps.com/tags
> Optional query args:
> text=abc
> limit=12
> 
> https://api.stateofthedapps.com/categories
> 
> https://api.stateofthedapps.com/stats

**Comment by zhangzhongnan928** [comment]
https://docs.google.com/spreadsheets/d/1xKmpCA8Xt5ASiRWizZ59IBiNwjpsbmKn9KovTkI1f8Y/edit?usp=sharing

Please find the list @hboon

**Comment by hboon** [comment]
@zhangzhongnan928 got it. Thanks.

**Comment by sharonsylu** [comment]
Not a dApp, but a Migration Portal:  https://kyber.org/migrate

Background:  KIP6: a Kyber Token Upgrade

For KNC holders managing their own tokens on self-custodial wallets such as Alphawallet, they can connect to the Kyber Migration Portal to Alphawallet and convert to the new KNC token on their own. 

Old KNC token contract: 0xdd974d5c2e2928dea5f71b9825b8b646686bd200
New KNC token contract: 0xdeFA4e8a7bcBA345F687a2f1456F5Edd9CE97202
Migration ratio: 1:1 (1 old KNC will be migrated to 1 new ERC-20 KNC token)

Timeline: 
Migration began Tuesday 20 April 9pm SGT. 
Migration process has no hard deadline and is open-ended (as of writing). 
No rush to convert to the new KNC tokens.

More info: 
https://blog.kyber.network/knc-token-migration-guide-fda08bfe62c2
