### ISSUE TITLE
DApp Home Page

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/alpha-wallet-ios#1006]
![img_2795](https://user-images.githubusercontent.com/33795543/51361863-51f3cb00-1b0c-11e9-8865-b0d252c36531.PNG)
1. once enter this editing mode, cannot exit this mode unless clicking on a button with function.
need to have "click any blank place to exit editing mode" function 
2. need to be able to move the order of DApps, eg hold the DApp move it to change the order.
3. better have an extra re-confirmation for deleting a DApp from home page. I have mistakenly deleted several DApps, by mistakenly click the x.

![img_2794](https://user-images.githubusercontent.com/33795543/51362067-0beb3700-1b0d-11e9-8cc4-3ec971eb9655.jpg)

Chang "Add Bookmark" to "Add to My DApps"

**Comment by hboon** [comment]
- [ ] once enter this editing mode, cannot exit this mode unless clicking on a button with function.
need to have "click any blank place to exit editing mode" function
- [ ] need to be able to move the order of DApps, eg hold the DApp move it to change the order.
- [ ] better have an extra re-confirmation for deleting a DApp from home page. I have mistakenly deleted several DApps, by mistakenly click the x.

**Comment by hboon** [comment]
Limitation for re-ordering dapps once #1036 is merged: Can only re-order in MyDapps, not in the Dapp home screen.

Have added #1037 to re-order in Dapp home screen.
