### ISSUE TITLE
Display issue with ERC875 token from token factory, XML from Peter's Tool

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/alpha-wallet-ios#1046]
Check out the lasted reply
@James-Sangalli @lyhistory

**Comment by lyhistory** [comment]
just for your information, maybe it's client-side misinterpretation of the 32 bytes
refer to: https://github.com/AlphaWallet/contracts/commit/ec7f9444ba1454a32c3e445917595419f6a931c6
now the bytes arrangement is:
![image](https://user-images.githubusercontent.com/1522513/51616191-892b0780-1f64-11e9-9e0b-785239ef7d05.png)

**Comment by zhangzhongnan928** [comment]
<?xml version="1.0" encoding="UTF-8" standalone="no"?><tb:token xmlns:tb="http://attestation.id/ns/tbml" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://attestation.id/ns/tbml ../../tbml.xsd">
  <tb:contract id="holding_contract" type="holding">
    
    <tb:name xml:lang="ru">Ваучеры</tb:name>
    <tb:name xml:lang="en">Vouchers</tb:name>
    <tb:name xml:lang="zh">门票兑换券</tb:name>
    <tb:name xml:lang="es">Cupones</tb:name>
    <tb:name xml:lang="ru">Ваучеры</tb:name>
    <tb:interface>erc875</tb:interface>
  <tb:address network="3">0xB94ff9c08fE580c5A2967D9f62e55CdE16F8d6ce</tb:address></tb:contract>
  <tb:contract type="wallet">
    
    <tb:address network="1">0xdecafbaddecafbaddecafbaddecafbaddecafbad</tb:address>
    <tb:name>Starwood Preferred Guest</tb:name>
  </tb:contract>
  
  <tb:features>
    
    <tb:feature type="market-queue">
      <tb:include>valid</tb:include>
      <tb:exclude>invited</tb:exclude>
      <tb:exclude>discounted</tb:exclude>
      <tb:gateway>https://482kdh4npg.execute-api.ap-southeast-1.amazonaws.com/dev/</tb:gateway>
      <tb:message type="exclude" xml:lang="en">%name% can't be traded on the market</tb:message>
      <tb:message type="exclude" xml:lang="zh">%name% 不能再在市场上交易</tb:message>
      <tb:message type="include">Only %name% can be traded on the market</tb:message>
      <tb:message type="include">只有%name%才可以在市场上交易</tb:message>
    </tb:feature>
    <tb:feature type="market-contract">
      <tb:include>valid</tb:include>
      <tb:exclude>discounted</tb:exclude>
      <tb:exclude>invited</tb:exclude>
      
      <tb:address network="1">0xdecafbaddecafbaddecafbaddecafbaddecafbad</tb:address>
      <tb:message type="exclude" xml:lang="en">%name% can't be traded on the market</tb:message>
      <tb:message type="exclude" xml:lang="zh">%name% 不能再在市场上交易</tb:message>
      <tb:message type="include">Only %name% can be traded on the market</tb:message>
      <tb:message type="include">只有%name%才可以在市场上交易</tb:message>
    </tb:feature>
    <tb:feature type="magic-link">
      <tb:include>valid</tb:include>
      <tb:exclude>discounted</tb:exclude>
      <tb:prefix>https://app.awallet.io/</tb:prefix>
      <tb:message type="exclude" xml:lang="en">%name% can't be traded with MagicLink</tb:message>
      <tb:message type="include">Only %name% can be traded with MagicLink</tb:message>
      <tb:message type="exclude" xml:lang="zh">%name% 不能用MagicLink交易</tb:message>
      <tb:message type="include" xml:lang="zh">只有末到期的票才可以用MagicLink交易</tb:message>
    </tb:feature>
    <tb:feature type="transfer-link">
      <tb:exclude>discounted</tb:exclude>
      <tb:exclude>invited</tb:exclude>
      <tb:prefix>https://app.awallet.io/</tb:prefix>
      <tb:message type="exclude" xml:lang="en">%name% can't be traded on the market</tb:message>
      <tb:message type="exclude" xml:lang="zh">%name% 不能再在市场上交易</tb:message>
    </tb:feature>
    <tb:feature type="feemaster">
      <tb:exclude>expired</tb:exclude>
      <tb:feemaster>https://app.awallet.io:80/api/claimToken</tb:feemaster>
      <tb:message type="include" xml:lang="en">%name% can't be imported</tb:message>
      <tb:message type="include" xml:lang="zh">不能收下%name%</tb:message>
    </tb:feature>
    <tb:feature type="qr-redeem">
      <tb:include>valid</tb:include>
      <tb:redeem format="Aztec"/>
      <tb:message type="include" xml:lang="en">Only %name% can be redeemed for paper tickets</tb:message>
      <tb:message type="include" xml:lang="zh">只有%name%才可以兑换纸票</tb:message>
    </tb:feature>
    <tb:feature type="nfc-redeem">
      <tb:include>valid</tb:include>
      <tb:device>decafbaddecafbad</tb:device>
      <tb:message type="include" xml:lang="en">Only %name% can be redeemed for paper tickets</tb:message>
      <tb:message type="include" xml:lang="zh">只有%name%才可以兑换纸票</tb:message>
    </tb:feature>
  </tb:features>
  <tb:selections>
    <tb:selection id="discounted">
      <tb:name xml:lang="en">Discount Tickets</tb:name>
      <tb:name xml:lang="zh">打折票</tb:name>
      <tb:filter>(|category=打折票)(category=Discounted))</tb:filter>
    </tb:selection>
    <tb:selection id="invited">
      <tb:name xml:lang="en">Gift Ticket</tb:name>
      <tb:name xml:lang="zh">赠票</tb:name>
      <tb:filter>gifted</tb:filter>
    </tb:selection>
    <tb:selection id="valid">
      <tb:name xml:lang="en">Tickets not expired</tb:name>
      <tb:name xml:lang="zh">末到期票</tb:name>
      <tb:filter>!expired</tb:filter>
    </tb:selection>
    <tb:selection id="expired">
      <tb:name xml:lang="en">Expired Tickets</tb:name>
      <tb:name xml:lang="zh">已经过期的票</tb:name>
      <tb:filter>expired</tb:filter>
    </tb:selection>
  </tb:selections>
  <tb:grouping>
    <tb:group bitmask="FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF" name="default">
      <tb:consecutive_groups/>
    </tb:group>
  </tb:grouping>
  <tb:ordering>
    <tb:order bitmask="FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF" name="default">
      <tb:byName field="locality"/>
      <tb:byValue field="match"/>
      <tb:byValue field="number"/>
    </tb:order>
    <tb:order bitmask="FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF" name="concise">
      <tb:byValue field="match"/>
      <tb:byValue field="category"/>
      <tb:byValue field="number"/>
    </tb:order>
  </tb:ordering>

  
  <tb:attribute-types>
    <tb:attribute-type id="country" oid="2.5.4.7" syntax="1.3.6.1.4.1.1466.115.121.1.15">
      <tb:name xml:lang="en">Country</tb:name>
      <tb:name xml:lang="zh">国家</tb:name>
      <tb:origin as="utf8" bitmask="FFFF000000000000000000000000000000000000000000000000000000000000"/>
    </tb:attribute-type>
    <tb:attribute-type id="locality" oid="2.5.4.7" syntax="1.3.6.1.4.1.1466.115.121.1.15">
      <tb:name xml:lang="en">City</tb:name>
      <tb:name xml:lang="zh">城市</tb:name>
      <tb:origin contract="holding-contract">
        <tb:function name="getLocality">
          <tb:inputs>
            <tb:uint256 ref="tokenID"/>
          </tb:inputs>
        </tb:function>
      </tb:origin>
    </tb:attribute-type>
    <tb:attribute-type id="time" syntax="1.3.6.1.4.1.1466.115.121.1.24">
      <tb:name xml:lang="en">Time</tb:name>
      <tb:name xml:lang="zh">时间</tb:name>
      <tb:origin as="utf8" bitmask="0000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000000000000000000000"/>
    </tb:attribute-type>
    <tb:attribute-type id="numero" syntax="1.3.6.1.4.1.1466.115.121.1.27">
      <tb:name xml:lang="en">No</tb:name>
      <tb:name xml:lang="zh">票号</tb:name>
      <tb:origin as="unsigned" bitmask="000000000000000000000000000000000000000000FFFF000000000000000000"/>
    </tb:attribute-type>
    <tb:attribute-type id="category" syntax="1.3.6.1.4.1.1466.115.121.1.15">
      <tb:name xml:lang="en">Cat</tb:name>
      <tb:name xml:lang="zh">等级</tb:name>
      <tb:origin as="utf8" bitmask="0000000000000000000000000000000000000000000000FFFFFFFFFF00000000"/>
    </tb:attribute-type>
    <tb:attribute-type id="section" syntax="1.3.6.1.4.1.1466.115.121.1.15">
      <tb:name xml:lang="en">Section</tb:name>
      <tb:name xml:lang="zh">区号</tb:name>
      <tb:origin as="utf8" bitmask="00000000000000000000000000000000000000000000000000000000FFFFFFFF"/>
    </tb:attribute-type>
    <tb:attribute-type id="expired" syntax="1.3.6.1.4.1.1466.115.121.1.7"> 
      <tb:origin as="mapping" contract="holding-contract">
        <tb:function name="isExpired">
          <tb:inputs>
            <tb:uint256 ref="tokenID"/>
          </tb:inputs>
        </tb:function>
        <tb:mapping>
          <tb:option key="0">
            <tb:value>FALSE</tb:value>
          </tb:option>
          <tb:option key="1">
            <tb:value>TRUE</tb:value>
          </tb:option>
        </tb:mapping>
      </tb:origin>
    </tb:attribute-type>
    <tb:attribute-type as="utf8" id="street" syntax="1.3.6.1.4.1.1466.115.121.1.15"> 
      <tb:origin contract="holding-contract">
        <tb:function name="getStreet">
          <tb:inputs>
            <tb:uint256 ref="tokenID"/>
          </tb:inputs>
        </tb:function>
      </tb:origin>
    </tb:attribute-type>
    <tb:attribute-type as="utf8" id="building" syntax="1.3.6.1.4.1.1466.115.121.1.15"> 
      <tb:origin contract="holding-contract">
        <tb:function name="getBuildingName">
          <tb:inputs>
            <tb:uint256 ref="tokenID"/>
          </tb:inputs>
        </tb:function>
      </tb:origin>
    </tb:attribute-type>
    <tb:attribute-type as="utf8" id="state" syntax="1.3.6.1.4.1.1466.115.121.1.15"> 
      <tb:origin contract="holding-contract">
        <tb:function name="getState">
          <tb:inputs>
            <tb:uint256 ref="tokenID"/>
          </tb:inputs>
        </tb:function>
      </tb:origin>
    </tb:attribute-type>
  </tb:attribute-types>
</tb:token>

**Comment by zhangzhongnan928** [comment]
**Contract**: 0xa1F63bB16E0cCFcb7050b764651068290Fe12044

**Peter's tool setting**
<img width="1377" alt="screen shot 2019-01-25 at 7 24 29 pm" src="https://user-images.githubusercontent.com/33795543/51743187-e0e98000-20d6-11e9-810e-17bdb68fc2e4.png">

**Link from Peter's tool**
https://app.awallet.io/AgAAAABcUrF6ofY7sW4Mz8twULdkZRBoKQ_hIERKUDIwMjAwNzI0MDgyNzM4KzA4MDAAAQAAVklQAAAAMWKzwZtPtjyib1eznKF4zf7synzA1CxQVDnkLxT1UjqACRMFexbzlgsi6XumI2TZM1nWhEfon5cifjSkzrQ_7poc

**XML from Peter's tool**
`<?xml version="1.0" encoding="UTF-8" standalone="no"?><tb:token xmlns:tb="http://attestation.id/ns/tbml" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://attestation.id/ns/tbml ../../tbml.xsd">
  <tb:contract id="holding_contract" type="holding">
    
    <tb:name xml:lang="ru">Ваучеры</tb:name>
    <tb:name xml:lang="en">Vouchers</tb:name>
    <tb:name xml:lang="zh">门票兑换券</tb:name>
    <tb:name xml:lang="es">Cupones</tb:name>
    <tb:name xml:lang="ru">Ваучеры</tb:name>
    <tb:interface>erc875</tb:interface>
  <tb:address network="3">0xa1F63bB16E0cCFcb7050b764651068290Fe12044</tb:address></tb:contract>
  <tb:contract type="wallet">
    
    <tb:address network="1">0xdecafbaddecafbaddecafbaddecafbaddecafbad</tb:address>
    <tb:name>Starwood Preferred Guest</tb:name>
  </tb:contract>
  
  <tb:features>
    
    <tb:feature type="market-queue">
      <tb:include>valid</tb:include>
      <tb:exclude>invited</tb:exclude>
      <tb:exclude>discounted</tb:exclude>
      <tb:gateway>https://482kdh4npg.execute-api.ap-southeast-1.amazonaws.com/dev/</tb:gateway>
      <tb:message type="exclude" xml:lang="en">%name% can't be traded on the market</tb:message>
      <tb:message type="exclude" xml:lang="zh">%name% 不能再在市场上交易</tb:message>
      <tb:message type="include">Only %name% can be traded on the market</tb:message>
      <tb:message type="include">只有%name%才可以在市场上交易</tb:message>
    </tb:feature>
    <tb:feature type="market-contract">
      <tb:include>valid</tb:include>
      <tb:exclude>discounted</tb:exclude>
      <tb:exclude>invited</tb:exclude>
      
      <tb:address network="1">0xdecafbaddecafbaddecafbaddecafbaddecafbad</tb:address>
      <tb:message type="exclude" xml:lang="en">%name% can't be traded on the market</tb:message>
      <tb:message type="exclude" xml:lang="zh">%name% 不能再在市场上交易</tb:message>
      <tb:message type="include">Only %name% can be traded on the market</tb:message>
      <tb:message type="include">只有%name%才可以在市场上交易</tb:message>
    </tb:feature>
    <tb:feature type="magic-link">
      <tb:include>valid</tb:include>
      <tb:exclude>discounted</tb:exclude>
      <tb:prefix>https://app.awallet.io/</tb:prefix>
      <tb:message type="exclude" xml:lang="en">%name% can't be traded with MagicLink</tb:message>
      <tb:message type="include">Only %name% can be traded with MagicLink</tb:message>
      <tb:message type="exclude" xml:lang="zh">%name% 不能用MagicLink交易</tb:message>
      <tb:message type="include" xml:lang="zh">只有末到期的票才可以用MagicLink交易</tb:message>
    </tb:feature>
    <tb:feature type="transfer-link">
      <tb:exclude>discounted</tb:exclude>
      <tb:exclude>invited</tb:exclude>
      <tb:prefix>https://app.awallet.io/</tb:prefix>
      <tb:message type="exclude" xml:lang="en">%name% can't be traded on the market</tb:message>
      <tb:message type="exclude" xml:lang="zh">%name% 不能再在市场上交易</tb:message>
    </tb:feature>
    <tb:feature type="feemaster">
      <tb:exclude>expired</tb:exclude>
      <tb:feemaster>https://app.awallet.io:80/api/claimToken</tb:feemaster>
      <tb:message type="include" xml:lang="en">%name% can't be imported</tb:message>
      <tb:message type="include" xml:lang="zh">不能收下%name%</tb:message>
    </tb:feature>
    <tb:feature type="qr-redeem">
      <tb:include>valid</tb:include>
      <tb:redeem format="Aztec"/>
      <tb:message type="include" xml:lang="en">Only %name% can be redeemed for paper tickets</tb:message>
      <tb:message type="include" xml:lang="zh">只有%name%才可以兑换纸票</tb:message>
    </tb:feature>
    <tb:feature type="nfc-redeem">
      <tb:include>valid</tb:include>
      <tb:device>decafbaddecafbad</tb:device>
      <tb:message type="include" xml:lang="en">Only %name% can be redeemed for paper tickets</tb:message>
      <tb:message type="include" xml:lang="zh">只有%name%才可以兑换纸票</tb:message>
    </tb:feature>
  </tb:features>
  <tb:selections>
    <tb:selection id="discounted">
      <tb:name xml:lang="en">Discount Tickets</tb:name>
      <tb:name xml:lang="zh">打折票</tb:name>
      <tb:filter>(|category=打折票)(category=Discounted))</tb:filter>
    </tb:selection>
    <tb:selection id="invited">
      <tb:name xml:lang="en">Gift Ticket</tb:name>
      <tb:name xml:lang="zh">赠票</tb:name>
      <tb:filter>gifted</tb:filter>
    </tb:selection>
    <tb:selection id="valid">
      <tb:name xml:lang="en">Tickets not expired</tb:name>
      <tb:name xml:lang="zh">末到期票</tb:name>
      <tb:filter>!expired</tb:filter>
    </tb:selection>
    <tb:selection id="expired">
      <tb:name xml:lang="en">Expired Tickets</tb:name>
      <tb:name xml:lang="zh">已经过期的票</tb:name>
      <tb:filter>expired</tb:filter>
    </tb:selection>
  </tb:selections>
  <tb:grouping>
    <tb:group bitmask="FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF" name="default">
      <tb:consecutive_groups/>
    </tb:group>
  </tb:grouping>
  <tb:ordering>
    <tb:order bitmask="FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF" name="default">
      <tb:byName field="locality"/>
      <tb:byValue field="match"/>
      <tb:byValue field="number"/>
    </tb:order>
    <tb:order bitmask="FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF" name="concise">
      <tb:byValue field="match"/>
      <tb:byValue field="category"/>
      <tb:byValue field="number"/>
    </tb:order>
  </tb:ordering>

  
  <tb:attribute-types>
    <tb:attribute-type id="country" oid="2.5.4.7" syntax="1.3.6.1.4.1.1466.115.121.1.15">
      <tb:name xml:lang="en">Country</tb:name>
      <tb:name xml:lang="zh">国家</tb:name>
      <tb:origin as="utf8" bitmask="FFFF000000000000000000000000000000000000000000000000000000000000"/>
    </tb:attribute-type>
    <tb:attribute-type id="locality" oid="2.5.4.7" syntax="1.3.6.1.4.1.1466.115.121.1.15">
      <tb:name xml:lang="en">City</tb:name>
      <tb:name xml:lang="zh">城市</tb:name>
      <tb:origin contract="holding-contract">
        <tb:function name="getLocality">
          <tb:inputs>
            <tb:uint256 ref="tokenID"/>
          </tb:inputs>
        </tb:function>
      </tb:origin>
    </tb:attribute-type>
    <tb:attribute-type id="time" syntax="1.3.6.1.4.1.1466.115.121.1.24">
      <tb:name xml:lang="en">Time</tb:name>
      <tb:name xml:lang="zh">时间</tb:name>
      <tb:origin as="utf8" bitmask="0000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000000000000000000000"/>
    </tb:attribute-type>
    <tb:attribute-type id="numero" syntax="1.3.6.1.4.1.1466.115.121.1.27">
      <tb:name xml:lang="en">No</tb:name>
      <tb:name xml:lang="zh">票号</tb:name>
      <tb:origin as="unsigned" bitmask="000000000000000000000000000000000000000000FFFF000000000000000000"/>
    </tb:attribute-type>
    <tb:attribute-type id="category" syntax="1.3.6.1.4.1.1466.115.121.1.15">
      <tb:name xml:lang="en">Cat</tb:name>
      <tb:name xml:lang="zh">等级</tb:name>
      <tb:origin as="utf8" bitmask="0000000000000000000000000000000000000000000000FFFFFFFFFF00000000"/>
    </tb:attribute-type>
    <tb:attribute-type id="section" syntax="1.3.6.1.4.1.1466.115.121.1.15">
      <tb:name xml:lang="en">Section</tb:name>
      <tb:name xml:lang="zh">区号</tb:name>
      <tb:origin as="utf8" bitmask="00000000000000000000000000000000000000000000000000000000FFFFFFFF"/>
    </tb:attribute-type>
    <tb:attribute-type id="expired" syntax="1.3.6.1.4.1.1466.115.121.1.7"> 
      <tb:origin as="mapping" contract="holding-contract">
        <tb:function name="isExpired">
          <tb:inputs>
            <tb:uint256 ref="tokenID"/>
          </tb:inputs>
        </tb:function>
        <tb:mapping>
          <tb:option key="0">
            <tb:value>FALSE</tb:value>
          </tb:option>
          <tb:option key="1">
            <tb:value>TRUE</tb:value>
          </tb:option>
        </tb:mapping>
      </tb:origin>
    </tb:attribute-type>
    <tb:attribute-type as="utf8" id="street" syntax="1.3.6.1.4.1.1466.115.121.1.15"> 
      <tb:origin contract="holding-contract">
        <tb:function name="getStreet">
          <tb:inputs>
            <tb:uint256 ref="tokenID"/>
          </tb:inputs>
        </tb:function>
      </tb:origin>
    </tb:attribute-type>
    <tb:attribute-type as="utf8" id="building" syntax="1.3.6.1.4.1.1466.115.121.1.15"> 
      <tb:origin contract="holding-contract">
        <tb:function name="getBuildingName">
          <tb:inputs>
            <tb:uint256 ref="tokenID"/>
          </tb:inputs>
        </tb:function>
      </tb:origin>
    </tb:attribute-type>
    <tb:attribute-type as="utf8" id="state" syntax="1.3.6.1.4.1.1466.115.121.1.15"> 
      <tb:origin contract="holding-contract">
        <tb:function name="getState">
          <tb:inputs>
            <tb:uint256 ref="tokenID"/>
          </tb:inputs>
        </tb:function>
      </tb:origin>
    </tb:attribute-type>
  </tb:attribute-types>
</tb:token>
`
**Current display on iOS,**
![img_2902](https://user-images.githubusercontent.com/33795543/51743277-2017d100-20d7-11e9-89f1-ce0a793a45a9.PNG)

**It should be displayed as,**
![img_2902](https://user-images.githubusercontent.com/33795543/51743689-733e5380-20d8-11e9-8236-107e39c91476.PNG)

**Comment by James-Sangalli** [comment]
@colourful-land 

- Cat is supposed to be the title on the card
- Building/venue on the subtitle of the card
- Datetime on the third line down
- On click display the time and full location address

**Comment by James-Sangalli** [comment]
@hboon last I checked we were still using Binary time?

**Comment by zhangzhongnan928** [comment]
![6b3f4836-c586-4497-b1ba-7726e2703f2f](https://user-images.githubusercontent.com/33795543/51784226-7f7deb80-2180-11e9-8be9-243fe154820f.jpeg)
![88c0638b-ffd1-44c3-819b-dbe8f660f6ce](https://user-images.githubusercontent.com/33795543/51784227-80168200-2180-11e9-92bf-f51d21634e71.png)

@James-Sangalli Android cannot pick up the MagicLinks from Peter’s tool.

**Comment by hboon** [comment]
> @hboon last I checked we were still using Binary time?

@James-Sangalli it parses it as "yyyyMMddHHmmssz" (e.g. 20180911190201+0800) string. If I'm checking the right contract, the tokenID is 0x000000000000000000000000000000000000000000000000000000000000004a. It isn't valid so the time field is ignored and current/today's date used (Not a good fallback, but was expecting to never get this in a valid contract).

**Comment by hboon** [comment]
> If this is so, then we are simply displaying the wrong fields in the token object. @zhangzhongnan928 what does it look like in android?

Wrong fields and wrong layout.


The iOS app supports 2 layouts for ERC875, 1 for ticket and 1 for spawnable contracts. We shouldn't change the ticket layout of course (at least not the fields, we *can* change the layout if we really want to). The spawnable layout is used when there is a field called building (I know. I'm already regretting this as I type it). Here are 2 layouts:

(Ticket)
x1 category
venue
date [icon] teams [icon] match
time city (collapsed upon display)

(Spawnable)
x1 building
street, state, country
date [icon] expired [icon] match
time, locality (collapsed upon display)

For spawnable, it looks like we aren't displaying these fields:

numero
category
section

And we are displaying match which isn't specified in the XML.

(I can't remember why category and section are not displayed in the spawnable layout. I guess no one filled it with data when we tested it the last time).

**So we can absolutely change the spawnable layout if we want. We don't have a way to select/describe a layout and the fields that go into it yet, so the easiest thing to do now is to (1) agree on the new layout for spawnable, as well as (2) make sure to only use those fields in spawnable contracts (since the field names to display are hardcoded, for now)**.

And continue to use the existence of "building" to switch to the spawnable layout, suggestions to improve the check are welcomed too, but remember this is not permanent.

It might have changed since, but I remember that the Android version had the same field/layouts when we introduced the spawnable contract. But we should of course keep both platforms in-sync.

**Comment by zhangzhongnan928** [comment]
(Spawnable)
x1 Cat
building
date [icon] section [icon] numero
Time, Street, City, State, Country

@James-Sangalli @hboon @JamesSmartCell 
Can we put this format in the readme page of spawndable contract?

**Comment by James-Sangalli** [comment]
@hboon would you mind handling this? We just use the format in the above comment until something more dynamic comes.

**Comment by hboon** [comment]
- [ ] Update fields displayed and layout
- [ ] Update contract repo to describe layout for spawnable contract

**Comment by zhangzhongnan928** [comment]
> 0xa1F63bB16E0cCFcb7050b764651068290Fe12044

**Comment by zhangzhongnan928** [comment]
> The last line wraps if it's too long.
ok, but can it align with time.

> For 0xa1F63bB16E0cCFcb7050b764651068290Fe12044:
> The category isn't displayed because the value encoded in the token ID is invalid
> The date is the current date because the valid encoded in the token ID is invalid
> The country isn't encoded in the token ID too (I hardcoded it to "JP" to show the wrapping effect)
Try the MagicLink below with **Cat** as VIP, **Date and Time** as 2020-01-01 21:29:18 +0800 **Country** as JP @hboon 

> Both state and locality (taken as city) are returning "Tokyo". Probably not intentional?
Because I put both **State** and **City** as Tokyo in token factory
https://x.alphawallet.com/
> 

This is a MagicLink generated from Peter's tool for above contract

<img width="769" alt="screen shot 2019-01-27 at 9 34 02 pm" src="https://user-images.githubusercontent.com/33795543/51801623-4d9d7f80-227b-11e9-9313-2fb531daa118.png">

https://app.awallet.io/AgAAAABcTbIuofY7sW4Mz8twULdkZRBoKQ_hIERKUDIwMjAwMTAxMjEyOTE4KzA4MDAAAQAAVklQAAAAMZGDs9Jg6xF33IUhKNxQwVj0O3WSGffck9WbV8OKSTmEEfZy3hsZMYJwoQBmYGQrhC5UUpyQdqfqxbnR42xMl9cb

**Comment by hboon** [comment]
> ok, but can it align with time.

Done.

**Comment by hboon** [comment]
@James-Sangalli 

An example of a transaction:

https://ropsten.etherscan.io/tx/0x66b5f01bc2f23f6975e6634b07d701312de3a74800f62157dfd290ab84828a16

Input data:

0x4bd13cdd000000000000000000000000000000000000000000000000000000005c5289c700000000000000000000000000000000000000000000000000000000000000c0000000000000000000000000000000000000000000000000000000000000001bcf4deb8c48d7026f2949870acf8d45a3e0db257c511142c2c23d6c08275d59c22a0f65cc2888558ae9c6a342bcb570ff76bd9c68b634970af9651eea17a15536000000000000000000000000bc8dafeaca658ae0857c80d8aa6de4d487577c6300000000000000000000000000000000000000000000000000000000000000014a5032303230303133303133333831352b303830300003000056495000000034

I'm guessing it breaks down into these:

* 0x4bd13cdd
* 000000000000000000000000000000000000000000000000000000005c5289c7
* 00000000000000000000000000000000000000000000000000000000000000c0
* 000000000000000000000000000000000000000000000000000000000000001b
* cf4deb8c48d7026f2949870acf8d45a3e0db257c511142c2c23d6c08275d59c2
* 2a0f65cc2888558ae9c6a342bcb570ff76bd9c68b634970af9651eea17a15536
* 000000000000000000000000bc8dafeaca658ae0857c80d8aa6de4d487577c63 recipient
* 0000000000000000000000000000000000000000000000000000000000000001
* 4a5032303230303133303133333831352b303830300003000056495000000034 tickets


4a5032303230303133303133333831352b303830300003000056495000000034 matches what I see when I step in the iOS app and inspect what is extracted from the MagicLink, converted to tokenID and displayed in the import token UI.

There are at least 2 problems:

1. The import UI is displaying some of the fields correctly. So the tokenID is correct. I think I can fix the ones that are wrong because of the import UI. (It's because they aren't using the exact same logic as the one we have in the wallet tab).
2. After importing, the token ID in the database is: 0x000000000000000000000000000000000000000000000000000000000000004a. I stepped into the iOS app right until just before the spawnPassTo() call and it looks like 4a5032303230303133303133333831352b303830300003000056495000000034 is passed in correctly. But notice that it starts with "4a". Maybe a coincidence?

@James-Sangalli Can you help figure out what's wrong with the tokenID? If you can verify the contract source, maybe we can see what are the values of spawnedTickets and inventory for the contract?

```
function spawnPassTo(uint256 expiry,
                uint256[] tickets,
                uint8 v,
                bytes32 r,
                bytes32 s,
                address recipient) public
```

**Comment by hboon** [comment]
- [ ] Fix: Import UI display for iOS is consistent (and wrong) with wallet tab's
- [ ] tokenID extracted from MagicLink isn't added correctly to contract when order is claimed.

**Comment by James-Sangalli** [comment]
@hboon got it verified with the latest contract code using a recent deployment: https://ropsten.etherscan.io/address/0xc62de900cd915b239142e6b96a8fd8306e623a57

**Comment by James-Sangalli** [comment]
@hboon 

<img width="230" alt="screen shot 2019-01-31 at 2 03 53 pm" src="https://user-images.githubusercontent.com/16630514/52027909-1cfe6400-2561-11e9-88be-9a9380b19c92.png">
<img width="486" alt="screen shot 2019-01-31 at 2 04 06 pm" src="https://user-images.githubusercontent.com/16630514/52027910-1d96fa80-2561-11e9-8f24-d1405e6a9215.png">
