### ISSUE TITLE
Fix the gas price as 1Gwei for xDai Chian 

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/alpha-wallet-ios#1051]

**Comment by James-Sangalli** [comment]
@zhangzhongnan928 is a 1 gwei gas price ensured to always confirm in a timely manner?

**Comment by James-Sangalli** [comment]
@hboon need this for xDAI links too.

**Comment by hboon** [comment]
@James-Sangalli I'm still on send/receive for ERC20 tokens. But if you need this sooner, let me know.
