### ISSUE TITLE
Auto pickup below tokens on xDai network

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/alpha-wallet-ios#1075]
https://blockscout.com/poa/dai/tokens/0x6a814843de5967cf94d7720ce15cba8b0da81967/token_transfers

https://blockscout.com/poa/dai/tokens/0x94819805310cf736198df0de856b0ff5584f0903/token_transfers

https://blockscout.com/poa/dai/tokens/0xdec31651bec1fbbff392aa7de956d6ee4559498b/token_transfers

https://blockscout.com/poa/dai/tokens/0xa95d505e6933cb790ed3431805871efe4e6bbafd/token_transfers

https://blockscout.com/poa/dai/tokens/0xbdc3df563a3959a373916b724c683d69ba4097f7/token_transfers

https://blockscout.com/poa/dai/tokens/0x6e251ee9cadf0145babfd3b64664a9d7f941fcc3/token_transfers

**Comment by hboon** [comment]
(For Ethereum, we had some "partner contracts" which we did similar detection)

@zhangzhongnan928 What would you call these tokens? It doesn't affect the functionality, but a name (in code, not exposed to users) is useful so we can store it meaningfully. Good for looking it up later or maintaining it.

**Comment by zhangzhongnan928** [comment]
Add one more, the same group ETHDever

https://blockscout.com/poa/dai/tokens/0x3e50bf6703fc132a94e4baff068db2055655f11b/token_transfers
