### ISSUE TITLE
Need the Scan QR from Dapp Browser function back

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/alpha-wallet-ios#1083]
Can put it here before we have a better design.
![img_3170](https://user-images.githubusercontent.com/33795543/52391745-dcab6280-2ad9-11e9-9322-fc9128601c27.PNG)

@farrahfazirah can think about a better design

**Comment by zhangzhongnan928** [comment]
Need to replace the switch camera button with Album(check a qr from photo in album)
![9133238e-ba49-4040-8894-542f90428155](https://user-images.githubusercontent.com/33795543/52534442-67ab8780-2d7c-11e9-9bd8-99caf9fa7b6f.jpeg)
![ee677a8f-9891-40e5-b91a-b2ce6fb7702f](https://user-images.githubusercontent.com/33795543/52534443-67ab8780-2d7c-11e9-8142-6bd3f84ba92c.jpeg)

@hboon @James-Sangalli same for Andriod @JamesSmartCell

**Comment by hboon** [comment]
Following up with #1097

**Comment by jzaki** [comment]
@tomekalphawallet current design. `Photos` text not visible with white background
<img src="https://user-images.githubusercontent.com/939603/74286682-65f41580-4d7c-11ea-8e03-d03d51f1c3e7.PNG" width="300">

**Comment by tomekalphawallet** [comment]
Sketch Cloud:
https://sketch.cloud/s/e4OJW/a/Kxp0g1

Zeplin:
https://app.zeplin.io/project/5d088205bff2d15de6a4397b/screen/5e20947a52f316bd0da69bb4/
