### ISSUE TITLE
Add Open in AlphaWallet DApp Browser in iOS Activities 

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/alpha-wallet-ios#1100]
![img_3268](https://user-images.githubusercontent.com/33795543/52625101-3ac9b280-2eeb-11e9-880e-1dd8804f9509.PNG)

If the user is browsing a DApp, he quickly selects Open in AlphaWallet DApp Browser, instead of copy paste.

**Comment by James-Sangalli** [comment]
Duplicate of #1102

**Comment by zhangzhongnan928** [comment]
Not the same, this is for any general URLs, not only our MagicLink.

**Comment by James-Sangalli** [comment]
@hboon Victor means that you should be able to open a safari link, for example, in AlphaWallet, just like you could with another browser.

**Comment by zhangzhongnan928** [comment]
![F6AE8EE7-D472-4666-AF28-B62E242CDDA8](https://user-images.githubusercontent.com/33795543/64489268-7e737780-d294-11e9-9739-4c782bb5de6c.jpeg)

**Comment by yangwao** [comment]
Looking forward to see this one on Android as well. Great job guys 👏

**Comment by hboon** [comment]
@vladyslav-iosdev this should describe what is desirable: https://github.com/AlphaWallet/alpha-wallet-ios/issues/1100#issuecomment-529205339

**Comment by vladyslav-iosdev** [comment]
@hboon maybe u can help me with this issue, as i understand i need to use something like app link, but can't find any information how to do that.

**Comment by hboon** [comment]
I'm not sure actually. We use https://github.com/AlphaWallet/alpha-wallet-ios/blob/8551d9992cfc1107ceacf257971b127f485b883a/AlphaWallet/Info.plist#L26 to handle `.tsml`. Initially I thought there might be an easy way. But maybe the solution is to create a share extension that doesn't open a UI? If that's the way out, let's hold it first and get the Xcode 12 upgrade done first.
