### ISSUE TITLE
Add Telegram in Settings under 'Contact Us' section

### ISSUE THREAD

**Issue by farrahfazirah** [AlphaWallet/alpha-wallet-ios#1105]
AlphaWallet telegram group link: https://t.me/AlphaWalletGroup
Logo for telegram:
[TelegramIcon.pdf](https://github.com/AlphaWallet/alpha-wallet-ios/files/2868567/TelegramIcon.pdf)

**Comment by hboon** [comment]
Dependent on #1066

**Comment by hboon** [comment]
Ok, will add it as the first entry, above Twitter.
