### ISSUE TITLE
Customise each wallet name on the Wallets page

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/alpha-wallet-ios#1108]
![img_3409](https://user-images.githubusercontent.com/33795543/52909412-024b1f80-32c3-11e9-9ac8-e727287621c5.PNG)

**Comment by hboon** [comment]
@zhangzhongnan928 shall we set the default label to the ENS name, if there is one?

**Comment by zhangzhongnan928** [comment]
Maybe, but I prefer my customise name can override the ENS name.
ENS is for others to easily remember my address, on my own wallet I have a
better way to name my wallet address.

P.S it is better these settings together with TBML files can be saved in
iCloud automatically, then when user change his phone he won't lose his
settings.

Regards,
[image: AlphaWallet] <https://awallet.io/>

*Victor Zhang*

[image: AlphaWallet Github] <https://github.com/alpha-wallet> [image:
AlphaWallet Twitter] <https://twitter.com/Alpha_wallet> [image: AlphaWallet
Reddit] <https://www.reddit.com/r/AlphaWallet> [image: AlphaWallet Facebook]
<https://www.facebook.com/AlphaWallet/> [image: AlphaWallet Youtube]
<https://www.youtube.com/channel/UCPP12PQeQmQ4_6qXzNvZw-w/> [image:
AlphaWallet Linkedin] <https://www.linkedin.com/company/%CE%B1wallet/> [image:
AlphaWallet Weibo] <https://weibo.com/AlphaWallet>
Join our Telegram group. <https://t.me/AlphaWalletGroup>

**Comment by zhangzhongnan928** [comment]
suggest doing the same as Andriod 
![photo_2019-04-29 18 11 07](https://user-images.githubusercontent.com/33795543/56889953-9814df00-6aaa-11e9-8abd-29730cbe93fb.jpeg)
![photo_2019-04-29 18 11 03](https://user-images.githubusercontent.com/33795543/56889955-9814df00-6aaa-11e9-86c5-8990e19e67da.jpeg)

This is my iOS setting/wallets page, very difficult to find the right one now.

**Comment by zhangzhongnan928** [comment]
now ENS can setup one and only Reverse Resolution Record, displaying ENS name of a wallet address may be a solution , as there will be only one ens reverse record for each wallet address.

**Comment by hboon** [comment]
Yes, should support this.
