### ISSUE TITLE
Scan EIP 681 QR code while in Send screen and fill in address + amount

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#1113]
See https://github.com/AlphaWallet/alpha-wallet-android/issues/601

**Comment by JamesSmartCell** [comment]
The schema will support different token contract types and even functions.

When a function call is given, assume it's a smart contract call.

Validate:
- check if current Token matches the 'address' field of the code. If wrong, prompt with Token name.
- Optional/TODO: Check if contract supports the function (parse constructor code). If not, prompt.

This will require modifications to UI, so we can produce a prototype run probably on Android and then get formal UI for handling smart contract calls.

This way of doing it is a little clumsy - there should be an ability to scan QR codes near the front of the app, and the app can have a heuristic to work out what to do:

I suggest this action tree:
1. Address:
- is there a token contract at this address? If so, add the token contract to the watch list.
- no contract? Take user to 'send' screen (This has an issue the token contract could be on a different chain - do we scan all chains?).

2. EIP681 code:
- take user to send screen and handle as already implemented. If Token is a known Non-Fungible then take user to the relevant Token Detail page. In future TBML will take over from here.
- If token is not known, then app should read the token in and take user to detail page. There is a possibility the user was 'air-dropped' the token so has a balance there but doesn't know it.
