### ISSUE TITLE
Evaluate if we can use Wallet Core by wrapping around it, remembering that we support multi-chain

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#1118]
https://github.com/TrustWallet/wallet-core

**Comment by James-Sangalli** [comment]
@hboon how will you know when this has been achieved?

**Comment by hboon** [comment]
@James-Sangalli updated title to be more actionable. It'll be good if we can use it if: 

1. The library is dumb enough that we are able to make a thin wrapper around it which makes using it simple. e.g It has to work without requiring HD keys.
2. Works with multi-chain. In particular, it will not work if it uses a global preference or static var to represent the current (block)chain.

Alternatively, 

* It presumably it has some kind of plugin/subclassing system, so if we can quite easily make and maintain a compatible system based on what we already have with some refactoring, we might also be able to use Wallet Core (by copying and pasting even) and contribute back to it.

**Comment by hboon** [comment]
We started to use Wallet Core in #1272 as a means to import/export seed phrases and generate the 0th Ethereum wallet address and private key.
