### ISSUE TITLE
Signed message incorrect in https://playground.counterfactual.com/ when creating account

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#1140]
Via @zhangzhongnan928

**Comment by hboon** [comment]
Seems to work ok on MetaMask

**Comment by zhangzhongnan928** [comment]
Works on metamask and cipher 

		
Victor Zhang
CEO, AlphaWallet
							
Not only display information, @Alpha_Wallet let you preform the functions: DEPOSIT, WITHDRAW, PAYBACK, GENERATE, MO… https://t.co/6dJfdvnM3i

**Comment by James-Sangalli** [comment]
site is gone now
