### ISSUE TITLE
Deleting ropsten token causes a crash with tokenId Force unwrap

### ISSUE THREAD

**Issue by James-Sangalli** [AlphaWallet/alpha-wallet-ios#1145]
I imagine this has to do with the tokenobject database?

**Comment by hboon** [comment]
@James-Sangalli I can't reproduce it by both swiping to delete a token with a zero-balance as well as non-zero balance on Ropsten. How do you reproduce it?

**Comment by James-Sangalli** [comment]
@hboon sorry forgot to mention this is on multichain

**Comment by hboon** [comment]
@James-Sangalli Yup. I tested on the multi chain branch. Are you able reproduce it? Or if you can send me the stack trace with the function name, I might be able to guess what could be the cause.

**Comment by James-Sangalli** [comment]
Signal: SIGABRT (signal SIGABRT)
2019-03-24 11:40:31.708490+0100 AlphaWallet[2759:1856262] *** Terminating app due to uncaught exception 'RLMException', reason: 'Attempting to create an object of type 'HiddenContract' with an existing primary key value '0xd0066e5f48a425c6DC3271d081f7C12d6be80a2F-3'.'
*** First throw call stack:
(0x19b2adea4 0x19a47da50 0x106f2e8f0 0x10797c47c 0x10797c5fc 0x1049712e4 0x10797bd48 0x104971214 0x104ba7f14 0x104933d94 0x104933e20 0x10493dd94 0x10493de60 0x1c87f9290 0x1c8a67818 0x1c87f90e0 0x1c88010ec 0x1c8765618 0x1c876abcc 0x1c876a7d4 0x1c8767160 0x1c8768f1c 0x1c8768660 0x1c81e50d0 0x1c81ed6ec 0x1c81eaf70 0x1c81ea458 0x1c81dd760 0x1c81dd2cc 0x1c81dd09c 0x1c8608cb4 0x1c85e7fcc 0x1c86b6e38 0x1c86b9830 0x1c86b2320 0x19b23e0e0 0x19b23e060 0x19b23d944 0x19b238810 0x19b2380e0 0x19d4b1584 0x1c85ccc00 0x104887274 0x19acf6bb4)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by hboon** [comment]
Ah, I imagine this would crash, but it doesn't match the title of this issue. I think there could be more than 1 type of crash.

**Comment by hboon** [comment]
Created an issue #1155 for the crash for the stack trace above which seems to be separate cause of crashing then suggested by this issues title.

**Comment by hboon** [comment]
To be reopened if we can reproduce it.
