### ISSUE TITLE
Adding Zerion to the DApp list

### ISSUE THREAD

**Issue by rockfridrich** [AlphaWallet/alpha-wallet-ios#1147]
Hey Alpha Wallet team, 

We added support of Alpha wallet to our interface. Do you mind adding us to the Finance section of DApps exploration tab?
You could use this logo — https://drive.google.com/file/d/1qv0-kc1BKbJoO12LYCxxKkk3n7ISsXCR/view?usp=sharing
Description: Trade and manage your digital assets across different wallets in one interface.

Regards,
Vadim

**Comment by zhangzhongnan928** [comment]
- [ ] Andriod @JamesSmartCell 

- [ ] iOS @hboon

**Comment by hboon** [comment]
Related https://github.com/AlphaWallet/alpha-wallet-android/issues/637
