### ISSUE TITLE
Need to show "Open in AlphaWallet" when scan a EIP681 QR Code

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/alpha-wallet-ios#1163]
![IMG_4055](https://user-images.githubusercontent.com/33795543/55407435-89610800-5590-11e9-9aa2-45d912c47f4d.PNG)

"ethereum:0xf956F4D787F8CA0F363468859E54eAD5cA1e5184"

**Comment by hboon** [comment]
@zhangzhongnan928 we can add it in, but remember that if the iOS device has more than one app that claims to support the URL scheme, it's unpredictable which one gets launched. But still good for when the user only has 1 wallet app.
