### ISSUE TITLE
Support Görli Tesnet

### ISSUE THREAD

**Issue by JamesSmartCell** [AlphaWallet/alpha-wallet-ios#1182]
Here's the details:

GOERLI_NETWORK_NAME = "Görli (Test)";
GOERLI_SYMBOL = "GÖETH";
GOERLI_ID = 5;
GOERLI_RPC_URL = "https://goerli.infura.io/v3/<your infura key>";
Etherscan API: "https://api-goerli.etherscan.io/"
Etherscan TX page URL: "https://goerli.etherscan.io/tx/"
Colour: #BBAE9A

Everything else works same as Rinkeby/Ropsten testnets.

**Comment by James-Sangalli** [comment]
Goerli or Gorli?
