### ISSUE TITLE
The balance display in DApp Browser blocks some DApp buttons

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/alpha-wallet-ios#1208]
![A9859291-AAB6-4BCC-A8DC-18141CAE6ECE](https://user-images.githubusercontent.com/33795543/56867457-f644b200-6a17-11e9-8a48-50eeebd2d445.jpeg)

Is there any way to keep the balance display but allow the dapp button functions on the same place. That means if I click the balance display area, the function button at the background can be triggered.

**Comment by hboon** [comment]
> Is there any way to keep the balance display but allow the dapp button functions on the same place. That means if I click the balance display area, the function button at the background can be triggered.

@zhangzhongnan928 yes, good catch. Fixed in PR.
