### ISSUE TITLE
ENS loading issues

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/alpha-wallet-ios#1213]
1. If the network is slow, users may submit a transition before ENS load up. It will end up with Invalid Address error message.

- [ ] need an Indication to tell users, the address is loading up.

2. Once triggered Invalid Address error message, the wallet will stop loading the ENS. Means once users click the send before ENS load up, the ENS will never load up again, unless you kill the app and restart it.

- [ ] need to continue loading.

**Comment by hboon** [comment]
@vladyslav-iosdev Help to check if still applicable, and fix or close

**Comment by vladyslav-iosdev** [comment]
> @vladyslav-iosdev Help to check if still applicable, and fix or close

ok
