### ISSUE TITLE
DApp https://uniswap.exchange/ cannot detect wallet.

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/alpha-wallet-ios#1215]
DApp https://uniswap.exchange/ cannot detect wallet. It works very well before

**Comment by zhangzhongnan928** [comment]
I have received several complains about this issue.
Uniswap made a “limit edition socks selling” event, several users complained that they cannot use AlphaWallet to buy socks, after all they have to transfer the fund to other wallets.

**Comment by James-Sangalli** [comment]
@hboon I am on it.

**Comment by James-Sangalli** [comment]
https://github.com/Uniswap/uniswap-frontend/issues/282

**Comment by zhangzhongnan928** [comment]
I tested Uniswap on most of the web3 wallets, it failed only on us and Cipher. Did we use something that is different from other wallet but same as Cipher? @James-Sangalli

**Comment by zhangzhongnan928** [comment]
Supporting EIP1193 should fix this
https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1193.md

Ref from https://github.com/Uniswap/uniswap-frontend/issues/282#issuecomment-494150608
