### ISSUE TITLE
Deleted tokens keep coming back

### ISSUE THREAD

**Issue by James-Sangalli** [AlphaWallet/alpha-wallet-ios#1220]

**Comment by hboon** [comment]
Reason for this:

A. `GetContractInteractions.getErc20Interactions()` fetches transactions for ERC20 tokens and then the caller eventually calls `TransactionsStroage.add()` which calls `TokensDataStore.update(in: realm, tokens: tokens)` with the tokens (contracts) extracted from those ERC20 transactions.
B. Compare that to the caller of `GetContractInteractions().getContractList()` which fetches a list of contracts, and then filter the list of contracts that has been deleted/hidden or previously detected as delegate contracts.

So the caller of (A) has to somehow perform a similar filtering of the contracts before adding them to the tokens database. Possibly the filtering part in (B) can be extracted and reused?

@James-Sangalli do you want to give this a go?
