### ISSUE TITLE
https://dapp.neutralproject.com/ is not working in DApp Browser

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/alpha-wallet-ios#1224]
Works in Trust.

**Comment by zhangzhongnan928** [comment]
https://dapp.neutralproject.com/ is still not working in DApp Browser on Version 2.0(276)

**Comment by zhangzhongnan928** [comment]
Doesn't work on 2.02(282)

**Comment by hboon** [comment]
@zhangzhongnan928 I see this after the prompt to sign the message and signing.

<img src="https://user-images.githubusercontent.com/56189/59252858-8acd4180-8c5f-11e9-9d0c-6b4b6f3ae705.png" width=200>

How do we reproduce the error?

**Comment by zhangzhongnan928** [comment]
The popup window doesn’t show up on my phone, build 2.01(281)

		
Victor Zhang
CEO, AlphaWallet
							
Not only display information, @Alpha_Wallet let you preform the functions: DEPOSIT, WITHDRAW, PAYBACK, GENERATE, MO… https://t.co/6dJfdvnM3i

**Comment by zhangzhongnan928** [comment]
@hboon tested on James's iPhone and my iPad, all works fine besides my iPhone.
We think it may be an issue from the browser cache.
We should provide a Clear Browser Cache function in the setting page
https://github.com/AlphaWallet/alpha-wallet-ios/issues/1244

**Comment by James-Sangalli** [comment]
Closed to follow discussions on #1244
