### ISSUE TITLE
Victor to follow up.

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/alpha-wallet-ios#1230]
Hi Victor! Not sure if our devs told you before, we have a fee-sharing program where trades through alpha wallet can earn some fees in KNC. Have you registered an address for alpha wallet?  https://developer.kyber.network/docs/Integrations-FeeSharing/#docsNav

Cool, once you registered, could you pass me your registered fee-sharing program wallet ID address? that will help us track dapp volume growth in reports like this: https://blog.kyber.network/kyber-ecosystem-report-2-bb0fdff5d962  thanks:)

**Comment by James-Sangalli** [comment]
moved to more relevant repo: https://github.com/AlphaWallet/web-service/issues/31
