### ISSUE TITLE
duplicated transection records and token cards for ETH and ETC networks, Build 2.0(267) and 2.0(277)

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/alpha-wallet-ios#1231]
All the transaction I did on ETH network will create a duplicate copy on ETC network.
and some of the ETH network transections show as ETC network.
 
![IMG_5140](https://user-images.githubusercontent.com/33795543/59009067-94c1ff80-886f-11e9-841b-26e766b96e7e.PNG)
![IMG_5141](https://user-images.githubusercontent.com/33795543/59009066-94296900-886f-11e9-8ee9-f9ad2a82d129.PNG)
![IMG_5142](https://user-images.githubusercontent.com/33795543/59009060-925fa580-886f-11e9-917e-b2f71adcf9db.PNG)

**Comment by James-Sangalli** [comment]
@hboon related to erc20Interactions?

**Comment by hboon** [comment]
@James-Sangalli yes. Should be a dup issue

**Comment by James-Sangalli** [comment]
Solved in #1305
