### ISSUE TITLE
When dropping TS files for actions, application crashes (has to be done twice)

### ISSUE THREAD

**Issue by James-Sangalli** [AlphaWallet/alpha-wallet-ios#1233]
Thread 1: Fatal error: Unexpectedly found nil while unwrapping an Optional value

`func getContractName(for addressString: String,
                         completion: @escaping (ResultResult<String, AnyError>.t) -> Void) {
        let address = Address(string: addressString)
        getNameCoordinator.getName(for: address!) { (result) in
            completion(result)
        }
    }`

**Comment by hboon** [comment]
@James-Sangalli fixed with https://github.com/AlphaWallet/alpha-wallet-ios/pull/1170/commits/3c8aba6415f4035119c8e5de4b3e6416f2ac3bc7 in tokenscript feature branch

**Comment by James-Sangalli** [comment]
Haha was just about to say that, thanks!
