### ISSUE TITLE
Some times the 3 dot on the the top right corner of browser is disappeared.

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/alpha-wallet-ios#1259]
![6D960E71-35C0-4BA6-8678-35E50AB36979](https://user-images.githubusercontent.com/33795543/59886770-b987ac80-9403-11e9-9da5-be2833f03c1b.jpeg)

Will need to kill and restart the app to get that button back.

Don't know how to reproduce it, but it happens many times.

**Comment by hboon** [comment]
@zhangzhongnan928 Which app version and build number is this for?

**Comment by zhangzhongnan928** [comment]
The latest released version 2.04 284

**Comment by hboon** [comment]
Might have been fixed due to other changes at some point. Reopen if we reproduce it again.
