### ISSUE TITLE
HD wallet support

### ISSUE THREAD

**Issue by colourful-land** [AlphaWallet/alpha-wallet-ios#1265]
## Which HD library to use?

This relates to #1118 - we must evaluate the path to support HD wallet and the possibility of using Trust Wallet Core should be investigated. I filed it in iOS because @JamesSmartCell is away and we are on the edge of starting backup/recovery project by Tomek.

## Support only English seed phrase with the vision of supporting more down the way

We enforce the use of English seed phrases. Despite that seed phrases are [polyglot](https://github.com/bitcoin/bips/blob/master/bip-0039/bip-0039-wordlists.md
). Reason:

- We assume that Chinese input methods always send the combination to the server (e.g. when the user writes an ideograph in a drawing area)
- we are concerned putting the keyboard to password mode prevents typing of umlauts like ë

Tomek is going to develop a safe seed phrase recovery tool which will allow non-English. But it will be a separate task.

**Comment by JamesSmartCell** [comment]
Existing web3j issue for HD wallet support https://github.com/web3j/web3j/issues/533

**Comment by JamesSmartCell** [comment]
We could implement this in web3j and fulfil our community service! However it has to be done very carefully.

**Comment by colourful-land** [comment]
> We could implement this in web3j and fulfil our community service! However it has to be done very carefully.

We prefer paying them to do so than using our own bandwidth. We will probably fail the goal of becoming the wallet of next 1M blockchain users even if we didn't split our focus.

**Comment by James-Sangalli** [comment]
@colourful-land @JamesSmartCell why not use Trust's implementation?

**Comment by colourful-land** [comment]
> @colourful-land @JamesSmartCell why not use Trust's implementation?

Good question

**Comment by James-Sangalli** [comment]
@colourful-land @hboon @JamesSmartCell 

He uses a seed wallet and derives multiple coins by choosing paths far away from each other. Supporting this kind of scheme is much more practical for the future when there are other coins.

Example code (iOS):

1. https://github.com/TrustWallet/trust-keystore/blob/master/Tests/KeyStoreTests.swift (notice the derivationPath: label to derive the path)
2. https://github.com/TrustWallet/trust-keystore/blob/master/Sources/KeyStore.swift#L45
3. https://github.com/TrustWallet/trust-keystore/blob/master/Sources/KeyStore.swift#L67
4. (legacy keystore importing): https://github.com/TrustWallet/trust-keystore/blob/master/Sources/KeyStore.swift#L81

For android it is less clear cut, he hasn't specifically made an implementation for it so it may be best to look elsewhere, perhaps at coinomi?

**Comment by hboon** [comment]
@James-Sangalli we should also look at https://github.com/trustWallet/wallet-core. It's supposed to be cross-platform, so both iOS and Android might be able to use it. It might also be the successor to trust-keystone, so the API might be similar.

**Comment by colourful-land** [comment]
> For android it is less clear cut, he hasn't specifically made an implementation for it so it may be best to look elsewhere, perhaps at coinomi?

For our needs, HD wallet should be simple, we just need one (𝑔ˣ)ʸ in the same way James Brown hand-made a rudimentary Deffi-Hellman key (except this time it's really that simple, no need to care about forward security etc etc).

IMHO the most non-trivial part of HD wallet is not deriving the keys but managing them, that is, looking up Bitcoin bloom filters to find out whether or not an address is used, and collect balances from addresses. It's difficult because it's intertwined with status-update. A daunting task that we don't need to do for Ethereum alone.

I suggest we have less number of dependencies so if we already use webj and if wallet-core for Android isn't available we patch up webj.
