### ISSUE TITLE
Value in PLN is incorrect

### ISSUE THREAD

**Issue by tomekalphawallet** [AlphaWallet/alpha-wallet-ios#1268]
![2019-06-28 09 14 39](https://user-images.githubusercontent.com/51817359/60325727-47c1dc80-9988-11e9-9318-24f9682caaa0.png)

I have 139,18 PLN which is 37,26 USD (around 0,1237 ETH)

**Comment by tomekalphawallet** [comment]
Other thing is that we should't have a comma before decimal fractions for PLN value where the ETH has a period before decimal fractions 0.1237 ETH = 37,26 USD. One or another depending if this is Australia, UK, US, most of Asia (period) OR European/South American country.

https://en.wikipedia.org/wiki/Decimal_separator#/media/File:DecimalSeparator.svg

**Comment by James-Sangalli** [comment]
@tomekalphawallet The API gets the values in USD only so far

**Comment by tomekalphawallet** [comment]
@James-Sangalli on iOS it displays me PLN for an unknown reason
