### ISSUE TITLE
Replace icons in the Tab Bar

### ISSUE THREAD

**Issue by tomekalphawallet** [AlphaWallet/alpha-wallet-ios#1273]
Image resources can be found:

https://app.zeplin.io/project/5d0356be2f25b319dcc5944b/dashboard?seid=5d1c519e2a1bf3b008801932

All 4 icons are to be replaced and the text follows the icons (explicit text).

**Comment by tomekalphawallet** [comment]
Android Implementation can be found here:
https://github.com/AlphaWallet/alpha-wallet-android/issues/731

**Comment by James-Sangalli** [comment]
@tomekalphawallet please let me in 
<img width="645" alt="Screen Shot 2019-07-03 at 8 12 35 pm" src="https://user-images.githubusercontent.com/16630514/60583747-ee660d00-9dce-11e9-86d0-bfd1da19f396.png">
