### ISSUE TITLE
Flicking between languages causes the decimal point to fail

### ISSUE THREAD

**Issue by James-Sangalli** [AlphaWallet/alpha-wallet-ios#1274]
Discovered this bug when I was having dinner with some crypto newbies and decided I would send them some. Since they were Korean, I switched languages to Korean and then said I would give some ether to them to try. When I went to send it, the decimal point wouldn't render in the input label. Killing and restarting the process fixed it.

**Comment by hboon** [comment]
Are you referring to this screen and the textbook where it's currently showing "1.1"? I reach here after changing the language to Korean and it works for me. Are you able to reproduce the problem on your device?

<img src="https://user-images.githubusercontent.com/56189/60768974-f1c60500-a0fc-11e9-985a-425fdf86b31e.PNG" width=300>

**Comment by hboon** [comment]
@James-Sangalli are you able to reproduce this?

**Comment by hboon** [comment]
Bump @James-Sangalli

**Comment by hboon** [comment]
@James-Sangalli re-open if you still observe this.
