### ISSUE TITLE
when open Uniswap in DApp Browser, it shows blank page

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/alpha-wallet-ios#1279]
This issue only happens with my iPhone, my iPad works fine.
I have tried restart, clear cache.
![IMG_640F2B50754D-1](https://user-images.githubusercontent.com/33795543/60775947-8a936980-a16b-11e9-992f-05e2224c4920.jpeg)

**Comment by James-Sangalli** [comment]
Browser was caching an old webpage which had a bug. After installing from master, this problem persisted until I cleared the cache (on the new build) and then it worked. 

@hboon I am closing this but it is weird because Victor's version didn't clear the cache properly.

**Comment by hboon** [comment]
@James-Sangalli thanks! Yeah, we have had quite a few weird issues with the site. Probably have to test against it every now and then.
