### ISSUE TITLE
Use blockscout.com for fetching ERC20 transactions and detecting contracts

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#1286]
Looks like blockscout.com supports a much longer list now. Use them to replace the ones that were made to return nil in this [PR](https://github.com/AlphaWallet/alpha-wallet-ios/pull/1283/files) (if blockscout.com works like we expected for them).

**Comment by James-Sangalli** [comment]
@hboon still relevant?

**Comment by hboon** [comment]
Probably, but let's hold it first since event support with Amberdata might replace this completely.

**Comment by hboon** [comment]
Outdated
