### ISSUE TITLE
AlphaWallet latest build is super slow on heavily used keys

### ISSUE THREAD

**Issue by James-Sangalli** [AlphaWallet/alpha-wallet-ios#1288]
To reproduce:

1. get latest app on testflight
2. watch Victor's address: 0xbc8dAfeacA658Ae0857C80D8Aa6dE4D487577c63
3. Observe the laggyness 
4. downgrade to the previous build
5. notice that it is much faster.

**Comment by hboon** [comment]
@James-Sangalli I found a few places where performance can be improved, but empirical testing suggests that the one change implemented in #1291 is the most significant. Let me know if it helps?

**Comment by James-Sangalli** [comment]
Closing for now, will release a testflight to test on more devices. Thank you.
