### ISSUE TITLE
Issue with limit order on KyberSwap

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/alpha-wallet-ios#1290]
The new KyberSwap supports limit order through signed message. But it is not working on iOS.

![F97781ED-0B72-4E6D-A03B-20F21E2DBA95](https://user-images.githubusercontent.com/33795543/61124430-2d404500-a4ea-11e9-9891-b2b18471c1f2.png)

**Comment by James-Sangalli** [comment]
@zhangzhongnan928 could you go into further detail as to what happened in your case?

**Comment by zhangzhongnan928** [comment]
![297FB4E3-7C2E-4415-8664-34B7CD243885](https://user-images.githubusercontent.com/33795543/61137242-8028f500-a508-11e9-97ed-bbfd866e892a.jpeg)

Works in Trust and toshi

**Comment by James-Sangalli** [comment]
Been solved on their side, just need to wait for production release
