### ISSUE TITLE
Conflicting tokenscript files when there are none

### ISSUE THREAD

**Issue by James-Sangalli** [AlphaWallet/alpha-wallet-ios#1296]
Says there is a conflict, check TokenScript overrides and find none. 

![unnamed](https://user-images.githubusercontent.com/16630514/61194527-5d176480-a705-11e9-906c-0bd0c56aec75.jpg)

**Comment by hboon** [comment]
@James-Sangalli if this is your phone,

Can you help to attach it to Xcode and set a breakpoint in the `TokenScriptFileIndices.write(toUrl:)`, run the app a bit so the breakpoint are triggered and convert that data to string and paste it here? There are 2 instances of it, 1 for TokenScript files downloaded from the repo and 1 for overrides. So the former might have some entries, while the latter should be mostly empty. Post both versions here.

If you can't debug the phone, we'll have to figure out another way.

**Comment by James-Sangalli** [comment]
![Screen Shot 2019-07-16 at 4 40 30 pm](https://user-images.githubusercontent.com/16630514/61271616-76451180-a7e8-11e9-999d-74cbacde8521.png)

**Comment by hboon** [comment]
Can you convert to JSON and paste or email it? With `self` as the TokenScriptFileIndices instance:

```
let encoder = JSONEncoder()
let data = try! encoder.encode(self)
let jsonString = String(data: data, encoding: .utf8)!
```

**Comment by James-Sangalli** [comment]
@hboon 

{"contractsToOldTokenScriptFileNames":[],"contractsToEntities":{"0x2B58A9403396463404c2e397DBF37c5EcCAb43e5.tsml":[],"0x7c81DF31BB2f54f03A56Ab25c952bF3Fa39bDF46.tsml":[],"0x63cCEF733a093E5Bd773b41C96D3eCE361464942.tsml":[],"0xc27a404860708C7D17A899dF96043647a1a6c313.tsml":[],"0xA66A3F08068174e8F005112A8b2c7A507a822335.tsml":[],"0xFB82A5a2922A249f32222316b9D1F5cbD3838678.tsml":[],"0x89d24A6b4CcB1B6fAA2625fE562bDD9a23260359.tsml":[]},"fileHashes":{"0x2B58A9403396463404c2e397DBF37c5EcCAb43e5.tsml":-6727507399905694660,"0xc27a404860708C7D17A899dF96043647a1a6c313.tsml":-3317402840580287795,"0x63cCEF733a093E5Bd773b41C96D3eCE361464942.tsml":-7572245545901417282,"0x7c81DF31BB2f54f03A56Ab25c952bF3Fa39bDF46.tsml":-7572245545901417282,"0xA66A3F08068174e8F005112A8b2c7A507a822335.tsml":-3540229899019024488,"0xFB82A5a2922A249f32222316b9D1F5cbD3838678.tsml":-7572245545901417282,"0x89d24A6b4CcB1B6fAA2625fE562bDD9a23260359.tsml":9106646151450184934},"contractsToFileNames":[{"ethereumAddress":"0xA66A3F08068174e8F005112A8b2c7A507a822335"},["0xA66A3F08068174e8F005112A8b2c7A507a822335.tsml"],{"ethereumAddress":"0x63cCEF733a093E5Bd773b41C96D3eCE361464942"},["0x63cCEF733a093E5Bd773b41C96D3eCE361464942.tsml","0x7c81DF31BB2f54f03A56Ab25c952bF3Fa39bDF46.tsml","0x2B58A9403396463404c2e397DBF37c5EcCAb43e5.tsml","0xFB82A5a2922A249f32222316b9D1F5cbD3838678.tsml"],{"ethereumAddress":"0xc27a404860708C7D17A899dF96043647a1a6c313"},["0xc27a404860708C7D17A899dF96043647a1a6c313.tsml"],{"ethereumAddress":"0x2B58A9403396463404c2e397DBF37c5EcCAb43e5"},["0x63cCEF733a093E5Bd773b41C96D3eCE361464942.tsml","0x7c81DF31BB2f54f03A56Ab25c952bF3Fa39bDF46.tsml","0x2B58A9403396463404c2e397DBF37c5EcCAb43e5.tsml","0xFB82A5a2922A249f32222316b9D1F5cbD3838678.tsml"],{"ethereumAddress":"0x89d24A6b4CcB1B6fAA2625fE562bDD9a23260359"},["0x89d24A6b4CcB1B6fAA2625fE562bDD9a23260359.tsml"],{"ethereumAddress":"0x7c81DF31BB2f54f03A56Ab25c952bF3Fa39bDF46"},["0x63cCEF733a093E5Bd773b41C96D3eCE361464942.tsml","0x7c81DF31BB2f54f03A56Ab25c952bF3Fa39bDF46.tsml","0x2B58A9403396463404c2e397DBF37c5EcCAb43e5.tsml","0xFB82A5a2922A249f32222316b9D1F5cbD3838678.tsml"],{"ethereumAddress":"0xFB82A5a2922A249f32222316b9D1F5cbD3838678"},["0x63cCEF733a093E5Bd773b41C96D3eCE361464942.tsml","0x7c81DF31BB2f54f03A56Ab25c952bF3Fa39bDF46.tsml","0x2B58A9403396463404c2e397DBF37c5EcCAb43e5.tsml","0xFB82A5a2922A249f32222316b9D1F5cbD3838678.tsml"],{"ethereumAddress":"0xD8e5F58DE3933E1E35f9c65eb72cb188674624F3"},["0xA66A3F08068174e8F005112A8b2c7A507a822335.tsml"]],"badTokenScriptFileNames":["0x704813e188fe02628842ac5304ae3af370bf1c2b.tsml","0xedd6d7ba0ff9f4bc501a12529cb736ca76a4fe7e.tsml","0x17734f3709486b1d7015f941c069cebf8017a833.tsml","0x17515dc6b29525bde7ed2eb8e6ad35165215e90e.tsml","0xb94ff9c08fe580c5a2967d9f62e55cde16f8d6ce.tsml","0x4973b60e9d51d269d982c525e5fdc8d6d136722a.xml","0xb38b714f72a14f257d5b3c1cc5f1435006132a05.tsml","0x359e67642aa9c82eb244ea454ab1f6c0d90a9d58.tsml","0xa66a3f08068174e8f005112a8b2c7a507a822335.tsml","0x48401d879e7736ab80d3d18e24cebcac5345170a.tsml","0xe50d32425dead03f196d8a8f5dd871e21a01a74f.tsml","0xa66a3f08068174e8f005112a8b2c7a507a822335.xml","0x35b2a45abfba445214370210da93431fef99d120.tsml","0xdcceb64f0b42d8a69b3f875c230ea60f472a4008.tsml","0xd8e5f58de3933e1e35f9c65eb72cb188674624f3.xml","0x7c81df31bb2f54f03a56ab25c952bf3fa39bdf46.tsml","0x2b58a9403396463404c2e397dbf37c5eccab43e5.tsml","0xbe31f58b95e93c5a6d7ade4ba08847e5a7cfdc39.tsml","0x63ccef733a093e5bd773b41c96d3ece361464942.tsml","0x1e8bceed258ca5c7ed9f55639abbd01d3f7d9992.tsml","0xa1f63bb16e0ccfcb7050b764651068290fe12044.tsml","0xc8ce984740b2283e6547c2280b8770f5dc111173.tsml","0x6a3b2a506f53d737bb5897f9d894075f8f7c931f.tsml","0x2455b0154a446c8473f43225875418731710c5eb.tsml","0x3489f69eff3f656b203995bfe05d91864a7404ab.tsml","0x4973b60e9d51d269d982c525e5fdc8d6d136722a.tsml","0x4be043bf79740a42e66bdafe46db285de4d1bc03.tsml","0x308d21f1c807223129958837eac4bfcf7ba8d042.tsml","0xfb82a5a2922a249f32222316b9d1f5cbd3838678.tsml","0xadd-tokenscript-tutorial-exercise-examples.tsml","0x7d2aacf3cc179dab10cc0465af32346e09a4efea.tsml","0xa16b70e8fad839e62abba2d962e4ca5a28af9e76.xml","0x06012c8cf97bead5deae237070f9587f8e7a266d.tsml","0x26646a9b0dedac7ca0b933d49cc9a423cef357bc.tsml","0xa2918727ebd4b6c16ca3bd25becb0c739b70339d.tsml","0x9b047b680b7d323ebe4b49e28e73dc5f16559e8e.tsml","0x8ad587c997a8709fda69a3ee46dd1e03791cb50d.tsml","0x830e1650a87a754e37ca7ed76b700395a7c61614.xml","0xe3825b5d3e13555d3145230a7db85e5df6f9a9a0.tsml","0x16e58f9a98bc46a572cfb9ce28ddeeaf76af645a.xml","0x3f02f7629998b8022730f3822c994fa4610897cb.tsml","0xa16b70e8fad839e62abba2d962e4ca5a28af9e76.tsml","0x0dbc159fb28179b58467bd9e3f4233cba38a5c07.tsml","0xadd0e813e57cae5b348cb4f32ee6a3f9bcf6ad85.tsml","0x8c6d4fcecf75d2b9d9e646755af1203c4186014a.tsml","0x8555974c23a03aa14ff122f4fb2da9d13f45992b.tsml","0x1b67a93c591409b0b9a37ca4180497e4bd487d66.tsml","0xa1eb40c284c5b44419425c4202fa8dabff31006b.tsml"]}

**Comment by hboon** [comment]
Reopen if you see it again @James-Sangalli
