### ISSUE TITLE
The share option in Dapp Browser does nothing when tapped in the "home" screen

### ISSUE THREAD

**Issue by colourful-land** [AlphaWallet/alpha-wallet-ios#1299]
The issue https://github.com/AlphaWallet/alpha-wallet-android/issues/754 is found on ios version too.
---
# Project Information

* Project Name:  AlphaWallet
* Originally from: https://github.com/friendsmobile

# Expected behavior

When I click on the share option, different types of social media applications should appear where I can share it.

# Actual behavior

When I click the share option, no response to the application appears

#### How to reproduce

*  open the application
* go to Browse tab 
* click the 3 vertical dots at top right 
* click on share option

**Comment by colourful-land** [comment]
Maybe adopting @JamesSmartCell quick-behaviour-fix until UX team give us a specific design.

**Comment by James-Sangalli** [comment]
Is this what you are talking about @colourful-land? 

![unnamed](https://user-images.githubusercontent.com/16630514/61373587-9276aa80-a8dd-11e9-8144-0f33a08bbcaa.jpg)
