### ISSUE TITLE
Crash with v2.05 build 286

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#1301]
Reported by Victor

**Comment by James-Sangalli** [comment]
@hboon there is no information in this issue?

**Comment by hboon** [comment]
@zhangzhongnan928 how can we reproduce this?

**Comment by James-Sangalli** [comment]
I will release a testflight as this may be the issue.

**Comment by zhangzhongnan928** [comment]
> @zhangzhongnan928 how can we reproduce this?

watch my wallet address 0xbc8dAfeacA658Ae0857C80D8Aa6dE4D487577c63
enable all the networks
click around, open/close token card

**Comment by James-Sangalli** [comment]
Solved in #1304
