### ISSUE TITLE
Time to add an enable token filter 

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/alpha-wallet-ios#1312]
I have more than 50 tokens on mainnet, and  more on other networks. I don’t want to show all the tokens on my wallet home page, but I don’t want to delete them either, as I may want to use some of them later. 

An “enabled token filter” can be useful.

It also enables 0 balance token card, it can be useful for user to use TokenScript without having a token yet.

**Comment by colourful-land** [comment]
Has to be designed first.
