### ISSUE TITLE
With validator API, debug tokenscripts are also invalidated. 

### ISSUE THREAD

**Issue by James-Sangalli** [AlphaWallet/alpha-wallet-ios#1313]

**Comment by hboon** [comment]
This is what I see. Do you observe or expect something different?

(Also posted to https://community.tokenscript.org/t/if-a-tokenscript-in-debug-mode-has-a-bad-signature-or-is-not-signed-should-the-token-still-be-rendered-with-it/261 to clarify)

Invalid Sig | Valid sig
------------ | -------------
<img width="482" alt="Screenshot 2019-08-08 at 2 19 30 PM" src="https://user-images.githubusercontent.com/56189/62679694-e3168a80-b9e7-11e9-886f-f8856d41dcca.png"> | <img width="482" alt="Screenshot 2019-08-08 at 2 21 34 PM" src="https://user-images.githubusercontent.com/56189/62679718-f0cc1000-b9e7-11e9-8196-6b6c4cf8ad82.png">
