### ISSUE TITLE
Invalid signature on native token cards 

### ISSUE THREAD

**Issue by James-Sangalli** [AlphaWallet/alpha-wallet-ios#1314]

**Comment by hboon** [comment]
@James-Sangalli can you elaborate on this? A reproducible case?

**Comment by James-Sangalli** [comment]
@hboon simply open up the ethereum, xdai etc native cards and you will see "invalid signature"

**Comment by hboon** [comment]
@James-Sangalli  I know you mentioned previously that it fails for debug TSMLs, but when I try with the official Dai TSML, I see this. Looks good to me. Does it fail to validate when you test it?

<img width="482" alt="Screenshot 2019-07-23 at 11 00 08 PM" src="https://user-images.githubusercontent.com/56189/61722912-b5053980-ad9d-11e9-988c-5c671d51a327.png">
