### ISSUE TITLE
Build 2.07 288 Dapp browser issue

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/alpha-wallet-ios#1323]
Compound doesn't work
![3E6F2913-EDC5-471F-A73F-E3496125DD7E](https://user-images.githubusercontent.com/33795543/61809498-c410e800-ae80-11e9-804b-28e16738d5f3.png)

**Comment by James-Sangalli** [comment]
Working just fine on my side, are you sure you waited til it has loaded, or have you cleared the cache? this looks like the screen it shows when still loading. Certainly working in #1322

**Comment by zhangzhongnan928** [comment]
2.06 287
![8F746194-00C2-4420-A9B6-61EC282C6013](https://user-images.githubusercontent.com/33795543/61838239-b92f7500-aecb-11e9-8f25-5026e3509090.gif)
2.07 288
![2E834EE0-599F-4B1E-ACAF-8FE0E215AB2F](https://user-images.githubusercontent.com/33795543/61838246-c3517380-aecb-11e9-9ec0-1e87e8cd3e11.gif)

**Comment by hboon** [comment]
@zhangzhongnan928 is it still broken? If it is, can you describe what's wrong?

**Comment by James-Sangalli** [comment]
@zhangzhongnan928 I believe this was resolved some time ago
