### ISSUE TITLE
Build 2.07 290, the wallet type covered wallets

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/alpha-wallet-ios#1329]
![111A4A3D-3962-4926-AF34-0883BE1B0619](https://user-images.githubusercontent.com/33795543/62431411-c883ad80-b76a-11e9-9684-e39a9a7c0238.jpeg)
![68A03A07-3412-42AD-953B-35374C1D41E5](https://user-images.githubusercontent.com/33795543/62431413-c883ad80-b76a-11e9-91c9-759ea02b90d9.gif)

**Comment by hboon** [comment]
Fixed in https://github.com/AlphaWallet/alpha-wallet-ios/pull/1272.

Will be in TestFlight
