### ISSUE TITLE
Reproduce Realm database growing to enormous size

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#1334]
10s of GBs on hboon's simulator in laptop. This might have been due to a debugging set up and might have already been fixed earlier. Report back if we can reproduce it @James-Sangalli

**Comment by hboon** [comment]
@vladyslav-iosdev  Can you see if we can figure this out?

**Comment by vladyslav-iosdev** [comment]
@hboon i will try to reproduce it, but for me its not clear what steps do i need to walk through, to reproduce it.

**Comment by hboon** [comment]
I have no idea too :) During development (this was created a long time ago), I noticed that the Realm database grew to a huge size, but I didn't know why. I *think* `Transaction`s contributed the most to it. Can you see if it doesn't get cleaned up probably? Eg. when we fetch transactions again, is there a bug that cases some transactions to be left hanging around as duplicates that we ignore?

Give it a bit of time and if you can't reproduce or reason it out, let's close it.
