### ISSUE TITLE
Call AWS lambda DeriveTrustAddress 

### ISSUE THREAD

**Issue by colourful-land** [AlphaWallet/alpha-wallet-ios#1354]
You can find the tutorial address in Pull Request https://github.com/AlphaWallet/alpha-wallet-android/pull/806 (look for the interface file. The URL is in the comment.)

**Comment by James-Sangalli** [comment]
@jzaki 

Started here: https://github.com/AlphaWallet/alpha-wallet-ios/tree/aws-lambda-trust-address-setup

Info about setup in iOS: https://docs.aws.amazon.com/aws-mobile/latest/developerguide/how-to-ios-lambda.html

**Comment by James-Sangalli** [comment]
@jzaki @colourful-land is this issue still off value? we don't know who we shall use as the key to make such an address and it can't prevent phishing.
