### ISSUE TITLE
2.07 291 all the 721 token can not be displayed 

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/alpha-wallet-ios#1358]
![ECFB5700-C18D-40EF-8590-2AB8C0586037](https://user-images.githubusercontent.com/33795543/63226333-d120bd00-c21b-11e9-9ac5-a78a8414f6d7.png)
![BE1F4FA6-3775-4145-BA2C-F2FF810616A4](https://user-images.githubusercontent.com/33795543/63226334-d120bd00-c21b-11e9-8bfb-607eb0236fc5.png)

After kill the app , restart, they display as normal.

Haven’t found out how to reproduce it.

**Comment by hboon** [comment]
Should be fixed by #1452 and possibly these are related: #1429, #1442
