### ISSUE TITLE
Kovan magic links break on iOS when opened 

### ISSUE THREAD

**Issue by James-Sangalli** [AlphaWallet/alpha-wallet-ios#1372]

**Comment by hboon** [comment]
@James-Sangalli Can you elaborate? I created one and tapped on it and it showed the import screen.

**Comment by hboon** [comment]
(send me a link :) )

**Comment by James-Sangalli** [comment]
@JamesSmartCell sent me this link during the workshop on friday: https://kovan.aw.app/AQAAAABdXmK02RXIrTJB9FmkWty7-K9CyqVhoVQAMDAwMA==

Appears to be malformed but it should catch rather than crash

**Comment by James-Sangalli** [comment]
Maybe he truncated it by accident

**Comment by James-Sangalli** [comment]
https://github.com/AlphaWallet/alpha-wallet-android/issues/823
