### ISSUE TITLE
Move “Change Wallet” to the bottom of the Settings

### ISSUE THREAD

**Issue by tomekalphawallet** [AlphaWallet/alpha-wallet-ios#1391]
Note: I took screenshots from Android, but you will easily get what I mean here. 

Move “Change Wallet” to the bottom of the Settings screen list. 

<img width="584" alt="Screen Shot 2019-08-26 at 10 42 28 AM" src="https://user-images.githubusercontent.com/51817359/63666719-459ac380-c7fb-11e9-9589-6febffd0a0e7.png">

This is why I want to hide it a bit. Some users might look for the address in there (this is because they see "09xasddasd" in the secondary line. 

Then, add secondary line of text to "My Wallet Address" and place the address there.

<img width="441" alt="Screen Shot 2019-08-26 at 10 45 16 AM" src="https://user-images.githubusercontent.com/51817359/63666730-4e8b9500-c7fb-11e9-8d03-318d07e7a0fb.png">

**Comment by hboon** [comment]
Will change it so that the 3 rows remain at the top, but will read:

* My Wallet address (with the full address 0x991....353 as the subtitle) as before
* Change Wallet (remove the address)
* Back up this Wallet (with the 3-segment bars and BACKUP NOW text) as before

@JamesSmartCell
