### ISSUE TITLE
Do not refill empty mnemonics when the app is in the background

### ISSUE THREAD

**Issue by tomekalphawallet** [AlphaWallet/alpha-wallet-ios#1394]
If you change the app and left the AlphaWallet in the background (open Safari or Notes) it resets all words available to tap. So even I finished the whole seed phrase, the buttons does not change to green so I could verify Seed Phrase. I guess the button becomes green only when no mnemonics to tap are left - all empty. 

Here I entered 9/12 words, but the list below contains 12 options again. This is because I kicked AlphaWallet to the background for a moment:

![2019-08-26 15 43 13](https://user-images.githubusercontent.com/51817359/63739818-de434900-c8b8-11e9-912c-77d3c879ce4e.png)

**Comment by hboon** [comment]
Behavior is partly dictated by #1393.

But there's definitely a bug here though. So will clear the textbox when we reset the shuffled seed phrase list (i.e. when the app goes into the background)
