### ISSUE TITLE
Show Seed Phrase introduction screen at the start of the backup process before seed phrase is shown

### ISSUE THREAD

**Issue by tomekalphawallet** [AlphaWallet/alpha-wallet-ios#1397]
This is screen is important for new users, especially those not familiar with Seed phrases. You should see this screen when you has just created new wallet and has not backed up yet.

<img width="420" alt="Screen Shot 2019-08-27 at 12 28 09 PM" src="https://user-images.githubusercontent.com/51817359/63743405-56643b80-c8c6-11e9-86a7-8e34709c9042.png">

**Comment by tomekalphawallet** [comment]
Same to the next screen. 
<img width="437" alt="Screen Shot 2019-08-27 at 12 32 07 PM" src="https://user-images.githubusercontent.com/51817359/63743533-bb1f9600-c8c6-11e9-96ea-4b9055182d61.png">

Please use the copy "Ok, I wrote this down" instead "Test my Seed Phrase"

**Comment by hboon** [comment]
- [ ] Add introduction screen before backup HD wallet
- [ ] Tweak the back up screen button

**Comment by hboon** [comment]
@tomekalphawallet there are 2 screens that look like they are meant to be same in Zeplin. It looks like we've implemented the first in iOS. So are you saying we should switch to the 2nd?

1 | 2
-|-
<img src="https://user-images.githubusercontent.com/56189/63838040-2b094b80-c9af-11e9-9cea-d7fde2b66b69.png" width=200> | <img src="https://user-images.githubusercontent.com/56189/63838042-2b094b80-c9af-11e9-8ef8-5f8c7bbf14f8.png" width=200>

**Comment by tomekalphawallet** [comment]
You can ignore the first option where it says "Test my seed phrase". This might be confusing. Let's just stick to "Ok, I wrote this down"
