### ISSUE TITLE
Replace TokenScript Validator API call with lambda function call

### ISSUE THREAD

**Issue by James-Sangalli** [AlphaWallet/alpha-wallet-ios#1419]
Currently, the app calls the web api on our EC2 server to validate a TokenScript file (.tsml)

Replace this call with the lambda function and handle the result just like with the previous implementation.

See https://github.com/AlphaWallet/alpha-wallet-android/pull/836

**Comment by hboon** [comment]
Closed due to inactivity and pending changes
