### ISSUE TITLE
FIFA normal transfer is not working

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/alpha-wallet-ios#1438]
error msg as below

![IMG_6653](https://user-images.githubusercontent.com/33795543/64696559-05695f80-d4e2-11e9-8be7-f74ff4f151cc.PNG)

**Comment by hboon** [comment]
@James-Sangalli can you help verify if it's still happening?

**Comment by James-Sangalli** [comment]
@zhangzhongnan928 @hboon not an issue for me in the app store version https://etherscan.io/tx/0x555dca89db4146743253305bf1923ddc908b4b341e3807b96e679039f59de3e9

**Comment by hboon** [comment]
@James-Sangalli Thanks!
