### ISSUE TITLE
Freldo network tsml not showing verified

### ISSUE THREAD

**Issue by James-Sangalli** [AlphaWallet/alpha-wallet-ios#1440]
curl -X POST -F file=@"FRECNX.tsml" https://aw.app/api/v1/verifyXMLDSig

{"result":"pass","subject":"CN=backend.ico.freldo.com,OU=EssentialSSL,OU=Domain Control Validated","keyName":"FRECNX","keyType":"SHA256withRSA","issuer":"CN=Sectigo RSA Domain Validation Secure Server CA,O=Sectigo Limited,L=Salford,ST=Greater Manchester,C=GB"}

**Comment by hboon** [comment]
@James-Sangalli 

If you change this line:

```
<ts:ethereum contract="FreldoCoinX">
```

to:

```
<ts:ethereum contract="FRECNX">
```

The screen will not say "[DEBUG] Invalid Signature".

**Comment by hboon** [comment]
(probably good to keep a list of this "lint" checks we can build into our cli tool)

**Comment by James-Sangalli** [comment]
Resolved, cheers.
