### ISSUE TITLE
Keep one network label in each token card

### ISSUE THREAD

**Issue by colourful-land** [AlphaWallet/alpha-wallet-ios#1462]
Re-attempt to address this issue as boat #1414 has fallen (fallen un-executable = fallen dead).

There are two network labels only one needs to remain. Kill the 2nd (The one below the title). Keep the 1st (the one right to the title)

![63941384-da791780-caae-11e9-9ee4-d29926d65ed6](https://user-images.githubusercontent.com/548435/65216835-8bdefc00-daf5-11e9-992e-ef52c0565b9b.jpeg)

**Comment by James-Sangalli** [comment]
Superseded by fiji design
