### ISSUE TITLE
When repo server is unavailable, use last status

### ISSUE THREAD

**Issue by James-Sangalli** [AlphaWallet/alpha-wallet-ios#1464]
According to @zhangzhongnan928 when he enters a zone like China whereby the connection can be cut, he loses the successful status of his tokenscript and it reverts to the failed verification hardcoded settings. 

We should instead allow the last status to remain in that kind of situation

**Comment by hboon** [comment]
Ah right. Of course. It’s not the file, it’s the status that’s not accessible.

**Comment by zhangzhongnan928** [comment]
![F5B52989-0D68-43FD-8912-8A77BF332179](https://user-images.githubusercontent.com/33795543/65317282-e86a1600-dbde-11e9-9293-fe620631ff34.png)

when verifying, it should work as well.

**Comment by zhangzhongnan928** [comment]
@JamesSmartCell does Android behave the same?

This issue effect a lot in TS UX.

**Comment by hboon** [comment]
@zhangzhongnan928 

> when verifying, it should work as well.

It should already be. Can you share with me a wallet I can watch, the contract and a TokenScript file so I can verify?

**Comment by hboon** [comment]
- [ ] Cache and reuse previous signature verification status
- [ ] While verifying signature, the TokenScript file should still be used for rendering

**Comment by zhangzhongnan928** [comment]
> @zhangzhongnan928
> 
> > when verifying, it should work as well.
> 
> It should already be. Can you share with me a wallet I can watch, the contract and a TokenScript file so I can verify?

Can watch my wallet.
Try this
1. A fresh install, then you will see some token get TS, some not. Some get TS after a long time. 
2. Change your network condition, poor net work, no network, different VPN.

**Comment by James-Sangalli** [comment]
@hboon can confirm that cutting the internet and refreshing the phone removes all the tokenscripts

**Comment by hboon** [comment]
> @hboon can confirm that cutting the internet and refreshing the phone removes all the tokenscripts

@James-Sangalli I've created #1469. Can you see if refreshing still removes the TokenScript files? I can't figure out why that might happen and can't reproduce it both before and after the PR.

**Comment by James-Sangalli** [comment]
> > @hboon can confirm that cutting the internet and refreshing the phone removes all the tokenscripts
> 
> @James-Sangalli I've created #1469. Can you see if refreshing still removes the TokenScript files? I can't figure out why that might happen and can't reproduce it both before and after the PR.

Working now, thank you!

**Comment by zhangzhongnan928** [comment]
> > > @hboon can confirm that cutting the internet and refreshing the phone removes all the tokenscripts
> > 
> > 
> > @James-Sangalli I've created #1469. Can you see if refreshing still removes the TokenScript files? I can't figure out why that might happen and can't reproduce it both before and after the PR.
> 
> Working now, thank you!

On build 2.13(301)
Working on normal tokens, but xDai has the same issue, kill app, cut off internet, lose TS.
![2CAEC8FA-2DB5-46CD-B8A7-4D6B0B6CA432](https://user-images.githubusercontent.com/33795543/65512203-18395680-df1c-11e9-8e8e-74108d3586bc.png)
