### ISSUE TITLE
The display of Dai and USDx Token Card

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/alpha-wallet-ios#1472]
The standard display should be,
"balance" "contract name" "(Symbol)"
Like 
![IMG_7255](https://user-images.githubusercontent.com/33795543/65650753-787ce500-e04f-11e9-9a7c-6adb335ee1d1.jpg)
![IMG_7256](https://user-images.githubusercontent.com/33795543/65650758-7d419900-e04f-11e9-8029-f7efdaecc3b4.jpg)

It seems broken on Dai and USDx token card,
![IMG_7254](https://user-images.githubusercontent.com/33795543/65650796-964a4a00-e04f-11e9-873e-5c8f8e5dfd4e.jpg)
![IMG_7253](https://user-images.githubusercontent.com/33795543/65650798-96e2e080-e04f-11e9-8427-2600b4db2161.jpg)
![IMG_7252](https://user-images.githubusercontent.com/33795543/65650799-96e2e080-e04f-11e9-9302-1c707ede2d82.jpg)
![IMG_7251](https://user-images.githubusercontent.com/33795543/65650800-96e2e080-e04f-11e9-99ae-82d1f7df2f17.jpg)

**Comment by James-Sangalli** [comment]
dforce is the contract name (for both USDx and DF) but is missing the symbol once clicked on the card.

Contract name on the token card is overridden by the TokenScript for localization, however it is strange that a bracket is missing on the end (See https://github.com/AlphaWallet/alpha-wallet-ios/issues/1443)
