### ISSUE TITLE
Cache of old schema tokenscripts is not deleted on upgrade

### ISSUE THREAD

**Issue by James-Sangalli** [AlphaWallet/alpha-wallet-ios#1492]
When upgrading schema, old files linger and prevent the new ones from overriding them. You must reinstall to remove this as of now

**Comment by hboon** [comment]
@James-Sangalli it doesn't look like the `2019/10` files are available. eg.

```
$ curl -I https://repo.tokenscript.org/2019/10/0x3C18f1003e0B87D2B15C318df4261FDF370FF281
HTTP/2 404 
date: Wed, 09 Oct 2019 13:06:54 GMT
server: Apache
content-type: text/html; charset=iso-8859-1
```

**Comment by James-Sangalli** [comment]
> @James-Sangalli it doesn't look like the `2019/10` files are available. eg.
> 
> ```
> $ curl -I https://repo.tokenscript.org/2019/10/0x3C18f1003e0B87D2B15C318df4261FDF370FF281
> HTTP/2 404 
> date: Wed, 09 Oct 2019 13:06:54 GMT
> server: Apache
> content-type: text/html; charset=iso-8859-1
> ```

I only restored the aw.app files, you can see one here:  

$ curl -i https://repo.tokenscript.org/2019/10/0xf5dce57282a584d2746faf1593d3121fcac444dc

Compound etc are running on the new schema and are running on the phone. albeit they don't load or function properly

**Comment by hboon** [comment]
@James-Sangalli so this is reproducible with just files from the repo and no overrides? Is it that the `2019/05` version remains in the `assetDefinitions` directory and isn't replaced with `2019/10` version?

If so, can you see if the timestamp for that `2019/05` TokenScript file in the directory and the server's are what you expect? i.e the timestamp for the server version of `2019/10` should be later than the `2019/05` on disk.
