### ISSUE TITLE
TokenScript properties and updates to webview don't load in 2019/10

### ISSUE THREAD

**Issue by James-Sangalli** [AlphaWallet/alpha-wallet-ios#1493]

**Comment by hboon** [comment]
@James-Sangalli if this is with files that uses features which `2019/10` introduces, verify that the JavaScript emitted for the token data is valid.

**Comment by James-Sangalli** [comment]
@hboon all don't work, even those which were simply updating the schema and added nothing new

**Comment by James-Sangalli** [comment]
this.props is undefined inside the webview, continuing to investigate

**Comment by James-Sangalli** [comment]
Some of the token instance shows up like name but not attributes like allowance 

<img width="1150" alt="Screen Shot 2019-10-10 at 12 33 39 pm" src="https://user-images.githubusercontent.com/16630514/66532212-480e6e00-eb5a-11e9-9d90-07a380b8d67e.png">
