### ISSUE TITLE
Keep default layout for 721 tokens when you have a tokenscript for it

### ISSUE THREAD

**Issue by James-Sangalli** [AlphaWallet/alpha-wallet-ios#1501]
When creating the ENS TokenScript I noticed that the OpenSea layout disappears when I try to add extra functions to the token. We should keep this default layout IF the TokenScript developer leaves a blank view for the card.

**Comment by hboon** [comment]
We can do that as a quick fix, but we talked about this a while back and haven’t decided how to handle this — how to indicate to use the default view in the TokenScript file. Also need to sync for Android.

**Comment by James-Sangalli** [comment]
@hboon yep. I think for now having it that a blank view sets it to the default layout is a good one and if the developer puts something in there, use that one instead.

**Comment by hboon** [comment]
Ah, it only does not work specifically for ERC721 because it uses a different rendering cell. It already work for ERC875 when the view tag is omitted.

**Comment by hboon** [comment]
@James-Sangalli still on this.
