### ISSUE TITLE
Old cache of 2019/05 tokenscripts present with new release 2019/10

### ISSUE THREAD

**Issue by James-Sangalli** [AlphaWallet/alpha-wallet-ios#1527]
Reported by @zhangzhongnan928 and I am guessing this is the issue.

**Comment by zhangzhongnan928** [comment]
I reinstalled AlphaWallet last week with a fresh App Store build and recovered my wallet.
Then upgrade to the latest build this week. 
Now all my tokens lost TokenScript features.

**Comment by hboon** [comment]
Dup of #1492
