### ISSUE TITLE
TokenScript client displays values as NaN after opening and closing views a few times

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#1530]
Have to investigate to figure out more details.

Works again after app is restarted.

<img src="https://user-images.githubusercontent.com/56189/68071368-d91ce180-fdb4-11e9-9c76-b391366da132.jpg" width=250>

**Comment by zhangzhongnan928** [comment]
I did many test, it seems related to what tokens  you have, I can reproduce the issue with 0xbc8dAfeacA658Ae0857C80D8Aa6dE4D487577c63 on any build Andy device.

Once the issue appears on 0xbc8, the addresses on the same device stop working either.

**Comment by zhangzhongnan928** [comment]
![0FE684B5-D9E3-4459-9C64-2051EEA0EE07](https://user-images.githubusercontent.com/33795543/68384593-077f3000-01ac-11ea-83c4-91221027c74f.jpeg)

When the NaN on cDai happens, Devcon ticket also shows na in some field.

**Comment by hboon** [comment]
Fixed by #1576
