### ISSUE TITLE
“Add custom token” should pick up ENS

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/alpha-wallet-ios#1545]
![84AB78B8-ABAA-4931-9BF2-869D75476759](https://user-images.githubusercontent.com/33795543/68428600-99b12380-0200-11ea-8517-55d5a1531e63.jpeg)
![EB90DF5B-C270-4CB8-BAC9-5FCA1381401C](https://user-images.githubusercontent.com/33795543/68428601-9a49ba00-0200-11ea-923f-ad583d3e5a5e.jpeg)

**Comment by hboon** [comment]
Works for me. Can you reproduce it?

<img src="https://user-images.githubusercontent.com/56189/71340659-7d8bfa80-2592-11ea-8edc-0b08c32be8b8.png" width=200>

**Comment by hboon** [comment]
Seems to work.
