### ISSUE TITLE
Done button on NFT transfer hidden due to new colour scheme 

### ISSUE THREAD

**Issue by James-Sangalli** [AlphaWallet/alpha-wallet-ios#1548]

**Comment by hboon** [comment]
@James-Sangalli can you help upload a screenshot? Can't find it.

**Comment by hboon** [comment]
@James-Sangalli bump

**Comment by James-Sangalli** [comment]
@hboon actually all the magic link and NFT transfer pages have buttons hidden.

To reproduce:

Create a magic link til completion and you will see it
Transfer an NFT and on the last page you will see "Done" is hidden in the colour
