### ISSUE TITLE
Display ENS reverse lookup if they correspond directly to ETH address

### ISSUE THREAD

**Issue by tomekalphawallet** [AlphaWallet/alpha-wallet-ios#1552]
This one is a bit tricky. I might go and provide version for iOS and Android. Coz none of them is perfect.

Suggestion: @JamesSmartCell please add "Change Wallet" to the headline
@hboon Please add ENS reverse lookup if they correspond directly to ETH address
Both: Shall we call this "Watched Wallet" or "Watch Wallet"? 
@hboon Show only 4 digits after dot-decimal notation, so instead 0,8332341123123 - 0,8332
@JamesSmartCell What these green outlines mean? I understand the green checkmark, but what about green borders?

<img width="928" alt="Screenshot 2019-11-12 at 14 06 23" src="https://user-images.githubusercontent.com/51817359/68638429-a2ce2780-0555-11ea-9e98-2d9f0435c642.png">

**Comment by zhangzhongnan928** [comment]
@tomekalphawallet is the design ready? these useful small pieces can be implemented soon.

**Comment by tomekalphawallet** [comment]
@zhangzhongnan928 for iOS - yes. The whole Settings Tab is now ready for development. 

Change Wallet on Sketch Cloud:
https://sketch.cloud/s/e4OJW/v/09qdve/a/oE3M0x/r/wLDjww/

Change Wallet on Zeplin:
https://app.zeplin.io/project/5d0356be2f25b319dcc5944b/screen/5dfc1f4f38dc389a6fbe5b30

Settings tab Flow:
https://drive.google.com/a/alphawallet.com/file/d/1HCoj9rS4GsEKCJ7YuECf6abqemyjFj3g/view?usp=sharing

[Settings_iOS_flow.pdf](https://github.com/AlphaWallet/alpha-wallet-ios/files/4009653/Settings_iOS_flow.pdf)

**Comment by zhangzhongnan928** [comment]
@tomekalphawallet should the ENS name be displayed anywhere even in the transaction records? that means if an Ethereum address has ENS we will display it, no matter in which page.

@hboon I can see Andriod already have ENS reverse display, can we start implementing it on iOS, it solves a big pain point for me : )

**Comment by tomekalphawallet** [comment]
https://github.com/AlphaWallet/alpha-wallet-ios/issues/1662
