### ISSUE TITLE
Gas limit exceeds block gas limit on The new MakerDAO vault

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/alpha-wallet-ios#1563]
![444FC058-3329-4C3E-80E2-749DFDBC7856](https://user-images.githubusercontent.com/33795543/69116289-f43f5f00-0adf-11ea-8468-7fb140ed8a9f.jpeg)
![9369F68A-D9A6-4CFE-AA8F-40EF1A0F85CF](https://user-images.githubusercontent.com/33795543/69116290-f43f5f00-0adf-11ea-9c28-35ac83b176e9.png)

oasis.app

The new MakerDAO portal returns a super high gas limit when opening vault.

**Comment by James-Sangalli** [comment]
@zhangzhongnan928 can you link me to the exact page that you opened the vault on?

**Comment by zhangzhongnan928** [comment]
> @zhangzhongnan928 can you link me to the exact page that you opened the vault on?
It's the same oasis.app, the url won't change. 
click borrow, then select ETH-Dai

**Comment by James-Sangalli** [comment]
Indeed, this gas limit is too high, exceeding the block gas limit itself: https://etherscan.io/block/9331368

This might be an error on their side however we should protect against it by setting the max gas limit by default if it exceeds
