### ISSUE TITLE
Display suggestions when importing seed phrase

### ISSUE THREAD

**Issue by tomekalphawallet** [AlphaWallet/alpha-wallet-ios#1568]
Please use Moonlight app as a reference. 
Please improve the look of segmented controls. 

![Import_with_Seed_iOS](https://user-images.githubusercontent.com/51817359/69209421-41d4ce00-0bab-11ea-842d-006ea634d54a.jpg)

**Comment by tomekalphawallet** [comment]
https://github.com/AlphaWallet/alpha-wallet-android/issues/976

**Comment by hboon** [comment]
@tomekalphawallet to save you some effort, you only need to mention the issue/PR in a corresponding repo (Android/iOS) on one of them. ie. only mention Android issue in iOS repo, or vice versa. GitHub will link the other one for you.

**Comment by tomekalphawallet** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[1400] As a wallet user, I want to import my wallet's SEED phrase more readily, so that I'm not frustrated with typing long seed phrases](https://trello.com/c/b47sz01Q/31-1400-as-a-wallet-user-i-want-to-import-my-wallets-seed-phrase-more-readily-so-that-im-not-frustrated-with-typing-long-seed-phras)

**Comment by jzaki** [comment]
Only other requirement is that the dictionary is not a full english dictionary, but rather just the [bip39](https://github.com/bitcoin/bips/blob/master/bip-0039/english.txt)

**Comment by nimitparekh2020** [comment]
@hboon In above screenshot shows a number of counts so we need to add into ios or not.

<img src="https://user-images.githubusercontent.com/708425/80935451-46eca900-8dea-11ea-843a-41286758e9d1.png" width="200"/>

**Comment by hboon** [comment]
@nimitparekh2020 keep it

**Comment by nimitparekh2020** [comment]
Will implement and do commit.

**Comment by AW-STJ** [comment]
@hboon Do you have enough to take over and close this issue?
