### ISSUE TITLE
TokenScript attributes fail to load

### ISSUE THREAD

**Issue by James-Sangalli** [AlphaWallet/alpha-wallet-ios#1570]
<img width="429" alt="Screenshot 2019-11-20 17 22 48" src="https://user-images.githubusercontent.com/16630514/69214236-7439f780-0bba-11ea-97cc-239b62ae9998.png">

**Comment by hboon** [comment]
@James-Sangalli when does the left hand side occur?

**Comment by James-Sangalli** [comment]
> @James-Sangalli when does the left hand side occur?

Have it working first time (TS is on the server), kill the app and reload it

**Comment by hboon** [comment]
Fixed by https://github.com/AlphaWallet/alpha-wallet-ios/pull/1576
