### ISSUE TITLE
UEFA Token

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/alpha-wallet-ios#1573]
![9A004E10-036F-4311-B510-B4AE41B3CB80](https://user-images.githubusercontent.com/33795543/69398825-f56ec700-0d3f-11ea-8145-68d3a5a5018e.png)

Reproduce, transfer the token to your own address.

**Comment by James-Sangalli** [comment]
Smart contract problem, solved here and will be in the next deployment.

https://github.com/AlphaWallet/ticketing-721/commit/a4c4847a0cab18fbd5dbe42de8a0ee087b106d0a
