### ISSUE TITLE
Explore CKB Wallet SDK and integration effort

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/alpha-wallet-ios#1580]
https://github.com/nervosnetwork/ckb-sdk-js
https://github.com/nervosnetwork/ckb-sdk-java
https://github.com/nervosnetwork/ckb-sdk-ruby
https://github.com/nervosnetwork/ckb-sdk-swift

**Comment by James-Sangalli** [comment]
@zhangzhongnan928 this issue is not actionable, please elaborate...

**Comment by zhangzhongnan928** [comment]
> @zhangzhongnan928 this issue is not actionable, please elaborate...

It is meeting follow up for Boon. He will check out those SDK later.

**Comment by James-Sangalli** [comment]
@zhangzhongnan928 imToken has implemented CKB integration

**Comment by zhangzhongnan928** [comment]
> @zhangzhongnan928 imToken has implemented CKB integration

Yes, and several other wallets. 
@colourful-land is checking out their script(smart contract design.
