### ISSUE TITLE
OpenSea cause issue with the new ERC721+ contract

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/alpha-wallet-ios#1588]
Even with TS, wallet still loads data from the open sea.

**Comment by zhangzhongnan928** [comment]
- [ ] OpenSea can only pick the tokenID after it is transferred
- [ ] Once OpenSea pick up a tokenID, the wallet will display the balance based on OpenSea

**Comment by James-Sangalli** [comment]
https://github.com/AlphaWallet/ticketing-721/commit/4c7b90f82a582e94b7c9da1ae351685903adc68a

**Comment by hboon** [comment]
@James-Sangalli is this still a problem?

> Once OpenSea pick up a tokenID, the wallet will display the balance based on OpenSea

**Comment by hboon** [comment]
@James-Sangalli bumped

**Comment by hboon** [comment]
Should be good.
