### ISSUE TITLE
[Serious] Keystore wiped with the following

### ISSUE THREAD

**Issue by James-Sangalli** [AlphaWallet/alpha-wallet-ios#1589]
- Enabled ropsten
- Saw conflicting TokenScript for UEFA
- Removed airdropped UEFA file
- Killed the app
- Wallets have disappeared 

Cannot seem to reproduce this on my own phone, happened on Victors...

**Comment by hboon** [comment]
@James-Sangalli Did it happen once or is it reproducible?

**Comment by James-Sangalli** [comment]
> @James-Sangalli Did it happen once or is it reproducible?

Only once, having trouble reproducing it

**Comment by hboon** [comment]
Might be related to an iOS bug I have seen before, `NSUserDefaults` sometimes not accessible shortly after startup. But I have never been able to reproduce it. Someone reported something similar with various different conditions, iOS 11, 32-bit, etc.

**Comment by hboon** [comment]
#1591 helps to mitigate this. There might be other cause, but I can't figure out what else might be wrong by code inspection though.

**Comment by James-Sangalli** [comment]
@hboon fair enough, thanks for that. Will see if it can be reproduced again with the fix but we might never know.
