### ISSUE TITLE
Conflicting tokenscript file where there is none

### ISSUE THREAD

**Issue by James-Sangalli** [AlphaWallet/alpha-wallet-ios#1595]
Cleared overrides but it is still an issue. 

![photo_2019-12-02_15-52-30](https://user-images.githubusercontent.com/16630514/69931570-dd572e80-151b-11ea-90d9-24fbc1ee9e2f.jpg)

No exact steps to reproduce except that it seems to be triggered if you toggle between using the TokenScripts from the server and ones you airdrop

**Comment by hboon** [comment]
@James-Sangalli Does it say anything in Settings > Console?

**Comment by James-Sangalli** [comment]
![photo_2019-12-02_17-13-11](https://user-images.githubusercontent.com/16630514/69934768-0df09580-1527-11ea-911d-e026be66be66.jpg)
@hboon

**Comment by hboon** [comment]
@James-Sangalli did that help? 2 of those files refer to the same contact maybe?

**Comment by James-Sangalli** [comment]
@hboon we deleted all the overrides so it shouldn't

**Comment by hboon** [comment]
@James-Sangalli could you have accidentally changed one of the files in `assetDefinitions/` instead of `assetDefinitionsOverrides/`, that will trigger it also.

**Comment by James-Sangalli** [comment]
@hboon was a physical device with airdrop, didn't touch directories
