### ISSUE TITLE
Opensea and 721 ticket cast cause token card to have no symbol

### ISSUE THREAD

**Issue by James-Sangalli** [AlphaWallet/alpha-wallet-ios#1598]
To reproduce, simply open check the rinkeby token card for UEFA

**Comment by hboon** [comment]
Is it this screen?

<img src="https://user-images.githubusercontent.com/56189/70028581-f7f2db80-15df-11ea-8d76-0ea251b244d8.png" width=200>

**Comment by James-Sangalli** [comment]
Its on the token label and there.

Looks like FIFA()

**Comment by hboon** [comment]
@James-Sangalli looks good on mine. Can you help to screenshot what you see?

**Comment by James-Sangalli** [comment]
@hboon it has to be the rinkeby card because that one is on opensea (the other networks are not) 

![photo_2019-12-04_09-15-34](https://user-images.githubusercontent.com/16630514/70094451-a5b0c980-1676-11ea-80d4-d3a6e6668b97.jpg)

**Comment by hboon** [comment]
Because OpenSea is returning an empty string `""` as the symbol. So have to fix it upstream (OpenSea)
