### ISSUE TITLE
Update Tab Bar Icons + Apply Large Titles [Fiji]

### ISSUE THREAD

**Issue by tomekalphawallet** [AlphaWallet/alpha-wallet-ios#1633]
Sketch Cloud:
https://sketch.cloud/s/e4OJW/p/tab-bar-icons

Zeplin:
https://app.zeplin.io/project/5d0356be2f25b319dcc5944b/dashboard?seid=5e0a01cdd963351c5cb22ee1

- ~~Apply new Tab Bar active color to "Azure" (you can find it in Zeplin components)~~ edit: covered by #1673)
- Apply Large Titles
- Update Tab Bar Icons (since Activity tab is not finished, we can temporarily use "Transactions", but please update an icon)
- ~~Apply updated Segmented Controls~~ (edit: covered by #1634)

**Comment by tomekalphawallet** [comment]
![activity](https://user-images.githubusercontent.com/51817359/72553261-cafd3e00-3898-11ea-977f-e9988cea8192.png)
![browser](https://user-images.githubusercontent.com/51817359/72553262-cafd3e00-3898-11ea-83b9-4d8f1b21142f.png)
![settings](https://user-images.githubusercontent.com/51817359/72553263-cafd3e00-3898-11ea-9906-b0eddaca3589.png)
![wallet](https://user-images.githubusercontent.com/51817359/72553264-cafd3e00-3898-11ea-8ed7-2eb1bd5590ec.png)

**Comment by tomekalphawallet** [comment]
![large_titles](https://user-images.githubusercontent.com/51817359/72553507-35ae7980-3899-11ea-94bf-c0509fa7ed6a.png)
![small_titles](https://user-images.githubusercontent.com/51817359/72553511-35ae7980-3899-11ea-8227-79137dae5968.png)
![tab_bar](https://user-images.githubusercontent.com/51817359/72553513-35ae7980-3899-11ea-8342-860b53823bc3.png)

**Comment by hboon** [comment]
@tomekalphawallet the white circle in the Settings icon is filled, so it renders like this:

<img width="309" alt="Screenshot 2020-02-03 at 11 54 12 AM" src="https://user-images.githubusercontent.com/56189/73624527-188cef80-467c-11ea-8ee7-117578a3c535.png">

**Comment by tomekalphawallet** [comment]
Zeplin:

https://zpl.io/2j9xM0r zpl://components?coids=5e160c84f98a6c80b997c53e&pid=5d0356be2f25b319dcc5944b

https://zpl.io/adwjM47 zpl://components?pid=5d0356be2f25b319dcc5944b&coids=5e160c86a7c41a9404598bd6

@hboon updated

**Comment by tomekalphawallet** [comment]
The wallet icon lost his button too. 

![Screenshot 2020-02-03 07 16 51](https://user-images.githubusercontent.com/51817359/73630041-3e52ce00-4655-11ea-98ae-e024b55c665b.png)

**Comment by hboon** [comment]
@tomekalphawallet thanks!

@tomekalphawallet Ah, good catch. It looks quite nice without the button though. Up to you.

**Comment by tomekalphawallet** [comment]
Ok, so ignore the button. The rest is not so detailed.

**Comment by tomekalphawallet** [comment]
Well done.
