### ISSUE TITLE
Update Segmented Controls [Fiji]

### ISSUE THREAD

**Issue by colourfreak** [AlphaWallet/alpha-wallet-ios#1634]
Zeplin:
https://app.zeplin.io/project/5d0356be2f25b319dcc5944b/styleguide/components?cseid=5dfc12e12ec4d6975469c160

https://app.zeplin.io/project/5d0356be2f25b319dcc5944b/styleguide/components?cseid=5dfc1338bdb90d17d2aa628c

https://app.zeplin.io/project/5d0356be2f25b319dcc5944b/styleguide/components?cseid=5dfc1308cb89a49855c3063e

Please pay attention to the details. It took me a while to set up spacing, color, fonts.

**Comment by tomekalphawallet** [comment]
![segmented_controls](https://user-images.githubusercontent.com/51817359/72554377-d2bde200-389a-11ea-888f-bcb9748cf331.png)

**Comment by tomekalphawallet** [comment]
@hboon Few small tweaks. It needs to be taller and wider (increase spacing). Also, the bottom line is 1pt "Alto". You have 41 pt bg height (should be 49), and 2pt bottom line (should be 1). 

<img width="1069" alt="Screenshot 2020-02-12 10 51 41" src="https://user-images.githubusercontent.com/51817359/74324778-d6ecfa80-4d87-11ea-9850-c9373bd71fb4.png">

<img width="623" alt="Screenshot 2020-02-12 10 51 31" src="https://user-images.githubusercontent.com/51817359/74324783-d9e7eb00-4d87-11ea-89c1-52f69ddae9bc.png">

<img width="875" alt="Screenshot 2020-02-12 11 06 37" src="https://user-images.githubusercontent.com/51817359/74324801-e10ef900-4d87-11ea-9da8-33ebe4357d43.png">

<img width="978" alt="Screenshot 2020-02-12 11 05 14" src="https://user-images.githubusercontent.com/51817359/74324818-e79d7080-4d87-11ea-937d-639b4be30519.png">

There are some studies, where a minimum tappable area is 44 pt (fingertip).

<img width="593" alt="Screenshot 2020-02-12 11 15 00" src="https://user-images.githubusercontent.com/51817359/74325503-05b7a080-4d89-11ea-95bc-2191c912e357.png">

**Comment by tomekalphawallet** [comment]
Also, kill the top line (in between Search bar and Segmented Controls)

**Comment by hboon** [comment]
@vladyslav-iosdev would you help to check if we missed anything so we can close the issue? I think it's just https://github.com/AlphaWallet/alpha-wallet-ios/issues/1634#issuecomment-585134112

**Comment by vladyslav-iosdev** [comment]
@hboon currently there is no line over segment control on tokens screen.

**Comment by hboon** [comment]
Good then. Thanks
