### ISSUE TITLE
Tokenscript sign challenge return crashes app

### ISSUE THREAD

**Issue by JamesSmartCell** [AlphaWallet/alpha-wallet-ios#1635]
Just started with the latest update:

- go into the sign challenge from the Satoshi Villa (or our front door controller).
- get challenge, sign it
- on success, app crashes, although it successfully sends the signed response as our IoT door device activates correctly, so it may be related to receiving/handling the 'pass' response.

**Comment by hboon** [comment]
@JamesSmartCell Noticed https://github.com/AlphaWallet/TokenScript/issues/311 while attempting to reproduce.

**Comment by James-Sangalli** [comment]
@JamesSmartCell unable to reproduce this but got the aforementioned error stated by boon: 

Failed with: {"timestamp":1580778612516,"status":500,"error":"Internal Server Error","exception":"org.web3j.ens.EnsResolutionException","message":"Unable to determine sync status of node","path":"/api/checkSignature"}

this did not cause the app to crash however, could you please post which version of the app you were using?

**Comment by James-Sangalli** [comment]
Test on iPhone 5s and still can't reproduce. Going to assume this is closed but if it resurfaces feel free to reopen
