### ISSUE TITLE
Props not loading in TokenScript views (2.20/319)

### ISSUE THREAD

**Issue by James-Sangalli** [AlphaWallet/alpha-wallet-ios#1646]
![photo_2020-01-12_12-16-10](https://user-images.githubusercontent.com/16630514/72212721-67d87800-3535-11ea-99cd-71e7ddf218a7.jpg)

sorry @hboon should have caught this during PR review #1645

**Comment by hboon** [comment]
@James-Sangalli reviews can't catch everything. Would help if I didn't break it! :)
