### ISSUE TITLE
View iconified used twice but view is not

### ISSUE THREAD

**Issue by James-Sangalli** [AlphaWallet/alpha-wallet-ios#1654]
<style type="text/css">&style;</style>
      <ts:view-iconified xml:lang="en">
        &icon.en;
      </ts:view-iconified>
      <ts:view xml:lang="en">
        &token.en;
      </ts:view>

only icon will be displayed, the view is ignored.

To test: import 0x63cCEF733a093E5Bd773b41C96D3eCE361464942 and notice that the view iconified and view are the same, despite them being set to different pages. 

TokenScript test: https://github.com/AlphaWallet/TokenScript/blob/master/examples/EntryToken/EntryToken.xml

**Comment by hboon** [comment]
I see this. Is it different for you?

view-iconified | view
-|-
<img src="https://user-images.githubusercontent.com/56189/72403805-46be9400-378e-11ea-91ef-ac377b46ae5e.png" width=200>|<img src="https://user-images.githubusercontent.com/56189/72403806-47572a80-378e-11ea-9146-003214c16b23.png" width=200>

**Comment by James-Sangalli** [comment]
@hboon nope, mine is the same view twice

**Comment by hboon** [comment]
@James-Sangalli  Can you try to duplicate and override that TokenScript file then change the contents to:

```
  <ts:view-iconified xml:lang="en">
    iconified
  </ts:view-iconified>
  <ts:view xml:lang="en">
    view
  </ts:view>
```

And see what happens?

**Comment by James-Sangalli** [comment]
Not getting this now, maybe I was fiddling with an override...
