### ISSUE TITLE
Magic links on FIFA fail

### ISSUE THREAD

**Issue by James-Sangalli** [AlphaWallet/alpha-wallet-ios#1655]
https://etherscan.io/tx/0xb10bb04eec69fcfcb12524924372a4eacd89364b0d44b82a246a7aad2a4323b7

Assert was hit: https://github.com/AlphaWallet/contracts/blob/master/blockchain-tickets/schema1/TicketingContract.sol#L126 (silly me for using assert instead of require! It drains all the gas of the tx!) 

Example failed link: https://aw.app/AQAAAABgAorapmo_CAaBdOjwBREqiyx6UHqCIzU9JMb8G-hBE87L9MOBXb0T0OEju4SyGSeDzAav9Jz9At-QIyRcku06BTMyWXXs30-ThTW36UOwUuLl1mbdtvm_jL0b

Address it came from: 0xbc8dAfeacA658Ae0857C80D8Aa6dE4D487577c63

**Comment by James-Sangalli** [comment]
Solved here: https://github.com/AlphaWallet/PaymentServer/commit/7f2712c484e1cc563a82a636543f93dfc3e7b13b

Paymaster was casting the indices incorrectly, this bug never occurred when the transaction was from the app itself.

**Comment by hboon** [comment]
@James-Sangalli good job!
