### ISSUE TITLE
Update Change Wallet screens [Fiji]

### ISSUE THREAD

**Issue by tomekalphawallet** [AlphaWallet/alpha-wallet-ios#1662]
Sketch Cloud:
https://sketch.cloud/s/e4OJW/v/DP2LVa/a/oE3M0x/
https://sketch.cloud/s/e4OJW/v/DP2LVa/a/YP3Zwm

Zeplin:
https://zpl.io/bWn60RP
https://zpl.io/aX16JzE

- Display ENS reverse lookup if they correspond directly to ETH address
- when you click "Add" display native iOS menu
- Display Blockies
- Display balance
- Display ENS reverse lookup | address in a format 0x, four characters, ellipsis, four last characters

**Comment by tomekalphawallet** [comment]
![change_wallet](https://user-images.githubusercontent.com/51817359/72554840-c8e8ae80-389b-11ea-837c-1eb7ba9196c3.png)

**Comment by hboon** [comment]
@tomekalphawallet would you help take a look to see if the design is the latest?

**Comment by hboon** [comment]
@vladyslav-iosdev note these:

* Display Blockies — out  of scope
* Display ENS reverse lookup | address in a format 0x, four characters, ellipsis, four last characters — there’s a function that does this already. Probably in a String extension. Or in the AlphaWallet.Address class

**Comment by hboon** [comment]
@tomekalphawallet just noticed this: shall we use the standard tick (like we did a while back) instead of the custom radio/checkbox?

**Comment by vladyslav-iosdev** [comment]
@hboon by pressing on account cell it should place checkmark, and then open Manage Wallet Screen. After we return back checkmark should stay on pressed cell, right?

**Comment by vladyslav-iosdev** [comment]
@hboon i what case we need to use radio button, and in what case we need to use check mark?

**Comment by hboon** [comment]
@vladyslav-iosdev it’s going to be one of them only. Start with the tick (the iOS native tick) first. It’s easy to replace if necessary. We’ll wait for Tomek to confirm.

**Comment by vladyslav-iosdev** [comment]
Hi! @hboon currently on design there is no "copy address" action, but it is  in current implementation of showInfoSheet function, do i need to add it? what about "lose wallet", do i need to hide it?

**Comment by hboon** [comment]
@vladyslav-iosdev Hmm.. checking with Tomek. Hold on first.

**Comment by hboon** [comment]
@tomekalphawallet how does the user bring up the 3rd screen? They used to be able to do it by tapping on the disclosure (i) button which is now replaced by the checkbox/tick.

Also @vladyslav-iosdev 's question about "copy address" action.

**Comment by vladyslav-iosdev** [comment]
@hboon  i guess for now behaviour changes, when we tap on cell, we open screen , and when press on circle, we set wallet as current.

**Comment by hboon** [comment]
@vladyslav-iosdev possibly. But not if we change to a tick though.

**Comment by tomekalphawallet** [comment]
> @tomekalphawallet would you help take a look to see if the design is the latest?

yes, confirm.

**Comment by tomekalphawallet** [comment]
tapping on a blockie can take the user to the internal screen (Manage Wallet). See how well this is developed on Android. 

![IMAGE 2020-05-19 14:23:15](https://user-images.githubusercontent.com/51817359/82325901-47856200-99dc-11ea-9e57-e58cf12afbcf.jpg)

**Comment by hboon** [comment]
@tomekalphawallet That’s not conventional iOS behaviour according to the HIG though. Usually it’s either an additional button/switch, or disclosure button on the right to trigger such additional configuration.

What if we move the checkbox to the left (use a more native looking bluish tick like we do In the other screens like Change Language instead?) and still have the disclosure button (i) in the right like we used to, to trigger the Manage Wallet screen?

**Comment by hboon** [comment]
@vladyslav-iosdev I hope you have what you need for now to not be blocked :)

**Comment by vladyslav-iosdev** [comment]
yep, i will switch to #1802

**Comment by tomekalphawallet** [comment]
> @tomekalphawallet That’s not conventional iOS behaviour according to the HIG though. Usually it’s either an additional button/switch, or disclosure button on the right to trigger such additional configuration.
> 
> What if we move the checkbox to the left (use a more native looking bluish tick like we do In the other screens like Change Language instead?) and still have the disclosure button (i) in the right like we used to, to trigger the Manage Wallet screen?

Please always use links to Zeplin, as screenshots uploaded here might be outdated.
The tick should be on the right side. This is native iOS. 

Do we need Manage Wallet screen at all? You can swipe to loose wallet/delete cell.

**Comment by hboon** [comment]
> Do we need Manage Wallet screen at all? You can swipe to loose wallet/delete cell.

@tomekalphawallet Manage Wallet: https://app.zeplin.io/project/5d0356be2f25b319dcc5944b/screen/5dfc1f5011816316437fc424

No I don't have strong opinions on it. I didn't think it was necessary either.

> The tick should be on the right side. This is native iOS.

The tick can appear on the left or right for iOS. It's more common on the right, but since we have a secondary action (to either display an action sheet or the Manage Wallet), then the most conventional way to do it is to let that secondary action be invoked with a control on the right for iOS. In that case, we have to move the tick to the left. The built-in Reminders.app does that for example. Similar for other apps like Settings.app where the control to trigger the secondary action is on the right.

**Comment by tomekalphawallet** [comment]
So I think it's better if we don't have this screen at all "Manage Wallet". Contextual swipe can be use to "loose wallet". Problem solved :)

**Comment by hboon** [comment]
@tomekalphawallet great :) 1 screen less to implement and maintain too )

**Comment by vladyslav-iosdev** [comment]
@tomekalphawallet so how "Change/Add wallet" should look like for now?

**Comment by hboon** [comment]
@vladyslav-iosdev like https://github.com/AlphaWallet/alpha-wallet-ios/issues/1662#issuecomment-575298442

**Comment by vladyslav-iosdev** [comment]
> @vladyslav-iosdev like [#1662 (comment)](https://github.com/AlphaWallet/alpha-wallet-ios/issues/1662#issuecomment-575298442)

@hboon thx!

**Comment by hboon** [comment]
@vladyslav-iosdev sorry about this one. Let's go with this:

A. Tick on the right
B. Tap to switch accounts
C. Tap and hold to bring up the old actionsheet

So it looks exactly like https://github.com/AlphaWallet/alpha-wallet-ios/issues/1662#issuecomment-575298442, except you need to take note of (C).

**Comment by hboon** [comment]
@vladyslav-iosdev sorry about this one. Let's go with this:

A. Tick on the right
B. Tap to switch accounts
C. Swipe to Lose This Wallet and Copy Address
D. Tap and hold to bring up the old actionsheet, but without Copy Address

So it looks exactly like https://github.com/AlphaWallet/alpha-wallet-ios/issues/1662#issuecomment-575298442, except you need to take note of (C).

@tomekalphawallet would you help to update/add the Zeplin for (C)?

**Comment by tomekalphawallet** [comment]
<img width="1360" alt="Screenshot 2020-05-20 11 19 25" src="https://user-images.githubusercontent.com/51817359/82429181-cdacb180-9a8b-11ea-8086-e7e8ba765778.png">

**Comment by tomekalphawallet** [comment]
https://app.zeplin.io/project/5d0356be2f25b319dcc5944b/styleguide/components?cseid=5ec4f4ccb246754987537229

**Comment by tomekalphawallet** [comment]
https://app.zeplin.io/project/5d0356be2f25b319dcc5944b/screen/5ec4f634ea9d4332c3d9f790/

**Comment by vladyslav-iosdev** [comment]
@tomekalphawallet there i no ability to make backup, but in current implementation it exists.

**Comment by hboon** [comment]
> D. Tap and hold to bring up the old actionsheet, but without Copy Address

@vladyslav-iosdev this ^

**Comment by vladyslav-iosdev** [comment]
> > D. Tap and hold to bring up the old actionsheet, but without Copy Address

ok, sorry my fail.
