### ISSUE TITLE
Update FAQ section [Fiji]

### ISSUE THREAD

**Issue by colourfreak** [AlphaWallet/alpha-wallet-ios#1663]
Sketch Cloud:
https://sketch.cloud/s/e4OJW/v/DP2LVa/a/VAEZel
https://sketch.cloud/s/e4OJW/v/DP2LVa/a/pnYOxA
https://sketch.cloud/s/e4OJW/v/DP2LVa/a/enarnP

Zeplin:
https://zpl.io/V0jNrKO
https://zpl.io/VKL97X6
https://zpl.io/brpKAd3

- This one can wait, we need better content
- @jzaki any idea how we can generate the human-friendly content here?

**Comment by tomekalphawallet** [comment]
![faq](https://user-images.githubusercontent.com/51817359/72555268-87a4ce80-389c-11ea-8ad5-5b227fee9df7.png)

**Comment by jzaki** [comment]
> any idea how we can generate the human-friendly content here?

Are you talking about updating the copy?
Also, we don't yet have the feedback mechanism.

**Comment by tomekalphawallet** [comment]
Yes, about updating a copy. 

The feedback mechanism is really simple. If we will have too many downs, it means that something is wrong, we should work on a better copy.

**Comment by hboon** [comment]
Superseded by #2588
