### ISSUE TITLE
Update token icons in Wallet tab [Fiji]

### ISSUE THREAD

**Issue by tomekalphawallet** [AlphaWallet/alpha-wallet-ios#1665]
We will have rounded icons 40x40. It's easy to generate for coins, more difficult for tokens without graphics. For those ones, use colors (Emerald, Indigo, Radical, Pumpkin, Cerulean, Azure, Mine) and up to 4 characters inside (ENS, SFPF, DEFI, DAO). Use the Tokenary app for inspiration. 

If AlphaWallet wants to be the best wallet to hold tokens, we need to make it attractive. In the future, I will provide few more designs how you can manage your tokens quickly (by holding and swiping left to reveal hidden menu) 

Sketch Cloud:
https://sketch.cloud/s/e4OJW/a/oE3MPQ
https://sketch.cloud/s/e4OJW/a/8MQgg8

Zeplin:
https://zpl.io/V0j8yZK
https://zpl.io/VxXB74J

- We are using the same card as we used in "Settings", so we have an icon 40x40, then the same Headline, secondary line (in terms of font)
https://zpl.io/2GdzLDj

**Comment by tomekalphawallet** [comment]
![Tokens_with_icons](https://user-images.githubusercontent.com/51817359/72662253-3c4a0780-39e5-11ea-9ef0-6f960235d86f.png)

**Comment by hboon** [comment]
@tomekalphawallet are the 24hrs/appreciation/value for the native crypto (eth and xDai) removed? If they are, can you help to make a version in the BC project with them? They'll want to keep it.

**Comment by hboon** [comment]
- [ ] Update layout #1903 - token icon
- [ ] Add token icon

**Comment by tomekalphawallet** [comment]
![Zrzut ekranu 2020-06-09 o 08 42 58-kopia](https://user-images.githubusercontent.com/51817359/84119718-0f9a9900-aa35-11ea-9655-5afb257b387c.png)
![Zrzut ekranu 2020-06-09 o 08 42 58](https://user-images.githubusercontent.com/51817359/84119727-11645c80-aa35-11ea-9b4d-629c1ff097c2.png)

**Comment by hboon** [comment]
@tomekalphawallet can you also help provide the icons for these networks like you did for Ethereum mainnet and xDai?

- [ ] ARTIS — https://artis.eco
- [ ] POA — https://www.poa.network
- [ ] Ethereum classic — https://iconscout.com/icon/ethereum-classic-logo
- [ ] callisto — https://callisto.network

**Comment by tomekalphawallet** [comment]
ETC - https://zpl.io/2p6ypo8
POA - https://zpl.io/advnD5R
Callisto - https://zpl.io/bWoKlme
Artis (not sure if this is an official ATS token symbol) - https://zpl.io/VqqmDk5

**Comment by hboon** [comment]
@tomekalphawallet looks great. Thanks!

**Comment by James-Sangalli** [comment]
@tomekalphawallet could you also provide logos for WETH, DAI, WBTC, cDAI and other compound coins plus USDC

**Comment by James-Sangalli** [comment]
@tomekalphawallet actually most well known tokens can have this, including ones like cryptokitties and ENS

**Comment by tomekalphawallet** [comment]
> @tomekalphawallet actually most well known tokens can have this, including ones like cryptokitties and ENS

We have them all ready (ctokens, itokens, ptokens):
https://app.zeplin.io/styleguide/5e0b4e7149e83f987edc0a9e/components?cseid=5e0b16e4ce5cf519870b0316

More generic:
- USDC https://zpl.io/VQj0MDm
- DAI https://zpl.io/beqwzJm
- WBTC https://zpl.io/VDJ8v9W
- iDAI https://zpl.io/brB1r6W
- cDAI https://zpl.io/29QqDeB
- WETH this one is problematic, the one I found online looks like a handwritten, 3d drawing, for that reason I changed it to https://zpl.io/aMAdmO7

**Comment by tomekalphawallet** [comment]
WETH again https://zpl.io/bLz4E97

**Comment by tomekalphawallet** [comment]
Artis again - https://zpl.io/V4mEXv4

**Comment by hboon** [comment]
> Artis again - https://zpl.io/V4mEXv4

@tomekalphawallet Seems like the Artis icon can't be downloaded from there

**Comment by tomekalphawallet** [comment]
updated

**Comment by tomekalphawallet** [comment]
I added 

**a) ptokens:** 

pdai - https://zpl.io/2ENB0GY
psai - https://zpl.io/ag4M3q0
peth - https://zpl.io/2j6QJQr
pbtc - https://zpl.io/2p64JXN
peos - https://zpl.io/VKRPzgP
pusdt - https://zpl.io/VYvKE4L
pltc - https://zpl.io/a7AO00v

b) synthetix tokens

saud - https://zpl.io/VkqG6Lv
sgbp - https://zpl.io/boqDXWo
seur - https://zpl.io/aXxPvD8
sjpy - https://zpl.io/aR51pBr
schf - https://zpl.io/2yAOZXp
susd - https://zpl.io/V049Ej9
sbtc - https://zpl.io/V04qB6l
sxtz - https://zpl.io/2GKy0Nd
sxmr - https://zpl.io/VYvKEmJ
sdefi - https://zpl.io/bJm7Rj3
sada- https://zpl.io/2p64JYN
sltc - https://zpl.io/bJm7Rl9
seth - https://zpl.io/boqDXOW
snikkei - https://zpl.io/bzgNZJ4
sxau - https://zpl.io/aR51JMg
slink - https://zpl.io/beqDEwP

**c) others**
teo - https://zpl.io/a7AO9ZR
eos - https://zpl.io/bzgNEWX
nest - https://zpl.io/VQXLZ74 
link - https://zpl.io/agpvKqO
alphawallet discovery token - https://zpl.io/25D5OwW

**Comment by hboon** [comment]
> I added

Moved to #1958
