### ISSUE TITLE
Is there an ENS contract for xDai?

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#1684]
This line:

static let ENSRegistrarXDAI = AlphaWallet.Address(string: "0x17734f3709486b1d7015f941c069cebf8017a833")!

Probably related to https://github.com/AlphaWallet/alpha-wallet-ios/issues/991#issuecomment-454351375

Is it supposed to work?

**Comment by James-Sangalli** [comment]
Nah, think I forked that myself... no need to keep
