### ISSUE TITLE
Actionsheet-style confirmation for TokenScript transactions

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#1687]

**Comment by zhangzhongnan928** [comment]
Is this issue related to below? @hboon 

We should use the standard confirmation page to replace the current TokenScript confirmation page.

![IMG_3451](https://user-images.githubusercontent.com/33795543/84618827-ac1dd900-af16-11ea-83c5-d9c68928377d.PNG)

![IMG_3450](https://user-images.githubusercontent.com/33795543/84618832-ade79c80-af16-11ea-83dc-42e8f17fffbb.PNG)

**Comment by hboon** [comment]
> Is this issue related to below? @hboon

Yes, it is.

> If it is still quite far from the "final" solution, we should use the standard confirmation page to replace the current TokenScript confirmation page for now.

Ok. Will check.
