### ISSUE TITLE
Actionsheet-style confirmation for importing MagicLink (paid)

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#1688]

**Comment by oa-s** [comment]
@hboon can u remind me how to trigger it?

**Comment by hboon** [comment]
@oa-s never mind that. Seems like it is done already:

![IMG_9403](https://user-images.githubusercontent.com/56189/149472179-7b8bedf1-8a52-482b-8fb5-ce2df531a759.PNG)
