### ISSUE TITLE
Support button doesn’t seem to work

### ISSUE THREAD

**Issue by hellolucas** [AlphaWallet/alpha-wallet-ios#1693]
User reports the Contact Us button found in Help & FAQs did not work. 

Device: iPhone 7 and iPhone 11
OS: iOS 13.3

**Comment by hboon** [comment]
@nimitparekh2020 This is the yellow banner in Settings tab > Help & FAQs. Can you verify if this is still a problem and fix it if it is.

**Comment by nimitparekh2020** [comment]
@hboon - It's working...

**Comment by hboon** [comment]
Thanks
