### ISSUE TITLE
Error message & failure when transferring POAP tokens

### ISSUE THREAD

**Issue by hellolucas** [AlphaWallet/alpha-wallet-ios#1694]
User has a wallet with ETH + [POAP](https://www.poap.xyz/) token collectables.

When trying to transfer these POAP collectables to another wallet, he gets an error message saying “Your Token was not transferred” and the transfer fails.

Device: iPhone 7 and iPhone 11
OS: iOS 13.3

**Comment by James-Sangalli** [comment]
@hellolucas does said user have eth?

**Comment by hboon** [comment]
He has a backup from his old phone.

**Comment by hellolucas** [comment]
> @hellolucas does said user have eth?

He does, the user is Franco Zeoli (@fzeoli) from AW group, there might be a group chat associated with him.

**Comment by hboon** [comment]
Close from inactivity. Reopen if it or something similar pops up
