### ISSUE TITLE
"Can't access your wallet" Failure to backup wallet by exporting Keystore JSON

### ISSUE THREAD

**Issue by hellolucas** [AlphaWallet/alpha-wallet-ios#1695]
User fails to backup wallet by exporting Keystore JSON.

Receives message “Can’t access your wallet. Import your wallet again or enable passcode”

Device: iPhone 7 and iPhone 11
OS: iOS 13.3

**Comment by hboon** [comment]
NB: same user as #1694

**Comment by hboon** [comment]
Close from inactivity. Reopen if it or something similar pops up
