### ISSUE TITLE
Update Back up with Seed illustration

### ISSUE THREAD

**Issue by tomekalphawallet** [AlphaWallet/alpha-wallet-ios#1700]
This is what we have now:
![2020-02-10 11 07 20](https://user-images.githubusercontent.com/51817359/74141016-75495680-4bf6-11ea-8c4d-adc4810e53ea.png)

This is an updated illustration:
![Backup_Introduction](https://user-images.githubusercontent.com/51817359/74141172-b9d4f200-4bf6-11ea-8891-6bad1366ec42.png)

Sketch Cloud:
https://sketch.cloud/s/e4OJW/a/vngxyn

Zeplin:
https://app.zeplin.io/project/5d0356be2f25b319dcc5944b/screen/5e09f5de2149329a03eb4586/

**Comment by tomekalphawallet** [comment]
I have just updated this illustration. Please overwrite the existing one (Zeplin).

**Comment by hboon** [comment]
@vladyslav-iosdev remember to check the Zeplin version. Screenshot might be outdated.
