### ISSUE TITLE
Update Lock up seed phrase illustration

### ISSUE THREAD

**Issue by tomekalphawallet** [AlphaWallet/alpha-wallet-ios#1701]
Updated look:
![Backup_Lock_Intro](https://user-images.githubusercontent.com/51817359/74141398-23550080-4bf7-11ea-841f-725abca78de2.png)

Sketch Cloud:
https://sketch.cloud/s/e4OJW/a/rm39jA

Zeplin:
https://zpl.io/VQ746Kn

**Comment by tomekalphawallet** [comment]
I have just updated this illustration. Please overwrite the existing one (Zeplin).

**Comment by hboon** [comment]
@vladyslav-iosdev remember to check the Zeplin version to be sure. (screenshot might be outdated)

**Comment by vladyslav-iosdev** [comment]
@hboon can you tell me how can i get to this screen?

**Comment by hboon** [comment]
@vladyslav-iosdev from Settings > Change Wallet. Then the i button and show seed phrase. Toward the end of the backup process, it should prompt you to lock it (if it hasn’t locked this seed phrase before).

**Comment by tomekalphawallet** [comment]
<img width="1910" alt="Screenshot 2020-05-26 at 16 19 27" src="https://user-images.githubusercontent.com/51817359/82911864-af075880-9f6c-11ea-9a4f-59f283ba7c65.png">
