### ISSUE TITLE
Update TS buttons

### ISSUE THREAD

**Issue by tomekalphawallet** [AlphaWallet/alpha-wallet-ios#1702]
Sketch Cloud:
https://sketch.cloud/s/e4OJW/a/jz34zG
https://sketch.cloud/s/e4OJW/a/dP3gP9
https://sketch.cloud/s/e4OJW/a/zRdyRr
https://sketch.cloud/s/e4OJW/a/ZbrVbG

Zeplin:
- https://app.zeplin.io/project/5d0356be2f25b319dcc5944b/dashboard?seid=5e4130b758245792d0d24970

Finally confirmed and approved by @colourful-land

**Comment by tomekalphawallet** [comment]
![Screenshot 2020-02-10 11 39 18](https://user-images.githubusercontent.com/51817359/74142855-ff46ee80-4bf9-11ea-94aa-8eea9e2cda0a.png)

**Comment by tomekalphawallet** [comment]
@colourful-land wants to outsource this part to new developers on Upwork - and hire the one who provided the highest quality.

**Comment by hboon** [comment]
I think the buttons are displayed in:

* TokensCardViewController
* TokenViewController
* TokenInstanceViewController

Replace the instance of ButtonsBar with a new type cloned from ButtonsBar

**Comment by hboon** [comment]
Superseded by #1819
