### ISSUE TITLE
The gray background looks strange

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/alpha-wallet-ios#1712]
![9CBBA0C3-658B-4148-87DF-A96BB9475DC3](https://user-images.githubusercontent.com/33795543/74330453-d8e5a680-4de5-11ea-940a-a89f1bb37bf9.jpeg)

**Comment by hboon** [comment]
Ah indeed. Let’s see if I can change it.

**Comment by tomekalphawallet** [comment]
@hboon Please make the background white. Use "Alabaster" gray only if you don't have enough tokens in the list (below xDAI). 
<img width="469" alt="Screenshot 2020-02-12 13 07 23" src="https://user-images.githubusercontent.com/51817359/74333686-c002d400-4d98-11ea-8ea9-178c9ff9ab20.png">

**Comment by jzaki** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[__] As a user, I want understanding/control over transaction processing time, so that I can transact with confidence](https://trello.com/c/26MTjbSU/70-as-a-user-i-want-understanding-control-over-transaction-processing-time-so-that-i-can-transact-with-confidence)

**Comment by hboon** [comment]
> ![](https://camo.githubusercontent.com/193766a3b9959c5f4ed5cd8cf3251d015e839d51/68747470733a2f2f6769746875622e7472656c6c6f2e73657276696365732f696d616765732f6d696e692d7472656c6c6f2d69636f6e2e706e67) [[__] As a user, I want understanding/control over transaction processing time, so that I can transact with confidence](https://trello.com/c/26MTjbSU/70-as-a-user-i-want-understanding-control-over-transaction-processing-time-so-that-i-can-transact-with-confidence)

@jzaki is this the correct issue?

**Comment by jzaki** [comment]
The list in trello auto-updated under my click (still created the comment). Was referencing a different git-issue.
Will delete the comment to avoid confusion :)

**Comment by hboon** [comment]
Moved to #1818
