### ISSUE TITLE
All-encompassing QR code scanner

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#1723]
So that QR code scanner can be available in various screens and "jump" to the right screen depending on what is scanned instead of the ones we have now which only allows users to scan what is supported in the current screen.

Let’s make the scanner functionality configurable with options - for handling EIP681, WalletConnect etc -, mirroring how UIImagePickerController allows us to choose from photo, library, all, etc.

There’s a Zeplin screen which has the button, but let’s assume it’s a button available in the Wallets tab navigation bar (because: see Out of Scope below). 

Out of scope 
—-
When this is available, we should probably also make it available in the quick action list accessibly by tapping and holding the app icon in the iOS home screen.

**Comment by hboon** [comment]
Possible dup of #1214

**Comment by tomekalphawallet** [comment]
https://github.com/AlphaWallet/alpha-wallet-ios/issues/1738

Dup?

**Comment by vladyslav-iosdev** [comment]
@hboon  As i undarstand right, for this task i need update QRCodeReaderViewController add there my qr button. Right? but what the next? as i undarstand right if user tap my qr button it will start Wallet Connect client's session to get URL to connect.  What else i need to do here?

**Comment by hboon** [comment]
Oh. No. This is to add a button eg like the wallet tab. Tap the button and the QR scanner appears. If we scan an EIP681 payment link, go to the send screen, prefilled (like scanning the QR code in the send screen which you worked on recently). Or scan something else and another appropriate screen appear.

If you added My QR button, that’s fine too as a separate PR (I think you pushed that). But that’s another issue. We might have that issue somewhere I think.

Makes sense?

**Comment by vladyslav-iosdev** [comment]
> EIP681

Got it. Also i have a few questions:
what should happen when we tap on each action from didScanQRCode alert?
https://user-images.githubusercontent.com/51817359/75242825-19bbc300-57c9-11ea-862d-cf5e688b8aed.png
as i undastand when we tap it opens send token screen
but what should happens when we tap on watch, i need manually add it through `keystore.importWallet(type: importType)`
or show import wallet screen and fill it with scanned qr code?
also what should happen when we tap on add to address book?

**Comment by hboon** [comment]
Oh, I forgot to link to #1738. You can refer to it :) Would you verify if the flows are correct?

**Comment by vladyslav-iosdev** [comment]
> Oh, I forgot to link to #1738. You can refer to it :) Would you verify if the flows are correct?

@hboon i already added ability to watch wallet and open URL, now i want to work on "select asset" flow. do i need to add it in current PR, or it will be in separate one?

**Comment by vladyslav-iosdev** [comment]
also i am not able to open this link
https://drive.google.com/a/alphawallet.com/file/d/14ge8G3pIM513myKZbDrUyjA2bvRGzFXR/view?usp=sharing

**Comment by hboon** [comment]
> > Oh, I forgot to link to #1738. You can refer to it :) Would you verify if the flows are correct?
> 
> @hboon i already added ability to watch wallet and open URL, now i want to work on "select asset" flow. do i need to add it in current PR, or it will be in separate one?

Up to you, if you think the entire PR including the flow wouldn't touch too many files (and thus hard to merge, especially if we don't merge it quickly) then you can build it together if you like.

Otherwise you can break it up and we can just disable the new QR scanner button first and merge the rest in (with some of the other functionality still complete, though not exposed to the user).

**Comment by hboon** [comment]
> also i am not able to open this link
> https://drive.google.com/a/alphawallet.com/file/d/14ge8G3pIM513myKZbDrUyjA2bvRGzFXR/view?usp=sharing

There you go: [QR_Code_Scanner.pdf](https://github.com/AlphaWallet/alpha-wallet-ios/files/4937353/QR_Code_Scanner.pdf)

**Comment by vladyslav-iosdev** [comment]
> QR_Code_Scanner.pdf

thx!

**Comment by vladyslav-iosdev** [comment]
@hboon one more question 
how could i determine whether it "Add Custom Token" or token for "Scan Ethereum Address" flow? also what does it mean "add to address book", does application has this ability?

**Comment by hboon** [comment]
>@hboon just few questions: ...

@vladyslav-iosdev we can’t tell if the user wants to add a custom token or watch wallet etc give just an Ethereum address. Will have to ask the user with an actionsheet.

You can ignore the “address book” functionality for now across all issues/PRs. It’s not designed completely yet.

**Comment by vladyslav-iosdev** [comment]
> book

ok, so i can replace addToAddressBook action with addCustomToken, right?

**Comment by vladyslav-iosdev** [comment]
> > @hboon just few questions: ...
> 
> @vladyslav-iosdev we can’t tell if the user wants to add a custom token or watch wallet etc give just an Ethereum address. Will have to ask the user with an actionsheet.
> 
> You can ignore the “address book” functionality for now across all issues/PRs. It’s not designed completely yet.

ok, so i can replace addToAddressBook action with addCustomToken, right?

**Comment by vladyslav-iosdev** [comment]
@hboon this one seems like is ready for review.
