### ISSUE TITLE
Transactions should be rename to activities 

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/alpha-wallet-ios#1725]
![1BC8FEC4-6BBB-4714-8572-F81993553CF4](https://user-images.githubusercontent.com/33795543/74885693-51da9480-53ca-11ea-9ab8-6f9fa6f21ba9.jpeg)

**Comment by hboon** [comment]
Only when we implement Activities in the tab after adding events support.

**Comment by zhangzhongnan928** [comment]
> Only when we implement Activities in the tab after adding events support.

agreed

**Comment by hboon** [comment]
Done with #2180
