### ISSUE TITLE
URL in bookmarks and history list not visible because they are have the same color (white) as the background

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#1726]
URL is visible when user taps on the cell:

Bookmarks | History | Output
-|-|-
<img src="https://user-images.githubusercontent.com/56189/75002361-1d84d800-549f-11ea-9328-c68e9d345b1c.png" width=200>|<img src="https://user-images.githubusercontent.com/56189/75002363-207fc880-549f-11ea-8b14-98cd471a3233.png" width=200>|<img src="https://user-images.githubusercontent.com/708425/78222192-6d18e380-74e2-11ea-81f2-a5c762ed2cda.png" width=200>

**Comment by hboon** [comment]
@nimitparekh2020

**Comment by nimitparekh2020** [comment]
I changed to commit message.
