### ISSUE TITLE
iOS: Accept new `<view>` and `<item-view>` and drop the support for old `<view>` and `<view-iconified>`

### ISSUE THREAD

**Issue by James-Sangalli** [AlphaWallet/alpha-wallet-ios#1728]

**Comment by James-Sangalli** [comment]
@hboon this still doesn't work, if you try with karma token you will see that the item view and view are ignored completely. Try with: https://rinkeby.aw.app/AQAAAABetMZydcssw4DROHp57mSxt8n6BRE5oxkLCgkEP5lwSnhoRFKZZunc7GuI-fNi76c6zB1JoTQEn8Rw6iohMHmW1jVoNvN0UYfF8W-IlPx6cvIHnu-bqr6Ujxw=

**Comment by hboon** [comment]
@James-Sangalli can you generate another MagicLink for me?

**Comment by James-Sangalli** [comment]
https://rinkeby.aw.app/AQAAAABgnFYmdcssw4DROHp57mSxt8n6BRE5oxkLEd31LIggVn20fwOtnzmUzyeYzxmS0JqwLEQhC5UiNqR9rGC4Af_7OqonC60yWJY6LM1ATMrGgDKFuhYq473mSRs=
