### ISSUE TITLE
Add Smart QR Code Scanner [Fiji]

### ISSUE THREAD

**Issue by tomekalphawallet** [AlphaWallet/alpha-wallet-ios#1738]
Sketch Cloud:
https://sketch.cloud/s/e4OJW/p/qr-code-scanner

Zeplin:

1.  When scanning ETH Address 
- https://app.zeplin.io/project/5d0356be2f25b319dcc5944b/dashboard?seid=5e54e32e4bd7446694188199
- https://app.zeplin.io/project/5d0356be2f25b319dcc5944b/dashboard?seid=5e54e423716ee76784edcb52
- https://app.zeplin.io/project/5d0356be2f25b319dcc5944b/dashboard?seid=5e54e4a388f5977842798088

2. When scanning Payment Request
- https://app.zeplin.io/project/5d0356be2f25b319dcc5944b/dashboard?seid=5e54e10a20f88c73440ee6b6

3. When scanning to add custom token
https://app.zeplin.io/project/5d0356be2f25b319dcc5944b/dashboard?seid=5e54e03f88f59778427953c5

4. When scanned QR is not ETH
https://app.zeplin.io/project/5d0356be2f25b319dcc5944b/dashboard?seid=5e54e127444316639e4091e2

5. When QR is a link (to open in browser)
https://app.zeplin.io/project/5d0356be2f25b319dcc5944b/dashboard?seid=5e54e176ff4f2f6494e7d0eb

Flow
https://drive.google.com/a/alphawallet.com/file/d/14ge8G3pIM513myKZbDrUyjA2bvRGzFXR/view?usp=sharing

**Comment by tomekalphawallet** [comment]
When scanning ETH Address - Add to Contacts

<img width="1709" alt="Screenshot 2020-02-25 12 13 49" src="https://user-images.githubusercontent.com/51817359/75242746-f4c75000-57c8-11ea-9d2a-78260c2bfe2d.png">

When scanning ETH Address - Watch Wallet

<img width="1316" alt="Screenshot 2020-02-25 12 13 55" src="https://user-images.githubusercontent.com/51817359/75242797-0872b680-57c9-11ea-8b61-edcd3faf6217.png">

When scanning ETH Address - Send to the Address

<img width="2072" alt="Screenshot 2020-02-25 12 13 46" src="https://user-images.githubusercontent.com/51817359/75242825-19bbc300-57c9-11ea-862d-cf5e688b8aed.png">

When scanning Payment Request

<img width="1436" alt="Screenshot 2020-02-25 12 15 27" src="https://user-images.githubusercontent.com/51817359/75242861-2a6c3900-57c9-11ea-9de8-ba22b7568cea.png">

When scanning to add custom token

<img width="1769" alt="Screenshot 2020-02-25 12 12 32" src="https://user-images.githubusercontent.com/51817359/75242901-41129000-57c9-11ea-9785-0524dd277040.png">

When scanned QR is not ETH

<img width="1356" alt="Screenshot 2020-02-25 12 15 22" src="https://user-images.githubusercontent.com/51817359/75242929-4bcd2500-57c9-11ea-9252-106b38d8b6e7.png">

When QR is a link (to open in browser)

<img width="1694" alt="Screenshot 2020-02-25 12 14 11" src="https://user-images.githubusercontent.com/51817359/75242965-5be50480-57c9-11ea-9716-d5daa960ec54.png">

**Comment by hboon** [comment]
Closed with #2037
