### ISSUE TITLE
Add Manage Tokens [Fiji]

### ISSUE THREAD

**Issue by tomekalphawallet** [AlphaWallet/alpha-wallet-ios#1739]
Sketch Cloud:
https://sketch.cloud/s/e4OJW/p/manage-tokens

Zeplin:
https://app.zeplin.io/project/5d0356be2f25b319dcc5944b/dashboard?seid=5e5508fe6be802745d7b1e92

**Comment by tomekalphawallet** [comment]
This is the normal view (you don't have a search bar and "Add/Hide Tokens" visible). Only if you swipe it down, you reveal "Add/Hide Tokens" and search input field.

<img width="1463" alt="Screenshot 2020-02-25 13 00 15" src="https://user-images.githubusercontent.com/51817359/75246088-52f73180-57cf-11ea-88c5-22e515795be6.png">

This is a native iOS but tunned to have "Add/Hide" Tokens".

https://www.dropbox.com/s/c90phfe10fsxcpe/2020-02-25%2012.59.36.mp4?dl=0
https://www.dropbox.com/s/f5lw8tczi78qs0z/2020-02-25%2013.02.09.mp4?dl=0

Then, if there is a new token dropped, you will have a notification in there (and when a system detects new token there, "Add/Hide Tokens" button needs to be revealed immediately.

<img width="1000" alt="Screenshot 2020-02-25 13 00 21" src="https://user-images.githubusercontent.com/51817359/75246544-46270d80-57d0-11ea-96a1-af0701f0d096.png">

Contextual swipes to Send/Hide Tokens

<img width="1826" alt="Screenshot 2020-02-25 13 00 29" src="https://user-images.githubusercontent.com/51817359/75246569-5343fc80-57d0-11ea-8356-8eda7e13c514.png">

<img width="1876" alt="Screenshot 2020-02-25 13 00 35" src="https://user-images.githubusercontent.com/51817359/75246575-57701a00-57d0-11ea-8c6a-480290570c88.png">

**Comment by tomekalphawallet** [comment]
We have an updated design here:

<img width="907" alt="Screenshot 2020-02-27 10 13 53" src="https://user-images.githubusercontent.com/51817359/75651269-53248080-5c58-11ea-8fee-a4946962eafb.png">

**Comment by hboon** [comment]
@tomekalphawallet I think we should make the "DISPLAYED TOKENS" and "HIDDEN TOKENS" scroll separately as 2 separate lists. Does the design need to be tweaked a bit to show that?

**Comment by tomekalphawallet** [comment]
I would rather avoid it. Let's stick to the native iOS. 

https://drive.google.com/a/alphawallet.com/file/d/1th6lM650cK2dVMK2cfQ_KoYVvOLSw2yw/view?usp=sharing

**Comment by hboon** [comment]
It is native iOS.

I’m referring to how it would be difficult to scroll though a long list when the user has both visible and hidden tokens. But let’s implement it and see how it goes.
