### ISSUE TITLE
Update Input Fields look [Fiji]

### ISSUE THREAD

**Issue by tomekalphawallet** [AlphaWallet/alpha-wallet-ios#1742]
This is almost the last update of Fiji. The one remaining is a redesign of ERC20, ERC721 tokens. 

Zeplin:

1. Blank
https://app.zeplin.io/project/5d088205bff2d15de6a4397b/styleguide/components?cseid=5e218a805b5b617d8eec7aef

2. Entering
https://app.zeplin.io/project/5d088205bff2d15de6a4397b/styleguide/components?cseid=5e218c6773e393a79c640116

3. Entered
https://app.zeplin.io/project/5d088205bff2d15de6a4397b/styleguide/components?cseid=5e218cbacf6a85ab00ee4d3b

4. Error
https://app.zeplin.io/project/5d088205bff2d15de6a4397b/styleguide/components?cseid=5e218d1b0f5ab5ab7cdca668

----

![input_fields_ios](https://user-images.githubusercontent.com/51817359/82033944-c48f9f00-969d-11ea-84e0-d64795cb4a4e.jpg)

**Comment by tomekalphawallet** [comment]
We have many examples of use.

a) importing wallet
<img width="923" alt="Screenshot 2020-02-26 16 19 09" src="https://user-images.githubusercontent.com/51817359/75358932-ebff7880-58b3-11ea-8c69-3836e420a0f5.png">
<img width="1261" alt="Screenshot 2020-02-26 16 18 54" src="https://user-images.githubusercontent.com/51817359/75358938-ee61d280-58b3-11ea-9742-6c0383041031.png">
<img width="1326" alt="Screenshot 2020-02-26 16 18 22" src="https://user-images.githubusercontent.com/51817359/75358951-f1f55980-58b3-11ea-99ec-af4e05b415db.png">

b) setting up transactions/deals

<img width="836" alt="Screenshot 2020-02-26 16 19 16" src="https://user-images.githubusercontent.com/51817359/75359006-05a0c000-58b4-11ea-9061-b6aa96382c66.png">
<img width="847" alt="Screenshot 2020-02-26 16 19 34" src="https://user-images.githubusercontent.com/51817359/75359016-09344700-58b4-11ea-9487-edda82818479.png">

**Comment by tomekalphawallet** [comment]
Updated a new numeric text field. We have a component now, that will be used  in:
- dai/xdai bridge
- send coin
- supply to defi
- fiat on-ramp

**Comment by vladyslav-iosdev** [comment]
Hi! @hboon  can you assign me to this task i didn't find any way to do this. Also, as i understood i need to pull latest updates from master right?

**Comment by hboon** [comment]
@vladyslav-iosdev assigned. Yes, work on a feature branch you fork from the latest ‘master’. Thanks.

I haven’t looked deeply into this issue, but note that there are at least 2 classes that might be affected AmountTextField and AddressTextField as well as general usage of UITextField.

**Comment by vladyslav-iosdev** [comment]
ok, thx! i will explore them and will start update.

**Comment by vladyslav-iosdev** [comment]
i pulled master branch, update pods, and ran project. it seems like it does not contain updated i made before, does its ok? also i get crash when press settings tabbar button.

**Comment by hboon** [comment]
The PR you worked on hasn't been merged yet (my bad, will get to it).

Verify that your local `master` is the same as this: https://github.com/AlphaWallet/alpha-wallet-ios/commits/master.

I think it might be crashing because of database migrations which your last PR included. Delete the app and installing again should work.

If it still crashes, debug it and file and issue :)

**Comment by vladyslav-iosdev** [comment]
no, it get crashed i when update table view cells on settings. migration works ok, but any way i will reinstall app.

**Comment by vladyslav-iosdev** [comment]
@hboon i have several questions:
<img width="813" alt="Screenshot 2020-05-14 at 17 10 14" src="https://user-images.githubusercontent.com/55975226/81944752-de7da300-9605-11ea-88bb-967795368911.png">

do i need to add ETH Amount label, over every AmountTextField?
how fiatButton from AmountTextField shpuld be placed in textField? does it need to be moved over entered text?

**Comment by hboon** [comment]
> do i need to add ETH Amount label, over every AmountTextField?

Yes. And the grayed out "ETH" (of 4.342 ETH) text changes to USD if the user taps on the USD button (and the blue-ish USD button text changes to ETH). So the existing AmountTextField.fiatButton has split into a button and a new label.

> how fiatButton from AmountTextField shpuld be placed in textField?

Answered above.

> does it need to be moved over entered text?

I don't understand. But I'm guessing this: if the ETH (or USD) amount is a longer string of numbers than in the screenshot above, then the "currency" should be positioned to its right eg. "123456789.12  ETH".

Also don't add the "All Funds" button. The functionality isn't available at the moment.

@vladyslav-iosdev  There appears to be a few types of text fields, at least a normal type and, AmountTextField and AddressTextField. So if it's easier for you, you can split them into separate PRs. Up to you which one to go first.

**Comment by tomekalphawallet** [comment]
> @hboon i have several questions:
> <img alt="Screenshot 2020-05-14 at 17 10 14" width="813" src="https://user-images.githubusercontent.com/55975226/81944752-de7da300-9605-11ea-88bb-967795368911.png">
> 
> do i need to add ETH Amount label, over every AmountTextField?
> how fiatButton from AmountTextField shpuld be placed in textField? does it need to be moved over entered text?

This input field does not exist anymore. Every time you have you enter an amount (numeric input field) use:

<img width="827" alt="Screenshot 2020-05-14 at 18 49 56" src="https://user-images.githubusercontent.com/51817359/81962518-1ee41d80-9614-11ea-931c-0f20f78a3da1.png">

Examples of use:
https://app.zeplin.io/project/5d0356be2f25b319dcc5944b/screen/5dfc4ba7aa48e01aa20e886e/
https://app.zeplin.io/project/5d0356be2f25b319dcc5944b/screen/5e78c4d7586886702d73747e/

**Comment by hboon** [comment]
@tomekalphawallet my bad. Can you help to update the 1st comment? Or post a new one to replace it?

**Comment by vladyslav-iosdev** [comment]
Hi everyone! @tomekalphawallet what should happen when user press 1? does any drop down should appear? and @hboon do i need to show it (2) for now? and also currenlty we have alternativeAmountLabel in AmountTextField where do i need to show it?
 
![Group](https://user-images.githubusercontent.com/55975226/82026528-86917b80-969b-11ea-92b7-8ebd60b4c80f.png)

**Comment by hboon** [comment]
> 1. does any drop down should appear?
> 2. and @hboon do i need to show it (2) for now?

@tomekalphawallet what is this supposed to do? We currently only toggle between ETH and Fiat (USD). We don't have a case yet where we switch between tokens or other fiat currencies yet.

> currently we have alternativeAmountLabel in AmountTextField where do i need to show it?

@tomekalphawallet this is referring to the green "~ 0.00 USD" (or xxx ETH when switched). Where does it go with the updated design?

<img width="200" alt="81944752-de7da300-9605-11ea-88bb-967795368911" src="https://user-images.githubusercontent.com/56189/82027008-2c59e000-96c6-11ea-8c8e-49dee51bd53e.png">

**Comment by tomekalphawallet** [comment]
> @tomekalphawallet my bad. Can you help to update the 1st comment? Or post a new one to replace it?

Done

**Comment by tomekalphawallet** [comment]
@hboon @vladyslav-iosdev 

When I spoke with @colourful-land, he requested to hide this "arrow" for any transaction, where you are sending ERC20, Ether. I intended to keep it as a way to change between USD/ETH, but we decided to not have this option.

However, this arrow will appear when you are buying crypto with fiat money (fiat on-ramp). In that case, you can switch which currency you want to use to buy crypto.

https://www.dropbox.com/s/w39osx5um4i90xb/amount_input_field.mov?dl=0

**Comment by tomekalphawallet** [comment]
> Also don't add the "All Funds" button. The functionality isn't available at the moment.

As mentioned in the video, it will be nice to have it. It takes the available funds, deducts estimated gas fee and you have "All funds". This way, you will never have error when you want to send all funds and you forgot about deducting gas fee. 

https://ethgasstation.info/

**Comment by tomekalphawallet** [comment]
> @tomekalphawallet this is referring to the green "~ 0.00 USD" (or xxx ETH when switched). Where does it go with the updated design?

It does not exist. You have this arrow visible only when buying crypto with fiat, and you want to change currency. In transactions like Send ETH, Send DAI, Send LINK - you can only enter the amount in the cryptocurrency (no USD).

**Comment by vladyslav-iosdev** [comment]
@hboon 
<img width="287" alt="Screenshot 2020-05-15 at 12 39 37" src="https://user-images.githubusercontent.com/55975226/82036164-37eade00-96a9-11ea-8988-9487d33afd75.png">
here we have address textView, but in current implementation we have textField do i need to create address textView or can left updated textField?

<img width="432" alt="Screenshot 2020-05-15 at 12 43 20" src="https://user-images.githubusercontent.com/55975226/82036540-ae87db80-96a9-11ea-93ad-438d400536f9.png">
Also on next image there is scan button but on first image there is no this scan button
<img width="135" alt="Screenshot 2020-05-15 at 12 45 02" src="https://user-images.githubusercontent.com/55975226/82036731-eee75980-96a9-11ea-9836-de542e57c82b.png">

**Comment by tomekalphawallet** [comment]
https://zpl.io/259QAAr
https://zpl.io/aX1rqpX

Updated.

**Comment by vladyslav-iosdev** [comment]
@tomekalphawallet thx!

**Comment by hboon** [comment]
>> @tomekalphawallet this is referring to the green "~ 0.00 USD" (or xxx ETH when switched). Where does it go with the updated design? ...

@tomekalphawallet we have this functionality all along. Can we add that back? Our white label project will also want it.

**Comment by tomekalphawallet** [comment]
> @tomekalphawallet we have this functionality all along. Can we add that back? Our white label project will also want it.
 Can you confirm with Weiwu? If he is OK, we can keep arrow.

**Comment by hboon** [comment]
Checking. @vladyslav-iosdev assume it’s there for now so it doesn’t block your work.

**Comment by vladyslav-iosdev** [comment]
its seems like no blockers for now
one question: what it is, and do i need to show it?
<img width="529" alt="Screenshot 2020-05-15 at 14 19 00" src="https://user-images.githubusercontent.com/55975226/82045061-18f34880-96b7-11ea-8c33-048933d5cc79.png">

**Comment by vladyslav-iosdev** [comment]
aloso on this screen we also have address text field, but without paste and clear buttons, do i need to add them?
 
<img width="254" alt="Screenshot 2020-05-15 at 14 22 26" src="https://user-images.githubusercontent.com/55975226/82045299-8acb9200-96b7-11ea-845d-d0796b418ed6.png">

**Comment by tomekalphawallet** [comment]
ENS - think of it as DNS but for blockchain, instead of not human-readable addresses (26 characters 0x...) , you can buy a domain and reverse it back to your address. So every time you enter tomek.eth it will send funds to my address.

**Comment by tomekalphawallet** [comment]
> aloso on this screen we also have address text field, but without paste and clear buttons, do i need to add them?
> 
> <img alt="Screenshot 2020-05-15 at 14 22 26" width="254" src="https://user-images.githubusercontent.com/55975226/82045299-8acb9200-96b7-11ea-845d-d0796b418ed6.png">

Yes, please.

**Comment by hboon** [comment]
@vladyslav-iosdev there is an existing UILabel for the ENS name in the AddressTextField class. So you can use that.

**Comment by hboon** [comment]
The 2 classes are designed so that the “components” can be laid out differently by the user. That’s why they are not all in a single UIView/UIControl subclass

**Comment by vladyslav-iosdev** [comment]
does it look like on design?
<img width="254" alt="Screenshot 2020-05-15 at 14 22 26" src="https://user-images.githubusercontent.com/55975226/82047105-e2b7c800-96ba-11ea-904d-f2512e91f2bd.png">
<img width="432" alt="Screenshot 2020-05-15 at 14 41 03" src="https://user-images.githubusercontent.com/55975226/82047107-e4818b80-96ba-11ea-973d-96118a9af311.png">
<img width="432" alt="Screenshot 2020-05-15 at 14 45 19" src="https://user-images.githubusercontent.com/55975226/82047112-e64b4f00-96ba-11ea-85db-a3784cfc8300.png">
<img width="432" alt="Screenshot 2020-05-15 at 14 45 28" src="https://user-images.githubusercontent.com/55975226/82047113-e77c7c00-96ba-11ea-8330-54325f6b4f6c.png">
<img width="432" alt="Screenshot 2020-05-15 at 14 45 33" src="https://user-images.githubusercontent.com/55975226/82047116-e8151280-96ba-11ea-82eb-12f03979b9f9.png">
<img width="432" alt="Screenshot 2020-05-15 at 14 45 40" src="https://user-images.githubusercontent.com/55975226/82047119-e8ada900-96ba-11ea-9f92-49d7d9e80a06.png">
<img width="432" alt="Screenshot 2020-05-15 at 14 45 51" src="https://user-images.githubusercontent.com/55975226/82047121-e9463f80-96ba-11ea-9265-07110e7fcbd3.png">
<img width="432" alt="Screenshot 2020-05-15 at 14 45 56" src="https://user-images.githubusercontent.com/55975226/82047124-e9ded600-96ba-11ea-8bc3-c77345d434fb.png">

**Comment by vladyslav-iosdev** [comment]
one more question about address text field title
<img width="265" alt="Screenshot 2020-05-15 at 14 47 19" src="https://user-images.githubusercontent.com/55975226/82047229-1e529200-96bb-11ea-99b3-90289fac8524.png">
here we have  "Contract address" and on screen you provided there is "Enter ETH Address / ENS"
do i need to replace it with "Enter ETH Address / ENS" or left as it is?

**Comment by vladyslav-iosdev** [comment]
@hboon  for now every textfield has uppercased title, do i need to replace it with Capitalized title?

**Comment by vladyslav-iosdev** [comment]
currently add token screen looks next
<img width="432" alt="Screenshot 2020-05-15 at 14 56 14" src="https://user-images.githubusercontent.com/55975226/82047914-50182880-96bc-11ea-99d8-8a87b93975ed.png">

**Comment by hboon** [comment]
>@hboon  for now every textfield has uppercased title, do i need to replace it with Capitalized title?

@vladyslav-iosdev leave it for now and we can look at it while reviewing the PR. Similarly if you have small decisions to make. More efficient that way. But if anything bigger troubles you or blocks you, feel free to ask.

**Comment by vladyslav-iosdev** [comment]
ok, np

**Comment by vladyslav-iosdev** [comment]
@hboon can you tell me what address could i paste to receive success from GetENSAddressCoordinator(server: serverToResolveEns).getENSAddressFromResolver(for: value) { result in
?

**Comment by hboon** [comment]
@vladyslav-iosdev vitalik.eth :)

**Comment by hboon** [comment]
Remember that this is UI work. If there’s missing functionality, list it out and we can do it with a follow up PR or create an issue and leave it for later.

**Comment by vladyslav-iosdev** [comment]
@hboon thx!

**Comment by vladyslav-iosdev** [comment]
i wanted to know how it will work with updated ui

**Comment by hboon** [comment]
Yes. That was a good question :)

**Comment by colourful-land** [comment]
> Weiwu

@tomekalphawallet 

0. There is no technical implication one way or the other so Tomek has the final say.

1. As a user, I'd love to be able to fill in Ether amount and sees what USD equivalent should be, or even fill in USD amount and ask αW to use the corresponding ETH amount.

2. The first design Tomek gave me involve some kind of design which made me feel unsure whether or not the value I am typing as a user is ETH value or USD-equivalent value. I said it's rather confusing and @tomekalphawallet acknowledged that and proposed some kind of improvement. I forgot what he proposed.

**Comment by vladyslav-iosdev** [comment]
@hboon hi, how can i get to EditMyDappViewController, what actions should i do in app to get to this screen?

**Comment by hboon** [comment]
@vladyslav-iosdev go to the Browser tab, key in a URL and visit it. Tap the top right hand button to Add to My Bookmarks, double tap the Browser tab tab-button, and choose My Bookmarks, then edit.

It's basically editing a bookmark. It used to be called "Dapps" instead of Bookmarks in the UI.

**Comment by vladyslav-iosdev** [comment]
@hboon ok, see it, thx!

**Comment by vladyslav-iosdev** [comment]
@hboon on EditMyDappViewController do i need to update UILabel, and UITextField with existed TextField class? also do you see my pr?

**Comment by hboon** [comment]
@vladyslav-iosdev if you mean if you should switch all the standalone usage of `UITextField` to `TextField`: depends on how and where you implement the new look, is it in `TextField` or a new class. If you can consolidate them all into `TextField` or a new class, then, yes switch all of them over to use that class. i.e. you can replace the entire `TextField` class if it's not needed anymore.

(I can't remember if it's a good idea to subclass `UITextField`, so verify first if you are going to do that)

> also do you see my pr?

No. If you have pushed a new branch to your fork/repo, you'll need to create a pull request from within GitHub.com UI.
