### ISSUE TITLE
xcode 11 keystore issue

### ISSUE THREAD

**Issue by James-Sangalli** [AlphaWallet/alpha-wallet-ios#1745]
For some reason it is not possible to retrieve the keys when the app is built on xcode 11 and the tests which require keys fail when built in xcode 11. I cannot reproduce this issue in xcode 10, the IDE we have been using so far to release builds. 

<img width="262" alt="Screen Shot 2020-02-29 at 12 50 00 pm" src="https://user-images.githubusercontent.com/16630514/75595621-0030b900-5af2-11ea-82a1-dcc863027a10.png">

**Comment by hboon** [comment]
Appears to be a bug in Xcode 11.x and iOS 13.x simulator:

* http://openradar.appspot.com/7251207
* http://openradar.appspot.com/7478967

Works on all other cases including:

* iOS 11.x, 12.x, 13.x devices
* iOS 11.x, 12.x simulators
