### ISSUE TITLE
Check keychain access works on iOS 14 simulator when built with Xcode 12.x

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#1746]
Close when either:

* Xcode 11.x + iOS 13.x simulator works
* A newer, working combination is available (e.g Xcode 12.x + iOS 14)

Refer: #1745, #1741

**Comment by vladyslav-iosdev** [comment]
@hboon i checked with simulator iOS 14, and it worked for me ok. But when i tried it with simulator with iOS 13.7 it did't.
i found that guys from `SimpleKaychain` do next, they just add check for version, and disable it when its needed.
https://github.com/auth0/SimpleKeychain/blob/4edaf9dbac295be5c9e9f6bdef362b9eba964549/SimpleKeychain/A0SimpleKeychain.m#L49

i didn't find any other information how to fix this

**Comment by hboon** [comment]
It’s ok, if it works for iOS 14, we can just test against that for Travis

**Comment by hboon** [comment]
Closed with #2308
