### ISSUE TITLE
Update view controllers to be either presented modally (still full screen) or pushed onto a navigation controller

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#1748]
With #1741, all screens that were presented modally can be found by looking for callers of `makePresentationFullScreenForiOS13Migration()`. Selectively replaced those calls to reflect whether they should be modal or pushed.

When a view controller is changed from being presented modally to pushed onto a navigation controller, the view controller has to be popped instead of be dismissed. The existing UI flow may break and require tweaking.

Do not change to the modal card-style introduced in iOS 13.

**Comment by hboon** [comment]
@vladyslav-iosdev try this? One at a time for each PR. Because some of them might break because there are (very bad) assumptions about how to hide/dismiss them.

**Comment by hboon** [comment]
Forgot to add, we aren't supposed to change all of them from modal to push:

>  Selectively replaced those calls to reflect whether they should be modal or pushed.

**Comment by vladyslav-iosdev** [comment]
@hboon does it mean that i ned to remove unusefull calls for `makePresentationFullScreenForiOS13Migration()`
for example when we present actionsheet, alert, or before pushing vc to navigation stack?

**Comment by hboon** [comment]
Still keep the calls to `makePresentationFullScreenForiOS13Migration()` if they are still modal. So we can look for those later and decide if we want to keep them as `.fullScreen` or the more modern card-deck-like look.

**Comment by hboon** [comment]
Forced push after rebase master

**Comment by hboon** [comment]
Still WIP

**Comment by vladyslav-iosdev** [comment]
@hboon what else do we need to change here?

**Comment by hboon** [comment]
@vladyslav-iosdev Look for the remaining calls to `makePresentationFullScreenForiOS13Migration()`. These are all modal. Some should be replaced with push. Also:

> One at a time for each PR. Because some of them might break because there are (very bad) assumptions about how to hide/dismiss them in coordinators.
