### ISSUE TITLE
Update ER20 + Ether Default Token View [Fiji]

### ISSUE THREAD

**Issue by colourfreak** [AlphaWallet/alpha-wallet-ios#1754]
The DefaultTokenView area for iOS should be 375x208pt. 

<img width="627" alt="Screenshot 2020-03-16 10 45 33" src="https://user-images.githubusercontent.com/51817359/76745097-919c5e00-6775-11ea-869a-84c23259fcf8.png">

It contains a Token Icon (60x60pt), Token Balance, Token Available Balance (when you have just sent funds to someone, and still waiting for a confirmation, it should be deducted from your available balance).

Tokens (60x60):
https://app.zeplin.io/project/5d0356be2f25b319dcc5944b/styleguide/components?cseid=5e6200fb00514713f84a8cf8

Zeplin:
https://app.zeplin.io/project/5d0356be2f25b319dcc5944b/styleguide/components?coid=5e6f4b759f60ec14abcc4602

Coins $ Tokens:
https://app.zeplin.io/project/5d0356be2f25b319dcc5944b/dashboard?seid=5e2ac385dd5c7a55d29d4b7b

Note: If you have a token such as the Fifa ticket, you can also fit this in the DefaultTokenView. It will be aligned to the bottom (to have space at the top). I highlighted it by blue to show you what I meant:

<img width="1104" alt="Screenshot 2020-03-16 11 05 59" src="https://user-images.githubusercontent.com/51817359/76745512-42a2f880-6776-11ea-9922-2d89fd1fecb4.png">

---

Note that the security icon in the top right corner is updated - green lock + aw.app.

<img width="338" alt="Screenshot 2020-03-16 11 07 28" src="https://user-images.githubusercontent.com/51817359/76745542-54849b80-6776-11ea-8925-14800c0a952c.png">

**Comment by hboon** [comment]
@tomekalphawallet does it have a height of 208pt in an iPhone X-sized display because the fixed margin above and below, or is it 208pt because it looks nicer this way and the white space fills up the empty space?

It’s important to know because there are several screen sizes and we cannot hardcode for every one of them.

**Comment by tomekalphawallet** [comment]
I would say there are two types:

- 375 pt wide screens (6-8, SE, 11 Pro)
- 414 pt wide screens (8 Plus, 11, 11 Pro Max)

So for all screens with 414pt, you can make it 414x208pt. 

<img width="1599" alt="Screenshot 2020-03-16 12 02 25" src="https://user-images.githubusercontent.com/51817359/76750220-2b680900-677e-11ea-92db-479f1b888288.png">

Note that when the margin for 375 is 16, it changes to 20 pt for 414 wide screens.
