### ISSUE TITLE
Latest ENS Contract can't be added to the wallet

### ISSUE THREAD

**Issue by James-Sangalli** [AlphaWallet/alpha-wallet-ios#1756]
https://etherscan.io/address/0x57f1887a8BF19b14fC0dF6Fd9B2acc9Af147eA85

**Comment by James-Sangalli** [comment]
Since they do not have the main fields like decimals, name and symbol we have to keep using a service like opensea. We should keep this in mind but since we are able to catch it with a service like opensea this is not an issue.

**Comment by hboon** [comment]
A general solution to this could be to keep a list of contracts in the app to automatically pull TokenScript files from the repo and add the contracts upon startup if the balance is non-zero? We already do this for a few contracts but maybe we aren’t downloading the TokenScript file first.
