### ISSUE TITLE
 Implement browser User-Agent string + pull from forks

### ISSUE THREAD

**Issue by colourful-land** [AlphaWallet/alpha-wallet-ios#1758]
on iPhone, it is:

Mozilla/5.0 (iPhone; CPU iPhone OS 13_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148

Make it:

Mozilla/5.0 (iPhone; CPU iPhone OS 13_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 AlphaWallet/2.30

And pull the changes to the forks.

Whether or not the forks have their own variation of User-Agent is a seperate topic not covered in this issue. Currently I'm not seeing the need of it and cautious of over-design.

**Comment by hboon** [comment]
Done in 9c21a214f65c5dfbd19e482dcd427f92f1a7afde 😈
