### ISSUE TITLE
Cannot get address from attributes 

### ISSUE THREAD

**Issue by James-Sangalli** [AlphaWallet/alpha-wallet-ios#1768]
<ts:attribute-type id="lendingPoolAddress" syntax="1.3.6.1.4.1.1466.115.121.1.36">
            <ts:origins>
                <ts:ethereum function="getLendingPool" contract="LendingPoolAddressesProvider" as="address">
                </ts:ethereum>
            </ts:origins>
        </ts:attribute-type>

This attribute will not resolve or show up in the web3.tokens.data.currentInstance object

In android it will. 

This bug was discovered by an AAVE developer

**Comment by hboon** [comment]
@James-Sangalli is this reproducible with the 2019/10 or 2020/03?

**Comment by hboon** [comment]
According to https://ldapwiki.com/wiki/NumericString:

```
NumericString = 1*(DIGIT / SPACE)
```

So we'll have to use Directory String `1.3.6.1.4.1.1466.115.121.1.15` instead, and it will work.

**Comment by hboon** [comment]
Remember we look at attributes/origins as a set of pipelines

Smart contract function call -> "cast" to `as` -> "cast" to `syntax`

**Comment by James-Sangalli** [comment]
> @James-Sangalli is this reproducible with the 2019/10 or 2020/03?

2019/10

**Comment by James-Sangalli** [comment]
> According to https://ldapwiki.com/wiki/NumericString:
> 
> ```
> NumericString = 1*(DIGIT / SPACE)
> ```
> 
> So we'll have to use Directory String `1.3.6.1.4.1.1466.115.121.1.15` here instead, and it will work:
> 
> ```
> <ts:attribute-type id="lendingPoolAddress" syntax="1.3.6.1.4.1.1466.115.121.1.36">
> ```

Fixed as per suggestion

**Comment by James-Sangalli** [comment]
@colourful-land FYI
