### ISSUE TITLE
Unified function name， Networks

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/alpha-wallet-ios#1774]
![IMG_2516](https://user-images.githubusercontent.com/33795543/79175624-90785280-7e41-11ea-8714-2621c9828101.jpg)
![IMG_2515](https://user-images.githubusercontent.com/33795543/79175629-953d0680-7e41-11ea-99f9-d830aed251b1.jpg)

Change'Enabled Networks' to 'Select Active Networks'

**Comment by hboon** [comment]
Part of #1659. Almost there.
