### ISSUE TITLE
Improve the speed of Add Custom Token

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/alpha-wallet-ios#1791]
Sometimes it is fast, sometimes it takes a few minutes 
I just test with  0x93d6c4483Ae9dB93cA9B39A441019C5bFac5CFa5 
it takes more than 3 minutes to show the decimals without other fields.

Tested again, when it works, it works on both iOS and Andriod, both pick up token information very fast. When it has issues, on Andriod report as “not find”, on iOS keep searching for mins.

**Comment by hboon** [comment]
Implementation note: because it involves several calls, perhaps one or more of them is completing very slowly or fails. Possibly retry with shorter timeouts.

**Comment by hboon** [comment]
8f423e8ec618a96be2d526db53a2383dcafb2165 (part of Activity support) introduced batching of JSON-RPC calls and this is much faster and more reliable now
