### ISSUE TITLE
Add copy button to Transaction Details + rename "More Details" to "View in Etherscan"

### ISSUE THREAD

**Issue by colourful-land** [AlphaWallet/alpha-wallet-ios#1792]
Visual (by Tomek, if in question, ask him)
https://app.zeplin.io/project/5d0356be2f25b319dcc5944b/dashboard?seid=5e170e6ef7b0f25419ad8e00

Android: https://github.com/AlphaWallet/alpha-wallet-android/issues/1377

**Comment by hboon** [comment]
- [ ] Watch out that the "More Details" button don't always go to Etherscan. Examine the `viewModel.detailsURL` in TransactionViewController.more(). It'll ultimately get the URL from `ConfigExplorer.explorer(for:)`. Can you add a new func to `ConfigExplorer` that returns the site's name, eg. 

```
func explorerName(for server: RPCServer) -> String? {
    switch {
       case .main, .kovan, etc:
            return "Etherscan" //Don't need to localise
    }
}

Alternatively, modify `explorer()` to return a tuple.

(This specific bit is because we have white label projects that fork this repo and we want to make it easier to bring changes between this repo and the forks).

- [ ] Ignore the style changes for the green button for this issue. It's a common component, lets change it another time

- [ ] Test with short devices (5s)

**Comment by vladyslav-iosdev** [comment]
@hboon do i need to remove UITapGestureRecognizer and replace it with a button? or just add image and left gesture as it is?

**Comment by hboon** [comment]
@vladyslav-iosdev gesture or button: up to you, might depend on this:

> do I need to add copy icon for each item:

Continue to allow tap to copy, and don’t add the copy icon other than those (3?) in the design. We can just keep it as a harmless 
hidden feature of power users discover them.

Something unrelated: display the date time with locales and not the hardcoded format.

**Comment by vladyslav-iosdev** [comment]
> @vladyslav-iosdev gesture or button: up to you, might depend on this:
> 
> > do I need to add copy icon for each item:
> 
> Continue to allow tap to copy, and don’t add the copy icon other than those (3?) in the design. We can just keep it as a harmless
> hidden feature of power users discover them.
> 
> Something unrelated: display the date time with locales and not the hardcoded format.

@hboon  do i need to remove "copy alertSheet"?

**Comment by hboon** [comment]
Oh right. Remove it and show the little pop up that fades away like in the wallet screen which you worked on recently?

**Comment by vladyslav-iosdev** [comment]
Does this function right? do i need replace some nil's with specific title?
func explorerName(for server: RPCServer) -> String? {
        switch server {
        case .main, .kovan, .ropsten, .rinkeby, .goerli:
            return "Etherscan"
        case .classic:
            return "Gastracker"
        case .poa:
            return "Poaexplorer"
        case .custom, .callisto:
            return nil
        case .sokol:
            return nil
        case .xDai:
            return nil
        case .artis_sigma1:
            return nil
        case .artis_tau1:
            return nil
        }
    }

**Comment by hboon** [comment]
@vladyslav-iosdev like this:

```
    func explorerName(for server: RPCServer) -> String? {
        switch server {
        case .main, .kovan, .ropsten, .rinkeby, .goerli:
            return "Etherscan"
        case .classic:
            return "Gastracker"
        case .poa:
            return "POA Explorer"
        case .custom, .callisto:
            return nil
        case .sokol:
            return "Sokol Explorer"
        case .xDai:
            return "BlockScout"
        case .artis_sigma1:
            return "Artis"
        case .artis_tau1:
            return "ARTIS"
        }
    }
```
