### ISSUE TITLE
Display suggestions when importing seed phrase

### ISSUE THREAD

**Issue by nimitparekh2020** [AlphaWallet/alpha-wallet-ios#1798]
![69209421-41d4ce00-0bab-11ea-842d-006ea634d54a](https://user-images.githubusercontent.com/708425/81808174-f2a99d80-953c-11ea-89a7-d8852b9bb87c.jpg)

**Comment by hboon** [comment]
@nimitparekh2020 Dup of #1568 which is already assigned to you
