### ISSUE TITLE
Sending ERC20 tokens using QR Code

### ISSUE THREAD

**Issue by AW-STJ** [AlphaWallet/alpha-wallet-ios#1803]
iOS version 2.25(327) and noticed that the ERC20 token bug is still there.

To send any tokens from this wallet to another wallet, the following happens. From the Wallet window

1. Tap on the ERC20 token I want to send to open the Recent Transaction window.

2. Tap Send

3. Tap the camera icon to scan the receiver's QR Code.

5. The wallet automatically reverts from my selected ERC20 token to ETH. I cannot send any BITE, STERLING etc at all when using the "QR Code scan" function.

**Comment by AW-STJ** [comment]
Video Linked. Issue is from Coin Wallet

[](https://drive.google.com/file/d/1S1CsiL3W6LYMRxzf-qAUaKKs0i4cOilj/view?usp=drivesdk)

**Comment by James-Sangalli** [comment]
@AW-STJ I cannot reproduce this in the latest version at all. Let's give him the latest coin wallet build in iOS and see if it still happens to him

**Comment by AW-STJ** [comment]
Would you be able to do a Build of the iOS Coin wallet? I can then ask them to send us some tokens for testing.

**Comment by AW-STJ** [comment]
Bug confirmed resolved by the client
