### ISSUE TITLE
Make entire address and ENS name labels tappable to trigger the copy action

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#1806]
Currently only the blue icon is tappable. Note that the screenshot doesn't show the ens name label. Look around `RequestViewController.copyEnsButton`. The screen is accessible from Settings > My Wallet Address.

![Simulator Screen Shot - iPhone X - 2020-05-19 at 23 20 14](https://user-images.githubusercontent.com/56189/82344999-50e7ec00-9a27-11ea-9c3d-20f685b5c2ab.png)

**Comment by vladyslav-iosdev** [comment]
@hboon i'm not clearly undestand what do i need to make there. 
i need make label clickable?
and this address should be displayed in format like this?
var addresses: String {
        if let ensName = ensName {
            return "\(ensName) | \(wallet.address.truncateMiddle)"
        } else {
            return wallet.address.truncateMiddle
        }
    }

**Comment by hboon** [comment]
Sorry, was too vague. 

> i need make label clickable?

Yes.

> and this address should be displayed in format like this?

Don't need to change the display. Here's how it looks like. It shouldn't change visually:

<img width="452" alt="Screenshot 2020-05-20 at 4 14 50 PM" src="https://user-images.githubusercontent.com/56189/82422633-470cca00-9ab5-11ea-8bf9-199fb1704e6b.png">

**Comment by vladyslav-iosdev** [comment]
@hboon does it ok, if i add UITapGestureRecognizer for those labes and triggrer will call copyEns?

**Comment by hboon** [comment]
@vladyslav-iosdev sure
