### ISSUE TITLE
Update QR scanner screen

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#1814]
We currently use a fork (see Podfile) of QRCodeReaderViewController. Can you either modify it or implement it so that it looks like this? It's fine (probably best) if you can remove the dependency on QRCodeReaderViewController if implementing the scanner from scratch works for you:

https://app.zeplin.io/project/5d0356be2f25b319dcc5944b/screen/5e54e153f1689c658669eb8a

It's probably used in a few places.

Out of scope
---
You can ignore the "My QR code" button for now.

---

Boon for later:

- [x] ~~Create issue, add "My QR code" button~~ #1826

Related: #1738

**Comment by tomekalphawallet** [comment]
Not sure if that matters, but in the future, we might add an ability to trigger this screen with Siri. Having that in the back of mind might be good at this stage.

**Comment by hboon** [comment]
Yes, likely from the app launch shortcuts too

**Comment by vladyslav-iosdev** [comment]
@tomekalphawallet what if use pod 'QRCodeReader.swift', '~> 10.1.0'? its the same Pod, but with ability to define custom UI

**Comment by vladyslav-iosdev** [comment]
@hboon  Hi, i sent PR https://github.com/AlphaWallet/QRCodeReaderViewController/pull/1 
can't find how to set you as reviewer.

**Comment by hboon** [comment]
@vladyslav-iosdev Just added you as a collaborator. Could be the reason. Do you see this?

<img width="1212" alt="Screenshot 2020-05-22 at 3 24 22 PM" src="https://user-images.githubusercontent.com/56189/82642430-7f8cdf00-9c40-11ea-9c91-b49531ca7f29.png">

**Comment by vladyslav-iosdev** [comment]
no, there is no settings button

<img width="300" alt="Screenshot 2020-05-22 at 10 30 23" src="https://user-images.githubusercontent.com/55975226/82642905-52780680-9c17-11ea-9fdd-ae7a42533c30.png">

**Comment by hboon** [comment]
@vladyslav-iosdev no idea why. It's alright. You can just buzz me to review in a PR if you can't assign me :)

**Comment by vladyslav-iosdev** [comment]
@hboon QRCodeReaderViewController called from several places manually, do i need to replace those calls with calling it through ScanQRCodeCoordinator?

**Comment by hboon** [comment]
@vladyslav-iosdev yes, that would be great. Is it independent of this issue? If it is, create a new issue "Refactor all access to QRCodeReaderViewController so it goes through ScanQRCodeCoordinator" and assign yourself.

**Comment by vladyslav-iosdev** [comment]
> yes, that would be great. Is it independent of this issue? If it is, create a new issue "Refactor all access to QRCodeReaderViewController so it goes through ScanQRCodeCoordinator" and assign yourself.

yes it is. ok.

**Comment by hboon** [comment]
Closed by https://github.com/AlphaWallet/QRCodeReaderViewController/pull/1
