### ISSUE TITLE
Update shared ButtonsBar look

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#1819]
The `ButtonsBar` class is used across the app. The buttons are currently all green.

- [ ] Let's make them appear in 3 configurations:

A\. 1 green, 1 white, and a "...":

https://app.zeplin.io/project/5d0356be2f25b319dcc5944b/dashboard?seid=5e4130b758245792d0d24970

B\. All green, no "..." (there can be more than 1 button):

C\. All white, no "..." (there can be more than 1 button):

https://app.zeplin.io/project/5d0356be2f25b319dcc5944b/screen/5dfc4ba8e901f31623b867d4

5a and 5b below are the only cases where we use configuration A (correction hboon 20200610: `TokenViewController` uses configurationA too). There is one use of C in `CreateInitialWalletViewController` (look for ButtonsBar.configureSecondary(), this is shown for new users without wallets), every other instance of `ButtonsBar` use B.

- [ ] Assume that each button's style (green or white) can be configured separately (in the future, we might mix green and white button in A and not always 1st green, 2nd white, or B might not always be green)

- [ ] In the 2 view controllers mentioned below (TokensCardViewController and TokenInstanceViewController), noticed that there is an additional separator above the buttons (so only with configuration A). Either add the separator within the view controllers or `ButtonsBar`

How to go to screens which uses TokenScript
---
Don't worry about what is TokenScript for now.

1\. Enable the Kovan network

2\. Add the contract 0x2B58A9403396463404c2e397DBF37c5EcCAb43e5:

<img src="https://user-images.githubusercontent.com/56189/82627938-1eecaa80-9c1e-11ea-9076-b15f6ebe8acd.png" width=200>

3\. Tap the token:

<img width="200" alt="Screenshot 2020-05-22 at 11 05 39 AM" src="https://user-images.githubusercontent.com/56189/82627949-28761280-9c1e-11ea-878b-1244221269c8.png">

4a\. (We are now in TokensCardViewController) Tap one of the rows with the picture:

<img src="https://user-images.githubusercontent.com/56189/82627963-32981100-9c1e-11ea-95f8-871cd995c2a8.png" width=200>

5a\. The buttons at the bottom (in TokenInstanceViewController):

<img src="https://user-images.githubusercontent.com/56189/82627980-39bf1f00-9c1e-11ea-97ca-420f0c4e3d95.png" width=200>

4b\. (after 3) Tap and hold one of the rows with the picture

5b\. The buttons at the bottom (in TokensCardViewController):

<img src="https://user-images.githubusercontent.com/56189/82628019-4c395880-9c1e-11ea-829f-266bc6af0df4.png" width=200>

supersedes #1702

**Comment by hboon** [comment]
Updated the description ^ to mention configuration C, which is only used in a single place.

**Comment by vladyslav-iosdev** [comment]
@hboon i don't clearly undarstand what do i need to do here.
     correct me if i mistake, first i need update ButtonsBarViewModel, to allow pass background color through init, with some default value.
     Then i need to refactor ButtonsBar class to allow individually set ButtonsBarViewModel to each buttonContainerViews item.
     Also i don't understand this "A. 1 green, 1 white, and a "...":" what this "..." mean?

**Comment by hboon** [comment]
@vladyslav-iosdev in the 1st zeplin link (I can’t open Zeplin to verify now), you should see that the ButtonsBar appear as 1 green, 1 white and an additional “more” button”beside it, with the title “...”. This is because the buttons when in configuration A, is dynamic. There can be more buttons than can fit in the screen. So with this redesign, that 3rd “...” button brings up an actionsheet which reveals the rest of the button actions.

**Comment by vladyslav-iosdev** [comment]
i see there is only one
<img width="1100" alt="Screenshot 2020-05-25 at 13 33 59" src="https://user-images.githubusercontent.com/55975226/82805297-755f2080-9e8c-11ea-8ba3-26670a9a02ea.png">

**Comment by hboon** [comment]
@vladyslav-iosdev maybe it hasn't loaded completely. Looks like this. Notice the first 3 screens:

<img width="1349" alt="Screenshot 2020-05-25 at 7 13 43 PM" src="https://user-images.githubusercontent.com/56189/82808133-e538cf80-9ebb-11ea-9fb2-ed90f7c115c1.png">

**Comment by vladyslav-iosdev** [comment]
> @vladyslav-iosdev maybe it hasn't loaded completely. Looks like this. Notice the first 3 screens:
> 
> <img alt="Screenshot 2020-05-25 at 7 13 43 PM" width="1349" src="https://user-images.githubusercontent.com/56189/82808133-e538cf80-9ebb-11ea-9fb2-ed90f7c115c1.png">

@hboon  its my fail, i thought about complitelly different things need to be done. now its clear. what if i update `ButtonsBar` class  init with next input param `ButtonsBarConfiguration`

```
enum ButtonsBarConfiguration {
        case combined
        case green(buttons: Int)
        case white(buttons: Int)
        case custom(types: [ButtonsBarButtonType])

        var buttonViewModels: [ButtonsBarButtonType] {
            switch self {
            case .green(let buttons):
                return buttons == 0 ? [.green] : (0..<buttons).compactMap{ _ in .green }
            case .white(let buttons):
                return buttons == 0 ? [.white] : (0..<buttons).compactMap{ _ in .white }
            case .custom(let types):
                return types
            case .combined:
                return [.green, .white, .more]
            }
        }
    }
    
    enum ButtonsBarButtonType {
        case green
        case white
        case more
        
        var viewModel: ButtonsBarViewModel {
            switch self {
            case .green:
                return ButtonsBarViewModel(buttonBackgroundColor: Colors.appActionButtonGreen)
            case .white:
                return ButtonsBarViewModel(buttonBackgroundColor: Colors.appWhite)
            case .more:
                return ButtonsBarViewModel(buttonBackgroundColor: Colors.appWhite)
            }
        }
    }
```
this will allow us to update bar buttons as we want

**Comment by hboon** [comment]
@vladyslav-iosdev sounds like it would work, but remember to offer some way to reconfigure it using `configure(somethingHereIfNecessary)`. This is because the TokenScript screens can change dynamically. i.e part of the UI (in this case, just the buttons) is actually described using an XML file. When the contents of that file is edited, the number of buttons, the title, etc will change in those screens. You can see it in action (don't worry about the XML for now) in `TokensCardViewController.configure()`. Look for references to `buttonsBar` in that function. `TokensCardViewController.configure()` will be called multiple times.

**Comment by vladyslav-iosdev** [comment]
@hboon I am back, i sent PR for #1819, what's next? rest should be done if i didn't miss something.

**Comment by hboon** [comment]
@vladyslav-iosdev assigned you a few more issues :)
