### ISSUE TITLE
Refactor all access to QRCodeReaderViewController

### ISSUE THREAD

**Issue by vladyslav-iosdev** [AlphaWallet/alpha-wallet-ios#1822]
Refactor all access to QRCodeReaderViewController so it goes through ScanQRCodeCoordinator

**Comment by vladyslav-iosdev** [comment]
@hboon i refactored code related to https://github.com/AlphaWallet/alpha-wallet-ios/issues/1814
but code required dependency that was in https://github.com/AlphaWallet/QRCodeReaderViewController/pull/1
i will send code without updating pod file

**Comment by hboon** [comment]
@vladyslav-iosdev sure. Thanks
