### ISSUE TITLE
Add "My QR" button to show wallet QR code in QR code scanner screen

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#1826]
Study #1814

**Comment by vladyslav-iosdev** [comment]
@hboon My QR button always should present in QR code scanner screen, or not? (for example if we do scan qr code from send screen, do we need show this button)?

**Comment by hboon** [comment]
@vladyslav-iosdev yes, always show it.

**Comment by hboon** [comment]
Closed with #2037
