### ISSUE TITLE
Send functions allows send for transactions larger than the wallet balance

### ISSUE THREAD

**Issue by AW-STJ** [AlphaWallet/alpha-wallet-ios#1845]
Enhancement suggested when Coin Wallet was tested.

iOS: iPhone 8+. Coin Wallet V1.0.0 (2)
 
Send function. An amount larger than the wallet balance can be sent. The transaction fails at contract level but is still recorded as a Confirmed transaction in the Transaction window. Yes the wallet balance does not change as it failed, but it causes a “transaction revert” which costs the user ETH. Android manages this at wallet level and states “Insufficient Funds” and the transaction is not executed on the blockchain. 

Can we match iOS behaviour with Android on this instance?

**Comment by James-Sangalli** [comment]
@AW-STJ this was solved yesterday here: https://github.com/AlphaWallet/alpha-wallet-ios/pull/1841
