### ISSUE TITLE
Text field (currency button) periodically switched when detection token

### ISSUE THREAD

**Issue by vladyslav-iosdev** [AlphaWallet/alpha-wallet-ios#1846]
- click on ETH mainnet
- click Send action
- set amount to 1,
- press ETH float button to convert to USD
- scan address, address populated, textfield value changed from USD to ETH.

**Comment by hboon** [comment]
And remember that it should change to ETH if an EIP681 link with amount is scanned.

Also watch out for if it's a non-crypto token being transferred. Then there's no toggling from token -> USD

**Comment by vladyslav-iosdev** [comment]
> And remember that it should change to ETH if an EIP681 link with amount is scanned.
> 
> Also watch out for if it's a non-crypto token being transferred. Then there's no toggling from token -> USD

ok

**Comment by hboon** [comment]
Ah. If you haven't started work on this yet, wait until #1816 is merged. Unless it's a really simple change

**Comment by vladyslav-iosdev** [comment]
@hboon  is there other tasks to do, while i waiting for #1816 is merged? the rest of list seems like done, if i didn't miss anything.

**Comment by hboon** [comment]
@vladyslav-iosdev clean up https://github.com/AlphaWallet/bartercard-ios/pull/154 :)

**Comment by hboon** [comment]
@vladyslav-iosdev assigned a few more.

**Comment by hboon** [comment]
@vladyslav-iosdev hold this first. I might have fixed it somewhere rlsey

**Comment by hboon** [comment]
Not an issue after #1862 and related
