### ISSUE TITLE
Research if/how to test if a private key (which is marked as user presence required) written into the Secure Enclave can tested for existence without prompting for user presence check

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#1849]
Referring to the flag `SecAccessControlCreateFlags.userPresence`.

The public-private key pair is created in `SecureEnclave.createPrivateKey`.

This will require a device (not simulator) with Touch ID or Face ID to verify.

Just a snippet will do. It doesn't have to be integrated into the code base.

**Comment by hboon** [comment]
Bump.

**Comment by vladyslav-iosdev** [comment]
> @vladyslav-iosdev Bump.

@hboon i researched but find nothing according this issue

**Comment by hboon** [comment]
> @hboon i researched but find nothing according this issue

As in, it's probably not possible?

**Comment by hboon** [comment]
Good news, I asked someone who said this:

> I can confirm. I have code that does SecItemCopyMatching to check if a key already exists and it doesn’t prompt for biometry until you actually call something like SecKeyCreateEncryptedData

Can you help to dig further? :)

**Comment by vladyslav-iosdev** [comment]
> Good news, I asked someone who said this:
> 
> > I can confirm. I have code that does SecItemCopyMatching to check if a key already exists and it doesn’t prompt for biometry until you actually call something like SecKeyCreateEncryptedData
> 
> Can you help to dig further? :)

ok, i will check it

**Comment by vladyslav-iosdev** [comment]
@hboon can you try with this piece of code:
```
public func contains(_ key: String) throws -> Bool {
        var query = options.query()
        query[AttributeAccount] = key
        query[UseAuthenticationUI] = UseAuthenticationUIFail
        
        let status = SecItemCopyMatching(query as CFDictionary, nil)
        switch status {
        case errSecSuccess, errSecInteractionNotAllowed:
            return true
        case errSecItemNotFound:
            return false
        default:
            throw securityError(status: status)
        }
    }
```
i found it here:
https://github.com/kishikawakatsumi/KeychainAccess/issues/159

**Comment by hboon** [comment]
@vladyslav-iosdev thanks! Will try it out.

FYI. The painful part of this is, in order to be sure, I have wipe device, restore from iCloud back to verify the key is no longer there.
