### ISSUE TITLE
Make fastlane work again, notably posting app store screenshots

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#1850]

**Comment by vladyslav-iosdev** [comment]
@hboon  you mean make this work? or that screenshots directory is empty after `fastlane snapshot`
<img width="974" alt="Screenshot 2020-05-29 at 17 50 18" src="https://user-images.githubusercontent.com/55975226/83273220-f1cb6980-a1d4-11ea-81d8-757d162467a4.png">

**Comment by hboon** [comment]
Will have to check. Been a while since I tried.

**Comment by vladyslav-iosdev** [comment]
@hboon are there other tasks except  #1850 #1849 #1846 ?

**Comment by hboon** [comment]
There’s a couple at the forked repo I think

**Comment by vladyslav-iosdev** [comment]
> forked

@hboon can you send me a link?

**Comment by hboon** [comment]
> @hboon are there other tasks except #1850 #1849 #1846 ?

@vladyslav-iosdev Oh, I think that's all for now. I'll try to reply to the pending ones later today.

> @hboon can you send me a link?

You can use a link like this for the other repo too: https://github.com/AlphaWallet/alpha-wallet-ios/issues/assigned/vladyslav-iosdev

**Comment by hboon** [comment]
Closed since it is no longer needed for the time being.
