### ISSUE TITLE
Update Settings Tab Icons [Fiji]

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#1853]
Supersedes #1659 

https://app.zeplin.io/project/5d0356be2f25b319dcc5944b/dashboard?seid=5dfc1f63646faf970d746224

* There is a WIP feature branch: `update-settings-screen-design`. Only the very first screen is implemented (and not in a good way).
* Take care to address or remove all the `//hhh` comments
* Fix some of the bad practises/code in the branch. There might still be some. Some are probably marked with `//hhh` comments
* SettingsViewController is the original version
* Ignore SettingsViewController2 (and delete it at some point)
* Work on `SettingsViewController3` and finally rename it back to `SettingsViewController`. Feel free to do this right away if you prefer.
* There might be some mix match of rows in the design and in the current version (SettingsViewController), if they are not found in SettingsViewController, ignore it.

**Comment by vladyslav-iosdev** [comment]
@hboon what do i need to do when press `support` ?

**Comment by hboon** [comment]
@vladyslav-iosdev that would be the current "Help & FAQs"

**Comment by vladyslav-iosdev** [comment]
> @vladyslav-iosdev that would be the current "Help & FAQs"

thx

**Comment by vladyslav-iosdev** [comment]
@hboon also what should happen by selection on `Analytics` and `Change Currency`?

**Comment by hboon** [comment]
@vladyslav-iosdev ignore those 2. Would you make a list of those somewhere in this issue? So we can come back and revisit those.

**Comment by vladyslav-iosdev** [comment]
> ignore those 2. Would you make a list of those somewhere in this issue? So we can come back and revisit those.

ok
