### ISSUE TITLE
Large title in Wallet tab become normal after we push Add / Hide tokens screen and pop back

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#1859]

**Comment by tomekalphawallet** [comment]
Also, it might be a big finger problem, but tapping somewhere below "Add /Hide Tokens" triggers the first token to open. I might be not precise, but it happens to me too often. 

Try by yourself, tapping the area highlighted
![IMAGE 2020-06-01 09:04:34](https://user-images.githubusercontent.com/51817359/83384139-e9e31380-a3e6-11ea-9f3e-600833189f44.jpg)

**Comment by hboon** [comment]
@tomekalphawallet I've moved it over to https://github.com/AlphaWallet/alpha-wallet-ios/issues/1861

**Comment by tomekalphawallet** [comment]
https://www.dropbox.com/s/ltaq0ss1otx378o/2020-06-16%2019.25.41.mp4?dl=0

**Comment by hboon** [comment]
We seem to have lost the large title in Wallet tab completely (at launch)
