### ISSUE TITLE
build 3.00(334) in send action card, it should show the token name instead of the network currency 

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/alpha-wallet-ios#1863]
This should be BAT instead of ETH

![IMG_3232](https://user-images.githubusercontent.com/33795543/83400874-fbf49e80-a446-11ea-90cb-f10d1b094563.PNG)

this should be different from ETH
![IMG_3233](https://user-images.githubusercontent.com/33795543/83401015-4bd36580-a447-11ea-8cdc-1c6d2b00d52e.PNG)

**Comment by hboon** [comment]
Will address in #1862. Just hide it completely. We don't have an icon for the token anyway.

**Comment by zhangzhongnan928** [comment]
> Will address in #1862. Just hide it completely. We don't have an icon for the token anyway.

ok
