### ISSUE TITLE
Can't tap cell in token cards screen near the bottom

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#1868]
Probably because the currently 0 button `ButtonBar` is trapping them? Check again after #1832 is merged

**Comment by hboon** [comment]
Check after #1832 is merged

**Comment by vladyslav-iosdev** [comment]
@hboon can u tell me what ViewController it is, because for now its not clear what i need to check?

**Comment by vladyslav-iosdev** [comment]
meybe u mean this one?
<img width="432" alt="Screenshot 2020-09-10 at 12 08 30" src="https://user-images.githubusercontent.com/55975226/92707986-6d08f380-f35e-11ea-85e2-93c166ed52e0.png">

**Comment by hboon** [comment]
I probably mean `TokensCardViewController`.

**Comment by hboon** [comment]
Closed by #2132
