### ISSUE TITLE
Import button (wrongly) remains disabled after pasting in seed phrase on iPad

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#1869]
Verify first. Might be because soft keyboard is disabled while on simulator. But this can mean it's reproducible on actual iPad (or even iPhone) when using a hardware keyboard

**Comment by vladyslav-iosdev** [comment]
@hboon I tried on real device seems like it works. But i found  other one issue, with paste  action on SendViewController.

**Comment by hboon** [comment]
@vladyslav-iosdev did you with a hardware/external keyboard? Trying on the simulator with the soft keyboard disabled (so you can type with the laptop/mac keyboard) should simulate that.

**Comment by vladyslav-iosdev** [comment]
> @vladyslav-iosdev did you with a hardware/external keyboard? Trying on the simulator with the soft keyboard disabled (so you can type with the laptop/mac keyboard) should simulate that.

I tried with hardware keyboard

**Comment by vladyslav-iosdev** [comment]
@hboon "remains disabled" does it look like disabled? 
<img width="539" alt="Screenshot 2020-06-04 at 18 04 14" src="https://user-images.githubusercontent.com/55975226/83774156-08b70380-a68e-11ea-9024-e5aec1134871.png">

**Comment by hboon** [comment]
Yes it does look like disabled when it happens. If it’s only on the simulator, then it’s alright

**Comment by hboon** [comment]
Not a problem
