### ISSUE TITLE
Overridden method 'equals' has generic signature <T where T : LinearGradient> which is incompatible with base method's generic signature <T where T : Fill>; expected generic signature to be <T where T : Fill>

### ISSUE THREAD

**Issue by SazzadIp** [AlphaWallet/alpha-wallet-ios#1872]
When I upgrade pod with Xcode 11.5. I got this Error.

**Comment by SazzadIp** [comment]
Found Solution. Error due to Swift 5.2 new updates.

Solution:
https://github.com/exyte/Macaw/issues/668

**Comment by hboon** [comment]
@SazzadIp thanks! Will look into it soonish.

**Comment by hboon** [comment]
@SazzadIp we build with Xcode 11.3, so it's easiest to use that version for now. But we'll look at this soon.
