### ISSUE TITLE
Display an error message when QR code for EIP681 link has invalid contract

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#1874]
After #1862 is merged

This is in `SendViewController`.

Show "Invalid token" with `UIAlertController`.

Generate a link at https://brunobar79.github.io/eip681-link-generator/# and use the QR code

---

This should populate the fields and not show an error message:

contract: 0x89d24a6b4ccb1b6faa2625fe562bdd9a23260359 (this should show up as the SAI token)
receiver: any Ethereum address for wallet
amount: 1000000000000000000

---

This should show the error message and not populate the textfields:

contract: any Ethereum address that is not a token (eg. a wallet address)
receiver: any Ethereum address for wallet
amount: 1000000000000000000

**Comment by vladyslav-iosdev** [comment]
@hboon so you mean to show alert for all these cases 
.name, .symbol, .balance, .decimals, .nonFungibleTokenComplete, .delegateTokenComplete, .failed:
in checkAndFillEIP681Details?
