### ISSUE TITLE
Show a generic "token" icon in send screen when sending ERC20 token

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#1883]
In `SendViewController`, assuming the ERC20 token has the symbol "OMG".

<img src="https://user-images.githubusercontent.com/56189/83730858-401cb480-a67c-11ea-8f53-dbb65d06677a.png" width=200>

This icon:

https://app.zeplin.io/styleguide/5e0b15e46049c216fb7ab4d5/components?coid=5e27130e1d43768074cedd2d

Remember to handle 4 cases to update or not to update `SelectCurrencyButton` correctly:

- [x] User tapped the OMG token in the wallet tab
- [x] User tapped ETH in the wallet tab and then scan an EIP681 link with OMG token
- [x] User tapped ETH in the wallet tab and then scan an EIP681 link for ETH
- [x] User tapped the OMG token in the wallet tab and then scan an EIP681 link with OMG token
- [x] User tapped the OMG token in the wallet tab and then scan an EIP681 link with ETH token

**Comment by vladyslav-iosdev** [comment]
@hboon can you provide test OMG token address for testing?

**Comment by hboon** [comment]
@vladyslav-iosdev can you paste or send me a wallet to send to?

**Comment by vladyslav-iosdev** [comment]
@hboon 0xb4F0819ABC2d662Fbf7715EbCB87721b1DC1e142

**Comment by hboon** [comment]
@vladyslav-iosdev sent you this on Rinkeby 0x7f1511708E51A3088e4e8505F16523300668476E. TEST token

**Comment by hboon** [comment]
You can add it in the Add/Hide token screen. Add button.

**Comment by vladyslav-iosdev** [comment]
@hboon  i am not clearly undarstand what do i need to do here.
i added token you send, then selected added token and open SendViewController.
for now in case when we send ERC20Token we hide currency icon and expand button and at the title on navigation bar displays "OMG"
![photo_2020-06-04_15-57-05](https://user-images.githubusercontent.com/55975226/83759429-34c98900-a67c-11ea-9119-55ddb85b1e9f.jpg)

**Comment by vladyslav-iosdev** [comment]
i guess i added token in wrong way, i was need to enable Rinkeby network in settings

**Comment by hboon** [comment]
The change is to change the behaviour for ERC20 tokens: show the default icon as well as the symbol (in the screenshot I annotated it as OMG, if it’s the TEST token, show TEST instead. Depends on the current token).

In other words, no longer hide the currency selector when it’s ERC 20. Instead show the default icon and the symbol for that token (instead of ETH or USD). But still hide the down arrow and equivalent fiat amount.

**Comment by vladyslav-iosdev** [comment]
@hboon i s not sure why but i am not able to download this icon

**Comment by hboon** [comment]
@tomekalphawallet looks like this one isn't downloadable. Can you help? https://app.zeplin.io/styleguide/5e0b15e46049c216fb7ab4d5/components?coid=5e27130e1d43768074cedd2d

**Comment by vladyslav-iosdev** [comment]
@hboon i found how to download it)

**Comment by tomekalphawallet** [comment]
https://zpl.io/bJJBnEr

**Comment by hboon** [comment]
>@hboon i found how to download it) ...

@vladyslav-iosdev nice :)

**Comment by hboon** [comment]
>https://zpl.io/bJJBnEr

@tomekalphawallet thanks
