### ISSUE TITLE
Show "Available: <eth/token balance>" in send screen

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#1886]
https://app.zeplin.io/project/5d0356be2f25b319dcc5944b/screen/5dfc4ba7aa48e01aa20e886e

Also highlights this "Available: xxx" as well as the amount entered in red when the amount entered is more than the balance like in:

https://app.zeplin.io/project/5d0356be2f25b319dcc5944b/screen/5e2ac09836436754bc975a1f

This is probably going to make `SendInputErrors.wrongInput` redundant.

- [ ] If `SendInputErrors.wrongInput` is still used after this PR, point that out so we can improve the error message

edit hboon: `SendInputErrors.wrongInput` is probably still around, but only if the `input = 0`

**Comment by hboon** [comment]
@tomekalphawallet 

<img src="https://user-images.githubusercontent.com/56189/83965202-72304f80-a8e4-11ea-96af-86420f09b72c.png" width=200>

The proximity of "Available: 1.234" and "~483,12 USD" might be a bit misleading. Do you think it's better to move "~483,12 USD" to the right, below "2"?

We'll have to have a button for "All Funds" later too. Or maybe we can make tapping on "Available: 1.234" do what "All Funds" was intended to do?

**Comment by tomekalphawallet** [comment]
We don't have to show "~483,12 USD". Too much information already. And let's reduce Available: xxxx to just 4 numbers after ","

It might be a bit complicated, but also user-friendly:
a. I enter 10 ETH
b. I want to know how much is this worth in USD
c. I tap around the arrow to switch
d. It switches to USD, but does not clear the value I entered in ETH. Instead, I now see 2500 USD

@hboon what do you think?

**Comment by hboon** [comment]
> We don't have to show "~483,12 USD".

@tomekalphawallet Ok. Let's remove it then. Thanks.
