### ISSUE TITLE
App icon in launch (aka splash) screen should not move (up) abruptly

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#1897]
During a cold launch, this happens:

1. the launch screen (which includes the app icon) appears
2. SplashView(Controller) appears (probably due to `ProtectionCoordinator`) which includes the app icon too.
3. SplashViewController is hidden

The app icon in (1) and (2)'s y position is slightly different so it looks like the logo moved up abruptly. The icon should not move at all.

Need to verify the fix works on 5s, iPhone X and a bigger than 5s phone with no notch.

<img src="https://user-images.githubusercontent.com/56189/83971356-95232980-a90d-11ea-8473-307998700b04.gif" width=200>

**Comment by hboon** [comment]
Keeping this for Sunil

**Comment by hadwanihardik** [comment]
Hello @AW-STJ 
Can u verify if this is as per required?

**This is for notch device.**
![notch device](https://user-images.githubusercontent.com/5634693/84921111-ad4f3180-b0e1-11ea-91de-e98b79c7c53e.gif)

**This is for Older/Notch less device.**
![Notchless](https://user-images.githubusercontent.com/5634693/84921194-ca840000-b0e1-11ea-9f8a-66d6ea0c0f0c.gif)

**Comment by hboon** [comment]
@hadwanihardik launch the app again after creating a wallet to be sure.

**Comment by hadwanihardik** [comment]
@hboon I checked  it in notch display after creating wallet it has issue

**Comment by hadwanihardik** [comment]
@hboon I checked  it in notch display after creating wallet it has issue.

**Comment by hadwanihardik** [comment]
@hboon 
Is this shows issue resolved.
please check video in attached link.

https://drive.google.com/file/d/1v_6lY1jqrdf9Q4_1iopPxMN1B2VwbYVm/view?usp=sharing

**Comment by hboon** [comment]
@hadwanihardik can you push the code? And I can't watch the video.

**Comment by hboon** [comment]
Always push the code in a PR.

**Comment by hadwanihardik** [comment]
Ok sure

Sent from iPhone
Regards, 
Hardik Hadwani 
(iOS Developer)

**Comment by hadwanihardik** [comment]
> @hadwanihardik launch the app again after creating a wallet to be sure.

Hey boon this is public link you must be able to see video
https://drive.google.com/file/d/1v_6lY1jqrdf9Q4_1iopPxMN1B2VwbYVm/view?usp=sharing

**Comment by hadwanihardik** [comment]
@hboon I created PR for the same
