### ISSUE TITLE
Update Wallet tab cell's layout

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#1903]
Part of #1665 

https://app.zeplin.io/project/5d0356be2f25b319dcc5944b/screen/5dfaf2ce114ed41d029b3e2b

* The native crypto cells like Eth and xDai still has current fiat value, the appreciation/depreciation and fiat value appreciation
* Don't show Issuer because it's removed in #1902
* Also the Add / Hide screen

Out of scope
---
Don't add the token icon

**Comment by vladyslav-iosdev** [comment]
@hboon what this green text is? as i understand its the same what displayd above "24 hours", rigth? and where "appreciation/depreciation" should be placed?
<img width="198" alt="Screenshot 2020-06-09 at 16 19 39" src="https://user-images.githubusercontent.com/55975226/84152271-15ac6c00-aa6d-11ea-89b5-09f74fd477dc.png">

**Comment by vladyslav-iosdev** [comment]
@hboon do i need replace "$" sign to USD ?

**Comment by hboon** [comment]
> @hboon do i need replace "$" sign to USD ?

Yes, would you make the "USD" a non-localised constant somewhere if there isn't already one so we can handle it when we support other currencies in the future?

> @hboon what this green text is? as i understand its the same what displayd above "24 hours", rigth? and where "appreciation/depreciation" should be placed?
> <img alt="Screenshot 2020-06-09 at 16 19 39" width="198" src="https://user-images.githubusercontent.com/55975226/84152271-15ac6c00-aa6d-11ea-89b5-09f74fd477dc.png">

The green text "(+ 2.53%)" is the increase in fiat value of eth and "12.98 USD" is `2.53% * what_the_user_has`. The words "Ethereum Blockchain" for both ETH on mainnet and xDai chain should be replaced by the "457.34 USD" which is the `eth_user_has * price`. All 3 values are already computed and displayed before the PR

**Comment by vladyslav-iosdev** [comment]
> > @hboon do i need replace "$" sign to USD ?
> 
> Yes, would you make the "USD" a non-localised constant somewhere if there isn't already one so we can handle it when we support other currencies in the future?
> 
> > @hboon what this green text is? as i understand its the same what displayd above "24 hours", rigth? and where "appreciation/depreciation" should be placed?
> > <img alt="Screenshot 2020-06-09 at 16 19 39" width="198" src="https://user-images.githubusercontent.com/55975226/84152271-15ac6c00-aa6d-11ea-89b5-09f74fd477dc.png">
> 
> The green text "(+ 2.53%)" is the increase in fiat value of eth and "12.98 USD" is `2.53% * what_the_user_has`. The words "Ethereum Blockchain" for both ETH on mainnet and xDai chain should be replaced by the "457.34 USD" which is the `eth_user_has * price`. All 3 values are already computed and displayed before the PR

Does this right displaying?
<img width="331" alt="Screenshot 2020-06-10 at 11 52 51" src="https://user-images.githubusercontent.com/55975226/84247572-f9620b00-ab10-11ea-855a-b9cdd43c5bc7.png">
i didn't change calculation behaviour, left as it was before. only added USD currency. 
i didn't undestand about replacing `Ethereum Blockchain` blockchainLabel. do i need to  remove parentheses from  `valuePercentageChangePeriodLabel, valueChangeLabel` ?

**Comment by vladyslav-iosdev** [comment]
> @vladyslav-iosdev like how the xDai row is displayed below. It shows "457.34 USD" instead of "Ethereum Blockchain" (or "xDai Blockchain"). The first row (ETH) should show "xxx USD" too. Only do this for ETH on mainnet and xDai as they have prices. But notice how the non-crypto cards below it — Fifa, Celr, Crypto Pepe still shows "Ethereum Blockchain" and they don't have the appreciation values on the right too.
> 
> <img alt="Screenshot 2020-06-10 at 10 40 34 PM" width="440" src="https://user-images.githubusercontent.com/56189/84281655-6b673e00-ab6b-11ea-8413-f2805266e1f1.png">

@hboon Done.
