### ISSUE TITLE
Get rid of unnecessary func arg in `BackupCoordinator.export(for:)`

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#1910]
Verify it's not necessary first.

**Comment by vladyslav-iosdev** [comment]
@hboon this function takes export `account: EthereumAccount` parameter that used over screens for `BackupCoordinator`

**Comment by hboon** [comment]
@vladyslav-iosdev yes, but `export(for:)` is only called within `BackupCoordinator.start()` passing in the `account` property. So `export(or:)` just needs to access the `account` property directly instead of using the arg :)

**Comment by hboon** [comment]
i.e we keep the property, but remove the arg for the `export()` function.

**Comment by vladyslav-iosdev** [comment]
@hboon  done.
