### ISSUE TITLE
Remove "if #available(iOS 11.0, *) {" since we support >= 11

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#1911]

**Comment by vladyslav-iosdev** [comment]
@hboon do i need remove them only from project? there a lot of  `#available(iOS 11.0, *)` in` R.generated` file

**Comment by hboon** [comment]
@vladyslav-iosdev we only need to remove from the project.

`R.generated.swift` is autogenerated from our resource files (font, images, localisation, etc). It should never be hand edited (not just for this PR). But it's strange that it generates the check for iOS 11. But never mind that.
