### ISSUE TITLE
Background color revealed in Wallet and Transactions tab when pulling down to refresh is wrong

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#1912]
<img src="https://user-images.githubusercontent.com/56189/84354567-b036b780-abf3-11ea-9f55-0cd6b4c4970c.jpeg" width=200>

Reproducible this on iPhone X 13.3 device. But not on iPhone X 12.4 simulator and 13.3 simulator

The annotated section should be white

**Comment by vladyslav-iosdev** [comment]
@hboon i can't reproduce this, tested on Iphone X 13.4 (don't have 13.3) 
![photo_2020-06-11_13-04-17](https://user-images.githubusercontent.com/55975226/84493427-66f86d80-acb0-11ea-8ff3-f9611e323a07.jpg)

**Comment by hboon** [comment]
The background color of the area where the activity view is in your screenshot. That’s the part I’m referring to. It should be white instead of gray. If you run it in the simulator, it looks different — it is white.

**Comment by vladyslav-iosdev** [comment]
> The background color of the area where the activity view is in your screenshot. That’s the part I’m referring to. It should be white instead of gray. If you run it in the simulator, it looks different — it is white.

ooo, ok, so i guess it breaks my prev task where was need to change table view background. i will remove it and left white color for table view.

**Comment by hboon** [comment]
> > The background color of the area where the activity view is in your screenshot. That’s the part I’m referring to. It should be white instead of gray. If you run it in the simulator, it looks different — it is white.
> 
> ooo, ok, so i guess it breaks my prev task where was need to change table view background. i will remove it and left white color for table view.

It makes the previous fix unnecessary since the fix (in your PR) seems to make the table view background always white. Make sense! :)

**Comment by tomekalphawallet** [comment]
Also, when the list is short and does not take the whole real estate on the screen, make a background color alabaster #fbfbfb 

Uploading hot it looks at the moment (it's darker gray)
![2020-06-16 19 26 30](https://user-images.githubusercontent.com/51817359/84810012-07c98e80-b00b-11ea-8fdd-9a4252cdd440.png)

![2020-06-16 19 26 27](https://user-images.githubusercontent.com/51817359/84810006-05673480-b00b-11ea-9c74-94fd4befea3f.png)

**Comment by vladyslav-iosdev** [comment]
> Also, when the list is short and does not take the whole real estate on the screen, make a background color alabaster #fbfbfb
> 
> Uploading hot it looks at the moment (it's darker gray)

@tomekalphawallet this Alabaster color need apply only to settings screen?

**Comment by tomekalphawallet** [comment]
> > Also, when the list is short and does not take the whole real estate on the screen, make a background color alabaster #fbfbfb
> > Uploading hot it looks at the moment (it's darker gray)
> 
> @tomekalphawallet this Alabaster color need apply only to settings screen?

There are a few places. Usually, the background is white. But there are few places, where we have to distinct where we have the end the list, separator etc.

<img width="452" alt="Screenshot 2020-06-23 10 58 46" src="https://user-images.githubusercontent.com/51817359/85384908-efdd9780-b541-11ea-8d0d-9d47efd95feb.png">
<img width="666" alt="Screenshot 2020-06-23 11 03 51" src="https://user-images.githubusercontent.com/51817359/85384915-f23ff180-b541-11ea-9625-0af9fa4562ae.png">
<img width="668" alt="Screenshot 2020-06-23 11 03 58" src="https://user-images.githubusercontent.com/51817359/85384923-f5d37880-b541-11ea-8f1a-a62908ffe7c9.png">
<img width="843" alt="Screenshot 2020-06-23 11 04 24" src="https://user-images.githubusercontent.com/51817359/85384931-f8ce6900-b541-11ea-8198-35a3e57daf5f.png">
<img width="1787" alt="Screenshot 2020-06-23 11 05 04" src="https://user-images.githubusercontent.com/51817359/85384939-fc61f000-b541-11ea-9b51-df22c0103cf8.png">
