### ISSUE TITLE
Typing/pasting an Ethereum address into the address field in send ERC20/ETH screen should also do reverse ENS lookup

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#1914]
Display it in the label below the address textbox (the label that shows the address when an ENS name is entered)

Relevant:

* SendViewController
* ENSReverseLookupCoordinator

Should be careful not to have unnecessary look ups:

* Don't try when the address length is not complete

**Comment by vladyslav-iosdev** [comment]
@hboon Am i undastand right. when we typing address (with ens name) after ens name detected text field with address will be replaced with with ens name, and address will appear below text field? like when we paste esn directly?

**Comment by hboon** [comment]
No. We don’t change what the user types in the textfield. If they type an ENS name, the address appears in the label below. (This is the forward lookup and works now).

If they type an address, the ENS name appears in the label below. This is the reverse lookup which works in the list of wallets screen, but not in the Send screen yet.
