### ISSUE TITLE
Add support for .crypto (UnstoppableDomains) domain lookup

### ISSUE THREAD

**Issue by JamesSmartCell** [AlphaWallet/alpha-wallet-ios#1931]
Support New Blockchain name lookup service: https://unstoppabledomains.com/

Lookup is quite straightforward. When presented with a name ending in .crypto:

1. fetch resolver contract, call 'resolverOf(uint256 nameHash)' on contract ```0xD1E5b0FF1287aA9f9A268759062E4Ab08b9Dacbe```

```resolver = function resolverOf(uint256 nameHash) returns Address```

eg ```nameHash of 'brad.crypto' is 0x756e4e998dbffd803c21d23b06cd855cdc7a4b57706c95964a37e24b47c10fc9```
```resolverOf(0x756e4e998dbffd803c21d23b06cd855cdc7a4b57706c95964a37e24b47c10fc9)```

result:

```0xb66DcE2DA6afAAa98F2013446dBCB0f4B0ab2842```

2. lookup name address using the resolver contract found in step 1.

```function get(string key, uint256 nameHash) returns string```

where key is always ```crypto.ETH.address``` for ethereum lookup, eg:

```get('crypto.ETH.address', 0x756e4e998dbffd803c21d23b06cd855cdc7a4b57706c95964a37e24b47c10fc9)```

result:

```0x8aaD44321A86b170879d7A244c1e8d360c99DdA8```

BEWARE! look at the function prototypes, they are different from ENS.

**Comment by hboon** [comment]
@James-Sangalli do you want to take on this?

**Comment by vladyslav-iosdev** [comment]
@hboon its not really clear what do i need to do here, can u provide more details?

**Comment by hboon** [comment]
It’s a name service like ENS. So we should be able to add support for like we do for ENS

**Comment by vladyslav-iosdev** [comment]
@hboon i need to replace calling `GetENSAddressCoordinator(server: serverToResolveEns).getENSAddressFromResolver(for: value)` with calling this new service?
