### ISSUE TITLE
FIFA and Car Token is not showing up automatically 

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/alpha-wallet-ios#1942]
If have balance, they should show up automatically

**Comment by hboon** [comment]
@zhangzhongnan928 0xA66A3F08068174e8F005112A8b2c7A507a822335 for FIFA? What is the contract and chain for Car Token?

**Comment by zhangzhongnan928** [comment]
> @zhangzhongnan928 0xA66A3F08068174e8F005112A8b2c7A507a822335 for FIFA? 
YES

What is the contract and chain for Car Token?
0x75cB2Cc380d1387a79eE64b1b7C9Fa051139a319 
on Rinkeby
