### ISSUE TITLE
Showing the send screen the first time for a token which has no exchange rate/price should not show the down arrow

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#1949]
<img src="https://user-images.githubusercontent.com/56189/85371885-92f2d900-b563-11ea-96d2-d420a8c20643.png" width=200>

The behavior is correct (arrow not shown) when we scan an EIP681 link to switch from Ether (mainnet) to something that has no rate (eg. DAI/SAI)

**Comment by vladyslav-iosdev** [comment]
@hboon what fields in SendViewModel related for rate/price ?

**Comment by hboon** [comment]
> @hboon what fields in SendViewModel related for rate/price ?

Look for `storage.tickers` in `SendViewModel`.
