### ISSUE TITLE
Extract a UILabel wrapper or subclass which displays Ethereum address and/or ENS name

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#1950]
There at at least a few possibilities:

* Just address (sometimes the full address, sometimes shortened to 0xabcd...abcd)
* Just ENS
* "<ENS> | <address>" (in Settings screen)
* Maybe more?

Can you replace all of them with a single class with a way to configure them?

If it makes sense, let it be able to resolve, reverse resolve ENS names too, but might not be.

**Comment by vladyslav-iosdev** [comment]
@hboon I created AddressOrEnsNameLabel and applied it to AddressTextField, also i updated it with requirements from #1213 (loading indicator) (because it was isier to implement it in on PR, to prevent conflicts).  Check it, if its ok, them i will update resp places where it needed
