### ISSUE TITLE
Allow users to watch ENS names too

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#1951]
Accessible via Settings > Change / Add Wallet > + > Watch Wallet

Also show the equivalent address/ENS name below the textfield in the Watch agree

Complete the resolution before allowing the user to watch an address, so we don't have to track that the user watched an ENS name; we still track the Ethereum address it maps to.

**Comment by vladyslav-iosdev** [comment]
@hboon,i am not clearly undastans requirements for this task. as i undsrstand correctly AddressTextField can resolve address/ens by itself and displays it. Can you provide more details for this task, thx ;)

**Comment by hboon** [comment]
@vladyslav-iosdev sorry, it does work already :)
