### ISSUE TITLE
Reduce number of NumberFormatter and EtherNumberFormatter defined, if possible

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#1954]
Do a sweep, especially in `CurrencyFormatter.swift` and `EtherNumberFormatter.swift`.

Generally, we want to round down to 4 decimal places for crypto balances (but for transaction amounts, we display the full value) and round down to 2 decimal places for fiat.

Can you extract the `4` decimal places to a constant? (the other project fork will want 5 instead)

Take care with refactoring because:

* amounts are sensitive
* the other project fork is affected by this too. We'll probably copy these changes over to the other repo.

Add test cases with something like this:

```
        let values: [(BigInt, String)] = [
            (BigInt("1123450000000000000"), "1.1234"),
            (BigInt("1123440000000000000"), "1.1234"),
            (BigInt("1123490000000000000"), "1.1234"),
            (BigInt("1123499000000000000"), "1.1234"),
            (BigInt("1123990000000000000"), "1.1239"),

            (BigInt("1123850000000000000"), "1.1238"),
            (BigInt("1123840000000000000"), "1.1238"),
            (BigInt("1123890000000000000"), "1.1238"),
            (BigInt("1123899000000000000"), "1.1238"),
        ]
        for each in values {
            //EtherNumberFormatter.short.string(from: each.0, decimals: 18)
        }
```

**Comment by vladyslav-iosdev** [comment]
@hboon Related to `CurrencyFormatter` you mean to move this
```
let formatter = NumberFormatter()
formatter.minimumFractionDigits = 4
formatter.maximumFractionDigits = 4
formatter.roundingMode = .down
```
to constant and other formatters in `CurrencyFormatter` should use it as base?

**Comment by vladyslav-iosdev** [comment]
@hboon  what do i need to sweep in EtherNumberFormatter? there is only full/short formatter

**Comment by hboon** [comment]
> @hboon what do i need to sweep in EtherNumberFormatter? there is only full/short formatter

I supposed you just did and checked that there is no duplicate and unnecessary formatters in those 2 files :)

> @hboon Related to `CurrencyFormatter` you mean to move this
> 
> ```
> let formatter = NumberFormatter()
> formatter.minimumFractionDigits = 4
> formatter.maximumFractionDigits = 4
> formatter.roundingMode = .down
> ```
> 
> to constant and other formatters in `CurrencyFormatter` should use it as base?

Just extract the `4` in `EtherNumberFormatter.swift` into a constant and the `2` in `CurrencyFormatter`. No need to change the formatters themselves.

There's a `CurrencyFormatter.shortFormatter` which seems to be used for tokens/crypto, can you see if that can be replaced with something from EtherNumberFormatter or otherwise moved into `EtherNumberFormatter`?

I guess the goal is make this easier and harder to miss a spot:

* if we want to change 4 -> 5 for ether/tokens
* change how fiat is displayed

**Comment by vladyslav-iosdev** [comment]
@hboon What if i create factory extension for `NumberFormatter` with formatters for usd/short eth. and then i remove `shortFormatter`, usdFormatter, instead i will use CurrencyFormatter.formatter.usd or CurrencyFormatter.formatter.short. does it make sens?

**Comment by vladyslav-iosdev** [comment]
making this we even can remove CurrencyFormatter and do formatting just create let x = NumberFormatter().usd

**Comment by hboon** [comment]
> @hboon What if i create factory extension for `NumberFormatter` with formatters for usd/short eth. and then i remove `shortFormatter`, usdFormatter, instead i will use CurrencyFormatter.formatter.usd or CurrencyFormatter.formatter.short. does it make sens?

Sure. Sounds like a great improvement :) Just bear in mind that while we call it `usd`, it might have to handle other currencies formatting in the future (but we can assume it will be just a specific currency the user has chosen). But don't worry about the name itself, we can call it `use` for now. Also the performance hit for creating new instances of formatters.

Also bear in mind that we might want to copy this changes over to the other repo we are working on (depends on what is changed and if it's worth it/necessary), otherwise it'll get picked up with we rebase, which is done quite rarely.
