### ISSUE TITLE
Replace all `button.backgroundColor = ` with `setBackgroundColor(_:forState:)`

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#1955]
Maybe look for "utton.backgroundColor = "

I forgot why the former doesn't work properly. @vladyslav-iosdev do you know why?

**Comment by vladyslav-iosdev** [comment]
> Maybe look for "utton.backgroundColor = "
> 
> I forgot why the former doesn't work properly. @vladyslav-iosdev do you know why?

i am not sure clearly about it, but as this guy tells in this article, it just not supported for UIButton, or it depends on states button could be.
https://spin.atomicobject.com/2018/04/25/uibutton-background-color/

**Comment by hboon** [comment]
Ok. Would you help to fix those? I think it works sometimes, but will break unpredictably, so better to replace them.

**Comment by vladyslav-iosdev** [comment]
> Ok. Would you help to fix those? I think it works sometimes, but will break unpredictably, so better to replace them.

@hboon PR has been sent
