### ISSUE TITLE
Make tap token in Wallet tab push instead of present modal

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#1956]
There are many of these across the app that we will want to replace ultimately or change the modal presentation style to the card-style that comes with iOS 13. We have to be careful that it still displays correctly (especially the navigation bar) and that it gets popped (vs dismissed) correctly, and that clean up is done correctly. The coordinators might have been written to assume that it is presented modally and not pushed onto a navigation controller.

There should be a call to `makePresentationFullScreenForiOS13Migration()` for each of this change.  They are mainly to track these as TODOs. The call should be removed (and replaced with the explicit `modalPresentationStyle = xxx` line if we still want it to be modal).

This issue is for 1 of them:

You can trace it from `TokensViewController.tableView(_:didSelectRowAt:)`.

**Comment by vladyslav-iosdev** [comment]
@hboon i guess i am not clearly understand task requirements, **"push"** it doesn't mean to push into navigation controller, right

**Comment by hboon** [comment]
It does mean that. Change from present to push.

**Comment by vladyslav-iosdev** [comment]
@hboon, what screens do i need to handle with **modal** presentation style?
also about these **card style presentations**, do i need to add `isModalInPresentation` to prevent dissmiss by swipe down?

**Comment by hboon** [comment]
@vladyslav-iosdev to show SendViewController? Yes. You can do it together or separately.
