### ISSUE TITLE
Add bundled token icons

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#1958]
Add more bundled token icons into `AlphaWalletAddress+UI.swift`, in `tokenImage`. Watch out that the hardcoded addresses in the switch-case has to be in eip55String (i.e. the correct combination of upper/lowercase) to work correctly.

---

From Tomek at https://github.com/AlphaWallet/alpha-wallet-ios/issues/1665#issuecomment-648022585:

I added 

**a) ptokens:** 

pdai - https://zpl.io/2ENB0GY
psai - https://zpl.io/ag4M3q0
peth - https://zpl.io/2j6QJQr
pbtc - https://zpl.io/2p64JXN
peos - https://zpl.io/VKRPzgP
pusdt - https://zpl.io/VYvKE4L
pltc - https://zpl.io/a7AO00v

b) synthetix tokens

saud - https://zpl.io/VkqG6Lv
sgbp - https://zpl.io/boqDXWo
seur - https://zpl.io/aXxPvD8
sjpy - https://zpl.io/aR51pBr
schf - https://zpl.io/2yAOZXp
susd - https://zpl.io/V049Ej9
sbtc - https://zpl.io/V04qB6l
sxtz - https://zpl.io/2GKy0Nd
sxmr - https://zpl.io/VYvKEmJ
sdefi - https://zpl.io/bJm7Rj3
sada- https://zpl.io/2p64JYN
sltc - https://zpl.io/bJm7Rl9
seth - https://zpl.io/boqDXOW
snikkei - https://zpl.io/bzgNZJ4
sxau - https://zpl.io/aR51JMg
slink - https://zpl.io/beqDEwP

**c) others**
teo - https://zpl.io/a7AO9ZR
eos - https://zpl.io/bzgNEWX
nest - https://zpl.io/VQXLZ74 
link - https://zpl.io/agpvKqO
alphawallet discovery token - https://zpl.io/25D5OwW

**Comment by vladyslav-iosdev** [comment]
@hboon how could i determine which eip55String related to its icon?

**Comment by hboon** [comment]
Google + Etherscan :)

Note that some of them would have migrated (maybe more than once). Use the last address.

eg. one of the old sAUD https://etherscan.io/address/0xACa2179a884bAC7C3D0bc4131585E1B7DbDD048e

But Etherscan points to the latest near the top of that page to: https://etherscan.io/address/0xe04d8770Dc06135Dd97214ea8bcbf7B1CC057AA3

To get the eip55String, create AlphaWallet.Address(string:) on each one and print out the the result of `eip55String`.

**Comment by vladyslav-iosdev** [comment]
@hboon i can't find any information related to psai token. also in Zeplin it route to pdai icon.
also can't find peos token.

**Comment by hboon** [comment]
@vladyslav-iosdev ok. Do what you can, and can you make a list of those you can’t identify?

**Comment by vladyslav-iosdev** [comment]
didn't find any information:
- psai token
- peos token

the rest of tokens i find.

**Comment by vladyslav-iosdev** [comment]
> didn't find any information:
> 
> * psai token
> * peos token
> 
> the rest of tokens i find.

**Comment by hboon** [comment]
Seems to be testnet or not released at the moment, so let's ignore those.

**Comment by vladyslav-iosdev** [comment]
> Seems to be testnet or not released at the moment according to https://ptokens.io, so let's ignore those.

In this case  you can review this task. Other tokens added.
