### ISSUE TITLE
wallet-connect based authentication

### ISSUE THREAD

**Issue by colourful-land** [AlphaWallet/alpha-wallet-ios#1959]
to get wallet-connect working for authentication (for now, but we also hope it works for transaction signing which needs a bit of design).

You can hide this feature in a menu and we will first test it and then come up with the right ux design. 

experiment by trying to login through QR code on https://localcryptos.com/login

Familiar yourself with wallet-connect. You can get a wallet connect QR code to start with, by attempting to login to websites that uses it, like https://localcryptos.com/login

You will get a QR code like this:

![Screenshot_2020-06-10 Log In To LocalCryptos](https://user-images.githubusercontent.com/548435/85364805-4c06e280-b567-11ea-9889-2b1b1952fb22.png)

Which, if decrypted, has this link:

    wc:a97c80fa-e54a-4346-a805-25c293ac1c4c@1?bridge=https://bridge.walletconnect.org&key=14c4225e2cafddf44e0508fc2c2769853f396734c1b6efd3802f62bc51b2b667

**Comment by vladyslav-iosdev** [comment]
@hboon i am not clearly understand requirements for this task, can you provide more details?

**Comment by hboon** [comment]
@vladyslav-iosdev Sorry, I didn't include enough context :)

As you know the AlphaWallet app is an Ethereum wallet app, so it manages a set of keys (~ wallets). When the user wants to sign a piece of data (often a transaction), e.g they want to send some Ether, the app pops up a confirmation box and if the user agrees to proceed, the app signs the transaction using the user's key.

The built-in browser also allows users to visit a dapp (a website that integrates the web3.js library or similar) and when they perform an action, the dapp can trigger the same prompt in the app to sign data (often a transaction).

The keys don't leave the device.

What if the user wants to use a desktop browser like Safari.app, navigates to a website (dapp) and want to sign? Here's where WalletConnect comes in. It's basically a bridge/proxy protocol.

Basically you can start a WalletConnect session by scanning a QR code, and AlphaWallet app can sign data which the user is using their desktop (or another device).

We don't support WalletConnect at all in the app, so scanning a QR code for WalletConnect (like the ones we get from https://localcryptos.com/login) doesn't work. You'll have to build it as part of this.

Read more at:

https://walletconnect.org

There's a Swift SDK linked from there which has an example app.

Here are the screens:

https://app.zeplin.io/project/5d0356be2f25b319dcc5944b/screen/5ef326f4efab124620c80c7b
https://app.zeplin.io/project/5d0356be2f25b319dcc5944b/screen/5ef326f4a77805441903e05e
https://app.zeplin.io/project/5d0356be2f25b319dcc5944b/screen/5ef326faa77805441903e0c7

I think we can let the user trigger it from the Settings screen > Advanced for now.

Can you make up a screen with a list of active sessions?

One thing to keep in mind, we'll ultimately want to offer #1723, but not in this PR.

> (for now, but we also hope it works for transaction signing which needs a bit of design).

**Comment by vladyslav-iosdev** [comment]
@hboon while working on this task I encountered such a problem as I even can't install WalletConnectSwift pod, for me it breaks existed dependencies in pod file. i got next:

```
CocoaPods could not find compatible versions for pod "CryptoSwift":
  In snapshot (Podfile.lock):
    CryptoSwift (= 0.10.0, ~> 0.10.0)

  In Podfile:
    CryptoSwift

    TrustKeystore (from `https://github.com/alpha-wallet/trust-keystore.git`, commit `37f7eaf9531cb4e33d06129543b3a56972f59d2a`) was resolved to 0.1.3, which depends on
      CryptoSwift (~> 0.10.0)

    WalletConnectSwift (~> 1.0.0) was resolved to 1.0.1, which depends on
      CryptoSwift (~> 1.0)
```

**Comment by vladyslav-iosdev** [comment]
i realized how to fix it :)

**Comment by vladyslav-iosdev** [comment]
@hboon here in existing example to WalletConnect server/client apps i found ability to store sessions locally, do i need to add saving session to Realm db?

**Comment by vladyslav-iosdev** [comment]
> @hboon here in existing example to WalletConnect server/client apps i found ability to store sessions locally, do i need to add saving session to Realm db? to restore them in case if app was closed, and opened again.

**Comment by hboon** [comment]
>@hboon here in existing example to WalletConnect server/client apps i found ability to store sessions locally, do i need to add saving session to Realm db?

@vladyslav-iosdev is there anything on WalletConnect-side that limits how long sessions can last?

Let’s just store it in memory first and not worry about it.

**Comment by vladyslav-iosdev** [comment]
> @vladyslav-iosdev is there anything on WalletConnect-side that limits how long sessions can last?

i need to investigate this question.

**Comment by hboon** [comment]
>> @vladyslav-iosdev is there anything on WalletConnect-side that limits how long sessions can last? ...

@vladyslav-iosdev lower priority than getting a first cut to work in memory though

**Comment by vladyslav-iosdev** [comment]
@hboon can u help me to match actions from `DappAction`
   ```
case signMessage(String)
   case signPersonalMessage(String)
   case signTypedMessage([EthTypedData])
   case signTransaction(UnconfirmedTransaction)
   case sendTransaction(UnconfirmedTransaction)
   case unknown
```
with WalletConnect actions, https://docs.walletconnect.org/json-rpc-api-methods/ethereum

**Comment by hboon** [comment]
```
personal_sign - signPersonalMessage
eth_sign - signPersonalMessage
eth_signTypedData - signTypedMessage
eth_sendTransaction - sendTransaction
eth_signTransaction - signTransaction
eth_sendRawTransaction - seems like we might have to build it based on sendTransaction?
```

But the ones on the right are for the dapp browser, right? Maybe better to (indirectly) call the functions in `EtherKeystore` like `func signPersonalMessage(_:for:)` since you are calling from the WalletConnect bridging code?

**Comment by hboon** [comment]
But I suppose you would build up a similar list of enum and cases for wallet connect.

**Comment by vladyslav-iosdev** [comment]
> But the ones on the right are for the dapp browser, right?

yep, right.

**Comment by vladyslav-iosdev** [comment]
@hboon can u send me some eth to wallet 0x5d4Fdf90c45a7310e7DeAB4471038C067c2BdfCE to test Wallet Connect transaction.?

**Comment by hboon** [comment]
Done for mainnet and rospten

**Comment by vladyslav-iosdev** [comment]
@hboon for me its not clear what do i need to do with eth_sendRawTransaction (here i receive hash of transaction and what do i need to do next with it?)

**Comment by vladyslav-iosdev** [comment]
i updated code and seems like next action in working

**personal_sign - work
eth_sign - work**
eth_signTypedData - doesn't work
**eth_sendTransaction - work
eth_signTransaction - work**
eth_sendRawTransaction doesn't work

**Comment by hboon** [comment]
> @hboon for me its not clear what do i need to do with eth_sendRawTransaction (here i receive hash of transaction and what do i need to do next with it?)

For `eth_sendRawTransaction`, it means the transaction has already been signed (which is that hash string). So just need to send it. Refer to `SendRawTransactionRequest`.
