### ISSUE TITLE
Price per token should be ETH not the token name

### ISSUE THREAD

**Issue by James-Sangalli** [AlphaWallet/alpha-wallet-ios#1961]
![IMG_EB6B295654F4-1](https://user-images.githubusercontent.com/16630514/85509288-103c4d80-b639-11ea-949a-638ea6424232.jpeg)

**Comment by zhangzhongnan928** [comment]
![IMG_3603](https://user-images.githubusercontent.com/33795543/85514379-53012400-b63f-11ea-9a62-d847fbbf3fa0.PNG)

And if the currency symbol is too long, it will cover the amount input box

**Comment by vladyslav-iosdev** [comment]
@hboon, i am not shure if it will be good, but what if I update `AmountTextField.Currency` with `.cryptoCurrency(TokenObject, alternativeSymbol: String?)` case. With this we can update `var symbol: String ` to return `alternativeSymbol ?? tokenObject.symbol` and by default for AmountTextField alternativeSymbol will be nil, and in place where se need it we will provide right value?

**Comment by vladyslav-iosdev** [comment]
> @hboon, i am not shure if it will be good, but what if I update `AmountTextField.Currency` with `.cryptoCurrency(TokenObject, alternativeSymbol: String?)` case. With this we can update `var symbol: String ` to return `alternativeSymbol ?? tokenObject.symbol` and by default for AmountTextField alternativeSymbol will be nil, and in place where se need it we will provide right value?

@hboon in this case token icon also get changed, does it ok?

**Comment by hboon** [comment]
@vladyslav-iosdev saw the reply in my PR? The icon will be for the native crypto token (ether and USD)

**Comment by hboon** [comment]
@James-Sangalli this was merged
