### ISSUE TITLE
Show current market price instead of price diff in wallet tab

### ISSUE THREAD

**Issue by tomekalphawallet** [AlphaWallet/alpha-wallet-ios#1981]
Amount + Ticker ( 3.4525 ETH)
Value in USD (674 USD)----------------------- Market Price ( 226 USD) Price change in % (+2.34%)

![2020-07-01 08 22 22](https://user-images.githubusercontent.com/51817359/86210806-867b0b80-bb75-11ea-925f-158663985472.png)

**Comment by hboon** [comment]
@tomekalphawallet I don't understand. Can you help phrase it like this:

Expected
---
"abc xyz"

Observed
---
"def x.y.z USD"

**Comment by hboon** [comment]
@tomekalphawallet never mind. Got it now. Thanks

**Comment by tomekalphawallet** [comment]
<img width="1127" alt="Screenshot 2020-07-01 08 42 06" src="https://user-images.githubusercontent.com/51817359/86211649-06ee3c00-bb77-11ea-9827-3f9dc95eadea.png">

**Comment by tomekalphawallet** [comment]
In the example I created, look at ETH only as xDAI has wrong values. ;) You got it.

**Comment by hboon** [comment]
@tomekalphawallet yeah, but ETH is also bad. It 1.5 ETH could well be 226 USD :) But yeah, I get it, haha

**Comment by hboon** [comment]
The amount circled/underlined in red is currently showing the fiat equivalent amount incremented/decremented. It should show the price of 1 token (ETH/xDai) instead. i.e. no math.

**Comment by colourful-land** [comment]
@tomekalphawallet why do you expect the price of xDAI being 0 USD?
@hboon I personally think this information should disappear if the token is on the test net - in fact, I think that's the palce where the word "ropstern testnet" should appear. what do you think @tomekalphawallet

**Comment by tomekalphawallet** [comment]
> @tomekalphawallet why do you expect the price of xDAI being 0 USD?

This is not correct. Here is the correct screen. 

<img width="612" alt="Screenshot 2020-07-01 09 45 04" src="https://user-images.githubusercontent.com/51817359/86217290-8f70da80-bb7f-11ea-9fd4-d36c6018fe8c.png">

**Comment by tomekalphawallet** [comment]
Also, after speaking with Weiwu, we agreed on how to display tokens on testnet (like Ropsten). 
The logic is:
- if a token is on mainnet = no change, no indication
- if a token is on testnet = indicate it by network name in the same place where we usually have market price 

https://zpl.io/VKR85Z7

<img width="656" alt="Screenshot 2020-07-01 09 42 41" src="https://user-images.githubusercontent.com/51817359/86217550-ec6c9080-bb7f-11ea-912d-09ad84c24992.png">

**Comment by hboon** [comment]
- [ ] Show current market price instead of price diff in wallet tab
- [ ] Display test name, if test net

**Comment by hboon** [comment]
> * if a token is on testnet = indicate it by network name in the same place where we usually have market price

Do you want to move the testnet name upwards? There should be just 1 row, since "340.57 USD" shouldn't be shown; the tokens have no value.

**Comment by tomekalphawallet** [comment]
Whatever is easier for you. Don't have a strong preference.

**Comment by hboon** [comment]
> Whatever is easier for you. Don't have a strong preference.

Ok.
