### ISSUE TITLE
Show testnet label in cells if testnet in Wallet tab

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#1984]
Like in https://github.com/AlphaWallet/alpha-wallet-ios/issues/1981#issuecomment-652254180

Show that "ROPSTEN" label in the bottom row. We used to have something like that (and we still show it in other screens which haven't been updated yet), so remember to use the same colors because we use it for the token icons also.

Ignore this comment of mine:

> Do you want to move the testnet name upwards? There should be just 1 row, since "340.57 USD" shouldn't be shown; the tokens have no value.

**Comment by vladyslav-iosdev** [comment]
@hboon am i understood right, for this task i need update only `EthTokenViewCell`?

**Comment by vladyslav-iosdev** [comment]
> @hboon am i understood right, for this task i need update only `EthTokenViewCell`, and i should display blockChainTag, when server.isTestnet?

**Comment by hboon** [comment]
@vladyslav-iosdev no, all of the cells in TokensViewController. I think there are 3 or 4 of them.
