### ISSUE TITLE
Make address text field and auxiliary UI components in Transfer NFT screen look like Send screen

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#1991]
These steps are for the simulator:

1. Watch the wallet 0x007bEe82BDd9e866b2bd114780a47f2261C684E3
2. Look for the token 0xa3347C8ED134444C25169872c90a6360D42b3691. Add it if it was not auto detected in the wallet
3. Tap on the token in the app (you will need to make some temporary changes to the code so you can attempt to proceed as if it's not a watched wallet)
4. In the Xcode console, scroll to the line where the .realm and Documents/ directory for the app running in the simulator is logged. It's logged at the start of the app and whenever you switch wallet. Open that Documents/ directory in Finder
5. Download this file: `curl https://repo.tokenscript.org/2020/06/0xA66A3F08068174e8F005112A8b2c7A507a822335` and save it to the Documents/assetDefinitionsOverrides/ directory
6. Open the file to edit.
7. Look for this:

```
    <ts:contract interface="erc875" name="FIFA">
        <ts:address network="1">0xA66A3F08068174e8F005112A8b2c7A507a822335</ts:address>
    </ts:contract>
```

Add a line so it becomes:

```
    <ts:contract interface="erc875" name="FIFA">
        <ts:address network="1">0xA66A3F08068174e8F005112A8b2c7A507a822335</ts:address>
        <ts:address network="1">0xa3347C8ED134444C25169872c90a6360D42b3691</ts:address>
    </ts:contract>
```

8. The screen in the simulator should have changed and a few images displayed
9. Tap on one of them
10. Tap Transfer
11. Tap Next
12. Transfer Now
13. Enter an address (which resolves to an ENS name) or ENS name

Can you make the resolved address/ENS Name, activity indicator aligned left and add the Clear/Paste button so it looks similar to the send screen?

<img src="https://user-images.githubusercontent.com/56189/86431896-97b84980-bd28-11ea-8ddb-506549081151.png" width=200>

**Comment by vladyslav-iosdev** [comment]
@hboon i am working on this task, stuked  a little bit. followed all steps, but i dont see tiket. investigation problem now.

**Comment by vladyslav-iosdev** [comment]
> @hboon i am working on this task, stuked a little bit. followed all steps, but i dont see tiket. investigation problem now.

**Comment by hboon** [comment]
Sure. It’s a good chance to familiarise with a few other parts of the app :)
