### ISSUE TITLE
Introduce a protocol with default implementation so reusable views like UITableViewCells don't need to hardcode a reusable identifier

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#1994]
Add a new file `WithReusableIdentifier.swift`:

```
protocol WithReusableIdentifier {
	static var reusableIdentifier: String { get }
}

extension WithReusableIdentifier {
	static var reusableIdentifier: String {
		String(describing: self)
	}
}

extension UITableViewCell: WithReusableIdentifier {
}
```

and replace something like `AddHideTokensCell.identifier` with `AddHideTokensCell.reusableIdentifier` where `UITableView`s and `UICollectionView`s are used so we end up with:

```
tableView.register(AddHideTokensCell.self, forCellReuseIdentifier: AddHideTokensCell.reusableIdentifier)
```

And we can remove lines like:

```
static let identifier = "AddHideTokensCell"
```

There might be cases where we use more than 1 identifier for a cell class within a table/collection view. I can't remember if there's any of those. If so, just keep those as it is.

We could have abstracted it more to become:

```
tableView.register(AddHideTokensCell.self)
```

But it seems to be too much magic..

**Comment by vladyslav-iosdev** [comment]
@hboon Ok, Greate improvement! 
i also will add `UITableView` help function for dequeue cells, to reduce and make code clearer
```
func dequeueCell<T>(indexPath: IndexPath) -> T where T: WithReusableIdentifier {
        return dequeueReusableCell(withReuseIdentifier: T.reusableIdentifier, for: indexPath) as! T
}
```

**Comment by hboon** [comment]
@vladyslav-iosdev Ok, sounds good. Probably for UICollectionView too. We just have to be careful not to create too much magic and form our own dialects.

**Comment by vladyslav-iosdev** [comment]
> @vladyslav-iosdev Ok, sounds good. Probably for UICollectionView too. We just have to be careful not to create too much magic and form our own dialects.

Its a gonna magic ;)
