### ISSUE TITLE
Implement Gas Estimate node call

### ISSUE THREAD

**Issue by JamesSmartCell** [AlphaWallet/alpha-wallet-ios#1996]
This is a quick mod that will help new users. Rather than the traditional gas limit, network fee (if full gas limit used) have estimated gas and estimated network fee.

On web3j this code:

```
    private Single<EthEstimateGas> ethEstimateGas(String fromAddress, BigInteger nonce, BigInteger gasPrice,
                                               BigInteger gasLimit, String toAddress,
                                               BigInteger amount, String txData, Web3j web3j)
    {
        return Single.fromCallable(() -> {
            Transaction transaction = new Transaction (
                    fromAddress,
                    nonce,
                    gasPrice,
                    gasLimit,
                    toAddress,
                    amount,
                    txData);

            return web3j.ethEstimateGas(transaction).send();
        }).subscribeOn(Schedulers.io());
    }
```

Will return a BigDecimal wei amount which is the gas estimate from the node, or an error with a string detailing that the node thinks the transaction will fail (because eg the function has an assert that the account must be the contract owner).

The node's EVM does a local execution of the transaction and works out how much gas it would use.

Here's what the confirmation page looks like with this modification:

![alphaconfirm](https://user-images.githubusercontent.com/12689544/86433865-2a63e300-bd3f-11ea-8a10-5e04bb9f1175.jpg)

You can see for the kitty transfer the estimate is much lower than the gas limit.

We're starting to get more popular and recently I noticed people being confused about the transaction fee on the AlphaWallet group. You can view the limit as the TX fee and call the difference a 'refund', as some people have. But far easier to understand is the estimate.

Note how it doesn't affect the flow in any way - it's purely informational.

**Comment by JamesSmartCell** [comment]
Note that the ethEstimateGas is a node RPC call: 

```
// Request
curl -X POST --data '{"jsonrpc":"2.0","method":"eth_estimateGas","params":[{see above}],"id":1}'

// Result
{
  "id":1,
  "jsonrpc": "2.0",
  "result": "0x5208" // 21000
}
```

**Comment by James-Sangalli** [comment]
Already do this.
