### ISSUE TITLE
Update header for native crypto / ERC 20 token screens

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#2007]
This is related to #1995. The part that should change is circled in red:

<img src="https://user-images.githubusercontent.com/56189/86512012-c7527900-be30-11ea-937d-8f7ef6e9ca6a.png" width=200>

https://app.zeplin.io/project/5d0356be2f25b319dcc5944b/styleguide/components?cseid=5efeeb8d3e258fb78e39e09b

Refer to https://github.com/AlphaWallet/alpha-wallet-ios/issues/1995#issuecomment-653405327 to see how the line "Market Price: xxx" changes when tapped. There are 3 states. Start with "Value: xxx", then "Market Price: xxx", then "Available: ", then circle back again. Ignore "Earned so far: xxx" in Zeplin.

Notice that like the cells in Wallet tab, there are at least a few variations:

* native crypto where fiat value is available
* native crypto where fiat value is not available
* tokens, no fiat value
* native crypto or tokens for testnets

Can you see if there are other screens that uses this display or a very similar display? We might want to update those too.

**Comment by vladyslav-iosdev** [comment]
@hboon can you help me a little bit, can you remind me how to detect fiat value is available or not?

**Comment by hboon** [comment]
The price is usually stored as "ticker" in the code base.

In `TokenViewController`, there is this line, which is related:

```
let ticker = celf.tokensDataStore.coinTicker(for: etherToken)
```

**Comment by vladyslav-iosdev** [comment]
@hboon also can tell me where i can find `Earned so far:` value?

**Comment by hboon** [comment]
>@hboon also can tell me where i can find `Earned so far:` value?

@vladyslav-iosdev ignore that.

**Comment by tomekalphawallet** [comment]
Also related to https://github.com/AlphaWallet/alpha-wallet-ios/issues/1754

**Comment by tomekalphawallet** [comment]
I am really excited to see this live :)

**Comment by hboon** [comment]
@tomekalphawallet also a little follow up with #2082
