### ISSUE TITLE
ENS transfer issue

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/alpha-wallet-ios#2008]
![IMG_3769](https://user-images.githubusercontent.com/33795543/86527335-58812880-bee1-11ea-80fb-9d16fef6afc0.PNG)

**Comment by hboon** [comment]
@zhangzhongnan928 is this for all NFTs that you have tried? Or a particular one?

**Comment by zhangzhongnan928** [comment]
> @zhangzhongnan928 is this for all NFTs that you have tried? Or a particular one?

NFT with TokenScript
Tested FIFA, art token, kitty token
Fifa and art token failed

**Comment by hboon** [comment]
@James-Sangalli When I transfer 0x66F08Ca6892017A45Da6FB792a8E946FcBE3d865 on Ropsten, I get: "gas required exceeds allowance (8000029) or always failing transaction".

Any idea why? Notice that kitty is on mainnet.

**Comment by zhangzhongnan928** [comment]
> > @zhangzhongnan928 is this for all NFTs that you have tried? Or a particular one?
> 
> NFT with TokenScript
> Tested FIFA, art token, kitty token
> Fifa and art token failed

yesterday, I successfully submitted a transfer transaction for kitty, but the gas price is only at 9 gwei
https://cn.etherscan.com/tx/0x84fbddaed1b338ac4fbb905836a4e185d7a8bd79d214af6731cd99ded4bbd73f

Today, when I try to transfer another kitty, it shows error as " your token was not transferred"

I guess, the problem is from gas price. The transfer of NFTs(875, 721, 721+) uses a fixed gas price as 9 gwei.
Currently, 9 gwei is not an acceptable gas price form node. it will return "transaction underpriced"

**Comment by James-Sangalli** [comment]
#2011
