### ISSUE TITLE
Create a "Finance" tab inside the Wallet Tab

### ISSUE THREAD

**Issue by colourful-land** [AlphaWallet/alpha-wallet-ios#2023]
to contain all Compound tokens, and later a known list of Finance related tokens, hard coded.

PR it against the "train-leaves" branch:
https://github.com/AlphaWallet/alpha-wallet-ios/tree/train-leaves

**Comment by hboon** [comment]
Can someone prepare a list of contracts?

**Comment by hboon** [comment]
Dup of #2029
