### ISSUE TITLE
Change transaction confirmation screen popup in TS actions

### ISSUE THREAD

**Issue by James-Sangalli** [AlphaWallet/alpha-wallet-ios#2026]
Design: https://app.zeplin.io/project/5d0356be2f25b319dcc5944b/dashboard?seid=5f0d99dcf783828d19d2d075

This task is to simply replace the layout of the tokenscript transaction popup. No functional changes are to be added at all. 

Original transaction popup in TokenScript:

![IMG_07865FFF5CBE-1](https://user-images.githubusercontent.com/16630514/87619148-db667680-c75e-11ea-9439-8a6c66fcd964.jpeg)

How it should look:
<img width="375" alt="pop" src="https://user-images.githubusercontent.com/16630514/87619203-04870700-c75f-11ea-99ec-315fa2c51442.png">
 
Note: no extra features are to go into this, simply change the layout from the old to the new. You can also remove the arrows in the implementation as we do not have to show anything else. 

To invoke this screen:

- go to the xDAI card
- Click "Convert to DAI"
- Enter a value in the "amount to convert" input
- Press confirm

Related to https://github.com/AlphaWallet/alpha-wallet-ios/pull/2022 but scoped down

**Comment by hboon** [comment]
@James-Sangalli can't do this. Too much work and risk

**Comment by hboon** [comment]
A bit more context for Vlad's benefit. There are a few places in the app where we can post an Ethereum transaction:

A. Native crypto ERC20 Send screen — This uses the transaction confirmation screen which has a gear button to adjust gas.
B. TokenScript actions — This just shows the UIAlertController
C. In the dapp browser — This just shows an UIAlertController (I think, or something like that)
D. Send NFT — just UIAlertController
E. Tap on MagicLink and proceed with transaction. Just UIAlertController

Ultimately, we want to replace all of these with that custom "actionsheet" worked on in #2022. #2022 is just for (A).

This is is a scoped-down version for (B). (B) is ultimately going to be the most complicated among A, B, C, D and E, with fields that show up dynamically depending on the Ethereum function called. Like James mentioned above, this is scoped down, so for this issue, (B) is only showing a gas row and (always display "Default") and a contract row (can read the value somehow). There is nothing for the user to configure.

**Comment by vladyslav-iosdev** [comment]
@hboon do i need to reuse already created `ConfirmPaymentViewController` screen, or just copy it, to `ConfirmTransactionViewController`  for example, and use new one?

**Comment by hboon** [comment]
Copy over the version of `ConfirmPaymentViewController` etc in #2022 (sorry haven't reviewed it yet) for this PR, but make them all new classes rather than amend the existing ones. Since we want to only modify B for now and not change A (which is #2022). We'll merge the PR for this in and assume #2022 is only merged after at least 2-3 weeks.

**Comment by hboon** [comment]
But ultimately (not int the scope of this PR and #2022), A-E should all use the same set of "actionsheet" code

**Comment by vladyslav-iosdev** [comment]
> But ultimately (not int the scope of this PR and #2022), A-E should all use the same set of "actionsheet" code

ok, got it.

**Comment by vladyslav-iosdev** [comment]
@hboon according to this screen shot in new screen i should display only one row with amount, right?
<img width="418" alt="Screenshot 2020-07-16 at 09 10 32" src="https://user-images.githubusercontent.com/55975226/87635118-39875f80-c747-11ea-9749-a89d6bd635ea.png">

**Comment by hboon** [comment]
Yes, this is the correct UIAlertController to replace. But no, don't show the amount at all (for now). Just gas  = "Default" and the contract.

We might revisit this to add it in. But just a scoped-down version with gas and contract for this issue.

**Comment by hboon** [comment]
Done
