### ISSUE TITLE
Finances tab in iOS to show all defi related tokens

### ISSUE THREAD

**Issue by James-Sangalli** [AlphaWallet/alpha-wallet-ios#2029]
DeFi tokens so far supported in our wallet (via TokenScript):

1. aDAI: 0xfC1E690f61EFd961294b3e1Ce3313fBD8aa4f85d
2. cREP: 0x158079ee67fce2f58472a96584a73c7ab9ac95c1
3. cDAI: 0x5d3a536e4d6dbd6114cc1ead35777bab948e3643
4. cETH: 0x4ddc2d193948926d02f9b1fe9e1daa0718270ed5
5. cWBTC: 0xC11b1268C1A384e55C48c2391d8d480264A3A7F4
6. cUSDC: 0x39AA39c021dfbaE8faC545936693aC917d5E7563
7. cBAT: 0x6C8c6b02E7b2BE14d4fA6022Dfd6d75921D90E4E
8. mUSDC: 0x3564ad35b9E95340E5Ace2D6251dbfC76098669B
9. mDAI: 0x06301057D77D54B6e14c7FafFB11Ffc7Cab4eaa7
10. USDC: 0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48 
11. cSAI: 0xF5DCe57282A584D2746FaF1593d3121Fcac444dC
12. COMP: 0xc00e94Cb662C3520282E6f5717214004A7f26888
13. WETH:  0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2
14. DAI: 0x6B175474E89094C44Da98b954EedeAC495271d0F
15. NEST: 0x04abEdA201850aC0124161F037Efd70c74ddC74C
16. Uniswap daiPool: 0x2a1530C4C41db0B0b2bB646CB5Eb1A67b7158667
17. Uniswap saiPool: 0x09cabEC1eAd1c0Ba254B09efb3EE13841712bE14
18. Uniswap sethPool: 0x4740C758859D4651061CC9CDEFdBa92BDc3a845d
19. Uniswap usdcPool: 0x97dec872013f6b5fb443861090ad931542878126
20. Uniswap wbtcPool: 0x4d2f5cfba55ae412221182d8475bc85799a5644b
21. Uniswap wethPool: 0xA2881A90Bf33F03E7a3f803765Cd2ED5c8928dFb
22. USDCx: 0xeb269732ab75A6fD61Ea60b06fE994cD32a83549
23. mETH: 0xdF9307DFf0a1B57660F60f9457D32027a55ca0B2
24. cZRX: 0xB3319f5D18Bc0D84dD1b4825Dcde5d5f7266d407

**Comment by hboon** [comment]
@James-Sangalli Can someone prepare a list of contracts?

**Comment by James-Sangalli** [comment]
> @James-Sangalli Can someone prepare a list of contracts?

@hboon see edited comment

**Comment by hboon** [comment]
This is to add a "tab" to the Wallet tab (`TokensViewController`), between `All` and `Currencies`.

**Comment by vladyslav-iosdev** [comment]
@hboon can you please explain what do i need to do with this list of contracts?

**Comment by hboon** [comment]
@vladyslav-iosdev when this new "Finance" tab is tapped, show only tokens matching this list of contracts.

In other words, modify `FilterTokensCoordinator.filterTokens(tokens:filter)` to check for the new enum-case representing this new tab.

**Comment by hboon** [comment]
Done
