### ISSUE TITLE
Show transaction confirmation information (marriage proposal) after each action complete in TS

### ISSUE THREAD

**Issue by James-Sangalli** [AlphaWallet/alpha-wallet-ios#2030]
https://app.zeplin.io/project/5d0356be2f25b319dcc5944b/screen/5f0d9787fbff438dfee0f65d

**Comment by vladyslav-iosdev** [comment]
@James-Sangalli can you help me with places where i need to show this confirmation information screen?

**Comment by colourful-land** [comment]
> @James-Sangalli can you help me with places where i need to show this confirmation information screen?

This screen shows after each tx is sent from an action card and it leads the user back to the token where the user started.
