### ISSUE TITLE
Upload pTokens icons

### ISSUE THREAD

**Issue by tomekalphawallet** [AlphaWallet/alpha-wallet-ios#2041]
https://app.zeplin.io/styleguide/5e0b4e7149e83f987edc0a9e/components?cseid=5f0ed009ca3a099cf93e5744

![photo_2020-07-16 14 05 51](https://user-images.githubusercontent.com/51817359/87669021-82eaa580-c76d-11ea-94d8-b95a7a1eae94.jpeg)

**Comment by vladyslav-iosdev** [comment]
@hboon all ptokens has been added except p-sai, p-eos, i couldn't find contracts for them.
