### ISSUE TITLE
Make backup seed phrase page smaller for iPhone 5s

### ISSUE THREAD

**Issue by James-Sangalli** [AlphaWallet/alpha-wallet-ios#2044]
Currently it will truncate the warning message

**Comment by vladyslav-iosdev** [comment]
@James-Sangalli  Seems like this issues fixed in some prev PR.
<img width="432" alt="Screenshot 2020-09-10 at 10 57 33" src="https://user-images.githubusercontent.com/55975226/92697893-768d5e00-f354-11ea-91cc-71bf5467f894.png">

**Comment by hboon** [comment]
Close since it's no longer an issue
