### ISSUE TITLE
Improve token icons loading (in Wallet tab)

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#2047]
We load the token icons from a few sources. One of them is the GitHub repository through http. We still want to check against it so that if the icons from that source changes or are added, the Wallet tab will show them. It's currently cached using the built-in caching mechanism for URLSession.

But token icon loading seems to be a little slow (also check what happens when offline). Can you verify and see if it needs to be improved and improve it if necessary (but hopefully without introducing our own image cache?)

**Comment by vladyslav-iosdev** [comment]
@hboon what you mean by this `from that source changes or are added`? its not clear. i checked offline mode, it worked for me. open app-> close it-> disable internet-> open app again-> Images are displaying.

**Comment by hboon** [comment]
Meaning of:

> "from that source changes or are added"

One of the sources is the GItHub repo. That repo might be updated, a token might change or a new one was added.

Launch the app and scroll through the wallet tab. If the icons appear rather quickly, then we might not need to change anything. I hope we don't have to change anything. It's quite simple now :)

**Comment by hboon** [comment]
@vladyslav-iosdev can close this if there isn’t anything obviously slow/wrong
