### ISSUE TITLE
Add in a check if keys for all wallets are not accessible on startup

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#2048]
Probably have to iterate this a few times. Ideally something like:

1. Launch (not resume) app
2. Check keys are accessible
3. Inform user and "probably" go to the create new wallet screen

This is a bit tricky because we want to make sure the keys are really not accessible anymore (due to migration to a new device).

Related to: #1849

**Comment by vladyslav-iosdev** [comment]
@James-Sangalli 
Correct me if i mistake, for this task i need to to check wallets private key/ seed phrase accessibility while application is launching, right?
     i need to check accessibility with prefix `Keys.ethereumSeedUserPresenceRequiredPrefix` or `Keys.ethereumSeedUserPresenceNotRequiredPrefix` too? and how to test this issue?

**Comment by hboon** [comment]
> how to test this issue?

@vladyslav-iosdev the best way (and most important) test for this is:

1. Launch app, create wallet(s)
2. Run iCloud backup
3. Wipe phone or with a new phone
4. Restore phone from iCloud
5. Run app

Expected
---
6. Show the app like it's a new install (or tell user they keys are not restored)

Observed
---
6. The app looks like it still has the wallets and keys, but it doesn't.

Unless you have a spare phone, I'll try to test this :)

**Comment by hboon** [comment]
I might have been wrong about how to solve this.

So the problem we want to solve is described in the test above ^

The list of wallets is stored in UserDefaults with the keys `Keys.ethereumAddressesWithPrivateKeys` and `Keys.ethereumAddressesWithSeed`. So the problem is this is synced to iCloud. What if we wrote this 2 values to a file in the documents directory and don't back up the file to iCloud? (sorry I might have sent you down the wrong path! Vlad)

@vladyslav-iosdev what do you think?

**Comment by vladyslav-iosdev** [comment]
> @vladyslav-iosdev what do you think?

so while backup to icloud user defaults also move there. ok, got it, i will check it and  try to resolve it.

**Comment by vladyslav-iosdev** [comment]
> Unless you have a spare phone, I'll try to test this :)

i got one, will try to reproduce it

**Comment by vladyslav-iosdev** [comment]
@hboon do we want to replace `UserDefaults` with storing data in file?

**Comment by hboon** [comment]
>@hboon do we want to replace `UserDefaults` with storing data in file?

@vladyslav-iosdev I’m thinking just for these 2-3 values (list of wallets). Let’s think about this a bit. This piece of data is critical because if it’s broken, the user loses access to their wallets.

**Comment by vladyslav-iosdev** [comment]
@hboon am i understand right, wallets can be accessible only on one device,  and can't be becked up to another one?

**Comment by hboon** [comment]
Yes. We don’t want them to be backed up

**Comment by hboon** [comment]
So the problem is caused by:

1. Keys are stored and not backed up (good)
2. The list of wallets is in UserDefaults and appears to be backed up and restored

I thought the solution was to check that (1) is not available (in a new device), but maybe the better and much easier solution is (2)?

**Comment by vladyslav-iosdev** [comment]
> So the problem is caused by:
> 
> 1. Keys are stored and not backed up (good)
> 2. The list of wallets is in UserDefaults and appears to be backed up and restored
> 
> I thought the solution was to check that (1) is not available (in a new device), but maybe the better and much easier solution is just to make (2) not happen?

ok, now its much clear

**Comment by hboon** [comment]
And maybe the better way to store the list of wallets (2), currently in UserDefaults, should just be to store it in the keychain and flagged as not to backup. Seems safer than as a file?

**Comment by vladyslav-iosdev** [comment]
> And maybe the better way to store the list of wallets (2), currently in UserDefaults, should just be to store it in the keychain and flagged as not to backup. Seems safer than as a file?

seems like it will work, so it this case seems like this one will not need, right? 
```
if !UIApplication.shared.isProtectedDataAvailable {
            throw EtherKeystoreError.protectionDisabled
        }
```

**Comment by hboon** [comment]
Why not? That mainly checks for whether the Realm database is protected

**Comment by vladyslav-iosdev** [comment]
> Why not? That mainly checks for whether the Realm database is protected

oh, ok, i got it
