### ISSUE TITLE
finance tab and a few hard-coded tokens to be in the tab

### ISSUE THREAD

**Issue by colourful-land** [AlphaWallet/alpha-wallet-ios#2055]
aETH goes to Deposits
aDAI goes to Loans

**Comment by hboon** [comment]
@colourful-land is it better to focus on `train-leaves` and not worry about master for now?

**Comment by vladyslav-iosdev** [comment]
> aETH goes to Deposits
> aDAI goes to Loans

@James-Sangalli how can i determine whether it aERITH or aDAI, and what do i need to do with the rest of finance tab tokens?

**Comment by vladyslav-iosdev** [comment]
can you provide contracts for them?

**Comment by tomekalphawallet** [comment]
https://etherscan.io/address/0x3a3a65aab0dd2a17e3f1947ba16138cd37d08c04

![Zrzut ekranu 2020-07-21 14 06 25](https://user-images.githubusercontent.com/51817359/88053094-8dd17b80-cb5b-11ea-96c3-d49783e74eda.png)

And for Aave DAi Debt - the contract does not exist yet. We will have to write it. Correct?

**Comment by hboon** [comment]
@vladyslav-iosdev if this adds "tabs" to the Wallet tab, remember to add support to make it scroll horizontally.

**Comment by vladyslav-iosdev** [comment]
@hboon am i undastand right, i need to add https://etherscan.io/address/0x3a3a65aab0dd2a17e3f1947ba16138cd37d08c04 to Finances Token enum and display it in appropriate section, right? what about the rest of  Finances tokens?

**Comment by hboon** [comment]
No idea.

@colourful-land ?

**Comment by vladyslav-iosdev** [comment]
> @vladyslav-iosdev if this adds "tabs" to the Wallet tab, remember to add support to make it scroll horizontally.

@hboon  i checked on iPhone 5s it fits to screen size

**Comment by tomekalphawallet** [comment]
> No idea.
> 
> @colourful-land ?

Ideally, we could have all these DeFi smart contracts added by default. Same way we drop AlphaWallet Welcome Pack.

**Comment by hboon** [comment]
I think what Vlad is asking is which contracts show up where. We have already added a Finance tab with a list of tokens.

I presume Vlad knows how is Deposit and Loan displayed — I thought it was going to be added to the list of "tabs" like All, Finance, etc. But Vlad says that the filter already fits without scrolling. So apparently I misunderstood, but as long as that's communicated to Vlad, that's ok.

But we should let Vlad know what is listed under "Deposits" and what is listed under "Loans". And is the list under Finance to be changed?

And yes, we should automatically add the contracts like mentioned in https://github.com/AlphaWallet/alpha-wallet-ios/issues/2056#issuecomment-662855383 so they appear automatically. (separate commit @vladyslav-iosdev?)

**Comment by vladyslav-iosdev** [comment]
> I presume Vlad knows how is Deposit and Loan displayed — I thought it was going to be added to the list of "tabs" like All, Finance, etc. But Vlad says that the filter already fits without scrolling. So apparently I misunderstood, but as long as that's communicated to Vlad, that's ok.

updated tab with allowing to scroll, on small devices.

**Comment by hboon** [comment]
> updated tab with allowing to scroll, on small devices.

Ah great. Thanks :)

**Comment by colourful-land** [comment]
> > No idea.
> > @colourful-land ?
> 
> Ideally, we could have all these DeFi smart contracts added by default. Same way we drop AlphaWallet Welcome Pack.

It's difficult to tell which token is DeFi smart contracts. First, we don't have token taxonomy or token classification - something @zhangzhongnan928 proposed years ago but we never had the priority to put that into TokenScript.

Second, using "contract" is not reliable for example all of the Debt Tokens (DAI Debt, ETH Debt and so on) uses the same contract because they are all managed in one line of credit in AAVE (you can observe that by looking at available credit, it is the same across all debt tokens and if one changes all changes). But that's probably the best we have presently, therefore @vladyslav-iosdev you should take a token to the Finance Tab if its **originating contract** is one of these hard-coded values:

Put into the LOANS section:

https://github.com/AlphaWallet/TokenScript-Examples/blob/3f3773a873deface13a5a8e0e0e7b79abc6227ef/examples/erc20/aETH/aETH.xml#L74
https://github.com/AlphaWallet/TokenScript-Examples/blob/3f3773a873deface13a5a8e0e0e7b79abc6227ef/examples/erc20/aETH/aETH.xml#L77
https://github.com/AlphaWallet/TokenScript-Examples/blob/3f3773a873deface13a5a8e0e0e7b79abc6227ef/examples/erc20/aETH/aETH.xml#L89

Put into the DEPOSITS section:
https://docs.aave.com/developers/deployed-contracts/deployed-contract-instances from aETH to aZRX.

**Comment by vladyslav-iosdev** [comment]
> Put into the LOANS section:
> 
> https://github.com/AlphaWallet/TokenScript-Examples/blob/3f3773a873deface13a5a8e0e0e7b79abc6227ef/examples/erc20/aETH/aETH.xml#L74
> https://github.com/AlphaWallet/TokenScript-Examples/blob/3f3773a873deface13a5a8e0e0e7b79abc6227ef/examples/erc20/aETH/aETH.xml#L77
> https://github.com/AlphaWallet/TokenScript-Examples/blob/3f3773a873deface13a5a8e0e0e7b79abc6227ef/examples/erc20/aETH/aETH.xml#L89
> 
> Put into the DEPOSITS section:
> https://docs.aave.com/developers/deployed-contracts/deployed-contract-instances from aETH to aZRX.

thx, now it's much clear.

**Comment by vladyslav-iosdev** [comment]
@James-Sangalli and the same for this #2055 PR
