### ISSUE TITLE
Lack confirmation message when a developer opened/imported a TSML file into αW

### ISSUE THREAD

**Issue by colourful-land** [AlphaWallet/alpha-wallet-ios#2079]
A developer has to go to advanced settings to see if the new file is recognised and in use - if the new file has the same name as one already in use there will be no clue if the import/open is successful.

currently:

1. open a tsml file (e.g. received from Telegram) with AlphaWallet
2. AlphaWallet launches innocently as αWallet but secretly takes the file in.

expected:

1. open a tsml file (e.g. received from Telegram) with AlphaWallet
2. AlphaWallet launches with a message like "xxx file imported with no error" or give some error.

@AW-STJ is following the process.

**Comment by vladyslav-iosdev** [comment]
> A developer has to go to advanced settings to see if the new file is recognised and in use

@James-Sangalli how could i determine what file currentry in use? i need to check if `AssetDefinitionStoreCoordinator.overrides` contains this file?

**Comment by hboon** [comment]
>> A developer has to go to advanced settings to see if the new file is recognised and in use ...

@vladyslav-iosdev probably look at how the console in settings displays files that override. Maybe ConsoleViewController.

**Comment by vladyslav-iosdev** [comment]
> @vladyslav-iosdev probably look at how the console in settings displays files that override. Maybe ConsoleViewController.

@hboon am i understand right, TSML its a token script file, that i can share with aw app and can get one from https://github.com/AlphaWallet/TokenScript-Examples, right?

**Comment by hboon** [comment]
>> @vladyslav-iosdev probably look at how the console in settings displays files that override. Maybe ConsoleViewController. ...

@vladyslav-iosdev yes. It’s these files that define what the action buttons do (the one that are alongside the send/receive buttons).
