### ISSUE TITLE
wallet doesn't allow the nonce of 0?

### ISSUE THREAD

**Issue by colourful-land** [AlphaWallet/alpha-wallet-ios#2083]
Feedback from a user:

> Question - I’m trying to specify a nonce of 0 to replace a pending tx of the same nonce (0 - first transfer from wallet). But Alpha Wallet is telling me the nonce must be a positive integer - it won’t let me specify 0.

I verified that this is a bug - 0 should be allowed. And 0 is a positive integer.

Can you try to reproduce this problem by:

1. Install a fresh AlphaWallet and generate a new address
2. Send some test-ether to the new address
3. Send it out
4. Speed up

See if you can capture the error in full and paste here.

> Your Ethereum address starts with a nonce of 0 and increases by 1 with each transaction that's confirmed.

I think this can be a hotfix release candidate. I don't know how to fix it but shouldn't be difficult to figure out (by any one including chintan)

**Comment by AW-STJ** [comment]
Moving to iOS repo as Android does not allow for nonce control in advanced settings
