### ISSUE TITLE
FIFA layout broke in Build 3.06 (350)

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/alpha-wallet-ios#2091]
Broken👇
![IMG_4144](https://user-images.githubusercontent.com/33795543/89265330-a66f8480-d677-11ea-867b-b4f29b875d25.PNG)

Should be 👇
![photo_2020-08-04 17 26 24](https://user-images.githubusercontent.com/33795543/89265354-b12a1980-d677-11ea-8070-a7c14dad2650.jpeg)

**Comment by hboon** [comment]
@James-Sangalli would you help to check? I noticed it while preparing the demo, so not sure if it's related (and since then I've ported some of the code into master) — but forgot to check again or file an issue.

**Comment by James-Sangalli** [comment]
caused by this.props._count being undefined but this is for the demo build not master (master is working)

**Comment by hboon** [comment]
@James-Sangalli might be present in the Activity branch

**Comment by zhangzhongnan928** [comment]
> @James-Sangalli might be present in the Activity branch
YES
This is in build 3.07(354)
![IMG_FEB1FFB349C0-1](https://user-images.githubusercontent.com/33795543/93280043-0f682180-f80c-11ea-9909-b03de0c3f995.jpeg)

**Comment by hboon** [comment]
@James-Sangalli would you be able to help take a look?

**Comment by James-Sangalli** [comment]
https://github.com/AlphaWallet/TokenScript-Examples/commit/302f522b230f4be24fa84416e5beb953f8a8bbd7

solved from here, waiting the ability to sync with the server but tested it working from my side with airdrop
