### ISSUE TITLE
Can not submit TX due to high gas price

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/alpha-wallet-ios#2099]
![image](https://user-images.githubusercontent.com/33795543/90216363-a3c41a80-de41-11ea-8f24-d1fd990e5e0e.png)

**Comment by zhangzhongnan928** [comment]
may need to increase more, the current average gas price is 500

**Comment by hboon** [comment]
500 is supported to be a Geth limit, if we set the default as > 500, have to check if it works.

**Comment by hboon** [comment]
Bump. @James-Sangalli

**Comment by James-Sangalli** [comment]
Raised the max fee to 0.2 ETH, there is a node limit of 500 gwei. Will keep it as set from the latest PR with 0.2 ETH max fee

**Comment by zhangzhongnan928** [comment]
> Raised the max fee to 0.2 ETH, there is a node limit of 500 gwei. Will keep it as set from the latest PR with 0.2 ETH max fee

this stupid limit just cost me at least 30 eth.....................................................................
can we please remove it. @hboon @James-Sangalli
