### ISSUE TITLE
Add custom linking to Uniswap to tokens

### ISSUE THREAD

**Issue by tomekalphawallet** [AlphaWallet/alpha-wallet-ios#2103]
So for all major ER20 tokens + Ether we are adding custom links, that will allow users to access Uniswap quickly. Remember that with custom linking you can have already preselected coin. So when you are starting with USDC, it should be already preselected in Uniswap. 

https://uniswap.org/docs/v1/frontend-integration/custom-linking/

Ethereum:
https://app.uniswap.org/#/swap?use=v1&create-exchange?tokenAddress=0x0F5D2fB29fb7d3CFeE444a200298f468908cC942

Zeplin:
https://app.zeplin.io/project/5d0356be2f25b319dcc5944b/dashboard?seid=5f3688a5c970497d6ded8a92
![Zrzut ekranu 2020-08-14 o 14 51 57](https://user-images.githubusercontent.com/51817359/90251264-b89eaf00-de3d-11ea-8bc5-5aafb7a78fc9.png)

**Comment by vladyslav-iosdev** [comment]
@hboon can u please provide more details for this task?

**Comment by hboon** [comment]
@vladyslav-iosdev I have no idea too :)

@tomekalphawallet more context?

**Comment by tomekalphawallet** [comment]
Explainer video
https://www.dropbox.com/s/wz9nbvcqbcturyy/uniswap-linking-explained.mp4?dl=0
@vladyslav-iosdev

**Comment by hboon** [comment]
So to sum it up:

Add a TokenScript action for a subset of ERC20 tokens, when launched, it opens Uniswap with the current token.

Longer:

* Add a TokenScript action for a subset of ERC20 tokens. This action is called "Exchange with Uniswap".
* When the action is launched, pop the navigation stack and switch to the browser tab, loading the URL as described by https://uniswap.org/docs/v1/frontend-integration/custom-linking/ with the token as the `inputCurrency`.
* The list of tokens is at https://github.com/AlphaWallet/alpha-wallet-android/issues/1564#issuecomment-677485732 [1]
* Probably look at `TokenInstanceAction.ActionType.erc20Send` to see how it's added

[1] Vlad: I asked about the list here, so maybe put just a token or two for now until we are sure: https://github.com/AlphaWallet/alpha-wallet-android/issues/1564#issuecomment-677509536

**Comment by vladyslav-iosdev** [comment]
> So to sum it up:
> 
> Add a TokenScript action for a subset of ERC20 tokens, when launched, it opens Uniswap with the current token.
> 
> Longer:
> 
> * Add a TokenScript action for a subset of ERC20 tokens. This action is called "Exchange with Uniswap".
> * When the action is launched, pop the navigation stack and switch to the browser tab, loading the URL as described by https://uniswap.org/docs/v1/frontend-integration/custom-linking/ with the token as the `inputCurrency`.
> * The list of tokens is at [AlphaWallet/alpha-wallet-android#1564 (comment)](https://github.com/AlphaWallet/alpha-wallet-android/issues/1564#issuecomment-677485732) [1]
> * Probably look at `TokenInstanceAction.ActionType.erc20Send` to see how it's added
> 
> [1] Vlad: I asked about the list here, so maybe put just a token or two for now until we are sure: [AlphaWallet/alpha-wallet-android#1564 (comment)](https://github.com/AlphaWallet/alpha-wallet-android/issues/1564#issuecomment-677509536)

ok, thx, now its clear.

**Comment by hboon** [comment]
@vladyslav-iosdev I volunteered you to figure out the list of tokens :)

Would you help to post back to https://github.com/AlphaWallet/alpha-wallet-android/issues/1564#issuecomment-677603725 when you have it?

**Comment by vladyslav-iosdev** [comment]
> Explainer video
> https://www.dropbox.com/s/wz9nbvcqbcturyy/uniswap-linking-explained.mp4?dl=0
> @vladyslav-iosdev

sorry i distracted to another task, and totally missed this one. Thx a lot for explanation.
