### ISSUE TITLE
Improve search results and add Top 20 Most Popular tokens

### ISSUE THREAD

**Issue by colourfreak** [AlphaWallet/alpha-wallet-ios#2112]
**Problem:**
During user tests, I discover that users have problems understanding how the wallet works. They think if something is not listed in the wallet tab - it is not available. And even if they try to look for a specific coin in the Add/Hide Tokens - if they can't search or find tokens they want to transfer to the wallet - they assume these tokens are not available for this wallet.

One user thought that a coin is not available because it was not listed in the wallet tab. So there was a wrong assumption that if something was not visible, it must be unavailable.

**Solution:**
1. Below "Hidden Tokens" add another section called "Popular Tokens" where we list the top 20 most popular erc20 tokens. 
https://zpl.io/2j0gqPA
2. The Search box in Add/Hide Tokens should display (as a result of searching) even those tokens that are out of the wallet, but still, ERC20.
https://zpl.io/bAMM9YP
3. Add Search bar (working the same way as 2) to the Add Custom Token screen.
https://zpl.io/VQwwLgA

Not related but can be updated along with this change:
4. Update the Plus icon symbol to https://zpl.io/aXxvAAK
5. Remove Plus icon symbol from the wallet (leave just a text "Add/Hide Tokens"
https://zpl.io/aRdOwWK

![Add_Hide_Tokens](https://user-images.githubusercontent.com/51817359/90646397-73acbb00-e237-11ea-9193-18e5247f9997.jpg)

**Comment by AW-STJ** [comment]
Hey @hboon: How much time do you think this work will cost us?

Not a priority at the moment, as I am considering the feasibility of testing a beta version of the flow on Android before confirming the final flows and then implementing on iOS. 

This is to help iOS to focus on Bartercard and Activity implementations for now.

**Comment by hboon** [comment]
@AW-STJ Can we scope it down and just do:

> 2. The Search box in Add/Hide Tokens should display (as a result of searching) even those tokens that are out of the wallet, but still, ERC20.  https://zpl.io/bAMM9YP

Excluding (1) and (3) means less work to go live, but I also thought that it wouldn't work as well. It's going to be a long list, users wouldn't see it anyway. But we can start with (2) and if works, think a bit more about this?

> 1. Below "Hidden Tokens" add another section called "Popular Tokens" where we list the top 20 most popular erc20 tokens.  https://zpl.io/2j0gqPA
> 3. Add Search bar (working the same way as 2) to the Add Custom Token screen.  https://zpl.io/VQwwLgA 

Process-related, this is a good hint that it shouldn't be written into the same issue: "Not related but can be updated along with this change":

> 3. Update the Plus icon symbol to https://zpl.io/aXxvAAK
> 4. Remove Plus icon symbol from the wallet (leave just a text "Add/Hide Tokens"
> https://zpl.io/aRdOwWK

**Comment by hboon** [comment]
@AW-STJ we can let Vlad have a go at it. Just keep BC at higher priority and he can sort it out.

**Comment by hboon** [comment]
Unassigned Vlad for now. Re-assign once it's decided.

**Comment by hboon** [comment]
Close from inactivity

**Comment by AW-STJ** [comment]
Reopening the issue as this was pointed out by a user, where the user expected to see the list of popular tokens.

Not a priority item, but opening the issue for tracking.

**Comment by AW-STJ** [comment]
Closing the issue and creating a new one https://github.com/AlphaWallet/alpha-wallet-ios/issues/2845
