### ISSUE TITLE
Make Add/Hide Tokens easier to tap

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#2113]
Can we make the hit test area bigger or just make it a table view cell and use `tableView(_:didSelectowAt:)`?

**Comment by vladyslav-iosdev** [comment]
@hboon https://github.com/AlphaWallet/alpha-wallet-ios/issues/2110 should close this issue. if i understand task correctly.

**Comment by hboon** [comment]
@vladyslav-iosdev it's hard to tap on it, probably because the label is quite short?

**Comment by vladyslav-iosdev** [comment]
ok, i will check it one more time

**Comment by tomekalphawallet** [comment]
![Uploading 2020-09-10 09.22.32.png…]()
