### ISSUE TITLE
iPhone 5s, ButtonsBar, adjust button width

### ISSUE THREAD

**Issue by vladyslav-iosdev** [AlphaWallet/alpha-wallet-ios#2118]
<img width="432" alt="Screenshot 2020-08-28 at 09 21 49" src="https://user-images.githubusercontent.com/55975226/91528217-eee52f80-e90f-11ea-8c9c-a7b77ba9202b.png">

**Comment by hboon** [comment]
Maybe make the font smaller too on smaller devices if it isn't already.

**Comment by vladyslav-iosdev** [comment]
> Maybe make the font smaller too on smaller devices if it isn't already.

yep, i am currently working on it
