### ISSUE TITLE
Implement EIP712 phase 1

### ISSUE THREAD

**Issue by JamesSmartCell** [AlphaWallet/alpha-wallet-ios#2120]
Implement legacy EIP712 which luckily is very simple (compared to current spec EIP712).

First you need to fix the bug in the AlphaWallet JS init code:

```
  signTypedMessage: function (msgParams, cb) {
    console.log('signTypedMessage ', msgParams)
    const { data } = msgParams
    const { id = 8888 } = msgParams
    AlphaWallet.addCallback(id, cb)
    alpha.signTypedMessage(id, JSON.stringify(msgParams))  //use msgParams directly
  },
```

Here's a sample EIP712 legacy data bundle:

```
    {
      type: 'string',
      name: 'Message',
      value: 'Hi, Alice!'
    },
    {
      type: 'uint32',
      name: 'A number',
      value: '1337'
    }
```

This can go into a struct for easy instantiation from JSON:
```
public class ProviderTypedData
{
    public String name;
    public String type;
    public Object value;
}
```

The EIP712 bytes you need for the signing algorithm is formed like this:

Part 1, type hash:
```keccak256('string Messageuint32 A number')``` (note that you're hashing the ASCII bytes here).

Here's the working Java code from Android for reference:

```
Hash.keccak256(encodeParams(rawData)));
```
```
    public static byte[] encodeParams(ProviderTypedData[] rawData)
    {
        //form the params for hashing
        StringBuilder sb = new StringBuilder();
        for (ProviderTypedData item : rawData)
        {
            sb.append(item.type).append(" ").append(item.name); //space between type and name
        }

        return sb.toString().getBytes();
    }
```

Part 2, message params hash. I simply ported the reference JavaScript version from dicether [here](https://dicether.github.io/js-eth-personal-sign-examples/bundle.js):
```
ABI.solidityPack = function (types, values) {
  if (types.length !== values.length) {
    throw new Error('Number of types are not matching the values')
  }

  var size, num
  var ret = []

  for (var i = 0; i < types.length; i++) {
    var type = elementaryName(types[i])
    var value = values[i]

    if (type === 'bytes') {
      ret.push(value)
    } else if (type === 'string') {
      ret.push(new Buffer(value, 'utf8'))
    } else if (type === 'bool') {
      ret.push(new Buffer(value ? '01' : '00', 'hex'))
    } else if (type === 'address') {
      ret.push(utils.setLengthLeft(value, 20))
    } else if (type.startsWith('bytes')) {
      size = parseTypeN(type)
      if (size < 1 || size > 32) {
        throw new Error('Invalid bytes<N> width: ' + size)
      }
      ret.push(utils.setLengthRight(value, size))
    } else if (type.startsWith('uint')) {
      size = parseTypeN(type)
      if ((size % 8) || (size < 8) || (size > 256)) {
        throw new Error('Invalid uint<N> width: ' + size)
      }
      num = parseNumber(value)
      if (num.bitLength() > size) {
        throw new Error('Supplied uint exceeds width: ' + size + ' vs ' + num.bitLength())
      }
      ret.push(num.toArrayLike(Buffer, 'be', size / 8))
    } else if (type.startsWith('int')) {
      size = parseTypeN(type)
      if ((size % 8) || (size < 8) || (size > 256)) {
        throw new Error('Invalid int<N> width: ' + size)
      }

      num = parseNumber(value)
      if (num.bitLength() > size) {
        throw new Error('Supplied int exceeds width: ' + size + ' vs ' + num.bitLength())
      }
      ret.push(num.toTwos(size).toArrayLike(Buffer, 'be', size / 8))
    } else {
      // FIXME: support all other types
      throw new Error('Unsupported or invalid type: ' + type)
    }
  }
  return Buffer.concat(ret)
}

// Parse N from type<N>
function parseTypeN (type) {
  return parseInt(/^\D+(\d+)$/.exec(type)[1], 10)
}
```

Obtain the second hash like this:
```
Hash.keccak256(encodeValues(rawData));
```
Where you can find the type and value from the ProviderTypedData array.

Now you have both elements you simply write the hash bytes sequentially, to form a 512 bit byte array. This is what you submit to your standard signing routine (or you can keccak256 them to 256 bits, then submit directly for signing if you don't always hash first).

Check on this website:

https://dicether.github.io/js-eth-personal-sign-examples/

I will write up the current EIP712 system in a new issue, as it's substantially more complex.

**Comment by JamesSmartCell** [comment]
Let me know when you're ready for full EIP712. This should be done ASAP as it will only take one important website to start using this then we are incompatible.

**Comment by hboon** [comment]
@vladyslav-iosdev would you help tackle this? :)

**Comment by vladyslav-iosdev** [comment]
@hboon #1959 allows to handle EIP712 json value

**Comment by vladyslav-iosdev** [comment]
@hboon how can i simulate action when in
`static func fromMessage(_ message: WKScriptMessage) -> DappCommand? {`
we receive `EIP712` json value ?

**Comment by hboon** [comment]
@vladyslav-iosdev I took a quick look. It’ll also be good to check if this is already supported in the code base already

**Comment by vladyslav-iosdev** [comment]
@James-Sangalli  please check latest changes, now it should work

**Comment by hboon** [comment]
Already includes EIP712 pre-v3 (which is this) in the code base.
