### ISSUE TITLE
Use Ethereum price oracle

### ISSUE THREAD

**Issue by JamesSmartCell** [AlphaWallet/alpha-wallet-ios#2126]
You can now use the Ethereum price oracle as detailed here:

# TickerContract
Server which updates a Rinkeby contract with the current chain price pairs

Runs on a remote server, updated every 5 minutes. 

Contract is at this address:

```0xf155a7eb4a2993c8cf08a76bca137ee9ac0a01d8```

Call 'getTickers()' Contract function at the above address, you will receive a uint256 array like this:
```
uint256[]: 1599182340,53919818046743065361484948727580919394523294113429944452015598514808,6646408691905980077939464562387862530341091577344504793193992017206892217,2695994540551596199929804836366431450312827145012815169827758052047688,2695994676086776870399015889108796676212760401494873926696187688785178,1536716852475725334180631652397702971157160858587054445996920862028748,1671516587355645560059090195736405322634432519060936747725063028484174
```

How to consume:

- The first entry is the UTC system time from Ethereum's 'now' System param. This is a failsafe to detect if the oracle is stale for whatever reason. Written every time the contract receives an update.
- Following this is the ticker list, each uint256 is a bytes32 data chunk:

 ```
 4 bytes ChainId
 4 bytes 3 decimal adjusted 24Hr change (Two's Compliment format)
 24 bytes 12 decimal adjusted price
 ```
 
 In Java you could consume each value as follows:
 
 ```
            byte[] tickerData = Numeric.toBytesPadded(tickerInfo, 32);            //ensure bytes data is correctly aligned
            ByteArrayInputStream buffer = new ByteArrayInputStream(tickerData);
            EthereumReadBuffer ds = new EthereumReadBuffer(buffer);

            BigInteger chainId = ds.readBI(4);  
            int changeVal = ds.readInt();
            BigInteger correctedPrice = ds.readBI(24);
            ds.close();

            BigDecimal changeValue = new BigDecimal(changeVal).movePointLeft(3);       //Adjust 24 Hr change by decimals 3
            BigDecimal priceValue = new BigDecimal(correctedPrice).movePointLeft(12);  //Adjust retrieved price by decimals 12
 ```
 
 Where readBI is a helper method:
 ```
    public BigInteger readBI(int sz) throws IOException
    {
        byte[] buffer = new byte[sz];

        read(buffer);
        return new BigInteger(buffer);
    }
 ```

Why? Because it avoid scaling issues with hitting API call limits. Could be useful for the future, to avoid the issues we had when the wallet scaled past our previous API limits.

**Comment by James-Sangalli** [comment]
> You can now use the Ethereum price oracle as detailed here:
> 
> # TickerContract
> Server which updates a Rinkeby contract with the current chain price pairs
> 
> Runs on a remote server, updated every 5 minutes.
> 
> Contract is at this address:
> 
> `0xf155a7eb4a2993c8cf08a76bca137ee9ac0a01d8`
> 
> Call 'getTickers()' Contract function at the above address, you will receive a uint256 array like this:
> 
> ```
> uint256[]: 1599182340,53919818046743065361484948727580919394523294113429944452015598514808,6646408691905980077939464562387862530341091577344504793193992017206892217,2695994540551596199929804836366431450312827145012815169827758052047688,2695994676086776870399015889108796676212760401494873926696187688785178,1536716852475725334180631652397702971157160858587054445996920862028748,1671516587355645560059090195736405322634432519060936747725063028484174
> ```
> 
> How to consume:
> 
> * The first entry is the UTC system time from Ethereum's 'now' System param. This is a failsafe to detect if the oracle is stale for whatever reason. Written every time the contract receives an update.
> * Following this is the ticker list, each uint256 is a bytes32 data chunk:
> 
> ```
> 4 bytes ChainId
> 4 bytes 3 decimal adjusted 24Hr change (Two's Compliment format)
> 24 bytes 12 decimal adjusted price
> ```
> 
> In Java you could consume each value as follows:
> 
> ```
>            byte[] tickerData = Numeric.toBytesPadded(tickerInfo, 32);            //ensure bytes data is correctly aligned
>            ByteArrayInputStream buffer = new ByteArrayInputStream(tickerData);
>            EthereumReadBuffer ds = new EthereumReadBuffer(buffer);
> 
>            BigInteger chainId = ds.readBI(4);  
>            int changeVal = ds.readInt();
>            BigInteger correctedPrice = ds.readBI(24);
>            ds.close();
> 
>            BigDecimal changeValue = new BigDecimal(changeVal).movePointLeft(3);       //Adjust 24 Hr change by decimals 3
>            BigDecimal priceValue = new BigDecimal(correctedPrice).movePointLeft(12);  //Adjust retrieved price by decimals 12
> ```
> 
> Where readBI is a helper method:
> 
> ```
>    public BigInteger readBI(int sz) throws IOException
>    {
>        byte[] buffer = new byte[sz];
> 
>        read(buffer);
>        return new BigInteger(buffer);
>    }
> ```
> 
> Why? Because it avoid scaling issues with hitting API call limits. Could be useful for the future, to avoid the issues we had when the wallet scaled past our previous API limits.

@JamesSmartCell is this a price pair for ETH:USD? If so, it is unnecessary to create our own because MakerDAO has an oracle for this already with ETH:DAI... https://etherscan.io/address/0x729D19f657BD0614b4985Cf1D82531c67569197B#readContract

Better to let them do the upkeep then ourselves :)

**Comment by JamesSmartCell** [comment]
@James-Sangalli This oracle contains ETH-USD but also has the following price pairs in a single call:

ETH->USD
ETC->USD
POA->USD
XDAI->USD
BNB->USD (Binance Chain)
ARTIS->USD

The MakerDao call only gives a single price pair, therefore it's not very useful to us.

I don't believe there's a single oracle that can give us all these price pairs in a single call without consuming API restrictions. Or even with multiple calls.

**Comment by JamesSmartCell** [comment]
Which price oracle do you use in iOS? Do you know what the API frequency restriction is? We hit it regularly in Android; the algorithm I use now is:

. read from our price oracle.
. check if the write date is within 10 mintes of now.
. if it is, use these, if not then fall back to the old combo of BlockScout + Amberdata + CoinmarketCap + EUR->USD/Artis.

**Comment by hboon** [comment]
Closing for now. Will implement when it's an issue.
