### ISSUE TITLE
Incorrect Balance for some iOS users for some tokens

### ISSUE THREAD

**Issue by AW-STJ** [AlphaWallet/alpha-wallet-ios#2130]
A user reported the issue where the STAKE balance was shown in Trillions, rather than the actual balance which was 2.6624:

![image](https://user-images.githubusercontent.com/61957841/92427865-f8547e80-f1d0-11ea-9474-a8e7265f10d9.png)

![image](https://user-images.githubusercontent.com/61957841/92427889-03a7aa00-f1d1-11ea-8e28-c2207fa25f7f.png)
 
Please let me know if you need any further information.

**Comment by hboon** [comment]
Contract: 0x0Ae055097C6d159879521C384F1D2123D1f195e6

**Comment by hboon** [comment]
Still a bug since it happened. Decimals (18) seems to be picked up correct since transactions are displayed properly. Also verified that decimals = 18 when I watch the wallet and look at the token in Realm.

**Comment by hboon** [comment]
@James-Sangalli still a problem?

**Comment by hboon** [comment]
Close from inactivity. Re-open if reproducible
