### ISSUE TITLE
Should limit the highest gas limit as the current block gas limit instead of limit the highest gas fee.

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/alpha-wallet-ios#2131]
![image](https://user-images.githubusercontent.com/33795543/92477893-b523fb00-f224-11ea-9574-724fe5dc0538.png)
![IMG_D69FD390A876-1](https://user-images.githubusercontent.com/33795543/92546175-48951480-f295-11ea-9667-c0b5b1b5c05a.jpeg)

- [ ] Set the max gas limit as 12,500,000
- [ ] Remove the limit of the highest gas fee

**Comment by hboon** [comment]
@James-Sangalli bump

**Comment by hboon** [comment]
Seems not necessary after #2297? Re-open and clarify if it's still needed
