### ISSUE TITLE
Hangs at launch screen for 1 hour without crashing

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#2137]
v3.06 from App store

From Tomek.

**Comment by hboon** [comment]
It didn't crash, so I wonder if there's a certain condition where the lock screen isn't hidden correctly?

**Comment by hboon** [comment]
Bump

**Comment by vladyslav-iosdev** [comment]
@hboon i tried to reproduce this issue several times, it worked ok, for me.

**Comment by hboon** [comment]
Leave it first then. I have seen it hang at the launch screen a few times, but rarely. Will have to check when it happens

**Comment by zhangzhongnan928** [comment]
![IMG_1719](https://user-images.githubusercontent.com/33795543/104973925-66943200-5a4a-11eb-9b1a-a9ff915bd5d0.PNG)

My experience is as below
1. I have experienced the frozen starting screen many many times. (in the past week, at least 10 times)
2. Sometimes I can solve it by install between TestFlight and Public build. (This saves me from wallets recovery)
3. Sometimes I have to delete the app and reinstall it. (Then have I have to recover my wallets and manually build my browser bookmark again)
4. It happens with all the versions.

**Comment by zhangzhongnan928** [comment]
it happens to me again. and this time no luck, it cannot be solved by install between TestFlight and Public build.
I have to delete the app reinstall and recovery my wallets.

**Comment by hboon** [comment]
Closed with 1 possible reason. Re-open if it happens again. There might be other reasons.
