### ISSUE TITLE
White space in wallet tab when reopening the app 

### ISSUE THREAD

**Issue by James-Sangalli** [AlphaWallet/alpha-wallet-ios#2151]
To reproduce, open the app and then close it. Open it again and it will appear like this. 

![photo_2020-09-17_19-47-32](https://user-images.githubusercontent.com/16630514/93454685-a6bd9980-f91e-11ea-8199-533c46f8fd0a.jpg)

**Comment by hboon** [comment]
@James-Sangalli I can't reproduce this. Can you specify the build/commit, device and iOS version?

Are these the steps to reproduce?

1. Tap on app to launch
2. Swipe to go to homescreen
3. Tap on app to resume

**Comment by James-Sangalli** [comment]
Disappeared in latest TestFlight build...
