### ISSUE TITLE
Update empty state image for Activity tab

### ISSUE THREAD

**Issue by colourfreak** [AlphaWallet/alpha-wallet-ios#2157]
Zeplin:
https://app.zeplin.io/project/5d0356be2f25b319dcc5944b/screen/5f6dbc43a7969f8574a7f7b9/

<img width="924" alt="Screenshot 2020-09-25 at 11 51 13" src="https://user-images.githubusercontent.com/51817359/94253310-6add9200-ff25-11ea-893f-b8dba2613745.png">

**Comment by hboon** [comment]
Closed with #2560
