### ISSUE TITLE
can't cancel out of "Scan QR code" screen 

### ISSUE THREAD

**Issue by James-Sangalli** [AlphaWallet/alpha-wallet-ios#2164]

**Comment by hboon** [comment]
@James-Sangalli How do you access the Scan QR code screen? I tried a few ways, from Wallet tab or send screen and it worked for me

**Comment by hboon** [comment]
Looks like it's:

1. Tap Add / Hide Tokens
2. +
3. Scan QR code
4. Scanner doesn't close, Cancel button doesn't work

**Comment by vladyslav-iosdev** [comment]
@hboon what qr code do u trying to scan, can u share it?

**Comment by hboon** [comment]
Any contract address will do. But don't worry about it. I'm halfway through fixing this :)

**Comment by hboon** [comment]
@vladyslav-iosdev but should be to stop and dismiss the scanner somewhere here https://github.com/AlphaWallet/alpha-wallet-ios/blob/0122226a580c2177add28df9b526a5c434528e0f/AlphaWallet/Tokens/Coordinators/NewTokenCoordinator.swift#L215

I'm checking if other places which use the scanner needs to be fixed the same way.
