### ISSUE TITLE
Using the universal QR scanner to add Custom Token, the wallet doesn't load the token information

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/alpha-wallet-ios#2171]
1. Using the universal QR scanner to add Custom Token, the wallet doesn't load the token information
2. after the above process, the scanner in ADD/Hide token stop working, don't pick up QR Code

**Comment by hboon** [comment]
> 2. after the above process, the scanner in ADD/Hide token stop working, don't pick up QR Code

Sounds like same problem as #2164
