### ISSUE TITLE
xDAI to DAI Bridge: Transaction not in pending activity until confirmed

### ISSUE THREAD

**Issue by AW-STJ** [AlphaWallet/alpha-wallet-ios#2188]
The xDAI bridge transaction works for me. But gave me a confusing experience because of the below issues:
1. 'Transaction is successful', but give not transaction details.
2. The transaction also does not show up in the 'Activity' tab, until it is confirmed.  
3. Even after showing 'Transaction is successful' dialogue box, the prompt to convert DAI to xDAI persists in the background urging user to click it again.

**Comment by hboon** [comment]
Issue with pending transactions displayed as successful immediately might be solved by #2184. It fixes it for transfers, at least. @AW-STJ  Would you test it again when we have a build?

**Comment by hboon** [comment]
@AW-STJ is this still reproducible?

**Comment by hboon** [comment]
Closed from inactivity
