### ISSUE TITLE
Improve activity - order of transactions 

### ISSUE THREAD

**Issue by AW-STJ** [AlphaWallet/alpha-wallet-ios#2192]
Maybe these will be addressed as part of activity work, however, wanted to point this out.

As I was doing more investigation for a transaction related issue reported by Android user, I found out that the transactions were not captured accurately. 
https://github.com/AlphaWallet/alpha-wallet-android/issues/1628

The most accurate transactions were captured by Zerion.
![image](https://user-images.githubusercontent.com/61957841/95153172-8b85d180-07da-11eb-871a-4020da8c8514.png)

Also check out the order of xDAI transactions that I executed to test #2188

Please investigate why the order of the successful DAI transaction is different to others wallets. Let me know if we need more details.

Also it is not very evident that the transactions have been failed.

@colourfreak - can you review how Android displays failed transactions and confirm the designs so that we can align both Android and iOS to display failed transactions similarly.

**Comment by hboon** [comment]
@AW-STJ can you paste the wallet address some where to check against?

**Comment by AW-STJ** [comment]
There you go Boon, wallet address 0xfCABe3451aC8EDfB8FB6b9274C2E095D9cCC8082

**Comment by colourfreak** [comment]
There is another on with Contact Execution. Zerion does the work.

<img width="1411" alt="Screenshot 2020-10-07 at 09 07 24" src="https://user-images.githubusercontent.com/51817359/95298585-95f8a780-087c-11eb-9bbf-8f5aa5c4f173.png">

**Hash**
https://etherscan.io/tx/0x98f65e2e737b69a42786a9abe2bba4a376a5390c9aca641900c991ca70f12f68

**Application**
0x4976fb03c32e5b8cfe2b6ccb31c09ba78ebaba41
![2020-10-07 08 51 10](https://user-images.githubusercontent.com/51817359/95298654-b6c0fd00-087c-11eb-9a68-158fa5c3777f.png)

**Comment by hboon** [comment]
Fixed the error (including sort order) in #2192, but created an issue for display in https://github.com/AlphaWallet/TokenScript/issues/393
