### ISSUE TITLE
AWS Lambda expect Bitcoin-style signature but was given Vitalik-style signature

### ISSUE THREAD

**Issue by colourful-land** [AlphaWallet/alpha-wallet-ios#2198]
AWS Lambda accepts DER encoded signature like the one used in Bitcoin.

Here is the code @vladyslav-iosdev used to create a signature:

````
public func sign(hash: Data, privateKey: Data) throws -> Data {
        precondition(hash.count == 32, "Expect hash size to be 32")
        precondition(privateKey.count == 32, "Expect private key size to be 32")

        var signature = secp256k1_ecdsa_recoverable_signature()
        try privateKey.withUnsafeBytes { (key: UnsafePointer<UInt8>) in
            if secp256k1_ec_seckey_verify(context, key) != 1 {
                throw Secp256k1Error.invalidPrivateKey
            }
            let result = hash.withUnsafeBytes { hash in
                secp256k1_ecdsa_sign_recoverable(context, &signature, hash, key, nil, nil)
            }
            if result == 0 {
                throw Secp256k1Error.invalidPrivateKey
            }
        }

        var output = Data(count: 65)
        var recid = 0 as Int32
        _ = output.withUnsafeMutableBytes { (output: UnsafeMutablePointer<UInt8>) in
            secp256k1_ecdsa_recoverable_signature_serialize_compact(context, output, &recid, &signature)
        }

        // add back recid to get 65 bytes sig
        output[64] = UInt8(recid)

        return output
    }
````

Which apparently uses Vitalik style Ethereum signature. Vitalik could have the courtesy to extend the DER siganture format to do what he want, given DER was originally intended to be extensible and was extended all the time by different crypto standards, and if done right can result in a signature that is compatible with older (e.g. Bitcoin) codebase even without recompiling! But no, Vitalik likes to do things his way.

There is a bit of hope that @vladyslav-iosdev said the code might actually call
https://github.com/bitcoin-core/secp256k1/blob/master/include/secp256k1.h

Which is a Bitcoin codebase - hence it must be able to store Bitcoin signature. (for one way to tell, a Bitcoin-style, i.e. Standard Comaptible, a signature is about 71 bytes, can be shorter occassionally, and has a variable length - which begets the question to Vitalik - 𝑎𝑟𝑒 𝑦𝑜𝑢 𝑠𝑢𝑟𝑒 that you want people to rewrite all libraries when you decided to extend the keysize when 256-bit is no longer enough? Or will you consider extensible standard, which was created after the pain of extending key size back in the 80s in the first place?)

How can we get a Bitcoin-style Signature? I can change the Lambda to be compatible with Vitalik-style but that requires some research work into how that works.

Alternatively, consider letting the mobile passing the Signature as (𝑥,𝑦) where each is BigInteger of 256-bits long, and I should be able to reconstruct needed signature in bytes at the server end.

**Comment by hboon** [comment]
@vladyslav-iosdev I’ll look into this but if you have time before me, can you try look into the pod which contains HDWallet? Since it has multi-coin support, we might be able to use it or copy the code from there. The latter may be because the interface only supports seeds and not private keys directly.

**Comment by vladyslav-iosdev** [comment]
i found solution for this
```
public func sign(_ data: Data, privateKey: Data) throws -> Data {
        let signature = UnsafeMutablePointer<secp256k1_ecdsa_signature>.allocate(capacity: 1)
        defer {
            signature.deallocate(capacity: 1)
        }

        let status = data.withUnsafeBytes { (ptr: UnsafePointer<UInt8>) in
            try? privateKey.withUnsafeBytes { (key: UnsafePointer<UInt8>) in
                secp256k1_ecdsa_sign(context, signature, ptr, key, nil, nil)
            }
        }

        guard status == 1 else {
            throw CryptoError.signFailed
        }

        let normalizedsig = UnsafeMutablePointer<secp256k1_ecdsa_signature>.allocate(capacity: 1)
        defer {
            normalizedsig.deallocate(capacity: 1)
        }

        secp256k1_ecdsa_signature_normalize(context, normalizedsig, signature)
        var length: size_t = 128
        var der = Data(count: length)

        guard der.withUnsafeMutableBytes({ return secp256k1_ecdsa_signature_serialize_der(context, $0, &length, normalizedsig) }) == 1 else {
            throw CryptoError.noEnoughSpace
        }
        der.count = length

        return der
    }
```
