### ISSUE TITLE
Test and diagnose : ETC DEX's not recognising AlphaWallet

### ISSUE THREAD

**Issue by AW-STJ** [AlphaWallet/alpha-wallet-ios#2202]
The issue is raised by our friend Dan from Universal Coin. AlphaWallet is not recognised by distributed exchanges or Dapps.

The glitch had been reported earlier and had rectified itself after a few days, before our team got to the issue. Need to check the ETC endpoint/nodes used.

**Comment by hboon** [comment]
@AW-STJ any luck reproducing this?

**Comment by James-Sangalli** [comment]
@AW-STJ make sure the user selects "classic" for the network in the browser, that can be a gotcha

**Comment by hboon** [comment]
@AW-STJ is this still an issue?

**Comment by AW-STJ** [comment]
No a problem now. Works as expected
