### ISSUE TITLE
Xcode 12 web3swift pod build errors

### ISSUE THREAD

**Issue by EVanzhula** [AlphaWallet/alpha-wallet-ios#2203]
Prerequisites: 
Xcode 12.0.1 (12A7300)
macOS: 10.15.7 (19H2)
cocoapods: 1.10.0.rc.1

So I've cloned the repo, stayed in master branch and applied changes to podfile that are presented in pull request by @vladyslav-iosdev (#2189 ). After "make bootstrap" i got the "web3swift" pod of version 0.9.0 and trying to build the AlphaWallet target on my device I got the error "Swift Compiler Error: 'nil' requires a contextual type". Screenshot attached 

![Screen Shot 2020-10-12 at 4 48 30 PM](https://user-images.githubusercontent.com/2589471/95753803-cb512b00-0caa-11eb-9a84-5a10a00f9f71.png)

**Comment by hboon** [comment]
@EVanzhula do you have a particular reason to need to use Xcode 12.x? Otherwise, while we are fixing this, you can use Xcode 11.7 instead.

**Comment by vladyslav-iosdev** [comment]
@hboon i suppose this issue can be closed as PR has merged

**Comment by hboon** [comment]
Sill have to wait till #2189 is closed
