### ISSUE TITLE
Activity doesn’t show ETH related information

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/alpha-wallet-ios#2229]
In a Tx, I swap USDT for ETH, and received some CoFi token. Sent USDT and received CoFi are displayed, but received ETH is not displayed.

![Uploading 97126347...]

**Comment by hboon** [comment]
The image didn't uploaded correctly, but I think you this is a dup of https://github.com/AlphaWallet/alpha-wallet-ios/issues/2179 ? It needs to be solved here: https://github.com/AlphaWallet/TokenScript/issues/392
