### ISSUE TITLE
Change the “exchange with Uniswap” button to 1inch

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/alpha-wallet-ios#2265]
ge the “exchange with Uniswap” button to "Exchange with 1inch" 

https://1inch.exchange/#/bat/eth/#/r/0x98f21584006c79871F176F8D474958a69e04595B/

0x98f21584006c79871F176F8D474958a69e04595B is alphawallet.eth

**Comment by hboon** [comment]
@zhangzhongnan928 what if we just label the button "Swap"?

**Comment by zhangzhongnan928** [comment]
> @zhangzhongnan928 what if we just label the button "Swap"?

Yes, that's even better. 

The reason using 1inch:
1. Referral 
2. Much better price than Uni

**Comment by hboon** [comment]
@vladyslav-iosdev If you look at the bottom of https://1inch.exchange/#/api for "Referral Program", it mentions you have to connect a wallet to get a referal link. I haven't tried it, but I presume it might just generate something like https://webapi.com?referralWallet=0xabc, can you try and if that's how it work plug in the address Victor mentioned in the first comment above?

**Comment by vladyslav-iosdev** [comment]
@hboon maybe i missed somethig but it seems like to perform excgange for 1inch we need 2 symbols, and it doesn't work for only one selected (like we did for UniSwap) what do i need to do in this case?

**Comment by vladyslav-iosdev** [comment]
@hboon seems like this could be resolved with adding some initial symbol.

**Comment by vladyslav-iosdev** [comment]
But i got another issue, i am not able to create URL from string like this 
https://1inch.exchange/#/ZRX/1UP#/r/0x98f21584006c79871F176F8D474958a69e04595B

**Comment by hboon** [comment]
Does this work instead?

https://1inch.exchange/#/r/0x98f21584006c79871F176F8D474958a69e04595B/ZRX/1UP

Can you see if you can verify that the referral wallet is picked up with such a URL?

**Comment by zhangzhongnan928** [comment]
> @hboon maybe i missed somethig but it seems like to perform excgange for 1inch we need 2 symbols, and it doesn't work for only one selected (like we did for UniSwap) what do i need to do in this case?

can always be ETH/XXX, even ETH/ETH

https://1inch.exchange/#/r/0x98f21584006c79871F176F8D474958a69e04595B/ZRX/ETH

https://1inch.exchange/#/r/0x98f21584006c79871F176F8D474958a69e04595B/ETH/ETH

**Comment by zhangzhongnan928** [comment]
Currently, the swap pairs are "XXX/1UP" like below 
https://1inch.exchange/#/r/0x98f21584006c79871F176F8D474958a69e04595B/USDC/1UP

It should be:
1. If it is in ETH card, then https://1inch.exchange/#/r/0x98f21584006c79871F176F8D474958a69e04595B/ETH/USDT

2. If it is in other ERC20 Token cards, then https://1inch.exchange/#/r/0x98f21584006c79871F176F8D474958a69e04595B/ERC20/ETH
@hboon

**Comment by hboon** [comment]
Created #2338
