### ISSUE TITLE
Display ENS name or local wallet name in Wallet tab's nav bar title if available, otherwise fallback to "Wallet"

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#2266]
Like in https://zpl.io/bJmwEox. Can you see first if it can be done in a way that is not too fragile or hard to maintain?

Note that users can set a "local wallet name" which overrides the ENS name. in Settings > Change Wallet > Tap and hold a wallet.

<img width="373" alt="Screenshot 2020-11-11 at 3 49 03 PM" src="https://user-images.githubusercontent.com/56189/98784090-89481000-2435-11eb-8964-f6484f858d62.png">

**Comment by vladyslav-iosdev** [comment]
<img width="673" alt="Screenshot 2020-11-12 at 13 34 28" src="https://user-images.githubusercontent.com/55975226/98935176-cf5fab00-24eb-11eb-8fce-f20314dc80c5.png">
@hboon is should be implemented like custom header view?

**Comment by hboon** [comment]
You mean a table view’s?

**Comment by vladyslav-iosdev** [comment]
yep

**Comment by hboon** [comment]
Is it possible to embed a custom view in the nav bar? Otherwise seems quite costly and hackish to implement it as a table view header (with the big title behaviour, push/pop etc)

**Comment by hboon** [comment]
Hackish - not good because the navigation bar has always been a bit fragile across iOS versions..

**Comment by vladyslav-iosdev** [comment]
> Hackish - not good because the navigation bar has always been a bit fragile across iOS versions..

yep, i now that, i will try to use custom view.

**Comment by hboon** [comment]
Thanks. Let’s see if that’s possible. Otherwise we can discuss how we can tweak the UI design to make the implementation less fragile.

**Comment by vladyslav-iosdev** [comment]
@hboon i tried to find any way to customize Large title view for navigation bar but find nothing related to this.

**Comment by vladyslav-iosdev** [comment]
> Thanks. Let’s see if that’s possible. Otherwise we can discuss how we can tweak the UI design to make the implementation less fragile.

@hboon  it seems like these is no way to update large title with custom view.

**Comment by hboon** [comment]
Created #2288 for Tomek

**Comment by colourfreak** [comment]
That should be possible. 

https://iosdesignkit.io/templates/

Examples:
<img width="1356" alt="Screenshot 2020-11-18 at 08 37 46" src="https://user-images.githubusercontent.com/51817359/99499761-ae7ad800-2979-11eb-8960-68a6b37676ca.png">
![a](https://user-images.githubusercontent.com/51817359/99499783-b89cd680-2979-11eb-9bae-843716e8a039.png)
![b](https://user-images.githubusercontent.com/51817359/99499800-bd618a80-2979-11eb-8958-98e41086b067.png)
![c](https://user-images.githubusercontent.com/51817359/99499810-bf2b4e00-2979-11eb-8a0c-4b19b2e7f6fa.png)
![d](https://user-images.githubusercontent.com/51817359/99499811-bf2b4e00-2979-11eb-9768-480128783980.png)
![e](https://user-images.githubusercontent.com/51817359/99499814-c05c7b00-2979-11eb-91e7-605945474c1a.png)
![f](https://user-images.githubusercontent.com/51817359/99499816-c0f51180-2979-11eb-825c-ff4926c6c4f1.png)
![g](https://user-images.githubusercontent.com/51817359/99499818-c18da800-2979-11eb-90ec-71b651f2b3f6.png)

**Comment by hboon** [comment]
Might be, but too much custom work. Hackish and unstable.

**Comment by colourfreak** [comment]
https://stackoverflow.com/questions/44748976/add-title-and-subtitle-to-navigation-bar-similar-to-apple-music-in-ios-11
Hmmmm... Can we try at least? Otherwise, we have to compromise on the design. As a user, you need to know which wallet you are in and how much this is worth. 

Even App Store does that. 
![2020-11-18 08 56 42](https://user-images.githubusercontent.com/51817359/99501414-ff8bcb80-297b-11eb-9c73-2ff5a2cd1467.jpg)

**Comment by hboon** [comment]
Yes, and the App Store app uses a hack according to that page. And it’s also possible that’s a private API only usable by Apple.

**Comment by hboon** [comment]
Oh, but we might be able to customise the place where it says “Wallet” in this screenshot though. It has a fixed height, so less space, but we should be able to fit 2 rows. But not the big title version which displays the text on the left.

On mobile now, will have to check back.

![BEE53903-ED92-4C51-BCC2-7862720877FC](https://user-images.githubusercontent.com/56189/99503409-24526400-29b9-11eb-82b9-db50c038d0e5.png)

**Comment by colourfreak** [comment]
Let me think about it.

**Comment by colourfreak** [comment]
<img width="1187" alt="Screenshot 2020-11-18 at 11 41 20" src="https://user-images.githubusercontent.com/51817359/99520153-0d008000-2993-11eb-8f5f-385bc72aeb10.png">
How about this?

**Comment by colourfreak** [comment]
<img width="1475" alt="Screenshot 2020-11-18 at 11 58 38" src="https://user-images.githubusercontent.com/51817359/99522000-679adb80-2995-11eb-9bf0-846089934fb2.png">

**Comment by vladyslav-iosdev** [comment]
@hboon what if we avoid using UINavigationBar in TokensViewController and add custom table view header, that will hanle scrolling and so on, to reach design requirements, like in first version?

**Comment by hboon** [comment]
>@hboon what if we avoid using UINavigationBar in TokensViewController and add custom table view header, that will hanle scrolling and so on, to reach design requirements, like in first version? 

@vladyslav-iosdev yeah. That would work; but it’s a slippery slope, because while we still can use UINavigationBar for push and pop there, but hide the UINavigationBar when it’s at the base, we are going to want to implement the navigation bar look and feel and behaviour and keep it consistent ourselves, as well as make sure the “real” parts of the table still scroll and pan like before. I’d rather not go there if there are other options.

**Comment by hboon** [comment]
Ditto with UICollectionView

**Comment by colourfreak** [comment]
What about this one? Would it help? https://github.com/AlphaWallet/alpha-wallet-ios/issues/2266#issuecomment-729602966

**Comment by hboon** [comment]
This ought to work: https://github.com/AlphaWallet/alpha-wallet-ios/issues/2266#issuecomment-729602966

@colourfreak do we still show the big title? Maybe just the name and fallback to “Wallet” if not available?

**Comment by colourfreak** [comment]
No, in this example we don't have a Large Title. But instead, we use the same font (size, etc) to show how much this is worth in USD underneath. I think that solves the problem and IMO looks and works even better.

**Comment by hboon** [comment]
> No, in this example we don't have a Large Title. But instead, we use the same font (size, etc) to show how much this is worth in USD underneath. I think that solves the problem and IMO looks and works even better.

Great. Sounds good. @vladyslav-iosdev lets go with that. So for this issue, just need to show the name instead of “wallet” in the nav bar if it’s available. I’ll create a new issue for the blockie and we can get that done too

**Comment by hboon** [comment]
> No, in this example we don't have a Large Title. But instead, we use the same font (size, etc) to show how much this is worth in USD underneath. I think that solves the problem and IMO looks and works even better.

Thanks!

**Comment by hboon** [comment]
@vladyslav-iosdev have renamed this issue and create a followup to this: 

Generate and display blockies for wallets #2294
