### ISSUE TITLE
Update Wallet Tab [Samoa]

### ISSUE THREAD

**Issue by colourfreak** [AlphaWallet/alpha-wallet-ios#2273]
<img width="1829" alt="Screenshot 2021-03-08 at 10 44 07" src="https://user-images.githubusercontent.com/51817359/110303883-39501300-7ffb-11eb-9a29-ec4e73a2b2af.png">

https://zpl.io/V0vZnvx

-----

**Ether, ERC20, xDAI.. going up:**
https://zpl.io/aMrnRKN
<img width="452" alt="Screenshot 2021-03-08 at 10 52 41" src="https://user-images.githubusercontent.com/51817359/110304942-749f1180-7ffc-11eb-9d97-eac051fe33c6.png">

-----

**Ether, ERC20, xDAI.. going down:**
https://zpl.io/2p5jk4y
<img width="453" alt="Screenshot 2021-03-08 at 10 52 46" src="https://user-images.githubusercontent.com/51817359/110304958-78329880-7ffc-11eb-9cb0-93c1bd0f3184.png">

-----

**Savings, Loans, Debt Obligation, LP tokens:**
https://zpl.io/a3mDRvl
<img width="460" alt="Screenshot 2020-11-12 at 11 24 29" src="https://user-images.githubusercontent.com/51817359/98928746-70de0100-24da-11eb-9814-180401c779de.png">

-----

**NFTs:**
https://zpl.io/2GdzLDj
<img width="514" alt="Screenshot 2020-11-12 at 11 40 10" src="https://user-images.githubusercontent.com/51817359/98929709-d41c6300-24db-11eb-8df5-800bc01e4cee.png">

-----
**Large Title** with:
a) tomek.eth - a name that you can change in the Settings
b) $114,224.76 - how much those assets are worth in USD (you can change it to ETH, AUD, etc. in the Settings)
c) +$405.12 (+2.53%) - Portfolio change in last 24h
<img width="798" alt="Screenshot 2021-03-08 at 10 55 45" src="https://user-images.githubusercontent.com/51817359/110305251-d8c1d580-7ffc-11eb-9f6a-8834ff042d23.png">

-----
**Small Title**, when scrolled down:
https://zpl.io/2ZZBnPd
<img width="534" alt="Screenshot 2021-03-08 at 10 56 34" src="https://user-images.githubusercontent.com/51817359/110305449-fabb5800-7ffc-11eb-8bf9-95fe8010027c.png">

**Comment by colourfreak** [comment]
Zeplin:
https://zpl.io/a8rv7WK
https://zpl.io/amQw5AK

**Comment by hboon** [comment]
@AW-STJ For both #2273 and #2274:

Is this considered an important change or a good to have? Reason why I'm asking is there's a bit more design work necessary and also to gauge if it's going to take a lot of work or a little (and weigh it against the importance). We might also need to break it down.

Off the top of my mind (I have not think too deeply about this yet):

A. We only have prices for native crypto (and DAI/SAI), so we can't compute the fiat value for the other tokens right away. So for the total/summary fiat value to make sense, we ought to address this first. Maybe there's a web API (etherscan?) we can use to fetch the total fiat value then it's much less work for us.
B. We currently display the native crypto balance and fiat value balance in the list of wallets screen. Our apps are designed to work with a single wallet at a time. At least on iOS, there isn't a way to fetch the contents of each wallet (i.e. what tokens are in each and their balance) other than the active wallet. If (A) is solved by calling a web API, it might be simple.

**Comment by colourfreak** [comment]
There are more than just #2273 and #2274 I am about to file new issues today. 

If you look at AlphaWallet now, you don't have any incentive to open an app a few times a day (unless you are building it). And the may reason behind are **variables**. We don't have anything new for a user. You can learn how many tokens you have and interact with those tokens using TokenScript and Dapp browser. But [you can't build a habit](https://www.amazon.com/Hooked-How-Build-Habit-Forming-Products/dp/1591847788), because we don't provide any data that a user can consume once in a while. And Zerion app is great in this area (check out [Google Play](https://play.google.com/store/apps/details?id=io.zerion.android) and [App Store](https://apps.apple.com/us/app/zerion-defi-portfolio/id1456732565) reviews). 

Looking at a portfolio, how your tokens are performing, how much you gained, how much you lost. But Zerion is off-chain on mobile devices. You can learn what to do next out of it, but you can't do anything (not within the native app).

**If we aim to be the best DeFi wallet in the market, we need to feed users with data.** 

A. I am sure this is just a detail. Important, but doable. 
B. Would you find this feature useful? If you have multiple wallets, how can you quickly tell me how much ETH you have (Total).

**Comment by colourfreak** [comment]
CoFiX Protocol Analytics will be full of data. I think we can reuse some of their data. Similar to [Uniswap](https://info.uniswap.org/token/0xdac17f958d2ee523a2206206994597c13d831ec7)

**Comment by AW-STJ** [comment]
> @AW-STJ For both #2273 and #2274:
> 
> Is this considered an important change or a good to have? Reason why I'm asking is there's a bit more design work necessary and also to gauge if it's going to take a lot of work or a little (and weigh it against the importance). We might also need to break it down.

Let us consider that and categorise the change into 'Must-Have' or 'Good to have' bucket accurately. Based on my initial thinking, this would be a must-have as we move our focus to DeFi. We can think about validating this design more at this stage as we have a few sprints to go before the activity is completed. We may prototype this design to get some feedback and then push for implementation.

> Off the top of my mind (I have not think too deeply about this yet):
> 
> A. We only have prices for native crypto (and DAI/SAI), so we can't compute the fiat value for the other tokens right away. So for the total/summary fiat value to make sense, we ought to address this first. Maybe there's a web API (etherscan?) we can use to fetch the total fiat value then it's much less work for us.
> B. We currently display the native crypto balance and fiat value balance in the list of wallets screen. Our apps are designed to work with a single wallet at a time. At least on iOS, there isn't a way to fetch the contents of each wallet (i.e. what tokens are in each and their balance) other than the active wallet. If (A) is solved by calling a web API, it might be simple.

We will have to explore solving A & B, as one of our strong assumption is that people across DeFi personas tent to use multiple wallets. We would want to aggregate information across wallets if we want to provide insights to the users.

**Comment by hboon** [comment]
> We will have to explore solving A & B, as one of our strong assumption is that people across DeFi personas tent to use multiple wallets. We would want to aggregate information across wallets if we want to provide insights to the users. 

Sounds good. And A and B are just off the top of my head. We might also need to look into how to synchronise data. Eg. We don’t often sync our transactions history/balance. If and as we implement aggregating information, this might be more blatant and require solving at a more fundamental level. This might be really easy or it might be really hard.

Also, if this is the general direction we are heading towards, we ought to look at more than 1 of this features/changes in aggregate and evaluate if we need to make sure our code base handles that (or if we can even handle it or to what degree) and make sure any work we do sets up the foundation for that.

Software is a combination of a million moving pieces and while we often say anything is possible in software (to a certain extent), lack of proper design and focus will doom us.

**Comment by colourfreak** [comment]
Hold your horses here. We are updating.  ;)

**Comment by colourfreak** [comment]
@hboon This is now up-to-date. Ready for the development.
