### ISSUE TITLE
Add Wallet Summary [Samoa]

### ISSUE THREAD

**Issue by colourfreak** [AlphaWallet/alpha-wallet-ios#2274]
<img width="1532" alt="Screenshot 2021-03-08 at 11 02 38" src="https://user-images.githubusercontent.com/51817359/110306254-e7f55300-7ffd-11eb-9d3b-169bfef628af.png">

-----
This screen will be a replacement for the current "Change/Add Wallet". 

- It will be the first screen you see when launching AlphaWallet (already imported wallets). 
- There are two ways to enter this screen
a) from the wallet tab, you tap on a blockie 
b) You Open Settings -> Change/Add Wallet. So the same as we have now.

-----
Zeplin:
https://zpl.io/aBQO6xK

-----
If you open the summary of all wallets, it will work the same as Watch-only but for all wallets you imported (watch-only and that on-chain)
<img width="727" alt="Screenshot 2020-11-12 at 11 53 28" src="https://user-images.githubusercontent.com/51817359/98931085-d97aad00-24dd-11eb-8353-28ec4266c565.png">

**Comment by colourfreak** [comment]
Updated and ready for the development

**Comment by colourfreak** [comment]
1. Make lines I marked in red in gray colors #dddddd Mike
![2021-07-26 10 52 49](https://user-images.githubusercontent.com/51817359/126963708-b6aab866-dc74-4bff-b3e0-f076ae01fba6.png)

**Comment by colourfreak** [comment]
* Instead of USD symbol, add $ prior to the number
* Add spacing or commas every 3 numbers

for example: $3 400,22  or $3,456.23 

@hboon I think we can unify decimals. 
so 
$1.50
$233.45
$45,453.33 

$000,000,000.00

![2021-07-26 11 07 07](https://user-images.githubusercontent.com/51817359/126964979-452669ea-9a5e-4fe7-ae88-ef30aba7899b.png)

**Comment by colourfreak** [comment]
We don't need to show which wallet you are in (checkmark). Instead, show unified icons for all. https://zpl.io/bAKlY3q

![2021-07-26 11 07 09](https://user-images.githubusercontent.com/51817359/126965148-a63371a4-03cb-4850-ae95-515c189f3fa2.png)

**Comment by hboon** [comment]
> We don't need to show which wallet you are in (checkmark). Instead, show unified icons for all.

Do you mean to show the chevron for the current wallet too? Wouldn't it make usability worse by making it harder for users to go back to the current wallet? And this screen is also accessible in Settings > Change /Add Wallet where we show a checkmark against the current wallet.

**Comment by colourfreak** [comment]
Yes, chevron for the current wallet too. 

https://invis.io/7TZHRQ8W265

It works fine with Zerion. We have few more indicators such as portfolio value, blockie, wallet name to get the difference.
