### ISSUE TITLE
Testing Feedback for 3.09 (361)

### ISSUE THREAD

**Issue by AW-STJ** [AlphaWallet/alpha-wallet-ios#2293]
Hey Boon, wondering whether this is the best way to share testing feedback. Let me know if you have any other ideas, sharing it here for now.

General feedback: Actionsheet works like magic, really good experience 

Specific feedback:
1. Allows 0 transactions to go through
2. Know it is a test build, but was slow especially for wallets with a large number of tokens and transactions. Crashed often, you can use to test this 0x26aaD4D82f6c9FA6E34D8c1067429C986A055872
3. Search: Confirming that the only search are for type of activity itself such as 'Receive', 'Approve' etc.
4. The transition from Activity to Token is not smooth with a tab bar appearing for a split second
![image](https://user-images.githubusercontent.com/61957841/99612458-b4e87d00-2a69-11eb-84c5-93a99755ffca.png)

5. Activity needs network as in Android, otherwise Rinkby and Mainnet transactions looks the same
![image](https://user-images.githubusercontent.com/61957841/99612976-d007bc80-2a6a-11eb-9649-e3510f93c5dd.png)

6. Pending transactions were not populated, at least on Rinkeby network

7. ENS Name in Actionsheet now behaving properly 
![image](https://user-images.githubusercontent.com/61957841/99613224-499faa80-2a6b-11eb-8225-004975fa02f6.png)

8. Approve transactions: Should be 'All tokens', rather than showing the exact balance
![image](https://user-images.githubusercontent.com/61957841/99613683-14e02300-2a6c-11eb-96fe-537fbbdf6793.png)

**Comment by hboon** [comment]
> Hey Boon, wondering whether this is the best way to share testing feedback. Let me know if you have any other ideas, sharing it here for now.

Yeah, GitHub issues are definitely the way to go. But would you create separate issues for them? Much easer to track and address.

**Comment by hboon** [comment]
> 1. Allows 0 transactions to go through

@AW-STJ Do you mean to allow users to send 0 ERC20 tokens? Is there an example where that's useful? We do allow users to send 0 ETH

> 2. Know it is a test build, but was slow especially for wallets with a large number of tokens and transactions. Crashed often, you can use to test this 0x26aaD4D82f6c9FA6E34D8c1067429C986A055872

Created #2340 and #2341

> 3. Search: Confirming that the only search are for type of activity itself such as 'Receive', 'Approve' etc.

@AW-STJ yes, for now

> 4. The transition from Activity to Token is not smooth with a tab bar appearing for a split second
> ![image](https://user-images.githubusercontent.com/61957841/99612458-b4e87d00-2a69-11eb-84c5-93a99755ffca.png)

Created #2342

> 6. Pending transactions were not populated, at least on Rinkeby network

@AW-STJ can you elaborate when it means by "not populated"?

> 7. ENS Name in Actionsheet now behaving properly 
> ![image](https://user-images.githubusercontent.com/61957841/99613224-499faa80-2a6b-11eb-8225-004975fa02f6.png)

@AW-STJ fixed in latest TestFlight

> 8. Approve transactions: Should be 'All tokens', rather than showing the exact balance
> ![image](https://user-images.githubusercontent.com/61957841/99613683-14e02300-2a6c-11eb-96fe-537fbbdf6793.png)

@AW-STJ fixed in latest TestFlight

**Comment by hboon** [comment]
Child issues that were created has been completed. Closing this thread because of inactivity.
