### ISSUE TITLE
Generate and display blockies for wallets

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#2294]
Blockies like https://github.com/ethereum/blockies. Maybe there's a Swift version?

2 places:

* Left of navigation bar in Wallet tab (screenshot below)
* Rows in "Change Wallet" screen zpl.io/bWn60RP

<img width="400" alt="image" src="https://user-images.githubusercontent.com/56189/99616968-3aaffc80-2a59-11eb-8b9b-af6d9fc93176.png">

**Comment by vladyslav-iosdev** [comment]
@hboon i found pod `JdenticonSwift` for generation blockie icon, it generated icons like this 
https://github.com/alejandro-isaza/jdenticon-swift
is it acceptable to use it?

**Comment by vladyslav-iosdev** [comment]
also there is https://github.com/Boilertalk/BlockiesSwift, but it doesn't work for me (generates only gray squares)

**Comment by vladyslav-iosdev** [comment]
> also there is https://github.com/Boilertalk/BlockiesSwift, but it doesn't work for me (generates only gray squares)

i don't know how but it become to work
