### ISSUE TITLE
Support reverse name lookups for .crypto and .zil with UnstoppableDomains

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#2295]
i.e. 0x8aaD44321A86b170879d7A244c1e8d360c99DdA8  -> brad.crypto

Not sure if it's possible. Follow up for #2250

**Comment by vladyslav-iosdev** [comment]
@hboon it seems like there is no any way to determine reverse name for address, i didn't find any api functions.

**Comment by hboon** [comment]
Don't worry about it then. Thanks
