### ISSUE TITLE
Do not show "ENS" label in Actionsheet for transaction confirmation under Recipient if there is no ENS name resolved (yet)

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#2310]
If we tap on Recipient in the actionsheet, we see (A):

<img width='200' src='https://user-images.githubusercontent.com/56189/100065993-71c64980-2e6f-11eb-9741-e9f9e86b35ec.png'>

After a while, it becomes (B):

<img width='200' src='https://user-images.githubusercontent.com/56189/100066001-7559d080-2e6f-11eb-9342-5ae604e3cda3.png'>

Let's make it be (B) unless an ENS name has already been resolved (or provided) and become (A) if/when it's resolved.

**Comment by vladyslav-iosdev** [comment]
@hboon  i suggest that it resolved with empty ens string value, could be there such case? because there is only check for is nill, but not for string itself (if its empty or not)

**Comment by hboon** [comment]
Seems like it shouldn't be empty in the results for a reverse lookup. Maybe it's empty because the reverse lookup isn't completed yet? Anyway, probably good enough to just show (B) when it's not nil and not empty. (I didn't check the logic for how that display i handled).
