### ISSUE TITLE
Slow with large wallet

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#2340]
From Sunil https://github.com/AlphaWallet/alpha-wallet-ios/issues/2293#issue-746194844:

> 2. Know it is a test build, but was slow especially for wallets with a large number of tokens and transactions. Crashed often, you can use to test this 0x26aaD4D82f6c9FA6E34D8c1067429C986A055872

**Comment by vladyslav-iosdev** [comment]
@hboon i found that place where stuck appears, locate in function
`private func filterTransactionsToNotOverrideERC20Transactions(_ transactions: [Transaction], realm: Realm) -> [Transaction]`
it seems like we a trying to filter 10k array, matching with 7k other values that is why execution stucks.
