### ISSUE TITLE
Crash with large wallet

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#2341]
From Sunil https://github.com/AlphaWallet/alpha-wallet-ios/issues/2293#issue-746194844:

> 2. Know it is a test build, but was slow especially for wallets with a large number of tokens and transactions. Crashed often, you can use to test this 0x26aaD4D82f6c9FA6E34D8c1067429C986A055872

**Comment by vladyslav-iosdev** [comment]
@hboon i found that this crash caused in web3swift library ( not sure if that is right crash, but i checked this one several times). when we trying to call `GetBlockTimestampCoordinator`.

**Comment by hboon** [comment]
Hmm.. do you have a fix for it or can you paste a stacktrace and how you reproduced it?
