### ISSUE TITLE
Updates to Binance Smart Chain API

### ISSUE THREAD

**Issue by JamesSmartCell** [AlphaWallet/alpha-wallet-ios#2351]
Heads up, Binance changed the APIs for querying transactions. The end points for mainnet and test are now:

## Mainnet

API route for JSON transaction query:

```https://api.bscscan.com/```
eg
```
https://api.bscscan.com/api?module=account&action=txlist&address=0x0000000000000000000000000000000000001004&startblock=0&endblock=99999999&sort=asc
```

And for taking user to 'view in Etherscan page':

```https://bscscan.com/tx/<Transaction Hash Here>```

## Testnet

```https://api-testnet.bscscan.com/```
```https://testnet.bscscan.com/tx/```

**Comment by hboon** [comment]
@JamesSmartCell thanks!
