### ISSUE TITLE
Add High/Low Fee Warnings 

### ISSUE THREAD

**Issue by colourfreak** [AlphaWallet/alpha-wallet-ios#2360]
1. High Fee Warning caused by a mistake

Zeplin: https://zpl.io/adZWLy5

<img width="2084" alt="Screenshot 2020-12-03 at 14 11 15" src="https://user-images.githubusercontent.com/51817359/101022297-7d052d80-3571-11eb-89ba-4cb197f5324a.png">

----

2. High Fee because the network is congested

Zeplin: https://zpl.io/29rJ6dy

<img width="1607" alt="Screenshot 2020-12-03 at 14 11 21" src="https://user-images.githubusercontent.com/51817359/101022306-82627800-3571-11eb-9686-50c1ee7cf286.png">

----

3. Fee too Low

Zeplin: https://zpl.io/V1Pm63k

<img width="2083" alt="Screenshot 2020-12-03 at 14 11 34" src="https://user-images.githubusercontent.com/51817359/101022319-88585900-3571-11eb-86f0-66dff9c43cf3.png">

----

4. Note that updated a few components: 

I increased the font size to 15pt for the secondary row.

<img width="957" alt="Screenshot 2020-12-03 at 14 12 49" src="https://user-images.githubusercontent.com/51817359/101022518-c9e90400-3571-11eb-9ea4-a5ba8cb9389b.png">

This component has changed to two rows. 
<img width="456" alt="Screenshot 2020-12-03 at 14 17 35" src="https://user-images.githubusercontent.com/51817359/101022896-4bd92d00-3572-11eb-8e54-bd0e2f9aaf01.png">

https://zpl.io/b6qO6Wy
https://zpl.io/agwyXEA
https://zpl.io/VDeR6Yg

**Comment by hboon** [comment]
Created #2367 for tweaking font and layout
