### ISSUE TITLE
Show gas price in actionsheet options

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#2370]
<img width="456" alt="image" src="https://user-images.githubusercontent.com/56189/101443081-8cacb980-3957-11eb-9a15-90363d4d8368.png">

https://zpl.io/VDeR6Yg

**Comment by hboon** [comment]
@colourfreak do you think this:

> Gas Price: 24

Might look better with:

> Gas Price: 24 gwei

Or this?

> 24 gwei?

**Comment by colourfreak** [comment]
Gas Price: 24 gwei - sounds very good

**Comment by colourfreak** [comment]
Gas Price: 24 Gwei

**Comment by hboon** [comment]
Ok!
