### ISSUE TITLE
Speed up app launch

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#2374]
We have done this before, but good to revisit again. See if we can make it faster without drastic changes

**Comment by vladyslav-iosdev** [comment]
@hboon can u please provide more detailed information what do i need to do here?

**Comment by hboon** [comment]
See if you can shave some time off the app launch without too drastic changes. i.e the time between tapping on app icon in homescreen till app is responsive to touches.

**Comment by vladyslav-iosdev** [comment]
@hboon i am not really sure that its related to this issue, but i found that while using wallet with a lot of transactions and activities, we got 100 percentage CPU load for some time, that is causing ui freeze.
<img width="1904" alt="Screenshot 2020-12-11 at 11 39 23" src="https://user-images.githubusercontent.com/55975226/101887879-1d78d480-3ba6-11eb-9d40-410f6fc3d4be.png">

**Comment by hboon** [comment]
Possibly. I can imagine one case is when we fetch the transactions/activities from the database, the other is when it's creating them (before saving to the database). If it's the former, it might matter. I think I patched it a while ago so that it wouldn't load them right away at launch, but still, good to revisit.

**Comment by vladyslav-iosdev** [comment]
it would be good if we move creating activities to background queue, but as i see all actions according activities perform on main queue.

**Comment by vladyslav-iosdev** [comment]
it would be good if we move creating activities to background queue, but as i see all actions according activities perform on main queue.?

**Comment by vladyslav-iosdev** [comment]
@hboon what if we rename `Transaction` to `TransactionObject`, and add `Transaction` struct wrapper for `TransactionObject`, that will allow us to add threadsafe object, and perform all massy execution on background queue.

**Comment by hboon** [comment]
Yes. I was toying with the idea of moving all Realm access to a background thread. So this would go well with it? Do you want to give it a go (just Transaction for now) to see if it works in a PR? Don't rename `Transaction` first, and don't worry too much about code quality, just to reduce the number of changes and localise them; let's see if it works and if there are any gotchas?

**Comment by vladyslav-iosdev** [comment]
@h_boon wanted to let u know, i moved transaction/activities perfomance to background, but it seems like it not all things that need to be done. i found that most cpu loads caused because we calls func update(items: multiple time (for each rpc server) and every call calls fetching all Transaction objects from DB. currebtly i am trying to resolve it
