### ISSUE TITLE
Push instead of present modal the Wallet Address screen (the one with QR code)

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#2375]
* From Fungible send's Receive button
* From Settings

**Comment by vladyslav-iosdev** [comment]
> * From Fungible send's Receive button

@hboon its not clear where it is, can u send me a screenshot?

**Comment by hboon** [comment]
![4B805D33-575F-4A4E-AD87-037838F57C0B](https://user-images.githubusercontent.com/56189/101488412-8b50b080-399a-11eb-946d-21173ae1c4ea.png)

Triggered by the Receive button
