### ISSUE TITLE
Decode ERC20 approval transactions

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#2394]
Look for `DecodedFunctionCall.FunctionType.erc20Transfer`, which decodes ERC20 transfers.

This can be tested through transactions posted from dapp and WalletConnect

**Comment by hboon** [comment]
Extend the functionality of DecodedFunctionCall so we can figure out that given a transaction’s data, that it is an ERC20 approve call.

**Comment by vladyslav-iosdev** [comment]
> If you aren’t sure, but want to tackle this, let me know, and I’ll post back more details.

Yes, please.

**Comment by hboon** [comment]
You probably know some/all of this, so I might be repeating the obvious for you. But any way:

In Ethereum, function calls/transactions are encoded by keccak256 hashing their signature (eg. `balanceOf(address)`) and then taking the first 4 bytes of that hash and sticking in to the front of the transaction's `data` (or function call). This is followed by the function arguments.

This [1] gives an example of the computation. Look for "This is derived as the first 4 bytes of the Keccak-256 hash of the ASCII form of the signature baz(uint32,bool)" and read a page down. (I didn't vet the article for quality).

So given a transaction's data, by looking at the 1st 4 bytes, we can potentially match that transaction to a function call, i.e. we can tell, what function is being called. Since hashing is one-way, this is a little limited of course, but this works well for common, known functions like `balanceOf(address)` or ERC20's `transfer(address,uint256)` function.

So for this issue, we just need to dig up the function signature for ERC20 approval, plug it into the snippet below to get the hash and then amend `DecodedFunctionCall.swift` to support it. Then, when a transaction (and its data) is downloaded, if the transaction is for ERC20 approval, the app will be able to figure it out [2]. It'll also be displayed in the actionsheet for transaction confirmations [3] \(which might be easier for you to test this out)


Here's a web3.js snippet to compute the `transfer()`'s hash:

```
const Web3 = require('web3')
let web3 = new Web3(new Web3.providers.HttpProvider("<infura URL>"));
const f = "transfer(address,uint256)"
hash = web3.utils.sha3(f).substr(0, 10)
console.log(`hash: ${hash}`) //prints "a9059cbb"
```

PS: We might introduce a better way too to do this by using a library to do this decoding (actually web3swift might be able to do this), but I just implemented this in an ad-hoc manner previously because we only needed to see if it worked. So you can pursue this (better) approach too if you like.

[1] https://www.geeksforgeeks.org/application-binary-interfaceabi-in-ethereum-virtual-machine/
[2] Look for `Transaction.decodeOperations`
[3] Look for references to `DecodedFunctionCall.FunctionType.erc20Transfer`
