### ISSUE TITLE
Send 10 tokens but only receives 1

### ISSUE THREAD

**Issue by maxweng** [AlphaWallet/alpha-wallet-ios#2408]
I am seeing a weird issue here with the amount sent. Basically, when I try to send 10 USDT, it only sends 1 instead. And it seems to happen with all the tokens, ie. ETH, and other ERC20 too. I'm with the latest build checked out from the master branch.

**Comment by maxweng** [comment]
Attaching the screenshot [here](https://imgur.com/uEYWRBE). You can see I'm sending 100 USDT, but it shows 1 in the confirmation popup.

**Comment by hboon** [comment]
@maxweng  thanks. I can reproduce this.

**Comment by hboon** [comment]
@vladyslav-iosdev would you help with this? It seems to strip trailing zeros from the user's input. Another way to reproduce this is to try to input an amount which is larger than what is available and see if the "Available: xxx" turns red.
