### ISSUE TITLE
How can we add trx wallet

### ISSUE THREAD

**Issue by akhilccrb** [AlphaWallet/alpha-wallet-ios#2410]
name: Bug Report
about: Using AlphaWallet, but it's not working as you expect?

---

**Describe the bug**

**Steps to reproduce (REQUIRED)**
Steps to reproduce the behavior

1. Tap Wallet tab
2. Tap ...
3. Tap ...
4. Wait ...
5. Tap ...

**Expect**
6a. ...

**Observed**
6b. ...

**Screenshots**
If applicable, screenshots (preferred to video) to help explain your problem, a wallet address or transaction hash if applicable/possible

**Version or build number number**
Version number (if app store), build number (if TestFlight)

**Additional context (Error Messages, etc.)**

**Comment by hboon** [comment]
@akhilccrb do you mean how/if we can support the Tron chain?

**Comment by akhilccrb** [comment]
yes , how can I ass trx coin @hboon

**Comment by hboon** [comment]
Can't do this at the moment.
