### ISSUE TITLE
Supporting Heco

### ISSUE THREAD

**Issue by kevinho** [AlphaWallet/alpha-wallet-ios#2411]
Integration Docs Here:

https://docs.hecochain.com/#/en-us/wallet

Thanks a lot.

[Heco icon.zip](https://github.com/AlphaWallet/alpha-wallet-ios/files/5742915/Heco.icon.zip)

**Comment by hboon** [comment]
@kevinho the "scan" URL specified in https://docs.hecochain.com/#/en-us/wallet for mainnet is https://scan-mainnet.hecochain.com. It returns a 404. Perhaps it should be this instead?:

https://scan.hecochain.com

**Comment by hboon** [comment]
@kevinho is there a web API endpoint to fetch a list of historical transactions made by and against an address/account?

**Comment by hboon** [comment]
Reopen to wait for information.

**Comment by hboon** [comment]
@kevinho this is now on the app store.

**Comment by hboon** [comment]
@kevinho would you help update https://docs.hecochain.com/#/en-us/wallet once it's verified? Thanks.
