### ISSUE TITLE
Integration Docs Here:

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/alpha-wallet-ios#2412]
Integration Docs Here:

https://docs.hecochain.com/#/en-us/wallet

Thanks a lot.

[Heco icon.zip](https://github.com/AlphaWallet/alpha-wallet-android/files/5742914/Heco.icon.zip)

__Originally posted by @kevinho in https://github.com/AlphaWallet/alpha-wallet-android/issues/1702__

**Comment by hboon** [comment]
Duplicate of #2411
