### ISSUE TITLE
Add test case(s) to check ERC20 send token transactions are sent to contract, and not to the recipient

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#2416]
Follow up to #2415

**Comment by vladyslav-iosdev** [comment]
@hboon can u provide more details what exactly need to do here? (maybe some steps, and so on)

**Comment by hboon** [comment]
Maybe create a TransactionConfigurator, pass in a few types of transactions and check the output unsigned (is it UnconfirmedTransaction or RawTransaction) that the fields to sign are correct.

Something in the order of 10-30 lines of code maybe for a single transaction type? No UI.

As a litmus test, it should be able to catch the bug fixed by the linked PR
