### ISSUE TITLE
Display more user-friendly message when there's not enough funds for sending a transaction instead of: "APIKit.Session-TaskError error 2"

### ISSUE THREAD

**Issue by AW-STJ** [AlphaWallet/alpha-wallet-ios#2441]
name: Bug Report
about: APIKit.Session-TaskError error 2

**Desciption**
Some users report this error when they are trying to execute any transactions
![image](https://user-images.githubusercontent.com/61957841/103978632-f676e800-51cf-11eb-9f85-5c13da07e720.png)

One user have reported that the error went away when he topped up his ETH. So the error could be because of insufficient gas.

**Version or build number number**
Version number (3.11)

**Comment by AW-STJ** [comment]
The issue still persists in the latest AppStore release 3.14 (372)

![image](https://user-images.githubusercontent.com/61957841/106661584-79376b00-65f5-11eb-97e9-a0fc05838a82.png)

**Comment by hboon** [comment]
Fixed #2449, but not deployed to App store yet. Still in review.
