### ISSUE TITLE
Add send all funds button

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#2450]
Can probably track down an approach from https://github.com/AlphaWallet/alpha-wallet-android/pull/1704

Easier for tokens, bit more work for native crypto. Careful that xDai has a fixed gas price (look for `estimateGasPriceForXDai`)

**Comment by vladyslav-iosdev** [comment]
@hboon can u provide more details, please?

**Comment by hboon** [comment]
@vladyslav-iosdev 

Sorry, had wanted to mentioned this but forgot:

Check out https://app.zeplin.io/project/5d0356be2f25b319dcc5944b/screen/5dfc4ced734c3d9725f640b3 and looks or the "All Funds" button. When you tap on it, the amount should populate itself to "sweep" the account clean for the chosen native crypto or token. For native crypto, basically use the full amount minus the gas.

**Comment by vladyslav-iosdev** [comment]
@hboon am i understand right gas i can get from
`TransactionConfigurator.estimateGasPrice(server: session.server)`
right?

**Comment by hboon** [comment]
@vladyslav-iosdev you’ll need both the gas price and gas (amount)

**Comment by vladyslav-iosdev** [comment]
@hboon did u have a chance to check this PR?
