### ISSUE TITLE
Add all Aave V1 and V2 tokens

### ISSUE THREAD

**Issue by colourfreak** [AlphaWallet/alpha-wallet-ios#2453]
Currently, we only display icons for tokens V1 (below you can see how it looks from my wallet perspective) https://etherscan.io/token/0xfC1E690f61EFd961294b3e1Ce3313fBD8aa4f85d?a=0x80cc263cb3fa1be2aec748b3811261c1e2a1ba8d

we need this for V2 too

https://etherscan.io/token/0x028171bca77440897b824ca71d1c56cac55b68a3?a=0x80cc263cb3fa1be2aec748b3811261c1e2a1ba8d

Zeplin: https://zpl.io/bWl54p1

and please add all aTokens. 

<img width="1522" alt="Screenshot 2021-01-13 at 11 02 48" src="https://user-images.githubusercontent.com/51817359/104437299-e1fb6c80-558e-11eb-9423-386e878adf13.png">

**Comment by vladyslav-iosdev** [comment]
@hboon can u help me with adding this images, how can i find right contrats for this aave tokens?

**Comment by vladyslav-iosdev** [comment]
i found that there is several places where we can find aave tokens, but how can i select right one?
https://etherscan.io/accounts/label/aave-v2
https://etherscan.io/tokens/label/aave?subcatid=0&size=50&start=0&col=3&order=desc

**Comment by hboon** [comment]
@colourfreak if you have acquired them, can you help to list them? Otherwise we’ll have to figure out another way.

@vladyslav-iosdev usually they will list it in their docs. Try looking there too?

**Comment by vladyslav-iosdev** [comment]
@hboon seems like we can follow these links 
https://etherscan.io/tokens/label/aave
https://etherscan.io/tokens/label/aave-v2

**Comment by hboon** [comment]
@vladyslav-iosdev Ok
