### ISSUE TITLE
If the message to sign is very long for personal_sign, it isn't displayed correctly

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#2455]
Test: https://danfinlay.github.io/js-eth-personal-sign-examples/

**Comment by vladyslav-iosdev** [comment]
@hboon can u send a screenshot with wrong displaying.

i took string from https://danfinlay.github.io/js-eth-personal-sign-examples/ and seems like it displays normal.
![IMG_0527](https://user-images.githubusercontent.com/55975226/104693830-f9636280-5712-11eb-9648-7b29755ec2c3.PNG)

**Comment by vladyslav-iosdev** [comment]
@ how can i reproduce this issue?

**Comment by hboon** [comment]
Strange. When I tap "personal_sign" in https://danfinlay.github.io/js-eth-personal-sign-examples/, after a few seconds (which is strange too), I see this (master/3bf7e2794c1820d0dad4383cac1c4eb1e4604f90, iOS 12.4 iPhone X simulator):

![Simulator Screen Shot - iPhone X (12 4) - 2021-01-27 at 10 56 55](https://user-images.githubusercontent.com/56189/105936320-6b7e6480-608e-11eb-9141-4fbebd167e6d.png)

**Comment by vladyslav-iosdev** [comment]
@hboon hey, maybe i did something wrong, but when i tap `personal_sign` nothing happens for me

**Comment by hboon** [comment]
It seems to take very long to appear. If you wait for say, a minute, does it?

**Comment by vladyslav-iosdev** [comment]
> It seems to take very long to appear. If you wait for say, a minute, does it?

it asks to connect with using `MetaMask`, does it right? and after i succesfully connect with `MetaMask`, nothing happenswhen i tap on `personal_sign `

**Comment by hboon** [comment]
Oh. I mean to load this URL and test it in the dapp browser. But it should work with MetaMask too (look at who wrote it :))

**Comment by vladyslav-iosdev** [comment]
oh, thanks a lot;)
 i followed these steps, and for some time application get freezed

<img width="1904" alt="Screenshot 2021-01-28 at 13 01 44" src="https://user-images.githubusercontent.com/55975226/106129849-532f4800-6169-11eb-85aa-2eadc59ebeee.png">

**Comment by vladyslav-iosdev** [comment]
right after that i received this
![IMG_0536](https://user-images.githubusercontent.com/55975226/106130057-98ec1080-6169-11eb-8ddf-60927320cab7.PNG)

**Comment by hboon** [comment]
@vladyslav-iosdev  How did you reproduce the issue? Or why were you able to get the message to display earlier?
