### ISSUE TITLE
WalletConnect connection with QR code does not work

### ISSUE THREAD

**Issue by ochikov** [AlphaWallet/alpha-wallet-ios#2458]
1. Open: https://web3modal.com/
2. Tap connect
3. Choose Wallet Connect
4. Scan QR Code through alpha wallet app.

The connection should be established, but nothing happens.
A possible problem in the App, with other apps (Metamask and Rainbow) works.

**Comment by vladyslav-iosdev** [comment]
@hboon i just scanned qr code from  https://web3modal.com/ and it get connected succesfully. but for now i see only this.
<img width="1026" alt="Screenshot 2021-01-15 at 15 18 42" src="https://user-images.githubusercontent.com/55975226/104731911-1022ad00-5745-11eb-9a30-516589fd5b8c.png">

**Comment by ochikov** [comment]
> @hboon i just scanned qr code from https://web3modal.com/ and it get connected succesfully. but for now i see only this.
> <img alt="Screenshot 2021-01-15 at 15 18 42" width="1026" src="https://user-images.githubusercontent.com/55975226/104731911-1022ad00-5745-11eb-9a30-516589fd5b8c.png">

Yes, this is what it need to be. On my side it is not working. I am scanning the code, but the https://web3modal.com/ is staying on the QR code not getting the event. This is happening also with another app using the same library: web3Modal.

**Comment by hboon** [comment]
@ochikov Is this with the app store version? The iOS version has WalletConnect functionality in our code base, but we haven't released it yet. But we will very soon.

**Comment by ochikov** [comment]
> @ochikov Is this with the app store version? The iOS version has WalletConnect functionality in our code base, but we haven't released it yet. But we will very soon.
Yes, I am using the AppStore version. Thanks. When do you expect the release ?

**Comment by hboon** [comment]
@ochikov If nothing goes wrong, some time this time.

**Comment by hboon** [comment]
@ochikov this is now on the app store
