### ISSUE TITLE
WaletConnect doesn't work for certain TX Signing, build 3.14(370)

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/alpha-wallet-ios#2462]
The same TX doesn't work on iOS
![IMG_1725](https://user-images.githubusercontent.com/33795543/104991991-1f229b80-5a74-11eb-9618-c3068ccbf31b.PNG)

But works on Andriod 
![photo_2021-01-19 16 33 33](https://user-images.githubusercontent.com/33795543/104991980-1631ca00-5a74-11eb-8d53-b43e7d3272b9.jpeg)

**Comment by hboon** [comment]
@zhangzhongnan928 is there a dapp I can test this against?

**Comment by zhangzhongnan928** [comment]
> @zhangzhongnan928 is there a dapp I can test this against?
https://example.walletconnect.org/
<img width="815" alt="Screen Shot 2021-01-19 at 6 25 56 pm" src="https://user-images.githubusercontent.com/33795543/105001402-d1ae2a80-5a83-11eb-9ab9-bdc81b347380.png">

https://gnosis-safe.io/app/
<img width="1199" alt="Screen Shot 2021-01-19 at 6 28 11 pm" src="https://user-images.githubusercontent.com/33795543/105001617-2782d280-5a84-11eb-8888-c395a16589bb.png">

**Comment by hboon** [comment]
@vladyslav-iosdev if you have the chance to look at it today. Otherwise I’ll try to take a look tomorrow so we might do a build with it

**Comment by vladyslav-iosdev** [comment]
> @vladyslav-iosdev if you have the chance to look at it today. Otherwise I’ll try to take a look tomorrow so we might do a build with it

ok, i will check it

**Comment by vladyslav-iosdev** [comment]
> @zhangzhongnan928  did u change selected walled while connected to WalletConnect?

**Comment by zhangzhongnan928** [comment]
> @zhangzhongnan928 did u change selected walled while connected to WalletConnect?

no,

my current status is, I have 2 wallets(1 Keystore 1 seed), all backed up.
I have Ethereum and xDai network enabled 

I just test **eth_signTypedData** in https://example.walletconnect.org/, same issue.

**Comment by vladyslav-iosdev** [comment]
@hboon  it seems like the reason of this issue hidden here
```
private func start() {
        for each in UserDefaults.standard.walletConnectSessions {
            try? server.reconnect(session: each)
        }
    }
```
and it appears because we cconnect to stored walletConnect sessions  but we don't  save `urlToServer`

**Comment by zhangzhongnan928** [comment]
using wallet connect with gnosis-safe.io, got "ErrorTransaction failed - Request failed with status code 42"

is it related to 👇

<img width="878" alt="Screen Shot 2021-01-21 at 5 20 05 pm" src="https://user-images.githubusercontent.com/33795543/105293180-27620e80-5c0d-11eb-8fcf-a614a85f6ad9.png">
<img width="788" alt="Screen Shot 2021-01-21 at 5 18 05 pm" src="https://user-images.githubusercontent.com/33795543/105293195-28933b80-5c0d-11eb-8af0-02095eaacb69.png">

**Comment by hboon** [comment]
> using wallet connect with gnosis-safe.io, got "ErrorTransaction failed - Request failed with status code 42"

@zhangzhongnan928 how do you get these error with gnosis-safe.io? Might not be related. How can we reproduce it?

**Comment by hboon** [comment]
Reopen to make sure gnosis safe isn’t trigger a different bug

**Comment by zhangzhongnan928** [comment]
> > using wallet connect with gnosis-safe.io, got "ErrorTransaction failed - Request failed with status code 42"
> 
> @zhangzhongnan928 how do you get these error with gnosis-safe.io? Might not be related. How can we reproduce it?
> 
> (the one with WalletConnect is fixed, pending merging)

It is not easy to test, as you need to make a  multisig TX request. After signing msg in mobile the gnosis multisig website shows that error msg.

I will test it again once the new build is out.

**Comment by hboon** [comment]
@zhangzhongnan928 Thanks. Created #2483 to track
