### ISSUE TITLE
Hardcode 'Convert xDAI' button to https://bridge.xdaichain.com/

### ISSUE THREAD

**Issue by AW-STJ** [AlphaWallet/alpha-wallet-ios#2473]
Since the xDAI bridge does not support the conversion end-to-end, let us remove the xDAI conversion button as an easy fix.

We can re-introduce the feature, if there is interest from users.

**Comment by zhangzhongnan928** [comment]
1. The function is ok, but the UX need to be redesigned. Before that, I agree to remove the TokenScript of it.
2. I suggest to keep the button, but same like swap, link the button to https://bridge.xdaichain.com/

**Comment by colourfreak** [comment]
Btw, we do have a better UX. 

![dai-xdai-bridge](https://user-images.githubusercontent.com/51817359/105336565-b2291600-5bd9-11eb-91b0-a917b815742b.jpg)

**Comment by zhangzhongnan928** [comment]
> Btw, we do have a better UX.
> 
> ![dai-xdai-bridge](https://user-images.githubusercontent.com/51817359/105336565-b2291600-5bd9-11eb-91b0-a917b815742b.jpg)

The logic has changed from the xDai side. It seems request an extra step to claim the converted Dai.

**Comment by colourfreak** [comment]
Then deep linking is a much better idea. Very cost-effective and quick to change. Same for Xdai bridge, Swap on Uniswap, Swap on 1inch, Stake on Lido etc.

**Comment by colourfreak** [comment]
@hboon @vladyslav-iosdev Can we automatically connect to xDai network when clicking this link?

![2021-02-19 09 22 54](https://user-images.githubusercontent.com/51817359/108478102-5ca55f00-7294-11eb-8878-93881922cc61.png)

**Comment by zhangzhongnan928** [comment]
> @hboon @vladyslav-iosdev Can we automatically connect to xDai network when clicking this link?
> 
> 
> 
> ![2021-02-19 09 22 54](https://user-images.githubusercontent.com/51817359/108478102-5ca55f00-7294-11eb-8878-93881922cc61.png)
> 
> 
> 

The bridge works on both Xdai and Ethereum

**Comment by hboon** [comment]
A few things here:

* Generally speaking, yes we shouldn't switch chains automatically for this dapp, but in this case, we can and we do switch automatically switch to the xDai chain when it's launched from the xDai card. Similary, if we were to add this dapp to the list of actions for the Dai card, then we can automatically switch to the Ethereum chain
* The error in the last few screenshots is because we have a bug where the browser doesn't switch to the xDai chain properly. The fixed version is in the app store.

**Comment by colourfreak** [comment]
> A few things here:
> 
> * Generally speaking, yes we shouldn't switch chains automatically for this dapp, but in this case, we can and we do switch automatically switch to the xDai chain when it's launched from the xDai card. Similary, if we were to add this dapp to the list of actions for the Dai card, then we can automatically switch to the Ethereum chain
> * The error in the last few screenshots is because we have a bug where the browser doesn't switch to the xDai chain properly. The fixed version is in the app store.

Yep. Very good idea.
