### ISSUE TITLE
Error with gnosis-safe.io

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#2483]
Victor:

> using wallet connect with gnosis-safe.io, got "ErrorTransaction failed - Request failed with status code 42"

> It is not easy to test, as you need to make a multisig TX request. After signing msg in mobile the gnosis multisig website shows that error msg.

**Comment by hboon** [comment]
Verify/reproduce with coming build (372)

**Comment by zhangzhongnan928** [comment]
works perfectly with 3.14 (172)
