### ISSUE TITLE
Navigation bar (Activity tab)

### ISSUE THREAD

**Issue by vladyslav-iosdev** [AlphaWallet/alpha-wallet-ios#2493]
**Navigation bar doesn't change to Large state, after activity get opened**

**Comment by hboon** [comment]
It works like this in master. How do I reproduce the bug?

https://user-images.githubusercontent.com/56189/105934870-eeea8680-608b-11eb-83c0-1a49c9f236a0.mov

**Comment by vladyslav-iosdev** [comment]
yep, i am able to reproduce it on master

https://user-images.githubusercontent.com/55975226/105998178-0b4ee900-60b5-11eb-82c0-27c78b9c407e.MP4

**Comment by hboon** [comment]
Oh. You need to tap "Go to Token"
