### ISSUE TITLE
Prompt to sign messages

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#2497]
Continuing from #2496:

There are a few versions for the prompt to sign messages https://app.zeplin.io/project/5d0356be2f25b319dcc5944b/screen/6012d1ea027bac2033d22ea7. You can try them at https://danfinlay.github.io/js-eth-personal-sign-examples/. Not all of them work. So try these:

* personal_sign
* Sign Typed Data
* Sign Typed Data V3
* Sign Typed Data V4 (it's the same as v3, the message in this example might be a bit longer)

It looks like this https://github.com/AlphaWallet/alpha-wallet-ios/pull/2461 currently for Sign Typed Data V3 and V4. For Sign Typed Data V3/V3, besides the message, it'll be good to include these 2 values:

* "domain name" ("Ether Mail" in the screenshot)
* "verifying contract" ("0xCcCCccccCCCCcCCCCCCcCcCccCcCCCcCcccccccC")

The message for Sign Typed Data V3/V4 is a JSON string. For styling, we can change the font, color and add indentation (spaces), but can't otherwise have much control over the formatting. The length of some of the values might be too long to display (hence the intentional ellipsis for long values, otherwise it does a very ugly linewrap breaking the indentation). We ought to be able to do our normal 0xabcd...abcd formatting for addresses though, and keep the trailing truncation for non-address values.

**Comment by colourfreak** [comment]
I am not sure if that is enough, but we could use this template. Those examples from Metamask do not work.

<img width="1792" alt="Screenshot 2021-02-05 at 11 40 07" src="https://user-images.githubusercontent.com/51817359/107023482-01a93d80-67a7-11eb-826b-71124d47cc00.png">

so in your example, we can have something like

<img width="1484" alt="Screenshot 2021-02-05 at 11 53 56" src="https://user-images.githubusercontent.com/51817359/107025043-22729280-67a9-11eb-8b87-b29527aa120c.png">

or

<img width="1190" alt="Screenshot 2021-02-05 at 11 55 44" src="https://user-images.githubusercontent.com/51817359/107025049-26061980-67a9-11eb-9134-52fb41d1893b.png">

**Comment by hboon** [comment]
> I am not sure if that is enough, but we could use this template. Those examples from Metamask do not work.

Looks great. Thanks!
