### ISSUE TITLE
Hide 'Console' button

### ISSUE THREAD

**Issue by AW-STJ** [AlphaWallet/alpha-wallet-ios#2500]
Let us hide the console option, that sits under Settings -> Advanced.

Could not see the purpose of it.

https://github.com/AlphaWallet/alpha-wallet-android/issues/1566

**Comment by hboon** [comment]
It's for showing errors. Notably TokenScript [1]. We can't remove it unless we work out a better way. It's already tucked in Advanced where most users will not be exposed to it.

I had hoped that we can display other types of errors, but never got around to it yet.
