### ISSUE TITLE
Bring 'Clear Cache' option to browser

### ISSUE THREAD

**Issue by AW-STJ** [AlphaWallet/alpha-wallet-ios#2501]
I came across a very devout AlphaWallet Android user, who is using AlphaWallet because we are the only wallet with clear browser option. Intuitively, the user is looking for the option within the browser.

So it would be best to bring up the 'Clear Cache' option to iOS browser as well. We can continue to keep the option under 'Advanced'.

cc: @colourfreak this you agreed to this as well during the meeting

**Comment by hboon** [comment]
@AW-STJ our stand is that we don't touch the iOS dapp browser to minimise any problems with app store review. Trust and a few other populate iOS wallets have already lost theirs.

Has that decision changed?

**Comment by AW-STJ** [comment]
That decision around reducing the risk of browser removal still holds.

I imagined, doing something simple and minimal as this would not spook Apple.

**Comment by hboon** [comment]
And on technical merits alone, I'm not sure it's the most intuitive either. It's definitely useful for some users [1], but every action we add to the menu for a subset of users, it means every user has to look at it and choose to use/not used it when the tap on the menu.

[1] But why is it useful for those users? Is there a bigger problem that can be solved? For example, do the user really want privacy mode instead? Or is clearing the cache a way to fix bugs?

**Comment by AW-STJ** [comment]
The real issue was that, this user was an avid user of many Dapps on mobile. This user often comes across unresponsive UIs, as Dapps can be. Clearing cache helps to continue keep using Dapps better.

**Comment by hboon** [comment]
My point is:

* I don't think it's technically a good change and it makes the experience (even if just slightly) worse for users who don't need it. My intuition says no.
* The user is on Android, not iOS. And this is based on the feedback for a single user?
* Why risk anything with app store rejection by bringing us attention (however low, probably zero, chance) for something that we aren't sure is super useful for most users? This 10 minute change might (or might not) bring us hours or tens of hours of time to address?

There are many other ways we can improve the app.

If after weighing this and you think it's worth it, let's go ahead.

**Comment by AW-STJ** [comment]
Sure thing Boon. Let us discuss this and take off the list, during the weekly sync meeting.

**Comment by AW-STJ** [comment]
Closing the issue as the decision was taken, not to touch iOS browser
