### ISSUE TITLE
Fix Wallet connection in https://bridge.xdaichain.com/

### ISSUE THREAD

**Issue by colourfreak** [AlphaWallet/alpha-wallet-ios#2506]
1. You go to Browser.
2. You launch https://bridge.xdaichain.com/
3. You hit "Connect Wallet" and nothing happens.

This is on our side, as I check with Trust and Huobi wallets and it worked fine.

![2021-02-11 12 12 26](https://user-images.githubusercontent.com/51817359/107637109-eab68f80-6c6d-11eb-96b3-d85239d8a0d9.png)

The button works fine to prompt and connect to wallet in web3 browsers of other wallets.

**Comment by vladyslav-iosdev** [comment]
@hboon seems like it throws in `bridge.xdaichain` with error 

`Exception with thrown value: TypeError: e.request is not a function. (In 'e.request({method:"eth_requestAccounts"})', 'e.request' is undefined)` 

here: 
```
const ConnectToInjected = async () => {
  let provider = null;
  if (typeof window.ethereum !== 'undefined') {
    provider = window.ethereum;
    try {
      await provider.request({ method: 'eth_requestAccounts' }) <--- HERE
    } catch (error) {
      throw new Error("User Rejected");
    }
  } else if (window.web3) {
    provider = window.web3.currentProvider;
  } else {
    throw new Error("No Web3 Provider found");
  }
  return provider;
};

```

**Comment by hboon** [comment]
> eth_requestAccounts

@vladyslav-iosdev Ah. Maybe they made a change recently. It's related to #2499 and should work properly once that's done.
