### ISSUE TITLE
Implement deep links for xDAI Fiat-on-Ramp on Ramp.network

### ISSUE THREAD

**Issue by AW-STJ** [AlphaWallet/alpha-wallet-ios#2507]
We would like to show a Buy xDAI button and then direct the users to Ramp.network's xDAI purchasing option.

All the relevant technical documents would be on their site https://docs.ramp.network/. Let me know if you need more information. 

The scope of this work would be to
1. Add the 'Buy xDAI' option to xDAI token's the kebab menu
2. Take users to xDAI purchase site on Ramp.Network, on clicking this option.

![image](https://user-images.githubusercontent.com/61957841/107637316-0d729380-6cc2-11eb-9d51-46d5496cb131.png)

**Comment by colourfreak** [comment]
From Paulina (Ramp.Network)

"If you want to set up deep linking, you have to integrate in hosted mode https://docs.ramp.network/quick-start-hosted and set parameter swapAsset=xDai"

**Comment by hboon** [comment]
@colourfreak @AW-STJ can you access the https://buy.ramp.network/?swapAsset=xDai in a browser and try to buy xDai? I tried several countries (Singapore, Australia, US) and not the Debit card option is available for me:

<img width='200' src='https://user-images.githubusercontent.com/56189/108322549-8c0a8c00-7200-11eb-908a-b6f8a9a4002c.PNG'>

Payment is enabled on their testnet versions. There's even Apple Pay. I didn't try though.

**Comment by colourfreak** [comment]
I requested their support. But it goes through if you make a payment in EUR. For Singapore too.

**Comment by colourfreak** [comment]
Paulina from Ramp said that we did not integrate API keys. 

Production key:
j5wr7oqktym7z69yyf84bb8a6cqb7qfu5ynmeyvn

Staging Key:
m5mqqkn3m82sr28f2zy459wfo83h8wadgoe5tsht

---

They feel this information is still missing in their documentation. So they kindly request you to tell, where would you expect to see this information in their documentation so it's more obvious and easier to integrate (just a feedback on how they can improve it)

**Comment by hboon** [comment]
> Paulina from Ramp said that we did not integrate API keys.
> 
> Production key:
> j5wr7oqktym7z69yyf84bb8a6cqb7qfu5ynmeyvn
> 
> Staging Key:
> m5mqqkn3m82sr28f2zy459wfo83h8wadgoe5tsht
> 
> They feel this information is still missing in their documentation. So they kindly request you to tell, where would you expect to see this information in their documentation so it's more obvious and easier to integrate (just a feedback on how they can improve it)

Thanks! Ah I see https://docs.ramp.network/api-keys/ mentions it. A link to that from https://docs.ramp.network/quick-start-hosted/ (and from the pages for the other modes of integration would make it clearer)

**Comment by AW-STJ** [comment]
Yes i know this is now resolved, but to add on... yes, I have purchased xDAI on Ramp before.

It worked fine with my Australian cards.
