### ISSUE TITLE
with build3.15(374) DApps cannot read wallet balance in DApp browser

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/alpha-wallet-ios#2516]
DApps can load the wallet address, but cannot read anything from the node 
Tested with Uniswap, CoFiX

P.S. It seems DApps are unable to read blockchain data through AlphaWallet

**Comment by zhangzhongnan928** [comment]
it seems dapps won’t be able to load blockchain data though AlphaWallet. I tied https://james-sangalli.github.io/eth-allowance/ nothing can be loaded.

Although most of the Dapps still can display blockchain data, because they fall back to use their own node. Like CoFiX.
The rest parts of CoFiX can fall back to use its own node connections, but below 2 sections require wallet's node. 
![image](https://user-images.githubusercontent.com/33795543/108180343-c1f53500-715a-11eb-89b5-0149e22abe80.jpeg)res

**Comment by zhangzhongnan928** [comment]
Not solved try a DApp which doesn't have a build in node connection like this one👇

 https://james-sangalli.github.io/eth-allowance/

**Comment by hboon** [comment]
Have a fix. Preparing a PR.
