### ISSUE TITLE
Need to show WalletConnect is loading instead of not showing anything

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/alpha-wallet-ios#2517]
After scanning a WalletConnect QR or open from a mobile browser, before the connect windows appear,  AlphaWallet needs to show WalletConnect is loading instead of not showing anything.

Below is how Trust work

![IMG_2131](https://user-images.githubusercontent.com/33795543/108143195-5fc90f80-711b-11eb-9902-bd4eeeeb4e64.PNG)

![IMG_2132](https://user-images.githubusercontent.com/33795543/108143188-5e97e280-711b-11eb-9f3c-a246ff06e484.PNG)

**Comment by colourfreak** [comment]
We can add one more step, which is a blank screen with a spinner + Walletconnect in the headline. Then, you finish the flow in  the opened WalletConnect session (not in the Wallet as currently). You have to go back to Wallet, if you want to see a virtual token in a list. 

![walletconnect_improved](https://user-images.githubusercontent.com/51817359/108193016-3efdbb80-7115-11eb-98ea-44ef0858ba80.jpg)

**Comment by zhangzhongnan928** [comment]
> We can add one more step, which is a blank screen with a spinner + Walletconnect in the headline. Then, you finish the flow in the opened WalletConnect session (not in the Wallet as currently). You have to go back to Wallet, if you want to see a virtual token in a list.
> 
> ![walletconnect_improved](https://user-images.githubusercontent.com/51817359/108193016-3efdbb80-7115-11eb-98ea-44ef0858ba80.jpg)

Yes, we need this " a blank screen with a spinner + Walletconnect in the headline."
