### ISSUE TITLE
action sheets need to show which network I am using for the current TX

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/alpha-wallet-ios#2518]
now we have WalletConnect support, the TX can start from outside AlphaWallet. 

Fo me, seeing which network I am using for the current TX is important.

Below is a WalletConnect TX on Kovan, which looks no different to a mainnet Tx
![IMG_2133](https://user-images.githubusercontent.com/33795543/108143477-f4cc0880-711b-11eb-85f9-9014979a02ad.PNG)

**Comment by colourfreak** [comment]
Adding one more cell should do the work.
<img width="877" alt="Screenshot 2021-02-17 at 11 12 37" src="https://user-images.githubusercontent.com/51817359/108189452-0d82f100-7111-11eb-9ad7-a2e80b347f02.png">

**Comment by hboon** [comment]
@colourfreak the one with the logo, on the left looks nicer, the right is slightly more consistent. Which should we use?

**Comment by colourfreak** [comment]
The one on the left. You don't have to read, just a quick glance at the logo and you know which network you are using. 
https://zpl.io/awNz3Z1
