### ISSUE TITLE
lack hints on transactions accomplished since I was away

### ISSUE THREAD

**Issue by colourful-land** [AlphaWallet/alpha-wallet-ios#2545]
name: lack hints on transactions accomplished since I was away

This issue requires some UX design before implementation @colourfreak 
---

**Describe the bug**

Metamask would produce a hint that a transaction is included in the blockchain if the browser was last time closed with the transaction in pending status. Such a hint is in the form of a bubble (pop-up message) and I wasn't fast enough to take a screenshot. Such a hint is produced once the user logs in to metamask.

**Steps to reproduce (REQUIRED)**
Steps to reproduce the behavior

1. Do any transaction (what I did was visiting 1inch and hit "approve").
2. A transaction is created and I send it.
3. Wait for 1 hour, nothing happens, the transaction isn't included in the blockchain. You can reproduce this scenario by setting a low gas fee
4. Went to sleep.
5. Next morning, opened αW. The transaction has gone through, but there is no visual hint that it did

**Expect**
6a. A list of new transactions confirmed since last time the user left

**Observed**
6b. (lack of UI hints)

**Design challenges**

- How does a wallet know if the user has left the scene? How do you decide if a user has left and needs to be notified or if the user is watching the dapp all the time? My proposal is to always adding Pending transactions in the notification area and replace them with transaction finished notification when it's finished. This would result in double notification (if the webpage uses dapp which also produces such notification), but double notification is better than none I guess, and given one is inside the dapp and the other in the mobile notification area. Such a notification feature can be programmed without a notification server, except that αW will only be able to generate such a notification when it's running. Luckily, in Android, any app that has uncleared notification is allowed to live in memory. maybe it's the same in iOS?

- In the particular example, the user expects to hit the notification and return the dapp (since it was an approval transaction and usually the user wants to continue), but given we don't have tabbed browsing, we don't want to risk overwriting what is already opened in the user's dapp tab when the user hit a notification. So I propose asking the user if the user wants to return to the dapp (from which he sent that transaction)

- Consider the scenario with WalletConnect, a user might connect to a dapp and send a transaction. Later, she receives a notification on her mobile and she clicks that notification, resulting the dapp to be opened in the mobile. This might be desirable sometimes (e.g. when the wallet connection actually already broke). But undesirable in many others (e.g. the user already half filled the form in her desktop browser and opened the dapp in αW and realised the filled fields become empty).

**Comment by colourfreak** [comment]
> How does a wallet know if the user has left the scene? How do you decide if a user has left and needs to be notified or if the user is watching the dapp all the time? My proposal is to always adding Pending transactions in the notification area and replace them with transaction finished notification when it's finished. This would result in double notification (if the webpage uses dapp which also produces such notification), but double notification is better than none I guess, and given one is inside the dapp and the other in the mobile notification area. Such a notification feature can be programmed without a notification server, except that αW will only be able to generate such a notification when it's running. Luckily, in Android, any app that has uncleared notification is allowed to live in memory. maybe it's the same in iOS?

Yeah, I like it. I designed notifications already. Also did the same to Activities and Pending transactions. But I have never seen any push notification in AlphaWallet. So it's not on my side. I did the job and provided the design. But we never came with activities to the end. We started, but never finished.

iOS https://zpl.io/amPWE1A
Android https://zpl.io/bLv1m96

> In the particular example, the user expects to hit the notification and return the dapp (since it was an approval transaction and usually the user wants to continue), but given we don't have tabbed browsing, we don't want to risk overwriting what is already opened in the user's dapp tab when the user hit a notification. So I propose asking the user if the user wants to return to the dapp (from which he sent that transaction)

All good. But we need notifcations working. Not on my side. The design is ready. We need to implement it. 

> In the particular example, the user expects to hit the notification and return the dapp (since it was an approval transaction and usually the user wants to continue), but given we don't have tabbed browsing, we don't want to risk overwriting what is already opened in the user's dapp tab when the user hit a notification. So I propose asking the user if the user wants to return to the dapp (from which he sent that transaction)

Very challenging. 

On the other hand, we might update the current Pending Transaction icon by an animated gif. What would you need from me @hboon to create something like below (must be faster than this animation)

![spinner_2](https://user-images.githubusercontent.com/51817359/111328706-c4ba4b80-866e-11eb-923e-b7ae7c517871.gif)

**Comment by hboon** [comment]
> On the other hand, we might update the current Pending Transaction icon by an animated gif. What would you need from me @hboon to create something like below (must be faster than this animation)

@colourfreak just the 2 colors if it's just 2 solid colors.

**Comment by colourfreak** [comment]
> > On the other hand, we might update the current Pending Transaction icon by an animated gif. What would you need from me @hboon to create something like below (must be faster than this animation)
> 
> @colourfreak just the 2 colors if it's just 2 solid colors.

https://github.com/AlphaWallet/alpha-wallet-ios/issues/2650

**Comment by hboon** [comment]
Closed for now since there's #2650.
