### ISSUE TITLE
Bug with "Send All" funds in Send Dialog. Verify it's working 

### ISSUE THREAD

**Issue by JamesSmartCell** [AlphaWallet/alpha-wallet-ios#2547]
The 'All Funds' option in Send dialog needs an upgrade.

The expected operation is:

For ERC20 Tokens: 'All Funds' simply selects full token balance.
For Ethereum:

First obtain the gas price for default sending (average probably), then use gas limit of 21000 Gwei (the exact amount to make an ethereum transfer). 
Calculate the network fee as normal (21000 in WEI * gas price in WEI) and subtract this from the available ethereum balance.

Set the amount to send as the value calculated above.

Then, in the gas options, notice that the user is emptying the account, if the amount to send + network fee exactly matches the balance. If the user adjusts the gas options; re-calculate the amount that will be sent by subtracting the network fee using the gas price the user selected (so the amount to send could go up or down).

**Comment by hboon** [comment]
Already in master. Done with #2457, not deployed to app store yet

**Comment by hboon** [comment]
Looks like a bug.

**Comment by hboon** [comment]
From Tomek:

> when you want to send 'All funds' in Android it deducts an estimated gas price you need to cover the transaction. In iOS it takes the whole amount and it causes errors.
