### ISSUE TITLE
Remove App Intro Slides

### ISSUE THREAD

**Issue by colourfreak** [AlphaWallet/alpha-wallet-ios#2552]
There are [many studies](https://www.nngroup.com/articles/mobile-tutorials/), that this is not an effective way to onboard users. Those screenshots are small, out-of-date. Users are about to see the same screens after skipping this intro. 

![Uploading 2021-02-24 07.49.04.png…](
![2021-02-24 07 49 08](https://user-images.githubusercontent.com/51817359/108965708-850ad000-767d-11eb-89e7-c41a19c8dcf2.png)
![2021-02-24 07 49 00](https://user-images.githubusercontent.com/51817359/108965697-820fdf80-767d-11eb-9f7d-bb3872e6744a.png)

**Comment by hboon** [comment]
Careful to keep the coordinator. I think BC might use them?

**Comment by colourfreak** [comment]
Got it. Is this only to show those interested in forking AW, that we have this tutorial available?

**Comment by hboon** [comment]
@colourfreak sorry :) I meant that comment for. Vlad (or whoever implements it)

**Comment by colourfreak** [comment]
haha ;)

**Comment by vladyslav-iosdev** [comment]
@hboon it seems like `WelcomeViewController` is using without own coordinator, is uses in `AppCoordinator` only.

**Comment by hboon** [comment]
@vladyslav-iosdev ah, keep `WelcomeViewController` then. It's used by BC too right? Easier to stay in sync. Just don't use it anymore.

**Comment by vladyslav-iosdev** [comment]
@hboon  yep, it's used by BC
