### ISSUE TITLE
Improve error messages resulting from errors returned from RPC nodes

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#2557]
- [x] Log them #2559, #2571, #2576, #2625, #2636, #2640
- [x] Analyse them
- [x] Tomek prepare user-friendly messages + (if necessary: FAQ page)
- [x] Display user-friendly messages instead, as well as link to FAQ page if available

**Comment by hboon** [comment]
List of messages:

Some of the messages returned by RPC nodes aren't consistent across chains.

* Usually not enough native crypto to pay for gas (but xDai returns this when gas price specified is too low too): "insufficient funds for gas * price + value" (xDai returns a slightly different message)
* Gas price is too low: "transaction underpriced"

**Comment by hboon** [comment]
@colourfreak I have build a list here https://github.com/AlphaWallet/alpha-wallet-ios/issues/2557#issuecomment-785693226

I'll update again if we collect more. But I think those are the main ones.

**Comment by colourfreak** [comment]
I will go one by one, as it requires special attention.

1. Insufficient funds

<img width="1454" alt="Screenshot 2021-03-19 at 13 51 06" src="https://user-images.githubusercontent.com/51817359/111783397-78fbe200-88ba-11eb-82b8-c95b33acc108.png">

* We should avoid Alerts/Popups at any cost
* Instead, let's prevent users from making errors and prevent them just at a right time.
* If you are sending ETH or ERC20 and you don't have enough Ether to pay for the fees, the green button becomes gray (inactive). It prevents users from attempting to send which will end up with an alert. But what we are missing is the feedback in human-readable language that describes a problem and quick fixes to that issue (they work better than instructions). 
* on tap on the gray button, the modal slides in from the bottom. 
* Buy Now takes you to Ramp.network for ETH purchase
* Learn more takes you here: https://alphawallet.com/faq/what-do-insufficient-funds-for-gas-price-mean/

**Comment by colourfreak** [comment]
* execution reverted: (sometimes technical reason given here)
* revert
What can I do to recall this alert? What should I do?

**Comment by hboon** [comment]
> * execution reverted: (sometimes technical reason given here)
> * revert
>   What can I do to recall this alert? What should I do?

If you mean how to trigger it, it happens when the smart contract runs and the logic returns an error, e.g trying to vote outside the voting period. There's nothing general we can do in the app to trigger it. It depends on the contract/token and context around it.

Example, this is from Uniswap (I don't know how to trigger this, maybe trying to swap when there's not enough liquity for the target token?)

> revert: UniswapV2Router: INSUFFICIENT_B_AMOUNT

Another example:

> revert: You did not register for yesterday's period Or already claimed

So, we'll have to assume the error messages might or not not make sense, but it is probably specific to the contract. (note that the error message is not provided sometimes. Just "revert" or "execution reverted")

**Comment by hboon** [comment]
> Buy Now takes you to Ramp.network for ETH purchase

Do we have an alternative for when Ramp is not available for that native token, or if it's testnet?

**Comment by colourfreak** [comment]
> > Buy Now takes you to Ramp.network for ETH purchase
> 
> Do we have an alternative screen for when Ramp is not available for that native token, or if it's testnet?

If a Ramp is not available, take them to https://alphawallet.com/browser-item-category/buy-crypto/ in a Browser

**Comment by colourfreak** [comment]
4. Nonce is low
5. Nonce is too low

@hboon I need your help. What can we enter as a text. First sentence should describe what nonce is, second what exactly to change. Then, if you hit "Correct Nonce" it will take you back to Setting custom speed with an error marked in that input field. 

So I need this text + What to suggest under the input field?

![nonce_too_low](https://user-images.githubusercontent.com/51817359/112297292-00b86680-8c96-11eb-988b-d41890ebcf7d.jpg)

**Comment by hboon** [comment]
Something like:

> The nonce is the total number of transactions which has been sent from this wallet so far, and is included for security purposes.

Regarding the red text under the textbox "We recommend xxxx...", maybe we should have something like "Leave the nonce empty and we'll fill it in for you".

The rational behind this is if the user fills it in, it's likely that they know (or think they know) what they are doing, eg. they want to manually speed up a transaction (for some reason, not using our yet-to-be-available functionality, maybe they want more control, like change the amount of eth sent, etc).

I think we could hit this too after speedup/cancel is available, but with a twist [1]. But let's just ignore that for now. We just handle it directly in the speedup/cancel flow instead.

[1] When the user hits Confirm for the replacement transaction and the previous transaction has already been processed

**Comment by hboon** [comment]
> > > Buy Now takes you to Ramp.network for ETH purchase
> > 
> > 
> > Do we have an alternative screen for when Ramp is not available for that native token, or if it's testnet?
> 
> If a Ramp is not available, take them to https://alphawallet.com/browser-item-category/buy-crypto/ in a Browser

If it's testnet, do you want to link to a different page?

**Comment by colourfreak** [comment]
![4_nonce_too_low](https://user-images.githubusercontent.com/51817359/112453526-14c49c80-8d58-11eb-8a46-d54b430bc48f.jpg)
![5_nonce_is_too_low](https://user-images.githubusercontent.com/51817359/112453537-18f0ba00-8d58-11eb-84a9-f6a313ceaafa.jpg)

**Comment by colourfreak** [comment]
> > > > Buy Now takes you to Ramp.network for ETH purchase
> > > 
> > > 
> > > Do we have an alternative screen for when Ramp is not available for that native token, or if it's testnet?
> > 
> > 
> > If a Ramp is not available, take them to https://alphawallet.com/browser-item-category/buy-crypto/ in a Browser
> 
> If it's testnet, do you want to link to a different page?

https://alphawallet.com/browser-item-category/utilities/ - where you can get ETH from faucets

**Comment by colourfreak** [comment]
![6_transaction_underpriced](https://user-images.githubusercontent.com/51817359/112455102-b13b6e80-8d59-11eb-8a46-941316cbdfb0.jpg)

**Comment by colourfreak** [comment]
![7_intrinsic_gas_too_low](https://user-images.githubusercontent.com/51817359/112459578-47719380-8d5e-11eb-9cc0-fa8e0f5f4486.jpg)

**Comment by colourfreak** [comment]
![8_Transaction_gas_too_low](https://user-images.githubusercontent.com/51817359/112460263-fd3ce200-8d5e-11eb-9e2e-4e52292750e3.jpg)

**Comment by colourfreak** [comment]
I don't have a better idea for a copy or where to link buttons in the screenshot below:

<img width="431" alt="Screenshot 2021-03-25 at 14 49 04" src="https://user-images.githubusercontent.com/51817359/112483502-60d40900-8d79-11eb-9867-74e2a55b1ed0.png">
<img width="599" alt="Screenshot 2021-03-25 at 14 49 18" src="https://user-images.githubusercontent.com/51817359/112483510-62053600-8d79-11eb-9d04-d0ed0ea50780.png">
<img width="554" alt="Screenshot 2021-03-25 at 14 49 24" src="https://user-images.githubusercontent.com/51817359/112483512-629dcc80-8d79-11eb-8980-3fd1e1ed2296.png">

**Comment by hboon** [comment]
How about we display the message verbatim for these and point to a page that list possible explanations? Especially for execution reverted which can be very long and specific to each dapps/smart contract?

**Comment by hboon** [comment]
@colourfreak are these available on Zeplin?

**Comment by colourfreak** [comment]
https://zpl.io/aRnDQPv

But we are still missing: Invalid Sender, Revert, Execution Reverted.

**Comment by hboon** [comment]
Invalid sender would be something like (likely this is initiated from a dapp or WalletConnect and it's configured wrongly):

> You might be sending this transaction on the wrong chain.

Revert, and Execution Reverted are for same error messages so we can treat them the same way.

If we don't have FAQ pages to link them to for now, shall we skip them for now and fill them in later? It's still better than the current state.

**Comment by hboon** [comment]
Do we also have the FAQ entries for these?

* nonce too low (i.e. nonce)
* transaction underpriced	 (i.e. gas price too long)
* intrinsic gas too low (i.e gas limit too low)
* intrinsic gas exceeds gas limit (i.e gas limit too high)

**Comment by colourfreak** [comment]
> Do we also have the FAQ entries for these?
> 
> * nonce too low (i.e. nonce)
> * transaction underpriced	 (i.e. gas price too long)
> * intrinsic gas too low (i.e gas limit too low)
> * intrinsic gas exceeds gas limit (i.e gas limit too high)

No, we don't have. I can't write FAQ about something I don't understand.

**Comment by colourfreak** [comment]
https://alphawallet.com/faq/what-does-nonce-too-low-means/

I can make templates like this one, but I am unable to come up with anything better, because lack of my knowledge in that subject.

**Comment by hboon** [comment]
Done. There'll be more
