### ISSUE TITLE
Add the ability to delete wallets

### ISSUE THREAD

**Issue by AW-STJ** [AlphaWallet/alpha-wallet-ios#2568]
Currently, there is no way to delete wallets, once added. Not sure if it is intentional or not.

Let us add that ability to delete at least watch wallets if it is intentional, to avoid users accidentally deleting the wallet. We will have to do a manage wallet functionality for iOS, but will address it in a separate issue.

**Comment by hboon** [comment]
The functionality has always been there. Swipe and tap the cross button.
