### ISSUE TITLE
Manage Wallets functionality

### ISSUE THREAD

**Issue by AW-STJ** [AlphaWallet/alpha-wallet-ios#2569]
Let us implement a more detailed manage wallet's functionality for iOS like in Android:

![image](https://user-images.githubusercontent.com/61957841/109415087-c77c3600-7a0a-11eb-8b04-8414bd720323.png)

@colourfreak - do we have Zeplin designs for this functionality?

**Comment by hboon** [comment]
These functionality are available in the swipe menu as well as tap and hold.

**Comment by hboon** [comment]
Functionality already exists. Re-open if we are going to change the graphical UI design.
