### ISSUE TITLE
Deeplink FAQ from the Settings to AlphaWallet.com/faq

### ISSUE THREAD

**Issue by colourfreak** [AlphaWallet/alpha-wallet-ios#2583]
When you go to **Settings -> Support** you will find "FAQ" at the end of the list. 

![2021-03-02 12 03 18](https://user-images.githubusercontent.com/51817359/109639591-a96c1e00-7b4f-11eb-9770-8b2682852560.jpg)

You can link this to [https://alphawallet.com/faq/](https://alphawallet.com/faq/) and after clicking this, it will open in a Browser.

**Comment by hboon** [comment]
Vlad, would you show the standalone browser like we do for showing etherscan page for transactions?
