### ISSUE TITLE
build3.17（381）send "All Fund" will add "," in numbers which breaks the send function 

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/alpha-wallet-ios#2590]
![IMG_2325](https://user-images.githubusercontent.com/33795543/109811460-f8fd3780-7c7e-11eb-8c48-6b389022f124.jpg)
![IMG_2324](https://user-images.githubusercontent.com/33795543/109811475-fd295500-7c7e-11eb-8675-7d54e8a27834.PNG)

**Comment by vladyslav-iosdev** [comment]
@zhangzhongnan928 what locale is using here and region?

**Comment by zhangzhongnan928** [comment]
> @zhangzhongnan928 what locale is using here and region?

English

**Comment by hboon** [comment]
@vladyslav-iosdev the "," is generated. So maybe when generating the amount and transforming it to text for display, it's generated with the thousands separator? eg. `12000` -> `"12,000"`

**Comment by vladyslav-iosdev** [comment]
@hboon yep, the problem is that `EtherNumberFormatter.full.number(from:, units: )` doesn' t support values formated in current locale, (cases where decimalSeparator is comma)

**Comment by vladyslav-iosdev** [comment]
@hboon latest changes removes  grouping separator from formtted values for amount text field, for all funds values
