### ISSUE TITLE
Populate separators (Dot vs Comma) for amounts correctly

### ISSUE THREAD

**Issue by AW-STJ** [AlphaWallet/alpha-wallet-ios#2596]
Changing language between Spanish vs others does not change the amount separators correctly. Some times it comes up right, sometimes it does not.

![image](https://user-images.githubusercontent.com/61957841/109932769-be4adc00-7d1e-11eb-8d76-d9e46e5a2f45.png)

Its particularly confusing when users get dot separators for English. This is a screenshot from a customer, I tried to replicate this on English but could not. 

![image](https://user-images.githubusercontent.com/61957841/109933778-e2f38380-7d1f-11eb-8193-f9a911df326b.png)

**Comment by hboon** [comment]
Do you change the language in the in-app Settings or the device Settings? If it's the former, can you kill the app after changing the language in-app and see if the problem persists?

**Comment by hboon** [comment]
Closed from non-activity

**Comment by AW-STJ** [comment]
> @AW-STJ Do you change the language in the in-app Settings or the device Settings? If it's the former, can you kill the app after changing the language in-app and see if the problem persists?

I changed in in app settings. The delimiters are not changed at all, as I tested today. Even after killing the app and reopening.

**Comment by hboon** [comment]
Continue at #2655
