### ISSUE TITLE
Check if parsing/processing pending transaction is working correctly

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#2598]
We are hitting this line

https://github.com/AlphaWallet/alpha-wallet-ios/blob/554de9b913eedfde7f589efee6a3917bef242b36/AlphaWallet/Extensions/Session+PromiseKit.swift#L59

with the output:

```
JSONRPCError.resultObjectParseError | error: The operation couldn’t be completed. (AlphaWallet.CastError<AlphaWallet.PendingTransaction> error 1.) | from: kovan
```

**Comment by vladyslav-iosdev** [comment]
@hboon what account can i watch to reproduce this issue?

**Comment by hboon** [comment]
@vladyslav-iosdev might have chanced upon why this is happening. I'll fix it

**Comment by hboon** [comment]
Was fixed at https://github.com/AlphaWallet/alpha-wallet-ios/pull/2633/files#diff-4902c50a135f139a6c1960fb7a536bfcba64af0a20777c986ea276b64a459e95L224
