### ISSUE TITLE
Check if CoinGecko API is good for our purpose

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#2599]
We already use CoinGecko for ETH prices, it looks like we might be able to use them for other tokens as well as historical prices:

https://www.coingecko.com/api/documentations/v3#/coins/get_coins__id__market_chart

I think there's enough data for #2274

**Comment by hboon** [comment]
- [ ] Able to fetch fiat value of both native crypto and token (especially popular ERC20s) For #2274
- [ ] Price history for a particular token with 1 call, eg. 1 call to get price history (across 1 month or 1 year) for WBTC. Or even better 1 call for several tokens. For #2629

**Comment by vladyslav-iosdev** [comment]
> * Price history for a particular token with 1 call, eg. 1 call to get price history (across 1 month or 1 year) for WBTC. Or even better 1 call for several tokens. For #2629

as i found on  https://www.coingecko.com/api/documentations/v3#/coins/get_coins__id__market_chart_range it allows api call for one coin per time /coins/{id}/market_chart
