### ISSUE TITLE
add 3 more EVM based network

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/alpha-wallet-ios#2618]
- **Fantom**
Mainnet
Network Name: Fantom Opera
New RPC Url: https://rpcapi.fantom.network
ChainID: 250
Symbol: FTM
Block Explorer URL: https://ftmscan.com/

Testnet
Network Name: Fantom testnet
New RPC Url: https://rpc.testnet.fantom.network/
ChainID: 0xfa2
Symbol: FTM

- **Avalanche**
Avalanche Mainnet Settings:
Network Name: Avalanche Mainnet C-Chain
New RPC URL: https://api.avax.network/ext/bc/C/rpc
ChainID: 0xa86a
Symbol: AVAX
Explorer: https://cchain.explorer.avax.network/

FUJI Testnet Settings:
Network Name: Avalanche FUJI C-Chain
New RPC URL: https://api.avax-test.network/ext/bc/C/rpc
ChainID: 0xa869
Symbol: AVAX
Explorer: https://cchain.explorer.avax-test.network

- **Matic**
miannet
https://rpc-mainnet.maticvigil.com/
<img width="170" alt="metamask-settings-mainnet" src="https://user-images.githubusercontent.com/33795543/110260363-ff354000-7fff-11eb-8745-3a066c816dcc.png">

Testnet
https://rpc-mumbai.maticvigil.com/
![metamask-settings-mumbai](https://user-images.githubusercontent.com/33795543/110260375-1116e300-8000-11eb-9f7e-8c15b355fc5c.png)

**Comment by hboon** [comment]
Vlad, would you let Tomek know which icons you need?

**Comment by vladyslav-iosdev** [comment]
@colourfreak can u check comment https://github.com/AlphaWallet/alpha-wallet-ios/issues/2618#issue-824028458, and provide icons for these networks?

**Comment by colourfreak** [comment]
When do you want to use these icons?

**Comment by vladyslav-iosdev** [comment]
> When do you want to use these icons?

Oh, sorry! it seems like we can add without icons for now. Missed this information.

**Comment by colourfreak** [comment]
Matic is no longer Matic, but Polygon now. 

Anyway, you might need these icons for different action sheets, where we have to indicate which network you are using. 

https://zpl.io/V4w5jyz

**Comment by vladyslav-iosdev** [comment]
> Matic is no longer Matic, but Polygon now.
> 
> Anyway, you might need these icons for different action sheets, where we have to indicate which network you are using.
> 
> https://zpl.io/V4w5jyz

ok, thx  lot ;)
