### ISSUE TITLE
Cancel and speed up transactions

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#2619]

**Comment by hboon** [comment]
@colourfreak do you have the latest UI designs?

https://github.com/AlphaWallet/alpha-wallet-android/issues/1541#issuecomment-666378719 and the one in zpl://screen?pid=5d0356be2f25b319dcc5944b&sid=5f27e5cd3bd29121031f7f28 aren't consistent.

**Comment by colourfreak** [comment]
https://zpl.io/VDj1zeg

<img width="1788" alt="Screenshot 2021-03-16 at 08 25 04" src="https://user-images.githubusercontent.com/51817359/111271183-23f96b00-8631-11eb-8838-36d9ea620492.png">

**Comment by colourfreak** [comment]
I did not get what is inconsistent. @hboon Please take a look one more time, maybe I missed this part.

**Comment by hboon** [comment]
> I did not get what is inconsistent. @hboon Please take a look one more time, maybe I missed this part.

@colourfreak speed up is good now. Thanks. Do we have a similar design for cancelling a transaction? I think other than the additional button to "Cancel", the screens would be the same except for the copy.

**Comment by colourfreak** [comment]
https://zpl.io/addw4w5

**Comment by colourfreak** [comment]
<img width="1867" alt="Screenshot 2021-03-17 at 10 46 29" src="https://user-images.githubusercontent.com/51817359/111447758-09e18a80-870e-11eb-82cc-928c76337e18.png">
