### ISSUE TITLE
After connecting on mobile Safari and then signing with AlphaWallet on iOS, the example.walletconnect.org dapp redirects to Math Wallet #454

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#2621]
https://github.com/WalletConnect/walletconnect-monorepo/issues/454

**Comment by hboon** [comment]
Need to verify again

**Comment by vladyslav-iosdev** [comment]
@hboon visiting https://example.walletconnect.org triggers aw and shows sign screen for me.

**Comment by hboon** [comment]
Great. Thanks!
