### ISSUE TITLE
Add Price Alerts tab [Samoa]

### ISSUE THREAD

**Issue by colourfreak** [AlphaWallet/alpha-wallet-ios#2632]
https://zpl.io/aNN9JDn

<img width="1799" alt="Screenshot 2021-03-10 at 15 46 31" src="https://user-images.githubusercontent.com/51817359/110647042-c9d35280-81b7-11eb-9bc2-92bdd98ca3ec.png">

**Comment by hboon** [comment]
@colourfreak but can't have meaningful price alerts without push though?

**Comment by colourfreak** [comment]
Good point.

**Comment by hboon** [comment]
Also maybe good with widgets

**Comment by vladyslav-iosdev** [comment]
@hboon @colourfreak what api can we use for signaling prices?

**Comment by colourfreak** [comment]
I think you can make the UI for now. And we will add push notifications and local notificafions soon.

**Comment by vladyslav-iosdev** [comment]
ok, got it, working on it.

**Comment by hboon** [comment]
Yeah, but you can also add local notifications support. Doesn't require server (like how we are showing local notifications for receiving ETH now). We can try that out and if it doesn't work, disable it.
