### ISSUE TITLE
Tweak back up seed phrase introduction copy

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#2649]
Copy in here:

<img width="588" alt="image" src="https://user-images.githubusercontent.com/56189/111431035-37422e80-8736-11eb-806f-6b64fbd5ae71.png">

Refer: https://github.com/AlphaWallet/alpha-wallet-android/issues/1748

**Comment by vladyslav-iosdev** [comment]
@hboon can u provide more details what do i need to do here?

**Comment by hboon** [comment]
@vladyslav-iosdev The text in this screen has changed (on mobile now. Can check later)
