### ISSUE TITLE
Improve Pending Transaction icon & Background in Activity tab

### ISSUE THREAD

**Issue by colourfreak** [AlphaWallet/alpha-wallet-ios#2650]
Problem: Current icon does not stand out enough. Very hard to see the difference between pending transactions and confirmed. 

**Solution:**
1. Add background color for all pending transactions #e6f3ff Solitude

<img width="574" alt="Screenshot 2021-03-17 at 11 40 09" src="https://user-images.githubusercontent.com/51817359/111455119-b1ae8680-8715-11eb-9eee-c2c1683e844b.png">

2. Replace a current icon by an animated icon https://zpl.io/bzmrPgl or a bigger https://zpl.io/Vk4zmWW

We need this animation in Activity Main screen and internal like:

![spinner_2](https://user-images.githubusercontent.com/51817359/111456357-3057f380-8717-11eb-9095-7f898ccc1eb3.gif)

colors: 
#007fed Azure
#ECECEC

**Comment by hboon** [comment]
@vladyslav-iosdev some Core Animation fun, perhaps?

**Comment by hboon** [comment]
@vladyslav-iosdev could you do this for this screen too? 

<img width='200' src='https://user-images.githubusercontent.com/56189/111736286-83b57780-88b8-11eb-8a8a-25965bf7116c.png'>
