### ISSUE TITLE
Decimal and thousands separator not using the one specified in Settings > Advanced > Change Language

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#2655]
Refer: #2596

Can be observed in the Wallet tab with Spanish chosen in the in-app settings. (it still uses . as the decimal separator if there's what your iOS setting is)

It works in iPhone X 12.4 Simulator, it doesn't work on iPhone 11 Pro 14.5.

Maybe it's the iOS version number?

**Comment by vladyslav-iosdev** [comment]
@hboon as i found using Config.locale that was added in prev. commits should be used for tests only. Because it causes locale issues, like in https://github.com/AlphaWallet/alpha-wallet-ios/issues/2662.  I suppose we need to push off Locale.current and not from Config.locale
