### ISSUE TITLE
Move TaiChi option in Settings somewhere else.

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#2658]
Maybe in Settings > Advanced?

At least until we figure out if we should move it into somewhere like in the actionsheet, etc

**Comment by colourfreak** [comment]
Yes, please move it to **Advanced** and change the icon to https://zpl.io/25PWXwn

<img width="628" alt="Screenshot 2021-03-24 at 09 19 48" src="https://user-images.githubusercontent.com/51817359/112277483-158aff00-8c82-11eb-9ac4-689f19a4f3b7.png">
