### ISSUE TITLE
Remove "Save" button from Select Active Networks

### ISSUE THREAD

**Issue by colourfreak** [AlphaWallet/alpha-wallet-ios#2660]
The back button should automatically save your changes. The same way you did for changing languages. 

![2021-03-19 12 09 41](https://user-images.githubusercontent.com/51817359/111771702-4c40ce00-88ac-11eb-8323-7dbb24638ce3.png)

**Comment by hboon** [comment]
Vlad: maybe do a check upon "back" and compare if they list has changed? We might be just restarting with doing a comparison currently.
