### ISSUE TITLE
Wrong amount in Send actionsheet

### ISSUE THREAD

**Issue by colourfreak** [AlphaWallet/alpha-wallet-ios#2661]
I tried to send 5 DAI, but it displays my total balance under "Amount". 

![2021-03-19 12 16 39](https://user-images.githubusercontent.com/51817359/111772418-1d772780-88ad-11eb-8c56-fbc96feaf08a.png)

**Comment by hboon** [comment]
Vlad: could you include a test case for this too. The screen's too fragile
