### ISSUE TITLE
No way to enter decimals when sending funds

### ISSUE THREAD

**Issue by colourfreak** [AlphaWallet/alpha-wallet-ios#2662]
Maybe only for Europeans? 

![2021-03-19 12 20 54](https://user-images.githubusercontent.com/51817359/111773205-25839700-88ae-11eb-85ca-2260a21991c7.gif)

**Comment by hboon** [comment]
Vlad: could you include a test case for this too. The screen's too fragile

**Comment by hboon** [comment]
@colourfreak can you help to do a screenshot of the Settings.app > General > Language & Region screen, as well as the in-app Settings > Advanced > Change Language screen when you can reproduce this?

I can't reproduce the Send screen in your video which shows 0.3628 as the balance ("." as the decimal separator), but with the keyboard showing "," as the decimal separator.

This screen in Settings.app :

<img width="463" alt="Screenshot 2021-03-23 at 12 46 26 PM" src="https://user-images.githubusercontent.com/56189/112094355-18c8b100-8bd6-11eb-85ee-cba9e0d2d42b.png">

**Comment by colourfreak** [comment]
![image](https://user-images.githubusercontent.com/51817359/112108844-0e47f080-8bb1-11eb-9e13-294acb76a1ab.png)

**Comment by hboon** [comment]
@colourfreak thanks. How about the in-app version?

**Comment by colourfreak** [comment]
![image](https://user-images.githubusercontent.com/51817359/112131270-afdb3c00-8bc9-11eb-9d8e-5125385bd3d6.png)

![image](https://user-images.githubusercontent.com/51817359/112131291-b49ff000-8bc9-11eb-9301-29e84b5353f5.png)
