### ISSUE TITLE
Not able to connect to Uniswap using walletconcect on IOS

### ISSUE THREAD

**Issue by StillFantastic** [AlphaWallet/alpha-wallet-ios#2663]
To reproduce:
1. Go to https://app.uniswap.org/#/swap
2. Connect using walletconenct
3. Scan QR code on mobile

Then it stuck at loading.

**Comment by hboon** [comment]
Is there any chance you are connecting from within China?

What happens if you try again?

**Comment by StillFantastic** [comment]
@hboon I am not in China, but somehow it works now.
Thanks for the help.
