### ISSUE TITLE
Crash when verifying identity for ETH purchase via Ramp

### ISSUE THREAD

**Issue by jinkjonks** [AlphaWallet/alpha-wallet-ios#2667]
name: Bug Report
about: Using AlphaWallet, but it's not working as you expect?

---

**Describe the bug**

**Steps to reproduce (REQUIRED)**
Steps to reproduce the behavior

1. Wallet
2. Tap onto Ethereum page
3. Tap (...) -> Buy
4. Enter purchase details + create new account
5. Prompt to continue for verification
6. Prompt to record video for verification

**Expected**
6a. usage of front facing camera to record video

**Observed**
6b. Crash

https://user-images.githubusercontent.com/38381586/111983811-a8327d80-8b5e-11eb-8819-09ebd69a933c.mp4

**Version or build number**
Version number 3.18 
iOS 14.4.1 
iPhone 11 Pro Max

**Additional context (Error Messages, etc.)**
This is my first time making an account with Ramp so maybe this isn't a problem for already verified users. 
Tried to verify using Opera on iOS and it worked fine.

**Comment by hboon** [comment]
@vladyslav-iosdev crashes with this line:

> error	13:35:34.430490+0800	AlphaWallet	This app has crashed because it attempted to access privacy-sensitive data without a usage description.  The app's Info.plist must contain an NSMicrophoneUsageDescription key with a string value explaining to the user how the app uses this data.

Have created a PR. Looks like a simple fix :)
