### ISSUE TITLE
Replace in-app FAQ with (opening) web-based version

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#2670]
Supersedes #1663

**Comment by colourfreak** [comment]
Isn't it already implemented? 

![faq](https://user-images.githubusercontent.com/51817359/112592459-4ac05a00-8e06-11eb-9c3e-a6a003eb5f05.gif)

**Comment by hboon** [comment]
@colourfreak Haha. I forgot!

**Comment by hboon** [comment]
Already implemented in #2588
