### ISSUE TITLE
Add Wallet Naming feature in Settings

### ISSUE THREAD

**Issue by colourfreak** [AlphaWallet/alpha-wallet-ios#2679]
<img width="1574" alt="Screenshot 2021-03-29 at 15 22 47" src="https://user-images.githubusercontent.com/51817359/112843273-b6265800-90a2-11eb-8218-0465dcc854ee.png">

https://zpl.io/blKKYB0

**Comment by hboon** [comment]
Vlad, remember that the function is already available when we long press a cell in `AccountsViewController`, so let's keep it consistent, but we might remove the long press version later.

**Comment by hboon** [comment]
@colourfreak in the screenshots, when does the "min. 5 characters" and "Save Name" button appear?

**Comment by vladyslav-iosdev** [comment]
@hboon i suppose this one could be closed, isn't?

**Comment by hboon** [comment]
@vladyslav-iosdev yes it should be.
