### ISSUE TITLE
Use AlphaWallet tokenicon resource

### ISSUE THREAD

**Issue by JamesSmartCell** [AlphaWallet/alpha-wallet-ios#2680]
name: Improvement
about: Scan the AlphaWallet token icon repo for icons
---

When scanning for icons, also include the AlphaWallet iconassets:

```"https://raw.githubusercontent.com/alphawallet/iconassets/master/" + TOKEN ADDRESS (eg 0x123456...) + "/logo.png"```

This will allow us to add icons for rapid prototyping, testing etc. There are already a few icons in there.

We get a good rep from our friends at Artis, this is also so we can add their token icon in - which isn't in the Trust icon database.

**Comment by hboon** [comment]
@JamesSmartCell is this still intended for testnets only? (because it's already supported for testnets listed in https://github.com/alphawallet/iconassets#iconassets).

**Comment by JamesSmartCell** [comment]
@hboon No it should be a fallback from any network. If an asset isn't found in the checked places we try the icon here. I used it to add the icon for MIVA into Alphawallet, which sits on xDai network. It's not in the Trust repo that we usually use.

https://github.com/AlphaWallet/alpha-wallet-android/pull/1806

**Comment by JamesSmartCell** [comment]
You may ponder .. isn't there an attack vector there? That is, say there's a contract on xDai with the same address as a contract in Ropsten, if neither are in the Trust DB then won't these look the same?

Yes, you would be right, but the contract address is deterministic; it's a cryptographic interaction between the private key and the nonce; so if I deploy a contract on xDai with nonce 3, and do the same on Ropsten then I get the same address.

If the contract address is the same, then it was deployed by the same private key, so has the same owner.

It's very convenient for eg Hackathons etc to have this infrastructure.
