### ISSUE TITLE
Make 'Testnet' more obvious and separated from 'Mainnet'

### ISSUE THREAD

**Issue by colourfreak** [AlphaWallet/alpha-wallet-ios#2710]
**Clickable prototype:**
https://invis.io/GU10Q3YYSZB7

**Zeplin:**
https://zpl.io/254Zpjo

1. You have a toggle to enable Testnets. This toggle disables Mainnet and enable Testnet. And other way around. Only one can be enabled at the time. 
2. After you hit the toggle, it warns you about what testnets are
4. We say that they have no value at all time.

![testnet_flow](https://user-images.githubusercontent.com/51817359/114658680-8f972c80-9cf2-11eb-957f-df0e2a09f8cf.jpg)

**Comment by AW-STJ** [comment]
#3 would not be relevant right, as the mainnet tokens would be hidden when testnet is selected

**Comment by colourfreak** [comment]
Update:

- When you are viewing a Wallet in a Testnet, all Mainnet tokens are hidden. 
- You have a special link that on tap shows a modal explaining "Where are my Tokens?"
- You can go to "Switch to Mainnet" which will go to Select Active Networks again

![testnet_flow](https://user-images.githubusercontent.com/51817359/114668204-bd836d80-9d00-11eb-9bf9-5c1c2e646f3c.jpg)

**Comment by colourfreak** [comment]
Well done!
