### ISSUE TITLE
Allow Private Key and JSON Keystore export for wallets created in AlphaWallet

### ISSUE THREAD

**Issue by AW-STJ** [AlphaWallet/alpha-wallet-ios#2719]
Metamask has removed the option to import wallet using seed phrase. Now only allows private key or JSON import.
https://metamask.zendesk.com/hc/en-us/articles/360015489331-How-to-import-an-Account

Private key export had been a feature requested several times by users, now without this feature, it is a massive loss of control for users, new and experienced users alike. 
- I was talking to a new user in crypto (5 days experience) today, who wanted to import our wallet to Metamask and was not able to do it.
- Some of the experienced users have mentioned that the ability to export private key is a make or break decision while choosing a wallet. 

@colourfreak - do we have designs for this?

**Comment by colourfreak** [comment]
Zeplin:
https://zpl.io/V1A8qDQ

Go to Settings -> Advanced -> Export JSON Keystore

![export_to_json_android](https://user-images.githubusercontent.com/51817359/125928436-00979ed6-7452-4f5f-b1da-f00f9bad9415.jpg)

**Comment by hboon** [comment]
Refer to https://github.com/AlphaWallet/alpha-wallet-android/issues/1809

**Comment by hboon** [comment]
@eviltofu this would need some context. But would still be useful if you help to build the UI first. So basically:

- [ ] Add an item to the end of the Settings > Advanced screen
- [ ] Followed by 2 new screens

**Comment by eviltofu** [comment]
I always wonder why the final save button is always at the bottom. When I'm entering a form with text fields, the keyboard is often up. So I have to dismiss the keyboard then scroll down and hit the save button. Can the save button be positioned in the upper right hand corner?

**Comment by eviltofu** [comment]
@colourfreak when I try `https://zpl.io/V1A8qDQ`, Zeppelin says I'm not invited to this project. Email invite to eviltofu@gmail.com.

**Comment by eviltofu** [comment]
@colourfreak I scrolled through the Zeplin dashboard and found the screens.

https://zpl.io/bLJwNyJ
https://zpl.io/VOyWBZL
https://zpl.io/aBPEOrA
https://zpl.io/bJLKNr6
https://zpl.io/blemNgX

**Comment by hboon** [comment]
> I always wonder why the final save button is always at the bottom. When I'm entering a form with text fields, the keyboard is often up. So I have to dismiss the keyboard then scroll down and hit the save button. Can the save button be positioned in the upper right hand corner?

Good point. I think it's mainly legacy reasons. But this one should be coordinated across the app and some screens might not have that space available (or we decide to do it per-screen). Better to keep it separate. Create an issue?

**Comment by eviltofu** [comment]
@hboon From a design perspective, should the view controllers of the two new screens have their own single coordinator OR can the SettingsCoordinator handle this?

**Comment by hboon** [comment]
Separate if feasible.

**Comment by eviltofu** [comment]
> Separate if feasible.

I will make the Export JSON keystone process have their own coordinator.

**Comment by hboon** [comment]
Needs #3550
