### ISSUE TITLE
Add Harmony ONE as a custom network - fully EVM compatible

### ISSUE THREAD

**Issue by lijiang2087** [AlphaWallet/alpha-wallet-ios#2722]
name: adding Harmony ONE as a custom network
about: https://docs.harmony.one/home/network/wallets/browser-extensions-wallets/metamask-wallet

---

Network Name
Harmony Mainnet

New RPC URL
https://api.harmony.one

Chain ID
(use number only)
Shard 0: 1666600000

Currency symbol (optional)
ONE

Block Explorer URL (optional)
https://explorer.harmony.one/#/

![image](https://user-images.githubusercontent.com/3784595/115309463-2e6fbe80-a121-11eb-840c-aadf5a4ba5b6.png)

**Comment by lijiang2087** [comment]
our logos in svg: https://drive.google.com/drive/u/0/folders/1Y0r5KvRygXNZvLBDTIJTCElEi_ellMsG?ths=true

**Comment by zhangzhongnan928** [comment]
logos https://drive.google.com/drive/u/0/folders/1Y0r5KvRygXNZvLBDTIJTCElEi_ellMsG?ths=true

**Comment by hboon** [comment]
@lijiang2087 is there an endpoint for fetching transaction history for a wallet? E.g Etherscan has this for Ethereum mainnet:

curl "https://api-cn.etherscan.com/api?action=txlist&address=0x007bEe82BDd9e866b2bd114780a47f2261C684E3&endblock=999999999&module=account&sort=desc&startblock=1"

**Comment by hboon** [comment]
@lijiang2087 I can fetch the balance for a random wallet. Is there somewhere I can get some test tokens to verify sending works? I tried:

* https://faucet.pops.one
* https://onefaucet.ibriz.ai

My wallet address is 0x007bEe82BDd9e866b2bd114780a47f2261C684E3

**Comment by hypnagonia** [comment]
@hboon hello. you can use explorer https://explorer.harmony.one/ to check transfers

**Comment by potvik** [comment]
You can get BUSD/LINK tokens for testnet here https://testnet.bridge.hmny.io/get-tokens

**Comment by potvik** [comment]
other way https://docs.harmony.one/home/developers/smart-contracts/deploy-hrc20

**Comment by hboon** [comment]
Balance
---
I randomly picked an address and checked its balance:

https://explorer.harmony.one/#/address/one1x8lteqz8qaqu308xt02srcg42d86pe89ercncr?txType=regular which says "ONE Balance" = 8452.4469 as of writing

Clicking to get the ETH-compatible address: 0x31FEbc80470741C8BCE65bd501e115534FA0e4e5 and made an RPC call:

```
curl -H 'content-type: application/json' --data-binary '{"jsonrpc":"2.0","method":"eth_getBalance","params":["0x31FEbc80470741C8BCE65bd501e115534FA0e4e5","latest"],"id":1}' 'https://api.harmony.one/'
```

> {"jsonrpc":"2.0","id":1,"result":"0x2d7d8b274767768e9"}

Giving:

```
52.446865673816596 #ruby: p "0x2d7d8b274767768e9".to_i(16) / 10.0**18
```

Did I misunderstood something?

Transaction History
---

Is there a way/endpoint to retrieve the transaction history so we can display them in the Transactions tab? Similar to the ones offered by Etherscan https://github.com/AlphaWallet/alpha-wallet-ios/issues/2722#issuecomment-824567482 ?

**Comment by hboon** [comment]
@potvik just following up on this, any ideas about the above?

**Comment by hboon** [comment]
Close due to inactivity
