### ISSUE TITLE
Add SNAFU erc20 token on your token list

### ISSUE THREAD

**Issue by Agilulfo1820** [AlphaWallet/alpha-wallet-ios#2723]
Hello, we would like our users to be able to manage their $SNAFU token on your wallet.

Those are the specifics:

Network: xDai
Token Address: 0x27B9C2Bd4BaEa18ABdF49169054c1C1c12af9862
Ticker: SNAFU
Decimals: 18
Logo: https://gateway.pinata.cloud/ipfs/QmYFnC1RxAvNzWFmtR5CQYWBz8pgzDidqQKg8o1WVqppEq

More about SNAFU: https://nftsnafu.org

**Comment by hboon** [comment]
@Agilulfo1820 we don't have a pre-defined token list in-app at the moment. Instead, the app will attempt to detect and display tokens which the users own. But depending on how the transactions are crafted, or if the user don't already own it yet, this doesn't always work so users can add the token themselves by tapping "Add / Hide Tokens" in the Wallet tab and pasting in the token contract address, and the app will detect the details like the symbol and decimals.

We will add the logo so it shows up correct though. This will require an update. We haven't implemented this feature yet, but will so: #2680

**Comment by Agilulfo1820** [comment]
Ok thanks, my bad. Support was saying to create this PR to add the token to the "popular" list. 

It would be great if you could add the token logo tough!

**Comment by hboon** [comment]
> We will add the logo so it shows up correct though. This will require an update. We haven't implemented this feature yet, but will so: #2680

@Agilulfo1820 this feature has now completed and will be included in the next update.
