### ISSUE TITLE
Update the 'insufficient gas' error messages to refer to the correct native token

### ISSUE THREAD

**Issue by AW-STJ** [AlphaWallet/alpha-wallet-ios#2726]
The error message refers to 'Not enough Ether to pay for gas', when the transaction is in Heco network. The error message should be 'Not Enough HT to pay for gas'.

We would need to make sure that the correct native currency is referred to in the error message to avoid confusion. Also will have to remove the 'Buy' option for the currencies that Ramp does not support on-ramp.

![image](https://user-images.githubusercontent.com/61957841/115657250-eac3c180-a379-11eb-9e44-72f936fff0a7.png)

**Comment by hboon** [comment]
Will have to update the symbol, but the Buy button actually opens a slightly different screen if it's not supported by Ramp.
