### ISSUE TITLE
tornado.cash: Tapping AlphaWallet after Connect doesn’t seem to do anything

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#2743]

**Comment by vladyslav-iosdev** [comment]
@hboon i suppose there was a problem on `tornado.cash` side. a few days ago i was trying to reproduce this issue, and i wasn't able to sign in. for me it was as described in the issue title. but currently selection on alphaWallet connects wallet to the app.

**Comment by hboon** [comment]
@vladyslav-iosdev if you are saying it currently works but wasn't a few days ago, then yeah, let's close this.
