### ISSUE TITLE
WalletConnect keeps loading when connecting to a DApp.

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/alpha-wallet-ios#2744]
WalletConnect keeps loading when connecting to a DApp.
Only A refresh of the dapp website and a restart of AlphaWallet will solve it.

**Comment by hboon** [comment]
@zhangzhongnan928 this is with dapps that usually work with WalletConnect + AlphaWallet, right?

**Comment by hboon** [comment]
Duplicate of #3275
