### ISSUE TITLE
[Samoa] Modify the Activity sub-tab in token screen to show relevant Activities instead, with the correct UI and data 

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#2749]
Refer to umbrella issue: #2747

**Comment by vladyslav-iosdev** [comment]
@hboon can u provide more details how activities should be filtered for displaying in activity tab?

**Comment by hboon** [comment]
Oh. Sorry. Not the 3 recent ones,  it activities related to that token or native token(eth). So probably just by contract?

**Comment by hboon** [comment]
@vladyslav-iosdev maybe if we can reuse the ActivitiesVC and coordinator sill be good because it already handles the grouping and indentation for swaps etc.

**Comment by vladyslav-iosdev** [comment]
yep, i did it in way u described, but there is one issue for filtering activities for nativecrypto

**Comment by vladyslav-iosdev** [comment]
need to fix it

**Comment by hboon** [comment]
Heads-up, I'm fixing/modify swap display in the Activity tab. But probably wouldn't affect this PR. Hopefully :)
