### ISSUE TITLE
Dapp shows "Switch your network"

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/alpha-wallet-ios#2758]
DApp: https://omni.xdaichain.com/bridge
It works fine in Metamask Trust and imtoken.
But in AlphaWallet, it shows "Switch your network", no matter the browser is connected to Ethereum or xDai.
![IMG_3121](https://user-images.githubusercontent.com/33795543/118203241-fb5de800-b49e-11eb-8dc1-b7ea0a8e956b.PNG)

**Comment by hboon** [comment]
@vladyslav-iosdev if you are up for some JavaScript fun. Otherwise assign it back to me :)
