### ISSUE TITLE
Back button for fungible token screen doesn't work like native

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#2765]
In the fungible token screen (screenshot), tapping the back button doesn't show a list of (1) view controllers in the navigation stack. Also panning from the left edge of the screen doesn't go back.

It looks like it's because of https://github.com/AlphaWallet/alpha-wallet-ios/blob/5aefc4eee83bf4e0926031ecfcc0b54f5ab6bec9/AlphaWallet/Tokens/Coordinators/SingleChainTokenCoordinator.swift#L400

It looks like it's for ee701f1959384b81cf3de777c16d13e3ea5afe06. Do we still need it?

<img width='200' src='https://user-images.githubusercontent.com/56189/118435351-69114a80-b711-11eb-8ffe-679c51aff0df.png'>

**Comment by vladyslav-iosdev** [comment]
@hboon do we still need this issue?

**Comment by hboon** [comment]
Nah, let's close it.
