### ISSUE TITLE
Tokens not auto-detected on Polygon

### ISSUE THREAD

**Issue by colourfreak** [AlphaWallet/alpha-wallet-ios#2776]
**Describe the bug**!
Tokens on Polygon does not show up automatically even with a positive balance. 
Tokens are missing icons that will differentiate them from the Mainnet. 

**Steps to reproduce (REQUIRED)**
Steps to reproduce the behavior

1. Enable Polygon Network
2. Swap Matic (on Polygon) to DAI (on Polygon)
3. DAI does not show up

**Expect**
6a. Auto-display tokens with positive balance on Polygon
Display token icons

YFI
0xDA537104D6A5edd53c6fBba9A898708E465260b6
https://zpl.io/bW85XGj
![YFI](https://user-images.githubusercontent.com/51817359/118626588-49d6f380-b7cb-11eb-8f31-e3d586551a74.png)

WRX
0x72d6066F486bd0052eefB9114B66ae40e0A6031a
https://zpl.io/VQNz1yx
![WRX](https://user-images.githubusercontent.com/51817359/118626678-5f4c1d80-b7cb-11eb-9415-3c1d020ba0b9.png)

WMATIC
0x0d500B1d8E8eF31E21C99d1Db9A6444d3ADf1270
https://zpl.io/bJDB1dJ
![WMatic](https://user-images.githubusercontent.com/51817359/118628126-9d960c80-b7cc-11eb-82ba-ca58762b649a.png)

WBTC
0x1BFD67037B42Cf73acF2047067bd4F2C47D9BfD6
https://zpl.io/VOvr13L
![WBTC](https://user-images.githubusercontent.com/51817359/118628229-b69ebd80-b7cc-11eb-80b2-44a32d50d124.png)

UNI
0xb33EaAd8d922B1083446DC23f610c2567fB5180f
https://zpl.io/a3EG9GN
![UNI](https://user-images.githubusercontent.com/51817359/118628295-c3bbac80-b7cc-11eb-9386-02643dd14aa3.png)

USDC
0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174
https://zpl.io/VDg81ke
![USDC](https://user-images.githubusercontent.com/51817359/118628319-c918f700-b7cc-11eb-9f87-86f5aac93107.png)

USDT
0xc2132D05D31c914a87C6611C10748AEb04B58e8F
https://zpl.io/be3mWdD
![USDT](https://user-images.githubusercontent.com/51817359/118628419-e057e480-b7cc-11eb-932b-b92c3a22cb8a.png)

UBT
0x7FBc10850caE055B27039aF31bD258430e714c62
https://zpl.io/2j3OWrO
![UBT](https://user-images.githubusercontent.com/51817359/118628459-e8b01f80-b7cc-11eb-8d0e-76801df69254.png)

TEL
0xdF7837DE1F2Fa4631D716CF2502f8b230F1dcc32
https://zpl.io/bz3pLB3
![TEL](https://user-images.githubusercontent.com/51817359/118628546-fd8cb300-b7cc-11eb-9278-38980a619c8e.png)

SWAP
0x3809dcDd5dDe24B37AbE64A5a339784c3323c44F
https://zpl.io/2v3QPz7
![SWAP](https://user-images.githubusercontent.com/51817359/118628602-0bdacf00-b7cd-11eb-9a6e-cfbb7ee54427.png)

QUICK
0x831753DD7087CaC61aB5644b308642cc1c33Dc13
https://zpl.io/bPER1km
![QUICK](https://user-images.githubusercontent.com/51817359/118628625-1006ec80-b7cd-11eb-92fe-788e2de58bb5.png)

LINK
0x53E0bca35eC356BD5ddDFebbD1Fc0fD03FaBad39
https://zpl.io/VYqDXjw
![Link](https://user-images.githubusercontent.com/51817359/118628639-14330a00-b7cd-11eb-94ad-02a2a2b9e837.png)LEND
0xD16937941BD94Bd00050B21E2C1308DB6B89B485

HEX
0x23D29D30e35C5e8D321e1dc9A8a61BFD846D4C5C
https://zpl.io/2j3O7jW
![HEX](https://user-images.githubusercontent.com/51817359/118628653-19905480-b7cd-11eb-8045-b441359ec4b1.png)

COMP
0x8505b9d2254A7Ae468c0E9dd10Ccea3A837aef5c
https://zpl.io/bl3B6Gz
![COMP](https://user-images.githubusercontent.com/51817359/118627950-6d4e6e00-b7cc-11eb-9923-da78eaf4e771.png)

DAI
0x8f3Cf7ad23Cd3CaDbD9735AFf958023239c6A063
https://zpl.io/am3JWp9
![Dai](https://user-images.githubusercontent.com/51817359/118626886-8a367180-b7cb-11eb-9564-e74809ecc75d.png)

MATIC
0x0000000000000000000000000000000000001010
https://zpl.io/aNxW109
![Matic](https://user-images.githubusercontent.com/51817359/118627886-60317f00-b7cc-11eb-92ac-93424926c632.png)

**Screenshots**
<img width="789" alt="Screenshot 2021-05-18 at 11 10 10" src="https://user-images.githubusercontent.com/51817359/118624674-a46f5000-b7c9-11eb-8ed4-91f2fffabf2c.png">

**Comment by colourfreak** [comment]
Do I have to refresh, reinstall, reimport to see this?

**Comment by hboon** [comment]
> Do I have to refresh, reinstall, reimport to see this?

@colourfreak I just released the title of the issue only reflects 1 of the problem. Re-opening:

- [x] Update Polygon Token Icons — they should just appear with the new version without having the reinstall. Maybe restart will help.
- [ ] Tokens on Polygon not appearing — will check.

**Comment by colourfreak** [comment]
@hboon You can check out my wallet and tokens that are displayed and not.

https://explorer-mainnet.maticvigil.com/address/0x80cc263cb3fA1bE2AeC748b3811261c1E2a1ba8d/tokens

**Comment by hboon** [comment]
It wouldn’t because there was no way to fetch transaction history (and hence detect tokens) currently. Coming soon.
