### ISSUE TITLE
KNC token Migration

### ISSUE THREAD

**Issue by ssreelekhya** [AlphaWallet/alpha-wallet-ios#2779]
Hello Team,

KNC token is undergoing a migration and upgrade, KNC migration is an important step forward in our Kyber 3.0 journey. 
It would be great if you could support this migration.
New KNC smart contract address: 0xdeFA4e8a7bcBA345F687a2f1456F5Edd9CE97202
For further information, please refer to the following: [KNC Token Migration Guide](https://blog.kyber.network/knc-token-migration-guide-fda08bfe62c2)

**Comment by colourfreak** [comment]
https://github.com/AlphaWallet/alpha-wallet-android/issues/1848

Done
