### ISSUE TITLE
add a new network support, Optimism 

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/alpha-wallet-ios#2792]
https://community.optimism.io/docs/

**Comment by hboon** [comment]
@zhangzhongnan928 We can add it as a chains like other chains. But is there value, in the short term, if we figure out L1-L2 bridging and how it might be immediately useful for users?

**Comment by zhangzhongnan928** [comment]
> @zhangzhongnan928 We can add it as a chains like other chains. But is there value, in the short term, if we figure out L1-L2 bridging and how it might be immediately useful for users?

Yes, 
1. they are launching in June, it is the most important L2, many people will want to try, plus Uniswap SNX and many other DApp already on it.
2. AutographNFT will be deployed on it.
