### ISSUE TITLE
'Approve' activity not displayed

### ISSUE THREAD

**Issue by AW-STJ** [AlphaWallet/alpha-wallet-ios#2799]
I was testing out #2746 and found that I could not see Approve transactions in my Activity.

![image](https://user-images.githubusercontent.com/61957841/119425437-b8c3c780-bd4a-11eb-9a1e-2b07ecdbb646.png)

Build: 3.23(389)
Networks Affected: All including mainnet
Wallet in screenshot: 0xfCABe3451aC8EDfB8FB6b9274C2E095D9cCC8082 (Ethereum)

**Comment by hboon** [comment]
Should be fixed by #2777 and #2791. Merged but not on TestFlight yet.
