### ISSUE TITLE
Upgrade to universal NFT support

### ISSUE THREAD

**Issue by JamesSmartCell** [AlphaWallet/alpha-wallet-ios#2800]
### This is the implementation used in Android to fully support NFT on every chain with Etherscan, Blockscout and 'Polygon/Matic' APIs.

(note: Etherscan, Blockscout and Matic do things in slightly different ways, all of which affect us)

You will already be familiar with the 'tokentx' route provided by Etherscan:

```https://api-kovan.etherscan.io/api?module=account&action=tokentx&startBlock=1&address=0xa20efc4b9537d27acfd052003e311f762620642d&page=1&offset=100&sort=asc```

You may be familiar with the equivalent route for NFT transfers:

```https://api-rinkeby.etherscan.io/api?module=account&action=tokennfttx&startBlock=1&address=0xa20efc4b9537d27acfd052003e311f762620642d&page=1&offset=100&sort=asc```

Note the action= 'tokennfttx' replaces 'tokentx' to get NFT transfers in Etherscan. Blockscout and Matic don't have the 'tokennfttx' route, they lump all NFT and FT transfers together. Fantom supports both the Etherscan routes, see below.

If you examine the dump from the above route you may see that each unit looks like this:
```{
  "blockNumber": "8365144",
  "timeStamp": "1617710811",
  "hash": "0x06b9393c50186cbde6edc5f4e751145aca005ee7b14af6609b0c95885e438a9c",
  "nonce": "7",
  "blockHash": "0x7ddc3ed5d76d28fa94181279839d8d61d2ef27cb91f7753dfbd0d523ab24d962",
  "from": "0x0000000000000000000000000000000000000000",
  "contractAddress": "0xa567f5a165545fa2639bbda79991f105eadf8522",
  "to": "0xa20efc4b9537d27acfd052003e311f762620642d",
  "tokenID": "4",
  "tokenName": "Stormbird Art Contract",
  "tokenSymbol": "SART",
  "tokenDecimal": "0",
  "transactionIndex": "15",
  "gas": "432000",
  "gasPrice": "1000000000",
  "gasUsed": "147866",
  "cumulativeGasUsed": "2961783",
  "input": "deprecated",
  "confirmations": "279448"
}
```

Note that we have ```tokenId``` in the transfer description above. For Blockscout and Matic chains, to distinguish an NFT transfer from a normal FT transfer you see if there's a ```tokenId``` or a ```value``` respectively. (Note/TODO: find out what an ERC1155 transfer looks like; it should contain both tokenId and value.)

Providing we parse the transfers in ascending order, and knowing our wallet address we can detect transfer to and transfer from our account. By summing the transfer-to and transfer-from we can maintain a token balance.

Once you have the token balance; for any tokenId that doesn't yet have a metadata description (ie the ```name```,```image_url```,```description``` you normally get from Opensea), you need to fetch this:

```
    // call contract: function tokenURI(uint256 tokenId) public returns (string)
    private static Function getTokenURI(BigInteger tokenId)
    {
        return new Function("tokenURI",
                Arrays.asList(new Uint256(tokenId)),
                Arrays.<TypeReference<?>>asList(new TypeReference<Utf8String>() {}));
    }

    // call contract: function uri(uint256 tokenId) public returns (string)
    private static Function getTokenURI2(BigInteger tokenId)
    {
        return new Function("uri",
                Arrays.asList(new Uint256(tokenId)),
                Arrays.<TypeReference<?>>asList(new TypeReference<Utf8String>() {}));
    }
```

```
String responseValue = callSmartContractFunction(web3j, getTokenURI(tokenId), getAddress(), getWallet());
if (responseValue == null) responseValue = callSmartContractFunction(web3j, getTokenURI2(tokenId), getAddress(), getWallet());
        JSONObject metaData = loadMetaData(responseValue);
```
The result from the call to getTokenURI or uri (whichever works for the token) should be JSON and should look vaguely like this:
```
{
   "image":"http://james.lug.org.cn/tokenimage/fafa5a175353f72dccedb7e5ff6b5c92",
   "name":"Buena Vista Social Club",
   "description":"slightly overrated."
}
```

Note that some ERC721 follows the openZeppelin ```tokenURI``` standard, and some implement the, presumably legacy, ```uri```. Since ```tokenURI``` seems to be a lot more common we try that first. the legacy version is used by a lot of artworks for sale on opensea, so we should support it.

For supporting blockscout chains, eg Eth Classic, xDai (which has a big NFT following) you would just use the normal ```tokentx``` route:

```https://blockscout.com/poa/dai/api?module=account&action=tokentx&startBlock=2&address=0xa20efc4b9537d27acfd052003e311f762620642d&page=1&offset=100&sort=asc```

For Polygon/Matic and Fantom Mainnet (Fantom testnet is not currently supported - it is only supported by covalent), the route looks like this:

Matic Testnet (Mumbai):

```https://explorer-mumbai.maticvigil.com/api/v2/transactions?module=account&action=tokentx&startBlock=13123851&address=0xa20efc4b9537d27acfd052003e311f762620642d&page=1&offset=100&sort=asc```

Polygon mainnet:

```https://explorer-mainnet.maticvigil.com/api/v2/transactions?module=account&action=tokentx&startBlock=13123851&address=0xa20efc4b9537d27acfd052003e311f762620642d&page=1&offset=100&sort=asc```

Fantom mainnet. Note: ftmscan *is* Etherscan compatible and supports both ```tokentx``` and ```tokennfttx```, so treat it the same as the Etherscan routes WRT to the two routes:

```https://api.ftmscan.com/api?module=account&action=tokennfttx&startBlock=1&address=0xa20efc4b9537d27acfd052003e311f762620642d&page=1&offset=100&sort=asc```

```https://api.ftmscan.com/api?module=account&action=tokentx&startBlock=1&address=0xa20efc4b9537d27acfd052003e311f762620642d&page=1&offset=100&sort=asc```

Doing things this way means we can support discovery and keep current balance of NFT on almost every chain. Only Avalanche can't be supported like this, yet. There is a covalent route that gives you raw token balances which we can use for the main wallet page and to discover Tokens, but won't provide the receive event - we'd need a generic TokenScript or an event log scanner for that.

I will outline in a different issue how I got the full transaction from covalent (Fantom test, Avalanche and Fuji), together with some chicanery to get transaction and constructor events.

**Comment by hboon** [comment]
@JamesSmartCell do you have an example NFT on Polygon that implements `tokenURI` so I can verify? I tried with a few and they don't. The one we have on Rinkeby works.

**Comment by hboon** [comment]
Helps a lot. Thanks James!
