### ISSUE TITLE
[Samoa] Compute fiat value for each wallet while they are inactive

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#2802]
Not sure how it's possible:

We can either do it

A. The true/right way, be able to compute fiat for each inactive wallet. Seems like a major change
B. Cache the tokens (based on CoinGecko's token ID) and their count somewhere, say a .json file and be able to compute even if it is inactive.

This is going to be used:

- [x] to display the total (across all wallets) in Wallet tab for follow up to #2755
- [x] display total in "list of wallets" tab #2756

**Comment by vladyslav-iosdev** [comment]
@hboon i got few questions according to these changes:
- It seems like we in any case need to perform fetch coin Tikers a few times. For each wallet right?
- so initially we have to create banch of token data stores for each wallet, right?
- we can extract refreshETHBalance() and refreshBalance to separate class, to handle updates there. also do it in background.  What do you think?

- what if we update TokenObject with storing its Tiker, (in DB) like TickerObject, and also we can store history values there, what do you think?
- we can update code base with subscribing for ticker updates, (via realm object observation), it should simplify view updates (drop timers and reload view only if value get updated), what do you think?

**Comment by hboon** [comment]
> It seems like we in any case need to perform fetch coin Tikers a few times. For each wallet right?

Not necessarily, it's possible that we fetch the list of ticker IDs once and the prices for them once, so total 2 calls as long as we know all the ticker IDs and balance across N wallets, rather than 2N (or 1 + N) calls.

> so initially we have to create banch of token data stores for each wallet, right?

Maybe, but not necessarily. As long as we know the ticker IDs and their balance for each inactive wallet, we can compute the fiat total value. The problem I am concerned about with approach A is the app has always assumed one active wallet at a time. If we do it with A, we'll need to open database connections for all the wallets at the same time (or to open-close each set). So could be a concurrency + speed issue and I think we might have had an issue when we opened many database at one time a long time ago. Also quite a bit of dirty code where we initiate fetching etc in TokensDataStore (or the coordinator) which would run, but shouldn't need to run for inactive wallets.

> we can extract refreshETHBalance() and refreshBalance to separate class, to handle updates there. also do it in background. What do you think?
> what if we update TokenObject with storing its Tiker, (in DB) like TickerObject, and also we can store history values there, what do you think?

Might work.

> we can update code base with subscribing for ticker updates, (via realm object observation), it should simplify view updates (drop timers and reload view only if value get updated), what do you think?

I wonder if we should drop Realm at some point though. Either sqlite + a thin wrapper or straight out JSON file(s)? Realm doesn't seem to have brought much benefit for us..

What do you think?

But either way, if you think it wouldn't be too much effort to try it out, you are welcome to code it out and see if it works, as long as you aren't too attached to the idea :)

**Comment by vladyslav-iosdev** [comment]
> I wonder if we should drop Realm at some point though. Either sqlite + a thin wrapper or straight out JSON file(s)? Realm doesn't seem to have brought much benefit for us..

yep, i guess it could simplify some aspects of work. It could be greate if in the start of developing code base be closed in way when instances located in different  layers and changing DB doesn't involve updating whole project.

**Comment by vladyslav-iosdev** [comment]
@hboon  oh, i suppose that i didn't understand how it's going to work. We are going to fetch tickers only for native crypto for selected servers, right? and then calculate its values according their balance (fetched with GetNativeCryptoCurrencyBalanceCoordinator) am i right?

**Comment by hboon** [comment]
Yes, especially since it’s Ethereum. Most of the data (transactions) are immutable. Only the token properties changes. The original database design didn’t take advantage of that. And changes are actually limited to the block time which can be 1s to a few minutes. But never more often (except price) so lots we can tweak to make it better
