### ISSUE TITLE
Add Custom Linking to Quickswap for tokens on Polygon

### ISSUE THREAD

**Issue by colourfreak** [AlphaWallet/alpha-wallet-ios#2808]
#2103 - since Quickswap is a for of Uniswap, we can add custom linking for all tokens on Polygon. 

![Quickswap_AlphaWallet](https://user-images.githubusercontent.com/51817359/119621005-e7eb3f00-be05-11eb-8f8c-664d98f77a63.jpg)

**Comment by AW-STJ** [comment]
When we implement this feature, can we also log the event of using Quickswap for Mixpanel. The event should also capture the token information to understand which tokens are swapped the most using this deeplink.
