### ISSUE TITLE
Should not display fiat value for non-mainnets tokens

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#2811]
Maybe only native crypto on testnets have this problem

<img width="200" alt="Screenshot 2021-05-27 at 10 15 54 PM" src="https://user-images.githubusercontent.com/56189/119842286-22092d80-bf39-11eb-895c-800ae2cd6789.png">

**Comment by vladyslav-iosdev** [comment]
@hboon can provide more details what need to be fixed. not clear for now.

**Comment by hboon** [comment]
Rinkey shouldn’t show 48163 USD in the screenshot since testnet tokens are worthless.
