### ISSUE TITLE
Add a paste button for importing private key and keystore JSON

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#2815]
Since they are all meant to be copy and pasted?

Watch:

<img width="289" alt="Screenshot 2021-05-28 at 3 28 10 PM" src="https://user-images.githubusercontent.com/56189/119946605-62b08780-bfc9-11eb-9f43-fcf6ce6110db.png">

Import private key:

<img width="289" alt="Screenshot 2021-05-28 at 3 28 06 PM" src="https://user-images.githubusercontent.com/56189/119946621-66440e80-bfc9-11eb-9b5d-577d46cef05d.png">

**Comment by colourfreak** [comment]
Yes. Good idea.
