### ISSUE TITLE
Compile Bug

### ISSUE THREAD

**Issue by FullStackDevCoach** [AlphaWallet/alpha-wallet-ios#2821]
name: Compile Bug
about: I've tried compiling / running the project on my XCode 12.4 and XCode 11.7 (As guide)

---
![image](https://user-images.githubusercontent.com/52414598/120101033-cf766f80-c0f8-11eb-9e5c-40678e04d9ac.png)
---

It says - 'export.h' file not found in libsodium pod library.

Looking like there is a trick for it around. Please clear.

**Comment by hboon** [comment]
Tried this?

‘’’

1. Use Xcode 12.x
2. bundle (to get Cocoapods)
3. pod install

Clean in Xcode if it doesn’t work
‘’’

**Comment by FullStackDevCoach** [comment]
1. 12.4
2. bundle success.
3. pod install
4. clean

![image](https://user-images.githubusercontent.com/52414598/120107078-8a206500-c12d-11eb-8c07-8b65784a37f0.png)

Looks like is there something that I am missing? I'm not the only person that faces the issue.

**Comment by hboon** [comment]
Close from inactivity
