### ISSUE TITLE
Support SVG images for ERC721

### ISSUE THREAD

**Issue by JamesSmartCell** [AlphaWallet/alpha-wallet-ios#2822]
Supporting SVG images in ERC721

Why? : Because using SVG you can have animation with overlays done really nicely, and is popular with artists.
Why doesn't it work?: Opensea can't render SVG in its backend, so the thumbnail and preview images will be null, only the 'image_original_url' will show correctly, or you'll have to load directly from metadata.

How it's solved on Android:

Have a normal imageview and a webview occupying the exact same space, with the webview hidden behind the imageview.
Load using the 3rd party library. If loading of the image fails, then expose the webview, hide the imageview and send this data to the webview:

```
<html>
    <head>
        <style>
        * {
            margin: 0;
            padding: 0;
        }
        .imgbox {
            display: grid;
            height: 100%;
        }
        .center-fit {
            max-width: 100%;
            max-height: 100vh;
            margin: auto;
        }
    </style>
    </head>
    <body>
        <div class="imgbox">
            <img class="center-fit" src='[URL]'>
        </div>
    </body>
</html>
```

Where [URL] is replaced by the original image Url from the opensea or metadata.

**Comment by hboon** [comment]
Closed with #2896 and #2906
