### ISSUE TITLE
MetaMask message spec for Signing

### ISSUE THREAD

**Issue by JamesSmartCell** [AlphaWallet/alpha-wallet-ios#2825]
Currently we're not quite 100% compatible with MetaMask signing spec.

When you form the message to sign you need to check with the following heuristic:

```
var params = [msg, from]  
var method = 'personal_sign'

if (msg is Hexadecimal) encodedMessage = hexToBytes(msg)
else
encodedMessage = msg.getBytes()
```
EG if msg is 'My axe is sharp'
encodedMessage will be  [4D7920617865206973207368617270] (```getBytes()```)
if msg is '0x1234567890abcde'
encodedMessage will be [1234567890abcde]  (```hexToBytes()```)
if msg is 'aabbccddeeff'
encodedMessage will be [aabbccddeeff]

and so on.

These rules also apply to the deprecated sign message.

**Comment by hboon** [comment]
Thanks for the heads-up! Have checked the code. Looks like we already do that (sadly).
