### ISSUE TITLE
Let users add a custom chain

### ISSUE THREAD

**Issue by colourfreak** [AlphaWallet/alpha-wallet-ios#2826]
**Describe the issue**
Let users add a custom RPC, similar to MetaMask

**Steps to reproduce (REQUIRED)**
Steps to reproduce the behavior

1. Open Settings
2. Go to Select Active Networks
3. Click + button
4. Enter Data

Zeplin:
https://zpl.io/aMw5nmz

<img width="1735" alt="Screenshot 2021-05-31 at 14 09 51" src="https://user-images.githubusercontent.com/51817359/120197748-9d146180-c221-11eb-827e-079c7dcffc5c.png">

**Comment by hboon** [comment]
Probably `RPCServer.custom`. Careful to check every reference to `.custom` (good luck, haha).

Take note of the relatively new `RPCServer.getEtherscanURLERC721Events` property.

I think we'll need to have a check right after the user adds a new custom chain to figure out if the URL should behave like `.etherscan` or `.blockscout` and not return `nil` if we can do that. eg. if the URL includes "etherscan.", it must be `.etherscan`, ditto for BlockScout. And if we can't, we'll have to hit it once as ".etherscan" first (so `tokennfttx` is used), parse the result and see if that action (`tokennfttx`) is valid, if it is, record this custom chain as `.etherscan`, if not, record as `.blockscout`, maybe as an associated value to `CustomRPC` (if we still use it).

Let's store and share the list of custom chains across all wallets.

**Comment by colourfreak** [comment]
Alternatively, we can add most of entries from https://chainlist.org/ and let users search for networks.

**Comment by hboon** [comment]
@vladyslav-iosdev hold this first. I'm looking into #2879, so might make the underlying logic changes mention in https://github.com/AlphaWallet/alpha-wallet-ios/issues/2826#issuecomment-851924128. Buzz if you have started on it already.

**Comment by hboon** [comment]
Ok. Can proceed after #2881 is merged. Still has to do the testing described in https://github.com/AlphaWallet/alpha-wallet-ios/issues/2826#issuecomment-851924128 to figure out if it's `.blockscout` or `.etherscan`, but I might get to it first in #2879
