### ISSUE TITLE
Mainnet and Testnets should be mutually exclusive

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#2827]
Noticed this yesterday while working on something else. I don't think the code I was working on caused this: but mainnet and rinkeby native crypto showed up at the same time. Can't reproduce.

<img width='200' src='https://user-images.githubusercontent.com/56189/120278124-77ea2680-c2e7-11eb-97d1-2e753e557c49.PNG'>

**Comment by vladyslav-iosdev** [comment]
@hboon was u able to reproduce it several times?

**Comment by hboon** [comment]
@vladyslav-iosdev no, I only saw it a few times. How do I reproduce it before the PR?

**Comment by vladyslav-iosdev** [comment]
@hboon  actually i don't know how to reproduce it ;) btw, it was after the app was updated with displaying only mainet or testnet tokens, i mean updated on `Settings -> Select Active Networks`?
