### ISSUE TITLE
Add 3 items to Browser's menu

### ISSUE THREAD

**Issue by colourfreak** [AlphaWallet/alpha-wallet-ios#2828]
As discussed.
**Add three items to the menu:**
1. My Bookmarks
2. History
3. Set as Home Page

if you set a new Home Page, show a navigation bar with a Home icon. 
https://zpl.io/2ZwxJJ4
https://zpl.io/awvJ6lj

<img width="1535" alt="Screenshot 2021-06-01 at 09 39 50" src="https://user-images.githubusercontent.com/51817359/120285216-53795480-c2bd-11eb-9e5b-54be9cf8c558.png">

**Comment by hboon** [comment]
@colourfreak  after the user has set a homepage, what happens when they

A. taps on the Browser tab button?
B. when they tap on the new home button?

**Comment by colourfreak** [comment]
A and B take you to the same home page.

**Comment by hboon** [comment]
How do they get to the original “home” which was shown before the user sets their own homepage? Or does the user lose access to it after they do so?

**Comment by colourfreak** [comment]
Then you can open "My Bookmarks" and set it as your new home page. It's will not be the same, but you are not losing access to "History" because it's in the menu. But yes. You lose access to it unless we set it up as a custom URL.

**Comment by hboon** [comment]
Hmm. Ok. Thanks

**Comment by hboon** [comment]
Yes. ERC1155 first
