### ISSUE TITLE
Only display symbol in Wallet tab, i.e. "<symbol>" and no longer "<name> (<symbol>)"

### ISSUE THREAD

**Issue by colourfreak** [AlphaWallet/alpha-wallet-ios#2830]
**Describe the bug**
All Aave tokens have names starting with 
"Aave Interest bearing..." which is redundant in my opinion. 

**Steps to reproduce (REQUIRED)**
Steps to reproduce the behavior

1. Watch tomek.eth to see how does it look

**Expect**
Instead of:
"Aave Interest bearing USDT (aUSDT)" we could have: "aSUDT (aUSDT)"
"Aave Interest bearing USDC (aUSDC)" we could have: "aSUDC (aUSDC)"
"Aave Interest bearing TUSD (aTUSD)" we could have: "aTUSD (aTUSD)"

**Screenshots**
![2021-06-01 09 55 14](https://user-images.githubusercontent.com/51817359/120288341-63466800-c2c0-11eb-8822-f78fbb43425d.png)

**Comment by hboon** [comment]
Implementation:

Let's just hardcode this for now to strip off the prefix: "Aave Interest bearing " and replace it with "a" when displaying them in the Wallet tab and the Show/Hide token screen if token.name is longer than that string + say 3 characters.

@colourfreak once there are a few more of this that are AAVE-related, then let's look at it again and see how we can improve the implementation more generally. i.e. other tokens will continue to have this problem even if a PR for this is merged.

**Comment by colourfreak** [comment]
Do you want me to investigate and give you a list of tokens?

**Comment by colourfreak** [comment]
Looking at BAT at the end of the list, we have the same issue. :)

**Comment by hboon** [comment]
Yeah. If you could, just a mapping table with 2 columns (or arrows, it’s fine) here. Thanks

**Comment by colourfreak** [comment]
@hboon I have an idea. What if instead we only display a name from the brackets?
This way we will make a lot of space for the market price on the right. 

<img width="421" alt="Screenshot 2021-06-02 at 10 20 12" src="https://user-images.githubusercontent.com/51817359/120448839-3cedfe80-c38c-11eb-8bce-8dc975da9242.png">

**Comment by hboon** [comment]
Sure. Let’s go with that. We can fix it if it doesn’t work out well

**Comment by JamesSmartCell** [comment]
This won't always work - I've seen quite a few where they put a long name into the symbol (d'oh!). In general though, it should.

Can we agree on a procedural reduction for longer names?

**Comment by hboon** [comment]
Does those tokens with long symbols come with long names too? We can swap those?

**Comment by colourfreak** [comment]
> This won't always work - I've seen quite a few where they put a long name into the symbol (d'oh!). In general though, it should.
> 
> Can we agree on a procedural reduction for longer names?

What is an example? It sounds like an edge case. So that solution works for the 90%.

**Comment by JamesSmartCell** [comment]
> Does those tokens with long symbols come with long names too? We can swap those?

The name is usually like the symbol should be. I'll locate an example

**Comment by JamesSmartCell** [comment]
> > This won't always work - I've seen quite a few where they put a long name into the symbol (d'oh!). In general though, it should.
> > Can we agree on a procedural reduction for longer names?
> 
> What is an example? It sounds like an edge case. So that solution works for the 90%.

Yes it's more of an edge case, but it's something to be careful of.

**Comment by hboon** [comment]
Superseded by #3182
