### ISSUE TITLE
The Confirm Transaction action sheet does not show up in Matic Bridge

### ISSUE THREAD

**Issue by colourfreak** [AlphaWallet/alpha-wallet-ios#2839]
**Describe the bug**
The Confirm Transaction action sheet does not show up in Matic Bridge. It stays with "Continue" but I can't see the action sheet to confirm. Is this us or the way they badly implemented it?

**Steps to reproduce (REQUIRED)**
Steps to reproduce the behavior

1. Go to a browser
2. Scan the QR code below or open https://wallet.matic.network/bridge/
![QR_Code_1622623776](https://user-images.githubusercontent.com/51817359/120456475-ee456200-c395-11eb-9f95-7aaf9b59435f.png)

3. Metamask
4. Transfer, Continue... 

**Expect**
Expect to see an action sheet where I can confirm the transaction

<img width="1488" alt="Screenshot 2021-06-02 at 11 11 50" src="https://user-images.githubusercontent.com/51817359/120457159-85aab500-c396-11eb-877e-3a2f66f9d101.png">

**Screenshots**
![2021-06-02-111402](https://user-images.githubusercontent.com/51817359/120457054-71ff4e80-c396-11eb-9c13-f71d3341f625.gif)

**Comment by hboon** [comment]
I see this:

<img width="200" alt="Screenshot 2021-06-03 at 6 02 55 PM" src="https://user-images.githubusercontent.com/56189/120627131-f258a900-c495-11eb-8bdc-6a8356c9b5e7.png">

Is this the screen you were expecting to pop up, but didn't? Could be a WalletConnect glitch. Can you try again?

**Comment by hboon** [comment]
Ah. Was checking both this and #2846 and was confused. Just to be clear: #2846 is when connecting with WalletConnect (and seems to work/not work as expected, see the issue for details). Will check why it doesn't work when used from the dapp browser directly.

**Comment by hboon** [comment]
In next TestFlight.
