### ISSUE TITLE
Wallet tab doesn't include which chain a token is on

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#2840]
Would it be confusing and potentially harmful?

(we could wait till someone complains if it doesn't look obviously bad to us now).

![120288341-63466800-c2c0-11eb-8822-f78fbb43425d](https://user-images.githubusercontent.com/56189/120464633-b9560100-c3cf-11eb-857c-9d130ea7a6f9.png)

**Comment by AW-STJ** [comment]
Even though not in Tomek's design, Android shows this information for some tokens (not all of them)

![image](https://user-images.githubusercontent.com/61957841/120567771-d59c8100-c455-11eb-9ada-760393849e17.png)

> Would it be confusing and potentially harmful?

It is confusing,  so making the token's network easily identifiable will add a lot more clarity to the user.

**Comment by colourfreak** [comment]
What about we just use the same separator like anywhere else and group tokens based on network?

<img width="1157" alt="Screenshot 2021-07-08 at 11 34 09" src="https://user-images.githubusercontent.com/51817359/124899897-da1e0180-dfe0-11eb-8fe3-67641d2d1a0f.png">

So we will have token icons (already provided) plus this separation. No need to add anything else.

**Comment by hboon** [comment]
> What about we just use the same separator like anywhere else and group tokens based on network?

Sounds good.

**Comment by hboon** [comment]
Created #2957
