### ISSUE TITLE
Add token icon(s) for Optimism mainnet

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#2844]
Optionally, Optimism Kovan (testnet) too.

Follow up to #2841

**Comment by colourfreak** [comment]
Do you mean ERC20 tokens with a small Optimism logo (similar to what we have done for BSC, HECO, xDAI, Polygon)?

**Comment by hboon** [comment]
Same format but not for ERC20 tokens. Like the blueish ETH token. So can’t upload it to the icon repo because it has to be hardcoded into the app. In other words, exactly 1 for mainnet and 1 for testnet (if we want).

But you could create icons for prominent ERC20 tokens on Otpimisim too if you like. Those can be added to the repo like you did yourself.

**Comment by colourfreak** [comment]
Mainnet
https://zpl.io/V0rxme9

Kovan
https://zpl.io/b6APmNy

**Comment by colourfreak** [comment]
I added SNX, sUSD and ETH Optimism tokens to our iconassets

**Comment by hboon** [comment]
Thanks!

**Comment by hboon** [comment]
Re-opening so I remember to add them to the app
