### ISSUE TITLE
Below "Hidden Tokens" add another section called "Popular Tokens" 

### ISSUE THREAD

**Issue by AW-STJ** [AlphaWallet/alpha-wallet-ios#2845]
Below "Hidden Tokens" add another section called "Popular Tokens" where we list the top 20 most popular erc20 tokens. https://zpl.io/2j0gqPA

**Comment by vladyslav-iosdev** [comment]
@hboon what source can i use to retrieve tokens?

**Comment by hboon** [comment]
@vladyslav-iosdev away from computer now. You can try look for the corresponding Android issue. It should be quite a while back. Otherwise I’ll look it up later

**Comment by hboon** [comment]
You can find a list here for Ethereum mainnet [1]. Looks way longer than 20. But let's just start with this now. Look for those that are `"isPopular": true`. Remember to hide them if they are already in the user's database. Probably just hardcode them for now. But in the future, we ought to be pulling token lists from else where then we'll probably move to whatever external file format they are using (if there's a specific one).

[1] https://github.com/AlphaWallet/alpha-wallet-android/blob/fa86b477586929f61e7fefefc6a9c70de91de1f0/app/src/main/assets/known_contract.json

**Comment by vladyslav-iosdev** [comment]
@hboon  how things should done for contracts that don't have a name?

**Comment by hboon** [comment]
@vladyslav-iosdev can you give an example? If it doesn’t have a name, seems unlikely it’s a popular token. You can just add those with names.

**Comment by vladyslav-iosdev** [comment]
<img width="1109" alt="Screenshot 2021-06-07 at 11 25 41" src="https://user-images.githubusercontent.com/55975226/120984214-1dd3e000-c783-11eb-815f-7c4cbcb18bc5.png">
as u can see there are some tokens in json file that don't have a name. For now i applied filter for non empty names.  BTW when we call fetchContractData for token  it returns its actual name. do i need to update json with this info?

**Comment by vladyslav-iosdev** [comment]
nevermind, i am going to fetch all contracts data (with empty name in json) and then just update json file.

**Comment by hboon** [comment]
Great :) yeah. Up to you unless it’s something that is hard to undo and you aren’t sure.

**Comment by hboon** [comment]
I noticed a reference to "https://raw.githubusercontent.com/AlphaWallet/alpha-wallet-android/fa86b477586929f61e7fefefc6a9c70de91de1f0/app/src/main/assets/known_contract.json" as well as the same file being bundled. Are they duplicates?
