### ISSUE TITLE
Header for "parent" transactions

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#2850]
@colourfreak I remember we talked about showing Swap or Contract Interactions for "parent" transactions [1] and I thought we did have a design for grouping transactions or was discussing about one.

But we manage to pull and display more transactions now (more in the next build). Would you help do up something to replace the "Contract Execution" label in this screenshot without touching the rest as a stopgap so we can ship with that first, without completing #2505 

The label might read "Swap" or "Contract Execution" depending on the internal transactions following it.

[1] https://github.com/AlphaWallet/alpha-wallet-ios/issues/2505

**Comment by hboon** [comment]
Forgot the screenshot:

<img width="200" alt="Screenshot 2021-06-04 at 2 56 08 PM" src="https://user-images.githubusercontent.com/56189/120766020-62c20180-c54c-11eb-9488-02367edac096.png">

**Comment by colourfreak** [comment]
For clarity, I created the Activity tab prototype in Invision.
https://invis.io/KU114ACT6GCT#/453107113_01_Activity
