### ISSUE TITLE
Check and switch if other blockchain explorer sites supports "/token/<address>" like Etherscan does for mainnet

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#2852]
In `RPCServer.etherscanTokenDetailsWebPageURL`, we handle `.main` differently because they support "/token/<address>" in addition to "/<address>" or "/<search>". The "/token" page is better than "/<address>". Check if other services supports it

Example, compare https://cn.etherscan.com/token/0xdac17f958d2ee523a2206206994597c13d831ec7 and https://cn.etherscan.com/address/0xdac17f958d2ee523a2206206994597c13d831ec7

This URL is formed and used when the user tap on the token icon in the screen showing a single token

**Comment by vladyslav-iosdev** [comment]
for now what i found it that url we generating for

**Comment by hboon** [comment]
(That particular address is a EOA/wallet, but that's besides the point though).

How did you get the app to navigate to that URL?

**Comment by hboon** [comment]
The relevant functions are `etherscanContractDetailsWebPageURL()` and `etherscanTokenDetailsWebPageURL()`

**Comment by vladyslav-iosdev** [comment]
i made something like this ;)

**Comment by hboon** [comment]
Oh! 😭  Good catch. Fixed with #2871

**Comment by vladyslav-iosdev** [comment]
Fixed with #2871
