### ISSUE TITLE
Blockscout ignores 'startblock' and 'endblock' in 'tokentx' API route

### ISSUE THREAD

**Issue by JamesSmartCell** [AlphaWallet/alpha-wallet-ios#2855]
Normally we'd limit the tokentx return by using a combination of ```startBlock```, ```endBlock``` and ```offset```, eg:

```https://api-rinkeby.etherscan.io/api?module=account&action=tokennfttx&startBlock=8365174&endBlock=9999999999&address=0xa20efc4b9537d27acfd052003e311f762620642d&page=1&offset=5&sort=asc```

Which should give us 5 transfers starting at block 8365174. This is how etherscan works. Blockscout API would ignore the ```startBlock``` and ```endBlock```, only looking at ```page``` and ```offset```.

Since etherscan also follows the ```page``` and ```offset``` correctly we need to switch to only use these eg:

```https://blockscout.com/poa/xdai/api?module=account&action=tokentx&startBlock=1&endBlock=9999999999&address=0xa20efc4b9537d27acfd052003e311f762620642d&page=2&offset=5&sort=asc```

Gives us transfers 6 to 10 (starting at 1 not zero) (*note: in this actual case it returns zero params but you could substitute the above rinkeby call)*).

In Android we use a heuristic like this to give the best performance:

```
MAX_READ = 200
NORMAL_READ = 5
...
if (first time reading this account or 'max' is set) readFrom = (current_page * NORMAL_READ) / MAX_READ + 1
else readFrom = current_page

read from API -> tokentx page = readFrom, offset = (is max set?) MAX_READ : NORMAL_READ
```

eg - first time reading

```https://api-rinkeby.etherscan.io/api?module=account&action=tokennfttx&startBlock=1&endBlock=9999999999&address=0xa20efc4b9537d27acfd052003e311f762620642d&page=1&offset=200&sort=asc```

gives us 200 transactions, 

```
current_page = old_page + tx_count / NORMAL_READ
```

new page to read from next time is now 41, which is transactions 201 through 205.

The next check cycle we indicate that the previous return was a max count, so it would issue another 'max' check for the next 200 transactions:

```https://api-rinkeby.etherscan.io/api?module=account&action=tokennfttx&startBlock=1&endBlock=9999999999&address=0xa20efc4b9537d27acfd052003e311f762620642d&page=2&offset=200&sort=asc```

This time we only get 29 transactions, so now:

```
current_page = 41 + 29/5 (= 46)
```

The next iteration would be checking transactions 231 -> 235, and it would receive 4 transactions, and so we know it's now fully sync'd:

```https://api-rinkeby.etherscan.io/api?module=account&action=tokennfttx&startBlock=1&endBlock=9999999999&address=0xa20efc4b9537d27acfd052003e311f762620642d&page=46&offset=5&sort=asc```

Doing it this way gives us rapid catch-up and also doesn't consume much network because you have to regularly poll the API, so the NORMAL_READ needs to be as small as possible, since if there's no action we'll be receiving the same transfers over and over. Best to minimise these as much as possible. We could make NORMAL_READ = 1 that way we could get an empty return, and only do subsequent larger reads if we receive anything.

It's not ideal, however I'm not sure how else to optimise this. Maybe you have a better way? If you do, please let me know I'll switch. I didn't want to make it too complex with dynamic calculated amounts.

**Comment by hboon** [comment]
@JamesSmartCell I'm on something else but will check back soon. But just in case you are in the middle of this, try `startblock` and `endblock` (lowercase "b") instead when accessing blockscout.

According to https://blockscout.com/xdai/mainnet/api-docs#account, look for "Get token transfer events by address." Seems to work empirically against Polygon's

**Comment by hboon** [comment]
Actually, referring to Etherscan docs [1], it looks like it should be `startblock` instead of `startBlock` too, but Etherscan allows both to be used. I checked our BC codebase and we use `startblock` too, so it might be just easier to switch everything to lowercase "b" and it'll just work.

[1] eg https://ropsten.etherscan.io/apis#accounts

**Comment by hboon** [comment]
@vladyslav-iosdev FYI.
