### ISSUE TITLE
Showing token unit price instead of the total amount changed

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/alpha-wallet-ios#2894]
![image](https://user-images.githubusercontent.com/33795543/121839692-fbf7d180-cd1d-11eb-921a-72f33bb59f01.jpeg)

I find this number 👆 is useless.
And the UI is missing the very important token unit price. @colourfreak

**Comment by colourfreak** [comment]
In the #2273, I explained what this should be. Maybe not clear enough.

I conducted 3 tests using usabilityhub:
1) https://app.usabilityhub.com/tests/86ec06814d57/results/1f78709fe6f1

<img width="423" alt="Screenshot 2021-07-08 at 11 23 29" src="https://user-images.githubusercontent.com/51817359/124897902-03d62900-dfdf-11eb-82d3-5efc3b1ab081.png">

2) https://app.usabilityhub.com/tests/6076f465a67c/results/590f397ceee6

<img width="427" alt="Screenshot 2021-07-08 at 11 23 39" src="https://user-images.githubusercontent.com/51817359/124897929-09337380-dfdf-11eb-9351-ec1e1bd7a566.png">

3) https://app.usabilityhub.com/tests/bcdef3f68e73/results/420f2f243df1

<img width="347" alt="Screenshot 2021-07-08 at 11 23 49" src="https://user-images.githubusercontent.com/51817359/124897981-151f3580-dfdf-11eb-8eaa-851b94b9a4cf.png">

and the result is that they understand if the number you marked is the ‘24H Price change’ of the ‘how much your 
tokens are worth in USD’ (5% x 1500 USD). This is also the same as Delta app, Zerion App, Blockfolio. So the winner was 2)

@zhangzhongnan928 @hboon 
The trigger to open AlphaWallet and check wallet tab should be: **tell me how much money I gained/lost in last 24h**. There are other tools to check the market prices. And if you are looking for that data, open a token and you will find numbers like ETH price. 

So if **1 ETH = 1000 USD** and the ** ETH price raised by 5%** in last 24H then it should like this:

<img width="1665" alt="Screenshot 2021-07-08 at 11 16 29" src="https://user-images.githubusercontent.com/51817359/124896684-f2d8e800-dfdd-11eb-9b34-11034e9ea2de.png">

**Comment by zhangzhongnan928** [comment]
make sense

**Comment by colourfreak** [comment]
@vladyslav-iosdev Please apply the change from https://github.com/AlphaWallet/alpha-wallet-ios/issues/2894#issuecomment-876282955

**Comment by vladyslav-iosdev** [comment]
@colourfreak will do

**Comment by hboon** [comment]
Can we reopen or create a new issue? Too hard to track orherwisr

**Comment by colourfreak** [comment]
> Can we reopen or create a new issue? Too hard to track orherwisr

https://github.com/AlphaWallet/alpha-wallet-ios/issues/2894#issuecomment-915222932
