### ISSUE TITLE
Implement designed Prompts for EIP3085 wallet_addEthereumChain support

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#2908]
#2907 adds the ability for dapps to request the user's permission to add a custom chain (i.e. the programmatic version of #2826 without the user having to enter anything). But there are a few variations we should show the user, to get their permission.

The 3 screenshots and their titles in https://github.com/AlphaWallet/alpha-wallet-ios/pull/2907#issue-675916998 show the prompts variations. Feel free to change the copy, formatting etc.

**Comment by colourfreak** [comment]
https://zpl.io/V4G0AeN

<img width="1493" alt="Screenshot 2021-07-13 at 09 26 34" src="https://user-images.githubusercontent.com/51817359/125409949-b1b94d00-e3bc-11eb-89a5-c549e85d1514.png">

**Comment by hboon** [comment]
Thanks @colourfreak !

**Comment by JamesSmartCell** [comment]
@colourfreak would it be a good idea to warn users if they're switching between a currently selected main net to a test net and vice versa? So eg I'm on Eth Mainnet and I get a request to switch to Rinkeby.

**Comment by mpaschenko** [comment]
@colourfreak could you please invite me to that zeplin project as well mpaschenko@gmail.com

**Comment by colourfreak** [comment]
> mpaschenko@gmail.com

Done

**Comment by hboon** [comment]
@vladyslav-iosdev can you check if this has been implemented?
