### ISSUE TITLE
EIP 3085 doesn't work 

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/alpha-wallet-ios#2910]
I test it with https://idchain.one/begin/ 
Works on Metamask, not AlphaWallet.
It pops up the confirmation window but after clicking "Mainnet", nothing happens.

**Comment by hboon** [comment]
Their blockchain explorer (Etherscan/blockscout) site/API seems to be down. MetaMask don't seem to check.

We should at least show an error message.

<img width="600" alt="Screenshot 2021-06-28 at 12 18 54 PM" src="https://user-images.githubusercontent.com/56189/123579749-12685780-d80b-11eb-8d4b-143a5bf5434a.png">

**Comment by hboon** [comment]
@zhangzhongnan928 do you know how to contact the IDChain folks? I can't find their contact information to report this.

Also, the link at the bottom of https://idchain.one/ which links to the explorer is linking wrongly to https://explorer.idchaine.one/. (should be https://explorer.idchain.one/, without the "e")

**Comment by zhangzhongnan928** [comment]
> Also, the link at the bottom of https://idchain.one/ which links to the explorer is linking wrongly to https://explorer.idchaine.one/. (should be https://explorer.idchain.one/, without the "e")

https://twitter.com/Victor928/status/1409381120773267460?s=20
