### ISSUE TITLE
Custom RPC - Warning message

### ISSUE THREAD

**Issue by AW-STJ** [AlphaWallet/alpha-wallet-ios#2913]
Based on our experience with testnets, there can a chance that scammers may abuse custom RPC feature to con unsuspecting users.

Can we create a warning message ask users only to add networks that they trust?

![image](https://user-images.githubusercontent.com/61957841/123583876-b6f69380-d823-11eb-9ea5-603ec6cfe30d.png)

Our message can be:
'Only add networks that you trust. There can be networks with worthless coins and untrustable states.'

Tomek - can you please consider where, when and how should we show these messages?

**Comment by hboon** [comment]
Maybe similar consideration for #2908.

**Comment by colourfreak** [comment]
I don't think it will prevent users to add malicious networks anyway, but we can add a warning right after you click "Add Network"

Zeplin:
https://zpl.io/bAxX7dB

<img width="1704" alt="Screenshot 2021-07-08 at 10 47 21" src="https://user-images.githubusercontent.com/51817359/124892573-477a6400-dfda-11eb-86c7-de2457dc6ec6.png">

**Comment by hboon** [comment]
Hold for now.
