### ISSUE TITLE
Swipe to show swipe menu not working in Wallets screen opened from Wallet tab

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#2916]
If the list of wallets screen screen is accessed from the blockie in the Wallet tab and swiped, the swipe menu (with delete wallet and copy address options) don't appear.

If the same screen is accessed from Settings > Change / Add Wallet, it works.

**Comment by vladyslav-iosdev** [comment]
> If the list of wallets screen screen is accessed from the blockie in the Wallet tab and swiped, the swipe menu (with delete wallet and copy address options) don't appear. 

it disabled by default for wallets screen accessing from blocky icon. i'll Update it.
