### ISSUE TITLE
Higher level architecture tasks

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#2918]
This is on-going work, to keep in mind.

This will translate to lower level work. Just collecting here to keep them in mind as we go along. General goal is to improve the app quality, our development speed as well as support adding more developers working on the same code base.

Logging system (rather than all temporary logs)
---
* Possible to debug user problems remotely
* Useful during development and bug fixing any way

More tests
---
* Fewer regressions, develop newer/changes features faster
* Higher quality
* Also helps with white label projects, especially after resync

Prettifier
---
* Lower priority
* Less time wasted on styling

SwiftLint
---
* Enforce some good practises
* Less time wasted

Functional core
---
* Easier to reason
* Easier to test
* Easier to optimize
* Hence less bugs

Modules
---
* Clearer boundaries
* Hence better code quality
* Hence scale up team size
* Easier to swap out third party code
* Easier to optimize

Less non-main thread/processes
---
* Easier to reason
* Easier to optimize

A few of these work together when we make a change. I think one immediate one we can proceed with is to break out access to Realm into a Cocoapod. This would remove all dependencies on Realm in other parts of the code base, just passing value objects back and forth and provide an opportunity to improve performance of data access (if/when we need to). E.g. we can also swap Realm for an alternate form of datastore.

@vladyslav-iosdev would you think about this and feel free to add any comments/questions/feedback?

**Comment by vladyslav-iosdev** [comment]
@hboon Logging system (rather than all temporary logs)
it means to use something like Firebase to log all warnings errors and so on?

**Comment by hboon** [comment]
> @hboon Logging system (rather than all temporary logs)
> it means to use something like Firebase to log all warnings errors and so on?

No. I wrote a bit of code to use Papertrail for that currently. Just for discovering what RPC node errors we encounter to map them to more user-friendly versions. But not sure we will want that more generally.

Logging system here refers more to things like OSLog and Lumberjack. So we can enable logging for subsystems or full logging during development and at runtime, maybe offer a switch to capture logs when user reproduce a bug. I use a log of `NSLog("xxx")` and I think you use `print()` but most of the time, I keep adding a deleting the same logs to fix related bugs, so even if we don't use it in production, it should help during development.

**Comment by vladyslav-iosdev** [comment]
ok sound good, yep, it could make our life easier.

**Comment by vladyslav-iosdev** [comment]
i am not clearly understood about:
`Functional core`
 What do u meant here?

**Comment by hboon** [comment]
The only place I have done it so far is:

https://github.com/AlphaWallet/alpha-wallet-ios/blob/7a0fe988d803583d1b51b18967a8724a48a71400/AlphaWallet/Settings/Models/AddCustomChain.swift#L85

Copied from the PR:

> Static functions in an inner class enforce that state of value-type arguments are not modified, but it's still possible to modify reference-typed arguments. For now, avoid those. Inner class is required instead of a fileprivate class because one of the value they provide is being easier to test, so they must be accessible from the testsuite. So we don't suffer from extra indentations but being able to still modify reference-type arguments could be a problem. Maybe just don't pass those in or use them as read-only (the latter is hard).

We don't have to make it really be functional programming all the way [1]. But as long as a subset of those functions/methods don't mutate state, we get the same benefits. We then wrap around those with our usual OO code. Consider this an experiment, so you can try writing new code around this style too and see if it works for us. Also feel free to voice out if there's a better way syntatically.

[1] Impossible anyway, since Cocoa(touch) and almost every third party library isn't.

**Comment by hboon** [comment]
This also alleviates somewhat the problem where we have big classes and it's hard to see which bits of code actually mutate state. We could enforce shorter classes with SwiftLint, but length limit seems arbitrary sometimes. Some classes are going to be large simply because they have to do more.

**Comment by vladyslav-iosdev** [comment]
> The only place I have done it so far is:
> 
> https://github.com/AlphaWallet/alpha-wallet-ios/blob/7a0fe988d803583d1b51b18967a8724a48a71400/AlphaWallet/Settings/Models/AddCustomChain.swift#L85
> 
> Copied from the PR:
> 
> > Static functions in an inner class enforce that state of value-type arguments are not modified, but it's still possible to modify reference-typed arguments. For now, avoid those. Inner class is required instead of a fileprivate class because one of the value they provide is being easier to test, so they must be accessible from the testsuite. So we don't suffer from extra indentations but being able to still modify reference-type arguments could be a problem. Maybe just don't pass those in or use them as read-only (the latter is hard).
> 
> We don't have to make it really be functional programming all the way [1]. But as long as a subset of those functions/methods don't mutate state, we get the same benefits. We then wrap around those with our usual OO code. Consider this an experiment, so you can try writing new code around this style too and see if it works for us. Also feel free to voice out if there's a better way syntatically.
> 
> [1] Impossible anyway, since Cocoa(touch) and almost every third party library isn't.

interesting approach, i will try it.

**Comment by eviltofu** [comment]
What about using more protocol oriented programming and dependency injection? Or is this considered low level?

**Comment by hboon** [comment]
> What about using more protocol oriented programming

Using protocols as an interface when there are more than 1 implementation (either in the logic or because we need a version for testing) is good. And as an alternative to subclassing (especially our own classes), using protocols is generally better too.

But I think protocol oriented programming as many people have taken it is going too far. We should just start with the actual type (struct, class, enum) and then extract a protocol if necessary (i.e. there needs to be more than 1 implementation). I don't mind more verbose code if it is cleaer, but it's our internal code, so we can refactor it after the fact rather than start with typing more unless it's necessary. But there could be exceptions, eg. it might be useful to have a protocol and a single big implementation with the protocol as the way to publish an interface for code readability, but I don't think that would be common or so useful in practice.

> and dependency injection?

Dependency injection is a quite a vague term but it's basically about passing in an object from A to B so B isn't tightly coupled to the selection/implmentation of the object to be instantiated. That's done basically with protocols. Is that what you are referring to? We already do that mostly with `configure()` and `init()` in view controllers and coordinators respectively. One ugly thing we have in the codebase is we pass around many objects too often. But it's not a big issue, we can keep it as it is or just wrap some of those common ones in a "context" type.

If that's not what you are referring to, can you elaborate?

> Or is this considered low level?

Depends, but relevant. If we adopt any framework (loosely speaking. e.g. a DI framework) then we should use it consistently so we take advantage of it and the code base is easier to read for people familiar with it. That should be the general way the code base should be or strive to be — clear boundaries and a minimal set of frameworks/patterns, minimal dialects so a competent developer can pick it up. If there's something clever or very different, isolate and hide it somewhere (boundaries!).

**Comment by hboon** [comment]
Refer to #6606
