### ISSUE TITLE
Update Blockscout API endpoint for xDai

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#2941]
Old:

```
curl 'https://blockscout.com/poa/dai/api?module=account&action=tokentx&address=<address>'
```

New:

```
curl 'https://blockscout.com/xdai/mainnet/api?module=account&action=tokentx&address=<address>'
```

So transactions aren't fetched anymore and we can't detect any tokens — ERC20, ERC721.

**Comment by hboon** [comment]
(interestingly, replacing the "dai" with "xdai" in the old URL would work too, but let's just use the newer version that the 301 response is including, i.e "/xdai/mainnet/api?")

**Comment by JamesSmartCell** [comment]
thanks, got it.

**Comment by hboon** [comment]
Reopen to double check
