### ISSUE TITLE
How to get all transaction records of a wallet address？？

### ISSUE THREAD

**Issue by tinaxiu2014** [AlphaWallet/alpha-wallet-ios#2950]
name: Bug Report
about: Using AlphaWallet, but it's not working as you expect?

---

**Describe the bug**

**Steps to reproduce (REQUIRED)**
Steps to reproduce the behavior

1. Tap Wallet tab
2. Tap ...
3. Tap ...
4. Wait ...
5. Tap ...

**Expect**
6a. ...

**Observed**
6b. ...

**Screenshots**
If applicable, screenshots (preferred to video) to help explain your problem, a wallet address or transaction hash if applicable/possible

**Version or build number number**
Version number (if app store), build number (if TestFlight)

**Additional context (Error Messages, etc.)**

**Comment by hboon** [comment]
@tinaxiu2014 can you clarify if you downloaded the app from the app store and want to access the transactions in the Activity tab or are you trying to customise the app/code or if it's something else?

**Comment by tinaxiu2014** [comment]
yes,in the Activity tab, i can see  some send transaction records, but can't see received transaction records.

**Comment by tinaxiu2014** [comment]
like this picture.  ![IMG_0164](https://user-images.githubusercontent.com/7834396/124717637-e601b900-df37-11eb-8ea5-e9f084d77251.PNG)

**Comment by hboon** [comment]
I see. Let me rope in my colleague to help. (I might help you but they will be able to do it faster).

**Comment by tinaxiu2014** [comment]
ok。please reply as soon as possible

**Comment by sharonsylu** [comment]
Hi @tinaxiu2014, can I confirm: 

- Android or iOS ? 
- version --> navigate to [Settings] scroll to very bottom eg. Android will say v. 3.33 (158) if it is the latest release
- Could you please provide your wallet address? I will try to see if I can replicate your issue. 

Thank you

**Comment by tinaxiu2014** [comment]
iOS , version is 1.0.0（2）, my wallet address ：0xc25761Ac06b71A06b329dcEDAaD3e350d814B2C6  , wait reply . thanks .

**Comment by tinaxiu2014** [comment]
> iOS , version is 1.0.0（2）, my wallet address ：0xc25761Ac06b71A06b329dcEDAaD3e350d814B2C6 , wait reply . thanks .

please reply as soon as possible

**Comment by AW-STJ** [comment]
> iOS , version is 1.0.0（2）, my wallet address ：0xc25761Ac06b71A06b329dcEDAaD3e350d814B2C6 , wait reply . thanks .

There is no transactions on POA network for the given wallet address. Did you share the correct wallet address?

https://blockscout.com/poa/core/address/0xc25761Ac06b71A06b329dcEDAaD3e350d814B2C6/transactions

**Comment by AW-STJ** [comment]
@tinaxiu2014, also sharing the link from the transactions details page as show below would help us make sure that we are all looking at the correct place.

![image](https://user-images.githubusercontent.com/61957841/124756687-15341c80-df70-11eb-8dbf-718a085af305.png)

**Comment by tinaxiu2014** [comment]
yeah,my wallet address ：0xc25761Ac06b71A06b329dcEDAaD3e350d814B2C6  ，it is in my custom RPC network.

**Comment by tinaxiu2014** [comment]
> yeah,my wallet address ：0xc25761Ac06b71A06b329dcEDAaD3e350d814B2C6 ，it is in my custom RPC network.
now i can't see received transaction records.

**Comment by sharonsylu** [comment]
Could you please provide the MSC token contract address please? Three of us have been unable to replicate using the  wallet address , nor can we find on any blockexplorers...
