### ISSUE TITLE
Support the Tron chain? 

### ISSUE THREAD

**Issue by akhilccrb** [AlphaWallet/alpha-wallet-ios#2965]
No Tron network support.

**Comment by sharonsylu** [comment]
Hi @akhilccrb thanks for forking the Alphawallet-iOS repo.

As this is a network feature request, could you please describe what your use case is for wanting to have this codebase support the Tron mainnet?  This will help us prioritise where we spend developer time. 

Alternatively, as you're also playing around with the codebase, we welcome your pull requests.  This is an open source project so appreciate any OS dev contributions. Why contribute? Needless to say the benefits for your feature needs --  means the lead engineer will review and if committed, there will be continuous support in the main build.

**Comment by sharonsylu** [comment]
Logging reference resources for future Pull Requests: 

Tron RPC documentation: https://developers.tron.network/docs/tron-wallet-rpc-api#vote
Tron Mainnet Stats + Sun Sidechain: https://tronscan.org/#/

**Comment by akhilccrb** [comment]
Thanks for the update. But is it possible to use Tron signin useing this sdk. ?

**Comment by hboon** [comment]
Sorry for the delay.

Not for the time being, as we are currently heavily focused on EVM support only.
