### ISSUE TITLE
EIP 3085 doesn't work 

### ISSUE THREAD

**Issue by AW-STJ** [AlphaWallet/alpha-wallet-ios#2966]
I was trying out https://chainlist.org/. None of the chains that I tried to add works on AlphaWallet. However, most of them works on Metamask.

![image](https://user-images.githubusercontent.com/61957841/125357075-79107800-e3aa-11eb-9b69-4941f54f54ec.png)

One random example that worked in Metamask Thai Chain:
Network Name: ThaiChain
Network URL: https://rpc.dome.cloud
Chain ID: 7
Currency Symbol: TCH
Block Explorer URL: https://thaichain.io

**Comment by vladyslav-iosdev** [comment]
The problem is that builded URL `https://api.expanse.tech/api?module=account&action=tokentx&address=0x007bEe82BDd9e866b2bd114780a47f2261C684E3` is invalid, this URL is generated right out of `figureOutHostname` function.
