### ISSUE TITLE
RPC: Add own node but conflicts with preexisting chain ID

### ISSUE THREAD

**Issue by sharonsylu** [AlphaWallet/alpha-wallet-ios#2971]
Want to add alternate RPC, but own full node conflicts with pre-existing chain ID. 

Environment: 
- Alphawallet iOS build
- Full nodes are remote 
- tested wtih chainID 1

Observed: 
- Attempt to add a network on custom RPC
- Error Message: "Already supported. Enable this server instead." 

Is this a bug, or is this a feature...? 

641 | "addrpcServer.chainIdAlreadySupported" = "Already supported. Enable this server instead";
https://github.com/AlphaWallet/alpha-wallet-ios/blob/a8c9401e2ea7a673ac15da5d8c566a106241483e/AlphaWallet/Localization/ko.lproj/Localizable.strings

**Comment by hboon** [comment]
(For reference, we can click on the gutter for the relevant line, i.e. click on "641", and the URL in the URL bar will change to something like https://github.com/AlphaWallet/alpha-wallet-ios/blob/a8c9401e2ea7a673ac15da5d8c566a106241483e/AlphaWallet/Localization/ko.lproj/Localizable.strings#L641. Easier for you :) )

> Is this a bug, or is this a feature...?

More a limitation/feature than a bug.

We don't support multiple setups for the same chain ID, nor multiple RPC nodes for the same chain ID.

**Comment by sharonsylu** [comment]
Thank you (still learning, keep these tips coming!) and thank you for confirming we don't support multiple RPCs for same chain ID, will advise!
