### ISSUE TITLE
WalletConnect displays as an asset in the Wallet section on iOS.

### ISSUE THREAD

**Issue by hieronymus4826** [AlphaWallet/alpha-wallet-ios#2978]
WalletConnect displays as an asset in the Wallet section on iOS. Iphone 6e, latest version 19/07/21

![WalletConnect_displayed_in_wallet](https://user-images.githubusercontent.com/84448420/126225468-1673069d-f1c9-40fa-a8d5-abe2093d74ee.jpg)

**Comment by hboon** [comment]
Yes. That’s by design.

**Comment by hieronymus4826** [comment]
I understand.
