### ISSUE TITLE
Optimistic Ethereum not working

### ISSUE THREAD

**Issue by hieronymus4826** [AlphaWallet/alpha-wallet-ios#2979]
I have tested the new UniSwap Optimistic Ethereum and here is the sequence of events on the newest version (19/07/21) on iPhone 6e. These might be multiple issues, but I am posting the whole process to analyze here and then we can split it.

1) The wallet detects the tokens twice

![Two_optimistic_tokens](https://user-images.githubusercontent.com/84448420/126228251-51cf1b06-3af9-4374-a789-d2d48f754e7a.jpg)

2) The wallet doesn't connect at all via WalletConnect in Chrome on iOS (on Android connects the Ethereum network, even though its disabled in Active Networks)

3) The first step is good - the wallet detects the tokens and calculates correctly the expected swapping amounts

![Optimistic_sequence_1](https://user-images.githubusercontent.com/84448420/126227233-6c4ffe02-4364-43cf-bca4-e5bd4301bdfe.jpeg)

4) The wallet pull expected gas cost of congested Ethereum network instead of OE

![Optimistic_sequence_2](https://user-images.githubusercontent.com/84448420/126227355-9ab98e3d-3313-4e4f-8ebb-b5acec47dec8.jpeg)

5) When attempted to adjust the screen popps up with Ethereum mainnet gas calculations 

![Optimistic_sequence_3](https://user-images.githubusercontent.com/84448420/126227496-32d1db49-7de6-406e-860d-1a3ba4a6f711.jpg)

I have tried 10 different values here, from the minimum to the maximum and the next error is always the same.

6) After confirming the adjusted gas prices we get

![Optimistic_sequence_4](https://user-images.githubusercontent.com/84448420/126227649-ca8f86d9-36fe-4c9c-bbcf-b0b475fd48c8.jpeg)

I have tried slippage from AUTO to 10% and makes no difference. Same error. I was  unable to complete a transaction.

I dont know if it would help, but when I tested on Coinbase wallet I go an error the first time which you can see here: 
https://optimistic.etherscan.io/tx/0x56281fd57be0e794907d9d6c4b6edca5633715cec84fe5d3c2a406d4d33d0ef9

In CB Wallet, after increasing the slippage to 5% the transaction went through.

For a reference you can see the Android issue here: https://github.com/AlphaWallet/alpha-wallet-android/issues/1930

**Comment by hboon** [comment]
Going to look at it when I’m back, but can you share which networks are enabled in Settings > Select Active Networks?

**Comment by hieronymus4826** [comment]
At the beginning it was Ethereum, BsC and Optimistic. Later I have tried with Optimistic alone, but no difference in the output. Still displaying both tokens and the sequence is the same.

**Comment by hboon** [comment]
@hieronymus4826

> 1. The wallet detects the tokens twice

#3020

> 2. The wallet doesn't connect at all via WalletConnect in Chrome on iOS (on Android connects the Ethereum network, even though its disabled in Active Networks)

A few things here:

* I can't figure out how to connect to Optimistic on https://app.uniswap.org/#/swap. Is there a toggle in the site? When I use WalletConnect, the connection is always for Ethereum (not Optimistic)
* Connecting sometimes doesn't work, but sometimes it works consecutively. It's still *possible* that it's a problem with the app, but there's a good chacne it's the dapp too. But we *should* definitely show a better, or more informative message when it hasn't connected successfully after a while. Maybe ask the user to try again or something. Created https://github.com/AlphaWallet/alpha-wallet-ios/issues/3022

> 4. The wallet pull expected gas cost of congested Ethereum network instead of OE

#3023. Also stop allow user to change the gas price/limit.

> 6. After confirming the adjusted gas prices we get [slippage etc]

Not sure about this. Seems like it's an issue with the dapp unless we are packing the transaction incorrectly (which is quite bad). Could you give it a go again and see if it's the dapp.

If nothing goes wrong, the 2 PRs will be in next build end of the week.

**Comment by colourfreak** [comment]
@hboon I have the same problem when using Uniswap. 

https://user-images.githubusercontent.com/51817359/140880367-528e3a76-f91f-4aac-822d-f087a5ae4f4c.mp4

**Comment by hboon** [comment]
Closing for now
