### ISSUE TITLE
Design: Add email contact as a support channel back to iOS if it's still legit

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#2982]
We removed it when we switch from the in-app FAQ screen to linking to the website version. So maybe in this screen?

<img width="487" alt="Screenshot 2021-07-21 at 2 00 22 PM" src="https://user-images.githubusercontent.com/56189/126438815-1aed727f-5f00-40cc-b01c-8bda34ff11cb.png">

**Comment by colourfreak** [comment]
![Settings_Support](https://user-images.githubusercontent.com/51817359/126449767-c6628102-5b95-401f-afce-8131a4ebac72.png)

1. I replaced 'Telegram (Public Channel)' with 'Discord'
2. I added 'Email'
3. Do we need: Facebook, Blog, Reddit?

**Comment by colourfreak** [comment]
Zeplin:
https://zpl.io/2ZB67gG

**Comment by hboon** [comment]
>![Settings_Support](https://user-images.githubusercontent.com/51817359/126449767-c6628102-5b95-401f-afce-8131a4ebac72.png) ...

@colourfreak no opinions. Defer to you

**Comment by hboon** [comment]
> Do we need [.., etc]

@colourfreak would you help update either the screenshot or provide a textual description once you figure it out?

**Comment by colourfreak** [comment]
No Reddit, no Facebook and no Blog. This is not meant to be "Find us on" but to get the support.

**Comment by vladyslav-iosdev** [comment]
@hboon what email can do we need to use here?
