### ISSUE TITLE
Improve the alignment of the graphic and text on the Backup intro screen

### ISSUE THREAD

**Issue by colourfreak** [AlphaWallet/alpha-wallet-ios#2985]
Zeplin:
iPhone 8 https://zpl.io/amwxYjr
iPhone 11 https://zpl.io/2GqAqe9

![backup_intro](https://user-images.githubusercontent.com/51817359/126957580-916ab11f-8eca-46f0-88da-5e3f58a3b9ba.jpg)

**Comment by colourfreak** [comment]
* kill the thin, top, gray line 
* break down the text into 
Back up your wallet
with seed phrase 
* Increase the picture size
* Make the text breaks accordingly
* Move the bottom button a bit more to the top

**Comment by Mac3n** [comment]
Could I have contribute in this issue or it's just assigned ?

**Comment by hboon** [comment]
@Mac3n go for it. But could you make this out of scope for the PR? They might  affect other screens.

* kill the thin, top, gray line
* Move the bottom button a bit more to the top

But if you can keep it localised to just this screen too, then feel free to include them too.

**Comment by hboon** [comment]
Vlad, could you help with this? There might be a few other similar screens, especially in the backup seed/JSON keystore flow:

- [ ] Move the bottom button a bit more to the top
