### ISSUE TITLE
If no active WalletConnect session, immediately run the camera

### ISSUE THREAD

**Issue by colourfreak** [AlphaWallet/alpha-wallet-ios#2987]
Currently we are displaying a blank screen when you don't have any active session. I think we can immediately trigger the camera to scan.

![2021-07-26 11 18 31](https://user-images.githubusercontent.com/51817359/126965708-e1cbe7e8-5af3-41b5-b378-f9a48af00f77.png)
![2021-07-26 11 19 32](https://user-images.githubusercontent.com/51817359/126965723-d6344744-5263-44f0-9c19-eda55d0abb02.png)

**Comment by hboon** [comment]
>Sure, would you help give #2987 a go? It probably involves a slight change in flow.

@Mac3n this.

**Comment by Mac3n** [comment]
Sure, I will check it
