### ISSUE TITLE
[Samoa] Improve Add/Hide Tokens screen

### ISSUE THREAD

**Issue by colourfreak** [AlphaWallet/alpha-wallet-ios#2994]
This is one of the last, major changes in regards to Samoa. I think we discussed this part somewhere else, but I could not find this. 

**I recorded two explainer videos:**
https://drive.google.com/file/d/1uG9gtK-TTwSxt2rJU-NpHIreakEYriTC/view?usp=sharing
https://drive.google.com/file/d/1AqZY531iIGT9tzM83vDEMd6EmISwzLit/view?usp=sharing

**What we are changing:**
- I moved the Add/Hide Tokens to the very bottom under all tokens in the wallet tab
- I moved the search bar where Add/Hide Tokens button was before
- I made the search bar in the wallet tab works exactly the same as the one in Add/Hide Tokens. 
- I removed an option to manually reorder tokens inside Add/Hide Tokens
- I added sorting options: by Name, by Value, Most Used
- The search box should have also not displayed tokens in the search results. It means, that we can add a database of tokens (James did this very well) and display tokens while searching for them. 

https://zpl.io/2GqwPL4

**Comment by colourfreak** [comment]
Updated Wallet tab:
![Manage_Tokens_Wallet](https://user-images.githubusercontent.com/51817359/127473988-5cbef0b6-0d64-44b4-9836-696f569de82b.jpg)

**Comment by colourfreak** [comment]
Updated Add / Hide Tokens
![Manage_Token_Long](https://user-images.githubusercontent.com/51817359/127474082-1730aa3d-ce2e-47b3-91f9-3baf57ccf773.png)

**Comment by colourfreak** [comment]
When searching for DAI

![Manage_Token_Search_DAI](https://user-images.githubusercontent.com/51817359/127474138-b48a44f8-ff14-4349-a489-6633f4fa9db5.png)

**Comment by colourfreak** [comment]
When searching for a token that is not displayed, but we already have this address in our database (check out Android)
![Manage_Token_Search_USD](https://user-images.githubusercontent.com/51817359/127474276-08ee0b05-4e93-4761-9442-6d48332c5329.png)

**Comment by colourfreak** [comment]
Sorting selection
![Manage_Token_Sort](https://user-images.githubusercontent.com/51817359/127474325-31b451dd-032e-42f3-a523-f34e6405960a.png)

**Comment by colourfreak** [comment]
When you don't have any search results
![Manage_Token_Search_Empty](https://user-images.githubusercontent.com/51817359/127476031-2dfe582b-10fc-40c9-9154-b0c2df534db4.png)

**Comment by hboon** [comment]
Vlad, besides the categories like "Savings", "Loans", etc. We should be able to implement everything?

**Comment by vladyslav-iosdev** [comment]
Will do!

**Comment by vladyslav-iosdev** [comment]
@colourfreak please share the resources for this screen https://user-images.githubusercontent.com/51817359/127476031-2dfe582b-10fc-40c9-9154-b0c2df534db4.png, can't find this screen here https://app.zeplin.io/project/5d0356be2f25b319dcc5944b/dashboard?sid=60ffc365c0c1c312b627dd5b

**Comment by colourfreak** [comment]
> @colourfreak please share the resources for this screen https://user-images.githubusercontent.com/51817359/127476031-2dfe582b-10fc-40c9-9154-b0c2df534db4.png, can't find this screen here https://app.zeplin.io/project/5d0356be2f25b319dcc5944b/dashboard?sid=60ffc365c0c1c312b627dd5b

https://zpl.io/VY0Lgem
