### ISSUE TITLE
Single Selection looks the same as Multiple Selection

### ISSUE THREAD

**Issue by colourfreak** [AlphaWallet/alpha-wallet-ios#2996]
Not sure if we should change it, but we can have a discussion. I found that a single radio button looks the same like checkbox with multiple selections.

Current:
![Change_Currency_A](https://user-images.githubusercontent.com/51817359/127479230-73edb471-c5a7-4820-9f21-16629ad5f6ca.png)
![Change_Language_A](https://user-images.githubusercontent.com/51817359/127479236-86a95397-8c56-4052-94ac-66f58bbb2a96.png)
![Active_Networks_A](https://user-images.githubusercontent.com/51817359/127479237-a8b72085-6662-4348-82af-4d20bb28fd83.png)

Suggested
![Change_Currency_B](https://user-images.githubusercontent.com/51817359/127479286-8ca7512d-a323-4dae-bc2f-c5bb6b4ddca8.png)
![Change_Language_B](https://user-images.githubusercontent.com/51817359/127479292-694c53e5-6543-4832-ab86-26b1331e83ce.png)
![Active_Networks_B](https://user-images.githubusercontent.com/51817359/127479297-3b3b6085-e86f-4c81-b1b5-130b8c8f1b0e.png)

**Comment by hboon** [comment]
How about keeping the checkmarks for singe selections and switches (like how Alarm.app) for multiple selections? More idiomatic iOS

**Comment by hboon** [comment]
^

**Comment by colourfreak** [comment]
I would like to get back to the subject. Let's have it consistent.

### Radio buttons:
https://zpl.io/Nwkz1Jn
https://zpl.io/W4pdXz7

![Settings_Change_Currency](https://user-images.githubusercontent.com/51817359/153599928-12ae5965-c012-4970-a92a-4d1bc79f8157.png)
![Settings_Change_Language](https://user-images.githubusercontent.com/51817359/153599930-53bd0113-c523-4e6f-b80a-4af650ada215.png)


### Checkboxes:
https://zpl.io/1yk9DGm
https://zpl.io/aNWlZ8Q

![03_Testnet_Select_Active_Network_Disabled](https://user-images.githubusercontent.com/51817359/153599908-cdee8c46-0dd6-486a-8a35-68812b847a3b.jpg)

**Comment by hboon** [comment]
@eviltofu should see if there are other screens affected, so it looks like https://github.com/AlphaWallet/alpha-wallet-ios/issues/3511
