### ISSUE TITLE
Crash when switching wallet in Settings > Change / Add Wallet

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#3011]
Complains about Realm accessed from incorrect thread. Will post if I reproduce again. This is with the tip at 5532de05543c5d7d6d047c7538322504f5ac4042

**Comment by hboon** [comment]
@vladyslav-iosdev would you help check if this is resolved on `master`?

**Comment by vladyslav-iosdev** [comment]
Closing, out of date. Reopen if needed
