### ISSUE TITLE
Tweak? Transfer overlay hides Token image chain badge

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#3021]
Some token icons like Optimistic's ERC20 Ether token includes a round badge to indicate which chain it is. In our design, we overlay a down (or diagonal) arrow icon over the token icon to indicate a transfer. The overlay might cover the round badge completely

It does in the single Activity screen and only partially in the Activity list on iOS, so we might also want to make it consistent.

<img width="487" alt="Screenshot 2021-08-04 at 3 14 40 PM" src="https://user-images.githubusercontent.com/56189/128138222-b4b06866-7de4-43a8-a1b7-6511a025c2d5.png">
<img width="487" alt="Screenshot 2021-08-04 at 3 14 42 PM" src="https://user-images.githubusercontent.com/56189/128138242-82e308c8-83ad-4560-95d3-3b91e1490ffc.png">

**Comment by colourfreak** [comment]
I solved this by moving Network icons to the left.
