### ISSUE TITLE
Pending transactions don't show up in Activities tab after sending one

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#3039]
It looks like `TransactionDataCoordinator.delegate` and `TransactionDataCoordinator.delegate2` are not set anymore: https://github.com/AlphaWallet/alpha-wallet-ios/blob/1b53b96cfab93fa8aac5be1de8959e031a668cbb/AlphaWallet/Transactions/Coordinators/TransactionDataCoordinator.swift#L37

Looks like it's broken by bd1989196d7216edd7cbaca6e19670b88686f234 because most of the code in `ActivitiesCoordinator` was moved to `ActivitiesService` but this wasn't:

```
extension ActivitiesService: TransactionDataCoordinatorDelegate {
    func didUpdate(result: ResultResult<[TransactionInstance], TransactionError>.t, reloadImmediately: Bool) {
        switch result {
        case .success(let items):
            transactions = items
            reloadViewController(reloadImmediately: reloadImmediately)
        case .failure:
            break
        }
    }
}
```

Not sure if there's other code missing.

**Comment by hboon** [comment]
I would take a look at it again on Monday/Tues if Vlad hasn't by then.

**Comment by vladyslav-iosdev** [comment]
@hboon i checked behaviour for sending transaction in test net, it works as expected. does it means that a new tx doesn't show in list at all for you? or it appears with delay?

**Comment by vladyslav-iosdev** [comment]
also i am facing the next: the dates for activities list displays several times "for today section" is this is ok?
<img width="447" alt="Screenshot 2021-08-09 at 10 44 57" src="https://user-images.githubusercontent.com/55975226/128674600-37f62c64-0ec4-494e-9dd3-1789033cd6cc.png">

**Comment by hboon** [comment]
That should be ok for now

**Comment by hboon** [comment]
We can fix it separately unless the transactions are wrong

**Comment by hboon** [comment]
>@hboon i checked behaviour for sending transaction in test net, it works as expected. does it means that a new tx doesn't show in list at all for you? or it appears with delay?

@vladyslav-iosdev they don’t appear as pending transactions first. After you look at this, can you do a quick pass and see if anything else is missing? Just in case.

**Comment by vladyslav-iosdev** [comment]
@hboon seems like i am not able to reproduce it, after several attempts was not able to reproduce it. there shouldn't be any differences beetwen sending token on test or main Network right?

**Comment by hboon** [comment]
>@hboon seems like i am not able to reproduce it, after several attempts was not able to reproduce it. there shouldn't be any differences beetwen sending token on test or main Network right?

@vladyslav-iosdev yes. No difference. Can you try disable the code that fetches new transaction? Does the pending transaction show up right away after you post a transaction? If you can reproduce it, let me check it again tomorrow to be sure. Don’t waste your time in case it’s just a problem on my side.

**Comment by hboon** [comment]
@vladyslav-iosdev I can reproduce this on Ropsten with a8fd2280a8988185f163844d754f4c394e257d71:

Modify the function at https://github.com/AlphaWallet/alpha-wallet-ios/blob/a8fd2280a8988185f163844d754f4c394e257d71/AlphaWallet/Transactions/Coordinators/TransactionDataCoordinator.swift#L124 to be:

```
private func handleUpdateItems(reloadImmediately: Bool) {
    let objects = transactionCollection.objects
    NSLog("xxx calling delegate and delegate2: \(delegate) and \(delegate2)")
    delegate?.didUpdate(result: .success(objects), reloadImmediately: reloadImmediately)
    delegate2?.didUpdate(result: .success(objects), reloadImmediately: reloadImmediately)
}
```

After sending ETH, I get:

> xxx calling delegate and delegate2: nil and nil

And Activity tab doesn't show a "Sending ETH" row. After a while, the Activity tab shows "Sent ETH" for that new transaction. The Sending cell should immediately immediately

**Comment by vladyslav-iosdev** [comment]
```NSLog("xxx calling delegate and delegate2: \(delegate) and \(delegate2)")```
these pointers are null because we get updates directly from `TransactionCollection.swift` via its `Subscibable` values.
from here
```
func subscribableFor(filter: TransactionsFilterStrategy) -> Subscribable<[TransactionInstance]>
func removeSubscription(subscription: Subscribable<[TransactionInstance]>)
func transaction(withTransactionId transactionId: String, server: RPCServer) -> TransactionInstance?
```

**Comment by vladyslav-iosdev** [comment]
trying to reproduce it on my side

**Comment by vladyslav-iosdev** [comment]
@hboon  i suppose that this issue could be in case of large wallet, when sorting takes a lot of time. Because with wallet i am trying to reproduce, its not reproducing

**Comment by hboon** [comment]
Hmm. Could you point me the the piece of code which creates the pending transaction and add to the database?

**Comment by vladyslav-iosdev** [comment]
here is where is get created 
https://github.com/AlphaWallet/alpha-wallet-ios/blob/1b53b96cfab93fa8aac5be1de8959e031a668cbb/AlphaWallet/Transactions/Coordinators/TransactionDataCoordinator.swift#L109
and via this method we add it to the DB
https://github.com/AlphaWallet/alpha-wallet-ios/blob/1b53b96cfab93fa8aac5be1de8959e031a668cbb/AlphaWallet/Transactions/Coordinators/TransactionDataCoordinator.swift#L110
 and this method had called
https://github.com/AlphaWallet/alpha-wallet-ios/blob/1b53b96cfab93fa8aac5be1de8959e031a668cbb/AlphaWallet/Transactions/Storage/TransactionsStorage.swift#L208
and with this method we are listening for adding to the db
https://github.com/AlphaWallet/alpha-wallet-ios/blob/db59667b5b4f844fee94c4a1cc2cacb8970bcd13/AlphaWallet/Tokens/Types/TransactionCollection.swift#L97
https://github.com/AlphaWallet/alpha-wallet-ios/blob/db59667b5b4f844fee94c4a1cc2cacb8970bcd13/AlphaWallet/Tokens/Types/TransactionCollection.swift#L120

**Comment by hboon** [comment]
Thanks. I’ll take a look again and try.

**Comment by vladyslav-iosdev** [comment]
@hboon btw transaction doesn't appear on token screen in activity tap, or it doesn't appear on all activities tab?

**Comment by hboon** [comment]
I only checked the “main” Activities tab

**Comment by hboon** [comment]
@vladyslav-iosdev sorry, I get it now. It's added when the progress dialog is closed. I probably broke it when I was trying to look into it. Will see if there's a way to improve it in #3061, but not a bug. Thanks for checking.
