### ISSUE TITLE
'secp256k1.h' file not found

### ISSUE THREAD

**Issue by jagdeepmishra** [AlphaWallet/alpha-wallet-ios#3040]
name: Bug Report
about: Using AlphaWallet, but it's not working as you expect?

---
After Installing all pods, I am unable to run my project. it says secp256k1.h not found

**Version or build number number**
Swift 4.2

**Comment by hboon** [comment]
Hi @jagdeepmishra we have experienced something like this but not sure if we quite narrowed it down or have fixed it entirely, but just be sure, can you make sure you are on:

* `master` branch
* Build with Xcode 12.5?

If you haven't used 12.5, could you clone the repo again, just to be sure no intermediate files are affecting things (intermediate files was really tricky for us when we hunt down this issue).

**Comment by jagdeepmishra** [comment]
Yes Xcode version is 12.5.1 and its works with master branch. But when I try to add Alpha Wallet in my Sample Project. After installing all pods it gives me error in my xcode.

**Comment by hboon** [comment]
Can you elaborate what you mean by sample project?

**Comment by trustwalletvn** [comment]
First you need 
Run **make bootstrap** to install tools and dependencies. with Terminal on root of folder **alpha-wallet-ios**
After that build with xcode

> Yes Xcode version is 12.5.1 and its works with master branch. But when I try to add Alpha Wallet in my Sample Project. After installing all pods it gives me error in my xcode.
