### ISSUE TITLE
"Add token failure" error message 

### ISSUE THREAD

**Issue by benslaney** [AlphaWallet/alpha-wallet-ios#3045]
name: Bug Report
about: "Add token failure" error message on adding any Ethereum token (not other chains though). On compiled master branch only - works fine on app in App Store

---

1. Tap Wallet tab
2. Tap Add / Hide Tokens
3. Tap an ERC20 token, such as TrueUSD
4. Wait ...
5. There error dialog appears

**Expect**
The token to be added to the token list that shows on app startup

**Version or build number number**
latest master branch

![IMG_8C97466C0B1E-1](https://user-images.githubusercontent.com/10335775/128785300-f8f04a25-594b-4c16-95ce-a5910f83d59f.jpeg)

**Comment by vladyslav-iosdev** [comment]
@hboon it failures because of error `daily request count exceeded, request rate limited`

**Comment by hboon** [comment]
Ah, no wonder I can't reproduce it previously. Can you trap for it and show a message. We have shown something like that so we should be able to reuse the message. Buzz me if  you can't find it.

**Comment by benslaney** [comment]
I can't trap it well but it does feel like an API request failing. Which one would it be? I have tried replacing Etherscan and Infura to no avail

thanks for looking at it

**Comment by hboon** [comment]
@benslaney no worries, I'll look into it. Thanks for trying :)

**Comment by benslaney** [comment]
I can't trap it because it just stops on some coordinator thing that's got dozens of layers of abstraction and the actual code path is obfuscated by ASM dumps

if there's anything I can do let me know and I will

**Comment by hboon** [comment]
@benslaney but for your purpose, try replacing the Infura key in `Constants+Credentials.swift` if you haven't.

**Comment by benslaney** [comment]
I have tried replacing Etherscan and Infura to no avail

**Comment by benslaney** [comment]
I'll try again on the infra key I guess - thanks

**Comment by hboon** [comment]
Linked PR contains the fix.

For posterity, here's how we can debug it:

1. Do a full text search for the error message "Add token failure" in `R.generated.swift`
2. Look for the function which uses it -> walletsHideTokenErrorAddTokenFailure()
3. Look for where the function is called
4. We are lucky here and it's only used at one place:

```
}.catch { _ in
    self.displayError(message: R.string.localizable.walletsHideTokenErrorAddTokenFailure())
}.finally {
```

5. Modify to log the error:

```
}.catch { error in
    NSLog("xxx error: \(error")
    self.displayError(message: R.string.localizable.walletsHideTokenErrorAddTokenFailure())
}.finally {
```

then follow the flow to figure out why.
