### ISSUE TITLE
Crash when fetching events

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#3046]
Seems like #3043 introduces a crash. I tested with wallet: `0x007bEe82BDd9e866b2bd114780a47f2261C684E3` on Ropsten.

If we modify the loop at:

https://github.com/AlphaWallet/alpha-wallet-ios/blob/86555ad46d1cbf774ea9185daf7851a0082f59fa/AlphaWallet/Activities/ViewModels/ActivitiesViewModel.swift#L55

to become:

```
for each in activities {
    let date = each.date.timeIntervalSince1970
    let key: ActivityDateKey = .init(timeInterval: date)
    let currentItems = newItems[key] ?? .init()
    currentItems.add(each)
    NSLog("xxx keys before: \(newItems.keys) count: \(newItems.keys.count)")
    NSLog("xxx adding key: \(key) with hash: \(key.stringValue)")
    newItems[key] = currentItems
    NSLog("xxx adding after key count: \(newItems.keys.count)")
}

```

Running it, I get:

> 2021-08-10 11:58:56.293132+0800 AlphaWallet[742:8953664] xxx keys before: [AlphaWallet.ActivityDateKey(timeInterval: 1610440545.0, stringValue: "Jan 12, 2021"), AlphaWallet.ActivityDateKey(timeInterval: 1603530944.0, stringValue: "Oct 24, 2020"), AlphaWallet.ActivityDateKey(timeInterval: 1613564548.0, stringValue: "Feb 17, 2021"), AlphaWallet.ActivityDateKey(timeInterval: 1603947660.0, stringValue: "Oct 29, 2020"), AlphaWallet.ActivityDateKey(timeInterval: 1613451787.0, stringValue: "Feb 16, 2021"), AlphaWallet.ActivityDateKey(timeInterval: 1603437376.0, stringValue: "Oct 23, 2020")] count: 6
> 2021-08-10 11:58:56.293289+0800 AlphaWallet[742:8953664] xxx adding key: ActivityDateKey(timeInterval: 1603438086.0, stringValue: "Oct 23, 2020") with hash: Oct 23, 2020
> 2021-08-10 11:58:56.293435+0800 AlphaWallet[742:8953664] xxx adding after key count: 6
> 2021-08-10 11:58:56.293652+0800 AlphaWallet[742:8953664] xxx keys before: [AlphaWallet.ActivityDateKey(timeInterval: 1610440545.0, stringValue: "Jan 12, 2021"), AlphaWallet.ActivityDateKey(timeInterval: 1603530944.0, stringValue: "Oct 24, 2020"), AlphaWallet.ActivityDateKey(timeInterval: 1613564548.0, stringValue: "Feb 17, 2021"), AlphaWallet.ActivityDateKey(timeInterval: 1603947660.0, stringValue: "Oct 29, 2020"), AlphaWallet.ActivityDateKey(timeInterval: 1613451787.0, stringValue: "Feb 16, 2021"), AlphaWallet.ActivityDateKey(timeInterval: 1603437376.0, stringValue: "Oct 23, 2020")] count: 6
> 2021-08-10 11:58:56.293825+0800 AlphaWallet[742:8953664] xxx adding key: ActivityDateKey(timeInterval: 1603438086.0, stringValue: "Oct 23, 2020") with hash: Oct 23, 2020
> 2021-08-10 11:58:56.293962+0800 AlphaWallet[742:8953664] xxx adding after key count: 6
> 2021-08-10 11:58:56.387917+0800 AlphaWallet[742:8953691] Version 10.12.0 of Realm is now available: https://github.com/realm/realm-cocoa/blob/v10.12.0/CHANGELOG.md
> 2021-08-10 11:58:56.398084+0800 AlphaWallet[742:8953664] xxx keys before: [] count: 0
> 2021-08-10 11:58:56.398283+0800 AlphaWallet[742:8953664] xxx adding key: ActivityDateKey(timeInterval: 1603782995.0, stringValue: "Oct 27, 2020") with hash: Oct 27, 2020
> 2021-08-10 11:58:56.398452+0800 AlphaWallet[742:8953664] xxx adding after key count: 1
> 2021-08-10 11:58:56.398670+0800 AlphaWallet[742:8953664] xxx keys before: [AlphaWallet.ActivityDateKey(timeInterval: 1603782995.0, stringValue: "Oct 27, 2020")] count: 1
> 2021-08-10 11:58:56.398966+0800 AlphaWallet[742:8953664] xxx adding key: ActivityDateKey(timeInterval: 1603437972.0, stringValue: "Oct 23, 2020") with hash: Oct 23, 2020
> Fatal error: Duplicate keys of type 'ActivityDateKey' were found in a Dictionary.
> This usually means either that the type violates Hashable's requirements, or
> that members of such a dictionary were mutated after insertion.
> 2021-08-10 11:58:56.399572+0800 AlphaWallet[742:8953664] Fatal error: Duplicate keys of type 'ActivityDateKey' were found in a Dictionary.
> This usually means either that the type violates Hashable's requirements, or
> that members of such a dictionary were mutated after insertion.

**Comment by vladyslav-iosdev** [comment]
@hboon now it should be ok, removed usage of `ActivityDateKey`
