### ISSUE TITLE
Design: disambiguate tokens available to add with the same name in Add/Hide tokens

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#3049]
Could be due to our implementation, but should we provide a way to tell the various "Burner" tokens apart?

(just in the master branch, may not be available on TestFlight/app store yet)

<img width="460" alt="Screenshot 2021-08-10 at 4 44 44 PM" src="https://user-images.githubusercontent.com/56189/128839002-2fccfbf6-6881-41f9-b275-789861d14264.png">

**Comment by colourfreak** [comment]
Popular tokens are those with top30 ERC20 tokens

**Comment by vladyslav-iosdev** [comment]
> Popular tokens are those with top30 ERC20 tokens

@hboon Does it mean we need to update tokens `.json` file?

**Comment by hboon** [comment]
Superseded by #3069
