### ISSUE TITLE
Refactor/clean up. Seems TransactionDataCoordinator.delegate2 (and delegate?) is not used anymore

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#3061]
Check #3039 for background.

And maybe adding the pending transaction when the confirmation UI is closed is not good.

**Comment by vladyslav-iosdev** [comment]
> And maybe adding the pending transaction when the confirmation UI is closed is not good.

@hboon Displaying pending transaction comes with delay, that is because there is a lot of calculation before  displaying it. especially while using a large wallet.

**Comment by hboon** [comment]
Yes, but we can probably initiate it (with a delay in the background if necessary) in a different place in the chain rather than upon user close the confirmation dialog. Feels like the wrong place to be.

**Comment by vladyslav-iosdev** [comment]
oh, checked call stack, yeah it adds not. recently but after we closing the confirmation view
