### ISSUE TITLE
Mobile browser WalletConnect doesn’t work

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/alpha-wallet-ios#3077]
https://user-images.githubusercontent.com/33795543/129807234-0f1e4638-104b-4887-95c6-907277667a18.MOV

**Comment by hboon** [comment]
The configuration on our server to grant permission to intercept aw.app links is down:

```
$ curl https://aw.app/apple-app-site-association
```

> <html>
> <head><title>504 Gateway Time-out</title></head>
> <body>
> <center><h1>504 Gateway Time-out</h1></center>
> </body>
> </html>

**Comment by colourful-land** [comment]
@hboon is it to associate iOS app with a domain name? why not associate to alphawallet.com? There might be an old reason but I couldn't find it.

**Comment by hboon** [comment]
> is it to associate iOS app with a domain name? why not associate to alphawallet.com? There might be an old reason but I couldn't find it.

@colourful-land kind of, but more specifically, it is to tell Apple that the domain hosting this (i.e. aw.app) allows the app to intercept URLs containing that domain as deeplinks. We originally used this for MagicLinks, so we can't use it for alphawallet.com without changing MagicLinks.

But for this issue, we were just riding on the existing setup for aw.app, so in theory, if we want to, we can serve the same file on alphawallet.com too [1], but aw.app still needs it for MagicLinks.

[1] We'll need to create a PR for WalletConnect for the new deeplink and run both in parallel to support both.. so probably not practical.

**Comment by zhangzhongnan928** [comment]
@samuelhbne are you managing the aw.app ?

**Comment by samuelhbne** [comment]
I worked with Weiwu months ago for fixing this issue. It was resolved by restarting. So guess we can copy the cheat cheat again.

We planed to start a new project to replace it as there's no docs as well as work log of this project hence we have zero knowledge over how it worked.

**Comment by hboon** [comment]
Fixed after restarting server a long while ago.
