### ISSUE TITLE
App crashes for no reason

### ISSUE THREAD

**Issue by colourfreak** [AlphaWallet/alpha-wallet-ios#3106]
3.26 (401)
https://web.tresorit.com/l/ebzt1#T-J_0LWs0iifzl2CxI3G7Q

**Comment by hboon** [comment]
FYI. GitHub issues now supports video upload.

**Comment by hboon** [comment]
@colourfreak I can't reproduce this. Can you help provide context around this?

Build 401 is exactly the same as build 400 + 1 seemingly unrelated fix.

* Do you experience the same crash in the previous build, 400?
* Did you experience the crash just a few moments after launching without doing anything else? (I can't pick up if there were attempts to tap or scroll in the video)
* Did you do anything before the crash? Example, remove this wallet and re-import it?

**Comment by colourfreak** [comment]
> FYI. GitHub issues now supports video uploads.

Yep, I know. But my upload is low here. Next time.

**Comment by colourfreak** [comment]
https://user-images.githubusercontent.com/51817359/132080951-8befcb61-6f48-4032-97c5-322fe03eb16f.MOV

**Comment by colourfreak** [comment]
https://user-images.githubusercontent.com/51817359/132081102-5dc350a4-576f-46af-b8c2-9d1054a800ea.MOV

**Comment by colourfreak** [comment]
https://user-images.githubusercontent.com/51817359/132081183-05d65711-5e67-48c1-aafe-4d4b1f293d98.MOV

**Comment by hboon** [comment]
@vladyslav-iosdev would you help check if this is resolved on `master`?

**Comment by vladyslav-iosdev** [comment]
@hboon  this is not reproducing for me on `master`

**Comment by vladyslav-iosdev** [comment]
Reopen if reproduced again
