### ISSUE TITLE
QR scan button missing on the iOS version

### ISSUE THREAD

**Issue by colourful-land** [AlphaWallet/alpha-wallet-ios#3118]
Observe the upper-right corner icon was missing in iOS. 

![Screenshot_20210901-163619](https://user-images.githubusercontent.com/548435/131623802-72ba409f-3703-4b77-a71e-fe2f98783a55.png)

This icon should simply display a QR code of the Ethereum address

![Screenshot_20210901-164008](https://user-images.githubusercontent.com/548435/131624054-6e636add-b6ae-494e-8f15-a19a7249e2af.png)

 (where as the Receive tab might be redesigned to  include currency/token type + amount to form a payment request QR code instead)

**Comment by hboon** [comment]
QR button in zeppelin
