### ISSUE TITLE
ERC1155 Implementation Info

### ISSUE THREAD

**Issue by JamesSmartCell** [AlphaWallet/alpha-wallet-ios#3123]
## Querying balance:

1. Get TransferSingle receive events since last call (ie track the start block number).
2. Get TransferBatch receive events since last call.
3. Collect all the TokenIds for tokens received in those events.
4. Call 'balanceOfBatch' across all those tokenIds, and existing tokenIds tracked in previous calls.
5. Update the received balances and update the start block number for the next check.

```event TransferSingle(address indexed _operator, address indexed _from, address indexed _to, uint256 _id, uint256 _value);```

```event TransferBatch(address indexed _operator, address indexed _from, address indexed _to, uint256[] _ids, uint256[] _values);```

and the filter:

Topic1: TransferSingle/TransferBatch
Topic2: null (operator)
Topic3: null (from)
Topic4: wallet account address (to)

This way we get all the receive events and can check the current balance for each. You could also keep a running diff, but that is prone to failing under a currently unknown edge condition (maybe the filter events didn't return correctly etc).

## Is the TokenId a collection, NFT or a Fungible?

- Check the top 20 bytes (96 bits). If this is non zero, and matches another TokenId, it's probably part of the same collection.
- If the top 20 bytes are non-zero, mask the bottom 5 bytes. If the value is non zero, and 0xFFFF or less it's probably an NFT. If the value is zero, it's a fungible even if the balance is 1.

This heuristic works for all the OpenSea and Enjin ERC1155 collections so far seen.

Haven't yet added discovery via the BlockScout transfer query API.

**Comment by hboon** [comment]
Thanks James.

> Call 'balanceOfBatch' across all those tokenIds, and existing tokenIds tracked in previous calls.

What is this `balanceOfBatch`?

> since last call (ie track the start block number).
> This way we get all the receive events and can check the current balance for each. You could also keep a running diff, but that is prone to failing under a currently unknown edge condition (maybe the filter events didn't return correctly etc).

If you are saying that we should always fetch the events from genesis and recompute the current balance (and not track the balance from previous batch and fetch the delta since), Binance and Heco seems to have problems doing event log fetches across more than a 4000 block window size so you might have to paginate.

**Comment by JamesSmartCell** [comment]
> What is this `balanceOfBatch`?
> 
This is ERC1155's superpower and allows you to query a collection of tokenIds:

```
function balanceOfBatch(address[] memory accounts, uint256[] memory ids)
        public
        view
        virtual
        override
        returns (uint256[] memory)
    {
        require(accounts.length == ids.length, "ERC1155: accounts and ids length mismatch");

        uint256[] memory batchBalances = new uint256[](accounts.length);

        for (uint256 i = 0; i < accounts.length; ++i) {
            batchBalances[i] = balanceOf(accounts[i], ids[i]);
        }

        return batchBalances;
    }
```

eg ```balanceOfBatch([my wallet address], [34,30,29,50])```

gives you the balance for tokenIds 34,30,29,50 on your account. It makes this method possible.

> 
> If you are saying that we should always fetch the events from genesis and recompute the current balance (and not track the balance from previous batch and fetch the delta since), Binance and Heco seems to have problems doing event log fetches across more than a 4000 block window size so you might have to paginate.

You would call the filter log, initially starting at block 1 (say), up to the LATEST block. I don't know how you limit it, but by adding the receive only on your account it should limit it somewhat. If you get an error too many logs, then you'd need to change strategy.

Keep track of the latest event received, read the block number. The next time you query, you need only start at that block number + 1.

Presumably, on the first pass you'd store all the tokenIds that have positive balance. You need to query those along with any new tokenIds received in the logs.

**Comment by hboon** [comment]
Sounds great. Thanks!

**Comment by JamesSmartCell** [comment]
You probably spotted the typo in the above call, it should be:

eg ```balanceOfBatch([wallet address, wallet address, wallet address, wallet address], [34,30,29,50])```

**Comment by hboon** [comment]
Closing for now.
