### ISSUE TITLE
Reduce background queues count

### ISSUE THREAD

**Issue by vladyslav-iosdev** [AlphaWallet/alpha-wallet-ios#3125]
Fix rapid Realm files grow up, move from background accessing to realm to using main thread

**Comment by hboon** [comment]
Hold on to this one for a while while I work on ERC1155 :)

**Comment by hboon** [comment]
> Hold on to this one for a while while I work on ERC1155 :)

This also means our code base is not modularised enough. So we'll have to fix this as we go along.

**Comment by vladyslav-iosdev** [comment]
> Hold on to this one for a while while I work on ERC1155 :)

sure, np. i made these changes because of reasons i found while worked on erc1155 screens.

**Comment by vladyslav-iosdev** [comment]
> This also means our code base is not modularised enough. So we'll have to fix this as we go along.

do u mean to devide the proj by sub spm modules? or just modularise the instances we got?

**Comment by hboon** [comment]
> > Hold on to this one for a while while I work on ERC1155 :)
> 
> sure, np. i made these changes because of reasons i found while worked on erc1155 screens.

Ah yes. There's lots to improve. But try to postpone them. Hard for me to merge them in.

**Comment by hboon** [comment]
> > This also means our code base is not modularised enough. So we'll have to fix this as we go along.
> 
> do u mean to devide the proj by sub spm modules? or just modularise the instances we got?

Modularize what we already have. But breaking them into spm or pods is probably how we have to do it because it sets a clear boundary. It's quite hard in practise with Swift to set a boundary otherwise. But do you find it's possible without SPM/pods?

**Comment by vladyslav-iosdev** [comment]
i thought that modularizing instances it means to devide instances on smaller pieces, like it says `SRP` in `SOLID`. anyway yep, using also deviding by `SPM` would allow us flaxibility of changing these parts

**Comment by hboon** [comment]
Yes, something like SRP. We might not have to go too far to narrow it down, but in a lot of places we do mix UI and logic too much, and that's problematic sometimes now and would be bad if we have more people work on it at the same time. A prime example is fetching/detecting token data, while it's ok to spread it out like we do now, there isn't clear entry points and boundaries so for making changes like ERC1115, it blocks other changes (like this refactoring).

SPM doesn't seem to work if the code that is wrapped has Cocoapods dependencies, so we might end up with mostly Cocoapods.. but just an implementation detail I suppose.

**Comment by Tarkan122** [comment]
Merhaba çok teşekkür ederim Biricik Annem beyin ameliyatında öldü nevrim
dündü sank kalbim de 10.8 deprem oldu kendimde deyim

Benim güveneceğim bir ekipbe ihtiyacım var babam dagılmış her gün avlıyor
bana yardım ederöisin

GLOBAL MERKEZİ OLMAYAN CRYPTO BUSİNESS TCTB TOKENS UNISWAP TOKENS T1C
TOKENS COMPOND TOKENS COMP TOKENS BTC ve ETHERUM ETH TOKENS TRON ZRX, USDT
USDC, TOKENS USDB TOKENS MKR TOKENS C11 CONTRAT ERC20 ve ERC721, ERC1155,
EİP 1159  TRC20, TRC1155, İPS CONTRACT SAHİBİ OWNER EKONOMİ FİNAS
YATIRIMLARINDA 600 BORSADA TİCARET YAPAN CRYPTO BUSİNESS GÜVENLİK AGI
BROKSER TEKNOLEJİ SAVUNMA SANAYİ SİLAH VE İNSANSIZ HAVA YATIRIMLARI ve
MOBİL, PC OYUN ÜRETİCİSİ ve İŞLETMECİ  CRYPTO MANDENCİ HAVUZLARI FACTOR
ADRESS OWNERBTOKENS HOLDER EXPLORER YATIRIM DENİZCİLİK LİMAN PORT ARMATÖR
TERSANE GEMİ SHİP YATIRIMLARI ve EKONOMİ FİNANS BANKA FON YATIRIMLARI BORSA
EXPLORER TOKEN HOLDİNG A. Ş

YÖNETİM KURULU BAŞKANI
         TARKAN BİRİCİK


 https://twitter.com/tarkan1biricik

Mobil TC +905320157406

Crypto Telegram No: +905323056894

Mail:

***@***.***

***@***.***

***@***.***

***@***.***

     CRYPTO BUSİNESS

       🇹🇷🇹🇷🇹🇷🇹🇷🇹🇷🇹🇷🇹🇷

               biricik.eth

                    ens


               etherscan.io



              0x63616e.eth


          biricigim.argent.xyz


                   ens.eth


       🇹🇷 🇹🇷 🇹🇷 🇹🇷 🇹🇷 🇹🇷 🇹🇷



6 Eyl 2021 Pzt 09:47 tarihinde Hwee-Boon Yar ***@***.***>
şunu yazdı:
