### ISSUE TITLE
> This also means our code base is not modularised enough. So we'll have to fix this as we go along.

### ISSUE THREAD

**Issue by Tarkan122** [AlphaWallet/alpha-wallet-ios#3127]
> This also means our code base is not modularised enough. So we'll have to fix this as we go along.

do u mean to devide the proj by sub spm modules? or just modularise the instances we got?

_Originally posted by @vladyslav-iosdev in https://github.com/AlphaWallet/alpha-wallet-ios/issues/3125#issuecomment-913377761_

**Comment by hboon** [comment]
Spam
