### ISSUE TITLE
Crash a lot with recent versions

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/alpha-wallet-ios#3128]
when using Dapp Browser, crash every 2-5 mins
keep the app open without using anything, crash as well

**Comment by hboon** [comment]
Which version in Settings? 3.26/402 or 3.27/403?

**Comment by zhangzhongnan928** [comment]
> Which version in Settings? 3.26/402 or 3.27/403?

Both， I'm using3.26 402 right now.
the wallet is Victor928.eth. If I click share crash report, will you receive it?
previously I always click no.

**Comment by hboon** [comment]
> the wallet is Victor928.eth. If I click share crash report, will you receive it?

Sometimes. But send it anyway.

**Comment by hboon** [comment]
@vladyslav-iosdev would you help check if this is resolved on `master`?

**Comment by vladyslav-iosdev** [comment]
@hboon  this is not reproducing for me on `master`

**Comment by vladyslav-iosdev** [comment]
Reopen if reproduced again
