### ISSUE TITLE
A wallet’s NFTs appear in B wallet

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/alpha-wallet-ios#3132]
Some NFTs(not all) belongs to victor928.eth appear in both victor928.eth and BirdDAO.eth
![image](https://user-images.githubusercontent.com/33795543/132294349-2d5e259d-1cf2-42bb-935f-7de9f994fbbf.jpeg)
![image](https://user-images.githubusercontent.com/33795543/132294386-263703bc-5321-494e-8ff0-b66e61cba96d.jpeg)
![image](https://user-images.githubusercontent.com/33795543/132294397-f1c373c2-8244-41f7-a12a-b334f489f3bc.jpeg)
![image](https://user-images.githubusercontent.com/33795543/132294414-2ce97f20-a9d4-4820-b3ba-6e08489248bd.png)

**Comment by hboon** [comment]
@vladyslav-iosdev would you help check if this is resolved on `master`?

**Comment by vladyslav-iosdev** [comment]
yes, i was able to reproduce this issue. Trying to find the reasons of it.
