### ISSUE TITLE
Add Icon that links to "My Wallet Address" screen in the Wallet tab

### ISSUE THREAD

**Issue by colourfreak** [AlphaWallet/alpha-wallet-ios#3166]
https://zpl.io/2ZZBnPd

This should take you to the "My Wallet Address" screen

<img width="672" alt="Screenshot 2021-09-08 at 07 36 51" src="https://user-images.githubusercontent.com/51817359/132519857-5c4a1e7c-813c-4df3-9723-de9c565f5d31.png">
 Note, that this is already implemented in Android.

**Comment by vladyslav-iosdev** [comment]
its already closed via #3131
