### ISSUE TITLE
Is send button wrongly enabled for ERC721/1155 on watched wallet?

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#3175]
These lines:

```
        switch (type, session.account.type) {
        case (.send, .real), (.request, _):
            makeCoordinatorReadOnlyIfNotSupportedByOpenSeaERC721(coordinator: tokensCardCoordinator, token: token)
        case (.send, .watch):
            tokensCardCoordinator.isReadOnly = true
        }
```

were replaced by:

```
tokensCardCoordinator.makeCoordinatorReadOnlyIfNotSupportedByOpenSeaERC721(type: type)
```

in the PR https://github.com/AlphaWallet/alpha-wallet-ios/pull/3164/files for `SingleChainTokenCoordinator`.

Do you think that's wrong? It seems like if the user taps an ERC721 (or 1155) token on a watched wallet, the Send button will be enabled when it shouldn't be.

**Comment by vladyslav-iosdev** [comment]
hmm, that strange, i just moved code from `SingleChainTokenCoordinator ` to related coordinator

**Comment by hboon** [comment]
Could just be git doing it when resolving merge/conflicts. Can you help restore those few lines if it is wrong?
