### ISSUE TITLE
I don’t know how to create web3 on my iPhone

### ISSUE THREAD

**Issue by Euroman123** [AlphaWallet/alpha-wallet-ios#3183]

**Comment by hboon** [comment]
@Euroman123 can you be more specific what you would like to do?

**Comment by Euroman123** [comment]
I want to have w3 on my device

**Comment by hboon** [comment]
I don't understand. Let us try to gather some more information about what you want:

Are you trying to do this as a:

A. iOS app developer, possibly forking this repo?
B. DApp developer using the app to access the DApp?
C. User using the app to access a DApp?

If it's one of those, can you elaborate on what it is you are trying to do?

**Comment by Euroman123** [comment]
I want to create a telegram bot of my own

**Comment by hboon** [comment]
Ah, I see. Unfortunately, this isn't the correct repo for what you want to do

If you want to be able to connect to Ethereum via libraries, you can start with web3js or ethers.js for JavaScript or a similar libraries for other languages.
