### ISSUE TITLE
Update Polygon RPC endpoint to aggregator version

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#3203]
We got this message:

> Check out Hi team, some of the projects deployed on polygon are reflecting on slow DApp access on mobile wallet applications. Could you please verify if the rpc is updated to the aggregator version in your wallet? https://polygon-rpc.com

See if `https://polygon-rpc.com` is the RPC endpoint we should use (otherwise figure out what is), that it works and use it instead.

If it works, create an issue in the Android repo too

**Comment by vladyslav-iosdev** [comment]
@hboon seems the url `https://polygon-rpc.com/` works fine

**Comment by hboon** [comment]
I think that’s working but doesn’t handle the load very well. The other does some kind of old balancing

**Comment by vladyslav-iosdev** [comment]
does it mean that these changes not needed, right?

**Comment by hboon** [comment]
Oh, I see what you mean, since we are using Infura for Polygon currently. Sorry, I missed that. Hmm.. ok, let's keep it the RPC endpoint unchanged (and stick to Infura for Polygon) then. I noticed you have some other changes, maybe refactoring, in #3238. Could you just remove the endpoint change and let's get the PR going for the other changes alone, but with a different commit message?)
