### ISSUE TITLE
Fix build (and particularly signing) with Fastlane

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#3205]
I was trying to do this a while back, but for some reason, signing just doesn't work for me.

PS: try not to upload. You should be able to fix it without uploading.

**Comment by vladyslav-iosdev** [comment]
@hboon can u please show me the error you got here?

**Comment by vladyslav-iosdev** [comment]
running command `fastlane ios travis_tests` fails for me, i updated fastlane file with 

<img width="316" alt="Screenshot 2021-09-28 at 14 49 31" src="https://user-images.githubusercontent.com/55975226/135081206-a2844f25-fbba-4573-80a0-5527498af583.png">

and now it works, but i am not sure about signing

**Comment by hboon** [comment]
Ah, I'm sorry, can you try the `release` lane? You probably need to modify it to work for you. Running `travis_tests` doesn't sign it. I didn't run it to produce the errors this time because I'll need to modify it too :)

Let me know if you want me to create a separate app ID so you can generate profiles?

It's been a long time, but I remember that when trying to figure out the signing issue, I had to drop down to running `xcodebuild` manually to try to figure out what's wrong. I have this in my old notes:

---

I'm running `xcodebuild` [1] with `-exportOptionsPlist` passing it a plist which contains this snippet:

```
<dict>
    <key>com.example.myapp</key>
    <string>5f8cd286-671d-412f-a2cb-100feb5d64ca</string>
    <key>com.example.myapp.share</key>
    <string>cd966010-da0f-4583-a388-8f080333ae0a</string>
</dict>
```

But it's throwing this at me:

error: exportArchive: No "iOS App Store" profiles for team 'LRAW5PL536' matching '5f8cd286-671d-412f-a2cb-100feb5d64ca' are installed.

I've tried a few things:

* Change the value of the UUID in x.plist to another value to verify that xcodebuild does read it (and complain about the erroneous value I set in the error message)
* Made sure the provisioning profiles are in `~/Library/MobileDevice/Provisioning\ Profiles/`
* Change the filenames to `5f8cd286-671d-412f-a2cb-100feb5d64ca`
* Change the filenames to `5f8cd286-671d-412f-a2cb-100feb5d64ca.mobileprovision`
* Change x.plist so the uuid values are filenames with absolute paths

**Comment by hboon** [comment]
I could never get Xcode to automatically sign for AlphaWallet (as well as BC) uploads. It's also entirely possible that something is wrong with my environment instead of the projects.

**Comment by vladyslav-iosdev** [comment]
@hboon i am facing interesting errors while calling function `fastlane ios release`
It seems like predefined variables as `MARKETING_VERSION` couldn't be recognized by fastlane 
`Your current version ($(MARKETING_VERSION)) does not respect the format A or A.B or A.B.C`

**Comment by hboon** [comment]
I don’t remember getting those. Maybe it is the  way we are using variables? You can hardcode them first if it’s that.

**Comment by vladyslav-iosdev** [comment]
i will check it, btw, for me this line doesn't work
`match(type: "appstore", readonly: true)`
i am not sure if we still need it, as it uses Trust repo certs.

**Comment by hboon** [comment]
Yeah. If it points to their carts, it should be changed to ours.

**Comment by hboon** [comment]
@oa-s can you try this again?

**Comment by oa-s** [comment]
sure

**Comment by oa-s** [comment]
@eviltofu if you have throughput, could u check this issue?

**Comment by eviltofu** [comment]
Ok so running `./vendor/bundle/bin/bundle exec fast lane ios release` results in `[!] Your current version ($(ALPHAWALLET_INFO_PLIST_FILE)) does not respect the format A or A.B or A.B.C`.

**Comment by hboon** [comment]
Changed assignments just to be clear. Update yourself to reflect reality :)

**Comment by hboon** [comment]
BTW, I updated the first comment to include this:

> PS: try not to upload. You should be able to fix it without uploading.

**Comment by eviltofu** [comment]
How are you all using `fastlane`? `./vendor/bundle/bin/bundle exec fastlane ios release` or you have your own copy of `fastlane`? @oa-s @hboon

**Comment by hboon** [comment]
Should use the copy installed with `Gemfile`. So:

```
./vendor/bundle/bin/bundle exec fastlane <…>
```

**Comment by eviltofu** [comment]
> Should use the copy installed with `Gemfile`. So:
> 
> ```
> ./vendor/bundle/bin/bundle exec fastlane <…>
> ```

Strangely this is not the version that is installed via the Gemfile. The version of bundle here is the current Ruby's version of bundle.

**Comment by eviltofu** [comment]
I created a new Fastfile via Fastlane init and tinkered around until I was able to upload (where I hit control-c to kill the process).

```ruby
default_platform(:ios)

platform :ios do
  desc "Push a new release build to the App Store"
  lane :release do
    increment_build_number(xcodeproj: "AlphaWallet.xcodeproj")
    build_app(workspace: "AlphaWallet.xcworkspace", scheme: "AlphaWallet", xcargs: "-allowProvisioningUpdates")
    upload_to_app_store(skip_metadata: true, skip_screenshots: true, skip_binary_upload: true)
  end
end
```

**Comment by hboon** [comment]
Great! I suppose you managed to sign? that was what I was stumbing over.

**Comment by eviltofu** [comment]
Under Xcode 13.3 and macOS 12.3, I am unable to archive the current project master branch (d6a5ebbc77f8c4b315d5a891ed0eaf301acb5ae5). I get the following error:

```
CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler (in target 'SwiftProtobuf' from project 'Pods')
...
Command CompileSwiftSources failed with a nonzero exit code
```
and
```
SwiftCodeGeneration normal arm64 (in target 'Mixpanel-swift' from project 'Pods')
...
error: Segmentation fault: 11 (in target 'Mixpanel-swift' from project 'Pods')
```

@hboon

**Comment by hboon** [comment]
> Under Xcode 13.3 and macOS 12.3, I am unable to archive the current project master branch ([d6a5ebb](https://github.com/AlphaWallet/alpha-wallet-ios/commit/d6a5ebbc77f8c4b315d5a891ed0eaf301acb5ae5)). I get the following error:
> 
> ```
> CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler (in target 'SwiftProtobuf' from project 'Pods')
> ...
> Command CompileSwiftSources failed with a nonzero exit code
> ```
> 
> and
> 
> ```
> SwiftCodeGeneration normal arm64 (in target 'Mixpanel-swift' from project 'Pods')
> ...
> error: Segmentation fault: 11 (in target 'Mixpanel-swift' from project 'Pods')
> ```
> 
> I am able to build the project.
> 
> Xcode 13.2.1 reports no such problem and was able to successfully archive the project.
> 
> @hboon

Best stick with 13.2.1 then? Separately, we can try upgrade the `Mixpanel-swift` to see if it helps?

Is this related to Fastlane?

**Comment by eviltofu** [comment]
> Best stick with 13.2.1 then? Separately, we can try upgrade the `Mixpanel-swift` to see if it helps?
> 
> Is this related to Fastlane?

@hboon 

No. I was trying to verify that Xcode 13.3 could archive without any issues before working on a solution to Fastlane. I will post this as an issue to be solved later.
