### ISSUE TITLE
Design UI to edit custom chains

### ISSUE THREAD

**Issue by vladyslav-iosdev** [AlphaWallet/alpha-wallet-ios#3216]
Out of https://github.com/AlphaWallet/alpha-wallet-ios/pull/3209#issuecomment-926391018 comment, we need design for modifying RPC server suppose accessing from this screen: 
![IMG_4AF0073D5D49-1](https://user-images.githubusercontent.com/55975226/134678877-5e4767bd-dc06-41f8-abca-aafc5e025706.jpeg)
and also ui elements for deleting rpc servers.

**Comment by hboon** [comment]
Note that we can already delete custom-added ones by swiping. But the screen doesn’t indicate which ones are custom

**Comment by hboon** [comment]
Done. Refer to #3409
