### ISSUE TITLE
Popular tokens add button not working.

### ISSUE THREAD

**Issue by ericwingate** [AlphaWallet/alpha-wallet-ios#3218]
name: Bug Report
about: When cloning a fresh copy of the iOS version of Alpha Wallet, the Popular tokens section within "Add / Hide Tokens" will not allow me to add any tokens when pressing the green + icon.

I have replaced infura and etherscan API keys with my own, however, the problem still exists. 

---

**Describe the bug**
The Popular tokens section within "Add / Hide Tokens" will not allow me to add any tokens when pressing the green + icon.

**Steps to reproduce (REQUIRED)**
Steps to reproduce the behavior

1. Tap "Add / Hide Tokens"
2. Scroll down to Popular Tokens section
3. Tap greep + icon next to any of the popular tokens.
4. Nothing happens, a Loading... icon shows quickly and disappears

Video capture of issue is attached

https://user-images.githubusercontent.com/6406322/134789664-dbf25691-5ea1-451a-b1ff-86f0e088aa0b.mp4

.

**Comment by hboon** [comment]
@ericwingate thanks for reporting.
