### ISSUE TITLE
Create default, fallback icon for ERC1155 tokenIds ("tokens") that don't have token icons

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#3223]
The small icons and bigger version in these 2 screens respectively:

Small|Big
-|-
<img width="200" alt="Screenshot 2021-09-27 at 1 26 40 PM" src="https://user-images.githubusercontent.com/56189/134849848-e68b4891-f36a-4d5d-9150-95110347ac04.png">|<img width="200" alt="Screenshot 2021-09-27 at 1 26 50 PM" src="https://user-images.githubusercontent.com/56189/134849857-76065844-5240-41ac-9295-f64b544e9dee.png">

**Comment by colourfreak** [comment]
![ERC-1155-Project-Assets-List-Placeholder](https://user-images.githubusercontent.com/51817359/142423087-f0ee7335-42b0-4322-9dda-6d5e80f454ab.jpg)
![ERC-1155-Project-Placeholder](https://user-images.githubusercontent.com/51817359/142423091-51fc0970-e445-4136-893b-12105fe3ad09.jpg)

https://zpl.io/an8q4gv
https://zpl.io/2E3NoMv

**Comment by hboon** [comment]
Thanks @colourfreak !

**Comment by hboon** [comment]
@colourfreak BTW, do you think we can use the same or similarly styled icon in the dapp browser history/bookmarks? It seems more intention-revealing than the color app icon version that we use now. If so, We can create a new issue.

**Comment by hboon** [comment]
@colourfreak bump ^

**Comment by colourfreak** [comment]
> @colourfreak BTW, do you think we can use the same or similarly styled icon in the dapp browser history/bookmarks? It seems more intention-revealing than the color app icon version that we use now. If so, we can create a new issue.

What is the size of it? Can you send me a screenshot of how it looks right now?

**Comment by colourfreak** [comment]
https://zpl.io/aN3xkAD
https://zpl.io/V0Ool99

![Browser_Icons](https://user-images.githubusercontent.com/51817359/143845625-79438778-4e69-4a1a-aa13-60bc30b1f1ac.jpg)
