### ISSUE TITLE
Followup tasks for ERC1155 support

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#3224]
There are pending tasks for ERC1155 support after #3221:

- [ ] Classify token IDs in an ERC1155 contract into collections. i.e. 1 contract, N collections
    * James seems to have a solution
- [ ] Can we take decimals > 0 as meaning the token ID is fungible? (But can it be a fractional NFT?)
 Support batch transfers (and Select at top right hand corner of Assets sub-tab needs to be enabled)
- [x] Looks like a bug: `let view = SingleTokenCardAmountSelectionToolbarView(viewModel: .init(availableAmount: 20, selectedAmount: 1))`
    * Affects ERC721 ? Beause it's not used  for ERC1155
- [ ] Missing fields in token collection. Not sure we can get all of them (refer to UI design)
    * Issuer
    * Assets
    * Melts
    * Hodlers/Holders
    * Transfers
- [x] Missing fields in token ID screen (refer to UI design)
    * Issuer
    * Circulating Supply
    * Total Supply
    * Reserve Value
    * Type
    * Transferable
    * Melt Fee
    * Transfer Fee
    * Created (i.e. date)
- [ ] Some token URI JSONs have more metadata (e.g. properties?) eg. https://lostrelics.io/item-metadata/18000000000005e1000000000000000000000000000000000000000000000000
- [ ] Check add custom token from UI handles ERC1155 correctly. Especially balance. Also name/symbol is not part of ERC1155 (e.g. Enjin), and symbol is not applicable
- [ ] Check if relevant, about how tokenURI is interpreted: https://github.com/AlphaWallet/AlchemyNFT/issues/513
- [x] Tap token row in send 1155 should expand to show each tokenId + value
- [x] The big image after tapping on a token (tokenId) should almost fill the screen horizontally
- [x] Show default/fallback token ID icon when they are not available #3223

**Comment by hboon** [comment]
cc @colourfreak for what's missing.

**Comment by vladyslav-iosdev** [comment]
@hboon i was able to retrieve these values out with enjin api, for now the problem is it requires authorization. Authorization returns expirable token. And we have to manage it some how.

**Comment by hboon** [comment]
Hmm. Could you implement a simple version of its really simple or describe how it works? Whichever is easy and easier to understand it so we can see if it’s a good solution or how we might tweak it?

**Comment by vladyslav-iosdev** [comment]
once i done i will push changes

**Comment by hboon** [comment]
Only if it’s simple enough and you don’t mind throwing it away :) because Enjin sounds like it’s specific to their contract, but let’s see. Thanks

**Comment by vladyslav-iosdev** [comment]
@hboon  
i was not able to find how to fetch these fields information:
- Issuer
- Assets
- Melts
- Hodlers/Holders
- Transfers

**Comment by hboon** [comment]
That’s fine. We use what we have first.

**Comment by vladyslav-iosdev** [comment]
@hboon hope changings applied to `WebImageView` will not broke existed logic

**Comment by hboon** [comment]
@vladyslav-iosdev test them with ENS avatar? That seems the most fragile.

**Comment by vladyslav-iosdev** [comment]
it should affect on  ENS avatar, as its related to urls that don't have `url.pathExtension == "svg"`

**Comment by vladyslav-iosdev** [comment]
i updated web view to fit parents actual size, so it loads not with :
`webView.load(.init(url: url))` but with 
`
let html = generateHtmlForThumbnailSvg(url: url, size: size)
webView.loadHTMLString(html, baseURL: nil)
`

**Comment by vladyslav-iosdev** [comment]
@hboon  can u provide more details on it

**Comment by hboon** [comment]
> > Tap token row in send 1155 should expand to show each tokenId + value
> 
> @hboon can u provide more details on it

I was trying to build the PR to recall what I meant :) Did we miss including `Apollo` in the Podfile maybe?

**Comment by vladyslav-iosdev** [comment]
`Apollo` has installed via spm

**Comment by vladyslav-iosdev** [comment]
can u provide error message u've got

**Comment by hboon** [comment]
> > Tap token row in send 1155 should expand to show each tokenId + value
> 
> @hboon can u provide more details on it

Ah, I see it now. It's outdated. Ignore it.

**Comment by hboon** [comment]
> `Apollo` has installed via spm

I'm sorry, do you think we can switch to using Cocoapods for this (and future new libraries) for now. I know I said we want to use SPM where possible. But it seems to be having build problems with M1 [^1] . Eg. with MailChimp, I created a PR #3533 to disable it in simulators, but  we can't use that approach for most libraries.

[^1] Building for M1 + simulators work if we run Xcode in Rosetta mode. But that's the last resort.

**Comment by hboon** [comment]
@oa-s can you help to see if there's anything remaining for this issue; otherwise help close it?

**Comment by oa-s** [comment]
@hboon  seems like we don't access to https://github.com/AlphaWallet/AlchemyNFT/issues/513

**Comment by hboon** [comment]
@oa-s add you and @eviltofu to the repo as well as to the organization

**Comment by oa-s** [comment]
@hboon Thanks ;)

**Comment by oa-s** [comment]
> Check if relevant, about how tokenURI is interpreted: https://autographnft.io/0x18a808dd312736fc75eb967fc61990af726f04e4/58 cannot be displayed AlchemyNFT#513

in case if there is some decoding error appears (that shouldn't happen). But if the issue related to displaying base64 encoded image, it works fine. Tested with example from issue

**Comment by oa-s** [comment]
>  Check add custom token from UI handles ERC1155 correctly. Especially balance. Also name/symbol is not part of ERC1155 (e.g. Enjin), and symbol is not applicable

While adding a new erc1155 token, the balance value displays like `0`
