### ISSUE TITLE
sent  a EthCallRequest，How do decode the returned results ？？thinks 。

### ISSUE THREAD

**Issue by tinaxiu2014** [AlphaWallet/alpha-wallet-ios#3239]
name: Bug Report
about: Using AlphaWallet, but it's not working as you expect?

---

**Describe the bug**

**Steps to reproduce (REQUIRED)**
Steps to reproduce the behavior

1. Tap Wallet tab
2. Tap ...
3. Tap ...
4. Wait ...
5. Tap ...

**Expect**
6a. ...

**Observed**
6b. ...

**Screenshots**
If applicable, screenshots (preferred to video) to help explain your problem, a wallet address or transaction hash if applicable/possible

**Version or build number number**
Version number (if app store), build number (if TestFlight)

**Additional context (Error Messages, etc.)**

**Comment by hboon** [comment]
Look for "func adapt(".

**Comment by tinaxiu2014** [comment]
returned results : 0x00000000000000000000000000000000000000000000000000000000000c44000000000000000000000000000000000000000000000000000000000002faf33000000000000000000000000000000000000000000000000000000000614c4b56  ,also use   "func adapt(".    decode ??

**Comment by hboon** [comment]
That's the place to start looking. You'll have to do the rest :)
