### ISSUE TITLE
Create native token icon for Arbitrum One

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#3246]
- [x] Assign developer
- [x] Assign https://github.com/AlphaWallet/alpha-wallet-android/issues/2074

**Comment by colourfreak** [comment]
![Arbitrum](https://user-images.githubusercontent.com/51817359/135582241-52026504-5e67-44fa-9342-24217e058963.png)

https://zpl.io/ag5RdQ1

**Comment by hboon** [comment]
Thanks @colourfreak !

**Comment by colourfreak** [comment]
I haven't added a token to iconassets

**Comment by hboon** [comment]
Got it. iconassets don't support the native crypto token yet, so we'll still have to bundle it (the Zeplin link above) with the app for now. But feel free to add icons to iconassets for other tokens for Arbitrum if you like.
