### ISSUE TITLE
The Browser home icon should not disappear when coming back from address input

### ISSUE THREAD

**Issue by colourfreak** [AlphaWallet/alpha-wallet-ios#3252]
3.26 (406)

1. Open Browser
2. Check that there is a Home button up there
3. Open Address input field 
4. Click 'Cancel'
5. Notice that the Home icon disappears

**What to do?**
Keep this icon.

**Comment by colourfreak** [comment]
https://user-images.githubusercontent.com/51817359/135583553-4866cbb8-4bb6-410a-a21a-942f069b9610.MOV

**Comment by hboon** [comment]
Ah yes, I have seen this too. Thanks!
