### ISSUE TITLE
iOS app wallets suddenly replaced by a single, new wallet silently, automatically

### ISSUE THREAD

**Issue by sharonsylu** [AlphaWallet/alpha-wallet-ios#3260]
**Summary**: 
- iOS user opened App
- App no longer detecting user history: wallet, keys, tokens, activity, bookmarks. 

**Observed**:
- Open app, saw a new wallet address (not recognised by user). 

In triage, checked: 
- no changes to user environment (did not swap phones, did not clear cache, no new app version update) 
- between last use and opening today, only new action performed were to add two token contract addresses. 

**Screenshots**

Supplied by user, to show: 

Only one address, behaving as if this were a clean install of App with newly generated wallet 0x address - 

![2](https://user-images.githubusercontent.com/15342675/135798577-51d73228-9bee-4f65-83cb-171039f21466.png)

Other changes detected by user -  Arbitrum Network "added by user appears" in enabled networks. Although "added by user"  simply might be coincidental with the addition of Arbitrum in latest release, and not conclusive this is his history rpc being detected. 

![1](https://user-images.githubusercontent.com/15342675/135798631-af892e88-1980-4464-accd-cf082a6d090b.png)

**Further user investigation required** 

* is the iOS app installed straight from the iOS app store?
* Has the Face ID/Touch ID settings been changed recently? e.g. all Face scans/fingerprint scans have been removed?
* Device PIN changed?

User responses will be updated in this ticket. 

**Early Diagnosis**

Bug caused by the app thinking (which is indeed related to iOS that) there are no wallet addresses in the app and trying to create a default one. 

Will create a guard to make sure this case does not happen again.

**Comment by sharonsylu** [comment]
**Further User feedback** 

* downloaded Alphawallet directly from App store
* has not changed FaceID or PIN
* Punctilious with security
* iOS version is 15.0 on iPhone XsMax
![3](https://user-images.githubusercontent.com/15342675/135801598-cc57d87b-67cf-4e53-bc9e-1ddc9048a0af.png)

**User actions ** 
User next steps: 

* will decide to update to iOS v15.1 tomorrow when he visits wifi park (based in Cuba, spotty wifi) after he backs up everything 
* will clean download Alphawallet from Appstore and then restore all wallets from seed 
* will provide feedback 

Monitoring of progress is still underway, any new information will be posted here.

**Comment by sharonsylu** [comment]
**User Actions** 
* confirmed updated iOS v15.0.1 today, downloaded Alphawallet
* restore / reimport of all wallets using seed phrase was successful

**Observed behaviour**

Upon restoring all wallets, he observed:

* Activity: all displayed
* Bookmarks: all lost
* Tokens:   
- custom tokens automatically displayed (he expected that he would need to manually re-add, per first time when he started using the app in May/June). 
- however the 2 manual tokens, added yesterday before "the blackout" and after restoring, did not display

**Screenshot**

![4](https://user-images.githubusercontent.com/15342675/136002928-10c509b8-dd5b-4f4c-be71-f1337ea85fb8.png)

** Next steps**

- User issue:  resolved, no further user action.
- Bug: please advise if any further triage questions required of user, to diagnose mysterious behaviour?

**Comment by hboon** [comment]
> Bug: please advise if any further triage questions required of user, to diagnose mysterious behaviour?

No. Thanks!

**Comment by hboon** [comment]
Can't reproduce
