### ISSUE TITLE
Activity changes (discussion only)

### ISSUE THREAD

**Issue by colourfreak** [AlphaWallet/alpha-wallet-ios#3278]
Let's start with something very generic. 

**Issue 01**
Waste of space when we are displaying Activity with the same information you can find in the Activity list. They should be merged. I know that in the past we planned to use this real estate for TokenScript notes, but we have never used it. 

Note that in Android you learn even less. As you don't even see who is a recipient. You have to reveal Transaction Details to learn more.

![01_Android_ios](https://user-images.githubusercontent.com/51817359/136229238-deca2585-8361-4479-a3b5-3d048a745829.jpg)

**Suggestion:**
Merge Activity screen and Transaction Details into one screen.

<img width="1441" alt="Screenshot 2021-10-06 at 16 47 31" src="https://user-images.githubusercontent.com/51817359/136229441-429325b9-e4cb-45f6-999c-24586bac7644.png">

**Comment by colourfreak** [comment]
Issue 3
iOS and Android have a different layout of the Activity page. The icon is in a different size, Android lacks Recipient information, Android has the amount below the line, weird font. Also, the timestamp is different. 

![03](https://user-images.githubusercontent.com/51817359/136234618-1080b34b-e04f-4c1d-ab43-5ec13aa27dbf.jpg)

**Comment by colourfreak** [comment]
Issue 4
Trade on Uniswap is recognized as "Contract Execution" on iOS and just two transactions one after another "Sent ETH" and "Received DAI". 

![06](https://user-images.githubusercontent.com/51817359/136235304-0974257c-5d09-445b-abb7-ec394413e48d.jpg)

If you look at Etherscan, you will find exactly what I am looking for 
https://etherscan.io/tx/0x37213c42bb82505f355cd44ad38e678cc1bb98d33bb1f9826708cb38779705dd

<img width="1678" alt="06_Uniswap_Etherscan" src="https://user-images.githubusercontent.com/51817359/136235396-be7d5bb5-9e9b-4a33-a8d0-d8a5328825b7.png">

<img width="1685" alt="06_Swap on Uniswap 3" src="https://user-images.githubusercontent.com/51817359/136234948-8bc85806-b2f9-4784-b9b0-9c5994342564.png">

**Comment by colourfreak** [comment]
Issue 5
Android is missing a search option. 
![05](https://user-images.githubusercontent.com/51817359/136940226-9052688a-f05e-44ac-8cb2-fb078e050326.jpg)

**Comment by colourfreak** [comment]
Issue 8
The same transaction is called "Contact call" on Android and "Sent ETH" on iOS
https://cn.etherscan.com/tx/0x52921c840a7501c9bfbb9417f9d0ceb6dd8619210dd238d1d96c733d7cc5aef1

This transaction was about setting an ENS avatar. So neither of these transactions show a correct activity. 
![08](https://user-images.githubusercontent.com/51817359/136949899-66ec8b26-47ea-481d-96e9-d5aaecaf9cd9.jpg)

**Comment by hboon** [comment]
Closing for now
