### ISSUE TITLE
Support SVGs for ENS avatar text records

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#3342]
Test with Victor's ENS

**Comment by hboon** [comment]
I don't know if we still have the conversion code for SVG -> raster image in the code base and not sure if it will work well enough.

**Comment by vladyslav-iosdev** [comment]
@hboon can u please remind me his ens, was trying to find it, but couldn't

**Comment by hboon** [comment]
@vladyslav-iosdev I messaged you in Telegram :)
