### ISSUE TITLE
Adding chain with chain list.org (and hence EIP3085?) not working anymore

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#3343]
When adding expanse with chainlist.org. Thai chain too:

>  ), NSLocalizedDescription=A server with the specified hostname could not be found., NSErrorFailingURLStringKey=https://api.expanse.tech/api?module=account&action=tokentx&address=0x007bEe82BDd9e866b2bd114780a47f2261C684E3, NSErrorFailingURLKey=https://api.expanse.tech/api?module=account&action=tokentx&address=0x007bEe82BDd9e866b2bd114780a47f2261C684E3, _kCFStreamErrorDomainKey=12}
> 2021-10-19 16:34:51.094438+0800 AlphaWallet[65856:303018] [boringssl] boringssl_metrics_log_metric_block_invoke(144) Failed to log metrics
> 2021-10-19 16:34:51.455002+0800 AlphaWallet[65856:301717] [Presentation] Attempt to present <UIAlertController: 0x7fe17484d000> on <UINavigationController: 0x7fe16481da00> (from <AlphaWallet.BrowserViewController: 0x7fe174b30a00>) which is already presenting <AlphaWallet.SwitchChainRequestViewController: 0x7fe174b3ca00>.

Maybe broken recently.

**Comment by vladyslav-iosdev** [comment]
>2021-10-19 16:34:51.455002+0800 AlphaWallet[65856:301717] [Presentation] Attempt to present <UIAlertController: 0x7fe17484d000> on <UINavigationController: 0x7fe16481da00> (from <AlphaWallet.BrowserViewController: 0x7fe174b30a00>) which is already presenting <AlphaWallet.SwitchChainRequestViewController: 0x7fe174b3ca00>.

@hboon is there issue only in presenting `UIAlertController`? for me adding chains from `chainlist.org` works (but not for all)
