### ISSUE TITLE
Indicate which chain for each WalletConnect session more prominently by showing an icon for the chain for each session

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#3403]
In the list of WalletConnect sessions screen, we current show the connected chain in brackets, but it's not very readable and may not be visible if the site name is long. This comes in handy when we connect multiple sessions to the same dapp (eg. Swap). Can we improve it?

Current|Design
-|-
<img width="240" alt="Screenshot 2021-11-02 at 3 05 21 PM" src="https://user-images.githubusercontent.com/56189/139800959-3dd972fe-3bd6-4a2a-b74a-26599d7b4ed5.png">|<img width='200' src='https://user-images.githubusercontent.com/56189/139800974-356cc0f6-8440-4414-ba88-bd1918af763d.jpg'>

**Comment by colourfreak** [comment]
How about having a small icon indicating the network?

Network icons
https://zpl.io/adoPDwe

Screen
https://zpl.io/adoPDM7

That can be a good basement before we automatically add network icons to all icons (currently I have to upload an icon, but it will be better if I just upload one, and the network icon is added automatically)

![Active_Connections](https://user-images.githubusercontent.com/51817359/139828803-7705d77b-cc99-46e8-b643-ff6c11fc0374.jpg)

**Comment by hboon** [comment]
@colourfreak looks good. Thanks!

**Comment by hboon** [comment]
> That can be a good basement before we automatically add network icons to all icons (currently I have to upload an icon, but it will be better if I just upload one, and the network icon is added automatically)

@colourfreak yes

**Comment by hboon** [comment]
@vladyslav-iosdev would you help to show the little chain icon overlay in each chain?

**Comment by JamesSmartCell** [comment]
> How about having a small icon indicating the network?
> 
> Network icons https://zpl.io/adoPDwe
> 
> Screen https://zpl.io/adoPDM7
> 
> That can be a good basement before we automatically add network icons to all icons (currently I have to upload an icon, but it will be better if I just upload one, and the network icon is added automatically)
> 
> ![Active_Connections](https://user-images.githubusercontent.com/51817359/139828803-7705d77b-cc99-46e8-b643-ff6c11fc0374.jpg)

I like this a lot.

Can we also re-use this for the main wallet and activity pages? The way that the code works means one change can do this. This will clean up the activity pages in Android too.

**Comment by hboon** [comment]
If you are referring to using those little icons, that's what Tomek is referring to here: https://github.com/AlphaWallet/alpha-wallet-ios/issues/3403#issuecomment-957469567

But token icons in the iconassets already show this, so we might need to coordinate it a bit. Better to separate the work for this screen and elsewhere.

**Comment by JamesSmartCell** [comment]
> @JamesSmartCell If you are referring to using those little icons, that's what Tomek is referring to here: [#3403 (comment)](https://github.com/AlphaWallet/alpha-wallet-ios/issues/3403#issuecomment-957469567)
> 
> But token icons in the iconassets already include those small icons, so we might need to coordinate it a bit. Better to separate the work for this screen and elsewhere.

Yes, I have seen those, and indeed we should do a coordinated swap to a code driven graphic approach. I can isolate this chain icon to just the WC session screen for now.

**Comment by colourfreak** [comment]
> @JamesSmartCell If you are referring to using those little icons, that's what Tomek is referring to here: [#3403 (comment)](https://github.com/AlphaWallet/alpha-wallet-ios/issues/3403#issuecomment-957469567)
> 
> But token icons in the iconassets already include those small icons, so we might need to coordinate it a bit. Better to separate the work for this screen and elsewhere.

I can do it again and get rid of the network icon already placed in the token icon's corner. But I would prefer if we first make https://github.com/AlphaWallet/alpha-wallet-ios/issues/2629 so we have all tokens organized. Having #2629 ready is the gateway to all further wallet changes (adding sorting options, grouping, filtering, etc.) Kind of like metadata about the tokens we display. @hboon @JamesSmartCell

**Comment by hboon** [comment]
@colourfreak when you refer to #2629, are you referring to:

A. Display charts when we have the data
B. Make A work for more tokens, in particular for tokens that are on L2s or wrapped versions (eg. WETH). Have created #3423 for this to reduce confusion

A is already implemented on iOS, so I have created #3423 and closed #2629

**Comment by colourfreak** [comment]
https://github.com/AlphaWallet/alpha-wallet-ios/issues/2629#issuecomment-918291148

@hboon I am referring to this comment. I think we can make it a separate issue.

**Comment by JamesSmartCell** [comment]
> > @JamesSmartCell If you are referring to using those little icons, that's what Tomek is referring to here: [#3403 (comment)](https://github.com/AlphaWallet/alpha-wallet-ios/issues/3403#issuecomment-957469567)
> > But token icons in the iconassets already include those small icons, so we might need to coordinate it a bit. Better to separate the work for this screen and elsewhere.
> 
> I can do it again and get rid of the network icon already placed in the token icon's corner. But I would prefer if we first make #2629 so we have all tokens organized. Having #2629 ready is the gateway to all further wallet changes (adding sorting options, grouping, filtering, etc.) Kind of like metadata about the tokens we display. @hboon @JamesSmartCell

OK, I am done with the side projects for a bit, back on AW for the next week so I'll do another big Samoa work-push
