### ISSUE TITLE
Support editing custom chains

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#3409]
We ship with many built-in chains (See Settings > Select Active Networks), but users can add custom chains.

Custom chains can be added by going to the Browser tab and visiting https://chainlist.org. "Expanse Network" is one example you can add (since it's not bundled with the app). Follow through the flow and when you visit Settings > Select Active Networks again, the chain ("Expanse") should be selected.

You can also add a custom chain by tapping the + button in that "Enabled Networks" screen.

Custom chains are shown in the same screen (Settings > Select Active Networks), but they are:

* Currently not indicated as a custom chain, so users can't tell (out of scope here)
* Can be swiped to delete
* Can't be swiped to edit (this is what this issue is about)

In scope
---
* Swipe a custom chain to reveal an Edit and Delete button
* Implement the Edit functionality
* Duplicate/Modify the "Add Custom RPC Network" screen (accessible by tapping +) screen to make it support editing

Out of scope
---
* Icons for Edit and Delete button after swiping custom chain

Because our Infura key (see `Constants+Credentials.swift`) is included in the repo, it's often rate limited. If adding the custom chain doesn't work and you notice `429`s in the console, try a different Infura key.

Refer to https://github.com/AlphaWallet/alpha-wallet-ios/issues/3216#issuecomment-953641735 for the swipe menu (but icons aren't necessarily)

**Comment by eviltofu** [comment]
The scope describes setting up the Delete button but not the delete function. Is the delete function to be hooked up to the button?

**Comment by hboon** [comment]
Sorry, I just have edited that part out. Delete is already supported when you swipe; so you only need to implement editing.

**Comment by eviltofu** [comment]
Is there a localised string for the edit button title or should I use `R.string.localizable.editButtonTitle()`? The delete button which was already implemented by someone else has a X using `R.string.localizable.delete()`. It doesn't look consistent.

**Comment by hboon** [comment]
`R.string.localizable.editButtonTitle()` is fine.

**Comment by eviltofu** [comment]
How do I validate a CustomRPC?

**Comment by eviltofu** [comment]
Are duplicate chainName, symbol, rpcEndpoint, explorerEndpoint allowed when editing a CustomRPC?

**Comment by eviltofu** [comment]
What sort of activity need to be logged to the Analytics?

**Comment by eviltofu** [comment]
How do I indicate there are new entries to the localisation strings? Who do I inform so new translations can be added?

**Comment by hboon** [comment]
@eviltofu

> How do I validate a CustomRPC after editing it?

For validation logic, check how it's done when manually adding one (instead of via the browser). The title of that screen is "Add Custom RPC Network". UI for error messages/handling should be quite similar.

> Are duplicate chainName, symbol, rpcEndpoint, explorerEndpoint values allowed when editing a CustomRPC?

We don't check those (probably could check the endpoints just to be sure, but not at this moment). But it is important that chain ID is unique.

> What sort of activity need to be logged to the Analytics?

Ignore it for now

> How do I indicate there are new entries to the localisation strings? Who do I inform so new translations can be added?

Don't have to. Just make sure to update all 5 string files with the same English version

**Comment by eviltofu** [comment]
There is a side effect where if you select/deselect several servers, then edit a custom server, the new selected server don't appear to be saved. Am I to fix this?

**Comment by hboon** [comment]
If it's because of adding editing support than would be good to include it (as a separate commit (if that's possible). If it's not related to editing, then would be great if you can just create an issue.

**Comment by eviltofu** [comment]
This flaw is present when I manually add a network so I believe it is an existing bug.

**Comment by eviltofu** [comment]
Also why does the UI drop back to the main screen after manually adding or editing? Should it not be in the previous screen instead of jumping two screens down?

**Comment by hboon** [comment]
> Also why does the UI drop back to the main screen after manually adding or editing? Should it not be in the previous screen instead of jumping two screens down? This also happens after I select / deselect a server and hit the back button.

Technical constraint. Some of the resources for connecting to servers was never designed to clean up well so killing all of them is much easier. There's a whole bunch of logic for fetching from each server running.
