### ISSUE TITLE
WalletConnect v2

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#3413]
* Docs: https://docs.walletconnect.com
* SDK
    * Swift: https://github.com/WalletConnect-Labs/WalletConnectSwiftV2
        * Doc mentions requires minimum deployment iOS 13 (but doesn't seem so in practice?)
    * Kotlin: https://github.com/WalletConnect-Labs/WalletConnectKotlinV2
* Test sites
    Test wallet site
       https://react-wallet.walletconnect.com
    Test dapp site
        https://react-app.walletconnect.com

Observations
---
* Different version number in the wc URL
    * v2 vs v1 example (@2 vs @1)
    * wc:ea6410bc3ea20864f4331095335e0d3a23f5e70820f00f8edae9ec14eeb33917@2?controller=false&publicKey=35af052875ac113c6efab51934c8fa7967990345b6dfeb2a0a8b964693350c32&relay=%7B%22protocol%22%3A%22waku%22%7D and wc:2fa9b5c0-37f9-498f-b975-7874a6cf74b5@1?bridge=https%3A%2F%2Fs.bridge.walletconnect.org&key=6d9e4064d39e574dcdb0218ab31b2d2bb2a60ca15ebf42d0ead9d2a327de396f
* Allow requesting a set of chains
* Wallet no longer controls the chain ID of the chain, but session tracks multiple chain IDs
* Dapp requests permission to use a set of JSON-RPC methods (and whether they are supported)
* Session expiry, default to 7 days
* What are "pairings"? Decouples session from peer to peer pair
* Each session gets (after requesting and granted access) access to multiple wallets/accounts and chains

Wallet
---
* List all active sessions
* User can expand each session to check which account(s) and chain(s)
* Disconnect sessions
* Grant permissions for requested (and supported) JSON-RPC methods dapp needs

> Dapps should request upfront as many chains as possible from the wallet to expose in order to allow the user to control which chain and/or account is using directly from the dapp.
    https://docs.walletconnect.com/protocol/ux-considerations
    Doesn't sound like a good design choice

> Account decoupling
    This more relevant for Wallets where some multi-account wallets have the concept of an "active" account on their interface. This should be completely decoupled from the session state on WalletConnect 2.0. A user should be able to expose and sign methods targetted at an account that is different than the active one in the wallet.
        https://docs.walletconnect.com/protocol/ux-considerations
        We can be limited to 1 account at a time (because we have the concept of an active wallet), for now?

**Comment by hboon** [comment]
A few screenshots to highlight how some of the information/hierarchy changes:

v2 Prompt to connect|v1 Prompt to connect
-|-
<img width="300" alt="Screenshot 2021-11-05 at 4 24 53 PM" src="https://user-images.githubusercontent.com/56189/140481726-af521a29-494b-433b-84ab-b838b631fb10.png">|<img width="300" alt="Screenshot 2021-11-05 at 4 32 12 PM" src="https://user-images.githubusercontent.com/56189/140481734-e819fad4-7eba-4ce7-8eae-81659819e421.png">

v2 Session information|v1 Session information
-|-
<img width="300" alt="Screenshot 2021-11-05 at 4 25 08 PM" src="https://user-images.githubusercontent.com/56189/140481743-5351841b-876b-4605-a055-d7881d07c730.png"><br>The information from v1 is still needed, but there can be more than 1 chain in the session and it has the concept of approved JSON-RPC calls|<img width="300" alt="Screenshot 2021-11-05 at 4 25 53 PM" src="https://user-images.githubusercontent.com/56189/140481745-1ecd272a-4741-470f-92ab-aa4e910d7cda.png">

v2 List of sessions | v1 List of sessions
-|-
<img width="300" alt="Screenshot 2021-11-05 at 4 25 48 PM" src="https://user-images.githubusercontent.com/56189/140481739-aa6108f0-00e0-43d3-a8e5-810d56faf3b8.png">|Similar, but can't show the (one) tiny icon for the chain, since there can be more than 1 chain accessible in each session

**Comment by hboon** [comment]
We'll need to support both WalletConnect v1 and v2 at the same time in the app and since it's possible for users to connect to a dapp that uses v1 and another that uses v2, the UI have to display sessions from both in the same list.

We need to:

- [ ] Add support for v2
- [ ] Continues to support v1
- [ ] The correct version to use is detected by reading the `wc:` URL/QR code
- [ ] Add or modify existing UI, eg. prompt connection, list of sessions, session details screen to support both v1 and v2 at the same time

We need to figure out the UI changes needed so we can have Tomek help to design an updated version so we should also:

- [ ] Implement support for v2 so that if the user only uses v1, they can't tell v2 is supported (within reason)

Followups:

- [ ] Design production UI
- [ ] Implement design

**Comment by vladyslav-iosdev** [comment]
@hboon are u able to geenrage qr code with https://react-app.walletconnect.com/ app? not sure how to test the app

**Comment by hboon** [comment]
@vladyslav-iosdev yes, you need to tap to select the chain(s) you want to connect with:

1. Tap Ethereum Kovan
2. Tap Optimistm Kovan
3. Tap Connect
4. Tap New Pairing

**Comment by vladyslav-iosdev** [comment]
for me, after pasting url nothing happens, i will try to scan qr code

**Comment by hboon** [comment]
Where do you paste the URL? Are you testing with the test wallet site? https://react-wallet.walletconnect.com. That worked for me a few days ago.

**Comment by vladyslav-iosdev** [comment]
<img width="1904" alt="Screenshot 2021-11-12 at 09 37 12" src="https://user-images.githubusercontent.com/55975226/141428529-a2271cf1-a432-4304-80e8-d262402abd79.png">

**Comment by vladyslav-iosdev** [comment]
and here https://react-app.walletconnect.com/ for me it displays lik
<img width="398" alt="Screenshot 2021-11-12 at 09 38 04" src="https://user-images.githubusercontent.com/55975226/141428657-0f22f2bc-ffc9-499d-86ff-d300211a8b6e.png">
e

**Comment by hboon** [comment]
Strange. Try Safari in private mode.

Dapp:

<img width="496" alt="Screenshot 2021-11-12 at 3 38 52 PM" src="https://user-images.githubusercontent.com/56189/141428964-b20f14e0-b1bf-4f31-8e76-b1bc52f2a68d.png">

Wallet after pasting URL:

<img width="496" alt="Screenshot 2021-11-12 at 3 38 52 PM" src="https://user-images.githubusercontent.com/56189/141428912-fcf89cf5-a855-461a-afea-7b5863906903.png">

**Comment by vladyslav-iosdev** [comment]
ok, thx, checking!

**Comment by vladyslav-iosdev** [comment]
@hboon i currently stuck here, as there some topics and visibility of some needed properties. Created a few PRs, and waiting for approvance from guys now.

**Comment by hboon** [comment]
@vladyslav-iosdev great. Thanks! You can use a local fork of the v2 SDK in the mean time right? But yes, we should still get them to merge it upstream.
