### ISSUE TITLE
Search UI in Activities broken with spurious white background

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#3416]
Screenshot is taken on device iOS 15. Should verify on device if this is a problem. Can't reproduce on simulator

<img width='200' src='https://user-images.githubusercontent.com/56189/140867687-e2e2687d-665b-47ea-9e16-2d920f7a4248.PNG'>

**Comment by vladyslav-iosdev** [comment]
i wasn't be able to reproduce it with real device on iOS 15 os version.
