### ISSUE TITLE
When selecting/deselecting networks on the chain list screen, enable/disable changes are not saved if the new chain is saved

### ISSUE THREAD

**Issue by eviltofu** [AlphaWallet/alpha-wallet-ios#3420]
When in the enabled network screen, a user selects / deselects one or more networks. Then the user deletes a custom network or adds a custom network. The changes made to the selections are not preserved.

The following instructions assume the Expanse Network has not been previously added.

1. Tap the settings tab button when on the Home Screen.
2. Tap the select active networks table row.
3. Tap on  some of the selected networks to deselect them.
4. Tap on some of the unselected networks to select them.
5. Tap the + button in the upper right hand corner to add a network.
6. Type "Expanse Network" in the network name field.
7. Type "https://node.expanse.tech" in the RPC URL field.
8. Type "2" in the Chain ID field.
9. Type  "EXP" in the Symbol field.
10. Type "https://expanse.tech" in the Block Explorer URL field.
11. Tap "Save network" button. 
12. When "Warning" alert pops up hit continue.
13. After a few moments, the home screen will be shown with the wallet tab selected.
14. Tap settings tab button 
15. Tap select active networks

**Expect**
16a. Selections made to networks be changed. 

**Observed**
16.b Selections made to networks were not changed.

Version 3.29 Build 408

**Comment by hboon** [comment]
Reproducible with 51d2414

**Comment by hboon** [comment]
@eviltofu thanks for filing issues clearly.
