### ISSUE TITLE
Spurious (2nd) dialog after hitting cancel when manually adding a network 

### ISSUE THREAD

**Issue by eviltofu** [AlphaWallet/alpha-wallet-ios#3421]
When adding a network manually, hitting the cancel option when presented with a warning about unresolved Block chain URLs results in a redundant Error alert.

1. Tap the settings tab button when on the Home Screen.
2. Tap the select active networks table row.
3. Tap the + button in the upper right hand corner to add a network.
4. Type "Expanse Network" in the network name field.
5. Type "https://node.expanse.tech" in the RPC URL field.
6. Type "2" in the Chain ID field.
7. Type "EXP" in the Symbol field.
8. Type "https://expanse.tech" in the Block Explorer URL field.
9. Tap "Save network" button. 
10. When "Warning - Blockchain explorer URL can't be resolved..." alert pops up hit cancel.

**Expects**
11a. The alert to disappear.

**Observes**
11b. "Error - No blockchain explorer URL provided" alert pops up.

Version 3.29 Build 408

**Comment by hboon** [comment]
Reproducible with 51d241451ea627d45998352640338afbf34b5909

We should not show the 2nd dialog: "No blockchain explorer URL provided".
