### ISSUE TITLE
How to update token list with right balances and remaining tokens?

### ISSUE THREAD

**Issue by colourfreak** [AlphaWallet/alpha-wallet-ios#3431]
So looking at the list here, I know that it has only two tokens on Optimism Ethereum. 

![2021-11-15 08 12 58](https://user-images.githubusercontent.com/51817359/141741483-c5c836e9-812e-4200-bbb9-57430044aa9c.png)
But I know that I have more tokens on Optimism. 

<img width="514" alt="Screenshot 2021-11-15 at 08 40 40" src="https://user-images.githubusercontent.com/51817359/141741291-51faa061-4138-47ad-9789-c9b9f77ebcb8.png">

So I want to refresh the list to display them all. So I try this method:

https://user-images.githubusercontent.com/51817359/141741376-f21ddfe9-079c-4dfa-94c2-2245efc846a4.mp4

And it does not work either. Shall pull down to refresh update the list? I don't see any other usage of this.

**Comment by colourfreak** [comment]
I forgot about the wallet and re-imported it with the seed phrase. Same story. It does not display the full list.
When I removed the app and reinstalled it again. Does not work either.

**Comment by hboon** [comment]
Closing now. We fix this continously in various issues/ways. But haven't quite address it across the board though
