### ISSUE TITLE
Move the search bar down, move Add/Hide Tokens

### ISSUE THREAD

**Issue by colourfreak** [AlphaWallet/alpha-wallet-ios#3444]
**Changes:**
* Replace "My Wallet Address" with the additional menu icon
* When revealed additional menu, show two options "My Wallet Address" and "Add/Hide Tokens"
* Move search bar where "Add/Hide Tokens" was before

**Positives**
* More clear interface
* Less real estate occupied by "Add/Hide Tokens"
* We allow Android to be identical to iOS, and it was difficult to include a search bar anywhere on Android
* I found people are confused what's behind these two icons in the top right (when people are looking for QR Code scanner, do I have to tap on "QR Code" icon or "Camera"?

<img width="1584" alt="Screenshot 2021-11-17 at 10 05 16" src="https://user-images.githubusercontent.com/51817359/142170303-4aa1db47-dbd8-44bb-952a-61514bc8a959.png">

**Comment by hboon** [comment]
Vlad: can you try to retain that behavoir where the navigation bar is hidden when the taps the search bar and search if it's not too hackish? UISearchbar is too fragile for tricks, so if it's not feasible, never mind.

@colourfreak remember the option to copy wallet address too.

**Comment by vladyslav-iosdev** [comment]
ok, sure i will try

**Comment by colourfreak** [comment]
https://zpl.io/brOBvJX
https://zpl.io/VkPqp8g
![Wallet_Menu](https://user-images.githubusercontent.com/51817359/142404248-9001bb57-7167-44e4-b409-fbd72fdaf6c7.jpg)
![Wallet_New](https://user-images.githubusercontent.com/51817359/142404256-8c5be6b1-129b-4341-aca2-d0e618271872.jpg)
