### ISSUE TITLE
Eden icon

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#3445]
We are adding support for Eden as another option, alongside Ethermine for users to send their transactions privately. Would you help to create an appropriate icon for it to appear in this screen?

<img width="300" alt="Screenshot 2021-11-18 at 2 05 33 PM" src="https://user-images.githubusercontent.com/56189/142361343-7b4fe654-f114-44e3-b99b-45ba0d14e170.png">

They gave us these:

![EDN_Logo_02_EDEN_Logo_Colour Navy](https://user-images.githubusercontent.com/56189/142361695-d9362f5a-42f1-4d69-8e98-66298ab509e7.png)
![EDN_Logo_02_EDEN_Logo_Colour White](https://user-images.githubusercontent.com/56189/142361698-9df27d7e-1e80-405b-9fd9-b690923fd0db.png)
![EDN_Logo_02_EDEN_Mark_Colour (1)](https://user-images.githubusercontent.com/56189/142361703-f86e9264-8ce5-47c9-90b8-299a8785782a.png)

**Comment by colourfreak** [comment]
https://zpl.io/VO3O5gj
