### ISSUE TITLE
Allow users to import a wallet with 24 seed phrase

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#3447]
Refer https://github.com/AlphaWallet/alpha-wallet-android/issues/2204#issuecomment-972776818

- [x] Also need to check for references to "12 words seed phrases" or similar in the app
- [x] Also need to check if export functionality needs to be changed
- [x] Hide functionality behind a `Features` flag.
- [ ] Check verify seed phrase screen works for both 12-words and 24-words. This might not be accessible on the simulator due to #3609. This is accessible via Settings > Back up this Wallet > Back up my Wallet
  
* Let's just not allow user to create them at the moment

**Comment by hboon** [comment]
@eviltofu may need some context but see what you can discover by yourself.

**Comment by eviltofu** [comment]
As far as I can tell, accepting a 24 word seed phrase is not a problem. The problem appears to be generating a 24 word seed phrase. The 12 word seed phrase is generated by the `mnemonic` property of a `HDWallet` via `TWHDWalletMnemonic` which takes an `OpaquePointer`. I'm looking at the GitHub repository and 
```
TWString *_Nonnull TWHDWalletMnemonic(struct TWHDWallet *_Nonnull wallet){
    return TWStringCreateWithUTF8Bytes(wallet->impl.getMnemonic().c_str());
}
``` 
is as far as I got. I could not find any function definition for `getMenemonic`.

**Comment by eviltofu** [comment]
I was able to generate a 24 word seed phrase from an [external](https://iancoleman.io/bip39/) web site (iancoleman.io). The current master branch (85ca64640f11dd01728e624c48d1948ec018a81d) does not allow the 24 word phrase to be imported. I had to disable the mnemonic checks because the mnemonic generated by our code is only 12 words long.
```
    private func doesSeedMatchWalletAddress(mnemonic: String) -> Bool {
        let wallet = HDWallet(mnemonic: mnemonic, passphrase: emptyPassphrase)
        // Removed mnemonic check
        // guard wallet.mnemonic == mnemonic else { return false }
        let seed = HDWallet.computeSeedWithChecksum(fromSeedPhrase: mnemonic)
        let walletWhenImported = HDWallet(seed: seed, passphrase: emptyPassphrase)
        //If seed phrase has a typo, the typo will be dropped and "abandon" added as the first word, deriving a different mnemonic silently. We don't want that to happen!
        // Removed mnemonic check
        // guard walletWhenImported.mnemonic == mnemonic else { return false }
        let privateKey = derivePrivateKeyOfAccount0(fromHdWallet: walletWhenImported)
        let address = AlphaWallet.Address(fromPrivateKey: privateKey)
        let testData = "any data will do here"
        let hash = testData.data(using: .utf8)!.sha3(.keccak256)
        //Do not use EthereumSigner.vitaliklizeConstant because the ECRecover implementation doesn't include it
        guard let signature = try? EthereumSigner().sign(hash: hash, withPrivateKey: privateKey) else { return false }
        guard let recoveredAddress = Web3.Utils.hashECRecover(hash: hash, signature: signature) else { return false }
        //Make sure the wallet address (recoveredAddress) is what we think it is (address)
        return address.sameContract(as: recoveredAddress.address)
    }
```

**Comment by eviltofu** [comment]
The app only has TWO textual instances where the 12 word seed phrase is mentioned. Both are in the localised strings.

"Making backup is very simple and safe:\n just write down 12 words and\n keep them in a secret place, offline."
"Seed phrase has to be 12 words"

**Comment by eviltofu** [comment]
@hboon how do we proceed? It looks like we need a way to generate 24 word seed phrases.

**Comment by hboon** [comment]
@eviltofu Ok, so assuming that you have tweaked it so we can import (but not generate 24 word seed phrase), what are the blockers?

> It looks like we need a way to generate 24 word seed phrases.

We don't want to add support to the UI to generate 24 word seed phrases for users so we don't complicate the UI. Do we need to add it just in the code, but not as a feature for the user?

> The app only has TWO textual instances where the 12 word seed phrase is mentioned. Both are in the localised strings.

Let's keep these references as 12 words for now

**Comment by eviltofu** [comment]
> @eviltofu Ok, so assuming that you have tweaked it so we can import (but not generate 24 word seed phrase), what are the blockers?

We need to verify that the imported 24 word seed phrase account is valid. I got a crash earlier this morning but I'm not sure what the cause is. 

> We don't want to add support to the UI to generate 24 word seed phrases for users so we don't complicate the UI. Do we need to add it just in the code, but not as a feature for the user?

Only in code for import wallet verification. 

> Let's keep these references as 12 words for now

One of them is an error message when your seed phrase is not exactly 12 words. That should be modified to say "Seed phrase has to be 12 or 24 words".

**Comment by hboon** [comment]
>> We don't want to add support to the UI to generate 24 word seed phrases for users so we don't complicate the UI. Do we need to add it just in the code, but not as a feature for the user?
> Only in code for import wallet verification.

Hmm.. not sure. But you can add it, then we can evaluate, unless it's a lot of work that coudld be thrown away. But since you know it is necessary, it probably is?

> One of them is an error message when your seed phrase is not exactly 12 words. That should be modified to say "Seed phrase has to be 12 or 24 words".

Sure.

**Comment by eviltofu** [comment]
> Hmm.. not sure. But you can add it, then we can evaluate, unless it's a lot of work that coudld be thrown away. But since you know it is necessary, it probably is?

Do you know offhand if there is a library that does this? And if it's possible to generate a 24 word seed phrase for ETH? The web page (iancoleman.io) didn't appear to let me generate a 24 word seed phrase for ETH.

**Comment by hboon** [comment]
https://iancoleman.io/bip39/ does generate 24 seed phrases. I just tried. You might need to click the GENERATE button 1 more time after the error message.

> Do you know offhand if there is a library that does this?

`WalletCore`, which we are using, already supports 24 seed phrases.

I think importing might be broken because it only supports 12 seed phrases, for the time being, modify `EtherKeystore.doesSeedMatchWalletAddress(mnemonic:)` to always return true and I think that should be ok for you to proceed. If you do that, remember to make a note in the PR, it's a very important function so we need to fix it before merging.

**Comment by eviltofu** [comment]
```
let wallet = HDWallet(strength: 256, passphrase: "nuts")
NSLog("->* \(wallet.mnemonic)")
```
Generates a 24 word seed phrase.

**Comment by hboon** [comment]
Yes, it does. Remember to use "" as the passphrase.

**Comment by eviltofu** [comment]
Spanish, Chinese localisations for "importWallet.import.invalidMnemonicCount" has to be updated to reflect 24 word seed phrase.

**Comment by eviltofu** [comment]
EtherKeystore.swift:343
```
let seed = HDWallet.computeSeedWithChecksum(fromSeedPhrase: mnemonic)
let walletWhenImported = HDWallet(seed: seed, passphrase: emptyPassphrase)
//If seed phrase has a typo, the typo will be dropped and "abandon" added as the first word, deriving a different mnemonic silently. We don't want that to happen!
guard walletWhenImported.mnemonic == mnemonic else { return false }
```
This part is failing because for a 24 word phrase, the `seed` computed creates a wallet which has `""` as it's `mnemonic`. I don't know enough about the math to fix the code.

**Comment by eviltofu** [comment]
> ```
> let wallet = HDWallet(strength: 256, passphrase: "nuts")
> NSLog("->* \(wallet.mnemonic)")
> ```
> 
> 
>     
>   
> 
> Generates a 24 word seed phrase.

Mnemonic generated via this method does not appear to work when I try to import the seed phrase via the app.

**Comment by eviltofu** [comment]
EtherKeystore.swift:344
```
let walletWhenImported = HDWallet(seed: seed, passphrase: emptyPassphrase)
```
HDWallet+Extension.swift:30
```
self.init(data: Data(_hex: HDWallet.leftPadStringWithZero(seed, to: 33)), passphrase: passphrase)
```
But the length of the seed is 66 for 24 word see phrase. Increasing the length to 66 still results in an invalid account.

**Comment by hboon** [comment]
@eviltofu can you push to a branch first? And add commits/comments if relevant to reproduce?

**Comment by hboon** [comment]
I have updated the first comment in this issue with this: can you help hide this functionality behind a `Features` flag? I just realized the backup screen might be affected (e.g the longer seed phrase might not fit). So better to try it out a bit more first, but we can get the core merged with the flag disabled first to not stretch out the PR.

**Comment by eviltofu** [comment]
> @eviltofu can you push to a branch first? And add commits/comments if relevant to reproduce?

The branch you want me to push allows the 24 seed phrase to be accepted? I just disable the failing checks to allow the creation of the wallet?

**Comment by hboon** [comment]
@eviltofu updated 1st comment above to include this:

* Check verify seed phrase screen works for both 12-words and 24-words. This might not be accessible on the simulator due to #3609

Sorry, miss this earlier.
