### ISSUE TITLE
Redesign ERC721 to be align with recent ERC1155 update we made [ERC721]

### ISSUE THREAD

**Issue by colourfreak** [AlphaWallet/alpha-wallet-ios#3448]
The good news is, that we already made the layout for ERC1155 (at least on Android), which now can be applied to the ERC721 redesign. Note, that unlike ERC1155, in the Assets tab you will not find the menu icon in the top right. Since there no way for multiple selection, I skipped it. 

**Zeplin:**
https://zpl.io/bzzgow7

![ERC721-ios](https://user-images.githubusercontent.com/51817359/142427701-fe4eb5bb-4526-4b67-84c7-de9096c81e9c.jpg)

**Other Zeplin examples**
https://zpl.io/agEY0nR
https://zpl.io/2jK60A4
https://zpl.io/VK3RgX8

https://user-images.githubusercontent.com/51817359/142426556-8be43902-ea56-4741-b0c9-1f77eadca9db.mov

**Comment by hboon** [comment]
@vladyslav-iosdev probably ready to go after #3411
