### ISSUE TITLE
Improve how Collectibles tab look like in the wallet [ERC721]

### ISSUE THREAD

**Issue by colourfreak** [AlphaWallet/alpha-wallet-ios#3449]
We need to make this component and apply it to all Collections:
https://zpl.io/VD3E0we
https://zpl.io/2vXJZ47

![Wallet-Collectibles](https://user-images.githubusercontent.com/51817359/142430392-6ba68d1d-27d1-4587-a3f8-8a4bc3e4674b.jpg)

**Comment by colourfreak** [comment]
Is this now in the new build 414? @hboon

**Comment by hboon** [comment]
@colourfreak no, not yet. But will be in the next one.
