### ISSUE TITLE
Fix SwiftLint results not appearing in build results

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#3451]

**Comment by eviltofu** [comment]
### SwiftLint is working correctly. 
The .swiftlint.yml file has disabled a lot of the rules. Deleting `trailing_whitespace` in the `disabled_rules` section of the file makes the warnings appear again. 
### Build Phases position
In the build phases of the AlphaWallet target, the `Run SwiftLint` phase is after the `Compile sources` phase. The SwiftLint home page recommends that the lint phase be run before the compile phase. I will submit a pull request that corrects this.

**Comment by hboon** [comment]
It's working.
