### ISSUE TITLE
Next button (keyboard) should scroll screen so textfield is visible for EditCustomRPCViewController

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#3453]
Probably the add equivalent too.

**Comment by eviltofu** [comment]
The number pad has no next button. Perhaps a previous (<) and next (>) button should be set up on top of all the keyboards in this screen to move the focus.

**Comment by hboon** [comment]
Yeah, it's a funny thing with the built-in numeric keyboard.

If you do it, can you do it in a separate PR? Because there are a few screens that use it. Same general approach, you can either add it just for this save custom chain screen or all of them at one go (if the changes don't look massive).

**Comment by eviltofu** [comment]
Also, the url text fields should have a https:// button. This should go into another pull request?

**Comment by hboon** [comment]
Yeah, sounds like they are different things. For example, if it's a single screen that's affected with these:

* Make numeric fields use numeric keyboard
* Make URL fields have http button

Then it's perfectly fine to be in a single PR.

**Comment by eviltofu** [comment]
> Yeah, it's a funny thing with the built-in numeric keyboard.
> 
> If you do it, can you do it in a separate PR? Because there are a few screens that use it. Same general approach, you can either add it just for this save custom chain screen or all of them at one go (if the changes don't look massive).

Searching shows 4 instances of .numberPad and 7 instances of .decimalPad keyboards. I should add only for this screen and then we add the rest one by one.

**Comment by eviltofu** [comment]
@hboon On iPad, the decimal pad does have the NEXT button.
