### ISSUE TITLE
What's new dialog upon 1st launch after app is update

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#3462]
Show a list of changes. Textual, for example the following, but probably shorter:

> * Siri shortcut to show your wallet QR code, available in Siri suggestions and Spotlight
> * Custom RPC servers can now be modified
> * Improve ENS avatar support for SVG
> * Many UI tweaks
> * Bug fixes

Users tend not to read release notes especially if they have auto-update enabled. Also opens up the opportunity to use the same UI to highlight specific 1-2 features at selected times.

Might tweak this format to just be about a single feature with a lengthier feature in the future, but let's roll something out first.

**Comment by colourfreak** [comment]
Zeplin:
https://zpl.io/V4X8jk4

![Wallet_News](https://user-images.githubusercontent.com/51817359/143019888-b6c07df3-b8a8-47f4-8eaf-cbf80ff0dda0.jpg)

**Comment by hboon** [comment]
Thanks!

**Comment by hboon** [comment]
@vladyslav-iosdev I thought you added a base class that provides this actionsheet-type look and feel but I don't remember which. Can you help to point out which one this is or a similar one which we can base this screen on? It's just used to display some static text from a data source.

@eviltofu can you help to build this? So a new coordinator + UIViewController (or child) subclass with some hardcoded content (read from a hardcoded variable) and a way to trigger it. You can hook it up to the camera button you see in the Wallet tab for now and I'll wire in some logic when you are done.

I have asked Tomek to help add you to Zeplin.

**Comment by vladyslav-iosdev** [comment]
@eviltofu Look up for `ModalViewController`, its prettry what u need

**Comment by eviltofu** [comment]
Does this have to be multilingual?

**Comment by hboon** [comment]
Probably not. At least not now. Why does it matter?

**Comment by eviltofu** [comment]
How does this handle scrolling when there are too many items to display? Does the "What's new?" stay and the other news items scroll? @colourfreak

**Comment by hboon** [comment]
It should scroll. `ModalViewController` has a `UIScrollView`. Use that. The original idea is for the whole view to scroll up, but leave it for now unless it's built into `ModalViewController`.

**Comment by eviltofu** [comment]
How is colour defined in the app? I see colours defined in `Assests.xcassets` and `AppStyle.swift`. Can we stick with one?
