### ISSUE TITLE
Empty UI tests should be removed

### ISSUE THREAD

**Issue by eviltofu** [AlphaWallet/alpha-wallet-ios#3470]
The Empty UI tests are failing and prevents testers from running unit tests via CMD-T. These Empty UI tests should be removed.

**Comment by eviltofu** [comment]
Can the tests be randomised? Right now the tests all run in sequence. I'd like a random order to throw up more errors. 
I've found that `AppCoordinatorTests` fails when not run early in the tests sequence.

**Comment by hboon** [comment]
No idea
