### ISSUE TITLE
Unexpected and very long error message when saving custom rpc

### ISSUE THREAD

**Issue by eviltofu** [AlphaWallet/alpha-wallet-ios#3482]
When the RPC URL field in a CustomRPC is a valid URL but does not point to any actual location, the following error message is given. An example of such a url is https://node.expanse.tect.

![error](https://user-images.githubusercontent.com/1050309/143564712-c9bd214e-dc2c-4aa3-a026-8baeca858b28.png)

A better error message should be used.

**Comment by hboon** [comment]
Seems like it should appear as how errors look like when filing in the form

<img width="300" alt="Screenshot 2021-11-30 at 10 56 47 AM" src="https://user-images.githubusercontent.com/56189/143977736-1ceab5cc-8cc1-4ed2-801a-f8c2c9818954.png">
