### ISSUE TITLE
Add Dark Mode

### ISSUE THREAD

**Issue by colourfreak** [AlphaWallet/alpha-wallet-ios#3483]
# Dark mode conversion checklist

- [x] [Launch Screen](https://github.com/AlphaWallet/alpha-wallet-ios/pull/4700)
- [x] [Initial Wallet Creation](https://github.com/AlphaWallet/alpha-wallet-ios/pull/4830) 
- [x] [Initial Network Selection Screen](https://github.com/AlphaWallet/alpha-wallet-ios/pull/4955)
- [x] [Main wallet tab](https://github.com/AlphaWallet/alpha-wallet-ios/pull/5159)
- [x] [Main wallet tab overlay](https://github.com/AlphaWallet/alpha-wallet-ios/pull/5203)
- [x] Change wallet screen
- [x] Browser tab (at least the url/textbox color as well as "home" screen which has the "My Bookmarks" button)
- [x] #5394
- [x] #5395

In each branch's info.plist, the Appearance settings have been switched to _Automatic_ for testing purposes. Before merging, please switch the Appearance settings to _Light_.

## Edit

The screen shots posted here do not represent the current colour scheme. Follow the Zeppelin guides.

## Original Post

There are several rules which we have to follow, for quicker implementation
I will try to describe it as much as I can. 

- Dove #727272 to Dusty #999999
- Azure #007fed to Dodge #0c84ff
- White #ffffff bg to Cod #141414
- Green remains the same
- Alabaster #fbfbfb to Venus #232323
- Mercury #e9e9e9 to Venus #232323
- Mine #2f2f2f to White #ffffff

Zeplin:
https://zpl.io/VD3jRYq

![Wallet_Summary_New_Dark](https://user-images.githubusercontent.com/51817359/143593737-bfb927cc-0155-485f-929e-fe3af76907b3.jpg)
![Welcome_Dark](https://user-images.githubusercontent.com/51817359/143593741-4662b2ab-fa96-4b2d-8b64-dd0dc65e0035.jpg)
 ![Add_Custom_RPC_Entered_Dark](https://user-images.githubusercontent.com/51817359/143593707-3a5e3b87-e7dc-4641-99c0-b05aae1bcc84.jpg) 
![AS_Send_ETH_Confirm_Dark](https://user-images.githubusercontent.com/51817359/143593710-6f10bb3e-86b2-4bd8-956a-af0adfa4fc57.jpg)
![Activity_Send_Opened_ETH_Dark](https://user-images.githubusercontent.com/51817359/143593697-bef33264-e64c-4f0a-a903-c542271b7314.jpg)
![Backup_Introduction_Dark](https://user-images.githubusercontent.com/51817359/143593711-ade163f1-eae7-4d31-965d-6bae7d9c3eb3.jpg)
![Backup_Write_Down_Dark](https://user-images.githubusercontent.com/51817359/143593715-9eebd2fd-a8c2-4f3b-a885-a8b630781185.jpg)
![ETH_Activity_Dark](https://user-images.githubusercontent.com/51817359/143593717-8b85e3a6-1ffe-45f2-8ba0-516b324518ec.jpg)
![ETH_Alert_Dark](https://user-images.githubusercontent.com/51817359/143593719-55b07d81-ed0f-4963-89b8-d227ad58845f.jpg)
![ETH_Info_Dark](https://user-images.githubusercontent.com/51817359/143593720-8f26cbed-a221-470a-85ec-f1fd8fea6bde.jpg)
![Import_Keystore_Pass_Empty_Dark](https://user-images.githubusercontent.com/51817359/143593722-c541e617-9124-410d-bfa6-c1149af2c0b1.jpg)
![My_Wallet_Address_Dark](https://user-images.githubusercontent.com/51817359/143593723-4fcca70d-0099-4721-b349-2af65de63921.jpg)
![Send_ETH_Entered_Dark](https://user-images.githubusercontent.com/51817359/143593725-a4ac742b-f5ab-40fb-a691-0d8178ab1f82.jpg)
![Settings_Backup_Warning_Dark](https://user-images.githubusercontent.com/51817359/143593728-d5d797ea-1223-41af-811f-b26fdd9bbc81.jpg)
![Settings_Default_Reveal_Dark](https://user-images.githubusercontent.com/51817359/143593731-a2b7d431-9a57-4755-aef3-a03732af18f1.jpg)
![Settings_Select_Active_Network_RPC_Dark](https://user-images.githubusercontent.com/51817359/143593733-97482e5e-0d76-486b-a034-ea8008acc12e.jpg)
![Settings_Support_Dark](https://user-images.githubusercontent.com/51817359/143593734-2c7635c9-3a17-4ae0-b022-b5f812db5073.jpg)
![Wallet_New_Dark](https://user-images.githubusercontent.com/51817359/143593736-c93e744f-7974-4a8a-9f01-039cbd301e51.jpg)

**Comment by colourfreak** [comment]
**Import/Create new wallet screen wallet**

White #ffffff background becomes Cod #141414
The secondary button changes the background color to Mine #2f2f2f

<img width="1626" alt="Screenshot 2021-11-26 at 15 08 04" src="https://user-images.githubusercontent.com/51817359/143594376-f6e825d3-0d7d-42c8-b798-dda84b836746.png">

**Comment by colourfreak** [comment]
**ERC20 Token**
https://zpl.io/a3J4611

- All separators (thin 1pt horizontal lines, mostly in Mercury #e9e9e9) becomes Venus #232323
- Whenever we have a gray text Dove #727272 it becomes Dusty #999999
- All blue Azure #007fed becomes Dodge #0c84ff
- Background behind Action buttons from White #FFFFFF goes to Venus #232323
- Background from White #ffffff to Cod #141414

<img width="1744" alt="Screenshot 2021-11-26 at 15 50 21" src="https://user-images.githubusercontent.com/51817359/143598284-6231cd04-1052-43ae-8c79-f315dc484cfe.png">

**Comment by colourfreak** [comment]
**Wallet**
https://zpl.io/blnKyD1

- All separators (thin 1pt horizontal lines, mostly in Mercury #e9e9e9) becomes Venus #232323
- Whenever we have a gray text Dove #727272 it becomes Dusty #999999
- Tab Bar icons were Dove #727272 now becomes Dusty #999999
- All blue Azure #007fed becomes Dodge #0c84ff
- Background behind Action buttons from White #FFFFFF goes to Venus #232323
- Background from White #ffffff to Cod #141414
- Search Bar bg becomes Mine #2F2F2F

<img width="1774" alt="Screenshot 2021-11-26 at 16 09 11" src="https://user-images.githubusercontent.com/51817359/143600594-4bd505b2-19e4-4527-8aa2-d923348a2898.png">

**Comment by colourfreak** [comment]
**Transaction screen**
https://zpl.io/bW3MvN1

- All separators (thin 1pt horizontal lines, mostly in Mercury #e9e9e9) becomes Venus #232323
- Whenever we have a gray text Dove #727272 it becomes Dusty #999999
- All blue Azure #007fed becomes Dodge #0c84ff
- Background from White #ffffff to Cod #141414
- Search Bar bg becomes Mine #2F2F2F

<img width="1784" alt="Screenshot 2021-11-26 at 16 20 09" src="https://user-images.githubusercontent.com/51817359/143602086-977185d8-d784-4070-b726-68e89a4f4224.png">

**Comment by colourfreak** [comment]
**Confirmation**
https://zpl.io/brOqgvr

- Only in this screen separators (thin 1pt horizontal lines, mostly in Mercury #e9e9e9) becomes Cobalt #444444
- Whenever we have a gray text Dove #727272 it becomes Dusty #999999
- All blue Azure #007fed becomes Dodge #0c84ff
- Background from White #ffffff to Cod #141414

<img width="1751" alt="Screenshot 2021-11-26 at 16 31 47" src="https://user-images.githubusercontent.com/51817359/143603370-b7d60945-47a3-41e2-a16f-ca7e44e87aa2.png">

**Comment by colourfreak** [comment]
Settings
https://zpl.io/awlzpJg

- All separators (thin 1pt horizontal lines, mostly in Mercury #e9e9e9) becomes Venus #232323
- Whenever we have a gray text Dove #727272 it becomes Dusty #999999
- Tab Bar icons were Dove #727272 now becomes Dusty #999999
- All blue Azure #007fed becomes Dodge #0c84ff
- Background behind Action buttons from White #FFFFFF goes to Venus #232323
- Background from White #ffffff to Cod #141414
- Warning bg remains the same Mine #2F2F2F

<img width="1719" alt="Screenshot 2021-11-26 at 16 38 03" src="https://user-images.githubusercontent.com/51817359/143604089-c1c36dac-30b6-477d-aa99-4bbf0344511a.png">

**Comment by eviltofu** [comment]
@colourfreak What about the navigation bar text colour?

**Comment by colourfreak** [comment]
> @colourfreak What about the navigation bar text colour? Currently, it is black.

White #ffffff Follow the intuition.

**Comment by colourfreak** [comment]
Note that we have recently changed button colors.

**Comment by hboon** [comment]
@eviltofu let's get started with this one. See if we can do this reasonably without any massive refactoring first? Small PRs as long as it doesn't affect the app functionally, example extracting colors that weren't previously extracted.

**Comment by eviltofu** [comment]
Current launch icon has white background. Can I get one with a transparent background? @colourfreak 

![image](https://user-images.githubusercontent.com/1050309/170617881-d1460e35-f13a-42fe-b318-424eaacdc039.png)

**Comment by colourfreak** [comment]
You have every thing in Zeplin. Do you want me to record you tutorial videos on how to use it? I'll be happy to do it.
https://zpl.io/r174MyD

**Comment by eviltofu** [comment]
> You have every thing in Zeplin. Do you want me to record you tutorial videos on how to use it? I'll be happy to do it.
> https://zpl.io/r174MyD

How do I find a logo in dark mode with dimensions 93x66? @colourfreak

**Comment by eviltofu** [comment]
@colourfreak Can you update the primary button colour specs in zeplin? I know the background is #green but I'm not sure what the text colour is. I'm using #white right now.

**Comment by colourfreak** [comment]
@eviltofu These designs are not up to date - mostly because you are starting working on them 7 months after I created this issue. We don't have green buttons anymore. I did not update this as I stopped believing it will be ever developed.

**Comment by hboon** [comment]
@eviltofu added to list in 1st commnt

**Comment by eviltofu** [comment]
Image | Notes | Status
|-|-|-|
![Wallet_Summary_New_Dark](https://user-images.githubusercontent.com/51817359/143593737-bfb927cc-0155-485f-929e-fe3af76907b3.jpg) | <p>**AccountsViewController**</p>From main wallet screen: <br>1. Tap Blockie image in upper left hand corner.</p>  | Completed
![Welcome_Dark](https://user-images.githubusercontent.com/51817359/143593741-4662b2ab-fa96-4b2d-8b64-dd0dc65e0035.jpg) | <p>**CreateInitialWalletViewController**</p> Delete the app and reinstall and rerun. This is the first screen that shows up. | Completed
![Add_Custom_RPC_Entered_Dark](https://user-images.githubusercontent.com/51817359/143593707-3a5e3b87-e7dc-4641-99c0-b05aae1bcc84.jpg) | <p>**SaveCustomRpcManualEntryViewController**</p> From main wallet screen: <br>1. Tap Settings.<br>2. Tap select active networks.<br> 3. Tap plus sign in upper right hand corner.<br> 4. Tap Enter Tab.  | Completed
![AS_Send_ETH_Confirm_Dark](https://user-images.githubusercontent.com/51817359/143593710-6f10bb3e-86b2-4bd8-956a-af0adfa4fc57.jpg) | <p>**TransactionConfirmationViewController**</p>From main wallet screen:<br> 1. Tap ETH.<br> 2. Fill in ETH amount, destination wallet address.<br> 3. Tap send. | Completed
![Activity_Send_Opened_ETH_Dark](https://user-images.githubusercontent.com/51817359/143593697-bef33264-e64c-4f0a-a903-c542271b7314.jpg) | <p>**TransactionViewController**</P>From main wallet screen:<br>1. Tap ETH.<br>2. Tap Activity.<br>3. Tap an activity.<br>4. Tap Upper right corner icon.  | Completed
![Backup_Introduction_Dark](https://user-images.githubusercontent.com/51817359/143593711-ade163f1-eae7-4d31-965d-6bae7d9c3eb3.jpg) | <p>**SeedPhraseBackupIntroductionViewController**</p>From main wallet screen:<br>1. Tap Settings. <br>2. Tap Back up your wallet. | Completed
![Backup_Write_Down_Dark](https://user-images.githubusercontent.com/51817359/143593715-9eebd2fd-a8c2-4f3b-a885-a8b630781185.jpg) | <p>**ShowSeedPhraseViewController**</p>From main wallet screen:<br>1. Tap Settings. <br>2. Tap Back up your wallet.<br>3. Tap button Back up your wallet at bottom of screen. | Completed
![ETH_Activity_Dark](https://user-images.githubusercontent.com/51817359/143593717-8b85e3a6-1ffe-45f2-8ba0-516b324518ec.jpg) | <p>**FungibleTokenViewController**</p>From main wallet screen:<br>1. Tap ETH. <br>2. Tap activity. | Completed
![ETH_Alert_Dark](https://user-images.githubusercontent.com/51817359/143593719-55b07d81-ed0f-4963-89b8-d227ad58845f.jpg) | | Missing
![ETH_Info_Dark](https://user-images.githubusercontent.com/51817359/143593720-8f26cbed-a221-470a-85ec-f1fd8fea6bde.jpg) | <p>**FungibleTokenViewController**</p>From main wallet screen:<br>1. Tap ETH. | Completed
![Import_Keystore_Pass_Empty_Dark](https://user-images.githubusercontent.com/51817359/143593722-c541e617-9124-410d-bfa6-c1149af2c0b1.jpg) | <p>**ImportWalletViewController**</p>From main wallet screen:<br>1. Tap blockie image in upper left corner.<br>2. Tap plus symbol in upper right corner.<br>3. Tap import wallet.<br>4. Tap Keystore JSON | Completed
![My_Wallet_Address_Dark](https://user-images.githubusercontent.com/51817359/143593723-4fcca70d-0099-4721-b349-2af65de63921.jpg) | <p>**RequestViewController**</p>From main wallet screen:<br>1. Tap ellipses in upper right corner.<br>2. Tap Show My Wallet Address. | Completed
![Send_ETH_Entered_Dark](https://user-images.githubusercontent.com/51817359/143593725-a4ac742b-f5ab-40fb-a691-0d8178ab1f82.jpg) | <p>**SendViewController**</p>From main wallet screen:<br>1. Tap ETH.<br>2. Tap Send.| Completed
![Settings_Backup_Warning_Dark](https://user-images.githubusercontent.com/51817359/143593728-d5d797ea-1223-41af-811f-b26fdd9bbc81.jpg) |  | Missing
![Settings_Default_Reveal_Dark](https://user-images.githubusercontent.com/51817359/143593731-a2b7d431-9a57-4755-aef3-a03732af18f1.jpg) | <p>**SettingsViewController**</p>From main wallet screen:<br>1. Tap settings. | Completed
![Settings_Select_Active_Network_RPC_Dark](https://user-images.githubusercontent.com/51817359/143593733-97482e5e-0d76-486b-a034-ea8008acc12e.jpg) | <p>**EnabledServersViewController**</p>From main wallet screen:<br>1. Tap settings.<br>2. Tap Select Active Networks. | Completed
![Settings_Support_Dark](https://user-images.githubusercontent.com/51817359/143593734-2c7635c9-3a17-4ae0-b022-b5f812db5073.jpg) | <p>**SupportViewController**</p>From main wallet screen:<br>1. Tap settings.<br>2. Tap Support. | Completed
![Wallet_New_Dark](https://user-images.githubusercontent.com/51817359/143593736-c93e744f-7974-4a8a-9f01-039cbd301e51.jpg) | <p>**TokensViewController**</p> | Completed

**Comment by hboon** [comment]
@eviltofu thanks for the update. IMO, we don't have to do the screenshots to show they are completed (though you are free to). They are just very useful for before/after in individual PRs. But would be good to have a list that are not done yet though.

**Comment by eviltofu** [comment]
The screen shots are just the ones listed in the original issue. I can't find (via manual navigation in the app) any more screens where dark mode hasn't been added. I think I'll discover these hidden screens when I start removing the non-dark mode colour definitions from the code. 

We should have a document that shows how to get to each screen; this would be great for testings the app before release.

**Comment by hboon** [comment]
> I think I'll discover these hidden screens when I start removing the non-dark mode colour definitions from the code.

Sure. I'll run through the app with dark mode enabled too

**Comment by hboon** [comment]
@eviltofu would you also check the list in the first comment if all known ones are down?

**Comment by hboon** [comment]
And close these: https://github.com/AlphaWallet/alpha-wallet-ios/issues?q=is%3Aissue+is%3Aopen+dark+mode

**Comment by eviltofu** [comment]
@hboon This issue can be considered closed?

**Comment by hboon** [comment]
@eviltofu Yeah. Created #6468. Thanks!
