### ISSUE TITLE
How to set up the project? (New to xcode and student looking forward to contribute)

### ISSUE THREAD

**Issue by CodahUy** [AlphaWallet/alpha-wallet-ios#3485]
Hello,

I'm a programmer in C# and Java and last month I bought myself a Mac. 

I'm starting to learn swift and make experiments in Xcode but I don't seem to be able to install the dependencies as it is explained in "Get started" section.

I have already cloned the project and opened it in Xcode but when I try to build it has some errors because I can't find the place or the right console where I should type to run the bootstrap.

I'm new to development in Mac and I want to try to contribute for the project.
Thanks.

**Comment by hboon** [comment]
Welcome! Check out [this part](https://github.com/AlphaWallet/alpha-wallet-ios#getting-started) of the README. You need to run `make bootstrap` in the Terminal in the directory which you cloned the repository (it's probably still called `alpha-wallet-ios`).

**Comment by CodahUy** [comment]
Oh, ok! I didn't realise that. Thank you so much! As I said, looking forward to contribute to the community :)
