### ISSUE TITLE
Does ModalViewController need both didDismiss and didClose?

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#3493]
```
protocol ModalViewControllerDelegate: class {
    func didDismiss(_ controller: ModalViewController)
    func didClose(_ controller: ModalViewController)
}
```

They seem to be about the same concept?

**Comment by hboon** [comment]
Related: the "actionsheet" doesn't seem to dismiss with an animation

**Comment by eviltofu** [comment]
I believe one function is called when the X is tapped. The other is called when the view disappears from the screen.

**Comment by hboon** [comment]
Is it necessary to have that distinction and there's a bug somewhere where it doesn't dismiss with an animation for both cases.

**Comment by hboon** [comment]
> Related: the "actionsheet" doesn't seem to dismiss with an animation

Seems like a bug in client code #3501
