### ISSUE TITLE
Stuck at send ERC20 screen after tapping Send button. Screen grayed out

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#3495]
Can't reproduce.

Expecting the actionsheet to show up next.

Maybe a race condition or problem related to `DispatchQueue`?

![IMG_9695](https://user-images.githubusercontent.com/56189/144195059-7d99a9fc-5524-4d57-abc4-d30c4d73d4bc.png)

**Comment by oa-s** [comment]
it might happen because of `confirmationViewController.dismissViewAnimated` method. 
The callback function might be not called, when the view controller is already in transition state.

**Comment by oa-s** [comment]
There also another similar issue, one of them can be closed.

**Comment by hboon** [comment]
> There also another similar issue, one of them can be closed.

@oa-s ok. But note that this is before actionsheet is shown, the other is after hiding the actionsheet though. Is it the same issue? If it's the same thing you can mark it as a duplicate by commenting in one of the issue like this:

> Duplicate of #issue_number
