### ISSUE TITLE
Localised strings files needs to be organised?

### ISSUE THREAD

**Issue by eviltofu** [AlphaWallet/alpha-wallet-ios#3499]
I've noticed that some of the files appear to have more lines? Also the lines should be sorted and perhaps some form of organization be introduced to the naming nomenclature?

**Comment by hboon** [comment]
Can you help fix those files that has fewer lines? Add the missing lines in English at the right position.

> Also the lines should be sorted and perhaps some form of organization be introduced to the naming nomenclature?

I think just leave the mess for now. One thought I have is to combine both Android and iOS strings [^1] so the file format itself might not matter so much. But seems not worth the effort to do it now.

[^1]: It'll be faster and easier to get localisations updated and in sync, but maybe lots of coordination work to sync them in the first place

**Comment by eviltofu** [comment]
It's easier to fix the missing lines once the files are sorted. I'll start on this.

**Comment by eviltofu** [comment]
Ok sorted. There are no missing lines. I wrote a small python script to do the comparison, should I check this in someplace?

**Comment by hboon** [comment]
Is that to check for missing lines? Can you try rewriting it in simple JavaScript in this file https://github.com/AlphaWallet/alpha-wallet-ios/blob/3cb19bf54ea8f50a8bb82c986a93c7aa9db04ce5/dangerfile.js#L21 ? You can add it to your precommit hooks if it doesn't slow you down.

Run it with something like:

```
$ yarn run danger local
```

**Comment by eviltofu** [comment]
It's a python 2 and a bash script. Why not put this in the makefile? `make local_strings_check`. I'm not sure I know enough javascript to rewrite this quickly.

**Comment by hboon** [comment]
Then never mind. Because the next person who comes along might add a ruby script :)
