### ISSUE TITLE
Makefile crash when install cocoapods on M1 Macbook Air with `pod install --repo-update`

### ISSUE THREAD

**Issue by eviltofu** [AlphaWallet/alpha-wallet-ios#3506]
When installing via `make bootstrap`, cocoapods crashes with the following:

`/Users/jerome/Documents/alpha-wallet-ios/vendor/bundle/ruby/2.6.0/gems/ethon-0.12.0/lib/ethon/curls/classes.rb:35: [BUG] Illegal instruction at 0x0000000100870000
ruby 2.6.8p205 (2021-07-07 revision 67951) [universal.arm64e-darwin21]`

**Comment by eviltofu** [comment]
Upgrading to `Ruby 3.0.3` via `rbenv` seems to work. But this means I had to delete the `Gemfile.lock` file to get `Ruby 3.0.3` compatible versions of the Gems. Is this an acceptable work around?

**Comment by hboon** [comment]
> Is this an acceptable work around?

Yes, I think so. And I think it's the right way to go, not so much a workaround :)

If it poses a problem for some people to upgrade to Ruby 3.0.3, then they can bypass the Makefile for now.

**Comment by eviltofu** [comment]
> > Is this an acceptable work around?
> 
> Yes, I think so. And I think it's the right way to go, not so much a workaround :)
> 
> If it poses a problem for some people to upgrade to Ruby 3.0.3, then they can bypass the Makefile for now.

Ok so I will include instructions on how to build with and without the make file.

**Comment by hboon** [comment]
Nah. Just fix the make file and leave it for now and we will see what happens. The product is more important that instructions for others to build it.

**Comment by hboon** [comment]
@eviltofu Actually, this is a bit strange. Can you specify the simplest command(s), without involving using `make` to produce the error prior to the PR? It seems to be working for me, with Ruby 2.7. If you can reproduce it, can you clone the repo to another folder and repeat that to be sure? Here's what worked for me:

```
bundle
bundle exec pod install
```

(maybe the problem is with the Makefile and how it specifies the vendor directory. There's switch to bundle which does that actually, but let's not get into it yet if that's not the problem).

**Comment by eviltofu** [comment]
> @eviltofu Actually, this is a bit strange. Can you specify the simplest command(s), without involving using `make` to produce the error prior to the PR? It seems to be working for me, with Ruby 2.7. If you can reproduce it, can you clone the repo to another folder and repeat that to be sure? Here's what worked for me:
> 
> ```
> bundle
> bundle exec pod install
> ```
> 
> (maybe the problem is with the Makefile and how it specifies the vendor directory. There's switch to bundle which does that actually, but let's not get into it yet if that's not the problem).

This will work. The crash only happens when you do `bundle exec pod install --repo-update` which was in the original makefile. Pull Request #3507 was to simply remove the `--repo-update` command line option.

**Comment by hboon** [comment]
Got it. Thanks for the clarification.
