### ISSUE TITLE
Display chain icons in Settings > Select Active Networks screen

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#3511]
Maybe chain ID too.

Related: https://github.com/AlphaWallet/alpha-wallet-ios/issues/3464#issuecomment-979787211

**Comment by colourfreak** [comment]
Do you mean something like this?

![Settings_Select_Active_Network_RPC](https://user-images.githubusercontent.com/51817359/145557350-72cc7af1-f236-44e7-a2f6-81e56f8ea749.jpg)

**Comment by hboon** [comment]
Yes.

**Comment by hboon** [comment]
Follow ups:

- [ ] Other places where there are "checkboxes"
- [ ] Other places where list of chains are displayed
