### ISSUE TITLE
Dapp browser fallback icons have square focus on initial appearance

### ISSUE THREAD

**Issue by eviltofu** [AlphaWallet/alpha-wallet-ios#3517]
![Screen Shot 2021-12-09 at 4 11 39 PM](https://user-images.githubusercontent.com/1050309/145360494-fad7f277-6aef-418f-8a32-142e675efe4d.png)

**Comment by hboon** [comment]
Probably should verify on iOS 13, 14, 15 too.

**Comment by eviltofu** [comment]
I’ll check on my intel MacBook for 13. I have devices for 15 and 14. This screen shot was taken on 15.

**Comment by hboon** [comment]
Ok, if you want me or Vlad to look into it (or anything else), unassign yourself and assign the right person.

**Comment by oa-s** [comment]
i was able to reproduce it
