### ISSUE TITLE
Add "Search for a token" inside a new search box in the Wallet tab

### ISSUE THREAD

**Issue by colourfreak** [AlphaWallet/alpha-wallet-ios#3527]
![2021-12-10 11 23 18](https://user-images.githubusercontent.com/51817359/145566572-97854973-e5d1-4dd0-a37f-42a07b591d34.png)

**Comment by hboon** [comment]
@colourfreak do you mean to add "Search for a token" as placeholder text?

**Comment by colourfreak** [comment]
Yes. Currently, this is empty.
