### ISSUE TITLE
Improve the transition to Search Box at the top

### ISSUE THREAD

**Issue by colourfreak** [AlphaWallet/alpha-wallet-ios#3529]
Notice how the navigation bar animates. It slides up and it's not visually pleasant. Maybe we can speed up this animation.
https://user-images.githubusercontent.com/51817359/145568622-8a2073b1-813d-4abc-ac84-3d2b9e0f4705.mp4

This is the frame I am talking about.
<img width="631" alt="Screenshot 2021-12-10 at 12 39 57" src="https://user-images.githubusercontent.com/51817359/145568957-6c421c4d-a7f2-4229-a0ee-068af4939e52.png">

Check out how smooth this is in other apps.

Uploading 2021-12-10 09.02.16.mp4…

https://user-images.githubusercontent.com/51817359/145568860-8f4971e8-f859-4bb3-9962-492bdff685b9.mp4

**Comment by hboon** [comment]
Not sure if this is caused by moving the search bar out from the navigation bar though

**Comment by vladyslav-iosdev** [comment]
ok, i will try to improve it. The problem is that we are not really using Search bar in navigation bar, that is why there is such transition

**Comment by hboon** [comment]
Yes, I thought it might be related. See what you can do first. If it's fighting the system, we'll see if there's other ways to improve it (like restoring it in the navigation bar).
