### ISSUE TITLE
Increase the height of the Wallet's cell

### ISSUE THREAD

**Issue by colourfreak** [AlphaWallet/alpha-wallet-ios#3530]
Now the height is 74pt, let's make it according to the design 80pt.

https://zpl.io/aB3X98k

<img width="1331" alt="Screenshot 2021-12-10 at 12 47 16" src="https://user-images.githubusercontent.com/51817359/145569629-f10fad50-0b6d-4740-82f6-1e4b8b456bb4.png">

**Comment by eviltofu** [comment]
@colourfreak I'd like to know if dynamic font sizes are being considered in the design. Older people (like me) tend to increase the default font size.

**Comment by colourfreak** [comment]
> @colourfreak I'd like to know if [Dynamic Type Sizes](https://developer.apple.com/design/human-interface-guidelines/ios/visual-design/typography/) are being considered in the design. Older people (like me) tend to increase the default font size.

I believe that are more important issues at this moment. But I am designing this in a way, that by default it large enough to read.

Note, that the token value font should be larger - 20pt. I added you a Swift extension to Zeplin.
Please check https://extensions.zeplin.io/ if you want any other extension. 

```
let paragraphStyle = NSMutableParagraphStyle()
paragraphStyle.alignment = .right
paragraphStyle.minimumLineHeight = 34
let attributes = [.font: UIFont(name: "SourceSansPro-SemiBold", size: 20) as Any,
	.paragraphStyle: paragraphStyle,
	.foregroundColor: UIColor.AlphaWalletIOs.black]
let attrString = NSAttributedString(string:"$567.56", attributes: attributes)
```
<img width="1341" alt="Screenshot 2021-12-15 at 08 15 01" src="https://user-images.githubusercontent.com/51817359/146141473-30febd1f-0457-4bf9-8c37-fe41979d0c5c.png">

<img width="1555" alt="Screenshot 2021-12-15 at 08 20 03" src="https://user-images.githubusercontent.com/51817359/146141485-533d42ea-c6e5-4296-940d-5232d8f4d69d.png">
