### ISSUE TITLE
Use , as thousands separator and . as decimal separator no matter the locale

### ISSUE THREAD

**Issue by colourfreak** [AlphaWallet/alpha-wallet-ios#3531]
I know in the past we used to change decimals depending on location. But I think we should stick to only one version. People get used to tools like Coinmarketcap, where all goes with the English way to present decimals. Let's stick to it.

**Good:**
1,000,000.00 = 1 mln
2,000.00 = 2k
5.67% = 5 point 67 %

**No more of this:**
1000000,00 = 1 mln
2000,00 = 2k
5,67% = 5 point 67 %

<img width="588" alt="Screenshot 2021-12-10 at 12 59 56" src="https://user-images.githubusercontent.com/51817359/145571267-fb206069-919b-4fa1-aee4-e0893bd97408.png">

<img width="567" alt="Screenshot 2021-12-10 at 12 59 50" src="https://user-images.githubusercontent.com/51817359/145571256-3a62bca7-8776-4ef7-ae03-4298ccca6771.png">

**Comment by eviltofu** [comment]
I'll just make a default currency formatter and insert it into all the instances where it's required so if we decide to change our minds again it will be easier to implement. There already exists a USD currency formatter.

**Comment by eviltofu** [comment]
@colourfreak on a side note, the current code uses (or should be using) the built-in OS code to determine the format. It's a non-trivial task to change the format throughout the app. It's going to take a few days so please be patient.

**Comment by hboon** [comment]
@eviltofu great. Also check what are these:

```
extension NumberFormatter {

    static let currency = Formatter(.currency)
    static let usd = Formatter(.usd(format: .withTrailingCurrency))
```

The `usd` naming might be legacy, don't worry too much about it. Read it as "fiat" if it works better.

**Comment by eviltofu** [comment]
Does the ETH formats also need to obey this?
See [AS_Checkout_Item_Confirm
Loading layers…](https://app.zeplin.io/project/5d0356be2f25b319dcc5944b/screen/5e26175ad78e4558e45ffc20)
So if Doctor Mildews has over 1000 ETH, the display is `1,500.00 ETH`

**Comment by hboon** [comment]
Yes, I think so. But skip ETH for the moment.

I just realized a problem with this change: user's keyboard will still be affected by their locale and we need to make sure we can continue to parse the input correctly. But let's start the refactor for fiat and then we'll test to see if it's workable.

**Comment by eviltofu** [comment]
The old number formatter codes still exist. Those can be used for parsing.

**Comment by hboon** [comment]
@eviltofu are you working on this? Otherwise reassign it to @oa-s so he can take over this? Take care that #3702 will be merged.

**Comment by eviltofu** [comment]
There are places where there are number formatters being used. I should extract these out as well? So that all the NumberFormatters are in one file should we want to change the format again? @hboon

**Comment by hboon** [comment]
> There are places where there are number formatters being used. I should extract these out as well?

Not sure what you are referring to. But sounds like yes.

**Comment by eviltofu** [comment]
> > There are places where there are number formatters being used. I should extract these out as well?
> 
> Not sure what you are referring to. But sounds like yes.

Places which create and format their own NumberFormatter(). I replaced those with a NumberFormatter in the Formatters file.

**Comment by eviltofu** [comment]
@colourfreak Do we always want to use the "," separator? Currently some places (Wallet Summary) do not use ",". 
![image](https://user-images.githubusercontent.com/1050309/149864430-c6d85b71-1d8d-4b70-99fe-f745dc35ca76.png)

**Comment by hboon** [comment]
We might have discussed this, but it's been a while:

BTW, remember to check that entering decimal separators continues to work with locales that are defined to use commas. So I think we might have to do this:

* Users enter with their locale-specific decimal separators (Might be `,` or `.`) I guess we'll just hardcode to accept both. I think we might already do this.
* We display them always with the decimal separator `.` and thousands separator `,`, ignoring their locale.

Not sure if it will be confusing though. Makes sense?

**Comment by eviltofu** [comment]
> We might have discussed this, but it's been a while:
> 
> BTW, remember to check that entering decimal separators continues to work with locales that are defined to use commas. So I think we might have to do this:
> 
> * Users enter with their locale-specific decimal separators (Might be `,` or `.`) I guess we'll just hardcode to accept both. I think we might already do this.
> * We display them always with the decimal separator `.` and thousands separator `,`, ignoring their locale.
> 
> Not sure if it will be confusing though. Makes sense?

@hboon None of the NumberFormatters I converted appear to be used to convert from String -> Number. It appears to be `EtherNumberFormatter` which I haven't touched at all in EtherNumberFormatter.swift is used for the conversion.

**Comment by eviltofu** [comment]
@hboon Do you want me to rewrite the integer parsing code? Currently, the code assumes that "," is the group separator, and "." is the decimal separator.

**Comment by hboon** [comment]
> Do you want me to rewrite the number parsing code? Currently, the code assumes that "," is the group separator, and "." is the decimal separator.

Can you point us to that piece of code?

I think ideally, for user input it should be:

* Parse using user's locale
* If it fails, we just use whichever appears at the rightmost (`,` or `.`) as the decimal separator and ignore the other

For non-user input (I can't remember if we have any), always use "." as the decimal separator.

I can't remember if we have to make allowance to accept both "," and "." as decimal separators at the same time (especially because of copy and paste), so will be good to see where it is.

**Comment by eviltofu** [comment]
@hboon `func number(from string: String, units: EthereumUnit = .ether) -> BigInt?` in `EtherNumberFormatter.swift` I think.

**Comment by hboon** [comment]
@eviltofu Seems like we should keep it:

```
$ gl -S 'guard let index = string.index(where: { String($0) == decimalSeparator }) ?? string.index(where: { String($0) == EtherNumberFormatter.decimalPoint }) else {'
commit f382c855df7fd3fac6acd5dacc1bf46264ed7f6d
Author: Hwee-Boon Yar <hboon@motionobj.com>
Date:   2019-12-11 14:48:27 +0800

    Always support decimal comma as decimal separator in addition to what is specified by locale
```

and:

```
    /// We always allow users to use "." as the decimal separator even if the locale might specify a different separator, eg. a decimal comma like Spain. If user sets their locale to one that uses a decimal comma, eg. Spain, the `.decimalPad` will still show "." instead of "," so the user wouldn't be able enter the "," that the locale expects using the keypad.
    static let decimalPoint = "."
```

**Comment by eviltofu** [comment]
@hboon ok so there is nothing remaining on this issue besides the items in the PR?

**Comment by hboon** [comment]
@eviltofu seems so

**Comment by eviltofu** [comment]
@colourfreak from latest master.

![Simulator Screen Shot - iPhone 12 - 2022-01-22 at 19 47 37 copy](https://user-images.githubusercontent.com/1050309/150637304-7c4b8bfb-24da-48e1-91ea-02dd462d7b70.png)

**Comment by colourfreak** [comment]
All good.
