### ISSUE TITLE
Standardize chevron/checkmark usage in list of Wallet screen

### ISSUE THREAD

**Issue by colourfreak** [AlphaWallet/alpha-wallet-ios#3532]
1. We don't need to show which wallet you are in (checkmark). Instead, show unified icons for all. 
2. Make sure we have decimals right #3531 
3. Update chevrons (arrows) https://zpl.io/bAKlY3q

**Zeplin:**
https://zpl.io/bz4Rq4M

**Prototype:**
https://invis.io/7TZHRQ8W265

Now
![126964979-452669ea-9a5e-4fe7-ae88-ef30aba7899b](https://user-images.githubusercontent.com/51817359/145589690-e5544c98-cf4c-4888-b724-7ea11bbdcf04.png)
![126965148-a63371a4-03cb-4850-ae95-515c189f3fa2](https://user-images.githubusercontent.com/51817359/145589698-d20ad513-5e56-43fb-9b33-3d0622d4fd96.png)

Should be:
<img width="1061" alt="Screenshot 2021-12-10 at 15 30 22" src="https://user-images.githubusercontent.com/51817359/145589904-4b91e8d5-4a81-4bba-8872-6973bb2271d9.png">

**Comment by hboon** [comment]
> checkmark

@colourfreak what if there's more than a handful of wallets with no ENS names? I might just want to go here to check what is my total holdings and then quickly get back to my previous wallet. Wouldn't the checkmark give a sense of where to go?

<img width="487" alt="Screenshot 2021-12-13 at 12 47 00 PM" src="https://user-images.githubusercontent.com/56189/145754005-e2c4044c-9e0a-4557-96e8-3052e0175a3f.png">

**Comment by colourfreak** [comment]
Add a small, 8x8 Azure color #007FED circle on the right of the blockie.
<img width="985" alt="Screenshot 2021-12-13 at 08 37 49" src="https://user-images.githubusercontent.com/51817359/145771215-56987fa2-084c-40eb-ac16-fcb8e8864fd7.png">

**Comment by hboon** [comment]
@eviltofu The screen is available in 2 (similar) forms:

* Wallet tab > top left blockie/avatar
* Settings > Change / Add Wallet

- [ ] Replace chevron (if the existing one is wrong)
- [ ] Replace checkmark on the right with dot on the left for current wallet
