### ISSUE TITLE
Favicons detection looks broken

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#3534]
To reach this screen, go to:

1. Browser tab
2. Visit 1 or more URLs
3. Tap the Browser tab
4. Tap My History

At least some of the favicons should show up.

<img width="443" alt="Screenshot 2021-12-13 at 11 34 35 AM" src="https://user-images.githubusercontent.com/56189/145748376-3cfa125f-a799-4734-b4d1-d0af01863128.png">

**Comment by hboon** [comment]
After this PR:

- [ ] #1103

**Comment by hieronymus4826** [comment]
Hey @hboon can you please assign lexypaul13 to this one and/or add privileges to me for the future. Thank you!

**Comment by hboon** [comment]
@hieronymus4826 You should have access to assign issues (if you click the gear button beside Assignees and see a list, you've got it) . GitHub requires some interaction in the issue from someone outside the team before we can assign it to them. 

@lexypaul13 can you please reply to this? Any comment should do. I think that would fulfill that condition

**Comment by lexypaul13** [comment]
Hi @hboon , My apologies for the late response; I just recovered from an illness.  I would like to work on the task.

**Comment by hboon** [comment]
@lexypaul13 hope you are well now. Let us know of your findings or if you need help :)

**Comment by mmurali88** [comment]
@hboon took a look into this and it seems the favicons deployment is broken for a while.

when I try to access the URL manually from the History model I get 

![image](https://user-images.githubusercontent.com/4982265/148849371-399b2920-5957-4f23-a8ab-d5ec30e5c55c.png)

Also, I tried their website and found their deployment in vercel is not up anymore

![image](https://user-images.githubusercontent.com/4982265/148849534-5f644348-f895-483f-8aef-675813792a35.png)

**Comment by hboon** [comment]
> P.S : Sorry for jumping on the issue even though it was assigned to Lexy .

@mmurali88 thanks for helping to check too! All help welcome :) Let's give @lexypaul13 a bit of time and for their feedback first.

**Comment by hboon** [comment]
Looks like our very own @oa-s missed this discussion and create a PR.

@lexypaul13 would you help to check it out and respond there in the PR? https://github.com/AlphaWallet/alpha-wallet-ios/pull/3688. I'll just leave it for a few days and if you don't have the chance to look at it yet, I'll do a check and merge it. (But we'll come out with other issues to work on if you would like to help out).

**Comment by lexypaul13** [comment]
@hboon  My apologies for the late response, Ive been receiving a lot of interviews and I have been studying leet code. Yes please I would like to look at it

**Comment by hboon** [comment]
@lexypaul13 no worries! We have since merged that PR. But we'll come out with new issues that are suitable. Stay tuned.

**Comment by lexypaul13** [comment]
Awesome thank you so much for understanding.

**Comment by hboon** [comment]
@lexypaul13 @mmurali88 more at https://github.com/AlphaWallet/alpha-wallet-ios/labels/Good%20first%20issue if you are interested. You might not be able to self-assign, so leave a comment in the issue if you would like to take it up and we'll leave you with it for a bit of time.
