### ISSUE TITLE
Swipe to delete wallet is broken for simulator on M1

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#3535]
The screen is available in 2 (similar) forms:

* Wallet tab > top left blockie/avatar
* Settings > Change / Add Wallet

See if we can do it better so it works for simulators running on M1 too (especially if we are doing it wrongly currently), or as a fallback, have an alternative way so it works on simulators + M1 and finally, if it's really not our problem and nothing reasonable we can do, document it here.

Maybe related to: #3559

**Comment by vladyslav-iosdev** [comment]
@hboon can u provide more details. i've tested it, works as expected

**Comment by hboon** [comment]
@vladyslav-iosdev oh no, maybe it's on my side. Let me double check first.

**Comment by vladyslav-iosdev** [comment]
ok, just let me know

**Comment by hboon** [comment]
@vladyslav-iosdev seems like it's a problem with simulator running on M1: https://developer.apple.com/forums/thread/693731

It's not a problem with building on M1 and TestFlight. So you can leave it for now.

**Comment by hboon** [comment]
FYI @eviltofu

**Comment by eviltofu** [comment]
On master, when I swipe to delete on my iPhone X, I get the following error message and the app crashes.
```
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid update: invalid number of rows in section 3. The number of rows contained in an existing section after the update (2) must be equal to the number of rows contained in that section before the update (4), plus or minus the number of rows inserted or deleted from that section (0 inserted, 1 deleted) and plus or minus the number of rows moved into or out of that section (0 moved in, 0 moved out).
```

**Comment by hboon** [comment]
>Commit hash: e4581507a0718abbeabb55cb52814497b9610cfd ...

@eviltofu no. Different screen. Can you create a separate issue for this and fix it?

**Comment by eviltofu** [comment]
> > Commit hash: [e458150](https://github.com/AlphaWallet/alpha-wallet-ios/commit/e4581507a0718abbeabb55cb52814497b9610cfd) ...
> 
> @eviltofu no. Different screen. Can you create a separate issue for this and fix it?

ok!

**Comment by hboon** [comment]
Updated https://github.com/AlphaWallet/alpha-wallet-ios/issues/3535#issue-1078093752 to be clear

**Comment by eviltofu** [comment]
If I run the Simulator in Rosetta mode, I can swipe to delete. I created a **new** project that has a minimum deployment of iOS 15.2 and that has no problem swiping even when the simulator is not running in Rosetta mode. I bumped up the deployment version of the project to iOS 15.2 and it was NOT able to swipe. @hboon how much time do you want me to spend to track down the issue?

**Comment by hboon** [comment]
Say 1-2 days for now and circle back when you have time or are inspired to? It *might* get fixed with a new release so we can revisit it again if it's too painful and still not fixed.

So it works in both of these cases?

A. AlphaWallet + Rosetta
B. New project at 15.2 - Rosetta

but not AlphaWallet even with deployment target = 15.2?

**Comment by hboon** [comment]
Working as expected as of 25a0a0d89e32bf0125ccdcd7f7c8151794da0430
