### ISSUE TITLE
Display token network's symbol of each token in the wallet tab (and other places where the token icon is displayed)

### ISSUE THREAD

**Issue by colourfreak** [AlphaWallet/alpha-wallet-ios#3542]
We need to add a network symbol in each of tokens appearing in a wallet tab. Note, that this is already made in the newest Android build. 

Unlike we used to do this using iconassets, now we will have just one token symbol taken from iconassets (if not there, use the imported library). So my job right now is to re-upload all token icons I uploaded in the past where by default they won't have a network symbol in the corner.

So no matter if we have a LINK token on Optimism, Ethereum Mainnet, Polygon, it will use the same token symbol icon. The only difference is the network icon in the bottom left corner of each coin. And that network icon is another layer on the token symbol.

Mr. Hu did a great job scrapping all tokens with their metadata. Now it's a great time to make first use of this.

- network symbol is 16x16
- all network symbols can be found in Zeplin https://zpl.io/agE1LeZ
- I am going to expand the network symbol library
- note that both token symbol and network symbol are aligned to the left and bottom
- Use this Zeplin component to align token symbol and network symbol https://zpl.io/aB3X98k https://zpl.io/aRKEzez

<img width="1517" alt="Screenshot 2021-12-14 at 11 46 42" src="https://user-images.githubusercontent.com/51817359/145984767-cba4bfe7-6bc2-43b6-a5a5-6fc04396a127.png">

<img width="927" alt="Screenshot 2021-12-14 at 12 06 56" src="https://user-images.githubusercontent.com/51817359/145986953-ec9898e5-6618-4ed3-a5d3-b808649fa862.png">

**Comment by hboon** [comment]
Yes. Do the 3rd sentence of https://github.com/AlphaWallet/alpha-wallet-ios/issues/3496 first

**Comment by hboon** [comment]
It’s all described there alrrady

**Comment by hboon** [comment]
Created  #3545 and updated #3496 to refer to it

**Comment by hboon** [comment]
And this issue is the 2nd sentence of #3496 (linked from there too, now)

**Comment by hboon** [comment]
Waiting for:

- [ ] #3545
