### ISSUE TITLE
Add "Change language" option

### ISSUE THREAD

**Issue by colourfreak** [AlphaWallet/alpha-wallet-ios#3544]
You will access the "Change Language" screen straight from the Main Settings screen.
I can take care of getting translated strings. What I would need is a document (no idea what exactly), where I would enter translated strings. We have a multi-language team, so it will be fun to create. 

@JamesSmartCell How is Android translation made?

Maybe we could use https://lokalise.com/ ?

<img width="1555" alt="Screenshot 2021-12-14 at 14 34 17" src="https://user-images.githubusercontent.com/51817359/146008240-0eae306c-8de9-43ba-91f6-46c712eb0cf8.png">

**Comment by hboon** [comment]
We had this feature. It doesn't work properly on iOS, so we had to remove it. Localization is available on AlphaWallet iOS. Just that it relies on the user's device setting (as it should).

**Comment by hjhjdev** [comment]
@hboon I've changed user's device setting, but It didn't changed. Maybe it's a bug?

**Comment by hboon** [comment]
> @hboon I've changed user's device setting, but It didn't changed. Maybe it's a bug?

Could be. Can you help describe which language you are changing from and to, and preferrably how you did it in Settings? (screenshots would be great, if possible).

**Comment by colourfreak** [comment]
> We had this feature. It doesn't work properly on iOS, so we had to remove it. Localization is available on AlphaWallet iOS. Just that it relies on the user's device setting (as it should).

let me know how to get started with this. I assume I need a document where I can push translated strings.

**Comment by hboon** [comment]
We support 5 languages in iOS. They are in https://github.com/AlphaWallet/alpha-wallet-ios/tree/master/AlphaWallet/Localization, eg for English: https://github.com/AlphaWallet/alpha-wallet-ios/blob/master/AlphaWallet/Localization/en.lproj/Localizable.strings

What do you intend to do with them? I was planning to get a localization service to do it for us. They usually specialize in iOS and Android apps, so tend to know how to handle the file formats. We used to, but never got into doing them completely. So once we start, we ought to revise them regularly.

**Comment by hjhjdev** [comment]
> > @hboon I've changed user's device setting, but It didn't changed. Maybe it's a bug?
> 
> Could be. Can you help describe which language you are changing from and to, and preferrably how you did it in Settings? (screenshots would be great, if possible).

Sure! Images below are what I did.
Changed Language Engligh to Korean(image 1, image 2)
Found only Search String changed(image 3)
After revisiting settings menu, option changed to english automatically.

Also I tried changing device language, english to korean, but app locale strings didn't changed either(english)

<img src="https://user-images.githubusercontent.com/17705694/146473148-90f95e19-6ae5-4bc8-bfb4-0dae51660ecf.PNG" width="40%">

<img src="https://user-images.githubusercontent.com/17705694/146473299-d9ab5293-742e-4aa0-b712-9dfed61fc528.PNG" width="40%">

<img src="https://user-images.githubusercontent.com/17705694/146473350-3a3cee76-99ae-4508-944e-1288a7a88eb6.PNG" width="40%">

<img src="https://user-images.githubusercontent.com/17705694/146473380-8821f67a-1df7-4120-a619-b7f7a9b5f2c8.PNG" width="40%">

**Comment by hboon** [comment]
> > > @hboon I've changed user's device setting, but It didn't changed. Maybe it's a bug?

Yes indeed. Sorry, it took a while to figure out. We are close to merging the fix in and should be available in the next update.

**Comment by hboon** [comment]
Closing because: https://github.com/AlphaWallet/alpha-wallet-ios/issues/3544#issuecomment-993588053
