### ISSUE TITLE
Remove chain overlay on every token icon in iconassets

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#3545]
After this issue:

- [ ] #3542

**Comment by colourfreak** [comment]
[iconassets-master.zip](https://github.com/AlphaWallet/alpha-wallet-ios/files/7745732/iconassets-master.zip)

**Comment by hboon** [comment]
Have pushed to https://github.com/AlphaWallet/iconassets/tree/with-chain-overlay-removed so I might just update the code to

**Comment by hboon** [comment]
@colourfreak I'm updating the code to handle this but just noticed that they all seem to be 80x80px, would be better if they are 120x120 (the current version with the chain overlays are 120x120). But we can try these out first. Code isn't affected by this. If you want to update this, would you drop me a zip file here again?

**Comment by colourfreak** [comment]
> @colourfreak I'm updating the code to handle this but just noticed that they all seem to be 80x80px, would be better if they are 120x120 (the current version with the chain overlays are 120x120). But we can try these out first. Code isn't affected by this. If you want to update this, would you drop me a zip file here again?

This is very bad. I need to save them again and rename them all from original names to logo.png (folder by folder)
Very time-consuming, so please double-check if there is anything else you might miss.

**Comment by hboon** [comment]
If you can give them file names that matches the contract names, I can rename them for you too. Should save you some time.

**Comment by colourfreak** [comment]
[iconassets-master.zip](https://github.com/AlphaWallet/alpha-wallet-ios/files/7796299/iconassets-master.zip)

**Comment by hboon** [comment]
A couple of them are still not 120x120.

These are 128x128:

0x000004F5A30d9394316782AC3EE971546bcAa682/logo.png
0x00000D5B7AaBD11768CC14f8474e5B34f8D39F2B/logo.png
0x000080C09264F55160b719d6700424b877C8d977/logo.png
0x0000AD880efD1690EFd57Da2929bEA1d6eF221Ec/logo.png
0x117CC8a04eF99FB1cC566919502D7a79dE578EF9/logo.png
0xc987b821048EdcB9f5aa126125b95E44e2532A6A/logo.png

These are 47x47:

0x0000853AbE6Fa93f276b62F6984B75Ff2f9dC30E/logo.png
0xa567f5A165545Fa2639bBdA79991F105EADF8522/logo.png

These are 226x226:

0x6c4a441C099171B2279745fce535B89508D12A7a/logo.png

These are 200x200:

0x7714f320Adca62B149df2579361AfEC729c5FE6A/logo.png

These are 50x50:

0x8A953CfE442c5E8855cc6c61b1293FA648BAE472/logo.png

These are 119x119:

0xc56d17dD519e5eB43a19C9759b5D5372115220BD/logo.png

**Comment by colourfreak** [comment]
> A couple of them are still not 120x120.
> 
> These are 128x128:
> 
> 0x000004F5A30d9394316782AC3EE971546bcAa682/logo.png 0x00000D5B7AaBD11768CC14f8474e5B34f8D39F2B/logo.png 0x000080C09264F55160b719d6700424b877C8d977/logo.png 0x0000AD880efD1690EFd57Da2929bEA1d6eF221Ec/logo.png 0x117CC8a04eF99FB1cC566919502D7a79dE578EF9/logo.png 0xc987b821048EdcB9f5aa126125b95E44e2532A6A/logo.png
> 
> These are 47x47:
> 
> 0x0000853AbE6Fa93f276b62F6984B75Ff2f9dC30E/logo.png 0xa567f5A165545Fa2639bBdA79991F105EADF8522/logo.png
> 
> These are 226x226:
> 
> 0x6c4a441C099171B2279745fce535B89508D12A7a/logo.png
> 
> These are 200x200:
> 
> 0x7714f320Adca62B149df2579361AfEC729c5FE6A/logo.png
> 
> These are 50x50:
> 
> 0x8A953CfE442c5E8855cc6c61b1293FA648BAE472/logo.png
> 
> These are 119x119:
> 
> 0xc56d17dD519e5eB43a19C9759b5D5372115220BD/logo.png

I don't know about them. They were uploaded by James. Do you want me to research for better quality and size?

**Comment by hboon** [comment]
Oh. Never mind then. Thanks.
