### ISSUE TITLE
Make the “Hit test surface area” bigger

### ISSUE THREAD

**Issue by colourfreak** [AlphaWallet/alpha-wallet-ios#3553]
How to explain...  note that when you tap in here nothing will happen. This is because we set links area only to the text. But in reality, it should be a way beyond the text. 
<img width="834" alt="Screenshot 2021-12-15 at 13 36 36" src="https://user-images.githubusercontent.com/51817359/146188138-db0ed4f4-2c20-4fe2-93f3-74a49a5e73ad.png">

Now:
<img width="952" alt="Screenshot 2021-12-15 at 13 40 42" src="https://user-images.githubusercontent.com/51817359/146188319-ec9279d7-2292-43f1-af1a-cfa9522161c8.png">

Should be
<img width="915" alt="Screenshot 2021-12-15 at 13 40 18" src="https://user-images.githubusercontent.com/51817359/146188338-bdef2e46-7181-4a94-b9ba-92e1212ad2bb.png">

**Comment by hboon** [comment]
Make the “Hit test surface area” bigger

**Comment by hboon** [comment]
Probably after #3546 since it might need to be changed somewhat to support horizontal scrolling

**Comment by eviltofu** [comment]
@hboon I think this has to be rewritten. UIButtons tend to shrink themselves.

**Comment by hboon** [comment]
Sure. Remember #3546

**Comment by eviltofu** [comment]
Maybe base it off UICollectionView?

**Comment by eviltofu** [comment]
Ok first draft is completed (I created a small stand alone project to write this). Will clean up then transplant to AlphaWallet.
