### ISSUE TITLE
Sluggish UITableView scrolling on M1 + simulator

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#3559]
This happening for you @eviltofu and @vladyslav-iosdev ?

**Comment by hboon** [comment]
Doesn’t matter. Seems like swipe to scroll doesn’t work at all

**Comment by eviltofu** [comment]
Is this issue resolved? @hboon

**Comment by hboon** [comment]
Still there. There's a list of issues: https://github.com/AlphaWallet/alpha-wallet-ios/issues?q=is%3Aissue+is%3Aopen+m1

I don't think it's something we can solve until a version of Xcode + simulator fixes this? I'm building and running with Xcode 13.0 + iPhone 11/iOS 15 simulator

Can you reproduce this?

**Comment by hboon** [comment]
Any one. It doesn't matter how many rows. The rubberbanding seems to break some times. I always thought it's because of M1. Are you not experiencing it at all?

**Comment by hboon** [comment]
Forgot to use Quicktime. See if you can spot it. Flicked finger down and then up. Noticed the second time, it doesn't reach the end.

https://user-images.githubusercontent.com/56189/148376918-c8a3fae0-b018-48d7-bc88-178e052f1dfe.mp4

**Comment by hboon** [comment]
Working as expected as of 25a0a0d89e32bf0125ccdcd7f7c8151794da0430
