### ISSUE TITLE
Should automatically pop up 1 screen (to enter password screen) after export fails and user taps to close error popup in  Settings > Advanced > Export Keystore JSON

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#3563]
eg. if user cancels Touch ID / Face ID

<img width="443" alt="Screenshot 2021-12-16 at 4 09 26 PM" src="https://user-images.githubusercontent.com/56189/146332950-03e364eb-4bea-45fc-920e-e4d44d2df903.png">

**Comment by eviltofu** [comment]
Maybe we can do the export process on the password screen and only jump to this screen if export is successful.

**Comment by hboon** [comment]
But we'll have to pass the JSON around. Not desirable.

**Comment by eviltofu** [comment]
Here we have to pass the password around.

**Comment by hboon** [comment]
Yes, but can't do anything with the password. On the other hand, the JSON keystore file can be brute forced.
