### ISSUE TITLE
Empty Assets and Collectibles Tabs on Wallet screen needs to be filled.

### ISSUE THREAD

**Issue by eviltofu** [AlphaWallet/alpha-wallet-ios#3566]
There should be a screen to explain that there is nothing here and this is not a bug?

![Simulator Screen Shot - iPhone 12 - 2021-12-16 at 16 30 42 copy](https://user-images.githubusercontent.com/1050309/146338137-f9de1f2a-6a03-4d52-aa4b-0b3fdaa4f36d.png)
![Simulator Screen Shot - iPhone 12 - 2021-12-16 at 16 30 48 copy](https://user-images.githubusercontent.com/1050309/146338148-54151b43-06a0-4d66-aacf-12e1681ed46c.png)

**Comment by colourfreak** [comment]
https://zpl.io/aRkyZlp
https://zpl.io/bzzJ4KE
https://zpl.io/25ln7XQ

![Wallet-Collectibles-Empty](https://user-images.githubusercontent.com/51817359/146366972-e3b95bd4-165e-4a80-8097-cc7364be3878.jpg)
![Wallet-Defi-Empty](https://user-images.githubusercontent.com/51817359/146366979-1bc7f1ed-727f-4384-8bab-053bb73d0960.jpg)
![Wallet-Governance-Empty](https://user-images.githubusercontent.com/51817359/146366980-57d387ef-1414-476e-ad6c-043e86876061.jpg)

**Comment by hboon** [comment]
Thanks Tomek.

**Comment by eviltofu** [comment]
Solution is present in the pull request that fixes #3464 (which I've not created yet --- the code does the same thing there so I am making a note here to refer to it)

**Comment by eviltofu** [comment]
@colourfreak What text do I use for search filters resulting in no results for the Wallet screen.

1. All
2. Currencies
3. Assets
4. Collectibles

**Comment by hboon** [comment]
> What text do I use for search filters resulting in no results for the Wallet screen.

What do you mean?

**Comment by eviltofu** [comment]
> > What text do I use for search filters resulting in no results for the Wallet screen.
> 
> Can you elaborate?

I am currently using this:
![image](https://user-images.githubusercontent.com/1050309/149657771-c30a109f-45fd-4d84-a6b3-17234fa441b1.png)

What should it actually be?

**Comment by hboon** [comment]
"No results"

or

"No matches"
