### ISSUE TITLE
Repurpose fiat total value header in Wallet tab when in testnet mode

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#3569]
Maybe hide or use that space to make it clear it's testnet?

<img width="443" alt="Screenshot 2021-12-16 at 5 31 51 PM" src="https://user-images.githubusercontent.com/56189/146346046-d84b99ff-b006-4228-87e1-7ac198602795.png">

**Comment by colourfreak** [comment]
"Testnet"

https://zpl.io/2Gj7APW
https://zpl.io/2j3jMqW
https://zpl.io/bexzLRz

![07_Testnet_Wallet_Test_Networks](https://user-images.githubusercontent.com/51817359/146367658-e529c577-30d8-4759-bb4c-fa0831c17544.png)

![08_Testnet_Rinkeby_Info](https://user-images.githubusercontent.com/51817359/146367661-1ab77edb-146d-41de-bfe1-a349dbe6fdd7.png)

![09_Testnet_Modal](https://user-images.githubusercontent.com/51817359/146367655-159695ab-a281-4f64-be25-3fa7ecde8c5c.png)
