### ISSUE TITLE
Fix Travis caching

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#3570]
https://docs.travis-ci.com/user/caching/

At least gems and pods should be cached. From a recent run: https://app.travis-ci.com/github/AlphaWallet/alpha-wallet-ios/builds/243493658:

<img width="922" alt="Screenshot 2021-12-16 at 5 45 14 PM" src="https://user-images.githubusercontent.com/56189/146347760-653b03b3-b76d-4fb0-bbae-5510281a4ff1.png">

**Comment by eviltofu** [comment]
@hboon From the Travis [website](https://docs.travis-ci.com/user/caching/): `To use the caching feature, in your repository settings, set Build pushed branches to ON.` I can only find references to a web setting. How do I access the web interface for Travis for our git repository?

**Comment by hboon** [comment]
It's in Travis https://app.travis-ci.com/github/AlphaWallet/alpha-wallet-ios/settings. It is enabled (and have been so at least for a while now).

<img width="586" alt="Screenshot 2021-12-17 at 11 03 00 AM" src="https://user-images.githubusercontent.com/56189/146482160-f6c8f697-9804-42a0-b1a3-22aa0717e6ac.png">
