### ISSUE TITLE
Backup wallet doesn't work on simulator

### ISSUE THREAD

**Issue by oa-s** [AlphaWallet/alpha-wallet-ios#3609]
name: `Backup wallet doesn't work on simulator`
about: Using AlphaWallet, but it's not working as you expect?

---

**Describe the bug**
After writing down the seed phrase and selection backup wallet, on settings screen it still displaying not backuped

**Steps to reproduce (REQUIRED)**

0. Switch to non backedup wallet
1. Tap on `Back up this wallet`
2. Tap on `Back up my wallet`
3. Tap on `OK, i wrote this down`
4. Select seed phrase in right order and tap on `Verify seed phrase`

**Expect**
6a. `100% secure` is displaying on `settings` page for `Back up this wallet`

**Observed**
6b.  `Not locked` is displaying on `settings` page for `Back up this wallet` 

**Version or build number number**
Version number (if app store), build number (if TestFlight)

**Comment by hboon** [comment]
@oa-s Seems like not a bug because in #3457 we made `EtherKeystore.isUserPresenceCheckPossible` false for simulators.

Can you close this if that makes sense?

**Comment by oa-s** [comment]
> @oa-s Seems like not a bug because in #3457 we made `EtherKeystore.isUserPresenceCheckPossible` false for simulators.

@hboon  so out of this backup won't work on simulator ?

**Comment by hboon** [comment]
It goes like this, we define 3 states of backup

A. Not backed up
B. Backed up
C. Backed up and "locked" (i.e. elevated security). This is basically saving the seed/key into the keychain with `SecAccessControlCreateFlags.userPresence`.

> so out of this backup won't work on simulator ?

Sort of. So because we force `EtherKeystore.isUserPresenceCheckPossible` to always be false on the simulator, we can never get to C, but the user will get to B.

**Comment by hboon** [comment]
You can trace this by looking for "func didTapLock(inViewController viewController: ElevateWalletSecurityViewController)"

**Comment by oa-s** [comment]
> You can trace this by looking for "func didTapLock(inViewController viewController: ElevateWalletSecurityViewController)"

i see, thanks for explanation
