### ISSUE TITLE
Remove Eureka pod if it is only used for validation and not UI

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#3614]
Eureka is useful as a form/screen builder, but we might not be using it for that anymore, and it'll be good to replace it with our own code if we are only using it for rule/validation.

After #3613  is merged

**Comment by eviltofu** [comment]
Eureka is currently used in 8 files.

| File name | UI | Validation |
| --- | --- | --- |
| EnterPasswordViewController.swift | √ | √ |
| EthereumAddressRule.swift | | √ |
| PrivateKeyRule.swift | | √ |
| MnemonicLengthRule.swift | | √ |
| MnemonicInWordListRule.swift | | √ |
| FormAppearance.swift | √ | |
| FloatLabelCell.swift | √ | |
| FloatLabelTextField.swift |√ | |

However, these all files appear to be related/supporting EnterPasswordViewController.swift which is only used in two instances in EnterPasswordCoordinator.

**Comment by hboon** [comment]
Yes, and that seems like a very simple screen, so if you can remove it quite easily, go ahead.

**Comment by oa-s** [comment]
i have implementation for this issue

**Comment by hboon** [comment]
Remember to negotiate and reassign yourselves

**Comment by hboon** [comment]
So happy. @oa-s @eviltofu:

```
$ gd 08e8a7306999c069cec79e0f08336b0908c83e65^ 08e8a7306999c069cec79e0f08336b0908c83e65 | ag "\-import " | sort | uniq

-import Eureka
```
