### ISSUE TITLE
WalletConnect is not working in the 3.34(417)

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/alpha-wallet-ios#3621]
1. Scan QR
2. QR disappear without confirming on mobile 
3. wallet is not connected
4. later wallet asks to scan again

**Comment by hboon** [comment]
@zhangzhongnan928 I have seen this a few times but can't reproduce. When this happens, can you try this:

1. Scan a new WalletConnect QR code. Does it work?
2. If it doesn't, kill the app and try to scan a new WalletConnect QR code again. Does it work?

**Comment by zhangzhongnan928** [comment]
this is different, I have never experienced it before.
**QR disappear without confirming on mobile** previously QR code won't disappear

The same sites work well with the app store version.

**Comment by hboon** [comment]
Closing. Should work now
