### ISSUE TITLE
Map Features object into Settings app 

### ISSUE THREAD

**Issue by eviltofu** [AlphaWallet/alpha-wallet-ios#3623]
Map the Features.isXXXX = true/false into the settings application so that testers can manually turn on/off features for testing (instead of recompiling). 

https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/UserDefaults/Preferences/Preferences.html

However, no direct documentation from Apple (the above link is in archive) so I'm wondering if this feature is being depreciated.

**Comment by hboon** [comment]
Is it possible to only enable for TestFlight but not appstore? Remember that it's the same build. We can check for the build running on TestFlight with `Environment.isTestFlight`, but not sure how we can do it here.

**Comment by eviltofu** [comment]
I think we can use a combination of build phase (copy Root.plist resource only if it's a debug build) and `#if DEBUG` or `Environment.isTestFlight` for connecting the settings to the `Features` class code. I'll investigate and report later.

**Comment by hboon** [comment]
Ok. Just to be clear: TestFlight isn't a debug build, it's a release build. It's an acceptable limitation if TestFlights don't include the `Features` bundle, but it might not be what you originally intended.

**Comment by eviltofu** [comment]
For TestFlight use, we cannot use the Settings bundle. I would suggest we have a custom screen just for TestFlight to turn on/off the `Features`.

**Comment by hboon** [comment]
Yes, can you chuck in Settings > Advanced? The UI design doesn't matter since it's not going to be sure for users who install it via the app store.
