### ISSUE TITLE
Show chain icon in WalletConnect new session confirmation dialog

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#3629]
Shall we show the chain icon beside "Ethereum" in the screenshot?

<img width="443" alt="Screenshot 2021-12-31 at 3 34 26 PM" src="https://user-images.githubusercontent.com/56189/147906080-8d686e51-3280-4a7c-8b55-52286f3d539f.png">

**Comment by hboon** [comment]
Note to self/hboon:

Similarly, but bigger in the switch network screens, accessible from existing WalletConnect session and dapp browser. But this affects "Select Active Networks" too which has some pending changes:

<img width="443" alt="Screenshot 2022-01-03 at 3 05 20 PM" src="https://user-images.githubusercontent.com/56189/147906189-4b6694ce-6d8c-460e-b592-765edc02b040.png">

**Comment by colourfreak** [comment]
![QR_WalletConnect_Blank](https://user-images.githubusercontent.com/51817359/158380945-9e0b8744-c23b-477c-b991-48493a817439.jpg)

**Zeplin:**
https://zpl.io/adoxBNl
