### ISSUE TITLE
Chain overlay shouldn't show up `TokenImageView` is not used  in as a small icon

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#3631]
i.e. the chain overlay shouldn't show up here (or maybe it shouldn't but it doesn't look nice)

<img width="443" alt="Screenshot 2022-01-05 at 10 41 10 AM" src="https://user-images.githubusercontent.com/56189/148152272-4e57ce01-f341-4717-b989-f45765546428.png">

**Comment by oa-s** [comment]
@hboon Seems like this issue was closed with https://github.com/AlphaWallet/alpha-wallet-ios/pull/3598

**Comment by hboon** [comment]
Oh. Can you help close it if it isn’t relevant anymore?
