### ISSUE TITLE
Replace SegmentedControl with ScrollableSegmentedControl

### ISSUE THREAD

**Issue by eviltofu** [AlphaWallet/alpha-wallet-ios#3641]
Currently there are 14 instances (according to GitHub search) where `SegmentedControl` is used. Some of these are just using the `SegmentedControl.Selection` type. We should replace these instances of `SegmentedControl` with `ScrollableSegmentedControl`. I also suggest renaming `SegmentedControl.Selection` into something else, perhaps `Control.Selection` or rewriting it into `ControlSelectable<T>`?

**Comment by hboon** [comment]
>  I also suggest renaming SegmentedControl.Selection into something else

Sure, if it can be generalized. I suppose a selection is always an item that fits in a array (i.e. it has a unique non-negative index), so sounds like it would?
