### ISSUE TITLE
Enabled Networks screen should have search filter

### ISSUE THREAD

**Issue by eviltofu** [AlphaWallet/alpha-wallet-ios#3642]
Settings > Select Active Networks
Enabled Networks screen should have a search filter.

**Comment by eviltofu** [comment]
It's not that many now because it takes time to add one entry. Once the ability to add multiple is available, this area might be have more entries.

**Comment by hboon** [comment]
I see. Let's leave it this first then. We have analytics so we can check how many they have enabled.

**Comment by hboon** [comment]
Closing for now
