### ISSUE TITLE
Balance incorrect on Add/Hide token page

### ISSUE THREAD

**Issue by seabornlee** [AlphaWallet/alpha-wallet-ios#3645]
name: Bug Report
about: Using AlphaWallet, but it's not working as you expect?

---

**Describe the bug**

**Steps to reproduce (REQUIRED)**
Steps to reproduce the behavior

1. Tap Wallet tab
2. Tap Add/Hide Tokens

**Expect**
Check the `Displayed Tokens` section, all balance are correct, 2 ENS, 1 xPUNK. 
Or do not show the balance as Android does. @colourfreak Here it's different on 2 platforms.

**Observed**
Only ETH balance is correct, others are 0.

**Screenshots**
![IMG_4073](https://user-images.githubusercontent.com/735708/148394437-a951818c-a8e1-4451-b38c-7a3aa132e53b.PNG)
![IMG_4074](https://user-images.githubusercontent.com/735708/148394468-0bdeab68-6224-4175-b550-c67a95a2e3ee.PNG)

Android:
![image](https://user-images.githubusercontent.com/735708/148394388-5cbdf0ae-f745-44ed-9e06-edcd3c26d330.png)

**Version or build number number**
3.34(417)

**Comment by oa-s** [comment]
it seems like it doesn't work for collectibles tokens, will take a look on it
