### ISSUE TITLE
Spurious "..." at end of .travis.yml ?

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#3650]
https://github.com/AlphaWallet/alpha-wallet-ios/blob/52b1dff373ab2f331344364e89d5d91d9335b532/.travis.yml#L20

**Comment by eviltofu** [comment]
https://yaml.org/spec/1.2.2/
```
2.2. Structures
YAML uses three dashes (“---”) to separate directives from document content. This also serves to signal the start of a document if no directives are present. Three dots ( “...”) indicate the end of a document without starting a new one, for use in communication channels.
```

**Comment by hboon** [comment]
TIL. But is there any reason to add it at the end explicitly?

**Comment by eviltofu** [comment]
> TIL. But is there any reason to add it at the end explicitly?

It's the standard?

**Comment by hboon** [comment]
Why does it have that sometimes and why it doesn't have that sometimes? And if it's optional in our case, why do we add it explicitly? Is there any benefit to it?

**Comment by eviltofu** [comment]
I think it's like the case where some people don't close <html></html> tags. They know the browser will compensate for it. I don't see a point in taking it out. @hboon

**Comment by hboon** [comment]
Yeah, just curious. No big deal.
