### ISSUE TITLE
Should Podfile iOS version be bumped up to 13.0 as well?

### ISSUE THREAD

**Issue by eviltofu** [AlphaWallet/alpha-wallet-ios#3653]
```
platform :ios, '12.0'
inhibit_all_warnings!
source 'https://cdn.cocoapods.org/'
```
Should this be bumped up to 13.0

**Comment by hboon** [comment]
@eviltofu Ah yes. Also the deployment target at the bottom of the Podfile. Would you try running it on both M1 simulator and device? Just to be sure.

**Comment by eviltofu** [comment]
Should I also update all the code which has depreciation warnings?
```
ConfigureTransactionViewController.swift:146:16: 'setAnimationCurve' was deprecated in iOS 13.0: Use the block-based animation API instead
```

**Comment by hboon** [comment]
Sure. Separate PR? Deprecation aren’t that urgent so doesn’t have to be together

**Comment by eviltofu** [comment]
On iPhone X/iOS15.2 when I'm scrolling on the Wallet screen, it's not smooth. I think it's worse than the non 13 Podfile version.

**Comment by hboon** [comment]
Device or simulator? Are you saying this PR is causing the difference?

**Comment by eviltofu** [comment]
> Device or simulator? Are you saying this PR is causing the difference?

I am not sure if there is an actual slowdown, how can I measure the scrolling smoothness? It just felt more jerky but that could be from several other factors. 

After watching `0x73bceb1cd57c711feac4224d062b0f6ff338501e` things get very choppy. However, after several hours, the scrolling is smooth now.

**Comment by hboon** [comment]
They are libraries that display FPS in-app or you can use Instruments. We haven't bothered with FPS much. But if you do check, remember to test on device, not simulator.

**Comment by hboon** [comment]
Already done in other PR, but #3718 finishes up what's missing.
