### ISSUE TITLE
Unwanted layout animation after tapping on ERC1155 token in Wallet tab

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#3655]
Verify for ERC721 too

https://user-images.githubusercontent.com/56189/148489670-801b9bc2-5108-4d79-b5f8-5d09d60dcd74.mp4

**Comment by oa-s** [comment]
@hboon seems like its not reproducing for me on simulator iphone 11 pro, can u check if its still exists for u?

**Comment by hboon** [comment]
Seems not anymore. Thanks
