### ISSUE TITLE
Label clipped in configure transaction ("Set Speed") screen when there's an error

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#3656]
This is for nonce. Need to check if it happens for other fields too

![145928481-cbc3708f-accc-4fc5-b2b5-2dfcd26f4ac5](https://user-images.githubusercontent.com/56189/148504032-ea24f766-9a07-49b4-a7bc-16936b8b1745.PNG)

**Comment by eviltofu** [comment]
How do I start a transaction?

**Comment by hboon** [comment]
@oa-s help :)

**Comment by eviltofu** [comment]
I mean I don't have a wallet with anything in it.

**Comment by hboon** [comment]
Create one and paste the address here.
