### ISSUE TITLE
After a crash during unit testing, the app cannot start up

### ISSUE THREAD

**Issue by eviltofu** [AlphaWallet/alpha-wallet-ios#3669]
On hardware, after the app crashes during unit testing, the app cannot start up.

1. Delete the app.
2. Install a new copy and run unit tests from Xcode.
3. App crashes (see #3662).
4. Restart app.
5. App is frozen at start up screen.

**Comment by eviltofu** [comment]
@hboon @oa-s @colourfreak I've tracked down the problem to `AppCoordinator.swift:86`
```swift
        if isRunningTests() {
            startImpl()
        } else {
            DispatchQueue.main.async {
                let succeeded = self.startImpl()
                if succeeded {
                    return
                } else {
                    self.retryStart()
                }
            }
        }
```
where in `AppCoordinator.swift:120`
```swift
    @discardableResult private func startImpl() -> Bool {
        if MigrationInitializer.hasRealmDatabasesForWallet && !keystore.hasWallets && !isRunningTests() {
            return false
        }
```
The functions keeps returning false because the RealmDatabase exists but the keyStore has no wallets. This keeps the app in an infinite loop in `AppCoordinator.swift:107`
```swift
    private func retryStart() {
        DispatchQueue.main.asyncAfter(deadline: .now() + 0.5) {
            let succeeded = self.startImpl()
            if succeeded {
                return
            } else {
                self.retryStart()
            }
        }
    }
```
Once I can verify @colourfreak 's problem has the same cause, we can fix it.

**Comment by eviltofu** [comment]
@hboon @oa-s I would recommend a 15 second timer that will break this loop and asks if the user wants to reinitialise/reinstall the app. A second recommendation would be to store the wallet data in the secure user keychain as a back up and ask the user if they wish to reload from the keychain instead of reinitialising.

**Comment by hboon** [comment]
@eviltofu Thanks. Let me check this out.

**Comment by eviltofu** [comment]
Ok it's not the switching wallet rapidly bug. I was able to restart the app when I had a crash due to the switching wallet bug. #3657

**Comment by hboon** [comment]
@oa-s would you help to check this too? Thanks :)

**Comment by oa-s** [comment]
Yep, i was able to reproduce it, the problem is that after passing tests we got the list of created `realm` dbs and as `UsersDefaults` are empty that is why it stucks.

**Comment by oa-s** [comment]
The app crashes due to error:
```
AlphaWalletTests/EtherKeystoreTests.swift:184: Fatal error: 'try!' expression unexpectedly raised an error: AlphaWallet.KeystoreError.accountMayNeedImportingAgainOrEnablePasscode
2022-01-13 17:19:17.750579+0200 AlphaWallet[20925:3738079] AlphaWalletTests/EtherKeystoreTests.swift:184: Fatal error: 'try!' expression unexpectedly raised an error: AlphaWallet.KeystoreError.accountMayNeedImportingAgainOrEnablePasscode
```

**Comment by hboon** [comment]
@oa-s can you create a PR? Careful with Realm databases and user keys in production.

**Comment by eviltofu** [comment]
@hboon @oa-s My suggestion now is to have separate name spaces/folders for testing. This way we won't have to modify the start up code. The realm database could have a new folder just for testing. The Config user defaults could have a prefix `tests-` added to all the keys.

**Comment by oa-s** [comment]
@eviltofu @hboon Yep, that is what the pr does for this issue. We creating a new folder for realm files during testing. In cache directory we create `wallets` folder, with realm files, even if the app is crashing we drop folders content on next launch, so this issue shouldn't appear.
