### ISSUE TITLE
Add option to rename wallet straight from a dotted menu in the top right

### ISSUE THREAD

**Issue by colourfreak** [AlphaWallet/alpha-wallet-ios#3689]
https://zpl.io/VkPqp8g
<img width="693" alt="Screenshot 2022-01-11 at 14 02 59" src="https://user-images.githubusercontent.com/51817359/148947858-302c9236-7cc2-4c34-a22d-93274a3de4b9.png">

**Comment by hboon** [comment]
@colourfreak  Not a biggie now, but there's a bunch of unrelated functions tucked under the … button. Copy Address, Show My Wallet Address and Rename This Wallet are related to the wallet/address, maybe we can look into moving them somewhere *in the future*? Maybe when the title "tomek.eth" is tapped or when the blockie/ENS avatar is tapped?

**Comment by colourfreak** [comment]
That was fast. I am impressed how things just speeded up :)
