### ISSUE TITLE
Cannot compile master (4ea6700c8b62ae281bb727cecabd51f6bb595895)

### ISSUE THREAD

**Issue by eviltofu** [AlphaWallet/alpha-wallet-ios#3691]
`RPCServers.swift:720:28: Type 'R.image' has no member 'xdai'`

![image](https://user-images.githubusercontent.com/1050309/149055803-7c4ae870-19e5-4208-ba02-4a2b78e2b2ca.png)

**Comment by hboon** [comment]
@eviltofu I'll get this one
