### ISSUE TITLE
Remove unused pods

### ISSUE THREAD

**Issue by oa-s** [AlphaWallet/alpha-wallet-ios#3693]

**Comment by oa-s** [comment]
@hboon do we still need this pod, seems like it's not using in the app 
`pod 'TrezorCrypto', :git=>'https://github.com/AlphaWallet/trezor-crypto-ios.git', :commit => '50c16ba5527e269bbc838e80aee5bac0fe304cc7'`

**Comment by hboon** [comment]
@oa-s I can't remember what it's for without looking it up. If it builds, then you can remove it :)
