### ISSUE TITLE
Add support for universal link with embedded URL so that when the link is is tapped, URL is opened in dapp browser

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#3708]
So:

1. Tap on the universal link, `https://aw.app/openurl?url=<dapp-url-here>`
2. Operating system automatically switch to AlphaWallet app
3. AlphaWallet switches to browser tab and loads <dapp-url-here> in the browser

Samples to test:

```
https://aw.app/openurl?url=http%3A%2F%2Fapp.uniswap.org%3Ftest%3Dvalue1
https://aw.app/openurl?url=https%3A%2F%2Fapp.uniswap.org%3Ftest%3Dvalue1
```

I think this doesn't work, but can you verify?

```
https://aw.app/openurl?url=https://app.uniswap.org?test=value1
```

**Comment by hboon** [comment]
@oa-s Once you confirm the URL scheme is working correctly, would you help create an issue in the Android repo and assign to James, tag it with `High Priority`

**Comment by oa-s** [comment]
https://user-images.githubusercontent.com/96283950/149320117-a1199649-5d04-4ae2-aa4c-3e0b01a1988e.MP4

for me it works in the next way

**Comment by hboon** [comment]
Yeah, that's how it is currently. We want it to do this when the link is in this format: `https://aw.app/openurl?url=<dapp-url-here>`:

1. Tap on the universal link, `https://aw.app/openurl?url=<dapp-url-here>`
2. Operating system automatically switch to AlphaWallet app
3. AlphaWallet switches to browser tab and loads in the browser

**Comment by hboon** [comment]
Similar to how when there's a WalletConnect WCURL at the end for supporting WalletConnect
