### ISSUE TITLE
Remove the chevron icon from the Wallet Summary screen

### ISSUE THREAD

**Issue by colourfreak** [AlphaWallet/alpha-wallet-ios#3709]
![2022-01-13 11 16 11](https://user-images.githubusercontent.com/51817359/149314907-b116d46b-3469-4698-a73e-554c45d5f4a5.png)

Why? Cause this is confusing. It's an indication that you can see more, where this is not the case yet.

**Comment by oa-s** [comment]
@colourfreak can you please check build version you are using? the latest build doesn't have this chevron icon. Here is what we got
<img width="445" alt="Screenshot 2022-01-13 at 16 36 07" src="https://user-images.githubusercontent.com/96283950/149349938-37b52134-6ae3-4312-baa5-bce01e70e575.png">

**Comment by colourfreak** [comment]
All good then.
