### ISSUE TITLE
Email option not working on second time.

### ISSUE THREAD

**Issue by Saif-Fazlani** [AlphaWallet/alpha-wallet-ios#3724]
In support section, when email is tapped, it opens a MFMailComposeViewController, but when user cancels or sends the email and taps the email again, the cancel and send buttons for MFMailComposeViewController doesn't seem to work.

**Comment by hboon** [comment]
@Saif-Fazlani I can reproduce this too. Thanks for reporting!

**Comment by Saif-Fazlani** [comment]
@hboon You're welcome.
Any idea on how to resolve this?

**Comment by hboon** [comment]
@Saif-Fazlani we'll have to fix it in the codebase.

**Comment by Saif-Fazlani** [comment]
Could you please share the solution here?
I'm working on an MVP and I'm stuck on this issue for a few hours now.

**Comment by hboon** [comment]
Do you mean you are trying to fix the bug, perhaps in a fork?

If so, we should be getting to this shortly. We'll create a PR with the fix, which links back to this issue, so you'll get notified too.

**Comment by Saif-Fazlani** [comment]
Yes, I am.
That'd be great, thanks!
