### ISSUE TITLE
Show more collection-level data from OpenSea

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#3730]
We can get this additional data for NFTs available on OpenSea:

```
{
  "stats": {
    "count": 1700,
    "num_owners": 596,
    "floor_price": 4.9
    "total_volume": 9397.148721515618,
    "average_price": 9.159014348455768,

    "total_sales": 1026,
    "total_supply": 1700,
    //…
}
```

Here's the corresponding OpenSea page showing some of these data:

<img width="756" alt="Screenshot 2022-01-17 at 6 04 09 PM" src="https://user-images.githubusercontent.com/56189/149752094-c9a21a7b-4dcd-40da-8c95-cbc67561cb45.png">

Maybe we can display them in the Info tab:

<img width="504" alt="Screenshot 2022-01-17 at 6 20 47 PM" src="https://user-images.githubusercontent.com/56189/149752113-2a519e61-2f08-4bfb-8be4-7816dd171acc.png">

But perhaps we can highlight the floor price?

I was thinking if we should use the floor price:

* display in the Wallet tab
* include in fiat value of the wallet

What do you think?

---

Notes for implementation:

Doc: https://docs.opensea.io/reference/retrieving-collection-stats

```
//Get tokens owned by user:
curl -H 'X-API-KEY: <key>' 'https://api.opensea.io/api/v1/assets/?owner=0xbbce83173d5c1D122AE64856b4Af0D5AE07Fa362&order_by=pk&order_direction=asc&limit=50&offset=0'

//Read slug
"slug" : "blitmap"

//Use slug
curl -H 'X-API-KEY: <key>' 'https://api.opensea.io/api/v1/collection/blitmap/stats'
```

**Comment by hboon** [comment]
@colourfreak sorry. Hold this one. Can get more

**Comment by hboon** [comment]
Looks like just one more field is useful:

```
"safelist_request_status" : "verified",
```

According to docs:

> The collection's approval status within OpenSea. Can be not_requested (brand new collections), requested (collections that requested safelisting on our site), approved (collections that are approved on our site and can be found in search results), and verified (verified collections)

So the values can be:

* not_requested
* requested
* approved
* verified

**Comment by hboon** [comment]
@colourfreak So summing up, there's:

* a bunch of stats: https://github.com/AlphaWallet/alpha-wallet-ios/issues/3730#issue-1105671620
* safelist_request_status: https://github.com/AlphaWallet/alpha-wallet-ios/issues/3730#issuecomment-1015065563

**Comment by colourfreak** [comment]
![ERC-721-Token-Long](https://user-images.githubusercontent.com/51817359/151172701-84a0d05f-c0ed-4a81-8452-8de9356df976.jpg)

**Comment by hboon** [comment]
@colourfreak Thanks! Is this the final version to implement?

And is the action button dark gray-ish color confirmed? (if so, oa-s: let's do that separately and update the entire app).

**Comment by colourfreak** [comment]
https://zpl.io/aB3JRgq
https://zpl.io/aXRA3QP

Yes. This is final.

**Comment by hboon** [comment]
@colourfreak thanks!

**Comment by hboon** [comment]
@oa-s `ButtonBar` changes already covered in #3843

**Comment by oa-s** [comment]
@hboon Could you help in figuring out the `issuer` value for collection?

**Comment by oa-s** [comment]
```
curl --request GET \
     --url https://api.opensea.io/api/v1/asset/0x8d04a8c79ceb0889bdd12acdf3fa9d207ed3ff63/1650/ \
     --header 'X-API-KEY: 11ba1b4f0c4246aeb07b1f8e5a20525f'
```
Here is a request for retrieving one of [Blitmap](https://opensea.io/collection/blitmap) tokens. The response has `foor_price` values equal to `0`

**Comment by hboon** [comment]
> Here is a request for retrieving one of [Blitmap](https://opensea.io/collection/blitmap) tokens. The response has `foor_price` values equal to `0`

You can get it with:

```
curl 'https://api.opensea.io/api/v1/collection/blitmap/stats' -H 'X-API-KEY: 11ba1b4f0c4246aeb07b1f8e5a20525f'
```

```
{
   "stats" : {
      "average_price" : 9.12482951790678,
      "count" : 1700,
      "floor_price" : 4.99,
      "market_cap" : 7023.125,
      "num_owners" : 598,
      "num_reports" : 0,
      "one_day_average_price" : 4.725,
      "one_day_change" : 0,
      "one_day_sales" : 1,
      "one_day_volume" : 4.725,
      "seven_day_average_price" : 4.13125,
      "seven_day_change" : -0.227803738317757,
      "seven_day_sales" : 4,
      "seven_day_volume" : 16.525,
      "thirty_day_average_price" : 5.30045454545455,
      "thirty_day_change" : -0.538168706840695,
      "thirty_day_sales" : 11,
      "thirty_day_volume" : 58.305,
      "total_sales" : 1034,
      "total_supply" : 1700,
      "total_volume" : 9435.07372151562
   }
}
```

Or at the collection level (which includes `stats`):

```
curl 'https://api.opensea.io/api/v1/collection/blitmap' -H 'X-API-KEY: 11ba1b4f0c4246aeb07b1f8e5a20525f'
```

**Comment by hboon** [comment]
> @hboon Could you help in figuring out the `issuer` value for collection?

Will check

**Comment by hboon** [comment]
@oa-s Interestingly if we access the asset instead:

```
curl 'https://api.opensea.io/api/v1/assets/?owner=0xbbce83173d5c1D122AE64856b4Af0D5AE07Fa362&order_by=pk&order_direction=asc&limit=50&offset=0' -H 'X-API-KEY: 11ba1b4f0c4246aeb07b1f8e5a20525f'
```

It includes this:

```
"creator" : {
   "address" : "0xf296178d553c8ec21a2fbd2c5dda8ca9ac905a00",
   "config" : "verified",
   "profile_img_url" : "https://storage.googleapis.com/opensea-static/opensea-profile/30.png",
   "user" : {
      "username" : "dhof"
   }
}
```

Sometimes (most of the time!) the `username` is null, but the `address` is the contract deployer:

```
"creator" : {
   "address" : "0xba52c75764d6f594735dc735be7f1830cdf58ddf",
   "config" : "",
   "profile_img_url" : "https://storage.googleapis.com/opensea-static/opensea-profile/3.png",
   "user" : null
},
```

We can't really show the issuer, but we can show the contract deployer, so maybe we can do:

if user not null
    link to user on OpenSea //OpenSea seems to use this: https://opensea.io/{username}?tab=created
elsif address not null
    link to address on OpenSea //contract seems to work too: https://opensea.io/0xba52c75764d6f594735dc735be7f1830cdf58ddf?tab=created
else
    don't show issue
end

**Comment by oa-s** [comment]
ready for review

**Comment by hboon** [comment]
Wrapped|Truncated
-|-
<img width="498" alt="Screenshot 2022-02-08 at 11 37 55 AM" src="https://user-images.githubusercontent.com/56189/152913625-a8712e15-d67d-482c-99d1-b24506766e88.png">|<img width="474" alt="Screenshot 2022-02-08 at 11 37 59 AM" src="https://user-images.githubusercontent.com/56189/152913640-3e5f8dc2-4ddf-4f65-ab50-fee96d239bc2.png">

**Comment by colourfreak** [comment]
@hboon Android is one step behind, but do you think I have to make a dedicated design for Android or they can use what I provided here?

**Comment by hboon** [comment]
@colourfreak this should be good enough

@oa-s would you help to write an issue and detail the fields to read from? :) spare them some research and ensure consistency. It’s harder to catch differences after the fact for this

**Comment by JamesSmartCell** [comment]
@oa-s How did you get the % rarity for the attributes? (If you were able to).

**Comment by oa-s** [comment]
[JamesSmartCell](https://github.com/JamesSmartCell) i am not quite sure, can u share token name that has rarity for the attributes?

**Comment by JamesSmartCell** [comment]
Punks V2: https://opensea.io/collection/punksv2

https://opensea.io/assets/0x300b896c8ce26395cd1aed16cbbd070a487c7c3c/6653

Expand: Properties.

https://api.opensea.io/api/v1/asset/0x300b896c8ce26395cd1aed16cbbd070a487c7c3c/6653

Looks like we can use 'trait_count' combined with maybe 'totalSupply' from the contract itself. It doesn't seem safe though, as the contract may not have that amount.

Maybe once the TotalSupply hits the limit (10000) it would update in OpenSea?

Also this one:

https://api.opensea.io/api/v1/asset/0xa7d8d9ef8d8ce8992df33d8b8cf4aebabd5bd270/203000828

I don't know how to find the total number in order to calculate the % rarity of the traits.

**Comment by oa-s** [comment]
> I don't know how to find the total number in order to calculate the % rarity of the traits.

in iOS i didn't do this calculations, just displayed data from json

**Comment by JamesSmartCell** [comment]
> > I don't know how to find the total number in order to calculate the % rarity of the traits.
> 
> in iOS i didn't do this calculations, just displayed data from json

Yeah it's probably best to leave it for now until we know more. I suspect OpenSea calculate this value for collections based on how many tokens of that set exist (probably from a GraphQL/node service).

A very simple method would be to find the last 'mint' function, read the tokenId, if it's not the OpenSea or Rarible holding contract then we can know the tokenId count.

Alternatively if etherscan is available we can use (eg) this:

https://api.etherscan.io/api?module=stats&action=tokensupply&contractaddress=0x300b896C8ce26395CD1Aed16cBBD070A487c7c3c

Which gives the total token supply supply for V2 Punks, then we can calculate the rarity of the traits.

It also works for other contracts I have checked. I think it's an important thing to add because ppl love to check the rarity of their traits. We could even colour code them.

I'll create a new issue for this.

**Comment by hboon** [comment]
> I'll create a new issue for this.

The idea is right. But you'd want:

`collection-level` (https://api.opensea.io/api/v1/collection/#{collection_slug})

`collection.stats.count`

and not:

`collection.stats.total_supply` (nor the equivalent from https://api.opensea.io/api/v1/assets/?owner=#{ethereum_address})

i.e.

`trait_count / collection.stats.count * 100.0`

**Comment by JamesSmartCell** [comment]
@oa-s I have worked out a reliable method for this:

https://github.com/AlphaWallet/alpha-wallet-android/issues/2440

**Comment by JamesSmartCell** [comment]
> > I'll create a new issue for this.
> 
> The idea is right. But you'd want:
> 
> `collection-level` ([https://api.opensea.io/api/v1/collection/#{collection_slug}](https://api.opensea.io/api/v1/collection/#%7Bcollection_slug%7D))
> 
> `collection.stats.count`
> 
> and not:
> 
> `collection.stats.total_supply` (nor the equivalent from [https://api.opensea.io/api/v1/assets/?owner=#{ethereum_address}](https://api.opensea.io/api/v1/assets/?owner=#%7Bethereum_address%7D))
> 
> i.e.
> 
> `trait_count / collection.stats.count * 100.0`
> 
> ([https://api.opensea.io/api/v1/collection/#{collection_slug}/stats](https://api.opensea.io/api/v1/collection/#%7Bcollection_slug%7D/stats) would do too)

Or see this:

https://github.com/AlphaWallet/alpha-wallet-android/issues/2440

**Comment by JamesSmartCell** [comment]
> > I'll create a new issue for this.
> 
> The idea is right. But you'd want:
> 
> `collection-level` ([https://api.opensea.io/api/v1/collection/#{collection_slug}](https://api.opensea.io/api/v1/collection/#%7Bcollection_slug%7D))
> 
> `collection.stats.count`
> 
> and not:
> 
> `collection.stats.total_supply` (nor the equivalent from [https://api.opensea.io/api/v1/assets/?owner=#{ethereum_address}](https://api.opensea.io/api/v1/assets/?owner=#%7Bethereum_address%7D))
> 
> i.e.
> 
> `trait_count / collection.stats.count * 100.0`
> 
> ([https://api.opensea.io/api/v1/collection/#{collection_slug}/stats](https://api.opensea.io/api/v1/collection/#%7Bcollection_slug%7D/stats) would do too)

Looks like we're pretty much looking at the same data.
