### ISSUE TITLE
Display traits for NFTs (ERC721 and ERC1155) retrieved from OpenSea

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#3741]
We used to display them for ERC721s like CryptoKitties before we aligned the UI for ERC721 with 1155's.

Let's show them again.

Buzz @colourfreak if we need design help.

This screen, for individual token IDs:

<img width="504" alt="Screenshot 2022-01-18 at 12 29 48 PM" src="https://user-images.githubusercontent.com/56189/149871309-58de3d7a-1b51-407e-9591-3795bc0afd6b.png">

Sample, in the OpenSea API output:

```
"traits" : [
   {
      "display_type" : null,
      "max_value" : null,
      "order" : null,
      "trait_count" : 34,
      "trait_type" : "Affinity",
      "value" : "Earth II, Fire I"
   },
   {
      "display_type" : null,
      "max_value" : null,
      "order" : null,
      "trait_count" : 18,
      "trait_type" : "Slabs",
      "value" : "â¢ â¢ â¢ â¢"
   },
   //…
]
 ```

- [ ] Buzz Android too, in case it's missing?

**Comment by oa-s** [comment]
@hboon @colourfreak do we have design for displaying such kind of data?
