### ISSUE TITLE
Gas price and Gas limit textboxes' keyboard should not allow entering "." in configure transaction screen

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#3751]
`ConfigureTransactionViewController`

Probably should be `.numberPad`? (like `Nonce` in the same screen).

<img width="504" alt="Screenshot 2022-01-20 at 1 34 58 PM" src="https://user-images.githubusercontent.com/56189/150279751-c14599aa-5c89-4e2a-ab68-832af57232c5.png">

**Comment by eviltofu** [comment]
@hboon How do I get to this screen?

**Comment by hboon** [comment]
@eviltofu 

1. Wallet tab
2. Tap Ethereum
3. Tap Receive
4. Tap address to copy
5. Back
6. Tap Send
7. Paste address
8. Done
9. Send
10. Edit (this is the screen to adjust gas fees and nonce)
11. Tap Custom

**Comment by eviltofu** [comment]
@eviltofu Why does this not show up in my inbox? Tagged myself for this to show.

**Comment by hboon** [comment]
> @eviltofu Why does this not show up in my inbox? Tagged myself for this to show.

@eviltofu does it now? It should.

**Comment by eviltofu** [comment]
There are lower limits on gas price and gas limit. When I move the slider to the minimum level, I get gas price 1 and gas limit 21000. It is possible to type in 0 for both these fields. Do you want me to limit the values in both these fields to 1 and 21000 respectively? @hboon

**Comment by eviltofu** [comment]
Also the Gas Price box appears to change from red to black but only for a very narrow range (99-120) regardless of the Gas Limit. @hboon

**Comment by eviltofu** [comment]
Also keyboard keeps showing **Done** and no **Next**. Tapping **Done** moves the focus to the next textfield. When I tap on the textfield, the keyboard obscures the textfield. When focus shifts to next textfield, that textfield is not scrolled into view.

![Screen Shot 2022-01-29 at 9 05 12 AM copy 2](https://user-images.githubusercontent.com/1050309/151640768-72148d62-91ec-4b85-8e2c-babf3fb3e7e5.png)
.

**Comment by hboon** [comment]
@eviltofu can you help create a new issue for https://github.com/AlphaWallet/alpha-wallet-ios/issues/3751#issuecomment-1024775364 and the comments following it? And separate issues if appropriate? Easier to track.
