### ISSUE TITLE
Set Preserve Vector Data for PDFs in XCAssets file

### ISSUE THREAD

**Issue by eviltofu** [AlphaWallet/alpha-wallet-ios#3762]
I noticed some PDFs in the XCAssets file don't have the Preserve Vector Data checkbox clicked. Someone should go through all the PDF images in the XCAssests file and turn Preserve Vector Data on.

**Comment by ramen2020** [comment]
@eviltofu @hboon 
I have resolved this issue and submitted a pull request. Please confirm.

https://github.com/AlphaWallet/alpha-wallet-ios/pull/3801
