### ISSUE TITLE
Remove the gray line under nav bar in all ERC20, ERC721, ERC1155 tokens

### ISSUE THREAD

**Issue by colourfreak** [AlphaWallet/alpha-wallet-ios#3765]
<img width="1112" alt="Screenshot 2022-01-21 at 09 40 41" src="https://user-images.githubusercontent.com/51817359/150494795-e4761a27-6c46-474d-87a3-1237bbe16013.png">

Zeplin
https://zpl.io/2p8ozYy
https://zpl.io/aB3JRgq
https://zpl.io/V4Ngj04

**Comment by eviltofu** [comment]
@colourfreak What about erc875?

**Comment by colourfreak** [comment]
> @colourfreak What about erc875? I'm going to assume that you want that too.

Yes
