### ISSUE TITLE
Make the font larger 20pt in the wallet tab, token value

### ISSUE THREAD

**Issue by colourfreak** [AlphaWallet/alpha-wallet-ios#3766]
<img width="1408" alt="Screenshot 2022-01-21 at 09 55 16" src="https://user-images.githubusercontent.com/51817359/150497173-e0eff6a6-b4dc-46c4-8046-a079b9dded28.png">

This issue is coming back.

Zeplin:
https://zpl.io/aB3X98k

Font: SourceSansPro-SemiBold, 20pt, Black #000000, line height 34pt

react
```
const 56756 = {
  width: 229,
  height: 34,
  fontFamily: "SourceSansPro",
  fontSize: 20,
  fontWeight: "600",
  fontStyle: "normal",
  lineHeight: 34,
  letterSpacing: 0,
  textAlign: "right",
  color: colors.BLACK
};
```

Swift
```
let 56756View: UIView = {
    let view = UIView()
    view.widthAnchor.constraint(equalToConstant: 229.0) = true
    view.heightAnchor.constraint(equalToConstant: 34.0) = true
    view.translatesAutoresizingMaskIntoConstraints = true

    return view
}()
```

**Comment by hboon** [comment]
@oa-s heads-up! @eviltofu worked on this in #3779. Remember to assign yourselves.
