### ISSUE TITLE
Remove green sent/received icons from the Activity

### ISSUE THREAD

**Issue by colourfreak** [AlphaWallet/alpha-wallet-ios#3770]
At this point, I don't think they make any sense. 
- too similar to each other
- look very bad with a network symbol on the other side of a token symbol
- look cluttered

I know that there are many issues related to Activities in https://github.com/AlphaWallet/alpha-wallet-ios/issues/3278, but this is the easy gain.

<img width="1781" alt="Screenshot 2022-01-21 at 10 25 54" src="https://user-images.githubusercontent.com/51817359/150502186-eb04a8b4-b9a0-4c06-9fef-3310e4a33370.png">

@hboon This issue needs your special attention. Might not be trivial.

**Comment by hboon** [comment]
@colourfreak got it. @oa-s should go ahead. Will keep a lookout.
