### ISSUE TITLE
Check/Replace the RPC for Fantom

### ISSUE THREAD

**Issue by hieronymus4826** [AlphaWallet/alpha-wallet-ios#3776]
Got two reports the current RPC for the Fantom network is not performing transactions on multiple websites. Can we please diagnose?

Maybe time to revisit the idea of allowing the end-user to edit the included networks to save us some time in the future

**Comment by hboon** [comment]
> Maybe time to revisit the idea of allowing the end-user to edit the included networks to save us some time in the future

Yes
