### ISSUE TITLE
Scanning wrong type of QR code results in the app asking you to open the browser but nothing happens after that

### ISSUE THREAD

**Issue by eviltofu** [AlphaWallet/alpha-wallet-ios#3787]
In the Import Wallet screen, if you scan a Singapore COVID QR entry code with the AlphaWallet qr code scanner, it asks if you want to open the url in the browser but if the user answers open nothing happens. If you scan in other places, the app does open a built in browser.

https://user-images.githubusercontent.com/1050309/150711372-749056c4-e24a-4220-82e3-47e119cb2ba9.mov

**Comment by oa-s** [comment]
@eviltofu can u share URL example scanned in qr code?

**Comment by eviltofu** [comment]
> @eviltofu can u share URL example scanned in qr code?

https://share.icloud.com/photos/038jNZBwOCtPg3RdcJo-nH-IQ

**Comment by eviltofu** [comment]
![IMG_0005](https://user-images.githubusercontent.com/1050309/151093937-290662cf-3ae7-4f3a-a692-1dd31f26209a.jpg)

@oa-s
