### ISSUE TITLE
Text for No Browse Networks Available is missing

### ISSUE THREAD

**Issue by eviltofu** [AlphaWallet/alpha-wallet-ios#3791]
Settings > Select Active Networks > + > Browse > Search
When there are no results matching the search criteria, the text under image is missing.
![IMG_8E74A319AF6F-1](https://user-images.githubusercontent.com/1050309/150734428-e342adff-e006-4bbf-81d1-7964fe5d8bf5.jpeg)

**Comment by eviltofu** [comment]
@hboon @oa-s Also do you think the image is too big and should be scaled down?

**Comment by hboon** [comment]
@eviltofu as in the file size or the dimensions? The former: sure if there's no noticeable loss of sharpness. Buzz Tomek to shrink if it's too big?

The latter, up to Tomek (unless it becomes ridiculously small or big :) )

**Comment by hboon** [comment]
Reopening. To close when topic on file size/dimensions concluded

**Comment by eviltofu** [comment]
> Reopening. To close when topic on file size/dimensions concluded

We could set the top and bottom margins to a minimum constant and have the image with proportionally constraint.

**Comment by hboon** [comment]
@eviltofu Seems OK when I did., would you help open an issue and close this one?

**Comment by eviltofu** [comment]
iPhone 12 mini

![Simulator Screen Shot - iPhone 12 mini - 2022-01-25 at 15 23 16](https://user-images.githubusercontent.com/1050309/150930124-3536e80c-ab79-4265-8359-afc97cacc0e5.png)
