### ISSUE TITLE
Right after importing a wallet and going to the Collectibles tab and waiting for a short while, the app shows this (a vertical gap)

### ISSUE THREAD

**Issue by oa-s** [AlphaWallet/alpha-wallet-ios#3795]
- [ ] Right after importing a wallet and going to the Collectibles tab and waiting for a short while, the app shows this (a vertical gap). Not sure if it's because the data is already loaded and not filled yet or is it a layout issue:

<img width="504" alt="Screenshot 2022-01-20 at 12 33 49 PM" src="https://user-images.githubusercontent.com/56189/150274495-55063269-16ec-4a0b-8f16-49ef56c6f2ce.png">

- [ ] It looks OK after a while:

<img width="504" alt="Screenshot 2022-01-20 at 12 35 17 PM" src="https://user-images.githubusercontent.com/56189/150274510-de7ae1f2-2908-4721-af5d-f6c557a1242d.png">

- [ ] But when I scroll down a few rows, I see this:

<img width="504" alt="Screenshot 2022-01-20 at 12 35 37 PM" src="https://user-images.githubusercontent.com/56189/150274512-58cd3c64-419d-4ec8-911f-ac14d0eb1c71.png">

**Comment by eviltofu** [comment]
Is there a default view when the image isn’t loaded yet?

**Comment by oa-s** [comment]
it displays placeholder image while the image is loading. in this PR there was a problem with caching cells. The caching breaks table view layout
