### ISSUE TITLE
Erc1155TokenInstanceViewController needs to have gray line removed from navigation bar

### ISSUE THREAD

**Issue by eviltofu** [AlphaWallet/alpha-wallet-ios#3813]
How to get to this screen:

1. Watch this wallet: `0xE115De7efe6129538C7F6F846801Cd45dF60b36d`
2. Tap Wallet > Assets 
3. Scroll, find, and tap Creepz Invasion Pass
4. Tap Assets, tap Creepz Invasion Pass 

![Screen Shot 2022-01-26 at 9 40 40 AM copy](https://user-images.githubusercontent.com/1050309/151089031-a29e22d6-d8d6-4926-a74e-f9558be568b3.png)

**Comment by eviltofu** [comment]
Cannot find a ERC1155 token in a wallet to verify. The example above was removed or not detectable. @oa-s @hboon

**Comment by hboon** [comment]
Is it like this?

<img width="498" alt="Screenshot 2022-01-27 at 12 42 28 PM" src="https://user-images.githubusercontent.com/56189/151293324-5ac0b4a7-a7bf-4d83-b4ad-533a2d253d0e.png">

This is the "Sugar (Genesis)" in hweeboon.eth
