### ISSUE TITLE
After scanning a watched wallet with the camera icon on the Wallet screen, the current wallet is not switched to the watched wallet.

### ISSUE THREAD

**Issue by eviltofu** [AlphaWallet/alpha-wallet-ios#3825]
I was watching `hweeboon.eth` then I added `0xEA674fdDe714fd979de3EdF0F56AA9716B898ec8` with the QR code scanner in the `Wallet` screen as a watched wallet. The current wallet did not switch from `hweeboon.eth` to the new wallet.

Adding a watched wallet via the `Wallets` screen does change the current wallet to the added wallet.

URL to [Wallet](https://etherscan.io/address/0xea674fdde714fd979de3edf0f56aa9716b898ec8)

**Comment by hboon** [comment]
But better not to use an address like 0xea674fdde714fd979de3edf0f56aa9716b898ec8. It's Ethermine's. Way too many transactions unless that's the point.
