### ISSUE TITLE
Hardcode a new Collection picture for the Enjin ERC1155 token

### ISSUE THREAD

**Issue by colourfreak** [AlphaWallet/alpha-wallet-ios#3827]
https://zpl.io/VqrDmol

**Comment by colourfreak** [comment]
![image](https://user-images.githubusercontent.com/51817359/151157145-2b9909c3-6fad-4957-a8d6-7f37e4e8091d.png)

![image](https://user-images.githubusercontent.com/51817359/151157160-0fffc7e1-410e-4e2e-8118-d54132af16b9.png)

**Comment by hboon** [comment]
Related: #3828

**Comment by colourfreak** [comment]
@hboon Maybe it's a good idea if you could create me a way to upload it. Something similar to what you did for iconassets

**Comment by hboon** [comment]
@colourfreak hmm.. Do we show this new icon in the search results too? If so, maybe all we have to do is just upload a file with a more suitable/bigger dimensions to the `iconassets` repo. Or would you like to stylized it a bit when it's bigger, maybe?

<img width="498" alt="Screenshot 2022-01-27 at 10 38 51 PM" src="https://user-images.githubusercontent.com/56189/151380586-6710a8a9-5ea2-474a-80cf-2a73ba893b03.png">

**Comment by hboon** [comment]
(But I'll check if we can use the same repo that way if we use the same icon in both places as described in the comment above, seems no reason why it wouldn't technically work)

**Comment by colourfreak** [comment]
Let me know. My goal: make these two screenshots I uploaded to look better and apply the same to the most common nft collections.

**Comment by hboon** [comment]
@colourfreak yeah, think it will work, just upload it to the `iconassets` repo with the larger file dimensions and it should work for the Wallet tab as well as the 1st screenshot in https://github.com/AlphaWallet/alpha-wallet-ios/issues/3827#issuecomment-1022120532. Will need to modify the app so it's also picked up for the 2nd screenshot though.

Can you attach one here? For Enjin maybe? I'll try it out first to make sure.

**Comment by colourfreak** [comment]
What format (png, jpeg, svg) and size?

**Comment by hboon** [comment]
PNG, like the ones we have for `iconassets`.

**Comment by hboon** [comment]
> Can we have PDF with alpha 0 background? Then we don’t need to resize for different cases?

Not at the moment. This is for a repo of images that has to be PNG. Look for `static let file = "logo.png"` in the codebase.

**Comment by colourfreak** [comment]
![arts-large-19](https://user-images.githubusercontent.com/51817359/151553741-357a3c0b-368c-4d0a-b907-bb0f751d36b9.png)
![arts-large-19@2x](https://user-images.githubusercontent.com/51817359/151553752-534020e6-ccd7-4d1a-b368-95df8ac6a163.png)
![arts-large-19@3x](https://user-images.githubusercontent.com/51817359/151553758-8a74766e-0e2c-4395-8f46-cd0bfac059ba.png)

**Comment by hboon** [comment]
@colourfreak the 1080x1080 looks like this:

<img width="498" alt="Screenshot 2022-01-31 at 11 22 42 AM" src="https://user-images.githubusercontent.com/56189/151734720-3a503376-551c-4cd1-8936-2e39b3bb4cb0.png">
<img width="498" alt="Screenshot 2022-01-31 at 11 22 37 AM" src="https://user-images.githubusercontent.com/56189/151734721-a2689159-1254-4893-b509-c19efe8d7c94.png">
<img width="498" alt="Screenshot 2022-01-31 at 11 23 45 AM" src="https://user-images.githubusercontent.com/56189/151734709-5ef3f98b-6b02-4f65-b69b-b945d83e4375.png">

Is that how you want them to look like?

**Comment by colourfreak** [comment]
> @colourfreak the 1080x1080 looks like this:
> 
> <img alt="Screenshot 2022-01-31 at 11 22 42 AM" width="498" src="https://user-images.githubusercontent.com/56189/151734720-3a503376-551c-4cd1-8936-2e39b3bb4cb0.png">
> 
> <img alt="Screenshot 2022-01-31 at 11 22 37 AM" width="498" src="https://user-images.githubusercontent.com/56189/151734721-a2689159-1254-4893-b509-c19efe8d7c94.png">
> 
> <img alt="Screenshot 2022-01-31 at 11 23 45 AM" width="498" src="https://user-images.githubusercontent.com/56189/151734709-5ef3f98b-6b02-4f65-b69b-b945d83e4375.png">
> 
> Is that how you want them to look like?

Yeah. Exactly.

**Comment by colourfreak** [comment]
@hboon So shall I upload 1080x1080? That might a fun task for me. Lots of graphics etc.

**Comment by hboon** [comment]
@colourfreak Yes. You wouldn't see them in the app right away because of https://github.com/AlphaWallet/iconassets/issues/9 and because this PR isn't merged yet, but they will start popping up in the next TestFlight.

1080x1080 sounds good, but can you help to check that each image isn't bigger than say ~40kb? If it's bigger, you can use a smaller file dimension for that particular one, eg. 720x720px.

If you have lots of them, feel free to zip it up for me (or Vlad) with the right names (just use the address.png as file name in a single folder) and we can help you to update the repo)

**Comment by colourfreak** [comment]
> @colourfreak Yes. You wouldn't see them in the app right away because of [AlphaWallet/iconassets#9](https://github.com/AlphaWallet/iconassets/issues/9) and because this PR isn't merged yet, but they will start popping up in the next TestFlight.
> 
> 1080x1080 sounds good, but can you help to check that each image isn't bigger than say ~40kb? If it's bigger, you can use a smaller file dimension for that particular one, eg. 720x720px.
> 
> If you have lots of them, feel free to zip it up for me (or Vlad) with the right names (just use the address.png as file name in a single folder) and we can help you to update the repo)

Sure, .png is usually heavy. I prefer .jpgs optimized with tools such as [mozjpeg](https://mozjpeg.com/). The compression is even better than with webp or avif images.

**Comment by colourfreak** [comment]
@hboon https://github.com/AlphaWallet/alpha-wallet-android/pull/2271#issuecomment-1034814174
