### ISSUE TITLE
Hardcode a new Collection picture for ENS token

### ISSUE THREAD

**Issue by colourfreak** [AlphaWallet/alpha-wallet-ios#3828]
https://zpl.io/VqrDmG5

**Comment by colourfreak** [comment]
![image](https://user-images.githubusercontent.com/51817359/151158643-8e880223-6a3a-468a-97dd-fc5f7cd6326a.png)

**Comment by colourfreak** [comment]
![image](https://user-images.githubusercontent.com/51817359/151158681-6404bf08-4875-40f3-af2c-4e05455b345e.png)

**Comment by hboon** [comment]
Related: #3827

**Comment by eviltofu** [comment]
@colourfreak How does one manually add the image? What steps does the user take? Long press on the image and pop up an image selector? Can you elaborate? Am I understanding the issue correctly?

**Comment by hboon** [comment]
> How does one manually add the image? What steps does the user take? Long press on the image and pop up an image selector? Can you elaborate? Am I understanding the issue correctly?

No. It's to hardcode the image displayed for this specific token (contract)

**Comment by eviltofu** [comment]
After #3581 ? @hboon

**Comment by hboon** [comment]
@eviltofu unrelated. But hold off this one first.
