### ISSUE TITLE
Are the Info and Activity tabs unnecessary when viewing a single ERC1155 token instance?

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#3833]
ERC721 assets list | single token
-|-
<img width="498" alt="Screenshot 2022-01-27 at 12 56 06 PM" src="https://user-images.githubusercontent.com/56189/151294514-cf63244f-cdc5-4ce6-877e-3595f1dfa09a.png">|<img width="498" alt="Screenshot 2022-01-27 at 12 56 07 PM" src="https://user-images.githubusercontent.com/56189/151294516-157a4957-71a7-4e91-b04b-4e2a49010e6e.png">
ERC1155 assets list | single token
<img width="498" alt="Screenshot 2022-01-27 at 12 55 52 PM" src="https://user-images.githubusercontent.com/56189/151294499-91df64ab-afa7-47cf-9a49-b4e57698e0a1.png">|<img width="498" alt="Screenshot 2022-01-27 at 12 55 54 PM" src="https://user-images.githubusercontent.com/56189/151295276-f34ebf16-e3d7-4fee-9d26-1d86ebea9401.png">

In the 4th, is the info and Activity tabs unnecessary?

**Comment by oa-s** [comment]
firstly it was implemented in erc721, and design didn't contain it, that isn't problem, we can add it.

**Comment by hboon** [comment]
Yeah. I think we should remove them. It’s in the previous screen already right?

**Comment by oa-s** [comment]
a little bit confused, do you want to remove pages or add them for erc1155?

**Comment by oa-s** [comment]
ok, sure
