### ISSUE TITLE
Replace the primary button color "green" to "cod"

### ISSUE THREAD

**Issue by colourfreak** [AlphaWallet/alpha-wallet-ios#3838]
Cod #141414

https://zpl.io/ag7YvpO
https://zpl.io/AmkONme
https://zpl.io/AmkONme

<img width="943" alt="Screenshot 2022-01-27 at 12 37 58" src="https://user-images.githubusercontent.com/51817359/151351640-1e2edbbc-55c9-4299-a063-c2a72f1f33ff.png">

**Comment by colourfreak** [comment]
Dark Mode
https://zpl.io/ag7YvpO
https://zpl.io/GEkne6r

**Comment by eviltofu** [comment]
@hboon Would this be a good place to suggest a `UIKitFactory`?

**Comment by hboon** [comment]
> @hboon Would this be a good place to suggest a `UIKitFactory`?

Nope. Changing the 2 button colors should be quite easy currently.

**Comment by eviltofu** [comment]
So do you want light/dark mode to be implemented as well? @hboon

**Comment by hboon** [comment]
Separately. This  button color change #3843 and then #3819 should be a quick change, then Dark mode after some refactoring

**Comment by eviltofu** [comment]
I can do this with dark/light mode with just one extra line…

**Comment by hboon** [comment]
Nah, better to ship this first. Dark mode is a bigger change. Could have complications.

**Comment by hboon** [comment]
> I can do this with dark/light mode with just one extra line…

Also, functionality-wise, they are separate features/changes hence separate PRs.

**Comment by eviltofu** [comment]
Is there a inactive dark theme colour for foreground and text of buttons? @colourfreak @hboon

**Comment by eviltofu** [comment]
> Primary - Light https://zpl.io/ag7YvpO
> 
> Secondary - Light https://zpl.io/V1gKq1w
> 
> Primary - Dark https://zpl.io/aRA5Y8e
> 
> Secondary - Dark https://zpl.io/bemqYpp

I'm asking for Dark **Inactive** primary and Dark **inactive** secondary. Like https://zpl.io/2vQJYAv but for Dark.

**Comment by colourfreak** [comment]
Alright.

### Primary Active
<img width="1346" alt="Screenshot 2022-02-10 at 11 51 55" src="https://user-images.githubusercontent.com/51817359/153395450-6e0dbe3c-4ef9-46ab-99f6-2a5f3e19b6fc.png">

Light
https://zpl.io/ag7YvpO

Dark
https://zpl.io/aRA5Y8e

----
### Primary Inactive
<img width="1307" alt="Screenshot 2022-02-10 at 11 53 17" src="https://user-images.githubusercontent.com/51817359/153395549-05635d52-d01e-485b-b7dd-9f3b17aef201.png">

Light
https://zpl.io/MdkpW5K

Dark
https://zpl.io/5EkpJe3

----
### Secondary Active

<img width="1234" alt="Screenshot 2022-02-10 at 12 10 43" src="https://user-images.githubusercontent.com/51817359/153395756-7ef87549-e1fa-4565-9b0a-8557c524a8d8.png">

Light
https://zpl.io/V1gKq1w

Dark
https://zpl.io/bemqYpp

----
### Secondary Inactive
<img width="1309" alt="Screenshot 2022-02-10 at 12 10 36" src="https://user-images.githubusercontent.com/51817359/153395904-e5817da3-6a0b-4e3b-ac48-2941fb55165e.png">

Light
https://zpl.io/1ykQOeX

Dark
https://zpl.io/RMgzxon
