### ISSUE TITLE
Token title's descender clipped in Collectibles tab

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#3841]
"Enjin". Verify first? I pulled this screenshot from an unrelated issue :)

![151157145-2b9909c3-6fad-4957-a8d6-7f37e4e8091d](https://user-images.githubusercontent.com/56189/151379704-dd0f85d3-d252-48e4-ab22-d0fa35f0efc6.png)

**Comment by oa-s** [comment]
@hboon seems like it doesn't relevant anymore

**Comment by hboon** [comment]
Right. Thanks for checking.
