### ISSUE TITLE
Account with hundreds of tokens crashes the app

### ISSUE THREAD

**Issue by aliveli186** [AlphaWallet/alpha-wallet-ios#3850]
If the newly added account has long list of tokens and AlphaWallet tries to identify all of them in the background results with AlphaWallet crash.

**Comment by hboon** [comment]
@aliveli186 (I know you mentioned hundreds), but how many tokens would you say that should be in that account? Say ~100, or 300-800, or a thousand?

How about number of transactions?

**Comment by aliveli186** [comment]
Seems to be 1069 assets total.
Here is the addres:
https://ropsten.etherscan.io/tokenholdings?a=0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266

**Comment by hboon** [comment]
@aliveli186 thanks! Will check it out.

**Comment by Saif-Fazlani** [comment]
Hi, I also faced this issue. My total token count was around 50, yet the app still crashed.

**Comment by hboon** [comment]
@Saif-Fazlani we'll be fixing this. Thanks for reporting.

**Comment by oa-s** [comment]
Close as not reproducible
