### ISSUE TITLE
After tapping ERC1155 (and ERC721), Assets tab is selected, but contents is still from Info tab

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#3853]
Related to #3846

After tap token in Wallet tab|Tap Info and then Assets again
-|-
<img width="498" alt="Screenshot 2022-01-31 at 10 24 53 AM" src="https://user-images.githubusercontent.com/56189/151730824-cc938f85-88c1-4004-abdb-9ba84e26eea8.png">|<img width="498" alt="Screenshot 2022-01-31 at 10 24 56 AM" src="https://user-images.githubusercontent.com/56189/151730831-a4a748b1-95d4-4c08-a5c1-c044186af1fe.png">

**Comment by eviltofu** [comment]
Probably an error due to the new ScrollableSegmentedControl.
