### ISSUE TITLE
Polygonscan API update

### ISSUE THREAD

**Issue by JamesSmartCell** [AlphaWallet/alpha-wallet-ios#3859]
Polygonscan updated their API code, it now takes the action=tokennfttx switch same as Etherscan, so you'll need to check both `=tokentx` and `=tokennfttx`, if you aren't already doing so.

**Comment by hboon** [comment]
@JamesSmartCell Hmm.. we have always done it that way. But just to be sure, here's how we classify the chains to decide whether to use `tokennfttx` (those returning `.etherscan` does): https://github.com/AlphaWallet/alpha-wallet-ios/issues/3859
