### ISSUE TITLE
Upgrade WalletConnect with latest `0.4.0` version

### ISSUE THREAD

**Issue by oa-s** [AlphaWallet/alpha-wallet-ios#3882]
https://github.com/WalletConnect/WalletConnectSwiftV2

**Comment by oa-s** [comment]
@colourfreak Can we make an icon of AlphaWallet and upload it somewhere kind of `iconassets`. We  need an icon, for Wallet Connect session. For now we are using the next url: `https://avatars.githubusercontent.com/u/36216689?s=88&v=4`. The size, actually i don't know maybe some kind of `100*100` 
<img width="508" alt="Screenshot 2022-02-08 at 15 54 56" src="https://user-images.githubusercontent.com/96283950/153001304-747cda9d-d358-45c1-b02c-207747d44d4b.png">

**Comment by hboon** [comment]
@oa-s maybe in alphawallet.com. Probably better to do it with aw.app, but seems less reliable there

**Comment by hboon** [comment]
No, I mean if you get one, let’s host it on AlphaWallet.com

**Comment by oa-s** [comment]
Oh, i see. That not a problem.
`url: https://avatars.githubusercontent.com/u/36216689?s=88&v=4.` I only shown where i got current icon
