### ISSUE TITLE
Wallet tab should display symbol name instead of token name for ENS and aUSDC

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#3891]
In hweeboon.eth. Seems like it should, according to #3184.

ENS|aUSDC
-|-
<img width="498" alt="Screenshot 2022-02-09 at 2 15 10 PM" src="https://user-images.githubusercontent.com/56189/153132866-5feaefe3-ab92-4eed-8038-5bfbd1abc444.png">|<img width="498" alt="Screenshot 2022-02-09 at 2 15 13 PM" src="https://user-images.githubusercontent.com/56189/153132875-e02a757e-de5d-4623-8547-74f71708e8e1.png">

Can you help add test cases?

**Comment by oa-s** [comment]
Does it need to be applied only for `ens`, and `aUSDC` tokens ?

**Comment by hboon** [comment]
Not only `ENS` definitely. Could you look at #3184 and see what's the criteria? The gist of it should be: if a token has a long name and short symbol, the symbol should be used instead. Maybe #3184 is lost?
