### ISSUE TITLE
Add a screen where you can switch to Dark/Light/Auto mode

### ISSUE THREAD

**Issue by colourfreak** [AlphaWallet/alpha-wallet-ios#3901]
We need one more item in the Settings (System section)
![Settings_Default_Full](https://user-images.githubusercontent.com/51817359/153614596-9a382206-b372-418c-af67-5189a6a06338.jpg)

Then you can change the mode to 

- Light
- Dark
- Auto

![Select-Mode](https://user-images.githubusercontent.com/51817359/153614663-4c1e2490-e3a6-4833-9b2c-4a7e38a7b332.jpg)

### Zeplin:
https://zpl.io/8lkGeAw
https://zpl.io/bee6kjp

**Comment by hboon** [comment]
Let's skip this one for now
