### ISSUE TITLE
Gotcha with L2 base chain transfer

### ISSUE THREAD

**Issue by JamesSmartCell** [AlphaWallet/alpha-wallet-ios#3904]
Something I discovered and just fixed (https://github.com/AlphaWallet/alpha-wallet-android/commit/d20443928b574e7614ca373395e7992f4381d910) on L2 chains.

- The gas used (gaslimit) for a L2 base chain transfer may not be 21000. For Arbitrum it isn't.
- Arbitrum requires the exact gaslimit or the transaction won't go through.
- Use eth_estimateGas for base chain transfers. For L1, it's safe to always set at 21000, but L2 it isn't.

Also, if you implement Arbitrum use these transaction API / block explorer endpoints:

Block Explorer:

https://arbiscan.io/tx/
https://testnet.arbiscan.io/tx/

API:

https://api.arbiscan.io/api?
https://testnet.arbiscan.io/api?

These use an etherscan fork so work identically to all the usual calls.

Note: Eth Denver is using Arbitrum/Arbitrum Test for some services.

**Comment by hboon** [comment]
@JamesSmartCell ah, kind of like Optimistic? #1959

**Comment by JamesSmartCell** [comment]
Is that the right PR link? That's the original WalletConnect.

**Comment by hboon** [comment]
Wrong one. Have updated the comment.

**Comment by hboon** [comment]
Yes, we always use `eth_estimateGas` for all chains on iOS. Verified to be working.
