### ISSUE TITLE
App crashes while deleting a wallet.

### ISSUE THREAD

**Issue by Saif-Fazlani** [AlphaWallet/alpha-wallet-ios#3908]
While deleting a wallet on iPhone 12 Pro simulator, the app crashes with Thread 1: EXC_BAD_ACCESS (code=1, address=0x18).
Attaching an image of the stack trace.

<img width="784" alt="Screenshot 2022-02-14 at 5 26 58 PM" src="https://user-images.githubusercontent.com/96777132/153864204-4329ea71-e731-4a6b-b37e-0f6dcc7b27ec.png">

**Comment by hboon** [comment]
@Saif-Fazlani thanks for reporting.

**Comment by oa-s** [comment]
Non reproducible, reopen if appeared again.
