### ISSUE TITLE
Add Swap feature

### ISSUE THREAD

**Issue by colourfreak** [AlphaWallet/alpha-wallet-ios#3919]
### How to access Swap feature?

- For now, we let users to access the swap feature from the token menu (we will keep Send and Swap as main actions)
![ETH-Short](https://user-images.githubusercontent.com/51817359/154047080-1002c6c1-b720-47e4-8607-6d0157f0ff98.jpg)

- The second option will be in the dotted menu at the top
![Wallet-Menu](https://user-images.githubusercontent.com/51817359/154047132-6b13664e-8715-4f60-aae7-51f97e492b77.jpg)

- When we will test it positively (I know how bad it sounds nowadays), we can transform the tab bar so it has one more button int the centre. 
![Wallet-New](https://user-images.githubusercontent.com/51817359/154047170-969c77cc-7833-47cb-9f66-439c8ce20e3b.jpg)
![Wallet-Actions](https://user-images.githubusercontent.com/51817359/154047188-0fae4155-e4e5-4856-a715-aacc57f5d548.jpg)

### Invision prototype
https://invis.io/Z412DM7HGXTF

### Screenshots

- Default view
![Swap-Empty](https://user-images.githubusercontent.com/51817359/154047463-1f548f2b-5149-4d35-933a-220574daba7f.jpg)

- Token selection
![Swap-Select-Token](https://user-images.githubusercontent.com/51817359/154047498-5c0ad579-f047-4427-912e-6450a386fa74.jpg)

- Settings (you access in the top right icon)
![Swap-Settings](https://user-images.githubusercontent.com/51817359/154047528-4d36dcee-21d5-449e-8b3b-550f48dbd09f.jpg)

- Tokens selected, no amount entered
![Swap-Default](https://user-images.githubusercontent.com/51817359/154047614-ddc12dd6-b81b-44f9-8710-9f682f6b914a.jpg)

- Entering amount
![Swap-Entered](https://user-images.githubusercontent.com/51817359/154047696-2afd035b-16f0-4f9b-84f4-64f3a47f500d.jpg)

- You can expand the Fees view
![Swap-Expanded](https://user-images.githubusercontent.com/51817359/154047783-cac70e8d-5c0e-4a0a-98cf-8a3d97ce32b6.jpg)

- Confirmation
![Swap-Confirmation](https://user-images.githubusercontent.com/51817359/154047885-ecefc93c-38a3-48b9-91d5-b6198e769f84.jpg)

### Zeplin:
https://zpl.io/7wkvBnW

### Working on:
Few more states, when the price has been updated, no search results when selecting a token, switching to networks etc.

**Comment by hboon** [comment]
@oa-s if you haven't, don't work on the actionsheet confirmation screen yet. I might add it on my side. i.e. the last screenshot above.

**Comment by oa-s** [comment]
> @oa-s if you haven't, don't work on the actionsheet confirmation screen yet. I might add it on my side. i.e. the last screenshot above.

got it

**Comment by oa-s** [comment]
Working on `Entering amount`, `Token selection`, settings screens

**Comment by oa-s** [comment]
> Working on `Entering amount`, `Token selection`, `Settings` screens

**Comment by hboon** [comment]
Thanks. Yeah, everything else except the confirmation actionsheet.

**Comment by hboon** [comment]
@oa-s The backend code is available in the https://github.com/AlphaWallet/alpha-wallet-ios/tree/swap branch. Would you help to integrate it into the UI you are working on and add missing pieces?

The li.fi API supports both swap (same-chain) and bridging (cross-chain). We only implement swaps at the moment, so `fromChain` and `toChain` are always the same.

`SwapViewController` is only for development and should be removed. `SwapViewController` and `TokenSwapCoordinator` contains the driver code for swapping currently. For example displaying a list of quotes for the user to try from isn't implemented. Meta information and options like slippage isn't implemented too. We can skip them first. I haven't made the code fit into `TokenActionsProvider` yet. See if you want to leave it to a future PR.

There are actual UI integration and bits and pieces left to do; as usual, look out for the `//hhh`s and `NSLog("xxx`s.

To start the swap process, tap on the blockie button in Wallet tab to launch `SwapViewController`:

<img width="200" alt="Screenshot 2022-04-06 at 1 24 55 PM" src="https://user-images.githubusercontent.com/56189/161901782-98aaed4f-143c-4b7e-a535-fb5f1cfdd224.png">

The 3 buttons correspond to the 3 endpoints li.fi provides:

* "Fetch Chains" — get supported chains. Use this to limit which chains the user can choose in the swap UI
* "Fetch Tokens" — get supported swap "pairs" for selected chain. This is parsed into a `SwapPairs` object that return a list of "to" tokens given a "from" token. i.e we can use `SwapPairs` to popular to the list of "to" tokens based on user's selection
* "Swap" — fetch the transaction (in li.fi terminology the "quote") that will perform the swap functionality. This will sometimes require an ERC20 approval. Look for `SwapViewController.swap()` which fetches the transaction, checks if an ERC20 is required (prompt if necessary) and then prompts the user to sign the swap transaction.

Fetch chains
---
```
curl --url 'https://li.quest/v1/chains' --header 'Accept: application/json' --header 'Content-Type: application/json' | json_pp
```

Fetch Tokens
---
```
curl --url 'https://li.quest/v1/connections?fromChain=1&toChain=1' --header 'Accept: application/json' --header 'Content-Type: application/json' | json_pp
```

Swap
---
```
curl --request GET --url 'https://li.quest/v1/quote?fromChain=137&toChain=137&fromToken=0x7ceB23fD6bC0adD59E62ac25578270cFf1b9f619&toToken=0x0000000000000000000000000000000000000000&fromAddress=0xbbce83173d5c1D122AE64856b4Af0D5AE07Fa362&fromAmount=1000000000000000&order=BEST_VALUE&slippage=0.05' --header 'Accept: application/json' | json_pp
```

The quote API returns 503 sometimes. Just drop or retry.

If the from amount is too small, this error might be returned:

```
"message": "Unable to find a quote for the requested transfer."
```

Docs
===
The API docs are at https://apidocs.li.finance/reference/welcome-to-the-lifinance-api

The JavaScript SDK examples are easy to read to understand how to use the APIs https://apidocs.li.finance/reference/how-to-transfer-tokens

Others
---
Remember to use Polygon where possible. Cheaper to try

**Comment by hboon** [comment]
Re-opening since it's not ship-ready yet.

**Comment by hboon** [comment]
@oa-s what's left? Should I test more with `master`?

**Comment by hboon** [comment]
@hboon needs to test

**Comment by hboon** [comment]
Already done
