### ISSUE TITLE
Add the option to remove Watch Wallets

### ISSUE THREAD

**Issue by hieronymus4826** [AlphaWallet/alpha-wallet-ios#3941]
I think we used to have this, but it doesn't seem to be there now after the change from swap to hold.

Its the same for Android I believe

**Comment by hboon** [comment]
@hieronymus4826 It's available.

iOS:

* Swipe the watched wallet and tap X. It must not be the current wallet

Android:

* Tap the kebab button and tap "Lose this Wallet"

**Comment by hieronymus4826** [comment]
Thanks Boon!

The key is 'not the current wallet'

Also on Android the kebap has been removed and you have to tap the image (not intuitive IMHO)

Sorry for the misunderstanding
