### ISSUE TITLE
Title for disabled secondary button not visible

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#3945]
<img width="487" alt="Screenshot 2022-02-17 at 11 02 55 AM" src="https://user-images.githubusercontent.com/56189/154396920-5b37e699-408e-418c-af16-b3016bca59ba.png">

**Comment by eviltofu** [comment]
Ok will fix after lunch.

**Comment by eviltofu** [comment]
The blue button with the ellipses, should it be a secondary style button too? Should I do the change here? @hboon

**Comment by hboon** [comment]
>  Should I do the change here?

No. But just leave it for now. And we can see it in action.
