### ISSUE TITLE
Move logic out of coordinators so they are primarily navigation/glue code between screens

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#3990]
We have very fat coordinators.

Where possible, we should move logic out of coordinator, starting with those that can grouped together easily, eg. into something like `AddCustomChain` and supporting code in the same file.

Refactor bit by bit. Avoid huge PRs.

**Comment by eviltofu** [comment]
`AssetDefinitionStoreCoordinatorDelegate` is used for showing errors and adding new scripts. `AssetDefinitionStoreCoordinator` appears to be used mainly for importing scripts.

**Comment by eviltofu** [comment]
`PromptBackupCoordinator` is used in `AppCoordinator` but is not stored in the `coordinators` variable. It's sort of left hanging there.

**Comment by hboon** [comment]
@eviltofu Would you help to update this list, with a short sentence and if there is one, link to the comment?

- [ ] [AssetDefinitionStoreCoordinatorDelegate is used for showing errors and adding new scripts. AssetDefinitionStoreCoordinator appears to be used mainly for importing scripts and not navigation.](https://github.com/AlphaWallet/alpha-wallet-ios/issues/3990#issuecomment-1131289297)
- [ ] Something else

**Comment by hboon** [comment]
Refer to #6606
