### ISSUE TITLE
Replace with using single `TokensDataStore`

### ISSUE THREAD

**Issue by oa-s** [AlphaWallet/alpha-wallet-ios#3992]
`TokensDataStore` for each server could be updated with single `TokensDataStore` that supports fetching with `forServer` param.
It simplify future migrations for raw data store, (replace `Realm` with something else). Conform `TokensDataStore` to `TokensDataStoreType` and to improve testability.

**Comment by hboon** [comment]
>`TokensDataStore` for each server could be updated with single `TokensDataStore` that supports fetching with `forServer` param. ...

@oa-s but what if we switch to a datastore and we need to store those objects in the datastore? Or pass around data for 1 RPCServer? Would it make it harder?

**Comment by oa-s** [comment]
nope, as we conform it to protocol

**Comment by oa-s** [comment]
> nope, as we conform it to protocol

Just conform a new storage to protocol, and implement appropriate functions
