### ISSUE TITLE
Add action to Settings > Advanced > Tools to paste a transaction hash to check transaction state against RPC (not Etherscan)

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#4003]
Like the Infura ping, but paste a transaction hash into the popup and buzz Infura for transactions state and display it

**Comment by oa-s** [comment]
@hboon does it require to use an api [relay_getTransactionStatus](https://docs.infura.io/infura/features/transactions#relay_gettransactionstatus)?

**Comment by hboon** [comment]
@oa-s no, use `eth_getTransactionByHash`. Look for: `GetTransactionRequest`

**Comment by hboon** [comment]
`relay_getTransactionStatus` is for ITX. See https://www.notion.so/stormbirdlabs/Gas-less-transactions-4d66ad613de44812a6473d03dd3cda21#51230c3f15594659b5e23b29c67f60e9 for ITX
