### ISSUE TITLE
Add Klaytn as bundled chain

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#4047]
But disabled first.

**Comment by colourfreak** [comment]
Need icon?

**Comment by hboon** [comment]
@colourfreak oh yes, I missed that. Thanks

**Comment by colourfreak** [comment]
**Klaytn network icon**
https://zpl.io/dxmooEe

**Klay token**
https://zpl.io/40kXj1p

**Comment by hboon** [comment]
Closed by #4198 and #4206
