### ISSUE TITLE
WalletConnect 2 eth_signTypedData crash

### ISSUE THREAD

**Issue by seabornlee** [AlphaWallet/alpha-wallet-ios#4057]
name: Bug Report
about: It crashed, and rerun got a blank screen.

---

**Describe the bug**

**Steps to reproduce (REQUIRED)**
Steps to reproduce the behavior

1. Connect to WalletConnect 2 test Dapp https://react-app.walletconnect.com/
2. Invoke eth_signTypedData
3. App crashed
4. Rerun

**Expect**
App started.

**Observed**
Blank screen with nothing.

**Screenshots**
![image](https://user-images.githubusercontent.com/735708/157579516-3fbce582-ec7d-469b-b83b-621d06b6cb38.png)

**Version or build number number**
3.36

**Comment by oa-s** [comment]
The crash happens due to missing `EIP712Domain` part in received data

**Comment by oa-s** [comment]
@seabornlee  does missing part of `EIP712Domain` handled somehow in Android?

**Comment by seabornlee** [comment]
Yes, it has been caught and shows an empty message to the user. That's why I turn to test how iOS behaves.
I think it's a problem with WC sample Dapp. I left a question for them.

**Comment by oa-s** [comment]
oh, i see in iOS it wasn't handled, only force unwrap  with expectation that the value always present.
