### ISSUE TITLE
Update App Store Graphics

### ISSUE THREAD

**Issue by colourfreak** [AlphaWallet/alpha-wallet-ios#4074]
I don't have access to Google Drive, so sharing from the encrypted cloud. 

https://web.tresorit.com/l/VVKaQ#ToERAoDZyQM97iQTtzOSZA

**Comment by colourfreak** [comment]
![10_iPhone6 5](https://user-images.githubusercontent.com/51817359/158185979-90a2d7e0-d8a3-4ee3-bfce-1574880f6c7a.jpg)
![1_iPhone6 5](https://user-images.githubusercontent.com/51817359/158185990-e56a0d09-2dde-4a2b-80e1-bdf7dd04f865.jpg)
![2_iPhone6 5](https://user-images.githubusercontent.com/51817359/158185997-a182e214-c0a1-4519-a8d3-ca1340526d52.jpg)
![3_iPhone6 5](https://user-images.githubusercontent.com/51817359/158186008-5b01eb07-75a0-41eb-b3cf-4443af7c01e4.jpg)
![4_iPhone6 5](https://user-images.githubusercontent.com/51817359/158186015-b09d8a10-7dbb-480d-8b13-96f087102c34.jpg)
![5_iPhone6 5](https://user-images.githubusercontent.com/51817359/158186023-6db3a98b-2e00-4ca4-86e3-d53b28dc9ab7.jpg)
![6_iPhone6 5](https://user-images.githubusercontent.com/51817359/158186031-6ce9b868-f2ee-40c3-b1b9-40199b7f8e2d.jpg)
![7_iPhone6 5](https://user-images.githubusercontent.com/51817359/158186039-c0bf9753-7c5f-4bcb-a3a6-803dc7d1bc1f.jpg)
![8_iPhone6 5](https://user-images.githubusercontent.com/51817359/158186046-3525e767-885d-4ec2-b9fb-02118d784142.jpg)
![9_iPhone6 5](https://user-images.githubusercontent.com/51817359/158186053-e2830e6a-75ea-4a66-b124-52b7a4906616.jpg)

**Comment by colourfreak** [comment]
![1_iPhone5 5](https://user-images.githubusercontent.com/51817359/158186179-1aa82e50-b250-458c-8279-f2ec7b0f56e5.jpg)
![2_iPhone5 5](https://user-images.githubusercontent.com/51817359/158186197-349fd7c2-bb1e-4d3d-8778-5357408d72c2.jpg)
![3_iPhone5 5](https://user-images.githubusercontent.com/51817359/158186208-c71b508a-b74e-4ace-80b6-6aded16d3ce7.jpg)
![4_iPhone5 5](https://user-images.githubusercontent.com/51817359/158186215-2f392172-d23b-42a3-85fd-5b4cb0826f0b.jpg)
![5_iPhone5 5](https://user-images.githubusercontent.com/51817359/158186217-4391ecea-b542-4b90-82ee-363e33df8137.jpg)
![6_iPhone5 5](https://user-images.githubusercontent.com/51817359/158186220-1d31ffe4-d203-4fd0-8850-0da4aeacf7ae.jpg)
![7_iPhone5 5](https://user-images.githubusercontent.com/51817359/158186225-4d4e5e6d-24d8-4cbb-9f19-7a5c26a89472.jpg)
![8_iPhone5 5](https://user-images.githubusercontent.com/51817359/158186233-da8d6671-5aeb-4d03-9e16-3814d60d5972.jpg)
![9_iPhone5 5](https://user-images.githubusercontent.com/51817359/158186238-6b9bac5a-c96e-4b8d-88e6-277692a989a7.jpg)
![10_iPhone5 5](https://user-images.githubusercontent.com/51817359/158186243-5873ae9a-a6b1-4ae3-ba1e-eddd3d7e5ff7.jpg)

**Comment by colourfreak** [comment]
![1_iPad12 9_2nd](https://user-images.githubusercontent.com/51817359/158186287-9a154d88-591a-480a-8755-526c8af7e8a4.jpg)
![2_iPad12 9_2nd](https://user-images.githubusercontent.com/51817359/158186316-24c9a535-e884-4aca-855a-3acec1ec1368.jpg)
![3_iPad12 9_2nd](https://user-images.githubusercontent.com/51817359/158186323-7578d7c3-e466-4e50-9b02-826beb51b461.jpg)
![4_iPad12 9_2nd](https://user-images.githubusercontent.com/51817359/158186331-0c7e8027-5c02-4f4b-ab3d-a06a4d7d0a06.jpg)
![5_iPad12 9_2nd](https://user-images.githubusercontent.com/51817359/158186336-84310da9-a2d2-42a6-bf09-290bd0a0fc68.jpg)
![6_iPad12 9_2nd](https://user-images.githubusercontent.com/51817359/158186342-63f79e50-c5ae-4bb6-88a5-ea24cc7a5e58.jpg)
![7_iPad12 9_2nd](https://user-images.githubusercontent.com/51817359/158186358-dcb23569-2cf7-426a-bf19-bda36d56136b.jpg)
![8_iPad12 9_2nd](https://user-images.githubusercontent.com/51817359/158186366-b34dbed5-4903-486e-ae91-6e5db2f4598f.jpg)
![9_iPad12 9_2nd](https://user-images.githubusercontent.com/51817359/158186368-9fe5c0f9-e66b-4d46-bdaf-7fdcd6ccab46.jpg)
![10_iPad12 9_2nd](https://user-images.githubusercontent.com/51817359/158186377-d9b4577a-7544-4cf6-82ad-ded0d41e09ad.jpg)

**Comment by colourfreak** [comment]
![1_iPad12 9_3rd](https://user-images.githubusercontent.com/51817359/158186482-c5984144-1c81-4617-b8c5-a1b0413c2743.jpg)
![2_iPad12 9_3rd](https://user-images.githubusercontent.com/51817359/158186499-3eb7af62-834d-4293-a855-45f532178068.jpg)
![3_iPad12 9_3rd](https://user-images.githubusercontent.com/51817359/158186506-a5e4b0ae-e09e-4c94-aa64-d11c800caa2f.jpg)
![4_iPad12 9_3rd](https://user-images.githubusercontent.com/51817359/158186514-87b5029d-1ac3-4ef3-bf23-6f07bb1b5994.jpg)
![5_iPad12 9_3rd](https://user-images.githubusercontent.com/51817359/158186520-bf7043f8-bfaf-40a6-8fd2-28e9cb5d2dd6.jpg)
![6_iPad12 9_3rd](https://user-images.githubusercontent.com/51817359/158186527-7a19151f-867c-4fb7-91cd-91775290bcdd.jpg)
![7_iPad12 9_3rd](https://user-images.githubusercontent.com/51817359/158186536-28b05f2e-4666-4f8c-bd3f-938bd002f9f8.jpg)
![8_iPad12 9_3rd](https://user-images.githubusercontent.com/51817359/158186538-ea646f5b-a376-46d2-8682-903478d15a43.jpg)
![9_iPad12 9_3rd](https://user-images.githubusercontent.com/51817359/158186547-736ea26e-eba5-41dc-bbaf-45d1a35809b7.jpg)
![10_iPad12 9_3rd](https://user-images.githubusercontent.com/51817359/158186557-c3ba3c3c-ca20-404c-a3d7-147f55f4c271.jpg)

**Comment by hboon** [comment]
@colourfreak Looks great. Thanks!

There's a spurious "an" in "Buy & Swap Tokens with an Ease".

I'm not sure about the "Non Fungible Tokens" title, but let's try it.

Just to be sure, for the app store screenshots, we need these 3 sets of dimensions:

iPhone 5.5": 1242 x 2208 px

iPhone 6.5": 1242 x 2688 px

iPad Pro 12.9": 2048 x 2732 px

Seems like we have all 3 already (I didn't check every one of them, a little hard to navigate). Would you help verify? And if possible zip them, as 3 zip files?

**Comment by colourfreak** [comment]
> @colourfreak Looks great. Thanks!
> 
> There's a spurious "an" in "Buy & Swap Tokens with an Ease".
> 
> I'm not sure about the "Non Fungible Tokens" title, but let's try it.
> 
> Just to be sure, for the app store screenshots, we need these 3 sets of dimensions:
> 
> iPhone 5.5": 1242 x 2208 px
> 
> iPhone 6.5": 1242 x 2688 px
> 
> iPad Pro 12.9": 2048 x 2732 px
> 
> Seems like we have all 3 already (I didn't check every one of them, a little hard to navigate). Would you help verify? And if possible zip them, as 3 zip files?

Improved all. Please download zip from here

https://web.tresorit.com/l/VVKaQ#ToERAoDZyQM97iQTtzOSZA

**Comment by hboon** [comment]
TestFlight build v3.37 421 submitted with the existing screenshots. Will follow up with another submission with the new ones (want to get the app changes in first)

**Comment by hboon** [comment]
Closed previously with the build number mentioned above a few submissions ago.
