### ISSUE TITLE
Many "Socket is not connected" errors from WalletConnect

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#4079]
I'm still getting this in the console as of 4098a9dc814f7462f40a7008a0e2e8e21341aa5c. Might have been from switching accounts back and forth, restarting the app a few times. It's currently not showing any active WalletConnect sessions in the Wallet tab and I haven't used WalletConnect for a while. Do they represent a bug (session management? In the app or SDK)?

> WebSocket Error receiveMessageFailure(Error Domain=NSPOSIXErrorDomain Code=57 "Socket is not connected" UserInfo={NSErrorFailingURLStringKey=https://relay.walletconnect.com/?projectId=6eb1175ea3e57209d8f8f39bd4213691, NSErrorFailingURLKey=https://relay.walletconnect.com/?projectId=6eb1175ea3e57209d8f8f39bd4213691})
> WebSocket Error receiveMessageFailure(Error Domain=NSPOSIXErrorDomain Code=57 "Socket is not connected" UserInfo={NSErrorFailingURLStringKey=https://relay.walletconnect.com/?projectId=6eb1175ea3e57209d8f8f39bd4213691, NSErrorFailingURLKey=https://relay.walletconnect.com/?projectId=6eb1175ea3e57209d8f8f39bd4213691})
> WebSocket Error receiveMessageFailure(Error Domain=NSPOSIXErrorDomain Code=57 "Socket is not connected" UserInfo={NSErrorFailingURLStringKey=https://relay.walletconnect.com/?projectId=6eb1175ea3e57209d8f8f39bd4213691, NSErrorFailingURLKey=https://relay.walletconnect.com/?projectId=6eb1175ea3e57209d8f8f39bd4213691})
> WebSocket Error receiveMessageFailure(Error Domain=NSPOSIXErrorDomain Code=57 "Socket is not connected" UserInfo={NSErrorFailingURLStringKey=https://relay.walletconnect.com/?projectId=6eb1175ea3e57209d8f8f39bd4213691, NSErrorFailingURLKey=https://relay.walletconnect.com/?projectId=6eb1175ea3e57209d8f8f39bd4213691})

**Comment by oa-s** [comment]
Close due to duplication of #3863
