### ISSUE TITLE
Update the following screens with new VerticalButtonsBar

### ISSUE THREAD

**Issue by eviltofu** [AlphaWallet/alpha-wallet-ios#4089]
Based on https://github.com/AlphaWallet/alpha-wallet-ios/issues/3819#issuecomment-1023288063

- ~~Import Wallet Private Key~~
- [x] Import Wallet Key Store
- ~~Import Wallet Seed~~
- [x] Back up

**Comment by eviltofu** [comment]
@hboon The import from cloud option only appears in the current master branch for import Key store. Do I have to implement it for the import private key and import wallet seed?

**Comment by hboon** [comment]
No, keep it that way — just available for keystore file. Generally only keystore files, which are encrypted (though it’s weak) are saved to the file system. Not seed phrases. And that’s why seed phrases are the recommended way to go.

**Comment by eviltofu** [comment]
I would like to refactor this into a container view and have several simpler views for each tab. Currently it has one view and the various text fields etc are hidden and shown depending on which tab is focused. It also complicates the layout.

**Comment by hboon** [comment]
Sure. Just remember to also work on higher priority items. If ugliness that requires refactoring is self-contained, it's not high priority.
