### ISSUE TITLE
The bottom buttons should be at the same level for the Back up sequence

### ISSUE THREAD

**Issue by eviltofu** [AlphaWallet/alpha-wallet-ios#4090]
![same level](https://user-images.githubusercontent.com/1050309/158514530-3cef5c0a-f86d-492e-8f9e-e717a8d20e0a.png)

**Comment by hboon** [comment]
Can you make the issue clearer? If it's alignmennt, maybe combine the images and draw a line?

**Comment by eviltofu** [comment]
> Can you make the issue clearer? If it's alignmennt, maybe combine the images and draw a line?

Updated

**Comment by eviltofu** [comment]
What should the vertical bottom level be? I just noticed that for devices with the curved bevel bottom (iPhone X onwards) and those without (iPad, iPod) placing the buttons at the safe area layout guide looks a bit different. @colourfreak @hboon

**Comment by hboon** [comment]
The one on the right (with the seed phrase shown) looks a bit better. So make it something like that? It should be computed from bottom safe area + x so that it will be like this:

With physical home button: X (bottom safe area is 0 anyway)
With virtual home bar: bottom safe area + X

Then we can see how it looks like on an actual device and tweak if necessary. The main concern is not to be too low that it interferes with the virtual home bar. So, better to test it on a device, and Tomek can tweak it.

**Comment by eviltofu** [comment]
I'm thinking (1) distance of X from the bottom and (2) right at the bottom of the safe area where (1) has a higher priority over (2) in auto layout terms. So it will always be at least X from the bottom.

**Comment by eviltofu** [comment]
@hboon Do I have to check all the screens to make sure the buttons all follow this format after this is done?

**Comment by hboon** [comment]
> AutoLayout Constraints: **(1) At least X from bottom *(2) At least 0 from Safe Area Bottom ***(3) Must be within Safe Area
> 
> Stars represent higher priority

Why not fixed it?

**Comment by hboon** [comment]
> @hboon Do I have to check every screen to make sure all the bottom buttons follow this format after this is done?

Let's just do 1 first and over time work on the rest. Low priority

**Comment by eviltofu** [comment]
> Why not fixed it?

At least with constraints I can be sure it will apply to all current and future devices if they have different safe areas

**Comment by hboon** [comment]
> > Why not fixed it?
> 
> At least with constraints I can be sure it will apply to all current and future devices if they have different safe areas

I don't understand. If we set it to, say:

```
button.bottom = safearea.top + 10
```

Can you describe how it might be incompatible for current and future devices?

**Comment by eviltofu** [comment]
Yes but on iPad devices, this puts the button right on the bottom. On iPhone X devices, this puts this in the area above the bezels.

**Comment by hboon** [comment]
Maybe I misunderstood how constraints work with safe areas, but this is what I'm referring to. It doesn't matter whether it's iPad or iPhone. Safe areas take care of the presence of the virtual home bar:

<img width="518" alt="Screenshot 2022-03-31 at 12 44 48 PM" src="https://user-images.githubusercontent.com/56189/160978439-d694a7a6-ae5d-4fa4-80d8-20b52aad1e86.png">

If you are thinking of something different, can you describe or draw it?

**Comment by hboon** [comment]
Or, if it's easier, write a simple PR, make screenshots and it might be clearer.

**Comment by eviltofu** [comment]
```swift
//
//  ViewController.swift
//  BottomDisplay
//
//  Created by Jerome Chan on 31/3/22.
//

import UIKit

class ViewController: UIViewController {

    var button: UIButton = UIButton(type: .roundedRect)

    override func viewDidLoad() {
        super.viewDidLoad()
        layoutInternalViews()
    }

    func layoutInternalViews() {
        button.translatesAutoresizingMaskIntoConstraints = false
        button.setTitle("Ok", for: .normal)
        button.backgroundColor = .blue
        button.setTitleColor(.yellow, for: .normal)

        view.addSubview(button)
        let leadingC = button.leadingAnchor.constraint(equalToSystemSpacingAfter: view.leadingAnchor, multiplier: 1.0)
        let trailingC = view.trailingAnchor.constraint(equalToSystemSpacingAfter: button.trailingAnchor, multiplier: 1.0)
        let bottomC = button.bottomAnchor.constraint(equalTo: view.safeAreaLayoutGuide.bottomAnchor, constant: -8)
        NSLayoutConstraint.activate([
            leadingC,
            trailingC,
            bottomC,
        ])
    }

    override func viewDidLayoutSubviews() {
        super.viewDidLayoutSubviews()
        let margin = view.frame.maxY - button.frame.maxY
        print("Margin is \(margin)")
    }

}
```
![Simulator Screen Shot - iPad (9th generation) - 2022-03-31 at 13 11 30 copy 2](https://user-images.githubusercontent.com/1050309/160981310-c70c665f-a142-4410-9a3d-eb59b941a05d.png) ![Simulator Screen Shot - iPhone 13 Pro Max - 2022-03-31 at 13 10 54 copy 2](https://user-images.githubusercontent.com/1050309/160981314-45e25883-5386-4d8b-b391-7da661732622.png)

The margin printed out for the iPad is 8 while the one for the iPhone 13 Pro Max is 42. Because of the curved bottom area is not considered part of the safe area layout guide.

**Comment by hboon** [comment]
Ah, I see. It's fine. Yes, that's intentional. Keep it this way. 8 is probably too big, make it 2 in the PR and we'll see how it goes.

**Comment by eviltofu** [comment]
I actually have AutoLayout code that will place it at 0 from bottom of SafeLayoutGuide if it's curved and at least` x` from bottom of view if it's not. I'll try it at 2 then (if I can understand the current AutoLayout).
