### ISSUE TITLE
Add .xcode-version file

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#4093]
https://github.com/fastlane/ci/blob/master/docs/xcode-version.md and point it to 13.2.1?

We can change it after this, but with another PR and so everyone (just the 3 of us for now) a chance to know they have to and what is involved.

**Comment by eviltofu** [comment]
@hboon should we put `packaged.resolved` into `.gitignore`? This file can be recreated by Xcode if missing right?

**Comment by hboon** [comment]
I don't know. https://github.com/github/gitignore/blob/main/Swift.gitignore#L42 suggest so. Can you help figure it out?

**Comment by eviltofu** [comment]
> I don't know. https://github.com/github/gitignore/blob/main/Swift.gitignore#L42 suggest so. Can you help figure it out?

In this PR? @hboon

**Comment by hboon** [comment]
Separate.
