### ISSUE TITLE
App crashes after sending token

### ISSUE THREAD

**Issue by Saif-Fazlani** [AlphaWallet/alpha-wallet-ios#4100]
Once a transaction is confirmed and the "Transaction is in progress" screen is shown, the app crashes with the error "Realm accessed from the incorrect thread." Attaching stack trace below.

Moreover, the transaction succeeds and the token is received at the receiver's address.
<img width="1440" alt="Screenshot 2022-03-17 at 10 09 08 PM" src="https://user-images.githubusercontent.com/96777132/158856197-45ca4e15-6757-46fa-8791-e74c5392213e.png">
.

**Comment by hboon** [comment]
@Saif-Fazlani thanks for reporting. Could you elaborate which commit this happened with and did it happen repeatedly or did it seem like a one-off?

**Comment by Saif-Fazlani** [comment]
I forked AlphaWallet on 5th January 2022 and working on that currently.
Moreover, It happens every time.

**Comment by oa-s** [comment]
subscribableTokenBalance callback get called on background queue, you can check the place where  you call subscribe for subscribableTokenBalance, and and make it on main queue

**Comment by Saif-Fazlani** [comment]
I was also getting "UIViewController.view must be used from main thread only" on configure method of TokenViewController, so I thought it be better to force the call of this method to be run on main thread and that seems to do the trick.

<img width="1440" alt="Screenshot 2022-03-18 at 5 09 45 PM" src="https://user-images.githubusercontent.com/96777132/159000581-13688388-e262-4a8c-91f1-565a31d8e236.png">

**Comment by hboon** [comment]
@oa-s is this related to a customization/fork, or does it crash with our repo?

**Comment by oa-s** [comment]
Seems like with out repo. Have some changes, that should resolve it.

**Comment by hboon** [comment]
@oa-s ok. Help close it when you do then. Thanks

**Comment by oa-s** [comment]
Closed with #4100
