### ISSUE TITLE
New

### ISSUE THREAD

**Issue by Sleekbobby1011** [AlphaWallet/alpha-wallet-ios#4117]
name: Bug Report
about: Using AlphaWallet, but it's not working as you expect?

---

**Describe the bug**

**Steps to reproduce (REQUIRED)**
Steps to reproduce the behavior

1. Tap Wallet tab
2. Tap ...
3. Tap ...
4. Wait ...
5. Tap ...

**Expect**
6a. ...

**Observed**
6b. ...

**Screenshots**
If applicable, screenshots (preferred to video) to help explain your problem, a wallet address or transaction hash if applicable/possible

**Version or build number number**
Version number (if app store), build number (if TestFlight)

**Additional context (Error Messages, etc.)**

**Comment by oa-s** [comment]
@[Sleekbobby1011](https://github.com/Sleekbobby1011) Could this issue be updated with more informative way, or close it.
