### ISSUE TITLE
New iOS Release Fails to Read the True ETH Balance and Can't Send

### ISSUE THREAD

**Issue by Hoanib** [AlphaWallet/alpha-wallet-ios#4118]
The new update for iOS fails to read the ETH balance on the info page and also it doesn't allow send the token. Observe that the main page shows the balance in ETH but not the value in USD. I attach screenshots.

![image](https://user-images.githubusercontent.com/100842739/159209968-fe938028-6dc7-4153-aecf-aa09b88a68ac.png)

![image](https://user-images.githubusercontent.com/100842739/159209985-a7dbfd41-209e-4557-b525-e1a81dc93c36.png)

**Comment by hboon** [comment]
>  also it doesn't allow send the token

@Hoanib can you elaborate on how to reproduce this?

**Comment by Hoanib** [comment]
A bug! Resolved when I changed the wallet (address) and changed to the main wallet again.

**Comment by Hoanib** [comment]
> >  also it doesn't allow send the token
> 
> 
> 
> @Hoanib can you elaborate on how to reproduce this?

When I updated my wallet and opened it quickly I saw that the ETH token didn't show the balance in USD on the right side. And when I click on the page info didn't show the balance like if someone stolen my assets. Then I analyzed that it would be a bug and change the wallet and the ETH came back but I just check and the issue persists.

**Comment by Hoanib** [comment]
Open the wallet app (try to check it  with an address with ETH balance) if it doesn't show the USD balance on the right side and the all balance on the info page change for another address and then change again to the main wallet, the balance will show but if you close the app and open it again it will not.

**Comment by Hoanib** [comment]
Yes the bug is presented when you open the app with a wallet address connected with ETH asset. If you change for another wallet and then change back to the main we are testing the balance will show but when you close the app and open it again the balance disappears.

**Comment by Hoanib** [comment]
The bug is presented when you open the app with a wallet address connected
with ETH asset. If you change for another wallet and then change back to
the main we are testing the balance will show but when you close the app
and open it again the balance disappears.
