### ISSUE TITLE
Freeze with grayed out screen after sending ETH on Ropsten successfully

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#4120]
This is right after the actionsheet is closed. The transaction was sent successfully (confirmed in Etherscan). Could be intermittent.

![IMG_0096](https://user-images.githubusercontent.com/56189/159213328-7cf3a141-9164-452f-9872-5da9e77acf69.PNG)

**Comment by oa-s** [comment]
@hboon is this reproducing all the time?

**Comment by hboon** [comment]
@oa-s no. So #4118 is more important, especially if you can't reproduce this.
