### ISSUE TITLE
Wallet Summery Value is skewed because on MNEP token

### ISSUE THREAD

**Issue by colourfreak** [AlphaWallet/alpha-wallet-ios#4121]

**Comment by colourfreak** [comment]
![image](https://user-images.githubusercontent.com/51817359/159214198-d0b4e87d-e22e-4a5d-857b-bb7f21c34683.png)

**Comment by colourfreak** [comment]
![image](https://user-images.githubusercontent.com/51817359/159214214-2826b678-4d37-4534-804b-ba99ea947dfd.png)

**Comment by hboon** [comment]
Solved by #4020

**Comment by hboon** [comment]
@colourfreak can you help verify if it's on CoinGecko and report it to them? If it's spam, they shouldn't specify a non-zero price.
