### ISSUE TITLE
Design for showing rarity for properties for NFTs from OpenSea API

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#4136]
Moved from: #4125

Just realised we don't have the UI design to display rarity for properties. @colourfreak, can you help to come up with something?

<img width="200" alt="Screenshot 2022-03-22 at 3 51 02 PM" 

> src="https://user-images.githubusercontent.com/56189/159433072-ac44d818-a8b0-42bf-9594-093d0e7bc947.png">

This is how it looks like on OpenSea:

<img width="200" alt="Screenshot 2022-03-22 at 3 48 01 PM" src="https://user-images.githubusercontent.com/56189/159432621-60dfae7d-53f2-46c5-9e17-5926ea153104.png">

- [ ] Buzz Android when UI design is ready https://github.com/AlphaWallet/alpha-wallet-android/issues/2440

**Comment by colourfreak** [comment]
We do have them already. It has a different layout. Which one do you prefer?
https://zpl.io/aXRA3QP

<img width="1218" alt="Screenshot 2022-03-24 at 09 20 33" src="https://user-images.githubusercontent.com/51817359/159872917-49a8be08-ed7f-47af-8e8e-95f0f3e9166f.png">

**Comment by colourfreak** [comment]
Alternative
<img width="878" alt="Screenshot 2022-03-24 at 09 40 20" src="https://user-images.githubusercontent.com/51817359/159876400-a1303550-2bf1-4252-bf88-57ce09930c1c.png">

**Comment by hboon** [comment]
> We do have them already. It has a different layout. Which one do you prefer? https://zpl.io/aXRA3QP
> 
> <img alt="Screenshot 2022-03-24 at 09 20 33" width="1218" src="https://user-images.githubusercontent.com/51817359/159872917-49a8be08-ed7f-47af-8e8e-95f0f3e9166f.png">

Oh, sorry, I forgot. I think this version is already implemented earlier. Let's stick to this version then.
