### ISSUE TITLE
Support EIP1559 

### ISSUE THREAD

**Issue by JamesSmartCell** [AlphaWallet/alpha-wallet-ios#4138]
1. I used the Estimate fee calculation from this code: https://github.com/zsfelfoldi/feehistory, also ported to Kotlin here: https://github.com/komputing/KEthereum/blob/master/eip1559_feeOracle/src/main/kotlin/org/kethereum/eip1559_fee_oracle/EIP1559FeeOracle.kt
#### Note that we may want to override this calculation with an oracle later, such as the BlockNative Gas Oracle where available. I have compared the results of the calculation with the values appearing in Etherscan of the newly written blocks - it matches quite well. ####

2. This calculation uses the ```eth_feeHistory``` node call results and returns an array of 16 values from the [0]: Rapid to [15]: Slow
```
eth_feeHistory (eg:{"jsonrpc":"2.0","method":"eth_feeHistory","params":["0x64", "latest",[25, 75]],"id":1})  returns:
public class FeeHistory
{
    public String[] baseFeePerGas;
    public double[] gasUsedRatio;
    public String oldestBlock;
    public String[][] reward;
}
```
The elements of the array returned from the calculation looks like this:
```
public class EIP1559FeeOracleResult
{
    public final BigInteger maxFeePerGas;
    public final BigInteger maxPriorityFeePerGas;
}
```
(On the Android implementation I also recorded the baseFee in case this is needed for the UI).

3. Not all chains support EIP1559! You will need to distinguish; this is as simple as the node not recognising the opcode ```eth_feeHistory``` and returning an error. If this happens (eg Artis chain) you will need to fall back to Legacy style. On Android, the compromise I used was not to allow changing the gas speed for those chains. This will be expanded back to allow selection as this means you can't cancel or speedup transactions on those chains.
4. If you have implemented a wallet sweep action; this is only possible using Legacy transaction style since the exact amount of gas used is not known with 1559 until the transaction is written.

The design choices I used for Android:
- Maintain the legacy system for chains that don't support EIP1559 (including Artis, Optimism).
- Select the [0] element for Rapid, [15] for Slow, and calculate the intermediate two points for Standard and Fast.
- Use the same UI as we currently use to display Rapid -> Slow selection, but add 'Max Fee' and 'Priority Fee', similar to this: https://www.blocknative.com/gas-estimator
- Convert Gas Price slider to Max Fee slider.
- Add additional slider for Priority Fee. Minimum is 0, max is 4. (TODO: use eth_maxPriorityFeePerGas instead of 4, check this is what this call is for).
- Sometimes when testing lesser used chains like Gnosis chain the eth_feeHistory call returns a 'garbage' result where max gas would be returned at 0x7, ie 0.00000007 Gwei, which is clearly not correct. To deal with this, use a minimum of 1 Gwei Max Fee and minimum 1 Gwei Priority Fee.
- Tested on Mainnet and Testnet chains results seem good. Interestingly Polygon doesn't have much variance between rapid and slow. This corresponds with the 1559 fees used on the chain by written transactions.

As you might imagine, this corresponds to a lot of additional infrastructure. Hopefully knowing all the information before starting it makes your implementation a little smoother.

**Comment by hboon** [comment]
Thanks @JamesSmartCell. I will check this out and play with it.

Do you have examples or docs of the transaction format for EIP1559?

> Use the same UI as we currently use to display Rapid -> Slow selection, but add 'Max Fee' and 'Priority Fee', similar to this: https://www.blocknative.com/gas-estimator

Can you help paste a screenshot for this?

> Not all chains support EIP1559! You will need to distinguish; this is as simple as the node not recognising the opcode eth_feeHistory and returning an error.

Do you think it'll be easier to just maintain a hardcoded list of chains that supports EIP1559 in the app?

> On Android, the compromise I used was not to allow changing the gas speed for those chains

Is this because Android drops the gas customization UI for pre-EIP1559?

**Comment by JamesSmartCell** [comment]
> Thanks @JamesSmartCell. I will check this out and play with it.
> 
> Do you have examples or docs of the transaction format for EIP1559?
> 

Yes sorry I'll include those. Very similar to normal transaction.

> > Use the same UI as we currently use to display Rapid -> Slow selection, but add 'Max Fee' and 'Priority Fee', similar to this: https://www.blocknative.com/gas-estimator
> 
> Can you help paste a screenshot for this?

Yes

> 
> > Not all chains support EIP1559! You will need to distinguish; this is as simple as the node not recognising the opcode eth_feeHistory and returning an error.
> 
> Do you think it'll be easier to just maintain a hardcoded list of chains that supports EIP1559 in the app?
> 

You can, but if you check then you don't have to release a new build if/when they change.

> > On Android, the compromise I used was not to allow changing the gas speed for those chains
> 
> Is this because Android drops the gas customization UI for pre-EIP1559?

Yes, currently. I will push another re-factor/abstraction of the selection activity to make it selection agnostic. Currently it now only handles 1559 gas value types.

**Comment by JamesSmartCell** [comment]
Update: I did the abstraction so user can switch 1559 transactions on/off without affecting anything. 

Here's how I modified the Gas selection screen:

![Screenshot_20220330-164818_AlphaWallet](https://user-images.githubusercontent.com/12689544/160760227-3220c593-9062-4891-a2cb-33b56c07a633.jpg)

Not exactly a full implementation!

I would prefer something like this:

![image](https://user-images.githubusercontent.com/12689544/160760384-f31b118a-831f-47cf-820b-54d993086fef.png)

This is BlockNative's UI

**Comment by JamesSmartCell** [comment]
Here's the Transaction format as presented by Web3j:

```
    public static RawTransaction createTransaction(
            long chainId,
            BigInteger nonce,
            BigInteger gasLimit,
            String to,
            BigInteger value,
            String data,
            BigInteger maxPriorityFeePerGas,
            BigInteger maxFeePerGas) {

        return new RawTransaction(
                Transaction1559.createTransaction(
                        chainId,
                        nonce,
                        gasLimit,
                        to,
                        value,
                        data,
                        maxPriorityFeePerGas,
                        maxFeePerGas));
    }
```

Which differs from the Legacy format:

```
    public static RawTransaction createTransaction(
            BigInteger nonce,
            BigInteger gasPrice,
            BigInteger gasLimit,
            String to,
            BigInteger value,
            String data) {

        return new RawTransaction(
                LegacyTransaction.createTransaction(nonce, gasPrice, gasLimit, to, value, data));
    }
```

Note that the 1559 transaction has the chainId as a param, whereas the Legacy transaction requires the chainId to be encoded in the signature (optionally).

**Comment by hboon** [comment]
@oa-s give it a go :)
