### ISSUE TITLE
0 ETH balance sent

### ISSUE THREAD

**Issue by Hoanib** [AlphaWallet/alpha-wallet-ios#4154]
In IOS AW App the ETH transactions they are not being done correctly. When you do a transaction, no balance is sent and only consumes the gas fees.

**Comment by Hoanib** [comment]
User experience:

https://etherscan.io/tx/0x333342d4c6f5d2c7618a234f7dcc0f597429b21962c8e2310b6bf0362352a411

**Comment by hboon** [comment]
@oa-s help check?

**Comment by oa-s** [comment]
Tried to send ether in ropsten, tx is sending with enter amount, @Hoanib is there some specific configuration tx steps i missed missed when send eth?

**Comment by Hoanib** [comment]
A user complained about his AW (iOS) did not show the ETH balance in
dollars and that did not allow him to send it. I suggest him to do this
trick: change the current connected wallet address for another one and
change it back again in order to see the balance and then spend the token.
When the user did that he performed three transactions but no balance was
sent just the gas fees consuming. These are the Txn Hash:


0x333342d4c6f5d2c7618a234f7dcc0f597429b21962c8e2310b6bf0362352a411


0x46961a7ce3a373011509eb40a114d78ffd27f44870bedb3143c6bca8dfb2ea4b


0x6282deba121af38f15cf2dc296cbb46fbe443d84a72afcd6d246179fa6cc2c82

**Comment by oa-s** [comment]
can u share build version was using?

**Comment by Hoanib** [comment]
> can u share build version was using?

iOS 3.37 (421)

**Comment by Hoanib** [comment]
@oa-s User used this platform to make the transactions: https://60cek.org/

**Comment by Hoanib** [comment]
User reports that when he try to perform the send transaction in the Confirm pop up there's 0 balance. I just replicated it and it worked fine on my side. I attach screenshots.

User's: 
![image](https://user-images.githubusercontent.com/100842739/160230972-f8381874-d236-4a38-860c-7db3df5a7891.jpeg)

Mine:
![image](https://user-images.githubusercontent.com/100842739/160231020-41c0a62e-b010-45d1-a085-dfee799f623d.png)

**Comment by Hoanib** [comment]
I got reports from another users with the same issue confirming successful transactions after doin the trick I suggested them in order to AW displayed the ETH balance on the Send feature.

**Comment by oa-s** [comment]
@Hoanib Thanks for your report, it makes the issue clearly, we will check it asap.

**Comment by Hoanib** [comment]
@oa-s, @hboon, User reported that finally he could perform the transaction successfully!

**Comment by oa-s** [comment]
Close due to non activity, reopen if needed
