### ISSUE TITLE
After switching from mainnets to testnets OpenSea continues to fetch from mainnets

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#4165]
And vice versa.

1. Launch app with mainnets enabled
2. OpenSea API calls are made against Ethereum mainnet
3. Switch to testnet and enable Rinkeby

Observed
---
4. OpenSea API calls are made against Ethereum mainnet

Expected
---
4. OpenSea API calls are made against Ethereum Rinkeby

**Comment by oa-s** [comment]
it might happen as promise doesn't support canceling, and if case if request has trottled, or failure, it starts to retry to make a request, even when we have already switched to testnet/mainnet

**Comment by hboon** [comment]
Ah ok. Not a big deal then. But are new ones made against the new chain, correctly? If it’s working, then we can close this
