### ISSUE TITLE
Add documentation to describe how chains.zip is created and what it is used for.

### ISSUE THREAD

**Issue by eviltofu** [AlphaWallet/alpha-wallet-ios#4168]
`chains.zip` contains data relating to network RPC. It can be obtained from [here](https://chainid.network/chains.json) or [here](https://chainid.network/chains_mini.json).

The following code is used to compress the file:
```swift
@available(iOS 13.0, *)
fileprivate func compressChainFile(inputFileName: String, outputFileName: String) throws {
    let inputFileHandle = FileHandle(forReadingAtPath: inputFileName)!
    let inputData = inputFileHandle.readDataToEndOfFile() as NSData
    let outputData = try inputData.compressed(using: selectedCompressionAlgorithm) as Data
    FileManager.default.createFile(atPath: outputFileName, contents: outputData, attributes: nil)
    try inputFileHandle.close()
}
```

Documentation need to be added to the project in `doc/data-sources-chains.md` to describe the process used to obtain, update, and compress the file.

**Comment by eviltofu** [comment]
@hboon I'm revisiting my code and I find that the iOS `NSData.decompress(using:)` function call does not understand the `.zip` file format. My code `func compressChainFile` above simply dumps the compressed data into a file raw without any formatting and is not a `.zip` file. There are packages which do understand the the `.zip` file format and are able to extract and decompress the data. So we have a few options:

1. Make a command line tool that dumps the compressed data raw into a file and use that for preparing the chains.json.zip file.
2. Use a package/pod that allows the iOS app to decompress a zip file. So we can use the macOS provided tools to create a proper zip file.
3. Use the chains.json data without compressing.

**Comment by hboon** [comment]
How about this order:

> 3. Use the chains.json data without compressing.

See if the app size is affected (much). Try with the original, bigger tokens.json too, just for curiosity. But I imagine we'll not get to that size any time soon.

> 1. Make a command line tool that dumps the compressed data raw into a file and use that for preparing the chains.json.zip file.

A simple `.swift` script/file might work?

Failing that, write an uncalled function in the iOS code to produce the compress file.

> 2. Use a package/pod that allows the iOS app to decompress a zip file. So we can use the macOS provided tools to create a proper zip file.

Let's try to avoid it if possible.

**Comment by eviltofu** [comment]
> How about this order:
> 
> > 3. Use the chains.json data without compressing.
> 
> See if the app size is affected (much). Try with the original, bigger tokens.json too, just for curiosity. But I imagine we'll not get to that size any time soon.
> 
> > 1. Make a command line tool that dumps the compressed data raw into a file and use that for preparing the chains.json.zip file.
> 
> A simple `.swift` script/file might work?
> 
> Failing that, write an uncalled function in the iOS code to produce the compress file.
> 
> > 2. Use a package/pod that allows the iOS app to decompress a zip file. So we can use the macOS provided tools to create a proper zip file.
> 
> Let's try to avoid it if possible.

[Swift script](https://www.raywenderlich.com/25816315-using-swift-scripts-with-xcode) like this one? The script could download and compress the file.

**Comment by hboon** [comment]
Simpler, this https://rderik.com/blog/using-swift-for-scripting/ if possible. Look for:

```
#!/usr/bin/env swift
print("hello, world!")
```

**Comment by eviltofu** [comment]
I'll add this to the Makefile.
