### ISSUE TITLE
Computed fiat value not appearing for native token (Ethereum mainnet) despite rate and balance being available

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#4169]
Not sure if it's still reproducible on `master`

![IMG_0191](https://user-images.githubusercontent.com/56189/160337831-2e625e21-bb03-452f-9c61-7e1b9d87cce6.PNG)

**Comment by oa-s** [comment]
i will double check it, but for now i am not facing such issue

**Comment by oa-s** [comment]
Non reproducible

**Comment by hboon** [comment]
@oa-s probably fixed with a recent change.
