### ISSUE TITLE
Support IoTeX chain

### ISSUE THREAD

**Issue by JamesSmartCell** [AlphaWallet/alpha-wallet-ios#4192]
While at Eth Denver we met with IoTeX network team. They are doing some interesting work with IoT and blockchain. It appears TokenScript may be a useful asset for IoTeX developers.

After Klaytn network is integrated Covalent support will be in the app, which means it will be simple to add support for IoTeX:

### IoTeX Mainnet

ChainID: ```4689```
RPC: ```https://babel-api.mainnet.iotex.io```
BackupRPC: ```https://rpc.ankr.com/iotex```
BlockTXExplorer (EtherscanUrl): ```https://iotexscan.io/tx/```
EtherscanAPI: ```https://api.covalenthq.com/v1/4689/address/<ACCOUNT ADDRESS>/transactions_v2/```
Network Style Colour: ```#00D4D5```
Coingecko chainpair ID: ```iotex```
Coingecko chainIdAPI name: ```iotex```

SVG:  ![iotex-iotx-logo](https://user-images.githubusercontent.com/12689544/160728912-9aa2d781-7dc4-4afa-9b30-c65c36ddcdf2.svg)

### IoTeX Testnet

ChainID: ```4690```
RPC: ```https://babel-api.testnet.iotex.io```
BackupRPC: 
BlockTXExplorer (EtherscanUrl): ```https://testnet.iotexscan.io/tx```
EtherscanAPI: ```https://api.covalenthq.com/v1/4690/address/<ACCOUNT ADDRESS>/transactions_v2/```
Network Style Colour: ```#00D4D5```

SVG: ![iotex-test](https://user-images.githubusercontent.com/12689544/160728921-dac8501c-8279-42fc-8952-894a2bdad49d.svg)

**Comment by hboon** [comment]
@colourfreak would you help with a PDF version of the token icon?

**Comment by JamesSmartCell** [comment]
> @colourfreak would you help with a PDF version of the token icon?

PDF?

**Comment by hboon** [comment]
Yes, iOS has built-in support for scalable graphic assets in PDF form, not in SVG.

**Comment by colourfreak** [comment]
[IoTeX.pdf](https://github.com/AlphaWallet/alpha-wallet-ios/files/8379073/IoTeX.pdf)
[IoTeXTestnet.pdf](https://github.com/AlphaWallet/alpha-wallet-ios/files/8379074/IoTeXTestnet.pdf)

**Comment by colourfreak** [comment]
https://zpl.io/W4rB471
https://zpl.io/g8o9850
