### ISSUE TITLE
Handle NFT contract which provides metadata directly

### ISSUE THREAD

**Issue by JamesSmartCell** [AlphaWallet/alpha-wallet-ios#4197]
We are used to handling NFTs like this:

tokenURI(uint256 tokenId) -> "https://some_metadata_here/tokenId"

Then we go and fetch the metadata at that URL.

Some contracts provide the metadata directly:

tokenURI(uint256 tokenId) -> "{"name": "MachineFi NFT", "description": "The MachineFi NFT.", "image": "https://machinefi.com/nft/image/3253"}"

Check that the app handles this correctly.

Example is on IoTeX chain, but I can create a sample that checks this on Rinkeby.

**Comment by JamesSmartCell** [comment]
@hboon I sent you two 'MachineFi' Tokens on Rinkeby which illustrate this issue. Opensea should pick them up.

The two tokens also highlight an issue which is a hold-over from the ERC875 days, that is a tokenId of zero would be treated as 'spent' or burned. I have seen a few people with NFTs with tokenId zero (yes), which weren't showing up in AW Android.

The two tokenIds are 0 and 1, contract is 0x0f723571D66670f4304d21407caA068A70028F1D

Metadata returned for tokenID 0 (direct from contract):

```{"name": "MachineFi NFT", "description": "The MachineFi NFT.", "image": "https://machinefi.com/nft/image/0"}```

I notice that OpenSea doesn't handle this style of Metadata either.

**Comment by hboon** [comment]
@JamesSmartCell I'm been meaning to check and support this, but check out https://etherscan.io/address/0xff9c1b15b16263c61d017ee9f65c50e4ae0113d7#readContract 's token `tokenURI` if it does something similar. It returns:

```
uri: data:application/json;base64,eyJuYW1lIjogIkJhZyAjODE2IiwgImRlc2NyaXB0aW9uIjogIkxvb3QgaXMgcmFuZG9taXplZCBhZHZlbnR1cmVyIGdlYXIgZ2VuZXJhdGVkIGFuZCBzdG9yZWQgb24gY2hhaW4uIFN0YXRzLCBpbWFnZXMsIGFuZCBvdGhlciBmdW5jdGlvbmFsaXR5IGFyZSBpbnRlbnRpb25hbGx5IG9taXR0ZWQgZm9yIG90aGVycyB0byBpbnRlcnByZXQuIEZlZWwgZnJlZSB0byB1c2UgTG9vdCBpbiBhbnkgd2F5IHlvdSB3YW50LiIsICJpbWFnZSI6ICJkYXRhOmltYWdlL3N2Zyt4bWw7YmFzZTY0LFBITjJaeUI0Yld4dWN6MGlhSFIwY0RvdkwzZDNkeTUzTXk1dmNtY3ZNakF3TUM5emRtY2lJSEJ5WlhObGNuWmxRWE53WldOMFVtRjBhVzg5SW5oTmFXNVpUV2x1SUcxbFpYUWlJSFpwWlhkQ2IzZzlJakFnTUNBek5UQWdNelV3SWo0OGMzUjViR1UrTG1KaGMyVWdleUJtYVd4c09pQjNhR2wwWlRzZ1ptOXVkQzFtWVcxcGJIazZJSE5sY21sbU95Qm1iMjUwTFhOcGVtVTZJREUwY0hnN0lIMDhMM04wZVd4bFBqeHlaV04wSUhkcFpIUm9QU0l4TURBbElpQm9aV2xuYUhROUlqRXdNQ1VpSUdacGJHdzlJbUpzWVdOcklpQXZQangwWlhoMElIZzlJakV3SWlCNVBTSXlNQ0lnWTJ4aGMzTTlJbUpoYzJVaVBsZGhibVE4TDNSbGVIUStQSFJsZUhRZ2VEMGlNVEFpSUhrOUlqUXdJaUJqYkdGemN6MGlZbUZ6WlNJK1RHbHVaVzRnVW05aVpUd3ZkR1Y0ZEQ0OGRHVjRkQ0I0UFNJeE1DSWdlVDBpTmpBaUlHTnNZWE56UFNKaVlYTmxJajVEWVhBOEwzUmxlSFErUEhSbGVIUWdlRDBpTVRBaUlIazlJamd3SWlCamJHRnpjejBpWW1GelpTSStJa1p2WlNCVGFHOTFkQ0lnVTJsc2F5QlRZWE5vSUc5bUlGWnBkSEpwYjJ3Z0t6RThMM1JsZUhRK1BIUmxlSFFnZUQwaU1UQWlJSGs5SWpFd01DSWdZMnhoYzNNOUltSmhjMlVpUGlKVVpXMXdaWE4wSUUxdmIyNGlJRk5wYkdzZ1UyeHBjSEJsY25NZ2IyWWdkR2hsSUZSM2FXNXpJQ3N4UEM5MFpYaDBQangwWlhoMElIZzlJakV3SWlCNVBTSXhNakFpSUdOc1lYTnpQU0ppWVhObElqNUVaVzF2YmlkeklFaGhibVJ6UEM5MFpYaDBQangwWlhoMElIZzlJakV3SWlCNVBTSXhOREFpSUdOc1lYTnpQU0ppWVhObElqNUJiWFZzWlhROEwzUmxlSFErUEhSbGVIUWdlRDBpTVRBaUlIazlJakUyTUNJZ1kyeGhjM005SW1KaGMyVWlQa2R2YkdRZ1VtbHVaend2ZEdWNGRENDhMM04yWno0PSJ9
```

**Comment by JamesSmartCell** [comment]
Yes it's the same:

```
{"name": "Bag #1", "description": "Loot is randomized adventurer gear generated and stored on chain. Stats, images, and other functionality are intentionally omitted for others to interpret. Feel free to use Loot in any way you want.", "image": "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHByZXNlcnZlQXNwZWN0UmF0aW89InhNaW5ZTWluIG1lZXQiIHZpZXdCb3g9IjAgMCAzNTAgMzUwIj48c3R5bGU+LmJhc2UgeyBmaWxsOiB3aGl0ZTsgZm9udC1mYW1pbHk6IHNlcmlmOyBmb250LXNpemU6IDE0cHg7IH08L3N0eWxlPjxyZWN0IHdpZHRoPSIxMDAlIiBoZWlnaHQ9IjEwMCUiIGZpbGw9ImJsYWNrIiAvPjx0ZXh0IHg9IjEwIiB5PSIyMCIgY2xhc3M9ImJhc2UiPiJHcmltIFNob3V0IiBHcmF2ZSBXYW5kIG9mIFNraWxsICsxPC90ZXh0Pjx0ZXh0IHg9IjEwIiB5PSI0MCIgY2xhc3M9ImJhc2UiPkhhcmQgTGVhdGhlciBBcm1vcjwvdGV4dD48dGV4dCB4PSIxMCIgeT0iNjAiIGNsYXNzPSJiYXNlIj5EaXZpbmUgSG9vZDwvdGV4dD48dGV4dCB4PSIxMCIgeT0iODAiIGNsYXNzPSJiYXNlIj5IYXJkIExlYXRoZXIgQmVsdDwvdGV4dD48dGV4dCB4PSIxMCIgeT0iMTAwIiBjbGFzcz0iYmFzZSI+IkRlYXRoIFJvb3QiIE9ybmF0ZSBHcmVhdmVzIG9mIFNraWxsPC90ZXh0Pjx0ZXh0IHg9IjEwIiB5PSIxMjAiIGNsYXNzPSJiYXNlIj5TdHVkZGVkIExlYXRoZXIgR2xvdmVzPC90ZXh0Pjx0ZXh0IHg9IjEwIiB5PSIxNDAiIGNsYXNzPSJiYXNlIj5OZWNrbGFjZSBvZiBFbmxpZ2h0ZW5tZW50PC90ZXh0Pjx0ZXh0IHg9IjEwIiB5PSIxNjAiIGNsYXNzPSJiYXNlIj5Hb2xkIFJpbmc8L3RleHQ+PC9zdmc+"}
```

**Comment by hboon** [comment]
I think (2). The Loot contract, execution and things around it is ripe full of interesting things :)

**Comment by JamesSmartCell** [comment]
Ok, it should be straightforward to add support for those. Have you seen them anywhere else other than Loot? Does OpenSea support it?

**Comment by hboon** [comment]
I don't know if it's common but OpenSea displays those metadata. No idea if it's ad-hoc or built-in though. I think we can support it if there's no cost to it as `data:` are valid URIs. Also wary that the image itself might be base64…

Appears some tutorials demonstrate the technique https://www.reddit.com/r/opensea/comments/p7ajwx/tokenuri_with_base64_just_like_uniswapv3/

Example:

https://opensea.io/assets/matic/0x291ff90b9c410f56e047599bfee6b585c0c484d7/2

**Comment by hboon** [comment]
@oa-s Might already be doing this?

**Comment by oa-s** [comment]
already done for ios
