### ISSUE TITLE
TokenViewController sometimes show 0 balance for native token even when Wallet tab has refreshed to show non-zero

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#4200]
While testing #4198, I noticed this:

I noticed this:

1. Make sure only Klaytn testnet is enabled
2. Import a new wallet
3. Balance in wallet tab is 0
4. Wait
5. Balance in wallet tab is non-zero
6. Tap native token

Expected
---
7. Balance in TokenViewController is non-zero

Observed
---
7. Balance in TokenViewController is still 0

Going back to the wallet tab, the balance is still (correctly) non-zero, tapping into TokenViewController, it still shows 0. After I switch from Klaytn testnet -> mainnet, the non-zero balance for mainnet is shown correctly in both Wallet tab and TokenViewController. After I switch back to testnet, it now shows non-zero correctly for testnet and I can't reproduce the issue anymore.

Wallet|TokenViewController
-|-
<img width="487" alt="Screenshot 2022-03-31 at 10 40 33 AM" src="https://user-images.githubusercontent.com/56189/160967632-23911f8d-2442-4bfb-8574-108b7a04db32.png">|<img width="487" alt="Screenshot 2022-03-31 at 10 40 34 AM" src="https://user-images.githubusercontent.com/56189/160967620-db18174d-132f-4e87-945b-4cd84fad8b73.png">

**Comment by oa-s** [comment]
@hboon can u provide wallet address for watching?

**Comment by hboon** [comment]
@oa-s 0x424d0c6ed9addc9e80e81dbfe6e26911e4a25c8c
