### ISSUE TITLE
Klaytn Network Differences

### ISSUE THREAD

**Issue by JamesSmartCell** [AlphaWallet/alpha-wallet-ios#4203]
Two further refinements for supporting Klaytn network:

- Block gas limit is much higher than standard Ethereum node:
```
    public static final long GAS_LIMIT_MAX =          4712380L;  //Max block gas for most chains
    public static final long GAS_LIMIT_MAX_KLAYTN = 100000000L;  //Klaytn gas limit, see https://docs.klaytn.com/klaytn/design/computation/computation-cost
```
- Klaytn requires all transaction signatures to be EIP155 format (which you should be doing anyway).

**Comment by hboon** [comment]
@oa-s buzz reassign to me if you like

**Comment by hboon** [comment]
> GAS_LIMIT_MAX_KLAYTN = 100000000L;  

@JamesSmartCell as if we still estimate with `eth_estimateGas`, but expect that the value will be much higher?

**Comment by JamesSmartCell** [comment]
> > GAS_LIMIT_MAX_KLAYTN = 100000000L;
> 
> @JamesSmartCell as if we still estimate with `eth_estimateGas`, but expect that the value will be much higher?

Yes, everything else same.

**Comment by JamesSmartCell** [comment]
You can test both these issues here:

https://jamessmartcell.github.io/

Connect, then click on the 'Switch to Klaytn' button then try to deploy the Meks or Punks contract. If the gas limit is not set to the upper limit then the estimate gas will fail. Once you can deploy the contract you know it's working correctly.
