### ISSUE TITLE
Error Displaying Token Activity Page

### ISSUE THREAD

**Issue by Hoanib** [AlphaWallet/alpha-wallet-ios#4230]
A minor bug showing the token activity page incomplete as if it had been cut. Note that this doesn't occur when you access directly through Activity feature in the main page, just when you access through the token page.
 

![image](https://user-images.githubusercontent.com/100842739/161597870-5e15ff95-e198-435a-ac85-d0bdb7a1497b.png)

**Comment by oa-s** [comment]
issue fixed
