### ISSUE TITLE
App crashes because I have to many fake tokens

### ISSUE THREAD

**Issue by juancrescente** [AlphaWallet/alpha-wallet-ios#4279]
Im ios latest version, I got a lot of fake tokens in my wallet. Now I cannot add it to alpha wallet cause it crashes a few seconds after initialize. I have to uninstall it and install again in order to get my wallet removed

**Comment by hboon** [comment]
@juancrescente as in those are spam tokens? Or do you mean those token contracts/addresses are invalid?

**Comment by oa-s** [comment]
@hboon can you check reports?

**Comment by juancrescente** [comment]
> @juancrescente as in those are spam tokens? Or do you mean those token contracts/addresses are invalid?

Indeed they are spam tokens

**Comment by juancrescente** [comment]
Maybe an option to avoid auto adding all tokens? I want to add my own tokens only

**Comment by hboon** [comment]
> Maybe an option to avoid auto adding all tokens? I want to add my own tokens only

We might do that in the future. But a feature that is coming soon should help too — we'll being recognize spam tokens and avoid showing those. Closing this for now. Thank you for reporting this. Stay tuned!
