### ISSUE TITLE
Rename and move logic that is currently called coordinators that don't deal with UI flow

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#4282]
Long running task for all of us.

We have many types called coordinators. Coordinators should be restricted to those that control UI flow. We should rename and move (if necessary) the rest slowly as we go along.

I think the naming should be:

* coordinators — control UI flow. Usually a good sign is they import UIKit (other than for access to UIImage)
* service — some of the things that we used to call coordinators that are longer-running
* <name> — these are just logic and non-UI eg. What used to be GetENSOwnerCoordinator, ENSReverseLookupCoordinator.swift, GetENSTextRecordsCoordinator. They are used once and destroyed. They will soon be renamed to ENSResolver, ENSReverseResolver, GetENSTextRecord. Conventional wisdom says they should all be nouns, but I don't think it's easy to come up with a noun that is better than GetENSTextRecord — GetENSTextRecordManager is silly!

Related to: #3990

**Comment by eviltofu** [comment]
How different is this from #3990 ?

**Comment by hboon** [comment]
> How different is this from #3990 ?

#3990 is about extracting logic from real coordinators

This (#4282) is about renaming misnamed coordinators to something more appropriate eg. #4283

**Comment by eviltofu** [comment]
AnalyticsCoordinator does not inherit from Coordinator. This should be renamed AnalyticsService?

**Comment by eviltofu** [comment]
`UniversalLinkCoordinator` does not inherit from `Coordinator` but from `UniversalLinkCoordinatorType`.

**Comment by hboon** [comment]
@eviltofu similar to https://github.com/AlphaWallet/alpha-wallet-ios/issues/3990#issuecomment-1132479898, make a list of checkboxes here.

**Comment by hboon** [comment]
> `AnalyticsCoordinator` does not inherit from `Coordinator` but is a protocol. `AnalyticsCoordinator` should be renamed `Analytics` and concrete implementations should be named `AnalyticsService`.

Yes, but `Analytics` and `MixpanelAnalytics`.

**Comment by hboon** [comment]
> `UniversalLinkCoordinator` does not inherit from `Coordinator` but from `UniversalLinkCoordinatorType`.

Not coordinator, so maybe `UniversalLinkHandler`? But let's not call everything "handlers" (or managers!). Just seems appropriate for this one case.

**Comment by hboon** [comment]
Refer to #6606
