### ISSUE TITLE
Unable to run the project

### ISSUE THREAD

**Issue by Saif-Fazlani** [AlphaWallet/alpha-wallet-ios#4341]
Hi, I have downloaded the latest version of AlphaWallet and tried running it but it fails with the below-mentioned errors.
P.S I have ran pod install on it
<img width="1440" alt="Screenshot 2022-04-14 at 1 08 40 PM" src="https://user-images.githubusercontent.com/96777132/163342495-815d6ae3-6d33-447b-a0fd-3fb4ac6f456f.png">
.

**Comment by eviltofu** [comment]
Please make sure that you are using Xcode 13.3.1.

**Comment by hboon** [comment]
@Saif-Fazlani and in the future, you'll be able to discover the correct version from `.xcode-version`. See: #4309
