### ISSUE TITLE
Update screens which show list of chains to include icon and chain ID

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#4402]
Like in #3511

eg.

- [x] In dapp browser > … > Connect to:
- [x] Switch chain for active Wallet Connect session
- [x] Wallets > … > Add / Hide Tokens > + Auto

Not sure if there are more

**Comment by eviltofu** [comment]
The non icon table cell view is `ServerTableViewCell`. I'll just check for all instances where this is used and replace it with the newer version `ServerImageTableViewCell`.

**Comment by eviltofu** [comment]
![Simulator Screen Shot - iPhone 11 - 2022-05-07 at 08 54 58 copy 2](https://user-images.githubusercontent.com/1050309/167231532-7705528d-a004-4e9e-9afb-1a8f7956e0c9.png)

Does this count?

**Comment by eviltofu** [comment]
![Screen Shot 2022-05-07 at 9 12 59 AM copy 2](https://user-images.githubusercontent.com/1050309/167232124-b964c79f-afdd-476f-93b4-34122ef6bc73.png)

WalletConnectSessionsViewController

**Comment by eviltofu** [comment]
| Before | After |
| ----- | ----- |
| ![Screen Shot 2022-05-07 at 10 43 27 AM copy 2](https://user-images.githubusercontent.com/1050309/167234947-8b29a56f-e9f4-476d-8afb-f3e0de5a50f9.png) | |

There appears to be a special case for Wallets > … > Add / Hide Tokens > + Auto

**Comment by eviltofu** [comment]
![Screen Shot 2022-05-08 at 10 13 39 AM copy 2](https://user-images.githubusercontent.com/1050309/167278953-069abb53-1d58-41e3-9469-72330dc4c26f.png)

CustomRPC has no logo

**Comment by eviltofu** [comment]
@hboon feedback required

**Comment by hboon** [comment]
Seems OK. The `WIP Don't Merge` tag should be on the PR not issue though.

**Comment by eviltofu** [comment]
https://github.com/AlphaWallet/alpha-wallet-ios/issues/4402#issuecomment-1120335455 @hboon

**Comment by hboon** [comment]
> [#4402 (comment)](https://github.com/AlphaWallet/alpha-wallet-ios/issues/4402#issuecomment-1120335455) @hboon

Just leave it for this issue and create a separate one. So the PR should be good to merge. It might be related to a bug created recently — the icons for testtnet chains in these screens showing a list of chains shouldn't be just a solid colored circle. Should show the symbol inside the solid colored circle. Probably work the same for custom chains.

**Comment by hboon** [comment]
Created #4570
