### ISSUE TITLE
iOS App is not Showing NFT Image

### ISSUE THREAD

**Issue by Hoanib** [AlphaWallet/alpha-wallet-ios#4403]
New version of iOS app is not showing the images of the NFTS.
Also I received a ticket user's complaint that he is not able to send his NFT. He did not mention what AW app is using.

![image](https://user-images.githubusercontent.com/100842739/164752492-85d27267-d45c-4f60-895c-7c753c5eb5ad.jpeg)

![image](https://user-images.githubusercontent.com/100842739/164752529-59ad264d-d32c-4864-8ab6-88545157b211.png)

**Comment by Hoanib** [comment]
User came back saying he is using iOS.

**Comment by Hoanib** [comment]
User is using iOS app and the NFT is seated on Polygon.

**Comment by Hoanib** [comment]
I want to mention that every time I update the app since I got the NTF (mine is on Mainnet not Poly) the app fails to read the image and the image icon. I have solved this removing the app and downloading it again. Now I got many addresses and it can be something cumbersome for the time it takes to do it and it is not advisable to ask users to do that procedure.

**Comment by Hoanib** [comment]
Issue fixed with the new update version 3.39 (426)!

**Comment by hboon** [comment]
@Hoanib thanks for the update!
