### ISSUE TITLE
ENS avatar shown wrongly (refer to screenshot for device, not simulator)

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#4405]
Title was "ENS avatar shown differently on simulator and device (and both are wrong)".

This might be 2 separate issues:

simulator|device
-|-
<img width="200" alt="Screenshot 2022-04-25 at 11 34 41 AM" src="https://user-images.githubusercontent.com/56189/165016683-c62c13cb-afdf-4c02-8380-a526b1358325.png">|<img width='200' src='https://user-images.githubusercontent.com/56189/165016688-122da9e7-68a1-449d-91c9-46add29e1a14.jpg'>

The actual ENS avatar should look like this:

<img width="200" alt="Screenshot 2022-04-25 at 11 38 57 AM" src="https://user-images.githubusercontent.com/56189/165016937-b6b69544-b9f2-41d0-abee-75dd5bef79f9.png">

**Comment by hboon** [comment]
Ah, it showing the blockie on the simulator is likely because I was rate limited. So it would show the avatar from NFT (via OpenSea) like the device if it wasn't. Have updated the issue title.

So the (1) problem is: the NFT image isn't displayed correctly.

**Comment by oa-s** [comment]
> So the (1) problem is: the NFT image isn't displayed correctly.

yep, i catched case when svg image displays incorrectly, checked with https://user-images.githubusercontent.com/56189/165016937-b6b69544-b9f2-41d0-abee-75dd5bef79f9.png, (but with `svg` version) now it works as needed

**Comment by hboon** [comment]
> yep, i catched case when svg image displays incorrectly, checked with https://user-images.githubusercontent.com/56189/165016937-b6b69544-b9f2-41d0-abee-75dd5bef79f9.png, (but with `svg` version) now it works as needed

But if I try the actual SVG, https://openseauserdata.com/files/2ed62dcec7fb8ed6b45eff58c4c104a4.svg, it's still green. Does it work on your side?
