### ISSUE TITLE
WalletConnect message in Console

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#4431]
```
WC: incomming text deserialization to JSONRPC 2.0 requests error: The data couldn’t be read because it isn’t in the correct format.
```

Was connecting to WalletConnect v1, but not accept connection yet using http://example.walletconnect.org and I tapped cancelled. Not sure if it's because I tapped cancel.

**Comment by oa-s** [comment]
hmm, it fails with error `"Missing or invalid socket data"`

**Comment by hboon** [comment]
@oa-s fixed permissions.

**Comment by oa-s** [comment]
Created  pr [Remove ping pong as it happens automatically #1](https://github.com/AlphaWallet/WalletConnectSwift/pull/1)
