### ISSUE TITLE
GIFs token images used to animate in Wallet tab, they don't anymore

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#4447]
Seems like they used to animate?

Eg. Blitmap: 

https://etherscan.io/address/0x8d04a8c79ceb0889bdd12acdf3fa9d207ed3ff63#readContract

<img width="200" alt="Screenshot 2022-04-28 at 11 44 47 AM" src="https://user-images.githubusercontent.com/56189/165672239-bf73089c-503a-4d9d-ae95-abc91489fc78.png">

<img width="200" alt="Screenshot 2022-04-28 at 11 44 40 AM" src="https://user-images.githubusercontent.com/56189/165672233-1615b9b1-fee3-44b9-959b-8c1e7bc57e9f.png">

**Comment by oa-s** [comment]
https://user-images.githubusercontent.com/96283950/165773781-c91f5f3c-d784-44b9-9b63-904c22d4f1c5.MP4

**Comment by hboon** [comment]
@oa-s Strange! Is this without making any changes? It's not animating for me on both device and simulator.

**Comment by oa-s** [comment]
> @oa-s Strange! Is this without making any changes? It's not animating for me on both device and simulator.

yes, but let me double check

**Comment by oa-s** [comment]
on master without  any changes

https://user-images.githubusercontent.com/96283950/165893148-db5d6aa1-c35b-4a3e-bf1b-a00d72df3898.MP4

**Comment by hboon** [comment]
Just to be sure, can you try this on the simulator, iPhone 11 Pro iOS 15.4. Don't have to record a video.

**Comment by oa-s** [comment]
Real device, and simulators iPhone 11 Pro iOS 15.4, iPhone 11 Pro iOS 13.5


https://user-images.githubusercontent.com/96283950/166432734-127c3eff-be0c-4992-9802-5bda3ed3ac90.mov


https://user-images.githubusercontent.com/96283950/166432853-1b295891-f510-4464-8658-7d4623ab81fe.mov


https://user-images.githubusercontent.com/96283950/166432888-0baeb9a0-7556-4352-8472-990bc72db048.MP4

**Comment by hboon** [comment]
I have no idea why. But it works me now since 54e6ef9332e73474597dbfe54a65d4a09f873574 (maybe earlier, but I didn't check).
