### ISSUE TITLE
Send ETH transaction's actionsheet shown from dapp browser should show network etc like it does when we send from Wallet tab

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#4499]
Visit https://web3.hboon.repl.co (on testnet! This sends 0.0001 ETH to me).

<img width="443" alt="Screenshot 2022-05-04 at 2 52 56 PM" src="https://user-images.githubusercontent.com/56189/166634784-121fa6b5-38e9-43b6-a22f-1698ee83129b.png">

vs

<img width="487" alt="Screenshot 2022-05-04 at 2 54 20 PM" src="https://user-images.githubusercontent.com/56189/166634904-2e44224a-20df-4d30-979e-408a33b3fb79.png">

**Comment by oa-s** [comment]
i am facing this result when open the ur
![IMG_5885](https://user-images.githubusercontent.com/96283950/174996862-a9c2c147-1a8b-4fed-92d2-9f70f0dedaf2.PNG)
l

**Comment by hboon** [comment]
@oa-s sorry, have fixed the link. Would you try again?
