### ISSUE TITLE
Update the Welcome screen

### ISSUE THREAD

**Issue by colourfreak** [AlphaWallet/alpha-wallet-ios#4505]
**Problem:**
- we have an outdated logo
- users (tested with developers) have no idea what is "Watch"
- buttons are not aligned and in different width

![2022-05-04 12 53 31](https://user-images.githubusercontent.com/51817359/166670359-413a2155-460d-4168-b8ad-147dec61c225.png)

----
**Solution:**
- update the logo
- remove that top line (thin gray line)
- make two buttons at the bottom in the same width

a) Create a new Wallet
b) I already have a Wallet

![Welcome](https://user-images.githubusercontent.com/51817359/166669592-3529dbd5-7460-4cae-a922-b30658d0b2e4.jpg)

When you hit b) you will be prompt with options to choose between

* Import existing Wallet 
* Track Wallet Address

![Import-Wallet](https://user-images.githubusercontent.com/51817359/166669590-cfcdf085-ecbd-4879-b2aa-6a99ccc30656.png)

Zeplin:
https://zpl.io/p1m8vKM
https://zpl.io/noPny1Y
https://zpl.io/XYZe5oK

**Comment by hboon** [comment]
> Track Wallet Address

@colourfreak do you think "Follow Wallet Address" might be better? More common in social media, maybe more familiar to most users.

**Comment by hboon** [comment]
Anyway, 

For developer: let's do make the layout flow changes and keep the logo as it-is (we'll be updating the app logo app-wide).

**Comment by colourfreak** [comment]
> > Track Wallet Address
> 
> @colourfreak do you think "Follow Wallet Address" might be better? More common in social media, maybe more familiar to most users.

Also interesting, where have you stumbled upon this?

**Comment by colourfreak** [comment]
<img width="1370" alt="Screenshot 2022-05-10 at 09 35 42" src="https://user-images.githubusercontent.com/51817359/167576106-ab0b12f6-ec48-4188-822f-b7bbaebb6012.png">

**Comment by hboon** [comment]
You mean the use of Follow in "Follow Wallet Address"? Inspired when I saw "Track Wallet Address". Haven't noticed it anywhere else.
