### ISSUE TITLE
Make the hit avatar/blockie surface area bigger

### ISSUE THREAD

**Issue by colourfreak** [AlphaWallet/alpha-wallet-ios#4506]
**Problem:**
While conducting user tests in Amsterdam, I found that users have to hit the blockie/avatar in the top-left a few times to get to a new screen, where they manage wallets. We have to make the whole hit area larger. Do not limit the hit area to the icon 24x24, but make it a minimum of 44x44 or larger. This is the minimum area necessary for users to hit with ease. 

<img width="706" alt="Screenshot 2022-05-04 at 13 16 41" src="https://user-images.githubusercontent.com/51817359/166671342-a28d8f70-ebb8-4366-8767-10bc086abc9f.png">

**Comment by eviltofu** [comment]
@colourfreak Do I increase the image as well or just the to-hit area?

**Comment by eviltofu** [comment]
![Screen Shot 2022-05-08 at 10 49 56 AM copy 2](https://user-images.githubusercontent.com/1050309/167279658-a1b4ae6b-2de4-4594-87a8-d5b86bf0dbe6.png)

All three icons are 24x24 points. Do you want me to increase the others as well?

**Comment by hboon** [comment]
Yes. Thanks.

**Comment by eviltofu** [comment]
| Before | After |
| ----- | ----- |
| To be done | ![image](https://user-images.githubusercontent.com/1050309/167282412-ebbe9c2a-d297-4548-a6af-e7736b2f07c6.png) |

**Comment by eviltofu** [comment]
![image](https://user-images.githubusercontent.com/1050309/167282764-92c49a9d-2cb2-4258-af0b-3269f8dbce2f.png)

Camera icon is already close to 44x44.
