### ISSUE TITLE
Add "Select Network" screen after you create/import a new wallet

### ISSUE THREAD

**Issue by colourfreak** [AlphaWallet/alpha-wallet-ios#4507]
**Problem:**
During user tests in Amsterdam, I found that users don't really know how to enable their favorite networks. They don't even understand that we support multiple networks.

**Solution:**
Add one more screen where they can select multiple networks from the existing base (we make a long list of all 32 supported networks). If they would need a custom one, then they could do this later. 

**Why?**
- first, we let users know we support multiple chains
- the wallet is already customized, so they don't have to go to the Settings tab

Invision Prototype:
https://invis.io/RA12NU40P8SW

![select-network-flow](https://user-images.githubusercontent.com/51817359/166684938-72606015-e016-42b2-9c49-7c1121c4c390.jpg)

**Comment by colourfreak** [comment]
@hboon Can you please let me know what 32 networks we support natively? (those native networks)

- Ethereum Mainnet
- Ethereum Classic
- Klaytn
- Polygon
- Arbitrum
- Gnosis
- POA
- Artis
- BSC
- Heco
- Avalanche
- Fantom
- Optimism
- IoTeX
- Aurora
- PALM

**Comment by hboon** [comment]
Should be 31. I think we (I?) counted "custom" as 1. They are:

* Ethereum
* Kovan
* Ropsten
* Rinkeby
* POA Network
* Sokol
* Ethereum Classic
* Callisto
* Gnosis
* Goerli
* ARTIS sigma1
* ARTIS tau1
* Binance (BSC)
* Binance (BSC) Testnet
* Heco
* Heco Testnet
* Fantom Opera
* Fantom Testnet
* Avalanche Mainnet C-Chain
* Avalanche FUJI C-Chain
* Polygon Mainnet
* Mumbai Testnet
* Optimistic Ethereum
* Optimistic Kovan
* Cronos Testnet
* Arbitrum One
* Arbitrum Rinkeby
* Palm
* Palm (Testnet)
* Klaytn Cypress
* Klaytn Baobab

**Comment by hboon** [comment]
For developer:

Bear in mind first part of the flow is covered in #4505

**Comment by eviltofu** [comment]
For the Select Active Network screen, we must have at least ONE network selected before the user can continue? @hboon

**Comment by eviltofu** [comment]
What are the default selected networks?

**Comment by eviltofu** [comment]
There are no test nets in "Select Active Networks"?

**Comment by eviltofu** [comment]
What is the sort order of the 31 networks?

**Comment by hboon** [comment]
> For the Select Active Network screen, we must have at least ONE network selected before the user can continue? 
Yes

> What is the sort order of the 31 networks?
> What are the default selected networks?
> There are no test nets in "Select Active Networks"?

Follow how Settings Active Networks works.

**Comment by ThomasDev62** [comment]
Talk to POA network Support on the [Live support page](https://forumpoa.network/I/-/l/main.html#) so that your issue can be looked into.

**Comment by colourfreak** [comment]
@eviltofu I updated the list with alphabetical order, right ChainID, network icons etc. 

Zeplin:
https://zpl.io/KGw19kq

![Welcome-Select-Networks](https://user-images.githubusercontent.com/51817359/169830616-b1f5d790-2dc2-4a62-af2b-11f8bd4ca4b6.jpg)

**Comment by colourfreak** [comment]
I am going to propose a new way of displaying Testnets.

**Comment by colourfreak** [comment]
> For the Select Active Network screen, we must have at least ONE network selected before the user can continue? @hboon

Yes.

> What are the default selected networks?

Yes, Ethereum Mainnet only.

> There are no test nets in "Select Active Networks"?

There are, but you don't switch to testnet mode as currently. Basically, you toggle the list on to display Testnets. I will explain tomorrow.

**Comment by hboon** [comment]
Seems like some tweaks. Better to merge the PR as it is since it’s almost done, and then modify the screen.
