### ISSUE TITLE
Can't connect to any of Klaytn Dapps

### ISSUE THREAD

**Issue by colourfreak** [AlphaWallet/alpha-wallet-ios#4522]
I added the most popular Klaytn dapps to the AlphaWallet browser home page. The problem is when you want to connect to these dapps. There is no way to do so. Let's first check why, then think about potential solutions. 

You can run this in AlphaWallet browser
https://alphawallet.com/browser-item-category/klaytn/

https://user-images.githubusercontent.com/51817359/166884574-c8e1f1be-160f-4769-aec2-5401d4b5391a.mp4

![Screenshot_20220425-114613_AlphaWallet](https://user-images.githubusercontent.com/51817359/166884592-54bffcde-f506-4386-b1f1-4fb64f0f62b8.jpg)
![Screenshot_20220425-114714_AlphaWallet](https://user-images.githubusercontent.com/51817359/166884595-e23a9258-beba-434b-934a-b40941ffdaa5.jpg)
![Screenshot_20220425-114747_AlphaWallet](https://user-images.githubusercontent.com/51817359/166884596-df94a7d4-9802-4ae9-ba26-db0ad583c1f4.jpg)
![Screenshot_20220425-114815_AlphaWallet](https://user-images.githubusercontent.com/51817359/166884598-4d06561c-3c25-4113-bb24-056ff9d814bd.jpg)
![Screenshot_20220425-114939_AlphaWallet](https://user-images.githubusercontent.com/51817359/166884599-8e05d78a-f1de-4c04-9a45-54a5f88aa296.jpg)
![Screenshot_20220425-115242_AlphaWallet](https://user-images.githubusercontent.com/51817359/166884600-165d37de-a495-4877-b495-865a249a01c2.jpg)

**Comment by hboon** [comment]
@colourfreak I can't figure out how https://3space.art/ works or if it works.

If I try to connect with desktop Chrome + MetaMask extension, it tells me to connect to Ethereum mainnet if I try Klaytn.

When I'm connected to Ethereum mainnet on Chrome + MetaMask, it shows my ETH mainnet balance (sort of OK). Then when I try to buy something, eg. https://3space.art/payment/794, it lists the price as ETH and wants me to WalletConnect. Connect to Klaytn fails, but connecting to Ethereum mainet works. But when I try to buy, it says my balance is too low (when it isn't).

Can you try to find a path where it works with Chrome + MetaMask (or any wallet)? Then I will try to reproduce it for AlphaWallet and fix things?

---

This *seems* to work as expected:

https://app.eklipse.finance/

The rest looks like they are either hardcoded to work with MetaMask or they even support MetaMask.

**Comment by hboon** [comment]
cc @hieronymus4826

**Comment by hieronymus4826** [comment]
Contacted 3space to check if they want to explore the issue with us and try to build a reliable connector to Klaytn

**Comment by hboon** [comment]
Re-open if necessary
