### ISSUE TITLE
In WalletConnect, Connected to URL should be copyable or open web page.

### ISSUE THREAD

**Issue by eviltofu** [AlphaWallet/alpha-wallet-ios#4544]
![Screen Shot 2022-05-07 at 9 36 34 AM copy](https://user-images.githubusercontent.com/1050309/167232893-dd279e6d-b8a2-4a83-9826-31082c7b833a.png)

I should be able to copy the URL. The URL should also be displayed in full otherwise I can't tell what this is.

**Comment by hboon** [comment]
Makes sense. Maybe tap to expand them like we did for balance? And optionally a button to trigger the sharing sheet (so user can copy or open in the browser from there)? @colourfreak?

**Comment by colourfreak** [comment]
https://zpl.io/L48JmMJ
![QR-WalletConnect-Connected-Copy](https://user-images.githubusercontent.com/51817359/167570568-edd4d2af-dc34-40ff-b2b3-e91f72757475.png)

**Comment by hboon** [comment]
@colourfreak do we support tap to expand?

We tap the button to copy instead of show the sharing sheet, right?

**Comment by colourfreak** [comment]
> @colourfreak do we support tap to expand?
> 
> We tap the button to copy instead of show the sharing sheet, right?

We have so much space here that it would be better to show the full address by default. Is this what we want to achieve in this issue, or just make it copyable?

**Comment by hboon** [comment]
Both would be desirable.
