### ISSUE TITLE
`RLMException, reason: String too big`

### ISSUE THREAD

**Issue by oa-s** [AlphaWallet/alpha-wallet-ios#4565]
@hboon do you have any ideas of fixing this issue?

https://console.firebase.google.com/u/0/project/alphawallet-ios-prod/crashlytics/app/ios:com.stormbird.alphawallet/issues/087983306e9dd43e58732fcfac54a7b9?time=last-twenty-four-hours&sessionEventKey=90639cde2eb6426081d6f36049c5d468_1674795446825436627

**Comment by oa-s** [comment]
@hboon does it means that we trying to store single string that is larger then 16mb?

**Comment by hboon** [comment]
Looking… Strange that it says it's a regression from v3.40 (427) and was closed. I checked the closed issues and it's not there.

<img width="891" alt="Screenshot 2022-05-11 at 3 58 27 PM" src="https://user-images.githubusercontent.com/56189/167799007-f898e70c-1a9c-4a41-aa8f-949c564547aa.png">

**Comment by oa-s** [comment]
it couble be good to find our that exactly is large for storing, added pr to track users selected wallet address, for later watch ing and trying to reproduce

**Comment by hboon** [comment]
OK

**Comment by oa-s** [comment]
we also can track json strings that is greater than 16 mb, and skip such balances, but i don't think that its a good idea.

**Comment by oa-s** [comment]
it might happen, when json contains base64 data for images, that might  happen quite ofter

**Comment by hboon** [comment]
>@hboon i have suggestion about this issue, what if we update our code base to save balance json as file, like we do for erc1155, and store file url in realm instead whole json string?

@oa-s hmm. But wondering if that will end up with many loose files. Is there a Blob type? What if we convert to Data when we store JSON strings? I suppose the Realm size limitation is because of indexing performance rather than storage?

**Comment by hboon** [comment]
> not sure, as there same limitation for String, Data types, max file size is 16 mb

I see. Since we are guessing that it's images that are base64 encoded in the JSON, do you want to do a size check for them and log if it exceeds a certain size? (say 2MB?) to Firebase? Then if it crashes we ought to pick it up. Maybe log these:

* URL where we picked up the JSON from
* Contract + chain
* Token ID

?
