### ISSUE TITLE
PasscodeCharacterView behaves abnormally in dark mode

### ISSUE THREAD

**Issue by Saif-Fazlani** [AlphaWallet/alpha-wallet-ios#4577]
Hi, I'm working on a fork of AlphaWallet.
I've recently modified the PasscodeCharacterView, specifically the size of circle and hyphen. It works totally fine but when I switch the app from light to dark OR dark to light mode, the UI messes up. 
Attaching short screen recording below.

https://user-images.githubusercontent.com/96777132/167860725-56fabf0e-e6c5-4035-bee8-fba83d53d0fe.mp4

**Comment by Saif-Fazlani** [comment]
Yes. I removed UIUserInterfaceStyle=Light from Info.plist, so that the app may adapt to dark mode.
As you can see, once I enter a character, the hyphen gets removed and a circle appears in its place. But, when I switch the app to dark mode, the hyphen also appears with the circle.

**Comment by hboon** [comment]
@eviltofu see if there's a simple fix?
