### ISSUE TITLE
Transaction in Progress Pop Up Displays Misinformation When We Transact Out Ethereum Mainnet.

### ISSUE THREAD

**Issue by Hoanib** [AlphaWallet/alpha-wallet-ios#4578]
In both apps, iOS as well Android, when we interact with others blockchains instead of Ethereum Mainnet the sent pop up Transaction in Progress displays misinformation notifying users that the transaction is sent to the Ethereum blockchain instead of the blockchain we are interacting. 

![image](https://user-images.githubusercontent.com/100842739/167893334-32edf187-2078-43ac-b7e0-ccd981f7a6b5.png)

![image](https://user-images.githubusercontent.com/100842739/167893444-6098790f-360b-4b88-bf83-5d28a8d33b34.png)

**Comment by HebrewDev** [comment]
Talk to Algorand Support on the [Live support page](https://algo-developer.com) so that your issue can be looked into.
