### ISSUE TITLE
The App Is Not Showing the Balance in USD of the Synthetic Tokens and the Boba Token

### ISSUE THREAD

**Issue by Hoanib** [AlphaWallet/alpha-wallet-ios#4580]
These synthetic tokens are the ones we use to implement cross chain swaps and AW is not registering them well. The balances in USD are not shown. Also the value on dollars of the native token of the Boba blockchain is not shown.

![image](https://user-images.githubusercontent.com/100842739/167969366-83cb64d4-ee65-436c-987c-35b5d6ac75b6.jpeg)

**Comment by oa-s** [comment]
@Hoanib  please share a wallet address for watching (for checking)

**Comment by hboon** [comment]
@oa-s maybe have to use `tokens.json`

**Comment by Hoanib** [comment]
0xF2E8F55cc2fd97D44FD0f32040F081F0d2efE5F9

**Comment by Hoanib** [comment]
> @Hoanib do you know if these tokens supports by CoinGecko api?

Boba yes, I don't know about others but I will check 
![image](https://user-images.githubusercontent.com/100842739/170620022-b0c1801f-e453-48db-ba91-3355d04c9db5.jpeg)

**Comment by Hoanib** [comment]
CVXCRV appears on CoinGecko

0x62b9c7356a2dc64a1969e19c23e4f579f9810aa7

![image](https://user-images.githubusercontent.com/100842739/171747527-3857096d-dd5d-4f48-95e1-dba993868fcd.jpeg)

**Comment by Hoanib** [comment]
This dApp registers all DeFi tokens, also the total balance of the wallet by chain/of all chains.

https://debank.com/

**Comment by oa-s** [comment]
Made `AlphaWalletRemoteTickerIdsFetcher` to use searching in `tokens.json`, but without impl for now, as not quite realize its logic.

we got `let tickerIdsFetcher: TickerIdsFetcherImpl` tickerids fetching that is able to search for ticker id in sub providers, eg. InMemory, InListOfDefaultCoinGeckoTickerIds, and in Tokens.json. 
it has method `func tickerId(for token: TokenMappedToTicker) -> AnyPublisher<TickerId?, Never> {` that returns first **ticker id** found in any of added sub providers.

**Comment by hboon** [comment]
> Made `AlphaWalletRemoteTickerIdsFetcher` to use searching in `tokens.json`, but without impl for now, as not quite realize its logic.
> 
> we got `let tickerIdsFetcher: TickerIdsFetcherImpl` tickerids fetching that is able to search for ticker id in sub providers, eg. InMemory, InListOfDefaultCoinGeckoTickerIds, and in Tokens.json. it has method `func tickerId(for token: TokenMappedToTicker) -> AnyPublisher<TickerId?, Never> {` that returns first **ticker id** found in any of added sub providers.

Buzz me if you want help or clarification

**Comment by oa-s** [comment]
looks like i am in finish line with it, testing and pushing
