### ISSUE TITLE
Make ERC721 token image larger by default

### ISSUE THREAD

**Issue by colourfreak** [AlphaWallet/alpha-wallet-ios#4584]
Can you make it up to 344x344? 

### Now
<img width="808" alt="Screenshot 2022-05-12 at 09 54 58" src="https://user-images.githubusercontent.com/51817359/168020551-0a3561ce-c309-478d-9958-afa60cda6aca.png">

### Should be
<img width="439" alt="Screenshot 2022-05-12 at 09 51 31" src="https://user-images.githubusercontent.com/51817359/168024236-c8eea870-460c-4acd-80e8-90e9e7d791c6.png">

Zeplin
https://zpl.io/2ZAQrpX

**Comment by hboon** [comment]
@colourfreak if it’s not a square, do we make the width or height be 344pt? Width?

**Comment by colourfreak** [comment]
width
