### ISSUE TITLE
Make ERC721/ERC1155 token image with rounded corners

### ISSUE THREAD

**Issue by colourfreak** [AlphaWallet/alpha-wallet-ios#4585]
Is it possible to make the image with rounded corners as it is on Opensea?
<img width="858" alt="Screenshot 2022-05-12 at 10 22 30" src="https://user-images.githubusercontent.com/51817359/168025785-1bceeddc-f4a3-487d-9cdd-5ca19bef93a4.png">

**Opensea**
![2022-05-12 09 31 52](https://user-images.githubusercontent.com/51817359/168025941-0d3f6113-373d-4c03-a1f9-67ec706c62c9.png)

**Comment by hboon** [comment]
Hmm. Not sure because of problems with SVGs. Let’s try

**Comment by colourfreak** [comment]
I am not a developer, but maybe put a mask on the top of it?
[Maybe this can help](https://medium.com/@ahmedmuslimani609/rounded-corner-images-and-why-it-kills-your-app-248750884379).

**Comment by hboon** [comment]
@colourfreak should this be rounded too, for NFTs?

<img width="487" alt="Screenshot 2022-05-20 at 1 41 09 PM" src="https://user-images.githubusercontent.com/56189/169458525-ad677567-6e70-4a62-95fc-89ffe539a084.png">

**Comment by colourfreak** [comment]
Yes. It gives e the feeling of something modern.
