### ISSUE TITLE
Add Custom NFTs Tokens (Polygon) Is Not Working Properly

### ISSUE THREAD

**Issue by Hoanib** [AlphaWallet/alpha-wallet-ios#4602]
I could not add this NFT token (Polygon). The app isn't filling the info labels.

Contract Address:
0x2953399124f0cbb46d2cbacd8a89cf0599974963

![image](https://user-images.githubusercontent.com/100842739/168408055-b501e276-40af-4963-86ae-c0ced4b3f88d.png)

**Comment by hboon** [comment]
Fixed with #4876
