### ISSUE TITLE
[EthereumABI] Memory leak for NSRegularExpression

### ISSUE THREAD

**Issue by oa-s** [AlphaWallet/alpha-wallet-ios#4616]
@hboon  can you please make a fork from EthereumABI, so we would be able to make changes.
creating an instance of **NSRegularExpression** for every function call a lot of non released resources.

**Comment by hboon** [comment]
@oa-s done https://github.com/AlphaWallet/EthereumABI

**Comment by hboon** [comment]
@oa-s you ought to have permission to do it though.

**Comment by oa-s** [comment]
hmm, seems like i am not able to merge pr for that repo

**Comment by hboon** [comment]
> hmm, seems like i am not able to merge pr for that repo

Have just added you.
