### ISSUE TITLE
Travis failure

### ISSUE THREAD

**Issue by oa-s** [AlphaWallet/alpha-wallet-ios#4628]
seems like it cached pods instead of updating it

**Comment by hboon** [comment]
Have cleared the cache and re-run, the tests pass now.

This can be done by:

1. https://app.travis-ci.com/github/AlphaWallet/alpha-wallet-ios
2. Click More options
3. Click Caches
4. Click "Delete All repository caches" and wait for a few seconds on the page
5. Trigger the test from the latest PR to re-run
