### ISSUE TITLE
suppose to wrap Token in TokenScript.Token if its semantically right

### ISSUE THREAD

**Issue by oa-s** [AlphaWallet/alpha-wallet-ios#4645]
As we are using `Activity.AssignedToken` instead of `TokenObject`, its name not really fits, what it represents itself. it could be better to rename it into something like `Token`. The problem is `Token` already taken. I suppose existing `Token` is related to `TokenScript` and can be move there. @hboon any suggestings?

**Comment by hboon** [comment]
@oa-s are you keeping it as a subtype of `Activity`? If so, just `Activity.Token`?

**Comment by hboon** [comment]
Yes we might move `Token` into a TokenScript pod eventually, but if `Activity.Token` works, we can use now

**Comment by oa-s** [comment]
> Yes we might move `Token` into a TokenScript pod eventually, but if `Activity.Token` works, we can use now

ok, lets keep it for now

**Comment by hboon** [comment]
Ah. I see. Just realised I read the title wrongly. But yes. If you check that Token is only use for TokenScript, feel free to move it :)
