### ISSUE TITLE
SuperKongz NFT has empty empty Info sub-tab

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#4655]
https://cn.etherscan.com/address/0x989e5F1Da336c8a99a89E41594aa197735443563

<img width="487" alt="Screenshot 2022-05-25 at 12 34 13 PM" src="https://user-images.githubusercontent.com/56189/170180517-2c9b03c8-6d50-4643-b5fe-0966359e230e.png">

**Comment by oa-s** [comment]
Closing as nothing we can do here
