### ISSUE TITLE
Deeplink-based wallet API

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#4659]
So we'll need 2 actionsheets, 1 for connect and one for sign message. We might have sign transaction in the future (but not now).

The fields/values are:

For Connect
---
* icon
* name
* URL
* Hardcoded description with address value (feel free to rewrite it, including the address format)

For Sign Message
---
* icon
* name
* URL
* Message

Maybe a good idea to mirror how we present actionsheets for WalletConnect. We don't need to track sessions like we do for WalletConnect.

Roughly like this:

![deeplink-wallet-api](https://user-images.githubusercontent.com/56189/170187787-f6c3869b-73ba-4c22-87c9-7720d8e8d20e.png)

**Comment by colourfreak** [comment]
<img width="1355" alt="Screenshot 2022-06-06 at 12 40 51" src="https://user-images.githubusercontent.com/51817359/172145800-918e035d-1b05-49fa-9e8b-6cb7a11012e0.png">

Zeplin:
https://zpl.io/p1zO3oM
https://zpl.io/Dl6zgDW

**Comment by colourfreak** [comment]
I made the SVG of their logo as I could not find it anywhere online:
![bytebrew](https://user-images.githubusercontent.com/51817359/172146132-69fb99df-2b78-4fcd-9675-4b1bf05a0d24.svg)

**Comment by hboon** [comment]
For developer: Unlike WalletConnect, there's no concept of sessions, and only sign (personal) message, not transactions. And internal doc that describes what happens: https://www.notion.so/stormbirdlabs/Deep-link-based-wallet-SDK-3a8a124b54754452b9623615a8ac8e2b

**Comment by oa-s** [comment]
@hboon out of comment above, why do we need `connect` method, in case when we can send `sing`method before `connect`?

**Comment by oa-s** [comment]
@hboon pr is ready for review
