### ISSUE TITLE
Fix error in iOS Safari right after successful WalletConnect connect/signing

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#4660]
This is for accessing the dapp with iOS Safari and using WalletConnect on the same device

An error message like this in Safari:

<img width="487" alt="Screenshot 2022-05-25 at 2 26 55 PM" src="https://user-images.githubusercontent.com/56189/170195090-1260c30d-2b54-4bb8-a219-9bec7ea8defb.png">

But not if you see the banner with the "OPEN" button to open in AlphaWallet. If this banner and button appears, tap the "OPEN" and it should switch to AlphaWallet. It's iOS which decided not to open it AlphaWallet right away. Tapping the "OPEN" button might help ask Safari to do the right thing in future attempts (it didn't for Boon):

<img width="487" alt="Screenshot 2022-05-27 at 10 31 21 AM" src="https://user-images.githubusercontent.com/56189/170617037-aadf5c83-fc5b-40c1-bac3-6fcbb6c02f61.png">

**Comment by colourfreak** [comment]
https://user-images.githubusercontent.com/51817359/170198613-d2a5a66f-51b1-4140-8f70-2ff60c6a68a4.MOV

**Comment by hboon** [comment]
@colourfreak yes, don't test with that site for WalletConncet, it doesn't seem to work properly.

**Comment by Hoanib** [comment]
Yes, this issue happens in Simbiosis dApp (https://app.symbiosis.finance/swap) using both browsers, Safari and AW browser. 

![image](https://user-images.githubusercontent.com/100842739/170567060-e9c408e4-9965-466f-8ea7-4daa5c33bda3.png)

![image](https://user-images.githubusercontent.com/100842739/170567137-97a68814-4823-4050-86b0-c6489948ed24.png)

![image](https://user-images.githubusercontent.com/100842739/170567266-8178407a-0826-4032-ae73-3cc78c7cd8b7.png)

**Comment by hboon** [comment]
With https://app.symbiosis.finance/swap, how do you trigger the error in iOS Safari?

I tried this:

1. Visit https://app.symbiosis.finance/swap in iOS Safari
2. Tap the connect button at the top right
3. Tap page 2, tap AlphaWallet, OK
4. Connect in AlphaWallet
5. Wait a few seconds
6. Manually switch to iOS Safari
7. Seems good

**Comment by hboon** [comment]
#4735 makes using WalletConnect in the dapp browser work (better?): 

This issue #4660 continues to be for iOS Safari + WalletConnect

**Comment by hboon** [comment]
Apparently an issue with the WalletConnect integration (from the dapp's end) or a problem with iOS itself. Because following the steps for https://github.com/AlphaWallet/alpha-wallet-ios/issues/4660#issuecomment-1139221167 with iOS MetaMask, step 8 opens the app store page for MetaMask.


And sometimes after visiting other functionality in the dapp (pools etc) and then attempting to swap again will switch to AlphaWallet as expected.

**Comment by hboon** [comment]
Not something we can't fix. It's iOS + Universal links
