### ISSUE TITLE
Remove mutually exclusive mainnet and testnet modes so testnets can be selected once they are enabled

### ISSUE THREAD

**Issue by colourfreak** [AlphaWallet/alpha-wallet-ios#4663]
**Zeplin:**
https://zpl.io/g8oZleA

**Changes:**
- Change the headline to "Select Active Networks"
- Update the plus icon https://zpl.io/beqJEqq
- Update the network icons https://zpl.io/agE1LeZ
- When you toggle Testnet on, you will see a warning about the Monopoly money
- When you hit OK on the warning screen, the list of networks expands by testnet networks
- We cancel Testnet mode where you only see Mainnet or Testnet at a time. They can be both displayed, so we are coming back to the same flow as previously
- At the bottom of the list you have a Browse More button, it takes you to the same screen as plus button at the top - browse all other networks
- Add placeholder network icons for all remaining networks - https://zpl.io/jZE1A5m

**Comment by colourfreak** [comment]
Prototype:
https://invis.io/MW1220T36ET3

**Comment by colourfreak** [comment]
https://user-images.githubusercontent.com/51817359/170235287-63bf1a64-60bf-4e31-9d8a-40fb85245765.mov

**Comment by eviltofu** [comment]
Currently three main nets (**Ethereum**, **Gnosis**, **Polygon Mainnet**) and one test nets (**Ropsten**) are shown by default. Do you want to change the defaults to just one main nets and the one test nets? @colourfreak @hboon

**Comment by eviltofu** [comment]
Typing in the search field will filter both main nets and test nets lists at the same time?

**Comment by eviltofu** [comment]
The main net and test net toggles are used to toggle between main nets and testiest on the tokensviewcontroller (main Home Screen). With the main net toggle gone now, how do we determine which (main net or test net) to display?

**Comment by hboon** [comment]
The app currently runs in a mutually exclusive mode for mainnet and testnet. i.e. only mainnets OR testnets can be enabled, not at the same time.

This issue is a design (I almost always mean design in a general sense when’s sting design, not visual design) change that makes it possible for mainnet and testnets to be enabled at the same time. So the testnet switch is just a gate:acknowledgement to make testnets available (alongside mainnets)

**Comment by eviltofu** [comment]
So tokensviewcontroller now has to display both main nets and test nets?

**Comment by hboon** [comment]
Modify title to clarify scope. Has to be bundle with #4653 or at least most of #4653

**Comment by colourfreak** [comment]
> Typing in the search field will filter both main nets and test nets lists at the same time?

It should display networks from "Browse" tab. I mean search results.

**Comment by colourfreak** [comment]
> The app currently runs in a mutually exclusive mode for mainnet and testnet. i.e. only mainnets OR testnets can be enabled, not at the same time.
> 
> This issue is a design (I almost always mean design in a general sense when’s sting design, not visual design) change that makes it possible for mainnet and testnets to be enabled at the same time. So the testnet switch is just a gate:acknowledgement to make testnets available (alongside mainnets)

Yes.

**Comment by eviltofu** [comment]
Ok but I think the main screen should be modified to differentiate test nets from main nets. I'm looking at the custom RPC network list and a few do not have the words test/testnet in their titles. @colourfreak @hboon

**Comment by hboon** [comment]
TestNets would still show up like this right? That "ROPSTEN (TEST)" in the screenshot. Isn't that enough to distinguish them from mainnets?

<img width="487" alt="Screenshot 2022-05-26 at 3 38 17 PM" src="https://user-images.githubusercontent.com/56189/170441380-ad4d10ac-3e9c-4788-aba1-26fdef7ee1c6.png">

**Comment by eviltofu** [comment]
Can we merge all the main nets into the `Select Active Networks` screen? So `ThaiChain`, `Ubiq`, etc will appear on the same screen as `Gnosis`, `Heco`? Then hitting the Plus button will show the enter custom network manually.

**Comment by colourfreak** [comment]
> Can we merge all the main nets into the `Select Active Networks` screen? So `ThaiChain`, `Ubiq`, etc will appear on the same screen as `Gnosis`, `Heco`? Then hitting the Plus button will show the enter custom network manually.

No. Don't overwhelm users with an infinite number of networks. If we have more than 50 networks, how difficult would be to find out Optimism? The list is alphabetical, so you would have to use a search box.

**Comment by hboon** [comment]
Also the bundled networks are tested (we need more testing) and supported with special casing for some of them. The custom ones are not.

**Comment by hboon** [comment]
Let’s hold off doing this. Cutting down unnecessary work in phase 1

**Comment by hboon** [comment]
Out of phase 1

**Comment by hboon** [comment]
Superseded by #6034
