### ISSUE TITLE
App icon on "launch" screen looks a little small

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#4672]
Want to tweak it, @colourfreak ? Maybe at least bigger to close match the app icon size in the homescreen?

![IMG_6A29A449417D-1](https://user-images.githubusercontent.com/56189/170447264-77c6bb9a-b6de-4fa9-8869-6c0aed3d525b.jpeg)

**Comment by colourfreak** [comment]
Zeplin:
https://zpl.io/no0o9ok

<img width="1311" alt="Screenshot 2022-05-27 at 08 07 00" src="https://user-images.githubusercontent.com/51817359/170640486-7be1c4c8-7d87-441c-97d2-f2505c7c69af.png">
