### ISSUE TITLE
Not Shown $ Value of Tokens

### ISSUE THREAD

**Issue by Hoanib** [AlphaWallet/alpha-wallet-ios#4720]
The value in dollars of the tokens are not displayed, only the value of the native tokens of each network.

I'm pretty sure that when I opened the app after updated it with this last version 3.42 (430) the app showed the value in dollars but when I interacted with the app they disappeared immediately.

![image](https://user-images.githubusercontent.com/100842739/171289956-924409d2-32b2-47ae-a164-11cceb66ea92.png)

**Comment by hboon** [comment]
Unless it isn't included in CoinGecko's API

**Comment by oa-s** [comment]
[Hoanib](https://github.com/Hoanib) please share wallet address to watch

**Comment by Hoanib** [comment]
> [Hoanib](https://github.com/Hoanib) please share wallet address to watch 

0xdB9334F400Da78E564142c7d1A2d19515105E7bb
