### ISSUE TITLE
Not Shown NFT Icon and Image

### ISSUE THREAD

**Issue by Hoanib** [AlphaWallet/alpha-wallet-ios#4721]
The small icons of the NFTs are not displayed nor their images. They are not shown on All nor on Collectives.

![image](https://user-images.githubusercontent.com/100842739/171291546-0583e9ea-54fe-4383-9a74-3c6dd5a93401.jpeg)

![image](https://user-images.githubusercontent.com/100842739/171291570-a1ef135d-5a29-466b-8c08-e3a9ce3d2b34.png)

![image](https://user-images.githubusercontent.com/100842739/171291595-cea947d1-cc27-4a53-8bc7-35bc3f5616c0.png)

**Comment by oa-s** [comment]
@Hoanib please share wallet address to watch

**Comment by Hoanib** [comment]
> @Hoanib please share wallet address to watch 

0xdB9334F400Da78E564142c7d1A2d19515105E7bb

**Comment by oa-s** [comment]
open sea rate limit issue, works now

**Comment by hboon** [comment]
BTW OpenSea rate limits are probably limiting by IP too. So it can be hard to tell sometimes.

**Comment by oa-s** [comment]
@Hoanib this issue should be fixed with latest version
