### ISSUE TITLE
Not Shown Charts

### ISSUE THREAD

**Issue by Hoanib** [AlphaWallet/alpha-wallet-ios#4723]
The app only shows the chart of the native tokens. 

![image](https://user-images.githubusercontent.com/100842739/171297364-78be682f-7f29-45b2-a415-4c3c8f629f3d.png)

![image](https://user-images.githubusercontent.com/100842739/171297375-66a55cc1-6897-4587-8ba7-2252d7a4a346.png)

**Comment by hboon** [comment]
Unless it isn't included in CoinGecko's API

**Comment by Hoanib** [comment]
Both are included in. CoinGecko's API
