### ISSUE TITLE
Crashes when watching too many wallets

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#4725]
> iOS keeps crashing after I adding many watch wallet

v3.42 build 430

Victor

**Comment by eviltofu** [comment]
How many is too many? Can you give an exact figure?

**Comment by hboon** [comment]
> How many is too many? Can you give an exact figure?

@zhangzhongnan928 ^

**Comment by zhangzhongnan928** [comment]
I watched 19 wallets + 5 wallets

**Comment by oa-s** [comment]
@hboon what latest version do we have uploaded to appstore? facing a lot of crashes  
https://console.firebase.google.com/u/0/project/alphawallet-ios-prod/crashlytics/app/ios:com.stormbird.alphawallet/issues/aeb3e80dad0b5a7a339162bc5239980e?time=last-seven-days&sessionEventKey=4013475ffe8d4d61b76eaaf3113437e0_1682971026949823123

on queue **com.RealmStore.syncQueue**, but we are not using it anymore.

**Comment by hboon** [comment]
This 1f0715afe88c7b02114f85e079338d0315fb5610

**Comment by oa-s** [comment]
ok, i see

**Comment by oa-s** [comment]
Do we still facing crashes with latest uploaded version?

**Comment by hboon** [comment]
Doesn't seem so, close it if you think that's all we need/can do at the moment and we'll revisit.

**Comment by oa-s** [comment]
i'v got 14 wallets, 7 watched, 1 keystore and 6 connected, the app lokks like works fine. will test it more

**Comment by oa-s** [comment]
do we still have this issue?

**Comment by hboon** [comment]
@oa-s maybe not. Will try again in the future. Close for now.
