### ISSUE TITLE
Wallet Names Disappeared

### ISSUE THREAD

**Issue by Hoanib** [AlphaWallet/alpha-wallet-ios#4733]
The names given to my wallet addresses disappeared as if someone had erased them.

In the screenshot example you will see one of them renamed after this crash. 

![image](https://user-images.githubusercontent.com/100842739/171575853-215ca4c5-b605-4d9b-9bd5-7e5cc00bf5d8.png)

**Comment by oa-s** [comment]
@Hoanib how can i reproduce this issue, is there some special steps?

**Comment by Hoanib** [comment]
> @Hoanib how can i reproduce this issue, is there some special steps?

The only way to reproduce this issue, I guess, is having the previous version, naming several wallet addresses and then update the app.

**Comment by hboon** [comment]
@oa-s might have to reason about it without reproducing it :P The name are still stored in `UserDefaults`. Could that be a problem?

**Comment by oa-s** [comment]
not sure, but it shouldn't as we load wallet names when ap is already in foreground, loading from userdefaults should be fine in that state

**Comment by oa-s** [comment]
hmm, let's move them into some other persistent storage
