### ISSUE TITLE
Change font family to Circular Std

### ISSUE THREAD

**Issue by colourfreak** [AlphaWallet/alpha-wallet-ios#4741]
I have just updated all screens with a new font. I am going to check if we need a license for this font (paid). 
[Circular.zip](https://github.com/AlphaWallet/alpha-wallet-ios/files/8824679/Circular.zip)

**Comment by hboon** [comment]
Since we aren't going with Circular Std, we should either confirm that we switch to another font or revert to Source Sans Pro.

@colourfreak have we decided yet?

**Comment by hboon** [comment]
Ok, let's revert/stick to Sources Sans Pro for now.

**Comment by hboon** [comment]
No-op since it was only introduced in the `switch-font` branch
