### ISSUE TITLE
Improve display of domain.name in EIP712 v3 from WalletConnect

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#4744]
Not sure if this if we sign from the dapp browser without involving WalletConnect, but a reproducible example with WalletConnect:

1. In mobile Safari (definitely not dapp browser), visit https://attestation-foxgem.vercel.app
2. Enter email
3. Copy and paste confirmation code received in email
4. Accept WalletConect connection
5. In signing request, the URL (the row after "Network" in the screenshot below) appears as the field name (i.e. on the left column) instead of as the value

<img width="200" alt="Screenshot 2022-06-02 at 11 04 02 AM" src="https://user-images.githubusercontent.com/56189/171782754-0f35ba4b-5026-41b1-9362-740517132149.png">

Also after tapping on "Show" for the URL, the copy button is clipped off. This screen looks OK when there's a field name (eg. if we had tap on the "Show button" for "payload" instead)

<img width="200" alt="Screenshot 2022-06-02 at 11 04 00 AM" src="https://user-images.githubusercontent.com/56189/171782743-896fba18-e91b-48f1-a296-cd04dcd45428.png">

It looks like the EIP712 payload (seems to be `.signTypedMessageV3`) looks like this:

```
{
   "domain" : {
      "name" : "http://wwww.attestation.id",
      "version" : "0.1"
   },
   "message" : {
      "description" : "Creating email attestation",
      "identifier" : "hboon@motionobj.com",
      "payload" : "72f8d41ab26751f57fef3615a58c6015d3fb6597081263bcf2a863f510806a8e",
      "timestamp" : "Fri Jun 03 2022 12:08:26 GMT+0800"
   },
   "primaryType" : "AttestationRequest",
   "types" : {
      "AttestationRequest" : [
         {
            "name" : "payload",
            "type" : "string"
         },
         {
            "name" : "description",
            "type" : "string"
         },
         {
            "name" : "timestamp",
            "type" : "string"
         },
         {
            "name" : "identifier",
            "type" : "string"
         }
      ],
      "EIP712Domain" : [
         {
            "name" : "name",
            "type" : "string"
         },
         {
            "name" : "version",
            "type" : "string"
         }
      ]
   }
}

```
So maybe that URL is `domain.name`?
```

**Comment by oa-s** [comment]
@hboon can you please chare whole json, i am not able to pass thought attestation steps, after entering confirmation code it resets me on entering emain address again.

**Comment by hboon** [comment]
> @hboon can you please chare whole json, i am not able to pass thought attestation steps, after entering confirmation code it resets me on entering emain address again.

Oh, can you try once more, have to disable "Prevent Cross-Site Tracking" in mobile Safari (or macOS Safari). If it still doesnt' work let me know and I'll paste.

**Comment by oa-s** [comment]
thanks, it works now

**Comment by oa-s** [comment]
its emoty because of missing `domainVerifyingContract` 

```
AlphaWallet.EIP712TypedData(types: ["EIP712Domain": [AlphaWallet.EIP712Type(name: "name", type: "string"), AlphaWallet.EIP712Type(name: "version", type: "string")], "AttestationRequest": [AlphaWallet.EIP712Type(name: "payload", type: "string"), AlphaWallet.EIP712Type(name: "description", type: "string"), AlphaWallet.EIP712Type(name: "timestamp", type: "string"), AlphaWallet.EIP712Type(name: "identifier", type: "string")]], primaryType: "AttestationRequest", domain: {
  "version" : "0.1",
  "name" : "http:\/\/wwww.attestation.id"
}, message: {
  "payload" : "53ce72a8f4182ad9369239a99d2f6c182d1d1858e50a5e75e371c843a377436d",
  "timestamp" : "Mon Jun 06 2022 11:04:22 GMT+0300",
  "identifier" : "krypto.pank@gmail.com",
  "description" : "Creating email attestation"
})
```

**Comment by oa-s** [comment]
`"{\"primaryType\":\"AttestationRequest\",\"message\":{\"payload\":\"53ce72a8f4182ad9369239a99d2f6c182d1d1858e50a5e75e371c843a377436d\",\"timestamp\":\"Mon Jun 06 2022 11:04:22 GMT+0300\",\"description\":\"Creating email attestation\",\"identifier\":\"krypto.pank@gmail.com\"},\"types\":{\"EIP712Domain\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"version\",\"type\":\"string\"}],\"AttestationRequest\":[{\"name\":\"payload\",\"type\":\"string\"},{\"name\":\"description\",\"type\":\"string\"},{\"name\":\"timestamp\",\"type\":\"string\"},{\"name\":\"identifier\",\"type\":\"string\"}]},\"domain\":{\"version\":\"0.1\",\"name\":\"http:\\/\\/wwww.attestation.id\"}}"`

**Comment by hboon** [comment]
> its emoty because of missing domainVerifyingContract

Can you remember me what is `domainVerifyingContract`? If it still complies with the EIP712, we should handle it somehow, if it doesn't, let's see what it is (maybe the attestation.id guys need to fix it then).

**Comment by oa-s** [comment]
@Boon in view model `EIP712TypedDataConfirmationViewModel` we got
            `
            values = [
                (key: data.domainName, value: .string(data.domainVerifyingContract?.truncateMiddle ?? ""))
            ] + data.message.keyValueRepresentationToFirstLevel
            `
             what if we replace it with displaying separatelly `domain name`, and `verifying contract` like
            `
            values = [
                (key: "Domain Name", value: .string(data.domainName))
                (key: "Verifying Contract", value: .string(data.domainVerifyingContract?.truncateMiddle ?? "-"))
            ] + data.message.keyValueRepresentationToFirstLevel
            `

**Comment by hboon** [comment]
@oa-s Ah, from https://eips.ethereum.org/EIPS/eip-712

> Definition of domainSeparator
> 
> domainSeparator = hashStruct(eip712Domain)
> where the type of eip712Domain is a struct named EIP712Domain with one or more of the below fields. Protocol designers only need to include the fields that make sense for their signing domain. Unused fields are left out of the struct type.
> 
> string name the user readable name of signing domain, i.e. the name of the DApp or the protocol.
> string version the current major version of the signing domain. Signatures from different versions are not compatible.
> uint256 chainId the EIP-155 chain id. The user-agent should refuse signing if it does not match the currently active chain.
> address verifyingContract the address of the contract that will verify the signature. The user-agent may do contract specific phishing prevention.
> bytes32 salt an disambiguating salt for the protocol. This can be used as a domain separator of last resort.

This line in particular:

> Protocol designers only need to include the fields that make sense for their signing domain. Unused fields are left out of the struct type.

So it looks like `verifyingContract` is optional. Would you be able to improve it so it's handled when it's missing? What is actually shown if the `verifyingContract` is available?  If there's nothing we should just display the field name as "domain.name", maybe?

**Comment by oa-s** [comment]
it displays something like: `domain.name: domain.verifyingContract`

**Comment by hboon** [comment]
I see. Can we do this?

```
if notEmpty(domain.verifyigContract)
    "\(domain.name): \(domain.verifyingContract)"
else
    "domain.name: \(domain.name)"
end
```
