### ISSUE TITLE
Scrolling in Wallet tab on device is jerky

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#4749]
Reproducible with 398d0201d5cce2f86c2f6ef8ac23ac8c75151514. Might be since last few days or weeks?

**Comment by oa-s** [comment]
@hboon  it looks like function makes no sence, as cached values never read `private func cache(attributeValues values: [AttributeId: AssetAttributeSyntaxValue], forTokenId tokenId: TokenId)`

**Comment by oa-s** [comment]
as there is no any call of `getValuesFromCache(forTokenId`

**Comment by oa-s** [comment]
so `lazy var assetAttributesCache: AssetAttributesCache = AssetAttributesCache()` can be removed at all
