### ISSUE TITLE
Improve the AlphaWallet Repo icon

### ISSUE THREAD

**Issue by colourfreak** [AlphaWallet/alpha-wallet-ios#4753]
<img width="1001" alt="Screen Shot 2022-06-03 at 13 59 12" src="https://user-images.githubusercontent.com/51817359/171849322-c294f2ca-afa4-46ae-9911-74b12576e9b7.png">

![AlphaWallet-icon-official](https://user-images.githubusercontent.com/51817359/171849351-2f86831b-42ba-47f2-b225-d2fc3bad0116.jpg)

**Comment by hboon** [comment]
Apparently some kind hearted soul did it already:

<img width="790" alt="Screenshot 2022-06-06 at 12 19 27 PM" src="https://user-images.githubusercontent.com/56189/172094182-0b14e811-3d47-4ba0-a503-ae44d6dba4d7.png">
