### ISSUE TITLE
Add a bar with rounded corners bar at the top of each action sheet

### ISSUE THREAD

**Issue by colourfreak** [AlphaWallet/alpha-wallet-ios#4802]
<img width="1203" alt="Screenshot 2022-06-06 at 12 12 33" src="https://user-images.githubusercontent.com/51817359/172141658-497ffb6d-3f38-41f4-84cc-9ad9ebef5e45.png">
<img width="1368" alt="Screenshot 2022-06-06 at 12 12 44" src="https://user-images.githubusercontent.com/51817359/172141663-5a0e18c0-d74c-4da2-b148-3824dd09a6cc.png">
<img width="1659" alt="Screenshot 2022-06-06 at 12 13 24" src="https://user-images.githubusercontent.com/51817359/172141770-48b9773d-9a31-47b8-ab14-5b29f132f917.png">

Zeplin:
https://zpl.io/9qkzZee

**Comment by oa-s** [comment]
looks like all modal presented views have rounded corners
