### ISSUE TITLE
Crash because `AssetAttributesCacheData` (and its `contracts` property) is accessed from both main and other threads

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#4810]
https://console.firebase.google.com/u/0/project/alphawallet-ios-prod/crashlytics/app/ios:com.stormbird.alphawallet/issues/b4d18e4fca5eaeea7e6ae168945bb1c4?time=last-seven-days&versions=3.43%20(431)&sessionEventKey=9a5f34714ad64310995bad3f4ae531eb_1683421825567050960

**Comment by eviltofu** [comment]
Can we use _Actor_ here or it’s Swift 5.x only?

**Comment by hboon** [comment]
Actors are supposedly >= Swift 5.5.

I think yes, they can be used to solve such problems (it would be similar to how the incoming PR uses a custom `AtomicDictionary`). But I think this approach is fundamentally flawed. We need to reduce concurrent read/writes and centralize them and hence reduce data races in the app instead.
