### ISSUE TITLE
AlphaWallet Icon Needs to Be Updated in Connect Wallet

### ISSUE THREAD

**Issue by Hoanib** [AlphaWallet/alpha-wallet-ios#4846]
AlphaWallet icon needs to be updated in Wallet Connect and some direct connections like BadgerDAO dApp and Curve dApp. 

![image](https://user-images.githubusercontent.com/100842739/172845771-f8da362f-10f5-4037-8339-7b94ac0fc3f3.png)

![image](https://user-images.githubusercontent.com/100842739/172846228-730ecc0f-7274-4b7f-a4b1-0cda0235d459.png)

![image](https://user-images.githubusercontent.com/100842739/172846319-d569a791-f630-4afb-9885-69c50646476b.png)

**Comment by hboon** [comment]
- [ ] AlphaWallet v1
- [ ] AlphaWallet v2

**Comment by hboon** [comment]
Updated at https://cloud.walletconnect.com/app/registry/listing, need to wait for approval

**Comment by Hoanib** [comment]
Good to know! 

BadgerDAO dApp migrated to Web3 connection. And for some days the connection failed. Now it works fine.

**Comment by hboon** [comment]
It's gone live.

**Comment by Hoanib** [comment]
@hboon, New Icon on Wallet Connect achieved. On https://curve.fi/ not yet.

**Comment by hboon** [comment]
Right, but that's not using WalletConnect. Have created an issue #4898 for it
