### ISSUE TITLE
Fatal Exception: RLMException Wrong transactional state (no active transaction, wrong type of transaction, or transaction already in progress) 

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#4854]
https://console.firebase.google.com/u/0/project/alphawallet-ios-prod/crashlytics/app/ios:com.stormbird.alphawallet/issues/285b5fb66afd208d5527e26e64dd761e?time=last-seven-days&versions=3.43%20(436)&sessionEventKey=9de750f9fee44d6c81b9bc3534daa14d_1685645310597285838

Branch: https://github.com/AlphaWallet/alpha-wallet-ios/tree/testflight-3.43-436

**Comment by hboon** [comment]
Apparently this isn't #4856. @oa-s Can you help look into this one too?

**Comment by oa-s** [comment]
here what i found in doc https://github.com/realm/realm-swift/search?q=Wrong+transactional+state&type=code
but not clearly understand it

**Comment by hboon** [comment]
Let's leave it for a bit and see if it pops up again (much).

**Comment by hboon** [comment]
Removed the High Priority tag, assuming that Crashlytics is capturing the occurrences correctly.

**Comment by oa-s** [comment]
looks like this issue still exists 

https://console.firebase.google.com/u/0/project/alphawallet-ios-prod/crashlytics/app/ios:com.stormbird.alphawallet/issues/285b5fb66afd208d5527e26e64dd761e?time=last-seven-days&versions=3.43%20(437);3.43%20(436);3.43%20(435);3.43%20(434);3.43%20(431)&sessionEventKey=c9159740b4a7464db75396fc4754459c_1689489276892418629

**Comment by oa-s** [comment]
the crash caused when we calling function `getBalanceForNonErc721Or1155Tokens`, for all 3 events, looks like the same source of the crash

**Comment by hboon** [comment]
> the crash caused when we calling function `getBalanceForNonErc721Or1155Tokens`, for all 3 events, looks like the same source of the crash

Where do you see this?

I see these crash logs

A.

> Crashed: com.google.firebase.crashlytics.ios.exception
> 0  AlphaWallet                    0x6f6364 FIRCLSProcessRecordAllThreads + 393 (FIRCLSProcess.c:393)
> 1  AlphaWallet                    0x6f6744 FIRCLSProcessRecordAllThreads + 424 (FIRCLSProcess.c:424)
> 2  AlphaWallet                    0x704c30 FIRCLSHandler + 34 (FIRCLSHandler.m:34)
> 3  AlphaWallet                    0x704a74 __FIRCLSExceptionRecord_block_invoke + 215 (FIRCLSException.mm:215)
> 4  libdispatch.dylib              0x3a30 _dispatch_client_callout + 20
> 5  libdispatch.dylib              0x12c90 _dispatch_lane_barrier_sync_invoke_and_complete + 56
> 6  AlphaWallet                    0x704214 FIRCLSExceptionRecord + 219 (FIRCLSException.mm:219)
> 7  AlphaWallet                    0x70451c FIRCLSExceptionRecordNSException + 109 (FIRCLSException.mm:109)
> 8  AlphaWallet                    0x703e14 FIRCLSTerminateHandler() + 273 (FIRCLSException.mm:273)
> 9  libc++abi.dylib                0x10f18 std::__terminate(void (*)()) + 20
> 10 libc++abi.dylib                0x13ebc __cxa_rethrow + 148
> 11 libobjc.A.dylib                0x186c0 objc_exception_rethrow + 44
> 12 CoreFoundation                 0x1ecb4 CFRunLoopRunSpecific + 836
> 13 Foundation                     0x19464 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 236
> 14 AlphaWallet                    0x270bdc closure #1 in closure #1 in RunLoopThread.main() + 36 (RunLoopThread.swift:36)
> 15 AlphaWallet                    0x271070 partial apply for thunk for @callee_guaranteed () -> (@unowned Bool, @error @owned Error) + 4333719664 (<compiler-generated>:4333719664)
> 16 libswiftObjectiveC.dylib       0x1a10 autoreleasepool<A>(invoking:) + 64
> 17 AlphaWallet                    0x270af8 closure #1 in RunLoopThread.main() + 35 (RunLoopThread.swift:35)
> 18 AlphaWallet                    0x4b13a4 thunk for @callee_guaranteed () -> (@error @owned Error) + 4336079780 (<compiler-generated>:4336079780)
> 19 AlphaWallet                    0x271048 partial apply for thunk for @callee_guaranteed () -> (@error @owned Error) + 4333719624 (<compiler-generated>:4333719624)
> 20 libswiftObjectiveC.dylib       0x1a10 autoreleasepool<A>(invoking:) + 64
> 21 AlphaWallet                    0x270c48 @objc RunLoopThread.main() + 4333718600 (<compiler-generated>:4333718600)
> 22 Foundation                     0x6943c __NSThread__start__ + 808
> 23 libsystem_pthread.dylib        0x19ac _pthread_start + 148
> 24 libsystem_pthread.dylib        0xe68 thread_start + 8

B. 

> Fatal Exception: RLMException
> 0  CoreFoundation                 0x99288 __exceptionPreprocess
> 1  libobjc.A.dylib                0x16744 objc_exception_throw
> 2  Realm                          0xae18 (Missing UUID b18519c3d4173ac1b7750b0cb6d71d22)
> 3  Realm                          0x15cb8 (Missing UUID b18519c3d4173ac1b7750b0cb6d71d22)
> 4  AlphaWallet                    0x2bb524 specialized MultipleChainsTokensDataStore.updateTokenWithoutCommitWrite(primaryKey:action:realm:) (<compiler-generated>)
> 5  AlphaWallet                    0x2bbbc8 specialized closure #1 in closure #1 in MultipleChainsTokensDataStore.addOrUpdate(_:) (<compiler-generated>)
> 6  AlphaWallet                    0x4b1518 closure #1 in RealmStore.performSync(_:) (<compiler-generated>)
> 7  AlphaWallet                    0x270ed8 RunLoopThread.execute(_:) + 68 (RunLoopThread.swift:68)
> 8  AlphaWallet                    0x270f5c @objc RunLoopThread.execute(_:) (<compiler-generated>)
> 9  Foundation                     0x3df20 __NSThreadPerformPerform
> 10 CoreFoundation                 0xbb414 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__
> 11 CoreFoundation                 0xcc1a0 __CFRunLoopDoSource0
> 12 CoreFoundation                 0x5694 __CFRunLoopDoSources0
> 13 CoreFoundation                 0xb05c __CFRunLoopRun
> 14 CoreFoundation                 0x1ebc8 CFRunLoopRunSpecific
> 15 Foundation                     0x19464 -[NSRunLoop(NSRunLoop) runMode:beforeDate:]
> 16 AlphaWallet                    0x270bdc closure #1 in closure #1 in RunLoopThread.main() + 36 (RunLoopThread.swift:36)
> 17 AlphaWallet                    0x271070 partial apply for thunk for @callee_guaranteed () -> (@unowned Bool, @error @owned Error) (<compiler-generated>)
> 18 libswiftObjectiveC.dylib       0x1a10 autoreleasepool<A>(invoking:)
> 19 AlphaWallet                    0x270af8 closure #1 in RunLoopThread.main() + 35 (RunLoopThread.swift:35)
> 20 AlphaWallet                    0x4b13a4 thunk for @callee_guaranteed () -> (@error @owned Error) (<compiler-generated>)
> 21 AlphaWallet                    0x271048 partial apply for thunk for @callee_guaranteed () -> (@error @owned Error) (<compiler-generated>)
> 22 libswiftObjectiveC.dylib       0x1a10 autoreleasepool<A>(invoking:)
> 23 AlphaWallet                    0x270c48 @objc RunLoopThread.main() (<compiler-generated>)
> 24 Foundation                     0x6943c __NSThread__start__
> 25 libsystem_pthread.dylib        0x19ac _pthread_start
> 26 libsystem_pthread.dylib        0xe68 thread_start

**Comment by oa-s** [comment]
for `b` case it caused when `5 AlphaWallet 0x2bbbc8 specialized closure https://github.com/AlphaWallet/alpha-wallet-ios/issues/1 in closure https://github.com/AlphaWallet/alpha-wallet-ios/issues/1 in MultipleChainsTokensDataStore.addOrUpdate(:) ()` get called. in same time when we take a look at `org.alphawallet.swift.walletBalance` queue:

```
libsystem_kernel.dylib
__psynch_cvwait + 8
4 Foundation
-[NSObject(NSThreadPerformAdditions) performSelector:onThread:withObject:waitUntilDone:] + 120
5 AlphaWallet
<compiler-generated> - Line 4308471112
RunLoopThread.performSync(_:) + 4308471112
6 AlphaWallet
<compiler-generated> - Line 4308748508
MultipleChainsTokensDataStore.addOrUpdate(_:) + 4308748508
7 AlphaWallet
<compiler-generated> - Line 4306641628
PrivateBalanceFetcher.notifyUpdateBalance(_:) + 4306641628
8 AlphaWallet
<compiler-generated> - Line 4306644680
closure #1 in PrivateBalanceFetcher.getBalanceForNonErc721Or1155Tokens(forToken:) + 4306644680
9 AlphaWallet
<compiler-generated> - Line 4306695172
partial apply for thunk for @escaping @callee_guaranteed (@guaranteed BigInt) -> (@error @owned Error) + 4306695172
10 PromiseKit
$s10PromiseKit8ThenablePAAE4done2on5flags_AA0A0CyytGSo17OS_dispatch_queueCSg_8Dispatch0J13WorkItemFlagsVSgy1TQzKctFyAA6ResultOyARGcfU_yycfU_TA + 104
```
