### ISSUE TITLE
Crash when scrolling Wallet tab because of OOM (out of memory)

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#4856]
@oa-s and this is the one fixed by 97b54bb3928808537e86b947efec4a530e50490a ?

If so:

---

Do we know which type of images causes problems?

I see the fix works by limiting the cache size and downsampling the image; do you think it is sufficient if we modify the Google links to download lower resolution version of the images instead? For example to only use `GoogleContentSize.s750` in the rare case and never `.s2500` (though I don't think we use `.s2500` at all). This way we can keep the GIF/SVG animations?

But we can push 97b54bb3928808537e86b947efec4a530e50490a as a PR (for `master`) first, and we might always need to downsample any way since we don't control what gets downloaded, especially if the images aren't hosted by Google.

---

BTW, looks like Crashlytics doesn't log OOM errors anymore? I thought they did, years ago.

**Comment by oa-s** [comment]
> Do we know which type of images causes problems?

I am not sure that it fixes all issues with out our memory. It looks like I doesn't outs rapidly, but in time perspective, it still exists. I guess we can play with auto release pool, for some places.

**Comment by oa-s** [comment]
> For example to only use GoogleContentSize.s750 in the rare case and never .s2500

That is what we actually what we do. We don't use size limits.

**Comment by oa-s** [comment]
> BTW, looks like Crashlytics doesn't log OOM errors anymore? I thought they did, years ago.

looks like here is an answer, https://twitter.com/Arzhannikov_A/status/1073194994134065152, so they don't support it

**Comment by hboon** [comment]
> > Do we know which type of images causes problems?
> 
> I am not sure that it fixes all issues with out our memory. It looks like I doesn't outs rapidly, but in time perspective, it still exists. I guess we can play with auto release pool, for some places.

Modern iOS devices have lots of memory. Maybe we can selectively downsample when the sizes are big? At the same time keep a maximum cache size (like you did in the commit?)

Does kingfisher's downsampling do this: only downsize when it's past a certain size?

**Comment by hboon** [comment]
> I guess we can play with auto release pool, for some places.

Seems unnecessary if we can make sure total cache size is capped and no single image is too big?

**Comment by oa-s** [comment]
> This way we can keep the GIF/SVG animations?

we don't do downsizing for SVG, but for GIF images, it. need to investigate it

**Comment by oa-s** [comment]
> Does kingfisher's downsampling do this: only downsize when it's past a certain size?

it needs to rechech it

**Comment by hboon** [comment]
Ok. Will let you to it. And see if you want to do a PR based on 97b54bb3928808537e86b947efec4a530e50490a first, then you can come back and revisit this

**Comment by oa-s** [comment]
> > I guess we can play with auto release pool, for some places.
> 
> Seems unnecessary if we can make sure total cache size is capped and no single image is too big? Unless you mean the downloaded image is too big and we don't purge it fast enough even after downsampling?

i meant, that in some other parts, not related to loading images.
