### ISSUE TITLE
heh benchmarking might be tricky: how do we know adding the `if` isn't less performant, but we don't notice due this line making up for it?

### ISSUE THREAD

**Issue by arslan-raza-143** [AlphaWallet/alpha-wallet-ios#4872]
heh benchmarking might be tricky: how do we know adding the `if` isn't less performant, but we don't notice due this line making up for it?

__Originally posted by @martriay in https://github.com/OpenZeppelin/cairo-contracts/pull/326#discussion_r897287006__

**Comment by hboon** [comment]
Not relevant/wrong repo
