### ISSUE TITLE
Balance of NFTs on Polygon aren't detected (remains at 0). The tokens aren't autodetected either

### ISSUE THREAD

**Issue by Hoanib** [AlphaWallet/alpha-wallet-ios#4888]
A user complained about not seeing his already sent NFT (Polygon) to his Alpha. I added his wallet as a watch wallet and tried to import the token without success. 

Contract address: 0x612ee4BfD2EE2EAA7ef44120543C78AB4Bd16635

Transaction Hash: 0x6bec38eafaa857a58da983d9742ae1d2513b1b865202f638bb38edcf5129942b

**Comment by Hoanib** [comment]
Important note:

I wanted to create another repo but I think it's related. User did not give details but I do not think the user added the contract manually, however the token appears on his wallet but when he clicks on the notification "You don't have any tokens" pops up.

![image](https://user-images.githubusercontent.com/100842739/174915716-1eb7f175-541d-4bf2-bdcd-61878ff23391.jpeg)

**Comment by Hoanib** [comment]
New information related with this case: 

User has another wallet address with the same problem. 

When user click on any of the 4 NFTs a error occurs saying You don't have any tokens.

Wallet: 0x32024F224b493Da02B2b9B985ee2fEe37Eed966b

![image](https://user-images.githubusercontent.com/100842739/175364583-bac1fe49-600b-492e-afa5-857e1869c8d2.jpeg)

**Comment by hboon** [comment]
Found the reason.

**Comment by Hoanib** [comment]
@hboon, And now user got this error message:

![image](https://user-images.githubusercontent.com/100842739/177389799-9954a7d4-cac4-4606-8dbd-6e4df368f95a.jpeg)

**Comment by hboon** [comment]
> @hboon, And now user got this error message:
> 
> ![image](https://user-images.githubusercontent.com/100842739/177389799-9954a7d4-cac4-4606-8dbd-6e4df368f95a.jpeg)

I've created a new issue #4937 for this Would you be able to help describe how to reproduce there?

**Comment by hboon** [comment]
@oa-s help see if this is still reproducible?

**Comment by oa-s** [comment]
guess we've fixed it in some pr earlier

**Comment by hboon** [comment]
Yes, it sounds familiar :)
