### ISSUE TITLE
Display PHI NETWORK Price

### ISSUE THREAD

**Issue by Phinetwork** [AlphaWallet/alpha-wallet-ios#4890]
Need to add PHI Network Price API

here is the api example https://price.phi.network/api/ticker?filter=WPHI

pulls data from subgraph https://graph.phiswap.com/subgraphs/name/exchange/graphql

from analytics here https://info.phiswap.com

**Comment by Phinetwork** [comment]
Hello can we get this added to IOS @hboon this url works https://phiswap-api.herokuapp.com/api/ticker?filter=WPHI

to get price data 



will also be live at https://price.phi.network/api/ticker?filter=WPHI shortly

**Comment by Phinetwork** [comment]
@hboon are we able to integrate for next update?

**Comment by Phinetwork** [comment]
Testing 123 is this thing on @hboon ⭐️🚀🌈

**Comment by Phinetwork** [comment]
Are we working on this @hboon

**Comment by hboon** [comment]
@Phinetwork sorry, thought (wrongly!) that the endpoint isn't ready yet. Will look into it very soon.

**Comment by Phinetwork** [comment]
> @Phinetwork sorry, thought (wrongly!) that the endpoint isn't ready yet. Will look into it very soon.

Great thank you when it is please let me make would love to get price API integrated.
