### ISSUE TITLE
App crashes when closing it

### ISSUE THREAD

**Issue by oa-s** [AlphaWallet/alpha-wallet-ios#4893]
```
*** Terminating app due to uncaught exception 'NSDestinationInvalidException', reason: '*** -[AlphaWallet.RunLoopThread performSelector:onThread:withObject:waitUntilDone:modes:]: target thread exited while waiting for the perform'
*** First throw call stack:
(0x184aa5288 0x19d79f744 0x1862a897c 0x1862c5648 0x104973b00 0x104dae7e4 0x104dae8ec 0x104dae94c 0x10a0f27c0 0x10a103ca8 0x104dae65c 0x105048618 0x105049530 0x1048768b4 0x104875898 0x104874d64 0x104872b30 0x19cb1e4b0 0x19cb1dda8 0x19cb1bc54 0x19cb34970 0x19cb1af98 0x19cb14880 0x19cb18c48 0x19cb18c48 0x19cb259fc 0x19e617c04 0x10a0f0c70 0x10a0f27c0 0x10a0f5320 0x10a106878 0x10a107264 0x1f5c08080 0x1f5c07e5c)
```

This crash appears when we closing the app

**Comment by oa-s** [comment]
https://console.firebase.google.com/u/0/project/alphawallet-ios-prod/crashlytics/app/ios:com.stormbird.alphawallet/issues/0bfccae2beb9dbe613a2eec01b3e1786?versions=3.43%20(437);3.43%20(436);3.43%20(435);3.43%20(434);3.43%20(431)&time=last-thirty-days&sessionEventKey=ffdf4c632e224e7e8fa40a21900ccdb9_1683835958266544176

**Comment by hboon** [comment]
Do you mean when going to background (i.e. user went to the homescreen or switched to another app)?

**Comment by oa-s** [comment]
Close due to non activity
