### ISSUE TITLE
A Temporary Displaying Issue on Settings

### ISSUE THREAD

**Issue by Hoanib** [AlphaWallet/alpha-wallet-ios#4903]
Have you noticed a displaying issue loading Settings when you open AlphaWallet? For a moment the page does not displayed SELECT ACTIVE Networks and instead displayed repeatedly CHANGE/ADD WALLET. 

![image](https://user-images.githubusercontent.com/100842739/175790433-e79072cb-f833-440d-a3d0-14c37e6215e6.png)

**Comment by oa-s** [comment]
[Hoanib](https://github.com/Hoanib) Please share build number

**Comment by oa-s** [comment]
is there some specific steps to reproduce it?

**Comment by Hoanib** [comment]
> is there some specific steps to reproduce it?

Just open the app (it should be closed) and go to Settings, quickly look at the System section and you should see it. It change in a matter of minutes.

**Comment by hboon** [comment]
@oa-s could it be related to ENS resolution, maybe these few lines:

https://github.com/AlphaWallet/alpha-wallet-ios/blob/60c67778c368c29f25e975abb001a210815e79ca/AlphaWallet/Settings/ViewControllers/SettingsViewController.swift#L146

Seems easier to reproduce like this:

1. Launch app (after killing)
2. Immediately tap Settings tab
3. Immediately scroll

(seems to happen when ENS resolves from address to a name)

So better to test with a wallet that has an ENS name

**Comment by Hoanib** [comment]
I think it's fixed!
