### ISSUE TITLE
Prepare tokens for diffable data source

### ISSUE THREAD

**Issue by oa-s** [AlphaWallet/alpha-wallet-ios#4925]
https://github.com/AlphaWallet/alpha-wallet-ios/issues/4918#issuecomment-1170131025

> or if you mean logic to refresh, that should be simplified too, let's try to do a reloadData() when there's changes to the data and see if it works well enough. We can always do things like diff the JSON (just calling it JSON for simplicity) for more efficient refreshes. Also UICollectionView has some support for diffable data sources (I forgot if UITableView does), so we might simplify things quite a bit too.

`UITableView` also supports  diffable data sources.  But i guess `UICollectionView` would be more prefferable for displaying tokens, as it supports different layouts. but i am not sure about swipe gestures to delete actions. @hboon any ideas?

**Comment by hboon** [comment]
> UITableView also supports diffable data sources. But i guess UICollectionView would be more prefferable for displaying tokens, as it supports different layouts. but i am not sure about swipe gestures to delete actions. @hboon any ideas?

I guess we can use `UICollectionViewListCell` (and move minimum deployment target to iOS 14).

In that case, we can start converting `TokensViewController` over to `UICollectionView`? We should do it with baby steps of course, but I think after we get it to use `UICollectionView`, the transition to and fro the `Collectibles` tab can be made much smoother.
