### ISSUE TITLE
Do not add 1gwei to `2000wei` gas price estimate for PHI network

### ISSUE THREAD

**Issue by Phinetwork** [AlphaWallet/alpha-wallet-ios#4931]
Gas fees are much too high for phi network. transactions can process fast with 2000 wei . 1 gwei is very high for chain and makes it very expensive for users. can we please adjust gas to 2000 wei and not 1 gwei thank you

**Comment by hboon** [comment]
@Phinetwork in case, shouldn't eth_gasPrice return `1` instead of `2000` (`0x7d0`)?

```
curl -H 'accept: application/json' -H 'content-type: application/json' -H 'user-agent: AlphaWallet/395 CFNetwork/1237 Darwin/20.5.0' -H 'accept-language: en-us' --data-binary ' {"method":"eth_gasPrice","params":[],"id":1,"jsonrpc":"2.0"}' --compressed "https://rpc1.phi.network" -s

{"jsonrpc":"2.0","id":1,"result":"0x7d0"}
```

**Comment by Phinetwork** [comment]
not sure what you mean. I Just know that chain will process fast with transaction cost of 2000 wei 1gwei is very expensive for the tokenomics. but 2000 wei works to process fast and is appropriate for tokenomics.

**Comment by hboon** [comment]
I'm sorry I mixed up the 2 gas prices (`2000` and `1`) when I was writing this comment: https://github.com/AlphaWallet/alpha-wallet-ios/issues/4931#issuecomment-1173310044.

Will fix this. There will be a limitation in the UI though, the gas price used will show up as "~0 PHI". Our gas UI is tailored for `gwei` :)

**Comment by Phinetwork** [comment]
thats ok if gas price shows up at 0 gwei would perfer that they have user pay so high gas. will make it so users can practically use with wei so its ok we appreciate the update
