### ISSUE TITLE
NFT balance for Klaytn doesn't seem to be fetched correctly

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#4935]
token: 0xd915c8ad3241f459a45adcbbf8af42caa561a154
wallet: 0xbbce83173d5c1D122AE64856b4Af0D5AE07Fa362
Transaction: https://scope.klaytn.com/tx/0x856ef977221a48b3ff432d99326ab4b9f9a2df2ee84bf0726e7d91863a9ddcfe

Maybe related, this function doesn't seem to be called? https://github.com/AlphaWallet/alpha-wallet-ios/blob/cfb22ef2acd530a880a2d449299bcc4ff8ac6dc4/AlphaWallet/Covalent/TransactionProviders/CovalentNetworkProvider.swift#L37

The token is detected, but the balance is `0`.

**Comment by oa-s** [comment]
@hboon is it ok that we skip event logs like `Approval(indexed address owner, indexed address spender, uint256 value)` ?

**Comment by oa-s** [comment]
This issue might happen when we stop fetcher timer. Looks like when we receive an error we stop it, and don't restart anymore, when `paginationNotFound ` appears.

    private func didReceiveError(error: Covalent.CovalentError) {
        switch error {
        case .requestFailure(let e):
            switch e {
            case .general(error: let e):
                if case Covalent.DecodyingError.paginationNotFound = e {
                    transactionsTracker.fetchingState = .done
                    scheduler.cancel()
                } else {
        transactionsTracker.fetchingState = .failed
    }
            }
        case .jsonDecodeFailure, .sessionError:
            transactionsTracker.fetchingState = .failed
        }
    }

**Comment by hboon** [comment]
> @hboon is it ok that we skip event logs like `Approval(indexed address owner, indexed address spender, uint256 value)` ?

In the transaction history log? Sure.

**Comment by hboon** [comment]
But add a TODO so we can find it?
