### ISSUE TITLE
"Impossible To Build Configuration"

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#4937]
Refer https://github.com/AlphaWallet/alpha-wallet-ios/issues/4888#issuecomment-1175351309

@Hoanib would you help to describe how to reproduce this?

**Comment by Hoanib** [comment]
Blue Sky NFT token (Polygon)

Contract address: 0x612ee4BfD2EE2EAA7ef44120543C78AB4Bd16635

Wallet: 0x32024F224b493Da02B2b9B985ee2fEe37Eed966b

Owner wallet managed, some how, to add manually the contract address of the token. And the token is displayed in his wallet as the screenshots show. (I couldn't add it, even using his wallet as Watch Wallet)

![image](https://user-images.githubusercontent.com/100842739/177464096-5d3eb06f-f7ea-48f2-9e70-b2808e422abb.jpeg)

![image](https://user-images.githubusercontent.com/100842739/177464152-badae0b9-8738-4fba-bf3a-786f4ea64c57.jpeg)

![image](https://user-images.githubusercontent.com/100842739/177464202-978eb55a-146a-4608-a53a-2f492f49ec41.jpeg)

![image](https://user-images.githubusercontent.com/100842739/177464277-bb29f7ad-5ec5-4948-a7bb-b89aed0438d1.jpeg)

**Comment by hboon** [comment]
Not sure if it's still reproducible

**Comment by oa-s** [comment]
will check

**Comment by oa-s** [comment]
yes this is still a case, we wrongly update imported token balance, mean create a token with incorrect balance value, and user have some time to open token screen and go throught send process. 
@hboon  what if we remove creating a ercToken `AddOrUpdateTokenAction` case add(ercToken: ErcToken, shouldUpdateBalance: Bool) with its balance, as balance at this point can be incorrect. and will relay on balance fetcher, to get right balance value?

**Comment by hboon** [comment]
> what if we remove creating a ercToken AddOrUpdateTokenAction case add(ercToken: ErcToken, shouldUpdateBalance: Bool) with its balance, as balance at this point can be incorrect. and will relay on balance fetcher, to get right balance value?

Is this correct? —

1. User manually imports token
2. We auto detect token type correctly (so ERC-721 here) and add the wrong balance; do we add say 2, or do we have an invalid JSON representing 1, eg. `[{}, {}]`?
3. User tries to send the token before the balance is updated

If so, where in the code does it throw `TransactionConfiguratorError.impossibleToBuildConfiguration` and why does the code do it?

And do you mean to just set it to `0`/`[]` instead in step (2)?

---

Alternatively, what if we have a way to check/denote that the balance for each token is not ready yet? — I don't know how useful is this or if it just complicates things. Maybe a flag or switch the balance to an enum

**Comment by oa-s** [comment]
add pr with checking right token balance for each token type, also updated check is zero balance function. now should be good

**Comment by oa-s** [comment]
> If so, where in the code does it throw TransactionConfiguratorError.impossibleToBuildConfiguration and why does the code do it?
i suppose that its here https://github.com/AlphaWallet/alpha-wallet-ios/blob/cfd411b1d9f46f9450207fed10499ca95fc8127f/AlphaWallet/Transfer/Collectibles/Coordinators/TransferCollectiblesCoordinator.swift#L113
