### ISSUE TITLE
Remove manual sorting functionality in "Add / Hide Tokens" screen

### ISSUE THREAD

**Issue by oa-s** [AlphaWallet/alpha-wallet-ios#4948]
While working on #4925, found that applying sorting tokens by name or value, it actually makes no sence in sorting tokens by order index. When we change order, of token on `Add/Hide token` screen, it reloads and returns back to sorting by `name or value`
@hboon  any ideas?

**Comment by hboon** [comment]
Ah, ok, so it's like this:

The sorting option in this screen should only apply to this screen and not to the Wallet tab:

<img width="200" alt="Screenshot 2022-07-08 at 12 34 56 PM" src="https://user-images.githubusercontent.com/56189/177917591-3dfb7d45-5aa8-4d57-841f-463ebb16664e.png">

The Wallet tab should always be sorted by value followed by name, with hardcoded priority for the chain's native token (or something like that, as it was)

And I think that's basically what you are saying too, right? If so, let's remove the sorting functionality (and the handle bars on the right of the UITableView which support that). Would you also help with:

- [ ] Create Android issue to remove manual sorting functionality in "Add / Hide Tokens" screen?
