### ISSUE TITLE
app.mail3.me cannot connect wallet from Dapp browser

### ISSUE THREAD

**Issue by seabornlee** [AlphaWallet/alpha-wallet-ios#4966]
name: Bug Report
about: Using AlphaWallet, but it's not working as you expect?

---

**Describe the bug**

**Steps to reproduce (REQUIRED)**
Steps to reproduce the behavior

1. Tap Browser tab
2. Visit app.mail3.me
3. Tap WalletConnect
4. Wait 

**Expect**
6a. A `Connect` button as android side does

**Observed**
6b. A QR code

**Screenshots**
If applicable, screenshots (preferred to video) to help explain your problem, a wallet address or transaction hash if applicable/possible

**Version or build number number**
3.45(441)

Related to https://github.com/AlphaWallet/alpha-wallet-android/pull/2712

**Comment by hboon** [comment]
@seabornlee it works for me on iOS for both:

* MetaMask (this prompts for signature, after signing, it seems to be connected)
* WalletConnect
    1. Tap WalletConnect
    2. Display the WalletConnect mobile link screen (with Mobile and QR Code tab, Mobile is selected by default)
    3. Tap page 2 and tap AlphaWallet
    4. Prompted to Connect
    5. Tap Connect
    6. Tap Browser tab
    7. Tap Check
    8. Display signing request actionsheet
    9. Tap Sign and it seems to work too

Does it work differently for you?

**Comment by seabornlee** [comment]
@hboon It‘s different on my side.
https://user-images.githubusercontent.com/735708/178699080-59f78879-0130-4905-8a33-c8985f91bc87.MP4

**Comment by hboon** [comment]
Strange, I see this on both device and simulator:

<img width="487" alt="Screenshot 2022-07-13 at 5 52 16 PM" src="https://user-images.githubusercontent.com/56189/178705672-febdbd24-1b51-475e-9aa6-b5707cec774e.png">

Can you try again after clearing cache? Settings > Advanced > Clear Browser Cache. Also make sure in Browser tab > … > Connected to: Ethereum

**Comment by oa-s** [comment]
tested with real device, works fine for me.

**Comment by oa-s** [comment]
only thing i faced is that after wallet connect connecting, iphone navigation moved to previously used app. Maybe we need to add check to apply apps navigation to browser apps only, or disable navigation for in app browser

**Comment by hboon** [comment]
Oh. I thought of this but can’t reproduce it so was mistaken it’s ok. Can you help create an issue with strap to reproduce? Especially for switching/launching apps to trigger it

**Comment by hboon** [comment]
Looks like they changed it. I don't see WalletConnect anymore and connect as MetaMask (ouch!) works.
