### ISSUE TITLE
Need dark mode art assets for Initial network selection screen

### ISSUE THREAD

**Issue by eviltofu** [AlphaWallet/alpha-wallet-ios#4969]
See https://github.com/AlphaWallet/alpha-wallet-ios/pull/4955#issue-1298776662

**Comment by colourfreak** [comment]
![Welcome-Select-Networks-Dark@2x](https://user-images.githubusercontent.com/51817359/180677725-4d9663cd-c43b-40bc-a06b-c0c2f0a38f4c.jpg)

**Comment by hboon** [comment]
@eviltofu this done? Otherwise, would you help add to #5288?

**Comment by eviltofu** [comment]
@hboon, this appears to be done. Dark mode on master 67adcf86cd0b888dd31002b8077e03f8a41254c8
![Screen Shot 2023-02-27 at 4 43 45 PM copy](https://user-images.githubusercontent.com/1050309/221515548-60c5523b-4d45-4f86-a289-2e1bab14f02a.png)

**Comment by hboon** [comment]
Thanks
