### ISSUE TITLE
No way to export private key & keystore import doesn't work

### ISSUE THREAD

**Issue by Phinetwork** [AlphaWallet/alpha-wallet-ios#4993]
This is a major issue. There is no way to export private keys and when u download keystore and then go to enter always gives error even in Alpha wallet this is a major problem obviously should be fixed asap.

**Comment by hboon** [comment]
Can you point to a commit or an app store version which this doesn't work and the simplest way to reproduce (preferably including creating a wallet)? I tried on the app store version as of writing and key management works for me.

**Comment by hboon** [comment]
@Phinetwork is this not happening anymore?
