### ISSUE TITLE
Foreground color of "1D" label of charts is broken

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#4995]
It appears if we tap and hold it:

<img width="487" alt="Screenshot 2022-07-18 at 2 48 40 PM" src="https://user-images.githubusercontent.com/56189/179458033-1ada18d3-c850-46bc-ac9e-d2f9b31c40bb.png">

Probably broken by work on Dark Mode

**Comment by eviltofu** [comment]
Sorry for this oversight. I've fixed the issue at the UIButton level.
