### ISSUE TITLE
`self.promises[contract] = nil` in `fetchTokenOrContract(for:onlyIfThereIsABalance:)` might be wrong

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#4998]
Could this be wrong?

https://github.com/alphawallet/alpha-wallet-ios/blob/74d92639fdf85d3d38c3b4be94033d301c3ec4eb/AlphaWallet/Core/TokensAutodetector/TokenFetcher.swift#L68

**Comment by oa-s** [comment]
@hboon  not sure, does it cause some issues? Logically it should be ok. Make promise, cache it, once it get resolved release it

**Comment by hboon** [comment]
Oh, I see, the `promises` properties is a way to track inflight fetches and not a cache. No problem then. I created #5003
