### ISSUE TITLE
Check test suite

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#5040]
Tests seems to be broken. But I'm not sure why. Can you help to check by running locally @oa-s ?

This is for one the PRs:

https://app.travis-ci.com/github/AlphaWallet/alpha-wallet-ios/builds/253463201

But seems to happen on `master` (d6448bd84b0cf10a7f389111a98fd15418b8af37) too. The errors seems to be different for iOS 15.x and 14.x. 15.x seems to work better.

**Comment by hboon** [comment]
Just in case, it still crashes locally with master/3d5d7e8f070bb85f1ef68cca85b108f5bc704653 for me.

**Comment by oa-s** [comment]
trying to download 14.5 simulator, got only 13.5 and 15.5

**Comment by oa-s** [comment]
> trying to download 14.5 simulator, got only 13.5 and 15.5. Btw, what ios version are you using?

**Comment by hboon** [comment]
Do you mean Xcode? 13.3.1, as specified in `.xcode-version` :)

**Comment by oa-s** [comment]
i meant simulator version, oh i see checking
