### ISSUE TITLE
Issue with native swap

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#5043]
- [x] If I choose MATIC Polygon -> WETH, it says "Swap Pair Not Found".
- [x] MATIC Polygon -> USDC is better, and the Fees/Current Price/Minimum Received appears, but the To amount for USDC remains 0 and "Minimum Received" is "0.0000 USDC" too

If I choose ETH Ethereum -> USDC,

- [x] the fees says "0.1050 ETH". That sounds too high to be correct (my ETH balance is 0.1065, not sure if it's related)
- [x] "Current Price" shows "1 ETH = 0.0000 USDC"

Does the spillage and transaction deadline settings work?

**Comment by hboon** [comment]
Sorry, took a while to get back to testing this again

**Comment by oa-s** [comment]
not quite sure, i guess we pass these values as request params, will double check it

**Comment by oa-s** [comment]
> * If I choose MATIC Polygon -> WETH, it says "Swap Pair Not Found".
we got this error, as api call returns the next error: 
```
{
    errors =     (
    );
    message = "Unable to find a quote for the requested transfer.";
}
```

**Comment by oa-s** [comment]
params we trying to send:

**["toChain": 137, "fromToken": "0x0000000000000000000000000000000000000000", "fromAmount": "300000000000000000", "fromChain": 137, "toToken": "0x7ceB23fD6bC0adD59E62ac25578270cFf1b9f619", "fromAddress": "0xbbce83173d5c1D122AE64856b4Af0D5AE07Fa362", "slippage": "1.0"]**

**Comment by oa-s** [comment]
> * MATIC Polygon -> USDC is better, and the Fees/Current Price/Minimum Received appears, but the To amount for USDC remains 0 and "Minimum Received" is "0.0000 USDC" too

when we receive estimate response  toAmount = 168239;
        toAmountMin = 168239;
        toAmountUSD = "0.17";

**Comment by hboon** [comment]
If we are already doing it, can you point me to where I can find the `debugLog()` output for the URLs. If we aren't, add those? Then I can look at the URL and compare with what is observed in the UI while I test.

**Comment by oa-s** [comment]
> If we are already doing it, can you point me to where I can find the `debugLog()` output for the URLs. If we aren't, add those? Then I can look at the URL and compare with what is observed in the UI while I test.

[    func fetchSwapQuote(fromToken: TokenToSwap, toToken: TokenToSwap, wallet: AlphaWallet.Address, slippage: Double, fromAmount: BigUInt) -> AnyPublisher<SwapQuote, SwapError> {](https://github.com/AlphaWallet/alpha-wallet-ios/blob/d6448bd84b0cf10a7f389111a98fd15418b8af37/AlphaWallet/Swap/Helpers/TokenSwapperNetworkProvider.swift#L52)

**Comment by oa-s** [comment]
>  If I choose MATIC Polygon -> WETH, it says "Swap Pair Not Found".

looks like it happens because of parameter `slippage`, we send string value `1.0`, but with `1` works ok, will update code with removing trailing zeros from number.

**Comment by oa-s** [comment]
> MATIC Polygon -> USDC is better, and the Fees/Current Price/Minimum Received appears, but the To amount for USDC remains 0 and "Minimum Received" is "0.0000 USDC" too

there was an issue with formatting, missed case that some of tokens, has different `decimals` value.

**Comment by oa-s** [comment]
> Does the spillage and transaction deadline settings work?

we use `spillage` value, but not `transaction deadline`, didn't find request param for `transaction deadline`
