### ISSUE TITLE
Crash when running entire test suite. 11 Pro iOS 15.4 simulator Raw

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#5048]
Seems to be crashing randomly in Combine code.

https://gist.github.com/hboon/b5f761c17c091b8f0a77d9b77e72bdc1

**Comment by oa-s** [comment]
Lets wait for https://github.com/AlphaWallet/alpha-wallet-ios/pull/5047 first, looks like it fixes this issue. Need to double check it.
