### ISSUE TITLE
Reference to `.serverChange` in ActiveWalletCoordinator for all UI restarts doesn't seem right

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#5227]
```
func processRestartQueueAndRestartUI() {
        RestartQueueHandler(config: config).processRestartQueueBeforeRestart(restartQueue: restartQueue)
        restartUI(withReason: .serverChange, account: wallet)
    }
```

https://github.com/AlphaWallet/alpha-wallet-ios/blob/d0b89f5c5ef3dd24c216eb718558c9e2bc8eaf51/AlphaWallet/ActiveWalletCoordinator.swift#L525

**Comment by oa-s** [comment]
is the issue that, no matter who called method `processRestartQueueAndRestartUI ` function, it receiving `.serverChange` reason?

**Comment by hboon** [comment]
@oa-s yes.
