### ISSUE TITLE
Make a build so that the artifacts (jars for Android, frameworks for iOS) and their dependencies can be included in another project

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#5234]
* We can keep the UI, but not spin it up
* Make a dummy function in the code that signs a message
* Create a new skeleton driver project that uses this AlphaWallet project that includes something like this pseudocode:

```
import SDK
let wallet = SDK.Wallet("hardcoded seed phrase")
let result = wallet.signPersonal("some message")
let address = SDK.ecrecover(result)
print(wallet.address == address)
```

Goals
---
- [ ] Check feasibility
- [ ] Check constraints (including usage of dependencies, operating system requirements, build options)

**Comment by oa-s** [comment]
- [ ] - group types extension in model defition files
- [ ] - group models in related folders, (scattered on to many files)
- [ ] - group logic in (core) folder 
- [ ] - replace some definision to avoid adding additional dependencies, especially for (wallet connect, firebase) as modules added with spm.
- [ ] - move logic to pod

**Comment by oa-s** [comment]
out of steps above: 
we are going to have the next structure:
module like token, transactions, activities, settings, are going to stay in root project, as well as view model, and view definitions,  and the rest of code will be located in pod

**Comment by oa-s** [comment]
@hboon there is an issue with applying localization for enum cases or some description that were extracted to logic pod, as well as image usage, how to act in this case? how we could apply r.swift for pod, and where all of these resources should be?

**Comment by hboon** [comment]
> @hboon there is an issue with applying localization for enum cases or some description that were extracted to logic pod, as well as image usage, how to act in this case? how we could apply r.swift for pod, and where all of these resources should be?

Can we cope with adding them in class/type extensions in the main app? That'll be the easiest to manage localisations

**Comment by oa-s** [comment]
>  Can we cope with adding them in class/type extensions in the main app? That'll be the easiest to manage localisations

That is exactly what i am working on ;)

**Comment by hboon** [comment]
@oa-s is this issue closed yet? Only preparation work is done, right?

**Comment by oa-s** [comment]
looks like it could be closed

**Comment by hboon** [comment]
Also need this :) — https://github.com/AlphaWallet/alpha-wallet-ios/issues/5234#issue-1353682793

**Comment by hboon** [comment]
Forgot to assign earlier :P

**Comment by oa-s** [comment]
> Also need this :) — [#5234 (comment)](https://github.com/AlphaWallet/alpha-wallet-ios/issues/5234#issue-1353682793)

@hboon could you please explain, not so clear
