### ISSUE TITLE
Checkout text field text color, looks broken

### ISSUE THREAD

**Issue by oa-s** [AlphaWallet/alpha-wallet-ios#5236]
swap tokens screen

<img width="563" alt="Screenshot 2022-08-29 at 11 02 01" src="https://user-images.githubusercontent.com/96283950/187192424-6d0f6b7e-425f-431c-9253-3afa475e9156.png">

**Comment by eviltofu** [comment]
How do I get to this screen? @oa-s And which colours are wrong? What are the correct colours?

**Comment by hboon** [comment]
> How do I get to this screen? @oa-s And which colours are wrong? What are the correct colours?

Enable `.isSwapEnabled` in Features

1. tap ETH token
2. tap …
3. tap Swap
4. tap Native Swap
5. tap gear

If you look again before Vlad replies, you can compare it to the 

Expected|Observed
-|-
<img width="300" alt="Screenshot 2022-08-29 at 10 05 14 PM" src="https://user-images.githubusercontent.com/56189/187220768-c56e5b64-910d-4698-bd2d-6f2433b0b882.png">|<img width="300" alt="Screenshot 2022-08-29 at 10 08 06 PM" src="https://user-images.githubusercontent.com/56189/187220819-9258ba68-7e96-4ec2-8cbb-c1ac430a747d.png">

**Comment by eviltofu** [comment]
I checked out e50d0b168 (creation of `SwapOptionsViewController`) and 27cc8e1c1d79710508d736f489c01513aff69d4f (before my changes to TextField) and they both have this. Do you want me to remove the azure highlights?

![image](https://user-images.githubusercontent.com/1050309/187393355-05b0a5d0-4011-413f-bf36-d3ad8cd951ed.png)  ![image](https://user-images.githubusercontent.com/1050309/187396494-b80a177f-93db-40a7-b717-53f549a1ad6e.png)
