### ISSUE TITLE
Add GNO token being visible by default on Gnosis/Xdai

### ISSUE THREAD

**Issue by hieronymus4826** [AlphaWallet/alpha-wallet-ios#5239]
Hey @hboon,

I had a chat with Gnosis chain and they asked if we can add GNO (https://gnosisscan.io/token/0x9c58bacc331c9aa871afd802db6379a98e80cedb) to be visible by default when Gnosis/Xdai chain is selected - still keep the Xdai token (have both being visible even if the value is 0).

Is it possible to do it? Thank you!

**Comment by hboon** [comment]
It's easy and sensible, but wouldn't it already show up if the wallet has a non-zero GNO balance? Or do they want it to show up even when it is 0?

**Comment by hieronymus4826** [comment]
They want it to show natively even if its 0 (although its not the native token).

**Comment by hboon** [comment]
Yes of course.
