### ISSUE TITLE
Share SelectNetworkView (used in Swap screen settings) and the one used in EnabledServersViewController

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#5249]
i.e. share these 2:

Swap|Enable/disable server
-|-
<img width='300' src='https://user-images.githubusercontent.com/56189/187831517-c9d12654-d594-472e-8a79-af90d3fc859f.png'>|<img width="300" alt="Screenshot 2022-09-05 at 12 51 20 PM" src="https://user-images.githubusercontent.com/56189/188362884-786759f5-e888-4067-a945-9e80f8b550fd.png">

Or if the intention is to show they are single-selection or multi-selection, make it a single type that has a configurable display mode (for single vs multi-selection)

**Comment by oa-s** [comment]
could be not easy as there is server support validation

**Comment by hboon** [comment]
Just the cell-like row, not the entire screen or logic. Because it looks like `SelectNetworkView` is very similar to the cell in `EnabledServersViewController`. Have updated the title and first comment. Does that make sense?
