### ISSUE TITLE
List of missing images for dark mode 

### ISSUE THREAD

**Issue by eviltofu** [AlphaWallet/alpha-wallet-ios#5288]
There are some images which are required for dark mode. 

- [x] [#5267 Large logo](https://github.com/AlphaWallet/alpha-wallet-ios/pull/5267)

**Comment by eviltofu** [comment]
This is R.image.mascot_happy() in the art assets.

**Comment by eviltofu** [comment]
How do I close this issue? @hboon

**Comment by hboon** [comment]
Since there's nothing else, just close it.

**Comment by eviltofu** [comment]
Large logo still required for dark mode.

**Comment by hboon** [comment]
- [ ] Buzz #6468 when done
