### ISSUE TITLE
Fix crash with `GoBack` pod 

### ISSUE THREAD

**Issue by oa-s** [AlphaWallet/alpha-wallet-ios#5336]
https://console.firebase.google.com/u/0/project/alphawallet-ios-prod/crashlytics/app/ios:com.stormbird.alphawallet/issues/d4b71cd329e04060cd126d5c7dd63a43?time=last-thirty-days&types=crash&versions=3.49%20(447);3.49%20(446)&sessionEventKey=213e36fb8f1d48a0814d143eb4f24f25_1720420280847291594

**Comment by hboon** [comment]
@oa-s `UIApplication.shared.goBackToPreviousAppIfAvailable()` used to crash if there is no app to go back to. I can't get it to crash anymore. Tried with both building with Xcode 13 and 14. Can you?

You can try adding to `scanQRCodeButtonSelected:`

**Comment by oa-s** [comment]
i will try

**Comment by hboon** [comment]
@oa-s Is this still reproducible?

**Comment by oa-s** [comment]
looks like no, closing it for now
