### ISSUE TITLE
Dark mode: Secondary button background color (maybe title too?) wrong

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#5395]
<img width="487" alt="Screenshot 2022-09-16 at 12 53 44 PM" src="https://user-images.githubusercontent.com/56189/190559873-82ec68a1-4e8c-4166-b5bb-36f47cee8c51.png">

Should look more like this: https://zpl.io/a3J4611

**Comment by eviltofu** [comment]
I haven't worked on this screen yet? It's the result of other ui components being upgraded to handle dark mode.

**Comment by hboon** [comment]
> I haven't worked on this screen yet? It's the result of other ui components being upgraded to handle dark mode. Will do so now.

You are referring to #5394. This issue (#5395) just refers to the button

**Comment by eviltofu** [comment]
![image](https://user-images.githubusercontent.com/1050309/199383828-b5c47bd6-eb45-4363-a59c-25f6b50f64e3.png)

@hboon I followed the style guide. So confirm this the new secondary button colour scheme?

**Comment by eviltofu** [comment]
> Not sure why, but use this color zpl://screen?pid=5d0356be2f25b319dcc5944b&sid=61a0a7dfe3257a8be97aaf2b

How do I open this url?

**Comment by hboon** [comment]
Zeplin app

**Comment by hboon** [comment]
Web equivalent: https://zpl.io/a3J4611
