### ISSUE TITLE
Add Buy ETH button to bottom of Wallet tab

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#5398]
* Only if Ethereum mainnet is enabled
* Works like the "Buy" button when we tap "Buy" after tapping the ETH token > … > Buy

Something like Android's:

<img width='300' src='https://user-images.githubusercontent.com/56189/190570927-6888d41b-335a-474d-a482-47a75a10dc35.jpg'>
<img width='300' src='https://user-images.githubusercontent.com/56189/190570916-d000c2dd-3163-4176-bb7b-d24470eb609c.jpg'>

**Comment by hboon** [comment]
Actually a better reference: it is also available as "Buy Crypto" in Wallet > …

**Comment by oa-s** [comment]
any suggestions of how to make floating footer, to make it snap to content bottom, in case when content size is less then 
 table view frame, and snap it to table view's bottom when content size greater than frame height?

**Comment by hboon** [comment]
Not necessary I think. But if you want, make it float at the bottom if there is only < say 3 tokens ad adjust the table view inset?

**Comment by hboon** [comment]
@vladyslav-iosdev in case you forgot :)

**Comment by oa-s** [comment]
working on it, no success with its floating :(

**Comment by hboon** [comment]
Doesn’t have to float :)

**Comment by oa-s** [comment]
ok, making it to snap to table view bottom, found an issue when keyboard appears, working on it, will attach video of an issue
