### ISSUE TITLE
Update Unstoppable URL endpoint

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#5414]
Check Slack

- [x] Update
- [ ] Create Android issue

**Comment by oa-s** [comment]
@hboon can u point me on `Slack` thread?

**Comment by hboon** [comment]
@oa-s https://alphawalletworkspace.slack.com/archives/C030NJE8X5E/p1663640955406789

**Comment by hboon** [comment]
@oa-s have you helped to create the Android issue? If you haven't, can you help to do so?

**Comment by oa-s** [comment]
i sure i made one, have to check

**Comment by hboon** [comment]
Android: #2929
