### ISSUE TITLE
`The default Firebase app has not yet been configured. FirebaseApp.configure()` still happening when running tests

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#5420]
Was this what #5417 was trying to fix? :)

**Comment by oa-s** [comment]
it'v also happened before, we just skipped it

**Comment by hboon** [comment]
I mean #5417 doesn't didn't change anything, right?

**Comment by oa-s** [comment]
yes

**Comment by hboon** [comment]
> The default Firebase app has not yet been configured. Add `FirebaseApp.configure()` to your application initialization. This can be done in in the App Delegate's application(_:didFinishLaunchingWithOptions:)` (or the `@main` struct's initializer in SwiftUI). Read more: https://goo.gl/ctyzm8.

This one's still happening right?
