### ISSUE TITLE
Inconsistent usage of HTML Web Browser

### ISSUE THREAD

**Issue by eviltofu** [AlphaWallet/alpha-wallet-ios#5448]
When invoking the web browser, sometimes focus shifts to the Browser tab and sometimes it doesn't. For example Wallet tab > ... > Buy crypto and Wallet tab > ... > Swap

![Simulator Screen Shot - iPhone 12 - 2022-09-27 at 13 38 21 copy 2](https://user-images.githubusercontent.com/1050309/192441338-ea40bc29-c005-4d2f-b80d-db501ff22041.png) ![Simulator Screen Shot - iPhone 12 - 2022-09-27 at 13 38 47 copy 2](https://user-images.githubusercontent.com/1050309/192441335-33bfeb90-4a3b-4644-b328-49568761684d.png)

**Comment by hboon** [comment]
That's intentional. But will check back to make sure which uses which correctly.
