### ISSUE TITLE
Mark deprecated Testnets

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#5465]
Refer to [#2854](https://github.com/AlphaWallet/alpha-wallet-android/issues/2854)

**Comment by oa-s** [comment]
@hboon  What if we update retry logic, for not in case when we receive `execution reverted` error or any other error, we trying to retry it, we could do retrying only in case of some specific errors?

**Comment by hboon** [comment]
Are you referring to the backup nodes mentioned in the Android issue? If so, ignore those first.

But if you mean with the existing retry logic, I think we do check for specific error types. Do you mean to improve those?

**Comment by oa-s** [comment]
yes, i mean retrying logic for `getTokenType(` function, we could update it to avoid retrying when `execution reverted` for example, as sending same data will return same error.

**Comment by oa-s** [comment]
> Are you referring to the backup nodes mentioned in the Android issue? If so, ignore those first.

could you point me to this issue?

**Comment by hboon** [comment]
I'm sorry, I meant to link to the Android issue in the 1st comment of this issue. Have updated it. It should be https://github.com/AlphaWallet/alpha-wallet-android/issues/2854.

Ignore my comment about backup nodes too 😢 (it was referring to https://github.com/AlphaWallet/alpha-wallet-ios/issues/5466, and it's an iOS issue). Coffee!

**Comment by oa-s** [comment]
Yes, it should reduce a number of api calls (will update issue title, or create a new one)
