### ISSUE TITLE
Using Xcode 14 on M1 Mac - Build Documentation not compiling for iOS

### ISSUE THREAD

**Issue by geurtjens** [AlphaWallet/alpha-wallet-ios#5469]
name: Bug Report
about: Compiling newest version of AlphaWallet IOS

---

**Describe the bug**
Within Xcode 14 and using an M1 Mac Pro I am unable to compile the Build Documentation.  

It fails within the Pod file CombineExt. 

**Steps to reproduce (REQUIRED)**
1. Using the command line:
git clone https://github.com/AlphaWallet/alpha-wallet-ios.git
make bootstrap
pod install

2. Open the project by double clicking AlphaWallet.xcworkspace

3. Once the project is loaded into Xcode 14, click "Product" Menu -> "Build Documentation" menu item.

**Expect**
I expect it to create a help file that documents the entire system in a help file so I can better understand Alpha Wallet

**Observed**
Configuration Debug | Destination iPhone 14 Pro | SDK Simulator - iOS 16.0
CompileDocumentation (in target 'CombineExt' from project 'Pods')
    cd /Users/myusername/Developer/Experiments/alpha-wallet-ios/Pods
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/docc convert --index --fallback-display-name CombineExt --fallback-bundle-identifier org.cocoapods.CombineExt --fallback-bundle-version 1 --output-dir /Users/myusername/Library/Developer/Xcode/DerivedData/AlphaWallet-gcsrbirhovwvekfsznwmnqinpytm/Build/Products/Debug-iphonesimulator/CombineExt/CombineExt.doccarchive --emit-fixits --additional-symbol-graph-dir /Users/myusername/Library/Developer/Xcode/DerivedData/AlphaWallet-gcsrbirhovwvekfsznwmnqinpytm/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/CombineExt.build/symbol-graph

error: Symbol with identifier 's:So9NSDecimala10FoundationE11FormatStyleV8CurrencyV' couldn't be found
error: Symbol with identifier 's:So9NSDecimala10FoundationE11FormatStyleV7PercentV' couldn't be found
error: Symbol with identifier 's:So9NSDecimala10FoundationE11FormatStyleV7PercentV' couldn't be found
error: Symbol with identifier 's:So9NSDecimala10FoundationE11FormatStyleV8CurrencyV' couldn't be found
Error: An error was encountered while compiling documentation

**Screenshots**

<img width="723" alt="Screen Shot 2022-09-30 at 8 04 00 am" src="https://user-images.githubusercontent.com/69891975/193150301-07287c41-5c12-4294-b610-26148498e482.png">

**Version or build number number**
[master](https://github.com/AlphaWallet/alpha-wallet-ios) ([#5430](https://github.com/AlphaWallet/alpha-wallet-ios/pull/5430))

**Additional context (Error Messages, etc.)**
If this did work then it would be easier to create a help file which a programmer can use to better understand the IOS alpha wallet code.
<img width="723" alt="Screen Shot 2022-09-30 at 8 04 00 am" src="https://user-images.githubusercontent.com/69891975/193152881-9182aa83-6798-4a25-a8ab-c09c862879e1.png">

**Comment by hboon** [comment]
Hi, can you see if this works for you (and we'll figure out what's wrong):

```
git clone https://github.com/AlphaWallet/alpha-wallet-ios.git
cd alpha-wallet-ios/
#TODO: Create a file `.ruby-version` in the project root with the line: `3.0.3`, otherwise, somehow use Ruby `3.0.3`
bundle
bundle exec pod install
```

**Comment by geurtjens** [comment]
Homebrew previously would install 3.0.3 https://mac.install.guide/ruby/13.html but not anymore.  Homebrew now only installs the stable releases of ruby which are 3.1.2, 3.0.4, 2.7.6.

Here is the link to homebrew supported ruby https://formulae.brew.sh/formula/ruby

Here is the link to the stable releases from ruby language site https://www.ruby-lang.org/en/downloads/

I tried the next best thing ``brew install ruby@3.0`` which gives 3.0.4 but had same errors when I clicked ``Product->Build Documentation`` menu item in xcode 14.  Using ``brew install ruby`` gives me the latest stable version which is 3.1.2 and it doesn't work either.

I tried using ruby version manager https://rvm.io but it doesnt support ruby 3.0.3. So anyone getting the code may have difficulty installing 3.0.3 these days.

I wonder if version 3.0.3 does actually allow ``Product->Build Documentation`` menu item to compile the alpha wallet IOS project.  If it does then I will keep investigating how to install 3.0.3.

Please note that the actual project does compile and run but its this documentation feature of Xcode that doesn't work.  The documentation feature helps to explain how the project works by creating apple style documentation across all the code so it can be really helpful for new people starting to use the code base.

Please give it a try on your machine and if it works and you get new docc files then I will continue to try to install 3.0.3.

**Comment by geurtjens** [comment]
https://developer.apple.com/videos/play/wwdc2022/110368/

This is the WWDC2022 video describing Swift-Docc which is what ``Product->Build Documentation`` menu item creates.

**Comment by geurtjens** [comment]
Could this give another hint to what has happened.

When I run ``Xcodebuild docbuild`` I get the following error message:

Invalid Source '/Users/michaelgeurtjens/Library/Developer/Xcode/DerivedData/AlphaWallet-cratmskdghezidbiglabruneywwc/SourcePackages/checkouts/secp256k1.swift/secp256k1/Classes/secp256k1/modules/ecdh': File not found.Invalid Source '/Users/michaelgeurtjens/Library/Developer/Xcode/DerivedData/AlphaWallet-cratmskdghezidbiglabruneywwc/SourcePackages/checkouts/secp256k1.swift/secp256k1/Classes/secp256k1/modules/recovery': File not found.

**Comment by hboon** [comment]
> Please give it a try on your machine and if it works and you get new docc files then I will continue to try to install 3.0.3.

Oh, I'm sorry, we have never actually used that to build the docs. I can check.

But otherwise yes, 3.0.3 builds the app and tests.

**Comment by hboon** [comment]
Closing since it works with 3.0.3 + M1
