### ISSUE TITLE
Add TokenScript bridges for Optimism & Arbitrum Goerli testnets

### ISSUE THREAD

**Issue by JamesSmartCell** [AlphaWallet/alpha-wallet-ios#5482]
We can use TokenScript for the Bridges between Goerli -> Arbitrum/Optimism. The bridge works by depositing into the bridging contract:

Goerli -> Arbitrum: send a ```depositEth()``` function with value attached to ```0xaf4159A80B6Cc41ED517DB1c453d1Ef5C2e4dB72```

Goerli -> Optimism: send a ```depositETH(uint32 _l2gas, bytes _data)``` with value to ```0x636af16bf2f682dd3109e60102b8e1a089fedaa8```

_l2gas seems to be fixed as 0x30d40
_data can be zero length (I presume this is for a subsequent call)

I have confirmed these are working correctly by calling the functions and bridging directly via a call, see:

Arbitrum Swap:
https://goerli.etherscan.io/tx/0xad99cb74432f74e38f868f962dab47f6d5f651be63926b3f87be0cf09a3f1503

Optimism Swap:
https://goerli.etherscan.io/tx/0xceffbb7b313f34b32f951c4d531e376de572502468e91ef446bbdf5a992d7f50

Android project will get the scripts working and will attach here. Would work same as the old xdai bridge.

**Comment by hboon** [comment]
Closing for now
