### ISSUE TITLE
Add icons for Origin Protocol

### ISSUE THREAD

**Issue by hieronymus4826** [AlphaWallet/alpha-wallet-ios#5489]
Hello team,

We have a request to add the images for the Origin Protocol token suite to AW mapping for non-zero value assets.

The assets are on Ethereum Mainnet addresses:

OGN	0x8207c1FfC5B6804F6024322CcF34F29c3541Ae26	origintoken.eth	Origin Token
OUSD	0x2A8e1E676Ec238d8A992307B495b45B3fEAa5e86	ousd.eth	                Origin Dollar
wOUSD	0xD2af830E8CBdFed6CC11Bab697bB25496ed6FA62	wousd.eth	        Wrapped OUSD
OGV	        0x9c354503C38481a7A7a51629142963F98eCC12D0	ogv.eth                    Origin Dollar Governance
veOGV	0x0c4576ca1c365868e162554af8e385dc3e7c66d9	veogv.eth Vote Escrowed Origin Dollar Governance

and images can be found at: https://github.com/OriginProtocol/origin-website/tree/master/static/img/coins

Thank you!

**Comment by hboon** [comment]
- [ ] detect tokens
- [ ] icons

**Comment by hboon** [comment]
@hieronymus4826 added icons and the tokens should already be autodetected when they have non-zero balances
