### ISSUE TITLE
PHI Network v2 gas price

### ISSUE THREAD

**Issue by Phinetwork** [AlphaWallet/alpha-wallet-ios#5492]
Hello great job integrating phi v2 smart chain you are amazing. Just need to update phi network v2 is defaulting at 1 gwei for the gas fees need the default of gas fees like you did on the v1 chain the default of 1 gwei is too high for chain

**Comment by Phinetwork** [comment]
> Hello great job integrating phi v2 smart chain you are amazing. Just need to update phi network v2 is defaulting at 1 gwei for the gas fees need the default of gas fees like you did on the v1 chain the default of 1 gwei is too high for chain

So for sending the gas fees are correct but for using dapps in browser it is defaulting to 1 gwei can we check this

**Comment by hboon** [comment]
@Phinetwork can you help share an example dapp that we can verify against?

**Comment by Phinetwork** [comment]
> @Phinetwork can you help share an example dapp that we can verify against?

Yes got you thanks @hboon for looking into this 

 can try 

https://app.phi.exchange 

When we test using dapp gives 1 gwei as gas fee but when send it gives proper gas fee seems to only be the dapp browser.

**Comment by hboon** [comment]
@Phinetwork thanks!
