### ISSUE TITLE
Ethereum merge has shut down many test nets that are still in the app

### ISSUE THREAD

**Issue by geurtjens** [AlphaWallet/alpha-wallet-ios#5517]
name: Bug Report
about: The default test net is Ropsten but that's now shut down

---

**Describe the bug**
I tried to access the faucet for Ropsten https://faucet.ropsten.be but its been shutdown.
In fact as few test nets for ethereum seem to be shutdown including Kovan.
So they probably don't need to be in the app anymore.

Maybe default to Goerli which is the next one from the top.

This is a result of the Merge that made ethereum go to proof of stake.

**Comment by hboon** [comment]
@geurtjens thanks for the feedback. Yes, we have switched to Goerli as our testnet default with #5280. This should be live in th app store already.

We also have a change that marks those testnets as deprecated but it isn't live yet: #5471
