### ISSUE TITLE
Add main phi20 tokens logos

### ISSUE THREAD

**Issue by Phinetwork** [AlphaWallet/alpha-wallet-ios#5521]
Hello can we add the logos for the major tokens (Usdc, usdt, matic, bnb, etc.) on phi smart chain. Tokens show but the logos don't show thank you.

Screenshot attached so u can see what we are referring too. ![image](https://user-images.githubusercontent.com/85964511/194478871-a927efd1-f2fe-4eaa-92fa-e473fe55b757.jpeg)

**Comment by Phinetwork** [comment]
Is this something we can do for next update @hboon

**Comment by Phinetwork** [comment]
@hboon  can we add these

**Comment by hboon** [comment]
@Phinetwork oh yes, let me look into this, was preparing and updated our token collection earlier.

**Comment by hboon** [comment]
@Phinetwork can you help to paste the address and the PNG (180x180) icons for each? But is there an exchange where they can be bridged to/fro the ones on Ethereum mainnet?

**Comment by Phinetwork** [comment]
> @Phinetwork oh yes, let me look into this, was preparing and updated our token collection earlier.

Ok awesome thanks.

**Comment by Phinetwork** [comment]
> @Phinetwork can you help to paste the address and the PNG (180x180) icons for each? But is there an exchange where they can be bridged to/fro the ones on Ethereum mainnet?

Yes what folder does the contract address with the image go into will help add this as a pull request just need to know where it goes. Also there is a decentralized crosschain swap can see the bridge here. It's set up for BSC & polygon ethereum will be added in the future for now because of lower gas fees BSC & polygon are the chains that are used on the crosschain swap. 

 https://bridge.phi.network

**Comment by hboon** [comment]
You can just drop the images here.

**Comment by Phinetwork** [comment]
![0xE0195eA0A07b5835B6ECFa87f10DB37f603dEB02](https://user-images.githubusercontent.com/85964511/197373725-a685afb4-016e-4125-afd7-87f77123ecd4.png)
![0xBF5cFf4ABa4d2bf966D75fA60790C3E4eafb62e1](https://user-images.githubuserconte
![0xEab62CB353E1A570005452b91eD030f9C047370E](https://user-images.githubusercontent.com/85964511/197373747-f8a8e3c3-e010-40fc-b755-733645188a2d.png)
nt.com/85964511/197373
![0x6C963ecbB25a55cf663879
![0x9127cE46F4DcC340a5a57AF2f310Eb7340AB758b](https://user-images.githubusercontent.com/85964511/197373815-87720ecc-c3da-4437-b66d-e0c3354c5e25.png)
F13f
![0x3F357eab55501d5da6606B1A54A8d4f32AB8283F](https://user-images.githubusercontent.com/85964511/197373801-d75759e0-af0d-4da0-9ab4-a9abbeb799bf.png)
9EE282Cf89898A](https://user-images.githubusercontent.co
![0x8775b3A679d6e46035BB3aC715A17EB7472C649A](https://user-images.githubusercontent.com/85964511/197373784-9b705768-da9d-4178-ab0d-1e8a7f3f44e3.png)
m/85964511/197373776-36de16eb-a119-40e5-95e6-7709015b89f8.png)
741-0f974eb4-daee-429a-ab93-3f32e90bf6e1.png)
![0x85Bad89e8EbCB3b54D88C2DA22f30855A5fA5B59](https://user-images.githubusercontent.com/85964511/197373854-7ed7cfae-d2d0-435e-9462-60cb797e2faf.png)
![0xe59f2365d761711C264a58F1042ec225F029a910](https://user-images.githubusercontent.com/85964511/197373937-a706ab3d-b0e3-44ce-a387-7ab781c9f12d.png)
![0xBF5cFf4ABa4d2bf966D75fA60790C3E4eafb62e1](https://user-images.githubusercontent.com/85964511/197373950-98093e57-f064-46fa-8932-723025fd8a96.png)
![0x6C963ecbB25a55cf663879F13f9EE282Cf89898A](https://user-images.githubusercontent.com/85964511/197373956-dcf23503-8633-4c13-a2ef-ef8a6d25ee6c.png)

**Comment by Phinetwork** [comment]
![0x9127cE46F4DcC340a5a57AF2f310Eb7340AB758b](https://user-images.githubusercontent.com/85964511/197374027-ba8cc32f-d46d-4315-9328-bacac54748c5.png)
![0xe59f2365d761711C264a58F1042ec225F029a910](https://user-images.githubusercontent.com/85964511/197374028-28195345-4829-4f0b-9701-376e771f0a30.png)
![0x3F357eab55501d5da6606B1A54A8d4f32AB8283F](https://user-images.githubusercontent.com/85964511/197374029-983f7c55-af44-4e96-a5ce-a66823b40826.png)
![0x6C963ecbB25a55cf663879F13f9EE282Cf89898A](https://user-images.githubusercontent.com/85964511/197374030-f9e32d56-c748-4f12-b592-be91c2b4e1c1.png)
![0x8775b3A679d6e46035BB3aC715A17EB7472C649A](https://user-images.githubusercontent.com/85964511/197374032-f6d3ceb2-17a3-4fc9-84aa-009ec1f1f229.png)
![0xBF5cFf4ABa4d2bf966D75fA60790C3E4eafb62e1](https://user-images.githubusercontent.com/85964511/197374033-8f18dab8-034b-41fa-abc0-632679be87bc.png)
![0xD09d29e984580936D9De6951D28F136B4B866b53](https://user-images.githubusercontent.com/85964511/197374034-7ad43316-a816-4fe1-bdcb-4809ffed9ce1.png)
![0xEab62CB353E1A570005452b91eD030f9C047370E](https://user-images.githubusercontent.com/85964511/197374035-4e26f7c2-6a2e-41a2-a2b3-cecffc533bce.png)
![0xE0195eA0A07b5835B6ECFa87f10DB37f603dEB02](https://user-images.githubusercontent.com/85964511/197374036-dff74c83-46b6-49bf-99ae-47cb760146c4.png)
![0xAFD8806948AE6049d032215e94491DaCd8b396B4](https://user-images.githubusercontent.com/85964511/197374038-09cc8ac9-f91a-4d34-ba22-1e1fa7ce82c0.png)

**Comment by Phinetwork** [comment]
the addresses are attached to the image name can not tell if they are correct after uploading. https://phi.icu/drive/s/W1JXKFaTQlDM1fhuHVw5q9u32fWVNP

can also download from this link that has the contract address attached as the png name

**Comment by Phinetwork** [comment]
Did the logos work for you? @hboon

**Comment by hboon** [comment]
@Phinetwork away for a bit, will get back to this in a week+

**Comment by Phinetwork** [comment]
> @Phinetwork away for a bit, will get back to this in a week+

Ok awesome thanks for updates along with the logos the price will display for tokens like Usdc usdt busd as well right. On certain phones like the iPhone 11 & 13 seems to display price for certain tokens like usdc but the iPhone 12 only display value for phi. Is there a way that we can display the token value for all the tokens sent with the logos no matter what device.

**Comment by Phinetwork** [comment]
> @Phinetwork away for a bit, will get back to this in a week+

Where we able to get this added for the next update @hboon hope your doing great & had a nice time away.

**Comment by hboon** [comment]
@Phinetwork done!

**Comment by Phinetwork** [comment]
> @Phinetwork done!

Thank you can we also add the BCH logo as well as see why phi20 transactions are going now to contract address rather then destination wallet.

**Comment by hboon** [comment]
The transfer issue is fixed in #5812. We have a hotfix pending approval and it will also be merged into `master`
