### ISSUE TITLE
Gas warning does not go away when other options are selected in ConfigureTransactionViewController

### ISSUE THREAD

**Issue by eviltofu** [AlphaWallet/alpha-wallet-ios#5533]
In the main wallet tab tap `ETH > Send > Edit > Custom` then adjust the gas price to max and then select one of the other preset options. The gas warning should go away and the gas information text should be restored.

https://user-images.githubusercontent.com/1050309/195029392-01e16bdb-0880-4dd1-b46e-980f7efaf81f.mp4

**Comment by oa-s** [comment]
Gas warning is displaying for edited gas price, that how it should be

**Comment by hboon** [comment]
@oa-s but it makes sense that the warning should go away if the user do this with EIP-1559 disabled:

1. Tap edit in confirmation actionsheet
2. Tap Custom
3. Make high gas price. High Gas Price warning shown
4. Tap Slow.

The High Gas Price Price warning should be hidden as Custom is no longer selected. It ought to appear again if Custom is selected again (and only if the gas price is still considered high though)

**Comment by oa-s** [comment]
Will double check it

**Comment by oa-s** [comment]
since we save selected gas configuration once `save` button selected the `Gas Warning` will be presented, do we need to save gas price once it selected? then `save` button makes no sence

**Comment by hboon** [comment]
I don't understand, can you elaborate? It might be possible to remove the Save button, but currently, if we tap on custom to edit the gas and then tap the `X` button, the gas values as well as the "type" (like Custom vs Average) isn't saved.

**Comment by oa-s** [comment]
once user open configure gas price screen he is able to select any available gas price configuration or open edit custom gas price configuration. selection gas price configuration doesn't save it as selected one, saving gas price configuration performs only we tap a `save button`. Even use has selected any of gas price configurations and  tap `x` button, configuration wouldn't be saved.

**Comment by hboon** [comment]
```
on_change_gas
    update_warnings()

on_change_selection
    update_warnings()

func update_warnings()
    if let current_selection = current_selection, current_selection.gas_price > HIGH_VALUE
        show_warning()
    else
        //no-op
    end
```
