### ISSUE TITLE
Remove accessory type from select token screen

### ISSUE THREAD

**Issue by oa-s** [AlphaWallet/alpha-wallet-ios#5538]
Remove accessry type for cells, anyway once token selected we dismiss a screen
<img width="565" alt="Screenshot 2022-10-11 at 14 06 46" src="https://user-images.githubusercontent.com/96283950/195076826-717baedf-0d29-4dc2-b5b9-4ec389eef0b8.png">

**Comment by hboon** [comment]
@oa-s how do you navigate to that state in your screenshot above? For me the `Select Asset` screen goes away before the actionsheet is shown.
