### ISSUE TITLE
Write test for `Data.init(_hex:,chunkSize:)` with different `chunkSize` values

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#5547]
https://github.com/AlphaWallet/alpha-wallet-ios/blob/52081f6e986dbd33c5c76d66cc42907585d95ffb/modules/AlphaWalletFoundation/AlphaWalletFoundation/Extensions/Data.swift#L25

Also, what does `chunkSize` actually do?

**Comment by oa-s** [comment]
chunkSize splits passed string into array with n elems, to avoid crash when screating Data object, it heppens when we trying to create data from large hex string. in case i am not mistaking.

**Comment by hboon** [comment]
@oa-s so it doesn't change the result right? Maybe we can then make it a local var in the initializer instead? Clearer

**Comment by oa-s** [comment]
not quite sure in this init method, looks like it returns different results, if we pass different chunk size value, will remove this method and left `public init(_hex value: String)`

**Comment by oa-s** [comment]
btw, when we pass a value to init method `init(_hex value: String)` do we need to drop `0x` prefix from hex string?
we got extention property

public var toHexData: Data {
        if self.hasPrefix("0x") {
            return Data(_hex: self)
        } else {
            return Data(_hex: self.hex)
        }
    }

self.hex returns hex string without  `0x` prefix, so for `toHexData` it might be calculated wrong, as sometime it has `0x` and some time its not

**Comment by hboon** [comment]
@oa-s in case you missed it, remember to review and merge #5548. It renames `toHexData` so it's clearer what it does (and it's quite an important function)

**Comment by hboon** [comment]
> `self.hex` returns hex string without `0x` prefix, so for `toHexData` it might be calculated wrong, as sometime it has `0x` and some time its not

It treats both with and without "0x" as the same. In:

```
    public init(_hex hex: String) {
        let len = hex.count / 2
        var data = Data(capacity: len)
        for i in 0..<len {
            let from = hex.index(hex.startIndex, offsetBy: i*2)
            let to = hex.index(hex.startIndex, offsetBy: i*2 + 2)
            let bytes = hex[from ..< to]
            if var num = UInt8(bytes, radix: 16) {
                data.append(&num, count: 1)
            }
        }
        self = data
    }
```

this filters away the "0x":

```
            if var num = UInt8(bytes, radix: 16) {
                data.append(&num, count: 1)
            }
```

---

A simple test:

After cherry picking #5548 and adding to `Data` to mirror #5561:

```
    public var asSignableMessageDataWithoutChunkSize: Data {
        if self.hasPrefix("0x") {
            return Data(_hex: self)
        } else {
            return Data(_hex: self.hex)
        }
    }
```

It seems to work as expected:

```
infoLog("xxx \("0xab".asSignableMessageData.hex())") //"ab"
infoLog("xxx \("ab".asSignableMessageData.hex())") //"6162"
infoLog("xxx \("0xab".asSignableMessageDataWithoutChunkSize.hex())") //"ab"
infoLog("xxx \("ab".asSignableMessageDataWithoutChunkSize.hex())") //"6162"
infoLog("xxx \(Data(_hex: "0x61").hex())") //61
infoLog("xxx \(Data(_hex: "0x6162").hex())") //6162
infoLog("xxx \(Data(_hex: "61").hex())") //61
infoLog("xxx \(Data(_hex: "6162").hex())") //6162
```

**Comment by hboon** [comment]
Probably should add a testcase for `Data.init(_hex:)` to verify that behavior ("0x61" vs "61") above though, so we don't break it.

**Comment by oa-s** [comment]
that its ok
