### ISSUE TITLE
Crash with ERC1155 token IDs fetching

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#5550]
https://console.firebase.google.com/u/0/project/alphawallet-ios-prod/crashlytics/app/ios:com.stormbird.alphawallet/issues?time=last-seven-days&state=open&tag=all

**Comment by hboon** [comment]
@oa-s no idea what could be the problem it's in "functional" parts where it doesn't read/write from the filesystem nor any shared objects

**Comment by hboon** [comment]
How do you figure it's an overflow?

**Comment by oa-s** [comment]
also i catched overflow crash 
<img width="1840" alt="Screenshot 2022-10-13 at 11 43 21" src="https://user-images.githubusercontent.com/96283950/195548133-3a870ec1-d972-45ee-904a-660146dfd6de.png">
