### ISSUE TITLE
Replace infuraKey

### ISSUE THREAD

**Issue by wangaojie001** [AlphaWallet/alpha-wallet-ios#5557]
When I put the infuraKey replacement for myself when applying for the infuraKey, network request will appear responseError (APIKit. ResponseError. UnacceptableStatusCode (403)) this error, How should the problem be solved?

**Comment by hboon** [comment]
@wangaojie001 can you see if the HTTP response body gives a clue? Which chain are you connecting to?

**Comment by wangaojie001** [comment]
Already solved, just add polygon request permission to infura
