### ISSUE TITLE
hashValue of AlphaWallet.Address isnt same as (AlphaWallet.Address).eip55String.hashValue

### ISSUE THREAD

**Issue by oa-s** [AlphaWallet/alpha-wallet-ios#5565]
we got a crash https://console.firebase.google.com/u/0/project/alphawallet-ios-prod/crashlytics/app/ios:com.stormbird.alphawallet/issues/fc4da6df13d5e074b565fbd94434da38?time=last-seven-days&sessionEventKey=b4c49ca7ce344aa2822236d1b724f984_1730543674198288879

looks like its because of something wrong with hash calculation for addess value, not sure.
https://www.google.com/search?q=RawDictionaryStorage+find+hashValues&rlz=1C5CHFA_enUA906UA907&oq=RawDictionaryStorage+find+hashValues&aqs=chrome..69i57j33i10i160l3.42871j0j7&sourceid=chrome&ie=UTF-8

maybe we need to update calculatiin hash value from eip55String for address, because for now thaey are not the same
`address4.eip55String.hashValue != address4.hashValue`
`let address4 = AlphaWallet.Address(string: "0xA66A3F08068174e8F005112A8b2c7A507a822335")!`
```
(lldb) po address4.hashValue
-7618891263693548981

(lldb) po address4.eip55String.hashValue
-4218596858909156390
```

@hboon any suggestions?

**Comment by hboon** [comment]
Yeah. Can’t expect it to be the same. I haven’t checked yet; but why are they compared against each other?

**Comment by oa-s** [comment]
sorry that is the reason of the crash,  realized that its somewhere in other place ens pod i guess

**Comment by hboon** [comment]
Are we are to reproduce it? Shouldn't happen since they are of different type?

**Comment by oa-s** [comment]
i am not able to reproduce it

its out of crash log, (missed it before): `AlphaWalletENS.getName(fromAddress:`
```
1
AlphaWalletENS
$s14AlphaWalletENS0C0C7getName11fromAddress7Combine12AnyPublisherVySSAA18SmartContractErrorOG0abG00aB0O0G0O_tFAHySDySSypGAJGAQcfU_ + 96
2
AlphaWalletENS
$s14AlphaWalletENS0C0C7getName11fromAddress7Combine12AnyPublisherVySSAA18SmartContractErrorOG0abG00aB0O0G0O_tFAHySDySSypGAJGAQcfU_TA + 48
```

**Comment by hboon** [comment]
Hmm.. could be just the subscripting in one of these 2 lines too?

```
guard let resolverEthereumAddress = result["0"] as? EthereumAddress else {

//…

guard let ensName = result["0"] as? String, ensName.contains(".") else {
```

Is the dictionary read thread-safety broken?

It only seem to happen once, so let's not do anything unless it pops up again.

**Comment by oa-s** [comment]
guess no, there is local copy of `result`, definatelly threadsafe

**Comment by oa-s** [comment]
closing this issue for now, looks the reason is in something else
