### ISSUE TITLE
Evaluate if `CachedERC1155ContractDictionary` and its usage is optimal and improve if necessary

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#5579]
A few considerations:

* Does it cache only results we are sure of (i.e not `false` due to network connectivity issues)
* Should we include `RPCServer` as the key, so it's address+chain

Followups:

- [ ] Rename it so it can be used for other token types
- [ ] Use it for other token types

**Comment by oa-s** [comment]
We can actually update `IsInterfaceSupported165` and cache values there, then we wouldn't need to apply caching for each class that is use `IsInterfaceSupported165`

**Comment by hboon** [comment]
Yeah, even better!
