### ISSUE TITLE
Will this project upgrade from Bigint 3.0 to Bigint 5.0?

### ISSUE THREAD

**Issue by beckyzhang** [AlphaWallet/alpha-wallet-ios#5588]
name: Question about libary version upgrade
about: 

This project has the library of Bigint 3.0. Will it upgrade to Bigint 5.0?

**Comment by hboon** [comment]
@beckyzhang not familiar with what has changed from v3->5. Is there something useful?

**Comment by beckyzhang** [comment]
> @beckyzhang not familiar with what has changed from v3->5. Is there something useful?
The project is using a libary of bigint v3.0. The latest version of this libary is 5.0. Will this project plan to upgrade?

**Comment by beckyzhang** [comment]
@hboon The project is using the Bigint libary in v3.0. The latest version of this libary is 5.0. Will this project plan to upgrade?
