### ISSUE TITLE
Project fails to compile on command line for master branch commit 29d59b40754eaaf8f66bfca65b24d502e7008329

### ISSUE THREAD

**Issue by eviltofu** [AlphaWallet/alpha-wallet-ios#5595]
new git clone followed by make bootstrap && make test fails on master commit 29d59b40754eaaf8f66bfca65b24d502e7008329 

```Resolve Package Graph
xcodebuild: error: Could not resolve package dependencies:
  Couldn’t check out revision ‘cb8dfc428ec70499a585c43e33a5e5c695b135a2’:
    fatal: reference is not a tree: cb8dfc428ec70499a585c43e33a5e5c695b135a2
  an out-of-date resolved file was detected at /Users/jerome/Desktop/nuke/alpha-wallet-ios/AlphaWallet.xcworkspace/xcshareddata/swiftpm/Package.resolved, which is not allowed when automatic dependency resolution is disabled; please make sure to update the file to reflect the changes in dependencies. Running resolver because the following dependencies were added: 'walletconnectswift' (https://github.com/AlphaWallet/WalletConnectSwift.git)
  fatalError
```

**Comment by oa-s** [comment]
https://github.com/AlphaWallet/alpha-wallet-ios/commit/29d59b40754eaaf8f66bfca65b24d502e7008329 doesn't change dependencies urls

**Comment by eviltofu** [comment]
Removing `-disableAutomaticPackageResolution` from the build command resolves this issue.
`xcodebuild -workspace AlphaWallet.xcworkspace -scheme AlphaWallet -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 12,OS=latest' test | ./Pods/xcbeautify/xcbeautify`

**Comment by eviltofu** [comment]
> [29d59b4](https://github.com/AlphaWallet/alpha-wallet-ios/commit/29d59b40754eaaf8f66bfca65b24d502e7008329) doesn't change dependencies urls

```
git clone https://github.com/AlphaWallet/alpha-wallet-ios.git
cd alpha-wallet-ios
make bootstrap && make test
```
gives me the xcodebuild error. @oa-s
