### ISSUE TITLE
Fix NFT token image background color in dark mode

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#5608]
Maybe it's an HTML?

Remember that users can toggle Light/Dark mode on the device and the app will switch modes without restarting, unlike on the simulator
 
<img width="200" alt="Screenshot 2022-10-19 at 10 39 48 AM" src="https://user-images.githubusercontent.com/56189/196584699-16edde76-26d8-45ce-9189-846acedde237.png">
<img width="200" alt="Screenshot 2022-10-19 at 10 54 48 AM" src="https://user-images.githubusercontent.com/56189/196586838-9b864fd0-b124-45f5-9fd2-63175aff3b8b.png">

**Comment by oa-s** [comment]
I will check it

**Comment by hboon** [comment]
When you are back? Not now :)
