### ISSUE TITLE
Fix dark mode for cell in Activity tab for pending transaction

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#5614]
Send a transaction to reproduce.

<img width="487" alt="Screenshot 2022-10-19 at 2 30 53 PM" src="https://user-images.githubusercontent.com/56189/196614022-d6568122-e950-4d43-82fb-d6325e22fdc5.png">

**Comment by eviltofu** [comment]
What should the correct color for dark mode be?
```swift
        if activityStateViewViewModel.isInPendingState {
            return R.color.azure_sending()!
        } else {
            return .white
        }
```
is the code which determines the colour. (DefaultActivityCellViewModel.swift:20)
azure_sending is #E6F3FF.
@hboon

**Comment by hboon** [comment]
#323250 (though we will tweak this later, but use it for now)
