### ISSUE TITLE
Support dark mode for Tokenscript Overrides screen

### ISSUE THREAD

**Issue by eviltofu** [AlphaWallet/alpha-wallet-ios#5629]
Tap `Settings > Advanced > Tokenscript Overrides`. The screen is blank. 
If there are no overrides, the screen should indicate there are no overrides. Right now I am not sure if there is a bug or there are no overrides.

456ceb587dc99a54f4d838955a6e99ef8b1b2221 of master branch.

![Simulator Screen Shot - iPhone 13 - 2022-10-21 at 10 44 38 copy](https://user-images.githubusercontent.com/1050309/197099659-66f25f8e-6986-412c-afcf-d84fc18021c2.png)

**Comment by hboon** [comment]
@eviltofu no overrides by default. You can look at the view controller to mock up something to add dark mode support (it could be faster than getting it to show up something real)
