### ISSUE TITLE
Private ETH Transactions screen allowing multiple selections

### ISSUE THREAD

**Issue by eviltofu** [AlphaWallet/alpha-wallet-ios#5630]
Tap `Settings > Advanced > Private ETH`.
Tap the first option. The first option is selected.
Tap the second option. The first and second options are selected.
Tap the back arrow.
Tap Private ETH. Only the second option is selected.

What should correct behaviour be? The last one selected or both selected?

456ceb587dc99a54f4d838955a6e99ef8b1b2221 of master branch.

![Simulator Screen Recording - iPhone 13 - 2022-10-21 at 10 59 13](https://user-images.githubusercontent.com/1050309/197101376-08a57736-d829-40c3-adbe-6aed9381ca10.gif)

**Comment by hboon** [comment]
@eviltofu last. Only these are valid state:

A. 1 selection
B. 0 selections
