### ISSUE TITLE
Explore code formatter

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#5638]
Maybe SwiftFormat (https://github.com/nicklockwood/SwiftFormat) ? Open to others.

But basically, something that:

* Low effort and maintenance to use
* Can be ready to use without too much time and work tweaking rules
* Preserves our lines when running our code, spaces can be added or removed, but if a code is currently 1 line, it shouldn't be broken into 2 (eg. we don't wrap long lines, keep it that way)
* Be able to ad-hoc run and format specific file(names) and directories
* Can run as git commit pre-hook
* Be able to mark files to format or ignore, so we can start with 0 files modified and as we create PRs, add a commit to format the modified files so that after a while all the code is formatted

PS: Don't do `swiftformat .`. Don't run it on the `Pods` directory…

**Comment by oa-s** [comment]
not clearly understand why do we need this? its kind of swiftlint? haven't seen this before

**Comment by hboon** [comment]
It's a little like lint tools, but more towards asthetics, purely formatting, whereas lint is more for functionality and idiomatic code style. For example, you can configure code formatting tools to always lay out properties in this order — private, public or functions in this order — public, internal private. Wrap at max 80 char columns lines, order of import statements etc.

Whether it ends up prettier is subjective, but it helps to reduce the effort to make sure the spaces/tabs are the same when we edit. So end up with a smaller diff.

It's not terribly important for us now as we are more familiar with our repo's code formatting, so a quick look if it's mostly good for us out of the box. It is useful every time we add a new member or have PRs from external contributors though so we would have to look at it sooner or later.

**Comment by eviltofu** [comment]
SwiftFormat can be installed via cocoa pods so our makefile process should be able to handle it.
It can be run as a Xcode build phase.
It can run on the command line so a pre-hook could be done provided SwiftFormat is installed via make bootstrap.
It can exclude directories to process on the command line.
