### ISSUE TITLE
Dapp browser freezing and acting buggy

### ISSUE THREAD

**Issue by Phinetwork** [AlphaWallet/alpha-wallet-ios#5645]
Just a heads up The dapp browser is freezing many times and acting buggy even on the newest iOS update. @hboon

**Comment by hboon** [comment]
Thanks for reporting. Is there a particular dapp or something that can reproduce it more easily? Which device and iOS version are you running it on?

**Comment by Phinetwork** [comment]
> Thanks for reporting. Is there a particular dapp or something that can reproduce it more easily? Which device and iOS version are you running it on?

iPhone 13 15.7 iOS been having this issue anytime use any dapp going back and forth between wallet & dapp browser or when do multiple swaps on any dex it starts to freeze it was not ever doing this before has been a new issue only over the past couple days.

**Comment by Phinetwork** [comment]
It has been working better tonight than it has for the past few days which is odd because it is the same version with no change was freezing constantly now it's working smooth. I will keep using more and let you know what find.

**Comment by Phinetwork** [comment]
> It has been working better tonight than it has for the past few days which is odd because it is the same version with no change was freezing constantly now it's working smooth. I will keep using more and let you know what find. 

When change between networks it usually always freezes. And sometimes when it opens it deselects the chains you have selected and goes back to ethereum being enabled by itself.
