### ISSUE TITLE
Upgrade to send transactions with EIP-1559 protocol

### ISSUE THREAD

**Issue by beckyzhang** [AlphaWallet/alpha-wallet-ios#5733]
name: Upgrade to send transactions with EIP-1559 protocol
about: Using AlphaWallet to send transactions with EIP-1559 protocol

---

**Describe my question**
Can we modify the project code to support sending transactions with EIP-1559 protocol? Or, it will upgrade and when is it?

**Comment by hboon** [comment]
Thanks for the interest. There's issue #4138 and a PR which is WIP at #5172 for adding EIP-1559. Closing this as duplicate of #4138
