### ISSUE TITLE
SwiftFormat warning message "SwiftFormat not installed, download from https://github.com/nicklockwood/SwiftFormat"

### ISSUE THREAD

**Issue by eviltofu** [AlphaWallet/alpha-wallet-ios#5734]
When running `make test` the following warning message was displayed.

```
[AlphaWallet] Running script Swift Format
⚠️ SwiftFormat not installed, download from https://github.com/nicklockwood/SwiftFormat
```
The build phase in Xcode is
```
if which swiftformat >/dev/null; then
  #swiftformat .
    echo "warning: SwiftFormat is disable for now"
else
    echo "warning: SwiftFormat not installed, download from https://github.com/nicklockwood/SwiftFormat"
fi
```
`which` cannot detect the presence of `swiftformat` unless the pod file directory is included in the shell search path. 

The SwiftFormat install page suggests:
`"${PODS_ROOT}/SwiftFormat/CommandLineTool/swiftformat" "$SRCROOT"`

However, this command changes a lot of files (over 1200). @hboon

**Comment by hboon** [comment]
@eviltofu would  you help check if this is still reproducible?

**Comment by eviltofu** [comment]
> @eviltofu would you help check if this is still reproducible?

@hboon does not seem to be reproducible.

**Comment by hboon** [comment]
Thanks
