### ISSUE TITLE
Fix LocalizedOperationObjectInstance duplication

### ISSUE THREAD

**Issue by oa-s** [AlphaWallet/alpha-wallet-ios#5746]

**Comment by oa-s** [comment]
@hboon is there any way to identify `LocalizedOperationObjectInstance`, to make it unique? some kind of primary key

**Comment by hboon** [comment]
@oa-s not don't think there's one directly from the source since we pull and compose instances from multiple sources. Why do we need a key? Can't we always recreate the entire list? That's how we do it now right?

**Comment by oa-s** [comment]
i found some duplication in `LocalizedOperationObjectInstance`, that is why i suppose we received crashes on activities.

**Comment by oa-s** [comment]
> Can't we always recreate the entire list?
can try it
