### ISSUE TITLE
UI glitch (stuttering in screen transition) when sending testnet ethereum

### ISSUE THREAD

**Issue by eviltofu** [AlphaWallet/alpha-wallet-ios#5752]
Tested on iPhone 14 Pro hardware.

https://user-images.githubusercontent.com/1050309/200504738-8e928073-0483-4858-9952-600099868590.mov

**Comment by hboon** [comment]
What's the glitch? The spurious border around the textbox?

**Comment by hboon** [comment]
BTW, don't have to assign me these issues unless you want me to fix them. Vlad and I will grab them. I monitor the repo any way.

**Comment by eviltofu** [comment]
> What's the glitch? The spurious border around the textbox?

@hboon The stuttering when transiting from the first screen to the next.

**Comment by hboon** [comment]
Can you help update the title?
