### ISSUE TITLE
(Fractional?) Amount in confirmation actionsheet doesn't match ETH transfer amount

### ISSUE THREAD

**Issue by eviltofu** [AlphaWallet/alpha-wallet-ios#5762]
Try sending some ETH to another wallet. Tested on iPhone 14 Pro hardware.

![IMG_53B181B961F7-1](https://user-images.githubusercontent.com/1050309/200730810-9ca57abf-67a7-402d-95f1-d216f965405c.jpeg)

**Comment by oa-s** [comment]
@eviltofu is there specific steps for reproducing? looks ok for me

**Comment by oa-s** [comment]
After opening `send` screen, what steps did u made?
- typed value to send
- tapped on `all funds button`

**Comment by hboon** [comment]
And can you share the sender's address?
