### ISSUE TITLE
Tapping Done button in Custom gas ("Set Speed") screen does nothing so we can't set custom gas for transactions

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#5784]
<img width='200' src='https://user-images.githubusercontent.com/56189/201018832-9ab1a0ee-7fee-4870-a485-726417f7d6c6.PNG'>

**Comment by hboon** [comment]
Think this is fixed with #5796 by restoring the Save button?

**Comment by oa-s** [comment]
works for me as expected, hope i miss nothing

**Comment by oa-s** [comment]
tag `fixes` haven't closed the issue
