### ISSUE TITLE
Most of the accessory button with the "Done" title should be "Next" and they should scroll to review the first responder

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#5785]
- [ ] The accessory button should all be "Next" instead of "Done" except when the Nonce textbox is focused
- [ ] Tapping "Next" should scroll to reveal the textbox that will be become the first responder

<img width='200' src='https://user-images.githubusercontent.com/56189/201018805-a21f0daf-899c-4228-8c71-3011876435ec.PNG'>
<img width='200' src='https://user-images.githubusercontent.com/56189/201018827-274b477d-c285-4e3b-9c98-581666dd3f44.PNG'>

**Comment by oa-s** [comment]
What if we use `IQKeyboardManagerSwift` for that, it helps to use `done, next` buttons  and adds `up, and down arrows` to make navigation beetwen text inputs, also handles scrolling to appropriate text input?

**Comment by hboon** [comment]
Sure, let's try `IQKeyboardManagerSwift` and see if it's too heavy for us (always like to prefer less dependency where reasonable)
