### ISSUE TITLE
Paste into import seed phrase screen should get rid of warning "Seed phrase has to be 12 or 24 words" if it was present

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#5824]

**Comment by oa-s** [comment]
@hboon can u please share example screen?

**Comment by hboon** [comment]
1. Type something
2. Tap import
3. Paste or change the text

Expect
4. the warning to be cleared
 
<img width="300" alt="Screenshot 2022-11-21 at 3 26 45 PM" src="https://user-images.githubusercontent.com/56189/202989996-dd015ff2-f5e8-4144-bdd1-5762c320bd17.png">

**Comment by oa-s** [comment]
got it thanks
