### ISSUE TITLE
verify import token script file

### ISSUE THREAD

**Issue by oa-s** [AlphaWallet/alpha-wallet-ios#5878]
When importing a token script file the app stucks. looks like its bacause its trying to download asset definition  and request failures all the time.
steps to reproduce: 
- download any token script file;
- open AW app;
- drag and drop .xml file to the AW app.
**Expectation**: 
- app not feezes
**Actual:**
- the app is stuckes

**Comment by hboon** [comment]
@oa-s which commit can you reproduce this with? It worked for me just a few days ago. I was using it quite a number of times.

**Comment by hboon** [comment]
Duplicate of #5879
