### ISSUE TITLE
App hangs/Infinite recursion when we drop in a TokenScript file for a contract which has a official TokenScript file in the central repo

### ISSUE THREAD

**Issue by oa-s** [AlphaWallet/alpha-wallet-ios#5879]
When importing a token script file the app stucks. looks like its bacause its trying to download asset definition  and request failures all the time.
steps to reproduce: 
- download any token script file;
- open AW app;
- drag and drop .xml file to the AW app.
**Expectation**: 
- app not feezes
**Actual:**
- the app is stuckes

**Comment by hboon** [comment]
@oa-s which commit can you reproduce this with? It worked for me just a few days ago. I was using it quite a number of times.

**Comment by oa-s** [comment]
i am able to reproduce it on `master`, maybe its simulator specific

**Comment by hboon** [comment]
Yeah. I just used it quite a few times today. Dragging the TokenSscript file into the app.

**Comment by oa-s** [comment]
> Yeah. I just used it quite a few times today. Dragging the TokenSscript file into the app.

and it works for you ok? i wondering because when i do the same the app stocks, by performing a lot of requests.

**Comment by hboon** [comment]
Yeah. Works for me. Maybe the file you tried is different from mine. Would you share it with me?

**Comment by oa-s** [comment]
its `EntryToken.xml` from https://github.com/TokenScript/TokenScript-Examples/tree/master/examples/EntryToken

**Comment by hboon** [comment]
Ah. I can reproduce. Maybe because it's a .xml. Will check.

**Comment by hboon** [comment]
Ah, this happens under this condition for a contract:

A. Contract has an official TokenScript, i.e there's a file here: `wget https://repo.tokenscript.org/2020/06/0x63cCEF733a093E5Bd773b41C96D3eCE361464942`
B. We drop it an overriding TokenScript file that is different from A

This causes a recursive where we detect it's changed, re-download, detect it's changed, re-download, etc
