### ISSUE TITLE
Wallet tab seems to update much slowly to reflect what's already in the database

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#5892]
1. Manual import 0x63cCEF733a093E5Bd773b41C96D3eCE361464942
2. Check it's in Add/Hide token's list
3. Observe not in Wallet tab by filtering for 0x63cCEF733a093E5Bd773b41C96D3eCE361464942 or "tks"
4. Verify it's in Add/Hide token's list
5. Still not in Wallet tab

Appears in Wallet tab after a while

**Comment by hboon** [comment]
The Wallet tab updates very quickly for an almost empty wallet though? Maybe it's the number of tokens?

**Comment by oa-s** [comment]
will check it

**Comment by hboon** [comment]
Still happening as of fc9045919eea36b872ac894fcfca8cae1c5e9907

**Comment by oa-s** [comment]
@hboon could you please check with latest version?

**Comment by hboon** [comment]
Seems better. Closing for now. Thanks
