### ISSUE TITLE
LockPasscodeViewController does not have lock input centred vertically when keyboard is shown

### ISSUE THREAD

**Issue by eviltofu** [AlphaWallet/alpha-wallet-ios#5916]
From main wallet screen, tap "Settings > Passcode/FaceId". Also since it's a numeric passcode, the text should say "passcode instead of password".

![Simulator Screen Shot - iPhone 14 Pro - 2022-12-08 at 15 24 56 copy](https://user-images.githubusercontent.com/1050309/206384745-5abd7e89-1b58-4d67-800b-c021351a2abd.png)

**Comment by oa-s** [comment]
not important, alignment was needed for small devices, on smallest screen it looks ok
