### ISSUE TITLE
Crash with AtomicDictionary

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#6010]
Seems to occur when I switch wallets. Maybe related to TokenScript, but can't reproduce reliably. Stack track empty in Xcode crashes.

https://console.firebase.google.com/u/0/project/alphawallet-ios-prod/crashlytics/app/ios:com.stormbird.alphawallet/issues/9d0d1fe16f41d8b2a64431ac61d67b62?time=last-hour&sessionEventKey=3ec788fcc1bb48dfa6c2c1b9c5ebbd23_1760509057806674704

**Comment by oa-s** [comment]
that is actually strange as callback as well as function get called on main queue, will remove atomicDictionary for this case, native dictionary should be also good.
