### ISSUE TITLE
Sending transaction with WalletConnect v1 does nothing

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#6041]
@oa-s will send you a URL offline

1. Visit URL in desktop browser
2. Make sure Goerli is enabled
3. Click "Connect wallet" 
4. Approve WalletConnect session
5. Click "Mint Test Devcon Souvenir Token"
6. WalletConnect actionsheet to sign transaction appears
7. Tap Confirm
8. Actionsheet closes

Expected
---
9. Transaction sent — a confirmation screen appears about transaction sent and show up as done or pending in Activity

Observed
---
9. Nothing seemed to have happened

Works if accessed in dapp browser

**Comment by oa-s** [comment]
sorry looks like i found the issue
