### ISSUE TITLE
Gas fee (both gas price and limit) too high for native swap on Polygon from WETH to MATIC

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#6054]
Didn't test extensively with Ethereum mainnet, but seems to be off in a different way?

Screenshot taken by changing from Default to Custom to display the gas settings:

<img width='300' src='https://user-images.githubusercontent.com/56189/210690253-766b1ab1-5fcd-4dc7-94ac-f11ed6373bdc.PNG'>

* Gas price too high. 700gwei when 70 gwei would be enough
* Gas limit too high. 5 million (when 500k would be enough)

Both are off by a factor of 10 for each. Coincidence?

This transaction went through almost immediately with price = 31 gwei and gas used = 436,521 at the same time: https://polygonscan.com/tx/0x6b554d66e652b49e18cce25f442d91a497ee4a45e0451faa9a349f93e35de330

**Comment by oa-s** [comment]
@hboon are u still able to reproduce this issue?
what transaction it is, approve or swap confirmation?
have to tokens on polygon to test this issue, tested with bnb, looks ok

**Comment by hboon** [comment]
Just tried with recent master (probably from a day ago, as of writing). Looks good. Closing.

(should not be approve, the data doesn't match)
