### ISSUE TITLE
Make test fails with 4 failures

### ISSUE THREAD

**Issue by eviltofu** [AlphaWallet/alpha-wallet-ios#6097]
The following tests failed:

SendViewControllerTests.testScanEip681QrCodeEnglish()
SendViewControllerTests.testScanEip681QrCodeEnglish()
SendViewControllerTests.testScanEip681QrCodeSpanish()
TransactionTypeFromQrCodeTests.testScanSmallEthTransfer()

**Comment by hboon** [comment]
Ah, #6096 might have broken EIP681 handling

**Comment by eviltofu** [comment]
I got additional failures (ran make test twice).

EnsResolverTests.testEnsIp10WildcardAndEip3668CcipRead()
EnsResolverTests.testResolution()
EnsResolverTests.testResolutionThatHasDifferentOwnerAndResolver()
