### ISSUE TITLE
handle receiving ipfs hash without path `ipfs//`

### ISSUE THREAD

**Issue by oa-s** [AlphaWallet/alpha-wallet-ios#6271]

**Comment by hboon** [comment]
Might keep it separate. Video might be tricky.

**Comment by oa-s** [comment]
yes sure, video urls would be supported but without its playing

**Comment by oa-s** [comment]
@hboon do you know if there anyway to know when video has loaded via AVPlayed?

**Comment by hboon** [comment]
> @hboon do you know if there anyway to know when video has loaded via AVPlayed?

Something like this:

`NotificationCenter.default.addObserver(forName: .AVPlayerItemNewAccessLogEntry, object: item, queue: nil) { notification in`

then check for `player.state == .readyToPlay`
