### ISSUE TITLE
Support `action=token1155tx`

### ISSUE THREAD

**Issue by oa-s** [AlphaWallet/alpha-wallet-ios#6275]

**Comment by hboon** [comment]
This should already be supported. Careful not to implement it again

**Comment by hboon** [comment]
Refer to `Erc1155TokenIdsFetcher` and `Erc1155BalanceFetcher` and their class comment.

**Comment by hboon** [comment]
Maybe broken because of #6268 ?

**Comment by oa-s** [comment]
Nope there is another endpoint (in etherscan) for retrieving erc1155, transacted tokens, for polygon sure, hope for other too.

**Comment by oa-s** [comment]
here is link to doc: https://docs.polygonscan.com/api-endpoints/accounts#get-a-list-of-erc1155-token-transfer-events-by-address

**Comment by oa-s** [comment]
looks like the same for mainnet, we need to implement action `token1155tx`

**Comment by hboon** [comment]
So that's a newer way right and would be good (and I think much faster) if it works, but the original way of using events should work. It has been working for a while. Is it broken?

**Comment by oa-s** [comment]
not quite sure, but i havent seen erc1155 tokens added from transactions (for polygon only), maybe something with internet connection, .mainet worked good

**Comment by hboon** [comment]
Not from transactions, but from eventlog. Watching for transfer events. Note that it might take a while for Polygon as it has small block times so many more blocks to process and the RPC node has a window limit.

**Comment by oa-s** [comment]
> Not from transactions, but from eventlog. yes right, 
but we also import tokens from transactions, via `ErcTokenDetector` and there was no erc1155 tokens detected

**Comment by oa-s** [comment]
btw, i just realised that we actually do multiple same calls, when detection erc tokens we send actions like `module=account&action=tokennfttx` and when fetching transactions we send it too, looks like we can remove tokens autodetection operation, and use retrieving tokens from fetched transactions. or i mistaking?

**Comment by hboon** [comment]
> but we also import tokens from transactions, via ErcTokenDetector and there was no erc1155 tokens detected

Oh, that's because Etherscan and other blockchain explorer APIs don't include ERC1155 in their transaction history endpoints. I think Etherscan started to a few months (a year?) ago, and we haven't check that yet.

**Comment by hboon** [comment]
> btw, i just realised that we actually do multiple same calls, when detection erc tokens we send actions like `module=account&action=tokennfttx` and when fetching transactions we send it too, looks like we can remove tokens autodetection operation, and use retrieving tokens from fetched transactions. or i mistaking?

Yes, we do repeat them. I haven't changed those because not all nodes work the same and to keep the operations separate (detection and transactions), hence the duplicate.

**Comment by hboon** [comment]
Refer to https://github.com/AlphaWallet/alpha-wallet-android/pull/3086
