### ISSUE TITLE
ErrorView not being used in code. Propose removal.

### ISSUE THREAD

**Issue by eviltofu** [AlphaWallet/alpha-wallet-ios#6295]
ErrorView appears not to be in use. Propose removal.

**Comment by hboon** [comment]
@oa-s would you help check? Last instance was removed in 46d9fe684c3d29f20da4d328424492b07fc87114. See if it's intentional. The commit message doesn't explain why:

>     Update transactions screen #5727

**Comment by oa-s** [comment]
yes, we are not using error view for transactions screens, and there is not actual what to display, we use empty view and list of transactions
