### ISSUE TITLE
iOS - Error showed on Alpha Wallet after connecting to Bogota Passive using WC v2

### ISSUE THREAD

**Issue by jeanhwa** [AlphaWallet/alpha-wallet-ios#6341]
name: Bug Report
about: Occurs only on iOS Alphawallet

---

**Describe the bug**
Error showed on Alpha Wallet after connecting to Bogota Passive using WC v2, Eth/Polygon main net.

**Steps to reproduce (REQUIRED)**
1. Go to ticket issuer to create a ticket https://tokenscript.github.io/token-negotiator-examples/ticket-issuer-url-website/
2. Open https://tokenscript.github.io/token-negotiator-examples/hotel-bogota-passive-negotiation-website/
3. Click Book
4. Select Ticket and complete Attestation
5. Click WalletConnect v2
6. Scan QR code and confirm in Alpha wallet

**Expect**
Alpha Wallet connected via WC v2

**Observed**
Error showed on Alpha Wallet after connecting

**Screenshots**
![image](https://user-images.githubusercontent.com/107824107/218983239-c823861e-a872-4dd1-aa76-7a1823ff4792.png)

**Version or build number number**
3.61 (iOS)

**Additional context (Error Messages, etc.)**

**Comment by oa-s** [comment]
[jeanhwa](https://github.com/jeanhwa) can u provide more delailed description?
 after selection `book` appears next screen:
<img width="300" alt="Screenshot 2023-02-15 at 11 49 27" src="https://user-images.githubusercontent.com/96283950/218993056-ee0ae212-1eac-49be-abbe-494b5152ac37.png">
selection on `pay now` display a new popup
<img width="300" alt="Screenshot 2023-02-15 at 11 50 19" src="https://user-images.githubusercontent.com/96283950/218993375-c04186fe-203b-424f-b04d-9e56fe8a1f4d.png">
selection on `ok` does nothing

in case if there need to enter right card number, and so on, please provider test data

**Comment by jeanhwa** [comment]
Sorry @hboon I left out the first step, you need to create a ticket in ticket issue first.

**Comment by oa-s** [comment]
@jeanhwa after succesfull attestation should we  see something like this?
<img width="300" alt="Screenshot 2023-02-15 at 15 28 55" src="https://user-images.githubusercontent.com/96283950/219040598-b93aba0f-9ce2-4558-b0bf-8f44e0dd4bbb.png">

<img width="300" alt="Screenshot 2023-02-15 at 15 27 14" src="https://user-images.githubusercontent.com/96283950/219040330-9dba1d03-2580-47cb-a742-206db0f08539.png">

**Comment by jeanhwa** [comment]
@oa-s yup it should redirect back to bogota passive page and when click Pay there will be a popup which shows discount is applied. You can refer this entire flow with WC2 > Trustwallet


https://user-images.githubusercontent.com/107824107/219044353-281be197-53cb-4d87-be11-8a6bbd310db4.mp4

**Comment by oa-s** [comment]
wait for confirmation

**Comment by hboon** [comment]
@oa-s is this fixed?

**Comment by oa-s** [comment]
yep, it should bb

**Comment by oa-s** [comment]
wallet connect v2 looks ok, but when we using wallet connect v1 dapp stacks on screen after signing a received sign_message request
<img width="300" src="https://user-images.githubusercontent.com/96283950/220060811-87887c35-1218-4b3d-a864-d3a88092aa78.png">

**Comment by hboon** [comment]
If it’s shown this in Safari, there isn’t much we can do from within AlphaWallet. It seems to be either iOS or the site doing something differently.

Right?

**Comment by oa-s** [comment]
yes, its opened in safary

**Comment by oa-s** [comment]
wallet connect v2 looks ok

**Comment by jeanhwa** [comment]
> @jeanhwa have you tried to use Trust via WalletConnect v1? it redirects me to trust landing page without opening request signing

@oa-s yeah with WC v1, it redirects to Trust landing page, tested with iOS Safari
![token negotiator outlet](https://user-images.githubusercontent.com/107824107/220074868-b82783af-2c92-4e81-b7e9-5b7a0d8bd8f0.png)

**Comment by oa-s** [comment]
yes, facing the same, but still after signing a message we can't get back brandconnect with ticket page.

**Comment by hboon** [comment]
Confirmed fixed
