### ISSUE TITLE
`.signTransaction` from dapp browser should only sign, not sign + send

### ISSUE THREAD

**Issue by oa-s** [AlphaWallet/alpha-wallet-ios#6351]
@hboon  aren't we should to use ConfirmType.sign when we receive `case .signTransaction(let unconfirmedTransaction)` for dapp browser?

**Comment by oa-s** [comment]
https://github.com/AlphaWallet/alpha-wallet-ios/blob/1a270ba4ec899310885735ad48a5eb8f62bd7b06/AlphaWallet/Browser/Coordinators/DappBrowserCoordinator.swift#L477

**Comment by hboon** [comment]
Can you help elaborate or rephrase a bit?

**Comment by oa-s** [comment]
when we receiving `signTransaction` method call we actually should only sign transaction without its sending right? 
we receive `signTransaction` in dappBrowser, in function
https://github.com/AlphaWallet/alpha-wallet-ios/blob/1a270ba4ec899310885735ad48a5eb8f62bd7b06/AlphaWallet/Browser/Coordinators/DappBrowserCoordinator.swift#L469
and perform `executeTransaction(action: action, callbackID: callbackID, transaction: unconfirmedTransaction, type: .signThenSend)` type `.signThenSend` perform sending signed transaction, maybe we should change it with `sign`, to return signed transaction?

**Comment by oa-s** [comment]
in dap browser we do the same things when receive `singTransaction` and `sendTransaction`:
```
 case .signTransaction(let unconfirmedTransaction):
                executeTransaction(action: action, callbackID: callbackID, transaction: unconfirmedTransaction, type: .signThenSend)
            case .sendTransaction(let unconfirmedTransaction):
                executeTransaction(action: action, callbackID: callbackID, transaction: unconfirmedTransaction, type: .signThenSend)
            
```

**Comment by hboon** [comment]
Oh. I think it should be different. I think sign means sign and send and send means to send (assuming signed). It certainly was different previously. Could you help check the history? Otherwise I can check tomorrow. In a meeting on a tiny phone screen outside :p

**Comment by oa-s** [comment]
since first commit there is `.signThenSend` for message signing

**Comment by hboon** [comment]
> think sign means sign and send and send means to send (assuming signed). It certainly was different previously.

I was wrong here ^. Should be:

>  think sign means sign and send and send means to sign and not send

Strange. But yes, let's change it. Created #6357

**Comment by hboon** [comment]
Good job spotting it! :)

**Comment by hboon** [comment]
Fixed separately
