### ISSUE TITLE
Update tokens.json

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#6385]
With copy: https://github.com/AlphaWallet/tokens/blob/a07813077de4fc77e96c360dc67c211cf6c52a87/tokens.json#L1

There is a new group called "Spam". It currently crashes when it encounters that. Ignore it for now, making it not crash

**Comment by eviltofu** [comment]
@hboon 

Do I commit the new copy of `tokens.json`?

In add/hide token, I am able to add a SPAM token and it looks like this. I didn't write any code to display this. I just wrote enough to not cause the app to crash. Is this acceptable?

![Screen Shot 2023-02-24 at 11 17 38 AM](https://user-images.githubusercontent.com/1050309/221083904-7113b09f-26c2-4d8c-8f31-ead7fee4eca4.png)

**Comment by hboon** [comment]
> Do I commit the new copy of tokens.json?

Yes

> In add/hide token, I am able to add a SPAM token and it looks like this. I didn't write any code to display this. I just wrote enough to not cause the app to crash. Is this acceptable?

Not sure what you mean, but:

> I just wrote enough to not cause the app to crash.

Yes. Ignore the Spam group in the file, essentially.

> I am able to add a SPAM token and it looks like this.

Some of our token icons already included the word SPAM in the image itself. That's probably what you are seeing.

So what I meant was to delay this work: we'll make use of the new "Spam" group and programmatically show a preselected token icon or overlay to mark those tokens as spam as well as the removed those tokens from our token icons repo.
