### ISSUE TITLE
Extract tapping next button to focus on next textfield into one function for ConfigureTransactionViewController.swift

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#6405]
This is now done at 2 places:

A. https://github.com/AlphaWallet/alpha-wallet-ios/blob/fba12770c72080521a0cf1666d26afa46943fff9/AlphaWallet/Transfer/ViewControllers/ConfigureTransactionViewController.swift#L493
B. https://github.com/AlphaWallet/alpha-wallet-ios/blob/fba12770c72080521a0cf1666d26afa46943fff9/AlphaWallet/Transfer/ViewControllers/ConfigureTransactionViewController.swift#L365

This is a refactoring that also cleans up some spurious code because the if-else in (A)  checks for  ( and ) but those will never match and is handled (B). Better to call a single function which groups all the if-else's together.

**Comment by oa-s** [comment]
there is different types of text field **TextField**, **SlidableTextField**
`func nextButtonTapped(for textField: TextField)` and `func nextButtonTapped(for textField: SlidableTextField)`

**Comment by hboon** [comment]
Made #6479. Help see if it works right?
