### ISSUE TITLE
Why does TextField.textfield (still) return a static TextField?

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#6406]
https://github.com/AlphaWallet/alpha-wallet-ios/blob/0e2cf01f86978cdfcff08a44eaa1ed67d49c2304/AlphaWallet/Common/Views/TextField.swift#L287

**Comment by oa-s** [comment]
that factory field  for returning typed text field, there batch of view types that have such variables

**Comment by hboon** [comment]
Oh, I was confused and didn't realize it creates a new instance. Can we rename it? The reason being there is a `textField` property on the instance side. I guess we can't implement it as `init()` because of it subclasses `UIControl`; shall we change it to a function and call it `create()` or something like that so it's less ambiguous? Properties tend to not convey the impression it's returning something new.
