### ISSUE TITLE
OKX network integration

### ISSUE THREAD

**Issue by justindg** [AlphaWallet/alpha-wallet-ios#6408]
Network Name: OKXChain Mainnet
RPC: `https://exchainrpc.okex.org/`
Chain ID: `66`
Currency Symbol: `OKT`
Block Explorer URL: `https://www.oklink.com/en/okc`
Logo (Android): https://github.com/AlphaWallet/alpha-wallet-android/blob/master/app/src/main/res/drawable/ic_okx.xml

**Note**: 
They don't have a raw transaction fetch via etherscan API. In Android, we used this relevant API to fit our needs:
https://www.oklink.com/docs/en/#explorer-api-transaction-query-transaction-list-information

**Comment by ravi19821982** [comment]
@justindg  bro how can i text you directly ???
