### ISSUE TITLE
Illustration has no dark mode counterpart

### ISSUE THREAD

**Issue by eviltofu** [AlphaWallet/alpha-wallet-ios#6435]
https://zpl.io/kDNyZXG has no dark mode counterpart. (Icons/Illustrations/Empty/Light)
![iconsIllustrationsEmpty2](https://user-images.githubusercontent.com/1050309/222320267-2b6c5aac-5181-41d4-b86b-b1027d6320e2.png)

**Comment by hboon** [comment]
Just this one? Or are there more coming?

**Comment by eviltofu** [comment]
> Just this one? Or are there more coming?

For illustrations, just this one.

**Comment by hboon** [comment]
@eviltofu try https://app.zeplin.io/project/5d0356be2f25b319dcc5944b/styleguide/components?coid=6405a2fe3579de655a920aa2
