### ISSUE TITLE
[tokens.json] Auto mark tokens as hidden when a token is first discovered (and going to be added to the datastore) if they are in the "Spam Group"

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#6445]

**Comment by eviltofu** [comment]
@hboon So tokens are first discovered when

1. Creating a manual network
2. Already exists in an existing wallet (after adding new wallet)
3. Transferred to an existing wallet we are watching/using 

Automark hidden means on the main wallet screen where tokens can be added/hidden, such tokens when first detected are hidden. Do we allow users to show "Spam Group" tokens after they are hidden?

**Comment by hboon** [comment]
Users can undo the hidden tokens in Add/Hide if they want. We only default to hide each token once when it’s first auto detected. Users wouldn’t be able to tell if it was marked hidden by us or them (except if they remember that they didn’t do it themselves)

Instead of looking at the 3 points above, maybe better to just look directly at when the Realm database object is created and added. Probably needs some refactoring to support it (“Creating a manual network” shouldn’t be in it)

**Comment by eviltofu** [comment]
What if one token was not a spam token currently but in the future it is marked as spam? I should not auto-hide in this situation?

**Comment by eviltofu** [comment]
What if during start up or when wallets are changed/selected, created, imported, or watched, all the spam tokens are added to the TokenDataStore and hidden unless these already exist in the TokenDataStore? A marker could be saved someplace for each wallet so that the task doesn't repeat if it has already been done or when the spam list is updated. The frequency of one of these events happening is going to be much less than a token update event.

During the add/hide token process, we can group all the spam tokens at the end of the display so that the list doesn't appear cluttered.

**Comment by hboon** [comment]
> What if one token was not a spam token currently but in the future it is marked as spam? I should not auto-hide in this situation?

For simplicity, don't auto-hide since we only check to mark as hidden (because it's spam) when it's first detected.

**Comment by hboon** [comment]
> What if during start up or when wallets are changed/selected, created, imported, or watched, all the spam tokens are added to the TokenDataStore and hidden unless these already exist in the TokenDataStore? A marker could be saved someplace for each wallet so that the task doesn't repeat if it has already been done or when the spam list is updated. The frequency of one of these events happening is going to be much less than a token update event.

Do you mean to insert checkpoints where we deliberate add *all* the known spam tokens into the Realm database and mark them as hidden (and filter off those that are already in it)?

If that's what you mean — why?

The primary reason for marking spam tokens as such as because anyone can airdrop (fancy word for bulk transfer) tokens to anyone else. Most of these are worthless and can usually be automatically detected as tokens that users own, that's why they are spam. Spam detection just means to check and hide those automatically. Why do we want to add them and mark them as hidden if they don't appear in the database?

If that's not what you mean, can you elaborate?

**Comment by hboon** [comment]
> During the add/hide token process, we can group all the spam tokens at the end of the display so that the list doesn't appear cluttered.

Cluttered as in besides what is hidden now, they also include spam tokens? I think that's fine because:

* chances are if it's hidden, it's gone as far as the user is concerned
* spam tokens will soon be marked with the spam token image if they aren't already (they might already be because the token image file is already the spam token image according to the `iconassets` repo). So there's already a distinction
* less work and avoid complicating the UI. If there's a need, we can improve it later

Otherwise, would you help elaborate?

**Comment by eviltofu** [comment]
> > What if during start up or when wallets are changed/selected, created, imported, or watched, all the spam tokens are added to the TokenDataStore and hidden unless these already exist in the TokenDataStore? A marker could be saved someplace for each wallet so that the task doesn't repeat if it has already been done or when the spam list is updated. The frequency of one of these events happening is going to be much less than a token update event.
> 
> Do you mean to insert checkpoints where we deliberate add _all_ the known spam tokens into the Realm database and mark them as hidden (and filter off those that are already in it)?
> 
> If that's what you mean — why?
> 

@hboon 

# Cases

## Case A
Yes. The check points being when 

1. wallets are created/monitored
2. when the app starts up and a new spam list is generated. 

I thought that this would occur less frequently once all the spam tokens are hidden.

## Case B

1. When tokens are added.

I thought this would occur much more frequently and lead to more checking.

# Checking

For all cases,  If a token is already shown then it would be ignored.

# Results

I assume you want me to do Case B?

> The primary reason for marking spam tokens as such as because anyone can airdrop (fancy word for bulk transfer) tokens to anyone else. Most of these are worthless and can usually be automatically detected as tokens that users own, that's why they are spam. Spam detection just means to check and hide those automatically. Why do we want to add them and mark them as hidden if they don't appear in the database?
> 
> If that's not what you mean, can you elaborate?

**Comment by eviltofu** [comment]
> > During the add/hide token process, we can group all the spam tokens at the end of the display so that the list doesn't appear cluttered.
> 
> Cluttered as in besides what is hidden now, they also include spam tokens? I think that's fine because:
> 
> * chances are if it's hidden, it's gone as far as the user is concerned
> * spam tokens will soon be marked with the spam token image if they aren't already (they might already be because the token image file is already the spam token image according to the `iconassets` repo). So there's already a distinction
> * less work and avoid complicating the UI. If there's a need, we can improve it later
> 
> Otherwise, would you help elaborate?

@hboon I will implement this? I'm not sure if this is a yes or no.

**Comment by hboon** [comment]
For the cases A and B:

> I assume you want me to do Case B?

Yes, but I would like to know why you suggested A and think it might be better? If it's better, sure. I just thought that B is easier and simpler to implement and maintain. If performance is the primary concern, I think it doesn't matter much since new tokens aren't detected all that often compared to launches and wallet switches

**Comment by hboon** [comment]
> During the add/hide token process, we can group all the spam tokens at the end of the display so that the list doesn't appear cluttered.

> @hboon I will implement this? I'm not sure if this is a yes or no.

I don't understand. What would we it look like? I probably misunderstood you earlier. Is it:

A. Add the newly detected spam token to the "Hidden Tokens" group in Add/Hide Tokens. And to always add the newly one at the bottom of that group?
B. Add *all* the spam tokens in `tokens.json` at once to the "Hidden Tokens" group in Add/Hide Tokens, at the bottom of that group?

I thought you mean (B). I mean to do (A).

**Comment by eviltofu** [comment]
> > During the add/hide token process, we can group all the spam tokens at the end of the display so that the list doesn't appear cluttered.
> 
> > @hboon I will implement this? I'm not sure if this is a yes or no.
> 
> I don't understand. What would we it look like? I probably misunderstood you earlier. Is it:
> 
> A. Add the newly detected spam token to the "Hidden Tokens" group in Add/Hide Tokens. And to always add the newly one at the bottom of that group? B. Add _all_ the spam tokens in `tokens.json` at once to the "Hidden Tokens" group in Add/Hide Tokens, at the bottom of that group?
> 
> I thought you mean (B). I mean to do (A).

Ok doing (A)
