### ISSUE TITLE
[tokens.json] Automatically apply the Spam token icon instead of the one from sources like `iconassets` repo

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#6446]

**Comment by eviltofu** [comment]
@hboon can you elaborate on this? Currently this is showing when a token is spam.
![Screen Shot 2023-04-05 at 8 04 47 AM copy](https://user-images.githubusercontent.com/1050309/229948462-7f634653-7dbf-4fd5-9991-15e96a78ff32.png)

**Comment by hboon** [comment]
@eviltofu we currently display the spam icon, as in the screenshot above for tokens we think are spam. We want to continue this effect.

Current implementation:
---
We don't use the `Spam` group from `tokens.json` to detect them. Instead, if we think `0x0b91b07beb67333225a5ba0259d55aee10e3a578` is spam, we'll upload an icon file to the `iconassets` repo with the word "spam" in it https://github.com/AlphaWallet/iconassets/blob/4d77b8d2160b5009e86cb46e138e13e113e74a0d/0x0b91b07beb67333225a5ba0259d55aee10e3a578/logo.png

So it's a lot more work than necessary and wasteful of bandwidth, storage etc

How the implementation should be:
---
We should check against the new-ish `isSpam(address:chainId:)` (I think that's what it's called) when fetching a token image and use a single copy of the icon file we will ship with the app and not involve the network at all. This might be a good place to start at and work upstream: https://github.com/AlphaWallet/alpha-wallet-ios/blob/31fe94d93870947d3c7e6fac2ccc6fb8d2d4a026/modules/AlphaWalletFoundation/AlphaWalletFoundation/Tokens/TokenImageFetcher.swift#L260

**Comment by eviltofu** [comment]
Needs #6645 to be merged.
