### ISSUE TITLE
Update app to use updated tokens.json

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#6447]
After #https://github.com/AlphaWallet/alpha-wallet-android/issues/3129

**Comment by eviltofu** [comment]
How do I update tokens.json? Or is this the addition of `Spam` to the list of groups? I also noted that some contracts addresses are duplicated `0xd6A5aB46ead26f49b03bBB1F9EB1Ad5c1767974a` exists in 
https://github.com/AlphaWallet/alpha-wallet-ios/blob/b7351542e77f34ad37e3e21b6f64783db91e500d/AlphaWallet/Resources/tokens.json#L29305
https://github.com/AlphaWallet/alpha-wallet-ios/blob/b7351542e77f34ad37e3e21b6f64783db91e500d/AlphaWallet/Resources/tokens.json#L29309
```json
  {
    "contracts": [
      {
        "address": "0xd6a5ab46ead26f49b03bbb1f9eb1ad5c1767974a",
        "chainId": 1
      },
      {
        "address": "0xd6a5ab46ead26f49b03bbb1f9eb1ad5c1767974a",
        "chainId": 137
      }
    ],
    "group": "Assets"
  },
```
as well as
https://github.com/AlphaWallet/alpha-wallet-ios/blob/b7351542e77f34ad37e3e21b6f64783db91e500d/AlphaWallet/Resources/tokens.json#L93351
```json
      {
        "address": "0xd6A5aB46ead26f49b03bBB1F9EB1Ad5c1767974a",
        "chainId": 1
      }
```
and 
https://github.com/AlphaWallet/alpha-wallet-ios/blob/b7351542e77f34ad37e3e21b6f64783db91e500d/AlphaWallet/Resources/tokens.json#L93583
```json
    [
    ....
      {
        "address": "0xd6A5aB46ead26f49b03bBB1F9EB1Ad5c1767974a",
        "chainId": 137
      },
      {
        "address": "0xD7f1d4F5A1B44D827a7C3cC5dd46a80fADe55558",
        "chainId": 137
      }
    ],
    "group": "Spam"
```

**Comment by eviltofu** [comment]
I've looked at the [adjustments.json](https://github.com/AlphaWallet/tokens/blob/main/adjustments.json) in the `Token` repository and I see
```json
{
  "remove": [
  ],
  "add": [
    {
      "contracts": [
        {"address": "0x89E642e9BDB2c3d2fA03B600d8922cFc0800fdDB", "chainId": 1},
        {"address": "0xfcb5DF42e06A39E233dc707bb3a80311eFD11576", "chainId": 1},
        {"address": "0x7Be15314511801113b2f42796bbA73bc4294a39A", "chainId": 1},
        {"address": "0xD48Cf65488486fa0d45B806aA51Ca35727D70880", "chainId": 1},
```
Shouldn't the contracts in the spam group be added to the `remove` section?

**Comment by hboon** [comment]
> How do I update tokens.json?

You need to clone the repo and run the code in the repo.

Looks like the way to trigger step 1-3 above is: https://github.com/AlphaWallet/tokens#how-to-run

If you can't figure it out, post a copy of `adjustments`.json` to https://github.com/AlphaWallet/alpha-wallet-android/issues/3129 and I'll try it out (I want to know how it works too to improve the process). I might need a key and might take a long time to run.

**Comment by hboon** [comment]
No, `adjustments.json` work like [described here](https://github.com/AlphaWallet/tokens#manual-overrides). Note that you have to explicitly remove a contract with the `remove` and explicitly add it with `add` to perform a "replace".

> Shouldn't the contracts in the spam group be added to the remove section?

No, The process to generate `tokens.json` is:

1. Generate a temporary tokens.json from sources excluding `adjustments.json` (for now, only CoinGecko)
2. tokens.json = tokens.json - adjustment's `remove`
3. tokens.json = tokens.json + adjustment's `add`

**Comment by hboon** [comment]
Can you make a list of tokens that are duplicated? `0xd6a5ab46ead26f49b03bbb1f9eb1ad5c1767974a` is not duplicated. It looks like it *is* the same contract address on both chain ID `1` and `137`. You can see them here:

* https://etherscan.io/address/0xd6a5ab46ead26f49b03bbb1f9eb1ad5c1767974a
* https://polygonscan.com/address/0xd6a5ab46ead26f49b03bbb1f9eb1ad5c1767974a

**Comment by eviltofu** [comment]
So this issue mainly just get the new tokens.json from running the `npm run start` and making sure the tests all work and the app doesn't freeze during normal usage?

**Comment by hboon** [comment]
This issue is not to do `npm` (and thus wouldn't modify the `tokens` repo), but just to copy over the updated `tokens.json` from `tokens` repo after it has been updated in https://github.com/AlphaWallet/alpha-wallet-android/issues/3129

**Comment by eviltofu** [comment]
Ok so I'll have to wait for the android site to complete before I proceed?

**Comment by hboon** [comment]
@eviltofu yeah, that one looks like it's not Android specific, so if you want to go for it, assign yourself. This is even better because we get to close a self-contained task faster rather than have too many WIP

**Comment by eviltofu** [comment]
@hboon What about the "spam" group? Any more additions?

**Comment by hboon** [comment]
> @hboon What about the "spam" group? Any more additions?

Do you mean if we want to append more entries to it? Eventually. Feel free to add more if you like, but we can do it separately, these couple of issues is more for adding/tweaking the functionality. If we add entries (be it spam or run the script again to update from sources, it's a fairly easy change, just copy over `tokens.json`)

**Comment by eviltofu** [comment]
@hboon Ok so after running `npm run start` I check out both Android and iOS repositories, swap in the newly generated tokens.json, and create pull requests for both repositories?

**Comment by hboon** [comment]
> Ok so after running `npm run start` I check out both Android and iOS repositories, swap in the newly generated tokens.json, and create pull requests for both repositories?

Definitely for iOS. Up to you for Android — would be good though if it's straightforward; submit a PR. And remember to assign yourself there if you work on it.

And only after https://github.com/AlphaWallet/alpha-wallet-android/issues/3129

**Comment by eviltofu** [comment]
> > Ok so after running `npm run start` I check out both Android and iOS repositories, swap in the newly generated tokens.json, and create pull requests for both repositories?
> 
> Definitely for iOS. Up to you for Android — would be good though if it's straightforward; submit a PR. And remember to assign yourself there if you work on it.
> 

Both applications should have the same data.

> And only after [AlphaWallet/alpha-wallet-android#3129](https://github.com/AlphaWallet/alpha-wallet-android/issues/3129)
