### ISSUE TITLE
[tokens.json] Use "Spam Group" data to show the spam token image instead of many duplicate images from `tokens` repo

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#6448]
After #6447

**Comment by eviltofu** [comment]
Is this for the issue for the following? @hboon 

1|2
-|-
![Simulator Screenshot - iPhone 14 Pro - 2023-04-10 at 14 32 08](https://user-images.githubusercontent.com/1050309/230841809-0bd44acc-d3ac-4660-a06f-5876d9ce4eea.png)|![Simulator Screenshot - iPhone 14 Pro - 2023-04-10 at 14 32 11](https://user-images.githubusercontent.com/1050309/230841818-5076af27-6899-4d82-aeeb-07b656b2ee0a.png)

**Comment by hboon** [comment]
@eviltofu I don't understand your question.

But this (#6448) seems a dup of #6446. Unless you figure it out, let's close this issue for now.
