### ISSUE TITLE
Use tokens.json for detecting tokens as Spam

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#6449]
- [x] #6445
- [x] #6446
- [x] #6447
- [x] #6448

**Comment by hboon** [comment]
@eviltofu any luck with this so far?

**Comment by eviltofu** [comment]
Working on #6445 Trying to figure out how/where to store the spam group data.

**Comment by eviltofu** [comment]
@hboon considered closed?

**Comment by hboon** [comment]
@eviltofu seems so!
