### ISSUE TITLE
Don't show activity indicator for token icon while it's loading

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#6459]
Maybe it's used for some other cases? We can keep those probably, but it doesn't look nice for these little token icons

<img width="400" alt="Screenshot 2023-03-05 at 9 27 58 AM" src="https://user-images.githubusercontent.com/56189/222936699-bc088b0f-cbdd-40b3-acfc-9f56f8b2d4ba.png">

**Comment by oa-s** [comment]
will hide it in tokens list view, but keep to token page
