### ISSUE TITLE
awallet://wc regression

### ISSUE THREAD

**Issue by 10xSebastian** [AlphaWallet/alpha-wallet-ios#6466]
It looks like the native deeplink `awallet://` does not work for `/wc` (WalletConnect V1) anymore. 

https://user-images.githubusercontent.com/851393/222998440-4629831c-c32a-48e6-9cb5-ef4101ee9837.MP4

It would be great if native deep links remain usable.

Universal deep links are not sufficient and highly unreliable, see the following screenshot why:

<img width="744" alt="Screenshot 2023-03-05 at 18 10 02" src="https://user-images.githubusercontent.com/851393/222997950-52fab8ab-7000-4abc-952f-937acfa2802c.png">

On iOS universal deep links are optimistic, if internet connectivity is not sufficient or safari deems a universal link is not a direct trigger of a user click, it will send you either to the app store or will stay in safari without opening the native app at all. The "universal" in universal link, means that the content can be displayed in the browser, which is not true for a wallet connection and nobody should rely on universal links when connecting to mobile wallets on a mobile device.

You can test the behavior yourself here: https://depayfi.github.io/widgets/demo.connect.html

**Comment by hboon** [comment]
> Universal deep links are not sufficient and highly unreliable, see the following screenshot why:

Fully agreed. It's causing us a lot of pain with WalletConnect.

> It looks like the native deeplink awallet:// does not work for /wc (WalletConnect V1) anymore

Thanks for the repo, I'm checking this now and I think I'm reproducing it, but just to be sure:

It *does* switch to AlphaWallet, but the app seems to do nothing about it right?

**Comment by 10xSebastian** [comment]
Thanks for the quick response. 

Correct, it does switch to Alphawallet, but it does nothing afterwards.

**Comment by 10xSebastian** [comment]
Thanks to everyone for the work so far.

I can confirm. It does not hide the "try it" button after a wallet is connected, but only shows the connected wallet below the card.

This is intentional. This landing page is to test various mobile wallets quickly after each other.

**Comment by 10xSebastian** [comment]
Once the version is live on the App Store I will let confirm from our end again.

**Comment by hboon** [comment]
We don't (well, we did, but the beta review times were killing us, so it's rarely updated). Is it OK if I ping you here once this is live?

**Comment by 10xSebastian** [comment]
That's ok.

**Comment by hboon** [comment]
@10xSebastian released AlphaWallet iOS v3.63 build 480 which includes this. Would you be able to help confirm if it works for you?

**Comment by 10xSebastian** [comment]
It works flawlessly now. Long live native links 🙌. Thanks everyone.
