### ISSUE TITLE
Enable Dark Mode

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#6468]
- [x] #6435
- [x] #5288
- [x] Smoke test by running through app
- [x] Enable in `Info.plist`

**Comment by eviltofu** [comment]
@hboon #5288 completed.

**Comment by hboon** [comment]
@eviltofu should only buzz when issue (#6495) is closed

**Comment by eviltofu** [comment]
#5288 is closed now @hboon

**Comment by hboon** [comment]
@eviltofu thanks! Seems good with smoke test
