### ISSUE TITLE
Wrong label background color in "Change Wallet" screen's group headers

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#6502]
The label has a black-ish background over the header's gray background

<img width="482" alt="Screenshot 2023-03-13 at 1 11 03 PM" src="https://user-images.githubusercontent.com/56189/224613551-1d9d3fa0-c9f7-45b5-af9f-5497890491cc.png">

**Comment by eviltofu** [comment]
This happens in the create wallet screen too. I'll fix them all in this issue? It's all the same problem. @hboon
