### ISSUE TITLE
WalletConnect v2 sign typed message broken

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#6512]
Reproducible on master/d62711da358922e16adc8bbd7eb1bab982d3d9ad

https://react-app.walletconnect.com

`eth_sign` (standard) works, but when I tap `eth_signTypedData`, I see these:

&nbsp;|&nbsp;
-|-
<img width="300" alt="Screenshot 2023-03-14 at 3 14 53 PM" src="https://user-images.githubusercontent.com/56189/224923826-ae093e5a-69b2-418d-ada9-da9d49ab38cc.png">|<img width="800" alt="Screenshot 2023-03-14 at 3 14 54 PM" src="https://user-images.githubusercontent.com/56189/224923854-1de12e0a-7686-4a12-aeea-de673eb6be18.png">

**Comment by oa-s** [comment]
this is because of our validation, received sign message with chain id `1` mainnet, when connected servers goerli, optimism

**Comment by oa-s** [comment]
maybe need to change message

**Comment by hboon** [comment]
The error message seems wrong then. Can we tweak that?

**Comment by oa-s** [comment]
What about this one `You were requested to sign a message for the %@ chain. You need to make sure your WalletConnect session have the same chains as requested`?

**Comment by hboon** [comment]
The second half be: “make sure the %@ chain is enabled” would be better
