### ISSUE TITLE
Trying OKX

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#6532]
@oa-s can you help give me a wallet address that has some transactions? I threw in https://www.oklink.com/okc/address/0x6b8335644265fcba30d4a690500581ad2cfeb6e2 but it doesn't seem to detect any in the app.

curl does return something:

```
curl -H "Ok-Access-Key: <key>" "https://www.oklink.com/api/v5/explorer/address/transaction-list?address=0x6b8335644265fcba30d4a690500581ad2cfeb6e2&protocolType=token_20&chainShortName=OKC&page=0&limit=50"
```

**Comment by oa-s** [comment]
try with this wallet **`0xB85AC6c29E6e8203ffa84715Cfc23075F8687882`**, looks like there are present all types of transactions

**Comment by hboon** [comment]
I specify a key running in curl, but not fetching transactions in the app. Maybe not retained? Reaches here, but no error or results: https://github.com/AlphaWallet/alpha-wallet-ios/blob/f6a6cd2879802fcd00583889461315355f268ca9/modules/AlphaWalletFoundation/AlphaWalletFoundation/Transactions/Oklink/OklinkNetworking.swift#L97

**Comment by oa-s** [comment]
do u mean this part of curl `<key>` as a key?

**Comment by hboon** [comment]
I used the key in the code base and the wallet you gave me above.
