### ISSUE TITLE
Fix error type implementation for those errors that are defined in modules (i.e. CocoaPod) and their localized strings are provided in the app bundle

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#6541]
Related to #6498.

eg. `SendInputErrors`, make the error conform to `Error` instead of `LocalizedError` in the module and only conform to `LocalizedError` in the app, i.e. change from this:

```
//module
struct E1: LocalizedError {
}

//app
extension E1 {
    var errorDescription: String? {
      return "E1's localized errorDescription" //using R.string.localizable.xxx()
    }
}
```

to:

```
//module
struct E1: Error {
}

//app
extension E1: LocalizedError {
    var errorDescription: String? {
      return "E1's localized errorDescription" //using R.string.localizable.xxx()
    }
}
```

**Comment by hboon** [comment]
Note the reassigning

**Comment by eviltofu** [comment]
So for https://github.com/AlphaWallet/alpha-wallet-ios/blob/37c145a84e28ab836305547844c252e83859b725/modules/AlphaWalletFoundation/AlphaWalletFoundation/Ethereum/ABI/ABIError.swift#L9 
I can ignore or do you want me to change the type to `Error` as well? There does not appear to be any `LocalizedError` in the app that extends ABIError.

**Comment by hboon** [comment]
Keep those unchanged.
