### ISSUE TITLE
Switching chain in app and then signing from WalletConnect v1 test dapp fails with "Call Request Rejected"

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#6542]
Not necessarily a problem on our side. But this used to work (I smoke test before release). Like this:

1. Make sure Ethereum and xDai is enabled
2. https://example.walletconnect.org
3. Scan and connect. Note that it is connected to Ethereum
4. Switch Network in AlphaWallet for that WalletConnect session to xDai
5. Confirm dapp shows "xDai"
6. Click personal_sign
7. Confirm in AlphaWallet
8. Dapp shows "Call Request Rejected"

Works with v2, but the mechanics are different of course.

**Comment by oa-s** [comment]
there might be something with signature verification in wallet connect example app, Ethereum works

**Comment by hboon** [comment]
Works for me upon connection, but not after switching networks though.

**Comment by oa-s** [comment]
hmm, i tried to connect directly to gnosis, still the same, will explore it more

**Comment by oa-s** [comment]
i amnot quite sure but here what i found: 
rpc url `https://dai.poa.network/` that is defined for Gnosis chain in wallet connect v1 doesn't exists
also console logs from web page

<img width="1840" alt="Screenshot 2023-03-20 at 10 14 32" src="https://user-images.githubusercontent.com/96283950/226282704-7a0d4009-7a0f-432b-9b4e-2c92eef6efe2.png">

**Comment by oa-s** [comment]
yes pretty sure its because of rpc, as verify signature function makes call to rpc node
```
export async function verifySignature(
  address: string,
  sig: string,
  hash: string,
  chainId: number,
): Promise<boolean> {
  const rpcUrl = getChainData(chainId).rpc_url;
  const provider = new providers.JsonRpcProvider(rpcUrl);
  const bytecode = await provider.getCode(address);
  if (!bytecode || bytecode === "0x" || bytecode === "0x0" || bytecode === "0x00") {
    const signer = recoverAddress(sig, hash);
    return signer.toLowerCase() === address.toLowerCase();
  } else {
    return eip1271.isValidSignature(address, sig, hash, provider);
  }
}
```

**Comment by hboon** [comment]
@oa-s Oh, I see what you mean. It works if I replace the Gnosis (xDai, hah!) with say Polygon. Closing since it's not us. Thanks for researching.
