### ISSUE TITLE
Opening and saving in custom gas screen saves gas price as 0 for chains that have sub-gwei gas prices. eg. Arbitrum

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#6549]
Especially after #6548.

This is because that screen can't display < 1 gwei

<img width="400" alt="Screenshot 2023-03-20 at 1 02 07 PM" src="https://user-images.githubusercontent.com/56189/226252091-352be235-5bfa-4e38-9517-e66463069f2d.png">

**Comment by oa-s** [comment]
latest updates with ConfigureTransaction screen solved this issue
<img width="561" alt="Screenshot 2023-04-28 at 09 56 59" src="https://user-images.githubusercontent.com/96283950/235076721-f9443ca0-cb1e-4de3-a5a7-ba4e14b46648.png">

**Comment by hboon** [comment]
Thanks!
