### ISSUE TITLE
Add/hide tokens does not work when using results of search

### ISSUE THREAD

**Issue by eviltofu** [AlphaWallet/alpha-wallet-ios#6585]
When a token is hidden via the add/hide tokens screen with the search bar, the token is not hidden. 
Sequence | Description
-|-
![Simulator Screen Shot - iPhone 14 Pro - 2023-03-24 at 20 30 13](https://user-images.githubusercontent.com/1050309/227522078-d4b1cf58-41d5-49c6-a570-49b4561818f6.png) | Delete
![Simulator Screen Shot - iPhone 14 Pro - 2023-03-24 at 20 30 16](https://user-images.githubusercontent.com/1050309/227522048-042a8466-5ea5-45de-918b-9482d6eb437b.png) | Deleted
![Simulator Screen Shot - iPhone 14 Pro - 2023-03-24 at 20 30 31](https://user-images.githubusercontent.com/1050309/227521914-0b695859-0eec-4f25-91d2-2aa19a853916.png) | Missing

**Comment by hboon** [comment]
@eviltofu not fixed AFAIK right?

**Comment by eviltofu** [comment]
> @eviltofu not fixed AFAIK right?

This looks fixed.
