### ISSUE TITLE
NFT from ERC-721 contract on polygon mumbai test net not showing in iOS Wallet

### ISSUE THREAD

**Issue by jsolderitsch** [AlphaWallet/alpha-wallet-ios#6593]
name: Bug Report
about: Using AlphaWallet, but it's not working as you expect?

---

**Describe the bug**

Using Polygon Mumbai testnet. 

I am sending an NFT smart token to my AlphaWallet with a contract based on ERC-721 OpenZeppelin template. I was expecting the NFT to show up as a collectible. It does not.

Using the same contract, sending to a metamask wallet address, the NFT does appear (have to enter the contract address to find the token)

This is with an iPhone running latest iOS and version 3.63 (480) of AlphaWallet installed from App Store.

**Steps to reproduce (REQUIRED)**
Steps to reproduce the behavior

1. Tap Wallet icon after NFT is transferred.
2. Check list of Collectibles
3. No NFT is present

**Expect**
6a. NFT icon to be be seen in the collectibles list

**Observed**
6b. No NFT is shown.

**Screenshots**
If applicable, screenshots (preferred to video) to help explain your problem, a wallet address or transaction hash if applicable/possible
<img width="502" alt="Screen Shot 2023-03-25 at 5 07 53 PM" src="https://user-images.githubusercontent.com/23091236/227802997-2e65f9be-597d-44d4-96ad-ac5ecd5ad1f9.png">

<img width="476" alt="Screen Shot 2023-03-25 at 5 07 38 PM" src="https://user-images.githubusercontent.com/23091236/227803010-1249be2d-7357-4bbc-8c55-9aac1d4c12d9.png">

![Screen Shot 2023-03-25 at 5 13 26 PM](https://user-images.githubusercontent.com/23091236/227803304-55b79164-09f5-48c3-8dd5-e16fa8196bf7.png)

**Version or build number number**
Version number (if app store), build number (if TestFlight)

3.63 (480) from app store.

**Additional context (Error Messages, etc.)**

**Comment by jsolderitsch** [comment]
The top transaction is the transfer to this wallet address.

**Comment by hboon** [comment]
@jsolderitsch hi! it's a bug and we will fix it and it *ought* to be included in the next update. Thank you so much for reporting this.

**Comment by jsolderitsch** [comment]
Any idea when the next release will happen that includes the bugfix? I am running a university class and I would like to show off the NFT image visibility that used to work when an NFT with proper metadata was added as a collectible.

**Comment by hboon** [comment]
> Any idea when the next release will happen that includes the bugfix? I am running a university class and I would like to show off the NFT image visibility that used to work when an NFT with proper metadata was added as a collectible.

Quite likely sometime next week
