### ISSUE TITLE
Should not be possible to go dapp browser home screen after opening browser in read-only mode

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#6613]
1. Wallet tab
2. Tap ETH token
3. Tap token icon
4. Tap back (of back and forward) button — does nothing. Good
5. With device bezels enabled, swipe from left to right

Expected
---
6. nothing happens

Observed
---
6. The dapp browser home screen is revealed

<img width="200" alt="Screenshot 2023-03-29 at 7 46 19 AM (2)" src="https://user-images.githubusercontent.com/56189/228391604-7f0b3bf2-8240-47d8-9245-1ddf7d9756bb.png">

**Comment by oa-s** [comment]
not able to reproduce it, maybe some specific conditions before steps?

**Comment by hboon** [comment]
Hmm.. I can do it with simulator (device bezels enabled) with `master` and the most recent app store version.

**Comment by hboon** [comment]
Can you list your steps? :)

**Comment by oa-s** [comment]
the steps from description, let me check one more time

**Comment by oa-s** [comment]
also latest version on master

**Comment by oa-s** [comment]
guess need to change simulator

**Comment by hboon** [comment]
I can reproduce in both device and simulator

**Comment by oa-s** [comment]
able to reproduce, thanks
