### ISSUE TITLE
Camera to scan QR code not working when importing a wallet during onboarding

### ISSUE THREAD

**Issue by eviltofu** [AlphaWallet/alpha-wallet-ios#6618]
When the app is newly installed and there is no previous data, the camera icon to allow scanning of QR codes does not work.

1. Delete the app and all it's data
2. Run the app
3. Tap "I already have a wallet"
4. Tap "Track Wallet Address"
5. Tap camera icon in Ethereal Address text field

QR code scanner did not show up.

Tested on iOS 16.3.1, iPhone 14 Pro (actual hardware).

If you create an empty new wallet, then add a wallet, the QR code scanner does show up.

 Screen shot | Screen shot
-|-
![Simulator Screen Shot - iPhone SE (3rd generation) - 2023-03-30 at 09 17 13](https://user-images.githubusercontent.com/1050309/228703318-8ee90ba7-e19c-4f7c-8ecf-327a918b879b.png)|![Simulator Screen Shot - iPhone SE (3rd generation) - 2023-03-30 at 09 17 17](https://user-images.githubusercontent.com/1050309/228703326-0045db05-0733-40b6-b43b-5344cb5ae4e1.png)
![Simulator Screen Shot - iPhone SE (3rd generation) - 2023-03-30 at 09 17 31](https://user-images.githubusercontent.com/1050309/228703345-9f2ae26a-03b3-4bd0-8db2-de5cdfa7730f.png)

**Comment by hboon** [comment]
@eviltofu can you see if this title describes it more aptly, and rename if so?

> Camera to scan QR code not working when current wallet is a watch-wallet

**Comment by eviltofu** [comment]
> @eviltofu can you see if this title describes it more aptly, and rename if so?
> 
> > Camera to scan QR code not working when current wallet is a watch-wallet

This does not match the situation. When you first run the app and try to scan a QR code, it fails.

**Comment by hboon** [comment]
Ah, there is no wallet yet.
