### ISSUE TITLE
is buildClaimPaidErc875MagicLink function correct?

### ISSUE THREAD

**Issue by oa-s** [AlphaWallet/alpha-wallet-ios#6636]
in https://github.com/AlphaWallet/alpha-wallet-ios/blob/cfd411b1d9f46f9450207fed10499ca95fc8127f/modules/AlphaWalletFoundation/AlphaWalletFoundation/Transfer/Types/TransactionType.swift#L285 we got `buildClaimPaidErc875MagicLink` function declaration. function returns `UnconfirmedTransaction` with value `value: BigUInt(signedOrder.order.price)`but in `TransactionConfigurator` this transaction value get ignored, do we need to update function `buildClaimPaidErc875MagicLink` with zero value?
@hboon

**Comment by hboon** [comment]
It's used in here right?

https://github.com/AlphaWallet/alpha-wallet-ios/blob/31fe94d93870947d3c7e6fac2ccc6fb8d2d4a026/modules/AlphaWalletFoundation/AlphaWalletFoundation/Transfer/TransactionConfigurator.swift#L53

**Comment by oa-s** [comment]
yep, and and on level above the transaction was build in https://github.com/AlphaWallet/alpha-wallet-ios/blob/cfd411b1d9f46f9450207fed10499ca95fc8127f/modules/AlphaWalletFoundation/AlphaWalletFoundation/Transfer/Types/TransactionType.swift#L285, this transaction in calls smart contract, itsn't there should be zero value?

**Comment by hboon** [comment]
@oa-s I'm pretty sure I responded to you but I think my Git client lost it :( Would you buzz me again if I should reply?

**Comment by oa-s** [comment]
Yep, Al is good, compared with oldest commits, it looks the same, don't worry
