### ISSUE TITLE
AddressStorageTests.testInFileAddressStorage() and PublisherToAsyncTests.testCancellation() failing

### ISSUE THREAD

**Issue by eviltofu** [AlphaWallet/alpha-wallet-ios#6653]
Failing tests:
	AddressStorageTests.testInFileAddressStorage()
	PublisherToAsyncTests.testCancellation()

**Comment by hboon** [comment]
@oa-s reassigned to @eviltofu along since it's related to #6673. Feel free to help out if you like

**Comment by eviltofu** [comment]
I ran `AddressStorageTests.testInFileAddressStorage()` for 100 times and there was no failure. :(

**Comment by hboon** [comment]
I figure it might fail more frequently if you run the complete suite

**Comment by eviltofu** [comment]
I'm now running the entire test suite but in randomised mode. I figured the failures will show up there.

**Comment by hboon** [comment]
Does XCTest let you only run a subset of the test easily? If it's possible, then maybe binary search to narrow it down to a smaller set that is repeatable?

**Comment by hboon** [comment]
And maybe this is obvious: if you run the complete suite and one of the test fails, then I suppose the offending subset is right there at that point?

**Comment by eviltofu** [comment]
These tests don't seem to fail anymore.

**Comment by eviltofu** [comment]
Can this be closed? @hboon

**Comment by hboon** [comment]
Yeah, since they pass
