### ISSUE TITLE
Token has no name

### ISSUE THREAD

**Issue by eviltofu** [AlphaWallet/alpha-wallet-ios#6654]
From wallet `hweeboon.eth`.

![missing-name](https://user-images.githubusercontent.com/1050309/229984776-ddf05dd3-802c-4838-9893-9f12826df144.png)

**Comment by hboon** [comment]
Can help you paste the contract + chain ID with such issues?

**Comment by eviltofu** [comment]
It doesn't show up anymore. The next time it does I'll post more details. Close?

**Comment by hboon** [comment]
Ok. Thanks
