### ISSUE TITLE
Modify the "weights in `RPCServers.displayOrderPriority` so that the same order is preserved, except testnets come after all mainnets

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#6669]
Include a test to make sure that in the results of `RPCServers.displayOrderPriority` all testnets come after mainnets

**Comment by eviltofu** [comment]
What about manually added mainnets and testnets? Do they have to be included?

**Comment by hboon** [comment]
Didn't think of that. I guess we can play around with this line:

```
case .custom(let custom): return 300000 + custom.chainID
```

I guess besides this base weight of `300000` for `.custom` we should add a bigger base weight for all testnets, that should help weight them down?

**Comment by eviltofu** [comment]
Or we just create a function that takes into account all factors.

in order of priority
1. mainnets over testnets
2. chainIDs
3. name

**Comment by hboon** [comment]
Too complicated. Just a single weight for each one like now and one base add to all of them to weigh it down to testnets should do right (and 1 for `.custom`)? Then when we want to tweak the order, it's really easy. Don't need to worry about other things

**Comment by eviltofu** [comment]
If we remove the Weight, all the other data already exist. We don't even need to make the ordered list.

**Comment by hboon** [comment]
But I want to manually order them, so the weight for each always exists
