### ISSUE TITLE
Make price in gwei match what is in the gas settings UI exactly when posting a transaction

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#6680]
43.1 gwei -> in Etherscan 43.099998474 gwei https://goerli.etherscan.io/tx/0x7f5ac49ffe85b5b1ba80a94715f8e9b3154e44ee5e3eda458f28d2b40167d982

Similarly for Gnosis when I changed it to 2.1 gwei (I shouldn't of course), the transaction is posted as 2.099999905 gwei https://blockscout.com/xdai/mainnet/tx/0xaa324c2d576b082358a8c173f5e9294fecb5ba6bfb5412e26e4497d0bf55c6d0

Was precise here (26.5 gwei) https://etherscan.io/tx/0x50e80647b914f8650d2a366fef6e4cecf75ddb029133c18331e11fafb5d91aac

So it's probably the usual precision loss from floating point conversion

**Comment by oa-s** [comment]
do we have steps to reproduce it?, any specific cases?
