### ISSUE TITLE
429 with Gnosis in `func getContractList(walletAddress: AlphaWallet.Address, server: RPCServer, startBlock: Int? = nil, erc20: Bool) -> AnyPublisher<UniqueNonEmptyContracts, PromiseError> {`

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#6684]
https://github.com/AlphaWallet/alpha-wallet-ios/blob/9c986f9a604964e1e999979362bd51e6199306a0/modules/AlphaWalletFoundation/AlphaWalletFoundation/Tokens/Logic/GetContractInteractions.swift#L20

Should figure out why. Not sure if it's reproducible, but when I see it, many lines of this is logged to the console:

```
[API] request failure with status code: 429, message: 429 Too Many Requests [snipped]
```

We might need to check and enforce a delay?

**Comment by oa-s** [comment]
should be fixed with #6695
