### ISSUE TITLE
AlphawalletFoundation Pod Error , Cant Run in Xcode 14.1 

### ISSUE THREAD

**Issue by akhilccrb** [AlphaWallet/alpha-wallet-ios#6689]
<img width="337" alt="Screenshot 2023-04-13 at 4 49 17 PM" src="https://user-images.githubusercontent.com/45847512/231743204-1c60b3bd-1295-463e-8802-75fd827f0195.png">

Am using Mac M2 

   CocoaPods : 1.12.0
        Ruby : ruby 3.2.2 (2023-03-30 revision e51014f9c0) [arm64-darwin22]
    RubyGems : 3.4.10
        Host : macOS 13.0 (22A380)
       Xcode : 14.1 (14B47b)

**Comment by akhilccrb** [comment]
same error in  Xcode 14.2

**Comment by akhilccrb** [comment]
In realm they provided new support for Xcode 14 , do i need to update to new version. 


https://github.com/realm/realm-swift/releases

**Comment by hboon** [comment]
Try this:

```
bundle
bundle exec pod install
```

It looks like your Cocoapods version is 1.12.0 instead of `1.11.3` (as reflected in our `Podfile.lock`). It's best that all the gems and pods matches ours.

I use ruby `3.0.3`, but `3.4.10` should work fine as long as the gems install and run properly

**Comment by akhilccrb** [comment]
Is that mandatory to use same versions ?

**Comment by hboon** [comment]
It's not mandatory, but those are the versions we use, develop and test against. If you can run but not archive, then it's progress. When archiving, what does the errors say?

**Comment by akhilccrb** [comment]
Same error Undefined symbol. How can i update realm pod in AlphaWalletFoundation.podspec ( currently using spec.dependency 'RealmSwift', '10.27.0' ). I need to use exact commit so what change i need to do ?

**Comment by hboon** [comment]
Hi there! Just found it might be an issue introduced recently. Let me check this first.

**Comment by hboon** [comment]
Turns out, we haven't done an archive with Xcode 14.2 yet. Would you try with `14.0.1` instead. Sorry about that.

No wonder I didn't update `.xcode-version` :) — #6690 . We'll probably switch to 14.3 in the near future after we confirm it works.

**Comment by akhilccrb** [comment]
Any chance to SwiftUi or Storyboards ?

**Comment by eviltofu** [comment]
> Any chance to SwiftUi or Storyboards ?

No

**Comment by hboon** [comment]
Closing. Solution: https://github.com/AlphaWallet/alpha-wallet-ios/issues/6689#issuecomment-1512445409

**Comment by akhilccrb** [comment]
You cant close the issue , because from Apr 25 you need to archive using Xcode 14.1+ version.  So your not using Xcode new versions , is that a solution ?

**Comment by akhilccrb** [comment]
Still same issue @hboon

**Comment by hboon** [comment]
Will check soonish

**Comment by hboon** [comment]
@akhilccrb We'll test it out a bit more, but you can use #6740 first if you are in a hurry

**Comment by akhilccrb** [comment]
It worked for me ,

Updated to 'RealmSwift', '10.36.0'
