### ISSUE TITLE
Handle long request retry time 

### ISSUE THREAD

**Issue by oa-s** [AlphaWallet/alpha-wallet-ios#6773]
Coingecko api returns retry time of 600 seconds

@hboon  do we need to drop request when its timeout is less than retry time?

**Comment by hboon** [comment]
What is this "timeout" referring to?

**Comment by oa-s** [comment]
timeout - `timeout Interval For Request`

**Comment by hboon** [comment]
They aren't related right? See if these definitions are correct? —

* Timeout — we send a request and start waiting for a response. The max time we wait before dropping it is the timeout. This might be say, 1 to 10 seconds
* Time to retry returned by CoinGecko — this is the time that CoinGecko says we should hold off before making requests again. In other words, we are rate limited. This could be say, 600 seconds

**Comment by oa-s** [comment]
> See if these definitions are correct? 

yes, they are
