### ISSUE TITLE
Getting error trying to Speed up EIP-1559 transaction "replacement transaction underpriced" on Goerli

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#6822]
1. Enable EIP-1559
2. Send ERC20 on Goerli with low gas price
3. Speed up and confirm transaction and it shows "replacement transaction underpriced"

Running f99b39735966ee3a05006224dd997d6a97e17962

<img width='200' src='https://github.com/AlphaWallet/alpha-wallet-ios/assets/56189/c14d88cf-6863-4d62-bd45-057810849c91'>

**Comment by oa-s** [comment]
facing the same with disabled EIP-1559
