### ISSUE TITLE
A question about MPCVault

### ISSUE THREAD

**Issue by johnnynanjiang** [AlphaWallet/alpha-wallet-ios#6984]
Hi AlphaWallet,

I have to post my question here since there is no `discussion` section

Can you please help clarify what MPC-based vault is in this article about Alpha Wallet?

`This is the first Ethereum wallet to incorporate a Secure Enclave, an easy-to-use key backup, and a recovery system. It provides great customer support, hardware wallet accounts for its most demanding customers, an MPC-based vault, smart-contract accounts to batch transactions for various purposes, and secure peer-to-peer communication.` at https://nftsdaily.io/nft-wallet/alphawallet/

Thanks and regards,

**Comment by hboon** [comment]
Hi @johnnynanjiang thanks for the interest. AlphaWallet doesn't have built-in support for MPC-based vault atm. AFAIK, I thought you were the one who was exploring it :)

**Comment by johnnynanjiang** [comment]
> Hi @johnnynanjiang thanks for the interest. AlphaWallet doesn't have built-in support for MPC-based vault atm. AFAIK, I thought you were the one who was exploring it :)

Thanks @hboon for replying.

Yes we are exploring MPC options on AlphaWallet codebase, will definitely get back to you once we have a promising solution.

Not sure how this article mentions about MPC vault at https://nftsdaily.io/nft-wallet/alphawallet/, never mind, thanks for clarifying.
