### ISSUE TITLE
Translate tokenId in metadata link

### ISSUE THREAD

**Issue by JamesSmartCell** [AlphaWallet/alpha-wallet-ios#6997]
Hi @hboon were you aware of this nuance:

https://github.com/AlphaWallet/alpha-wallet-android/issues/3309

In summary:

> When you call uri in an ERC-1155 NFT contract it [can] returns something like:
>
> [https://game.example/api/item/{id}.json](https://game.example/api/item/%7Bid%7D.json)

Here's the excerpt from the docs:

> Metadata
>
>The URI value allows for ID substitution by clients. If the string {id} exists in any URI, clients MUST replace this with the actual token ID in hexadecimal form. This allows for a large number of tokens to use the same on-chain string by defining a URI once, for that large number of tokens.
>
>- The string format of the substituted hexadecimal ID MUST be lowercase alphanumeric: [0-9a-f] with no 0x prefix.
>- The string format of the substituted hexadecimal ID MUST be leading zero padded to 64 hex characters length if necessary.
>
>Example of such a URI: https://token-cdn-domain/{id}.json would be replaced with https://token-cdn-domain/000000000000000000000000000000000000000000000000000000000004cce0.json if the client is referring to token ID 314592/0x4CCE0.

**Comment by hboon** [comment]
@JamesSmartCell yeah, we have https://github.com/AlphaWallet/alpha-wallet-ios/blob/1f0a527326df8dbddd116d38c219bd8357a15026/modules/AlphaWalletWeb3/AlphaWalletWeb3/ContractMethodCalls/Erc721TokenUriMethodCall.swift#L108-L107

**Comment by JamesSmartCell** [comment]
Ok then.
