### ISSUE TITLE
No such module 'AlphaWalletShareExtensionCore' ios code

### ISSUE THREAD

**Issue by medeirosfalante2** [AlphaWallet/alpha-wallet-ios#7100]
i follow the readme install xcode but i have a erro  No such module 'AlphaWalletShareExtensionCore' ios code

I use Sonoma and xcode 15.3 in M3

**Comment by hboon** [comment]
@medeirosfalante2 it's in the modules directory [here](https://github.com/AlphaWallet/alpha-wallet-ios/tree/0f418bd373e0f3e2e8bcf122d8567914d13bbba7/modules/AlphaWalletShareExtensionCore/AlphaWalletShareExtensionCore)

**Comment by mikesomov** [comment]
Got the same error while trying to run the build. Would you be so kind as to explain what particular actions I should make to fix it. AlphaWalletShareExtensionCore.h does exist in the modules directory but Xcode keeps saying "No such module 'AlphaWalletShareExtensionCore"
Thank you
