### ISSUE TITLE
Bug Report - Blank page after click ERC20 token.

### ISSUE THREAD

**Issue by medeirosfalante2** [AlphaWallet/alpha-wallet-ios#7107]
name: Bug Report
about: Using AlphaWallet, but it's not working as you expect?

---

**Describe the bug**

**Steps to reproduce (REQUIRED)**
Steps to reproduce the behavior

1. Tap Wallet tab
2. Tap token Detail

After open the USDT on ETH network i have this page in blank, anothers token have a same problem.

<img width="403" alt="Screenshot 2024-04-01 at 10 55 37" src="https://github.com/AlphaWallet/alpha-wallet-ios/assets/151318142/e9141bf2-1d45-4000-a576-9b06b9c9bf6f">

**Comment by hboon** [comment]
Aware of this one. Will hunt it down. Thanks.

**Comment by medeirosfalante2** [comment]
I try check find the bug, but i dont have experience in swift a lot, but the problem is exclusive for erc20, probole problem in constraint.

**Comment by hboon** [comment]
Fixed
