### ISSUE TITLE
my funds were stolen

### ISSUE THREAD

**Issue by h1hj** [AlphaWallet/alpha-wallet-ios#7121]
name: Bug Report
about: Using AlphaWallet, but it's not working as you expect?

---

**Describe the bug**
my funds were moved without my consent what can i do?

**Comment by AW-STJ** [comment]
this means your wallet was compromised by either you signing malicious links or with sharing private keys/seedphrases. There is nothing we can do.

Advise you to create a new wallet, transfer funds and make sure you never share your backed up keys with anyone else.
