### ISSUE TITLE
Touch ID confirmation before signing

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#721]
James Brown on Telegram: "Should we be using fingerprint to unlock each usage of private key on the app?"

Sounds like a good thing to have?

**Comment by colourful-land** [comment]
@hboon how does touch ID work?

If it does release an encryption key, then the private key can be encrypted normally, and unencrypt when the user touches. It's a false sense of security but better than entirely unencrypted key?

**Comment by hboon** [comment]
@colourful-land There are 2 main ways Touch ID/Face ID affects apps and data:

A) Files on iOS and Keychain [1] records are protected by what Apple calls Data Protection which basically encrypts each file with a separate key based on the Data Protection class set. They are:

* Available when unlocked
* While locked (only for files, not keychain)
* After first unlock
* Always (not encrypted)
* Passcode enabled (passcode can be disabled completely on iOS. Only for keychain, not files)

The Secure Enclave (coprocessor with dedicated hardware for cryptographic functions) processes fingerprint and face data.

Using Touch ID, Face ID or entering the passcode successfully performs the unlocking (i.e. scan a fingerprint/face and unlocks the phone). 

This is a good Apple doc for all things security about iOS systems: https://www.apple.com/business/site/docs/iOS_Security_Guide.pdf

B) While the app is running and active on the screen, the system must have been unlocked already, so all the data are accessible to the user (except for data set to the "Passcode enabled" class, because the user might have disabled passcode on iOS). The only API available for 3rd party developers to access Touch ID/Face ID (not passcode) is the one to show the system provided UI for prompting to scan a fingerprint or face and get back an `authorized` or `not authorized` result. It's a high level API, we don't get access to any keys.

ie. the API is like this:

    result = callAppleAPIToShowTouchIDOrFaceID
    if result == "authorized" {
        //yeah, user has proven himself, we'll use the ethereum private key to sign a transactionc
    } else {
        //nope
    }

So in a way, it is a false sense of security, because the user's encrypted data has already been decrypted (or at least the keys to decrypt them has been released already) and available to the app (though not available to other apps due to sandboxing), so a bug in the app's code could have used the private key anyway without user successfully authenticating via Touch ID/Face ID. But yes, it's better than nothing because I could have unlocked the phone and passed to a friend, but they wouldn't be able to sign the transaction using my key.

[1] Keychain is primarily a secure key-value pair database, eg. for user/passwords and public/private keys. It doesn't only store keys

**Comment by hboon** [comment]
I’m wrong. Will update comment soon.

**Comment by hboon** [comment]
@colourful-land Here's the part I missed:

> Keychains can use access control lists (ACLs) to set policies for accessibility and authentication requirements. Items can establish conditions that require user presence by specifying that they can’t be accessed unless authenticated using Touch ID, Face ID, or by entering the device’s passcode.

C) So we can specify that when we programmatically access the password used to encrypt the private key, iOS prompts for a fingerprint/face scan and fallback to user passcode and not release the password (and thus access to the private key) unless the user is authenticated. We can set how long this access is granted — ranging from 0 seconds to up to a system defined maximum.

So going by the doc, it is secured.

**Comment by hboon** [comment]
Supported with #1272
