### ISSUE TITLE
Translate Asset Definition Overrides screen title

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#734]
This line:

    "a.help.assetDefinitionOverrides.title" = "Asset Definition Overrides";

This is the title shown in the screenshot. It refers to the overridden XML files that describe how the token should be displayed and how it works.

At: https://github.com/alpha-wallet/alpha-wallet-ios/blob/master/AlphaWallet/Localization/zh-Hans.lproj/Localizable.strings#L237

![img_78a8581913e6-1](https://user-images.githubusercontent.com/56189/45891925-5546a680-bdf9-11e8-86b7-b2577b4a58ef.jpeg)

**Comment by bootingman** [comment]
sorry, I have not checked the github issues for days, I will check daily.

update the L238 translation
