### ISSUE TITLE
Add EIP712 Compliance

### ISSUE THREAD

**Issue by JamesSmartCell** [AlphaWallet/alpha-wallet-ios#760]
See -

https://medium.com/metamask/eip712-is-coming-what-to-expect-and-how-to-use-it-bb92fd1a7a26

it's a new standard for transparency when doing a request to sign in the DApp browser. So far no wallet implements it but it is coming soon in Metamask.

**Comment by colourful-land** [comment]
I'm sure it needs to be implemented but it is more like a project than a task? Will look at the spec.

**Comment by James-Sangalli** [comment]
This is already implemented in iOS, see .typedMessage
