### ISSUE TITLE
CryptoKitty incomplete data becomes available after transfer

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#763]
Think we can report it as a bug to OpenSea @James-Sangalli ?

Reported by @zhangzhongnan928

**Comment by James-Sangalli** [comment]
@hboon , you are telling me that the kitties exist once you transfer them out of your wallet?

**Comment by zhangzhongnan928** [comment]
pull data from cryptokitties directly is a better option or not?

Regards,
[image: AlphaWallet] <https://awallet.io/>

*Victor Zhang*

[image: AlphaWallet Github] <https://github.com/alpha-wallet> [image:
AlphaWallet Twitter] <https://twitter.com/Alpha_wallet> [image: AlphaWallet
Reddit] <https://www.reddit.com/r/AlphaWallet> [image: AlphaWallet Facebook]
<https://www.facebook.com/AlphaWallet/> [image: AlphaWallet Youtube]
<https://www.youtube.com/channel/UCPP12PQeQmQ4_6qXzNvZw-w/> [image:
AlphaWallet Linkedin] <https://www.linkedin.com/company/%CE%B1wallet/> [image:
AlphaWallet Weibo] <https://weibo.com/AlphaWallet>
Join our Telegram group. <https://t.me/AlphaWalletGroup>

**Comment by zhangzhongnan928** [comment]
I just transferred another "incomplete data" kitty to my friend, and it becomes available on his phone.
I still have one  "incomplete data" kitty on my phone.

**Comment by James-Sangalli** [comment]
Reported to opensea

**Comment by James-Sangalli** [comment]
Up to opensea to fix this now.

**Comment by zhangzhongnan928** [comment]
B)

I used to have 5 kitties, I transferred out 2 kitties, now have only 3 in
my wallet.


Regards,
[image: AlphaWallet] <https://awallet.io/>

*Victor Zhang*

[image: AlphaWallet Github] <https://github.com/alpha-wallet> [image:
AlphaWallet Twitter] <https://twitter.com/Alpha_wallet> [image: AlphaWallet
Reddit] <https://www.reddit.com/r/AlphaWallet> [image: AlphaWallet Facebook]
<https://www.facebook.com/AlphaWallet/> [image: AlphaWallet Youtube]
<https://www.youtube.com/channel/UCPP12PQeQmQ4_6qXzNvZw-w/> [image:
AlphaWallet Linkedin] <https://www.linkedin.com/company/%CE%B1wallet/> [image:
AlphaWallet Weibo] <https://weibo.com/AlphaWallet>
Join our Telegram group. <https://t.me/AlphaWalletGroup>

**Comment by hboon** [comment]
Ah. Good. Thanks
