### ISSUE TITLE
Paymaster service times out with vodaphone 4G

### ISSUE THREAD

**Issue by colourful-land** [AlphaWallet/alpha-wallet-ios#766]
[video.zip](https://github.com/alpha-wallet/alpha-wallet-ios/files/2424177/video.zip)

@zhangzhongnan928 said "On iOS, after the 1min wait for import page to show up, it shows purchase instead of import, is that means the gas paid by me instead of payment server?"

**Comment by miang719** [comment]
@colourful-land take a look

**Comment by James-Sangalli** [comment]
@colourful-land any updates on this? Actually others are interested in the idea of a payment server too

**Comment by James-Sangalli** [comment]
Solved with AWS Load balancer. https://github.com/AlphaWallet/alpha-wallet-ios/pull/1205
