### ISSUE TITLE
Check DApp transaction gas limit

### ISSUE THREAD

**Issue by JamesSmartCell** [AlphaWallet/alpha-wallet-ios#768]
Most DApp transaction builders leave out gas limit. When you form the transaction normally gas limit = 0 gets built into the transaction. This always fails.

I notice metamask takes a '0' gas limit in the DApp transaction to mean that the wallet should use it's own default value.

You can test it on Tenzorum's TENZ-ID site here:

https://tenzorum.org/tenz_id/

try to register an ENS. You can test with testnet crypto - the gas limit gets added the same way. Even with testnet the website will report success.

I modified Android DApp browser to detect the zero gas limit and replace with the current gas limit setting.

**Comment by James-Sangalli** [comment]
@JamesSmartCell are you suggesting that the wallet sometimes sends tx with no gas?

**Comment by JamesSmartCell** [comment]
yes that exactly it. Victor checked and AlphaWallet iOS failed to push the transaction because it sends tx with zero gas.

The JS in the website should be fixed to include the gas limit, however, it's not important to be right (push the transaction with zero gas because the JS told me to) only that our wallet works when people are trying to do things.

It seems that Metamask will interpret zero gas limit with the wallet default. If user tries on our wallet it just fails, if they try on Metamask it works, the developer of the website will just recommend people to use Metamask only rather than fixing their site.

I'll try to find the forum post but Bitforward say exactly this when people are struggling to use their new ENS system - only metamask works and they don't know why. I left a post with how to fix their gas setup but they don't need to take any action because it works on Metamask.

**Comment by James-Sangalli** [comment]
@JamesSmartCell @zhangzhongnan928 it seems that they have fixed this because it is working on my side (See screenshot below) 
![unnamed 1](https://user-images.githubusercontent.com/16630514/46287709-01388080-c5b6-11e8-9ba7-0248afde0269.jpg)

**Comment by zhangzhongnan928** [comment]
@JamesSmartCell @James-Sangalli > AlphaWallet iOS failed to push the transaction because it sends tx with zero gas.

Not because of zero gas, because not enough gas, by default iOS provide 90000 gas limit, but transection cost more than 140000 gas, 
so the first transection failed:
https://etherscan.io/tx/0x77ab9d892f6ed32eb486d8957960a591dde2c2b92f208f09f9d6a11d0f07096b

the 2nd transection, I doubled the gas limit and it went through
https://etherscan.io/tx/0x593bb9527b1426bf246201ab8dc758908a489d46c6af9c7fc96738f7191f424a

**Comment by miang719** [comment]
@hboon @James-Sangalli take a look

**Comment by James-Sangalli** [comment]
Will attempt using this: web3.eth.estimateGas
