### ISSUE TITLE
Missing translations in es, ja, ko

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#774]
Some missing translations for `es`, `ja`, `ko`:

"transactions.received.ether" = "You have received %@ ETH";
"transactions.received.ether.notification.prompt" = "Allow Notifications When You Receive Ether?";
"browser.history.confirm.delete.title" = "Are you sure you would like to delete?";
"browser.noHistory.label.title" = "No history yet";
"browser.bookmarks.confirm.delete.title" = "Are you sure you would like to delete this bookmark?";
"browser.noBookmarks.label.title" = "No bookmarks yet!";
"browser.url.textfield.placeholder" = "Search or enter website URL";
"transaction.cell.availableButDataUnavailable.title" = "Incomplete Data";
"a.help.assetDefinitionOverrides.title" = "Asset Definition Overrides";

**Comment by James-Sangalli** [comment]
Noted, can be updated in the next translation round
