### ISSUE TITLE
Security alert SNS

### ISSUE THREAD

**Issue by colourful-land** [AlphaWallet/alpha-wallet-ios#786]
1. iOS app should automatically acquire an SNS endpoint (register if non-existed, enable if it is disabled).

2. iOS app should subscribe to the security SNS topic (fill in the SNS topic ID here) if not already.

3. iOS app should display an alert if the current version matches the alert's version. (We will leave the matching rule to the later stage).

**Comment by James-Sangalli** [comment]
@colourful-land started [here](https://github.com/AlphaWallet/alpha-wallet-ios/tree/sns-experiments)

**Comment by colourful-land** [comment]
Deleted Nervos Project 𝑙𝑎𝑏𝑒𝑙 because now it is managed by Nervos Project 𝑝𝑟𝑜𝑗𝑒𝑐𝑡.
