### ISSUE TITLE
SNS rego is causing a crash

### ISSUE THREAD

**Issue by James-Sangalli** [AlphaWallet/alpha-wallet-ios#791]
To reproduce: 

- Delete the app on your device
- Build it 
- Click on the wallet address tab and approve the notifications permission
- App will crash

@hboon any hunches?

**Comment by hboon** [comment]
@James-Sangalli No. But maybe good to hold the app submission first?

**Comment by hboon** [comment]
@James-Sangalli took a quick peek. We need to restore the body of `cognitoRegistration()` and call it before `AWSSNS.default()`. The "cognito" in there is a misnomer (and partly my bad!), it performs configuration for setting up the value defined in the constant `identityPoolId` etc.

Now we know what it's for :P

**Comment by hboon** [comment]
If you set into `AWS.default()`, the library's code throws an exception which explains the error. Seems not obvious otherwise.

**Comment by James-Sangalli** [comment]
@hboon thanks, however it seems that it has something to do with info.plist

`Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'The service configuration is `nil`. You need to configure `awsconfiguration.json`, `Info.plist` or set `defaultServiceConfiguration` before using this method.`

**Comment by hboon** [comment]
@James-Sangalli yes, and `cognitoRegistration()` sets `defaultServiceConfiguration`.
