### ISSUE TITLE
Signing is not working correctly in the dapp browser

### ISSUE THREAD

**Issue by James-Sangalli** [AlphaWallet/alpha-wallet-ios#792]
ecrecover fails on xcontract

**Comment by James-Sangalli** [comment]
@hboon please check this out with me as it is very important

**Comment by James-Sangalli** [comment]
@hboon see PR, the issue appears to be that web3.eth.sign in xcontract was hashed, our code double hashed it when instead it should have simply signed the hash directly.

web3.js does not have a method to verify, thus the code must first hash the message then perform verification in xcontract

**Comment by hboon** [comment]
And this for converting it to "readable" string https://github.com/TrustWallet/trust-wallet-ios/blob/master/Trust/Transfer/Coordinators/SignMessageCoordinator.swift#L70
