### ISSUE TITLE
5.8-inch Display on App Store

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/alpha-wallet-ios#802]
Please use below picture to replace the current 5.8-inch Display,
![1](https://user-images.githubusercontent.com/33795543/46567993-a49be380-c970-11e8-9544-0677aca35f10.PNG)
![2](https://user-images.githubusercontent.com/33795543/46567994-a49be380-c970-11e8-81df-a5927b761dcc.PNG)
![3](https://user-images.githubusercontent.com/33795543/46567995-a5347a00-c970-11e8-8351-4532f434ea7a.PNG)
![4](https://user-images.githubusercontent.com/33795543/46567996-a5347a00-c970-11e8-882b-22f09a0cf81c.PNG)
![5](https://user-images.githubusercontent.com/33795543/46567997-a5347a00-c970-11e8-8309-6c9ac08a74db.PNG)
![6](https://user-images.githubusercontent.com/33795543/46567998-a5cd1080-c970-11e8-917a-24e36e1188c7.PNG)
![7](https://user-images.githubusercontent.com/33795543/46567999-a5cd1080-c970-11e8-836b-3bd3a4511f62.PNG)
![8](https://user-images.githubusercontent.com/33795543/46568195-6c49d480-c973-11e8-9b49-cd116cd3dfaf.PNG)
![9](https://user-images.githubusercontent.com/33795543/46568201-884d7600-c973-11e8-9a12-b3afae3451d6.PNG)
![10](https://user-images.githubusercontent.com/33795543/46568202-884d7600-c973-11e8-974d-e417b9d7679e.PNG)

**Comment by James-Sangalli** [comment]
@zhangzhongnan928 this requires a new submission, will do it on the next one.

**Comment by James-Sangalli** [comment]
Included in next submission
