### ISSUE TITLE
iPad 12.9-inch Display

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/alpha-wallet-ios#803]
Please replace iPad Display in App Store
![img_0278](https://user-images.githubusercontent.com/33795543/46568228-eed29400-c973-11e8-879c-26e4a059f533.PNG)
![img_0279](https://user-images.githubusercontent.com/33795543/46568229-eed29400-c973-11e8-9562-1248eb8cac1d.PNG)
![img_0281](https://user-images.githubusercontent.com/33795543/46568230-eed29400-c973-11e8-8636-ba6bf9834de3.PNG)
![img_0283](https://user-images.githubusercontent.com/33795543/46568231-ef6b2a80-c973-11e8-8b07-843019d3dcbd.PNG)
![img_0284](https://user-images.githubusercontent.com/33795543/46568232-ef6b2a80-c973-11e8-99b5-e7784a35c083.PNG)
![img_0285](https://user-images.githubusercontent.com/33795543/46568251-26d9d700-c974-11e8-8936-9f25336b32df.PNG)
![img_0286](https://user-images.githubusercontent.com/33795543/46568252-27726d80-c974-11e8-92be-6b4a14773cb6.PNG)
![img_0287](https://user-images.githubusercontent.com/33795543/46568253-27726d80-c974-11e8-9ea5-d8a72aaf94c4.PNG)

**Comment by colourful-land** [comment]
What do you want booh or Sangalli to do?

a) upload the iphone screenshot as the screenshot for ipad.
b) get Doralin to make a design compatible with iPad (reactive design) and upload the design.
c) same as b, but do it when the design is actually implemented.

**Comment by James-Sangalli** [comment]
In submission
