### ISSUE TITLE
display issues with iPad 

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/alpha-wallet-ios#804]
![img_0280](https://user-images.githubusercontent.com/33795543/46568263-6b657280-c974-11e8-8ef1-b6504cc077c3.PNG)

this QR code used to be full of screen
![img_0282](https://user-images.githubusercontent.com/33795543/46568279-8afc9b00-c974-11e8-84a1-f5166e5d67a9.PNG)

**Comment by hboon** [comment]
@zhangzhongnan928 The distorted ERC721 image issue has been fixed in a recent TestFlight version.

Do you still want to make the QR code occupy the same width? Might be harder to scan because the user doing the scanning has to hold the scanner further away, especially for 12.9"

**Comment by zhangzhongnan928** [comment]
no, all good now
