### ISSUE TITLE
DApp Sign transaction not working correctly

### ISSUE THREAD

**Issue by JamesSmartCell** [AlphaWallet/alpha-wallet-ios#805]
New issue with signing a hex string using 'SignMessage' - the signature is no longer working; behaviour has changed since the last build.

To reproduce: attempt to use the office door dapp. It works correctly with Metamask and AlphaWallet Android.

**Comment by hboon** [comment]
@JamesSmartCell it has indeed changed to be more forgiving, implementing the check that you suggested. Which build did you test with?

**Comment by hboon** [comment]
Fixed with #807
