### ISSUE TITLE
Get listed on dapp provider sites - WIP

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#808]
Probably even better once we can display them like CryptoKitties

**Comment by hboon** [comment]
I couldn't have picked a worse example. EverDragons is one of those tokens that OpenSea doesn't return any useful data for. But yes, dapps like this that are better supported.

**Comment by hboon** [comment]
Here's a number of tokens we have better support for:

0xf5b0a3efb8e8e4c201e2a935f110eaaf3ffecb8d - Axie
0xf7a6e15dfd5cdd9ef12711bd757a9b6021abf643 - CryptoBots
0x87d598064c736dd0c712d329afcfaa0ccc1921a1 - CryptoFighters
0x06012c8cf97bead5deae237070f9587f8e7a266d - CryptoKitties
0xabc7e6c01237e8eef355bba2bf925a730b714d5f - CryptoSaga
0xdcaad9fd9a74144d226dbf94ce6162ca9f09ed7e - CryptoStrikers
0xBfdE6246Df72d3ca86419628CaC46a9d2B60393C - EtheremonAdventure 
0x995020804986274763df9deb0296b754f2659ca1 - EtherTuplis
0x6ebeaf8e8e946f0716e6533a6f2cefc83f60e8ab - Gods Unchained
0x7fdcd2a1e52f10c28cb7732f46393e297ecadda1 - HyperDragon
0x8c9b261faef3b3c2e64ab5e58e04615f8c788099 - MLBCB
0x273f7f8e6489682df756151f5525576e322d51a3 - MyCryptoHeroes
0x9d9c250311b65803c895cc77f878b8092019dedc - Player Tokens
0x5caebd3b32e210e85ce3e9d51638b9c445481567 - War Riders

**Comment by James-Sangalli** [comment]
@zhangzhongnan928 since you are buying these collectables and posting them on twitter, you can use these as a reference (especially as many do not have email addresses)

**Comment by zhangzhongnan928** [comment]
yes, we are on some of them already like 
https://multitoken.com/
<img width="1328" alt="screen shot 2018-10-26 at 5 39 03 pm" src="https://user-images.githubusercontent.com/33795543/47558643-31b9d300-d946-11e8-9232-2fabfd7cee1a.png">
better we can let those DApps recognize our wallet as AlphaWallet, currently most them recognize us MetaMask or unknow wallet.

**Comment by hboon** [comment]
@James-Sangalli Bump. Be particularly good when both iOS and Android get `isAlphaWallet = true` in.

**Comment by James-Sangalli** [comment]
@zhangzhongnan928 any updates on this?

**Comment by zhangzhongnan928** [comment]
https://github.com/AlphaWallet/private-activities/issues/27

 give me a short instruction(both Andriod and iOS) which I will pass to all the DApps, to make sure they display our wallet name and logo correctly.

		
Victor Zhang
CEO, AlphaWallet
							
A 1000 DApps in your pocket — Why a wallet is so much more than an app to hold keys by James Sangalli https://t.co/BNjaA6ob2e	Read More
