### ISSUE TITLE
Bug report for OpenSea: URLs Etheremon (EMONA) are wrong in the API results

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#809]
URLs Etheremon (EMONA) are returned in the API results as

https://www.etheremon.com/#/mons/2

They should be:

https://www.etheremon.com/mons/2

**Comment by James-Sangalli** [comment]
Moved to here: https://github.com/ProjectOpenSea/opensea-js/issues/2 @hboon please make such issues there next time. Cheers.
