### ISSUE TITLE
Shall we support ENS in AlphaWallet?

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/alpha-wallet-ios#810]
It seems to be an better UX service. 

This issue is considered solved if the first of the following is satisfied and the 2nd. Victor will create new issue for 3rd, 4th if/when he sees the needs.

1) when a user sends token or ether to another, he or she can type the ENS instead of an address.
2) when a user goes to his wallet settings, he can see his own wallet labelled in ENS fashion.
3) when a user receives a token or ether it is displayed as the ENS if applicable.
4) when a user goes to his wallet asset list, he can see his name as an asset.
5) when a user wants to get an ENS for his wallet he can do so by acoomplishing a mobile journey.

**Comment by dtbx** [comment]
Agree, would help using services like [tenzID](tenzorum.org/tenz_id) to transact between account.

**Comment by zhangzhongnan928** [comment]
@hboon @JamesSmartCell

**Comment by zhangzhongnan928** [comment]
@hboon @JamesSmartCell 
Seems to be a nice function. 
Any feedbacks?

**Comment by hboon** [comment]
Yes, sounds good. We should also do reverse resolutions and display the wallet names in Settings > Wallets.

Any concerns, @colourful-land ?

**Comment by colourful-land** [comment]
@hboon Yes. There are a lot of user experience issues that need to be considered. e.g. should we display ENS over 0x..., should we copy 0x... when the user holds on ENS, should we list ENS as an asset (if it can be sold and bought by detaching and reattaching to a different name), are other wallets supporting it too. Might need to get @farrahfazirah involved. Updated the main description to provide clarity.

**Comment by James-Sangalli** [comment]
@hboon working on a simple implementation that will allow the user to simply enter an ENS name instead of an address

**Comment by zhangzhongnan928** [comment]
Stage 1 for ENS,  don’t change any UI/UX, just allow user to send through ENS or wallet address. 
All the other flow remain the same. No design required. 





		
Victor Zhang
CEO, AlphaWallet
							
A 1000 DApps in your pocket — Why a wallet is so much more than an app to hold keys by James Sangalli https://t.co/BNjaA6ob2e	Read More

**Comment by zhangzhongnan928** [comment]
![37c9f1b1-c166-4468-befe-cd184fef3d29](https://user-images.githubusercontent.com/33795543/48189923-405bad80-e37c-11e8-9362-e37650d63c7d.jpeg)

This is interesting, but not very useful. I need to use URL to browse the right website, but it not interesting to know how many URL or domains are linked to the IP address. 

The wallet address I use now linked to 5 or 6 different ENS.

**Comment by James-Sangalli** [comment]
Implemented in rudimentary form in iOS
