### ISSUE TITLE
Build 1.25(231) Magiclink not working

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/alpha-wallet-ios#824]
Importing page show up, shows all good on app. 
But for mainnnet token, can not find any transection records on etherscan 
Payment server didn’t broadcast the transection at all. 

For ropsten, can find record, transection failed. 
User broadcast the transection, then fail. 
![f5da6dd7-1edd-43cf-961e-e0e7e2dfb247](https://user-images.githubusercontent.com/33795543/47262934-d6dc4200-d527-11e8-8203-9132e32ec2e8.png)

**Comment by James-Sangalli** [comment]
@zhangzhongnan928 first issue is solved, the paymaster was low on ether

**Comment by zhangzhongnan928** [comment]
Is that because, Ropsten tried to upgrade to the new version of ethereum
but failed.


Regards,
[image: AlphaWallet] <https://awallet.io/>

*Victor Zhang*

[image: AlphaWallet Github] <https://github.com/alpha-wallet> [image:
AlphaWallet Twitter] <https://twitter.com/Alpha_wallet> [image: AlphaWallet
Reddit] <https://www.reddit.com/r/AlphaWallet> [image: AlphaWallet Facebook]
<https://www.facebook.com/AlphaWallet/> [image: AlphaWallet Youtube]
<https://www.youtube.com/channel/UCPP12PQeQmQ4_6qXzNvZw-w/> [image:
AlphaWallet Linkedin] <https://www.linkedin.com/company/%CE%B1wallet/> [image:
AlphaWallet Weibo] <https://weibo.com/AlphaWallet>
Join our Telegram group. <https://t.me/AlphaWalletGroup>
