### ISSUE TITLE
Supporting ERC721 transfers

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#830]
http://erc721.org and https://github.com/ethereum/EIPs/blob/master/EIPS/eip-721.md specifies:

    function safeTransferFrom(address _from, address _to, uint256 _tokenId, bytes data) external payable;
    function safeTransferFrom(address _from, address _to, uint256 _tokenId) external payable;
    function transferFrom(address _from, address _to, uint256 _tokenId) external payable;

CryptoKitty itself implements:

    function transfer(address _to, uint256 _tokenId) external;
    function transferFrom(address _from, address _to, uint256 _tokenId) external;

Also compare 

https://etherscan.io/address/0xBfdE6246Df72d3ca86419628CaC46a9d2B60393C#code
vs
https://etherscan.io/address/0x8c9b261faef3b3c2e64ab5e58e04615f8c788099#code

**Comment by James-Sangalli** [comment]
@hboon do some contracts only implement safeTransfer or vice versa?

**Comment by hboon** [comment]
@James-Sangalli I checked a few and they have `safeTransferFrom()`. So maybe run `safeTransferFrom()` and if it fails try `transfer()`?

**Comment by James-Sangalli** [comment]
@hboon wouldn't it be better to simply implement safety on our client side? i.e. no sending to null address etc

**Comment by hboon** [comment]
@James-Sangalli The check for null address should be good to add here and across the app. I think we might already have that even. Remember checked and unchecked address which you added?

But it's still better to call the safeTransfer version because it implements additional checks like if the sender is an authorized operator or the approved address which might be hard or impossible to implement client side. And I suppose implementors of ERC721 might decide to add another check into the safeTransfer function which we wouldn't know about and skip it in the non-safe version:

> /// @notice Transfers the ownership of an NFT from one address to another address
> /// @dev Throws unless `msg.sender` is the current owner, an authorized
> ///  operator, or the approved address for this NFT. Throws if `_from` is
> ///  not the current owner. Throws if `_to` is the zero address. Throws if
> ///  `_tokenId` is not a valid NFT. When transfer is complete, this function
> ///  checks if `_to` is a smart contract (code size > 0). If so, it calls
> ///  `onERC721Received` on `_to` and throws if the return value is not
> ///  `bytes4(keccak256("onERC721Received(address,address,uint256,bytes)"))`.
> /// @param _from The current owner of the NFT
> /// @param _to The new owner
> /// @param _tokenId The NFT to transfer
> /// @param data Additional data with no specified format, sent in call to `_to`
> function safeTransferFrom(address _from, address _to, uint256 _tokenId, bytes data) external payable;
