### ISSUE TITLE
Strange issues when transferring different ERC 721 tokens from address A to address A

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/alpha-wallet-ios#833]
same address from and to, transaction will fail

**Comment by hboon** [comment]
@zhangzhongnan928 which token is that? Could be related to #830

**Comment by zhangzhongnan928** [comment]
Chibi Fighters
https://etherscan.io/tx/0x9e8753be702f56e0a88eeb58cab13cf3cd895842fcf64830cc8c4f851161777d
https://etherscan.io/tx/0x53cb4d58ad96ab950c72f2eb6f029aa4c15e7ab4df82b96076f4975a0198bddf


Regards,
[image: AlphaWallet] <https://awallet.io/>

*Victor Zhang*

[image: AlphaWallet Github] <https://github.com/alpha-wallet> [image:
AlphaWallet Twitter] <https://twitter.com/Alpha_wallet> [image: AlphaWallet
Reddit] <https://www.reddit.com/r/AlphaWallet> [image: AlphaWallet Facebook]
<https://www.facebook.com/AlphaWallet/> [image: AlphaWallet Youtube]
<https://www.youtube.com/channel/UCPP12PQeQmQ4_6qXzNvZw-w/> [image:
AlphaWallet Linkedin] <https://www.linkedin.com/company/%CE%B1wallet/> [image:
AlphaWallet Weibo] <https://weibo.com/AlphaWallet>
Join our Telegram group. <https://t.me/AlphaWalletGroup>

**Comment by hboon** [comment]
@zhangzhongnan928 oh, Chibi Fighters contract doesn't allow transfer to self.

(Note for myself):
    require(_to != ownerOf(_tokenId));

But for other ERC721 contracts, we may have to test through the few more popular ones or look at their code to verify if they work due to #830 because they may not implement transfer-ing the same way.

**Comment by zhangzhongnan928** [comment]
Yes, to other address works fine


Regards,
[image: AlphaWallet] <https://awallet.io/>

*Victor Zhang*

[image: AlphaWallet Github] <https://github.com/alpha-wallet> [image:
AlphaWallet Twitter] <https://twitter.com/Alpha_wallet> [image: AlphaWallet
Reddit] <https://www.reddit.com/r/AlphaWallet> [image: AlphaWallet Facebook]
<https://www.facebook.com/AlphaWallet/> [image: AlphaWallet Youtube]
<https://www.youtube.com/channel/UCPP12PQeQmQ4_6qXzNvZw-w/> [image:
AlphaWallet Linkedin] <https://www.linkedin.com/company/%CE%B1wallet/> [image:
AlphaWallet Weibo] <https://weibo.com/AlphaWallet>
Join our Telegram group. <https://t.me/AlphaWalletGroup>
