### ISSUE TITLE
Shall we not show Ether received notification for 0 ether?

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#839]
Eg. https://etherscan.io/tx/0x5ea28fa49ae55ca8aa6627087acf827ba3aaa04d372170c2e6c59d2eedea3038

This is the HyperDragons contract.

**Comment by James-Sangalli** [comment]
@hboon these transactions are contract transactions, therefore the user will never get such a notification as they have a regular address not a contract one
