### ISSUE TITLE
Next button on ETH page is not working

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/alpha-wallet-ios#856]
![bacea6b3-4cfc-4e7e-bb4c-c2a30ffbe72d](https://user-images.githubusercontent.com/33795543/47614836-2d75ed00-dae1-11e8-8900-4a4302826baf.jpeg)

**Comment by zhangzhongnan928** [comment]
Fixed?

Regards
Victor

**Comment by hboon** [comment]
@zhangzhongnan928 yes.
