### ISSUE TITLE
Broken link in app https://community.awallet.io/c/alphawallet-app/ios-feedback

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#862]
Where should it point to now? 

Maybe:
https://community.alphawallet.com/c/feedback  ?

**Comment by hboon** [comment]
Bump. @bootingman

**Comment by zhangzhongnan928** [comment]
https://community.alphawallet.com/c/feedback/ios-feedback

@hboon should be this one

**Comment by bootingman** [comment]
@hboon 

https://community.alphawallet.com/c/feedback/ios-feedback
