### ISSUE TITLE
Opensea‘s graphic assets seem being blocked by China Firewall 

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/alpha-wallet-ios#867]

**Comment by hboon** [comment]
Oh sorry. I forgot. At least some of those might be hosted on Google servers. Let me check

**Comment by hboon** [comment]
Filed a bug with OpenSea. Let's see what they say.

**Comment by hboon** [comment]
Waiting for a fix/workaround in the API.

**Comment by James-Sangalli** [comment]
Keep discussion open here: https://github.com/ProjectOpenSea/opensea-js/issues/3

**Comment by James-Sangalli** [comment]
Can discuss on other issue.

**Comment by hboon** [comment]
> Can discuss on other issue.

@James-Sangalli which issue are you referring to?

**Comment by James-Sangalli** [comment]
@zhangzhongnan928 @bootingman this is supposed to be fixed now, please test on Chinese internet

**Comment by zhangzhongnan928** [comment]
@bootingman Wen please confirm

**Comment by James-Sangalli** [comment]
@bootingman

**Comment by James-Sangalli** [comment]
@bootingman ??

**Comment by James-Sangalli** [comment]
Verified working by @bootingman
