### ISSUE TITLE
(iOS) XML to have TBML namespace

### ISSUE THREAD

**Issue by colourful-land** [AlphaWallet/alpha-wallet-ios#880]
Test case

1. Copy the following 3 XML files from tbml branch† to mobile phone's storage area, replacing the existing XML files, 

    ./spawnable-contract/schema1/MeetupContract.xml
    ./blockchain-tickets/schema1/blockchain-events-china.xml
    ./blockchain-tickets/schema1/TicketingContract.xml

† https://github.com/AlphaWallet/contracts/tree/tbml

2. Make sure the mobile work as before.

Notice that the same namespace is represented in 3 different shorthands in order to make sure the mobile code does not blindly assume any shorthand.

**Comment by hboon** [comment]
1.26 is the current version we have. So > 1.26 should support it.

Can test with something like: 

```
curl -H "Accept: text/xml; charset=UTF-8" -H "IF-Modified-Since: Mon, 02 Jul 2018 13:23:00 GMT" -H "X-Client-Name: AlphaWallet" -H "X-Client-Version: 1.0.3" -H "X-Platform-Name: iOS" -H "X-Platform-Version: 11.1.2" https://repo.awallet.io/0xd8e5f58de3933e1e35f9c65eb72cb188674624f3
```

**Comment by hboon** [comment]
We should probably standardise our version number format for iOS and Android. Maybe not as far as apply https://semver.org, but at least agree that it's in the format `x.y(.z)?` Helps with parsing on the server side.

**Comment by colourful-land** [comment]
> We should probably standardise our version number format for iOS and Android. Maybe not as far as apply https://semver.org, but at least agree that it's in the format `x.y(.z)?` Helps with parsing on the server side.

Can you file a new issue about that in https://github.com/AlphaWallet/alpha-wallet-android/issues/ where repo server code lies?

**Comment by colourful-land** [comment]
Since we are abandoning awallet.io we will use the method @James-Sangalli suggested:

New builds use repo.attestation.id
Old builds use repo.awallet.io

instead of version numbering.

**Comment by hboon** [comment]
@colourful-land is the new repo at `repo.attestation.id` up?

**Comment by James-Sangalli** [comment]
Keeping issue open until it is working with new server

**Comment by colourful-land** [comment]
> @colourful-land is the new repo at `repo.attestation.id` up?

repo.aw.app is online now. Its XML, however, has not been fully updated to allow ABI embedded in XML, see https://github.com/AlphaWallet/contracts/issues/70

Example: https://repo.aw.app/0xA66A3F08068174e8F005112A8b2c7A507a822335
