### ISSUE TITLE
Integrate Tenzorum-ID

### ISSUE THREAD

**Issue by JamesSmartCell** [AlphaWallet/alpha-wallet-ios#883]
Here's one method (which was used for Android integration):

In summary: 

- Make a list of all wallets you have
- Call Etherscan to fetch all transactions on the Tenz-ID contract, using `&sort=desc` (newer transactions first)
- Parse all `newSubdomain` transactions.
- Extract the `from` transaction field, and parse the `input` field to find the first of the two addresses.
- `from` and the first address need to match any of your wallet addresses, and the transaction must have been processed with no error. These checks are to prevent address spoofing.
- the name is assembled using sub-domain.domain.top-domain, eg james.tenzorum-id.eth
- Only use the first name found, since an address can have multiple aliases. Make assumption user wants to use the latest name (could be selected later perhaps).

To use Tenz-ID in lieu of addresses we use the universal ENS service, which has been there since 2016. This will allow us to use any registered ENS.

In detail:

The two files in Android that handle the process are in TransactionsNetworkClient.java and EtherscanTransaction.java. The TransactionDecoder.java is also used to break down the input into addresses and strings.

Tenz-ID contract on mainnet is here: `0xe47405AF3c470e91a02BFC46921C3632776F9C6b`
The registration function is: `newSubdomain(string ,string,string,address,address)`

Have a look at my application here:
[https://etherscan.io/tx/0x9d86ec6405b244b1c1d18844f288e029aee2cb2dc5a2d0c666494a9bee07f2d4](https://etherscan.io/tx/0x9d86ec6405b244b1c1d18844f288e029aee2cb2dc5a2d0c666494a9bee07f2d4)

Switch to 'decode input data' to see:

Function: newSubdomain(string _subdomain, string _domain, string _topdomain, address _owner, address _target)

# | Name | Type | Data
0 | _subdomain | string | james
1 | _domain | string | tenzorum-id
2 | _topdomain | string | eth
3 | _owner | address | 901dbb9771d30124bd25b2f86ef4d8c6c135d948
4 | _target | address | 901dbb9771d30124bd25b2f86ef4d8c6c135d948

The owner and the target can be different if you have re-assigned your name, but we don't worry about that at the moment. You need to check `_owner` and `from` are the same, to ensure the owner of the account requested this alias (and the function isn't called by a 3rd party in some elaborate spoofing attempt).

Then, pull out the three strings and assemble them like a URL.

I'll cover sending to an address in a different issue, it's considerably more straightforward.

In Android I check the ENS once at startup, and also if the user swipe-refreshes the wallet list, taking into account the last block scanned. If the user imports a new account you need to reset this scan back to block 0 because there could have been a tenz-id entry for the newly added account in the transaction list already scanned.

**Comment by James-Sangalli** [comment]
Related to: #887

**Comment by James-Sangalli** [comment]
Closing this for now, we support sending to an ENS name (see PR) but I am not sure we see the logic for Displaying a big list of ENS names you hold, that would be the same regardless of whether the ENS name is from tenzorum or not. Can re open in future if decided an elegant way to do so.
