### ISSUE TITLE
hiding twitter, facebook and community into one contact us label

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/alpha-wallet-ios#886]
hiding twitter, facebook and community into one contact us label

using https://community.alphawallet.com/ for community

**Comment by hboon** [comment]
I think @farrahfazirah is looking into a redesign/layout of the Settings screen with @James-Sangalli.

@zhangzhongnan928 , @farrahfazirah , @James-Sangalli confirm how to go about this first?
