### ISSUE TITLE
Dapp, https://dapp.originprotocol.com isn't loading in Dapp browser

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/alpha-wallet-ios#898]

**Comment by hboon** [comment]
@zhangzhongnan928 what about it?

**Comment by zhangzhongnan928** [comment]
Not working in our DApp browser 

		
Victor Zhang
CEO, AlphaWallet
							
A 1000 DApps in your pocket — Why a wallet is so much more than an app to hold keys by James Sangalli https://t.co/BNjaA6ob2e	Read More

**Comment by James-Sangalli** [comment]
<img width="1252" alt="screen shot 2018-11-21 at 6 30 53 pm" src="https://user-images.githubusercontent.com/16630514/48835638-a2c09f00-edbb-11e8-897d-bd8f14d8fed8.png">

**Comment by James-Sangalli** [comment]
Working on build 269.
