### ISSUE TITLE
Support EIP1102 aka. Privacy Mode or at least test to verify it doesn't break dapp browser

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#901]
https://eips.ethereum.org/EIPS/eip-1102

https://medium.com/metamask/https-medium-com-metamask-breaking-change-injecting-web3-7722797916a8

**Comment by hboon** [comment]
https://github.com/James-Sangalli/xcontract/issues/6 would provide a good test case.

**Comment by James-Sangalli** [comment]
@hboon this is supported in a branch on xcontract but the web3 beta api seems to be riddled with bugs, goes hand in hand with issue #877

**Comment by James-Sangalli** [comment]
@hboon this is dependent on the dapp itself, currently cryptokitties has this feature and it works without asking on our wallet (we probably need to upgrade web3 to get that to ask for permission)

**Comment by James-Sangalli** [comment]
@hboon another note, unless privacy mode is enabled on the client, the default way will continue. We could potentially add this feature in later

**Comment by hboon** [comment]
@James-Sangalli re-opening
