### ISSUE TITLE
Cache ENS lookups

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#911]
Maybe a simple one, in-memory from (name, networkId) to address. So when user make simple edits, we don't get repeated lookups?

**Comment by James-Sangalli** [comment]
@hboon you mean for when the user is sending to ENS multiple times within a short timeframe (i.e. when the app is running a process), like simply putting it into a var?

**Comment by hboon** [comment]
When the user types or paste "boon.thisisme.eth" hits backspace to become "boon.thisisme.et" then types a "h" or paste immediately again so it becomes "boon.thisisme.eth" triggering a second lookup in the same screen. Then they might cancel and then repeat again with the same address. Not too urgent I suppose :)

Can probably have a static var in `GetENSOwnerCoordinator` that is just a dictionary? If the key is (name, networkId), then we don't have to do any clean up when the user switch wallet or network. And because it's in-memory only, we don't have to worry about expiry (well, if it expires *while* the app is running... but that's a super low chance I suppose?)

**Comment by miang719** [comment]
@James-Sangalli bump
