### ISSUE TITLE
875 token factory cost much more(24 times more) gas on iOS than Android

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/alpha-wallet-ios#912]
create same contract, at almost the same time

Contract created from Android, Cost 0.005251958 ETH
https://ropsten.etherscan.io/tx/0x408dde295d3e3a71ff8df3e2033e099ad054ae682c178172f6577d72209ddd21

Contract created from iOS, Cost 0.126053136 ETH
https://ropsten.etherscan.io/tx/0x9013d3f1f11a61cba90fb63052b83abc8cfc90415c632b16eff3a69bb64fbe36

**Comment by James-Sangalli** [comment]
@hboon this appears to be related to how gas is calculated in the browser as regular transactions are unaffected. Investigating this further.

**Comment by James-Sangalli** [comment]
@hboon this appears to be related to how gas is calculated in the browser as regular transactions are unaffected. Investigating this further.
