### ISSUE TITLE
Rinkeby is freezing up

### ISSUE THREAD

**Issue by James-Sangalli** [AlphaWallet/alpha-wallet-ios#916]
Simply switch to rinkeby and you will see it

**Comment by hboon** [comment]
@James-Sangalli works for me (for wallets with and without transactions). Does it require a particular token to be in the wallet?

**Comment by James-Sangalli** [comment]
@hboon hit the transactions tab in rinkeby, it goes very slow on my phone at that point.

**Comment by James-Sangalli** [comment]
Turns out the key existed in the phone before the upgrade which safely queried the transactions. This is not an issue in current version.
