### ISSUE TITLE
need a search bar or better filter for the wallet page

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/alpha-wallet-ios#926]
Now I have more than 30 tokens in my wallet, hard to find the right one.

**Comment by hboon** [comment]
Yes, we can see if the built-in UI works with this. Eg. see the phone/contacts app.

**Comment by zhangzhongnan928** [comment]
> Yes, we can see if the built-in UI works with this. Eg. see the phone/contacts app.

Good idea, @farrahfazirah can start preparing the design. 

This will be done after iframe and Dapp browser projects.

**Comment by hboon** [comment]
I don't think there's much to design if we use the built-in UI though. Let me try out the built-in UI first to see if it works and we'll see if there's things we can tweak from there? Because if it can't be used, it might affect how the design can be tweaked.

**Comment by colourful-land** [comment]
> I don't think there's much to design if we use the built-in UI though. Let me try out the built-in UI first to see if it works and we'll see if there's things we can tweak from there? Because if it can't be used, it might affect how the design can be tweaked.

Sure, in your way,.
