### ISSUE TITLE
display issue when 721 token name is too long

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/alpha-wallet-ios#935]
![img_1873](https://user-images.githubusercontent.com/33795543/49288289-5bcd5a80-f4db-11e8-94a2-730dc7216014.jpg)

Can we make it change the text size automatically based on the length

**Comment by hboon** [comment]
Have added a fix so that it wraps both when expanded and collapsed, but when collapsed, it is still truncated because the token card's maximum height is set to the image's height.

But when expanded, it'll just wrap, like the description below the name.
