### ISSUE TITLE
TestFlight build 1.32 240, erc20 balance display issue 

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/alpha-wallet-ios#939]
https://etherscan.io/tx/0x598faafaba0f22c3c3563ea4832913afcc85e70ab6dc9d4cf357411670536e65

Balance display reduced correctly on 0xbc8dAfeacA658Ae0857C80D8Aa6dE4D487577c63
But balance display shows 0 on 0xFB83ED3ea8775537ce9a04dCe0e354edF9ee6658

![c26c3a9d-1905-4f99-a767-567d579f8b0f](https://user-images.githubusercontent.com/33795543/49324022-84e3fe80-f560-11e8-846f-2d5021c562b5.jpeg)

**Comment by hboon** [comment]
@james-sangalli Is it https://medium.com/@Bulleon_net/bulleon-promo-token-giveaway-7d202648a43c ? Look for "REDEEM YOUR BULLEON SHARE" in that page. It sounds like it's not supposed to be transferred as a normal ERC20 token, but you'd have to transfer them all to the DEX smart contract first to exchange for the "actual" BUL token.

---

https://etherscan.io/token/0x4f4d22ca77222ae3d51e308c9a8f0e564f98e77a?a=0xfb83ed3ea8775537ce9a04dce0e354edf9ee6658#readContract

balanceOf(0xFB83ED3ea8775537ce9a04dCe0e354edF9ee6658) is 0
but:
balanceOf(0xbc8dafeaca658ae0857c80d8aa6de4d487577c63) is 350000000000000000000

**Comment by zhangzhongnan928** [comment]
good, so it is the contract's issue not us.

Regards,
[image: AlphaWallet] <https://awallet.io/>

*Victor Zhang*

[image: AlphaWallet Github] <https://github.com/alpha-wallet> [image:
AlphaWallet Twitter] <https://twitter.com/Alpha_wallet> [image: AlphaWallet
Reddit] <https://www.reddit.com/r/AlphaWallet> [image: AlphaWallet Facebook]
<https://www.facebook.com/AlphaWallet/> [image: AlphaWallet Youtube]
<https://www.youtube.com/channel/UCPP12PQeQmQ4_6qXzNvZw-w/> [image:
AlphaWallet Linkedin] <https://www.linkedin.com/company/%CE%B1wallet/> [image:
AlphaWallet Weibo] <https://weibo.com/AlphaWallet>
Join our Telegram group. <https://t.me/AlphaWalletGroup>

**Comment by James-Sangalli** [comment]
Can confirm that other erc20 tokens are transferring, closing.
