### ISSUE TITLE
TeTestFlight build 1.32 240, wallet page display issue

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/alpha-wallet-ios#940]
After I transfer 1 erc875 token from address a to address b through magic link. A and b address on same mobile.
All the 875 721 token on A shows up in b as well, with 0 balance.
![6ae90419-3139-458d-a1b2-d940aa95b5b7](https://user-images.githubusercontent.com/33795543/49324162-71866280-f563-11e8-9ecb-c48a9b43c0bf.jpeg)
![e0096b8b-8b15-49b1-ac2a-55fe5cc7c456](https://user-images.githubusercontent.com/33795543/49324163-71866280-f563-11e8-981b-5630a52be33c.jpeg)

**Comment by hboon** [comment]
@zhangzhongnan928 does 

(A) only ERC 721 with 0 balance appear in b, or 
(B) does both ERC 721 and 875 tokens with 0 balances appear in b?

**Comment by zhangzhongnan928** [comment]
both 721 and 875


Regards,
[image: AlphaWallet] <https://awallet.io/>

*Victor Zhang*

[image: AlphaWallet Github] <https://github.com/alpha-wallet> [image:
AlphaWallet Twitter] <https://twitter.com/Alpha_wallet> [image: AlphaWallet
Reddit] <https://www.reddit.com/r/AlphaWallet> [image: AlphaWallet Facebook]
<https://www.facebook.com/AlphaWallet/> [image: AlphaWallet Youtube]
<https://www.youtube.com/channel/UCPP12PQeQmQ4_6qXzNvZw-w/> [image:
AlphaWallet Linkedin] <https://www.linkedin.com/company/%CE%B1wallet/> [image:
AlphaWallet Weibo] <https://weibo.com/AlphaWallet>
Join our Telegram group. <https://t.me/AlphaWalletGroup>

**Comment by James-Sangalli** [comment]
Covered from here on: https://github.com/AlphaWallet/alpha-wallet-ios/issues/1092
