### ISSUE TITLE
Dapp, https://multitoken.io/ isn't working in Dapp browser

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/alpha-wallet-ios#959]
It is used to work, I have bought some index before.

**Comment by James-Sangalli** [comment]
Their site is down.
<img width="537" alt="Screen Shot 2019-05-13 at 12 02 50 pm" src="https://user-images.githubusercontent.com/16630514/57591886-1c6d6480-7577-11e9-8bb8-a6f69eaa9944.png">
