### ISSUE TITLE
Can't connect to Ethereum Classic [ETC] Dapps - suspect faulty RPC node.

### ISSUE THREAD

**Issue by antsankov** [AlphaWallet/alpha-wallet-ios#960]
I tried to connect to:
- [P3C.io](https://p3c.io/use.html)
- [Saturn.network](https://saturn.network)

These are currently the 2 largest ETC dapps. Neither of them worked with Alphawallet. I suspect this has to do with the node being chosen [here](https://github.com/AlphaWallet/alpha-wallet-ios/blob/910a0b8f80ed521db2cb09f4c425fa12439c24dc/AlphaWallet/Settings/Types/Config.swift#L89) - can you change this to one of the nodes [here](https://github.com/kvhnuke/etherwallet/blob/9051f3240fe1297d2b783aee7224cc7a4fb6b5db/app/scripts/nodes.js#L133) specifically `https://web3.gastracker.io` which is the most stable.

**Comment by James-Sangalli** [comment]
Hi @antsankov, Thank you for finding this.

Turns out this is caused by an API change, we will look into adopting a new node that can support eth classic (thanks for listing some alternatives)

**Comment by antsankov** [comment]
Yes! I am happy to help, if you need any beta testing or have any questions
about ETC.
