### ISSUE TITLE
Automatically pickup partner contracts

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/alpha-wallet-ios#961]
When a user receives any of these token, it should automatically show up in the wallet. 
USDC
GUSD
USDO
TUSD
PAX
DAI

**Comment by hboon** [comment]
Couple of wallets with non-zero balances:

0x277aa00d6b807f04f910c7bb0d049749bb8a7e19 DAI
0xb384632Fe5757Fc8c53A228c25C93f3ce7562327 GUSD + PAX (but 1/100000000000000000 only)
0xf65e40968C9EC25b854F7572230EE399031174BB TUSD
0x41819f1418A734a2e1bAae14B9550c8Af4Ef6E31 USDC
0x04F06740D0f050B6af6358E0ddB4dC79f452dd87 USDO
