### ISSUE TITLE
Enhance UI/UX of the currency/asset search bar 

### ISSUE THREAD

**Issue by farrahfazirah** [AlphaWallet/alpha-wallet-ios#976]
When a user clicks on the search bar, an empty space appears in between the search bar and cards.

<div align="center"><img src="https://user-images.githubusercontent.com/20555752/50440652-28db8280-0932-11e9-9602-44c7d2beadec.jpg" height="350px" width="200px"></div>

<br>

Here is my suggestion below to improve the look and experience of the search bar. Ideally, the search bar should remain static when interacted by the user.

<br>

<div align="center"><img src="https://user-images.githubusercontent.com/20555752/50440869-0ac25200-0933-11e9-82ce-c6839a60cca0.png" height="550px" width="250px"></div>

<br>

Modifications:
- "Cancel" is removed and replaced with "x" icon. The "x" icon appears on the far right, inside the search bar when user clicks on the search bar.
- Replaced the search icon
- Changed the font type and colour
- Changed the UX copy of search bar
- Changed border radius of search bar

<a href="https://invis.io/ZPPRHSMUXQV">Please see this InVision board for the prototyping preview</a>

**Comment by hboon** [comment]
Done with #1337
