### ISSUE TITLE
Support xDAI bridging of DAI on eth to POA

### ISSUE THREAD

**Issue by James-Sangalli** [AlphaWallet/alpha-wallet-ios#981]
At the moment it is cumbersome for the user to do so, with TBML we can make it native and easy for the user. 

Dependent on #963

**Comment by zhangzhongnan928** [comment]
I tried https://dai-bridge.poa.network/, minted 0.5 xDAI,
https://blockscout.com/poa/dai/address/0xbc8dafeaca658ae0857c80d8aa6de4d487577c63/internal_transactions

**Comment by James-Sangalli** [comment]
related: https://github.com/AlphaWallet/contracts/pull/103

**Comment by James-Sangalli** [comment]
Will keep discussions in contracts repo
