### ISSUE TITLE
DApp localethereum.com 

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/alpha-wallet-ios#983]
![d67d6ab3-b3b8-4411-bcbd-fb443b6151a1](https://user-images.githubusercontent.com/33795543/50624121-d0227000-0f57-11e9-8b6e-981a2e3c8214.png)
Works in Android, but not working in iOS.
 It keeps loading, don’t popup the transection page.

**Comment by colourful-land** [comment]
@hboon  - do you know why the screen displays the word Trust? Also, I heard that metamask started to use a transaciton.arppove() function to request permission before sending, not sure if they are using this new interface.

**Comment by hboon** [comment]
Will have to check. What's a simple way to reproduce this?

**Comment by zhangzhongnan928** [comment]
@JamesSmartCell Andriod doesn't work either.

**Comment by hboon** [comment]
The reason being the app is providing an additional `gasLimit` dictionary. Metamask is happy with this, so we'll ignore `gasLimit` too (the value is already correctly provided as `gas` which we do read).

```
{
   "name" : "signTransaction",
   "object" : {
      "value" : "0x8ac7230489e80000",
      "to" : "0x867ffb5a3871b500f65bdfafe0136f9667deae06",
      "gasPrice" : "0x6422c400",
      "gasLimit" : {
         "s" : 1,
         "c" : [
            75000
         ],
         "e" : 4
      },
      "gas" : "0x124f8",
      "chainType" : "ETH",
      "data" : "0xf1e03d678988551c2e83424c9d6928c4e7afa02700000000000000000000000000000000000000000000000000000000f13967247af7e542d8c1f52f8e6fe8d3c7ff86e30000000000000000000000004b52133df7af5f05a858f4218e8cbdd66d9cd2520000000000000000000000000000000000000000000000008ac7230489e8000000000000000000000000000000000000000000000000000000000000000000640000000000000000000000000000000000000000000000000000000000001c20000000000000000000000000000000000000000000000000000000005c31d1ec000000000000000000000000000000000000000000000000000000000000001b11c0b0fa0de567a7ad28306a439830f413d46209ebbb205fcc70036887cc55e158d7726c312266663e861976e109f1f206a39a8536f9162b77d8cbb8cd27d0ff",
      "from" : "0xf13967247af7e542d8c1f52f8e6fe8d3c7ff86e3"
   },
   "id" : 8888
}
```

**Comment by hboon** [comment]
> @hboon - do you know why the screen displays the word Trust?

@colourful-land My mistake when making the TestFlight build. It cached and used an old version of the JavaScript embedded into the app browser. Should not happen again since we (and anyone new to the team) is unlikely to fetch older versions of the file anymore (though why it was ever possible is a bit worrying).

**Comment by hboon** [comment]
@JamesSmartCell maybe it's failing on Android for a similar reason (additional `gasLimit` dictionary).

**Comment by zhangzhongnan928** [comment]
Thanks, Boon,
Can we "fix" it, or should I speak to the DApp provider?

Regards,
[image: AlphaWallet] <https://awallet.io/>

*Victor Zhang*

[image: AlphaWallet Github] <https://github.com/alpha-wallet> [image:
AlphaWallet Twitter] <https://twitter.com/Alpha_wallet> [image: AlphaWallet
Reddit] <https://www.reddit.com/r/AlphaWallet> [image: AlphaWallet Facebook]
<https://www.facebook.com/AlphaWallet/> [image: AlphaWallet Youtube]
<https://www.youtube.com/channel/UCPP12PQeQmQ4_6qXzNvZw-w/> [image:
AlphaWallet Linkedin] <https://www.linkedin.com/company/%CE%B1wallet/> [image:
AlphaWallet Weibo] <https://weibo.com/AlphaWallet>
Join our Telegram group. <https://t.me/AlphaWalletGroup>

**Comment by hboon** [comment]
Yes, we can fix it ourselves. The fix is already in the master branch. We can of course still let them know though.
