### ISSUE TITLE
The border of new send receive buttons not smooth, clear

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/alpha-wallet-ios#986]
![wechatimg4](https://user-images.githubusercontent.com/33795543/50731596-f9cfd700-11a3-11e9-9010-1f7cd6edf356.jpeg)

it looks like, some glitch on the border.
<img width="1440" alt="screen shot 2019-01-06 at 11 14 24 am" src="https://user-images.githubusercontent.com/33795543/50731631-f25cfd80-11a4-11e9-88c3-e04007d45246.png">

**Comment by hboon** [comment]
Seems to be fixed. Re-open if required.
