### ISSUE TITLE
xDAI send page

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/alpha-wallet-ios#991]
![wechatimg3](https://user-images.githubusercontent.com/33795543/51092917-2bfebb80-17d8-11e9-9c5f-6467402acd36.jpeg)

**Comment by hboon** [comment]
@James-Sangalli should we rename all references to Ethereum across the app too? Eg. in this screen "Ethereum Blockchain" to "xDai Chain"?

**Comment by James-Sangalli** [comment]
@hboon yes, @colourful-land pretty sure they don't have ENS on dai yet, we could recreate it for them though

**Comment by James-Sangalli** [comment]
Closing with PR, added this specific issue to address the naming: https://github.com/AlphaWallet/alpha-wallet-ios/issues/997

**Comment by davecraige** [comment]
This confused me as well on my first day using the app.  Thank you for the help with this.
