### ISSUE TITLE
IFRAME should not allow images to be loaded over the internet

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#993]
At least one of the demo IFRAMEs linked to an image instead of embedding it and it was displayed correctly.

Input
---
IFRAME contains `img` tag with a `src` attribute that has a URL value

Expected
---
Image not displayed (/blocked)

Observed
---
Image displayed

**Comment by James-Sangalli** [comment]
@hboon deprecated?

**Comment by hboon** [comment]
Still valid. There's no hook to attach to for detecting when a remote image is being requested. Maybe we can use XSL to remove them like we did with <script> tags.

**Comment by hboon** [comment]
Implemented as part of TokenScript using web content blocking API.
