### ISSUE TITLE
TestFlight Build 1.34(250) HyperDragons transfer function fail 

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/alpha-wallet-ios#996]
Contract：0x7fDcD2a1E52F10C28cB7732f46393e297eCaDDa1

The transaction shows success on etherscan, but token  is still in my wallet
https://etherscan.io/tx/0xf179256b1de41040d4bdfd1683eecdb99977852cc904620758d1abf0000b7807
https://etherscan.io/tx/0x4f5c6ab9c280ccdaa4a38ea9e09eb018b43cf4b658ea0262fcbb17a825553cd3

Then I tried to transfer on opensea, transaction failed
https://etherscan.io/tx/0x11821153a3cbb90a31bd7ba700b657bab8ffe8d193951e9ac06dfdffee812fb7

At the same time, I tried Kitty, works fine.

**Comment by James-Sangalli** [comment]
@hboon having trouble identifying this issue since the code is not open source, seems that it is hitting revert in the other meaning that either he doesn't have the balance or there is some protection logic

**Comment by James-Sangalli** [comment]
@zhangzhongnan928 can you try this again?

**Comment by zhangzhongnan928** [comment]
Same issue 
Transection success but not token is transferred.

https://etherscan.io/tx/0xd47d416eece1828e8c44d25b373e203cb28e9fc1adfb6e29ea9b4c0c2b2464c1

**Comment by zhangzhongnan928** [comment]
https://etherscan.io/tx/0xededf62e30ec29df1016c1fe780b7dbe30f582591cd8e4abaa43c649ebb5df88

Not fixed

**Comment by James-Sangalli** [comment]
@hboon this might have to do with using transferFrom and safeTransferFrom in Erc721 however it is not clear since they have not opensourced their smart contract

**Comment by hboon** [comment]
@James-Sangalli I suppose one way to figure this is to generate the function hash for the 2 functions and manually go through a few of their transactions to see which one is in there?

**Comment by James-Sangalli** [comment]
No safeTransfer is implemented in hyperdragons.
